### ISSUE TITLE
inline-math

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#100]
1. Not moving together
![3](https://user-images.githubusercontent.com/15811943/73742900-0ad67900-4713-11ea-8596-7aa05dfd6b81.gif)

2. moving with cursor key ( <=, =>)
![2](https://user-images.githubusercontent.com/15811943/73743011-3fe2cb80-4713-11ea-9ac7-eb8ff50efef3.gif)

3. backspace at inline-math (can delete all markdown text except inline-math)
![1](https://user-images.githubusercontent.com/15811943/73743155-8b957500-4713-11ea-8c53-5b90c47bdcba.gif)

**Comment by Vanessa219** [comment]
Could tell me the reproduce steps of the problem 2?
