### ISSUE TITLE
增加点击链接时的回调函数

### ISSUE THREAD

**Issue by TobiasTao** [Vanessa219/vditor#1002]
### 你在什么场景下需要该功能？

目前支持的链接点击是内置的：https://github.com/Vanessa219/vditor/issues/926

我在基于 vditor 做一款vscode插件；而在vscode中打开文件与网站需要调用vscode的两个api。

希望可以像上传文件一样，增加一个回调函数

类似这样：

```javscript

linkClickHandler(link:string)

```

谢谢！

**Comment by cweijan** [comment]
我之前弄过, 给你参考.
```javascript
window.onclick = e => {
    if (!e.ctrlKey) {
        return;
    }
    let ele = e.target;
    if (ele.classList.contains('vditor-ir__link')) {
        ele = e.target.nextElementSibling?.nextElementSibling?.nextElementSibling
    }
    if(ele.classList.contains('vditor-ir__marker--link')){
       //  超链接被点击
    }
}
```

**Comment by TobiasTao** [comment]
> 我之前弄过, 给你参考.
> 
> ```js
> window.onclick = e => {
>     if (!e.ctrlKey) {
>         return;
>     }
>     let ele = e.target;
>     if (ele.classList.contains('vditor-ir__link')) {
>         ele = e.target.nextElementSibling?.nextElementSibling?.nextElementSibling
>     }
>     if(ele.classList.contains('vditor-ir__marker--link')){
>        //  超链接被点击
>     }
> }
> ```

谢谢大佬！
