### ISSUE TITLE
options.input无法监听点击toolbar link的输入内容

### ISSUE THREAD

**Issue by ajycc20** [Vanessa219/vditor#1004]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

正常在编辑器中键入内容，options.input(value)可以监听到 value值的变化

使用toolbar中的link标志插入链接， input(value)中未能监听到变动

### 期待的结果

对于toolbar中的link输入，input（value) 也可以监听到更改

### 截屏或录像

![image](https://user-images.githubusercontent.com/22912512/118753403-7bb58c00-b897-11eb-81df-2ae4b610be21.png)

### 版本信息

* 版本：npmjs.org  --> v3.8.4
* 操作系统：macOS Big Sur 11.3.1
* 浏览器：Google Chrome  版本 90.0.4430.212（正式版本） (x86_64)

**Comment by zhouxianjun** [comment]
+1
