### ISSUE TITLE
公式解析支持设置 `InlineMathAllowDigitAfterOpenMarker`

### ISSUE THREAD

**Issue by xmu714** [Vanessa219/vditor#1007]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

下面一段带公式的笔记片段，我用veditor有处公式解析不正常，其中后两处将两个公式中间的中文解析进去了。
这个问题是在vscode的插件[vscode-markdown-editor](https://github.com/zaaack/vscode-markdown-editor)里面发现的，作者说他直接用的veditor没有改过里面的代码，我试着在veditor的demo里面将这段笔记贴进去也是一样的有问题，但是思源笔记里面是正常的。

````````markdown
Test
这类极限主要包括三种未定型 $i^\infty, \  \infty^0, \  0^0$. 其中第一种是重点，后两种很少考察。

共同解法——指数化：$f(x)^{g(x)}=e^{g(x)\ln f(x)}$. 
这样可以将以上几种未定型全部转换为 $0 \cdot \infty$ 未定型，然后结合其他方法使用。

对于 $1^\infty$ 有特殊解法 $e^A$. 如果底数部分提供了1，那么可以简单计算。
````````

### 期待的结果

希望公式都能正常解析

### 截屏或录像

解析bug截图：
![BUG](https://xmu714-disk.oss-cn-shenzhen.aliyuncs.com/notepic/Screenshot_2021-05-18_21-39-10.png)

### 版本信息

这是作者的veditor版本：
![Ver](https://xmu714-disk.oss-cn-shenzhen.aliyuncs.com/notepic/Screenshot_2021-05-19_16-22-16.png)

### 其他信息

作者测试发现可以通过在$和0/1之间加空格解决，但是思源笔记可以不用这样就正常显示，所以还是希望能修复掉，因为我的blog里面行内公式$和内容之间不可以空格。

**Comment by xmu714** [comment]
这个似乎是思源里面的一项自定义功能：
![pic](https://xmu714-disk.oss-cn-shenzhen.aliyuncs.com/notepic/20210519165248.png)
但是这个特性能不能添加到veditor里面呢？

**Comment by 88250** [comment]
> 这个似乎是思源里面的一项自定义功能：
> ![pic](https://camo.githubusercontent.com/d00ae9bb9c4da830c139a9b9cfb405d11cd954072d8b05d3d7ce25b42c52fbfe/68747470733a2f2f786d753731342d6469736b2e6f73732d636e2d7368656e7a68656e2e616c6979756e63732e636f6d2f6e6f74657069632f32303231303531393136353234382e706e67)
> 但是这个特性能不能添加到veditor里面呢？

这个是 Lute 引擎上的一个选项 `InlineMathAllowDigitAfterOpenMarker`，Vditor 里如果没有暴露接口的话麻烦 PR 添加，谢谢。

**Comment by xmu714** [comment]
> > 这个似乎是思源里面的一项自定义功能：
> > ![pic](https://camo.githubusercontent.com/d00ae9bb9c4da830c139a9b9cfb405d11cd954072d8b05d3d7ce25b42c52fbfe/68747470733a2f2f786d753731342d6469736b2e6f73732d636e2d7368656e7a68656e2e616c6979756e63732e636f6d2f6e6f74657069632f32303231303531393136353234382e706e67)
> > 但是这个特性能不能添加到veditor里面呢？
> 
> 这个是 Lute 引擎上的一个选项 `InlineMathAllowDigitAfterOpenMarker`，Vditor 里如果没有暴露接口的话麻烦 PR 添加，谢谢。
> 
> https://github.com/88250/lute/blob/master/lute.go

啊这，我不太懂这个的代码，不知道咋提交PR，希望把这个选项提供一个可以配置的参数出来

**Comment by 88250** [comment]
@xmu714 好的，这个需要稍微等等，谢谢。

**Comment by Vanessa219** [comment]
可参见 https://ld246.com/article/1549638745630#options-preview-math
