### ISSUE TITLE
在旧版本中看见目录中存在大量空白或者奇怪的字符，

### ISSUE THREAD

**Issue by thinkido** [Vanessa219/vditor#1013]
新版本未测试，

### 编辑模式

* `ir` 即时渲染模式

### 截屏或录像
![image](https://user-images.githubusercontent.com/5847958/119283276-0e2aa680-bc6f-11eb-8a2e-0ac306e8c9df.png)

### 版本信息

* 版本：vditor@3.6.6
* 操作系统：win
* 浏览器：chrome

**Comment by HerbertHe** [comment]
这个奇怪的符号像是折叠的符号, 升级到新版本没有这个问题

**Comment by thinkido** [comment]
> 这个奇怪的符号像是折叠的符号, 升级到新版本没有这个问题, 应该是样式问题导致的

新版本也有这个问题。

**Comment by thinkido** [comment]
index.css 对应版本问题，搞定。
