### ISSUE TITLE
minus number at table(not important)

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#102]
![11](https://user-images.githubusercontent.com/15811943/73773758-59ead100-4748-11ea-8769-a0bd1c337b32.PNG)

any shortcut key?
vim style : 
  something+J: increase row
  K: decrease row
  H: decrease column
  L:  increase column

**Comment by Vanessa219** [comment]
alt+shift+delete : remove current column
alt+shift+enter: add column after current column
alt+delete : remove current row
alt+enter: add row after current row
