### ISSUE TITLE
列表项的粗体文字左侧空格会被清除

### ISSUE THREAD

**Issue by cweijan** [Vanessa219/vditor#1020]
模式: wysiwyg

````````markdown
- The book is **very** interesting
````````

期待的结果
- The book is **very** interesting

vditor的结果, 也就是解析后加粗字体左侧的空格被清除了, 在[demo](https://ld246.com/guide/markdown)那直接复制进去就可复现.
![image](https://user-images.githubusercontent.com/27798227/119962061-3f8dd400-bfd9-11eb-9baa-9fd7f741a977.png)

**Comment by 88250** [comment]
感谢反馈，后面会在 https://github.com/88250/lute/issues/149 中排查。

**Comment by 88250** [comment]
合并到 https://github.com/Vanessa219/vditor/issues/974 中。
