### ISSUE TITLE
严重bug：在输入文字的时候，光标很多时候会跑到编辑器的头部。

### ISSUE THREAD

**Issue by thinkido** [Vanessa219/vditor#1023]
### 编辑模式

* `ir` 即时渲染模式

### 描述问题
在输入几个文字之后，光标就立刻跑到市区的头部，这就导致后续撕的内容都是错乱的位置。

### 截屏或录像
[即时渲染模式光标总是跑到头部](https://reccloud.cn/u/0phq9ir)

### 版本信息

* 版本：vditor@3.8.4
* 操作系统：
* 浏览器：

**Comment by thinkido** [comment]
逻辑代码问题，放到vue项目中，自定义组件，v-model双向绑定导致的问题。

**Comment by seawenzhu** [comment]
怎么解决这个问题

**Comment by Elainemi1998abc** [comment]
我是谷歌浏览器不出现，edge 会出现，而且是有些电脑电脑会出现
