### ISSUE TITLE
切换全屏显示时希望可以动态更新 toolbar

### ISSUE THREAD

**Issue by kevinzhao2233** [Vanessa219/vditor#1026]
### 切换全屏显示时希望可以动态更新 toolbar

在评论区，内容比较小的地方只需要尽可能少的 toolbar 来满足基本的需求，但是倘若用户想在全屏时使用全功能的 toolbar，vditor 目前没有动态更新 toolbar 的方法。

### 描述最优的解决方案 

最好的应该是在动态设置 toolbar，点击全屏后把 toolbar 内容增加，关闭全屏时再回到简洁版的 toolbar。

### 描述候选解决方案

可以参考语雀的实现方式，本身有两个编辑器，一个简洁版，一个全功能版，点击全屏时弹出全功能版的，同时把书写的内容同步好。

![fullscreen](https://user-images.githubusercontent.com/42138464/120970747-68168a80-c79e-11eb-83cf-1abcb110dfd0.gif)

**Comment by Vanessa219** [comment]
工具栏是完全自定义的，可以使用 css 覆盖试一下
