### ISSUE TITLE
表格对齐问题

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#103]
![cellalignment](https://user-images.githubusercontent.com/15811943/73775477-90761b00-474b-11ea-8418-2b9d5760e5e4.gif)

**Comment by jakekwak** [comment]
another garbage?
enter, delete inside cell at wysiwig mode
![7](https://user-images.githubusercontent.com/15811943/73803079-4d389e00-4785-11ea-8bf1-ebe852f24942.PNG)

**Comment by 88250** [comment]
Thank you, the two problems will be fixed in v2.1.10, we will release this version soon.
