### ISSUE TITLE
_lutePath路径是否可以配置成本地路径呢？

### ISSUE THREAD

**Issue by poetwolf** [Vanessa219/vditor#1030]
### 编辑模式
* `sv` 分屏编辑预览模式

### 描述问题

1.看到页面加载的时候从cdn加载了一个lute.min.js文件，能否把这个lute.min.js放到项目中通过相对路径引入呢？
2.源码中有一个_lutePath路径怎么可以改成本地路径呢？

### 版本信息

* 版本：3.8.5
* 操作系统：ubuntu 18.04
* 浏览器：chrome

**Comment by Vanessa219** [comment]
可以的。直接参照 https://github.com/Vanessa219/vditor/blob/master/demo/index.js 即可
