### ISSUE TITLE
编辑器图片预览显示不正常

### ISSUE THREAD

**Issue by zhuyouzhufu** [Vanessa219/vditor#1037]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

![image](https://user-images.githubusercontent.com/34908518/124409115-46e39280-dd7a-11eb-8e11-fadba4058d17.png)

### 期待的结果

期待的结果是点击后图片占满整个屏幕 且 叠在所有的弹框之上

### 版本信息

* 版本：最新版
* 操作系统：Windows10
* 浏览器：谷歌浏览器

**Comment by Vanessa219** [comment]
可以自己重置一下 css 看看

**Comment by zhuyouzhufu** [comment]
![image](https://user-images.githubusercontent.com/34908518/124411730-b14b0180-dd7f-11eb-84fc-75ff05ac68c1.png)
![image](https://user-images.githubusercontent.com/34908518/124411865-ee16f880-dd7f-11eb-8a96-d5858a30ca45.png)
![image](https://user-images.githubusercontent.com/34908518/124411934-0f77e480-dd80-11eb-988c-6d3972b50152.png)

**Comment by zhuyouzhufu** [comment]
这个组件z-index可以调高一点，3真的太小了。随便一个组件为了保护自己的优先级都不止于设置一个个位数。希望编辑器越做越好。

**Comment by Vanessa219** [comment]
感谢建议
