### ISSUE TITLE
npm 上 3.8.5  缺少 dist/types

### ISSUE THREAD

**Issue by NateScarlet** [Vanessa219/vditor#1039]
### 描述问题

https://registry.npmjs.org/vditor/-/vditor-3.8.5.tgz

缺少 dist/types 导致类型错误

![image](https://user-images.githubusercontent.com/21083014/124425753-96868600-dd9b-11eb-81ec-bb5f1b233b3a.png)

3.8.4 正常

### 期待的结果

有 dist/types

### 截屏或录像

![image](https://user-images.githubusercontent.com/21083014/124425917-d77e9a80-dd9b-11eb-9097-c04b5b3a8a1b.png)

### 版本信息

* 版本：3.8.5

**Comment by Vanessa219** [comment]
fix https://github.com/Vanessa219/vditor/pull/1034/files

**Comment by Valen-Pony** [comment]
这个fix似乎还没发布到npm上?

**Comment by Vanessa219** [comment]
是的。正在整理，晚一点发布
