### ISSUE TITLE
new Vditor('vditor', options)的ID选择器可否变更为class选择器，某些复杂的业务场景可能会有2个及以上的编辑器引用

### ISSUE THREAD

**Issue by zhuyouzhufu** [Vanessa219/vditor#1045]
### 你在什么场景下需要该功能？
![image](https://user-images.githubusercontent.com/34908518/125221576-fb416380-e2fa-11eb-86d0-91fe0af7b45b.png)

以下是表现：
![image](https://user-images.githubusercontent.com/34908518/125221846-76a31500-e2fb-11eb-9a9d-02098dc6dc99.png)
![image](https://user-images.githubusercontent.com/34908518/125222009-c2ee5500-e2fb-11eb-9351-46c8fdc9dda6.png)
![image](https://user-images.githubusercontent.com/34908518/125222065-e31e1400-e2fb-11eb-8da6-30cfa98fae30.png)

**Comment by Vanessa219** [comment]
可以使用 dom

**Comment by Vanessa219** [comment]
https://ld246.com/article/1549638745630#id
