### ISSUE TITLE
数学公式不支持 \begin{equation}...\end{equation}分隔符

### ISSUE THREAD

**Issue by jihaihan** [Vanessa219/vditor#1046]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

````````markdown
\begin{equation}
m = \frac { m _ { 0 } } { \sqrt { 1 - v ^ { 2 } / c ^ { 2 } } }
\end{equation}
````````

### 期待的结果

能够正常解析数学公式

### 截屏或录像

![image](https://user-images.githubusercontent.com/993920/125407375-64ed6a80-e3ec-11eb-9df7-bfe62ebf876e.png)

### 版本信息

从在线demo测试的：https://b3log.org/vditor/demo/vue.html

**Comment by Vanessa219** [comment]
https://b3log.org/vditor/demo/advanced-math.html

katex 不支持，需要设置为 mathjax

**Comment by jihaihan** [comment]
非常感谢。
