### ISSUE TITLE
Angular集成Vditor后，在预览模式输入#自动添加一个无法删除的空格

### ISSUE THREAD

**Issue by Exclamation-mark** [Vanessa219/vditor#1056]
### 编辑模式

* `sv` 分屏编辑预览模式

### 描述问题

输入#号会自动添加一个空格，而且空格无法按退格键删除。
因为添加了多个空格，导致两个#号不能被解析为H2

### 截屏或录像

![动画](https://user-images.githubusercontent.com/18455767/127425690-70e9bd35-e19c-45f8-8ed1-d4b90352ab02.gif)

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

### 其他信息

[示例代码](https://github.com/Exclamation-mark/VditorAngularAntZorroDemo)

**Comment by 88250** [comment]
感谢反馈，在 https://github.com/Vanessa219/vditor/issues/1049 中处理。
