### ISSUE TITLE
IE兼容性问题

### ISSUE THREAD

**Issue by kailong321200875** [Vanessa219/vditor#1057]
### 描述问题

想请问下，内置的highlight.js版本现在是多少，因为highlight.js9以上的版本，好像都不支持IE11了，然后我现在用的vditor版本是2.8.6，看了更新记录，在前几个版本有升级了highlight.js。目前就导致IE11上无法使用。

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/blob/master/src/js/highlight.js/highlight.pack.js 

那可能需要你手动修改一下了。
