### ISSUE TITLE
options不能指定预览时点击图片放大的z-index

### ISSUE THREAD

**Issue by Exclamation-mark** [Vanessa219/vditor#1058]
### 你在什么场景下需要该功能？
如果在model或者抽屉中预览文档，点击图片，会全屏放大图片，图片的zIndex有可能会小于html的zIndex.

![动画](https://user-images.githubusercontent.com/18455767/127659195-cf4739a6-e8cf-4526-85dd-4dd07c731d82.gif)

### 描述最优的解决方案 
最好是像全屏编辑时可指定zIndex一样，也可以在预览图片时执行zIndex参数。

### 描述候选解决方案
无

### 其他信息
无

**Comment by Exclamation-mark** [comment]
当前图片放大的z-index是从1开始递增的。

**Comment by Vanessa219** [comment]
自定义 css 修改一下
