### ISSUE TITLE
vditor可以插入超级链接实现CodeX editor的这种效果吗？

### ISSUE THREAD

**Issue by Yakumo-Yukari** [Vanessa219/vditor#1059]
![QQ截图20210731181527](https://user-images.githubusercontent.com/12076232/127736805-fc4cfb04-6bb8-4389-83ae-2ca564c45951.png)

![QQ截图20210731182100](https://user-images.githubusercontent.com/12076232/127736853-b0420797-5806-40b1-ac10-b989d23d8a7e.png)

目标网站 https://codex.so/editor   

在编辑器插入超级链接后  会获得网址的 标题  logo  简介  都会展示出来

**Comment by Vanessa219** [comment]
vditor 有三个模式，你期望的是哪一个模式加入呢？

**Comment by Yakumo-Yukari** [comment]
> vditor 有三个模式

见即所得模式

感觉用在网站编辑器上在网站上显示这样的效果很不错

**Comment by Vanessa219** [comment]
编辑的时候感觉不是太有必要，最后展现的话可以使用。可参见 
https://ld246.com/article/1627769638186/comment/1627774984079#comments
