### ISSUE TITLE
<del> tag

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#106]
from https://guides.github.com/features/mastering-markdown/

1. not same
2. backspace can not delete  <del> tag. 

- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> supported

![12](https://user-images.githubusercontent.com/15811943/73811108-2dfa3a80-479e-11ea-9af5-eedc483264a7.PNG)

**Comment by 88250** [comment]
Copy-paste from HTML will convert HTML to Vditor dom, copy-paste from the plain text will convert text to Vditor dom.

In this case `del` tag will be treated as an inline HTML element, so the result is expected. I close this issue, welcome comment if you have for details on it.

**Comment by jakekwak** [comment]
I think I typed `<del>tags</del>`.  <del>tags</del> at this github page but <> tags <> at vditor.

**Comment by 88250** [comment]
The final markdown renderring result in Vditor is consistent with GitHub's, but in editing we should keep its sematic.
