### ISSUE TITLE
选中文字后浮窗toolbar自定义

### ISSUE THREAD

**Issue by squarehelius** [Vanessa219/vditor#1061]
### 你在什么场景下需要该功能？

快捷方式让用户选中后进行一些操作，就不用再点最上边的toolbar了
<img width="173" alt="Screen Shot 2021-08-03 at 10 51 09 PM" src="https://user-images.githubusercontent.com/1957418/128037096-ec8b5e16-71ec-446f-b74b-d571884b29e8.png">

**Comment by Vanessa219** [comment]
试试自定义 css 隐藏看看。目前没有这个接口
