### ISSUE TITLE
能给个社区账号，我没国内手机

### ISSUE THREAD

**Issue by zhihengGet** [Vanessa219/vditor#1062]
### 你在什么场景下需要该功能？

在没有国内手机的场景下

### 描述最优的解决方案 

最优的方案是 你给我一个账户
### 描述候选解决方案

开通美国手机

### 其他信息

xd

**Comment by Vanessa219** [comment]
Vditor 不需要社区帐号也可以正常使用，如果是测试上传的话，可以自己本地搭建一下。
