### ISSUE TITLE
如何配合云开发调用cloudbase.upload云存储功能？

### ISSUE THREAD

**Issue by thinkido** [Vanessa219/vditor#1067]
### 你在什么场景下需要该功能？
在云开发上使用云存储功能，调用语音开发功能，它不是使用简单的HTTP访问。是调用js-sdk对象接口cloudbase.upload

[云开发 CloudBase 上传文件 - 开发指南 - 文档中心 - 腾讯云](https://cloud.tencent.com/document/product/876/19372)

**Comment by Vanessa219** [comment]
目前仅支持 POST 请求，那可能需要自己修改一下  upload/index.ts 207 行附近的代码后自己进行编译了。
