### ISSUE TITLE
wysiwyg模式中使用引用式链接报错

### ISSUE THREAD

**Issue by Jerry379** [Vanessa219/vditor#1068]
### 编辑模式
* `wysiwyg` 所见即所得模式

### 描述问题
wysiwyg模式中使用引用式链接报错， Error: runtime error: invalid memory address or nil pointer dereference

````````markdown
[**gitlab**][gitlab]\n\n[gitlab]: https://gitlab.com/
````````

### 期待的结果

能正常显示链接

### 截屏或录像

![image](https://user-images.githubusercontent.com/22445390/130054059-5327cd17-86f2-41d1-a72c-12c02164b2e2.png)

### 版本信息

* 版本：v3.8.6
* 操作系统：macos 10.14.6 (
* 浏览器：chrome 92.0.4515.131

**Comment by 88250** [comment]
已在 https://github.com/Vanessa219/vditor/issues/1063 中处理。
