### ISSUE TITLE
edit-mode 想像GitHub这样，将 write 和 preview 分开，请问能实现吗？

### ISSUE THREAD

**Issue by ColinLQ** [Vanessa219/vditor#1069]
### 你在什么场景下需要该功能？

目前的切换实现是放在一个里面，切换不太方便。并且想直接写Markdown 只能采用分屏形式

![image](https://user-images.githubusercontent.com/23398373/130202936-04ba998a-115d-43ec-9a5a-ce425745d6a6.png)

### 描述最优的解决方案 

希望可以像GitHub这样，实现写和preview的快捷切换，请问能实现吗？

![image](https://user-images.githubusercontent.com/23398373/130202550-da56b3e5-8863-4681-9343-2d84372c5a99.png)

**Comment by 88250** [comment]
这样的话切换就不统一了，所以暂时不考虑了，感谢提议。

**Comment by ColinLQ** [comment]
请问是否有相关 api ，可以使我们自行实现这个功能？

**Comment by Vanessa219** [comment]
使用接口添加 toolbar， 然后结合 setPreviewMode

**Comment by ColinLQ** [comment]
@Vanessa219 感谢建议。顺便也提个建议：

- 建议将 `setEditMode` 方法暴露出来，这样可以更加灵活。
- 看到挺多自定义 `toolbar` 的需求，我也有同样需求，建议将 `toolbar` 上的方法暴露出来。

**Comment by Vanessa219** [comment]
这些依赖于编辑器实例，不太好暴露
