### ISSUE TITLE
How to uninstall vditor from vscode

### ISSUE THREAD

**Issue by ThejaswinS** [Vanessa219/vditor#1072]
Whenever i open README.md in vscode the vditor console is opening and i dont want to have .pls kindly tell how to uninstall vditor from device permanently.

**Comment by Vanessa219** [comment]
Sorry, this is just a web editor, not a vs plugin.

**Comment by EazycTee** [comment]
> Whenever i open README.md in vscode the vditor console is opening and i dont want to have .pls kindly tell how to uninstall vditor from device permanently.

I had the same problem and searched around for the answer to no avail. Then I remembered a completely open source version of VSCode: VSCodium, which doesn't come with Vditor (for now), so I suggest you try it.
ps. Vditor is fine, but I just like plaintext while handling .md files in VSC:)

**Comment by EazycTee** [comment]
link for VSCodium
https://github.com/VSCodium/vscodium

**Comment by ArlenLiu** [comment]
Vditor is too slow to use, that's too bad.

**Comment by GazaliAhmad** [comment]
Disable this plugin: Office Viewer(Markdown Editor).

**Comment by petedegraw** [comment]
Office Viewer(Markdown Editor) isn't enabled and I still have markdown files opening in the Vditor. How do you actually remove the plugin?

**Comment by sr4001** [comment]
> Disable this plugin: Office Viewer(Markdown Editor). My md files are now all opened in VS Code editor and not that **** Vditor. It was very frustrating because I have lots of extensions.
> 
> The basic Vs Code is so much better, and I don't need all the GUIs for bold, italics etc. That's why the file is called a Mark Down.

I realize it has been a while, but THANK YOU FOR THIS.  It was driving me crazy.
