### ISSUE TITLE
获取编辑器的值getValue会忽略最前面的回车

### ISSUE THREAD

**Issue by 312307025** [Vanessa219/vditor#1073]
### 编辑模式

* `ir` 即时渲染模式

### 描述问题

如下，官方demo里面，我在1前面有5、6个回车，1后面有2、3个回车。
实际返回来只有最后面带上一个回车，其他的都被忽略了。
![微信截图_20210903184756](https://user-images.githubusercontent.com/17807336/131994093-0ac85b85-da4b-4714-8024-8e01eedfcb07.png)

### 期待的结果
能完整的返回全部信息

### 版本信息

* 版本：3.8.6
* 操作系统：win10
* 浏览器：edge最新版本

**Comment by 88250** [comment]
你好，Markdown 回车不会保留的。

请参考这里的讨论 https://github.com/Vanessa219/vditor/issues/321#issuecomment-621075435
