### ISSUE TITLE
Java代码高亮样式，能否引入highlight.js官方的各种样式

### ISSUE THREAD

**Issue by poolye** [Vanessa219/vditor#1075]
### 疑惑一

HLJS渲染code，能否把HLJS官方的各种样式加入进来~比如github-dark等等

### 疑惑二

从编辑器getHTML得到的HTML，有办法是渲染后的HTML吗，比如代码块是渲染过的~

**Comment by 88250** [comment]
这个应该可以自行改进，我关闭了，感谢提议。
