### ISSUE TITLE
Potential security problem(s)

### ISSUE THREAD

**Issue by intrigus-lgtm** [Vanessa219/vditor#1076]
Hi, could you please create a new [draft security advisory](https://help.github.com/en/github/managing-security-vulnerabilities/creating-a-security-advisory) and 
[invite me](https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-collaborator-to-a-security-advisory) to it?
Any other private communication channel would also be fine.
I think I've found a potential security problem.

My emails to os@b3log.org always get rejected by your server, it seems.

**My disclosures always follow Github's 90-day [disclosure policy](https://securitylab.github.com/advisories#policy) (I'm not an employee of Github, I just like their policy).**

**Comment by 88250** [comment]
Please email to 845765@qq.com, thanks.

**Comment by intrigus-lgtm** [comment]
Done.
