### ISSUE TITLE
编辑器在未知情况下会插入非 UTF-8 字符

### ISSUE THREAD

**Issue by naiba** [Vanessa219/vditor#1077]
我这边有一个 RSS feed https://www.lifelonglearning.cc/feed/rss ，浏览器打开就提示包含非 UTF-8 字符，然后我把相关文章复制到 https://www.soscisurvey.de/tools/view-chars.php  都是有一个 `08` 的非 UTF-8 字符，不知道什么问题。

![image](https://user-images.githubusercontent.com/29243953/132274031-4292f0ff-dbb7-4e18-b7e7-9d2aeb52f564.png)

![image](https://user-images.githubusercontent.com/29243953/132274041-ab4e2e5e-c2b1-4895-8a97-25c31affebcc.png)

文章链接 https://www.lifelonglearning.cc/how-to-build-an-aggregation-trading-platform

**Comment by naiba** [comment]
使用的是默认编辑模式、Chrome、Mac OS、我现在是在保存到数据库前清理一下非 UTF-8 字符，临时解决这个问题，待会可能链接都正常了，只看图片吧

**Comment by 88250** [comment]
感觉应该不是 Vditor 写入的，在代码块里，猜测可能是原始文本里拷贝过来的吧。

**Comment by naiba** [comment]
是我手打的，不是复制的

**Comment by 88250** [comment]
好像是个退格键（Backspace），正常情况下应该不会出现在文本里，后面再观察看看如何重现，谢谢。

**Comment by 88250** [comment]
目前不清楚重现情况，先关闭了，谢谢。

**Comment by naiba** [comment]
> 目前不清楚重现情况，先关闭了，谢谢。

好的 虎年快乐
