### ISSUE TITLE
setValue 后光标会移到到最前面

### ISSUE THREAD

**Issue by ColinLQ** [Vanessa219/vditor#1078]
### 编辑模式

* `ir` 即时渲染模式

### 描述问题

每次 setValue 后光标会移到到最前面，即便内容是一样的。

### 期待的结果

期望内容一致时，光标位置不变，内容不一致时，光标移动到最后面

**Comment by seawenzhu** [comment]
遇到同样的问题， 期待答案

**Comment by Vanessa219** [comment]
setValue 后不会设置光标，是不是之后你又做了什么处理？

**Comment by dowdyboy** [comment]
vue3中也有该问题

**Comment by Vanessa219** [comment]
demo 中好像重现不了

**Comment by BoilTask** [comment]
@Vanessa219 我这复现了相同的表现

写了一个最小复现步骤环境：https://jsfiddle.net/qs7rL9y4/1/

我正式项目里是使用Vue3的工具链，是为了做一个图片自定义上传功能，参考思路：https://github.com/Vanessa219/vditor/issues/985

上传图片后我期望做一次替换来修改原先的内容，不过就会出现这个issues描述的，光标移动到了最前面

**Comment by BoilTask** [comment]
PS：本来我以为是替换文本后长度变短了（或者变长了）导致光标自动修正了，但是测试下来无论变长变短似乎都会导致光标回到开始位置

**Comment by sunny12308** [comment]
问题说的是setValue 不是insertValue呢~ @Vanessa219
