### ISSUE TITLE
编辑器初始化后自动聚焦，希望添加一个参数控制 

### ISSUE THREAD

**Issue by ColinLQ** [Vanessa219/vditor#1081]
### 你在什么场景下需要该功能？

类似论坛底部的留言评论，用户进来页面时，其实是不希望聚焦到编辑器的，只有用户点击后才聚焦

### 描述最优的解决方案 

希望添加一个 `autofocus` 参数，来控制是否自动聚焦。

### 描述候选解决方案

或者默认不要自动聚焦，开发者初始化后，自己通过调用 `focus()` 来聚焦。

**Comment by lixiang810** [comment]
同需要此功能

**Comment by Vanessa219** [comment]
默认是不聚焦的，可参看 https://ld246.com/guide/markdown。检查一下是不是哪里调用了 focus

**Comment by lixiang810** [comment]
但这个示例也会自动聚焦。除此以外，react 示例、vue示例和angular示例也存在自动聚焦的问题。

测试环境：Mozilla Firefox Nightly 97.0a1，iOS 15.1 下的 safari

链滴的解决方法似乎是这样的：拿一个按钮替换掉，点击的时候再初始化。在[我的项目](https://github.com/lixiang810/n2rv/blob/main/pages/index/components/Editor.tsx)里也是暂时这么解决的。

**Comment by Vanessa219** [comment]
用 chrome 打开  https://ld246.com/guide/markdown 看看

**Comment by lixiang810** [comment]
Microsoft Edge 96.0.1054.43 功能正常，不会自动聚焦。

似乎只有 blink 内核不会自动聚焦，webkit 和 gecko / quantum 内核会自动聚焦。

**Comment by lixiang810** [comment]
我也曾经尝试在 new Vditor() 时的 after 方法里加入 vditor.blur()，但是也没用，最后还是用我上面那个方案解决的。

**Comment by de1ck** [comment]
遇到同样的问题，有什么更好的办法处理吗？

**Comment by axiaoxin** [comment]
遇到个问题，iOS上html表单里面，safari打开没有自动聚焦，但是无法点击提交按钮，点击输入框后才能点提交按钮。。

**Comment by Vanessa219** [comment]
@de1ck 可以参看一的 Demo，运行后也是不会聚焦的，检查一下是不是有 setValue 之类的操作

@axiaoxin 提交按钮应该是单独的，和这个没有关系。

**Comment by know-that** [comment]
nuxtjs 第一次打开页面未聚焦，第二次打开页面（不刷新）就会聚焦

**Comment by Vanessa219** [comment]
两次打开有什么区别么？

**Comment by BearD01001** [comment]
同样有类似的问题，每次重新渲染都会自动聚焦，导致外部的输入框丢失焦点无法连续输入，也无法输入中文。
外部的输入框用来设置 vditor 的一些外部样式属性，比如添加标题、设置描述信息等，这些输入框的输入会重新渲染 vditor，每输入一个字符都会自动聚焦到重新渲染后的 vditor 上，导致无法连续输入，也无法输入中文。
Chrome Version 108.0.5359.94 (Official Build) (arm64)
Vditor Version 3.8.18

**Comment by Vanessa219** [comment]
> 同样有类似的问题，每次重新渲染都会自动聚焦，导致外部的输入框丢失焦点无法连续输入，也无法输入中文。 外部的输入框用来设置 vditor 的一些外部样式属性，比如添加标题、设置描述信息等，这些输入框的输入会重新渲染 vditor，每输入一个字符都会自动聚焦到重新渲染后的 vditor 上，导致无法连续输入，也无法输入中文。 Chrome Version 108.0.5359.94 (Official Build) (arm64) Vditor Version 3.8.18

中文应该是可以正常输入的，不能正常输入是指可以输入英文，中文输入不了？

**Comment by BearD01001** [comment]
> > 同样有类似的问题，每次重新渲染都会自动聚焦，导致外部的输入框丢失焦点无法连续输入，也无法输入中文。 外部的输入框用来设置 vditor 的一些外部样式属性，比如添加标题、设置描述信息等，这些输入框的输入会重新渲染 vditor，每输入一个字符都会自动聚焦到重新渲染后的 vditor 上，导致无法连续输入，也无法输入中文。 Chrome Version 108.0.5359.94 (Official Build) (arm64) Vditor Version 3.8.18
> 
> 中文应该是可以正常输入的，不能正常输入是指可以输入英文，中文输入不了？

是的，因为每输入按下一个按键，vditor 重新渲染后就会自动聚焦到 vditor 上，导致页面上其他会引起 vditor 重新渲染的输入框都无法输入中文，大概是这样：
![iShot_2022-12-08_10 58 11](https://user-images.githubusercontent.com/16353144/206345308-7e76dea2-9909-4290-90de-22051ff427a3.gif)

**Comment by Vanessa219** [comment]
查看一下按键是不是用了带聚焦的功能

**Comment by BearD01001** [comment]
> 查看一下按键是不是用了带聚焦的功能

https://b3log.org/vditor/demo/react.html
官方的这个 demo 也有类似的问题，一旦曾聚焦过 vditor 编辑器，再修改左侧代码时就会自动聚焦到编辑器，，导致无法正常编辑代码：
![iShot_2022-12-15_11 22 00](https://user-images.githubusercontent.com/16353144/207765001-7fefbeb6-5d51-4683-825e-f3d05a57367d.gif)

**Comment by Vanessa219** [comment]
聚焦后可以把焦点再移动到用户需要的地方。

**Comment by BearD01001** [comment]
> 聚焦后可以把焦点再移动到用户需要的地方。

但是这样带来的后果，就会使外部输入控件无法输入中文，即使手动把焦点移动回去，也会变成英文输入一样，无法正常输入中文，而且输入法的待选框会反复跳动，非常怪异

![iShot_2022-12-16_15 47 09](https://user-images.githubusercontent.com/16353144/208049281-c5414bdb-0acc-43e5-9435-87a8721e8aec.gif)

**Comment by Vanessa219** [comment]
没看明白光标为何会在代码框中，光标会跳到编辑器中。

**Comment by BearD01001** [comment]
> 没看明白光标为何会在代码框中，光标会跳到编辑器中。

因为 Vditor 好像在每次重新渲染后就会 focus 抢走光标，导致用户无法输入
复现步骤是这样的：
1. 打开官网例子：https://b3log.org/vditor/demo/react.html
2. 等待 Vditor 渲染完成
3. 鼠标点击 Vditor 输入区域聚焦出现输入光标
4. 点击右侧代码框修改代码

这样之后每次在代码框敲击任意一个按键，Vditor 就会抢夺光标，导致无法在代码框正常输入，特别是中文，完全无法输入。

**Comment by Vanessa219** [comment]
这个是用了第三方的代码功能 https://codesandbox.io/s/vditor-react-minimal-example-264b79?from-embed 。而且我无法重现你说的问题。
![QQ20221218-130928-HD](https://user-images.githubusercontent.com/970828/208282497-ac8bf788-0210-4198-bf8a-5b4db64aa331.gif)

**Comment by BearD01001** [comment]
> 这个是用了第三方的代码功能 https://codesandbox.io/s/vditor-react-minimal-example-264b79?from-embed 。而且我无法重现你说的问题。 

> 3. 鼠标点击 Vditor 输入区域聚焦出现输入光标
> 4. 点击右侧代码框修改代码

这个 codesandbox 还是可以复现，
首先要【先聚焦一下到 vditor 上】，然后再修改代码编辑器的代码，就会重现，vditor 好像存储了失去聚焦的事件，然后在【重新渲染】后就会抢夺聚焦 focus。
直接修改代码编辑器的代码是正常的。
![iShot_2022-12-18_13 30 22](https://user-images.githubusercontent.com/16353144/208283178-e9c8da24-6c17-4166-833e-c3804a60fe50.gif)

**Comment by Vanessa219** [comment]
哦，可以重现了。这个是不是浏览器的什么特性？代码里应该没有写 focus 呀。

**Comment by BearD01001** [comment]
> 哦，可以重现了。这个是不是浏览器的什么特性？代码里应该没有写 focus 呀。

那太奇怪了，我在 safair、edge、chrome 都重现了这个问题 orz
我试过将项目中 vditor 依赖中的全部 focus() 全局替换成 focus，之后确实没有这个问题了，所以应该还是在哪里调用了 focus 函数。

**Comment by BearD01001** [comment]
被我找到咯～，每次 re-render 之后都会调用这个 toggle 函数
<img width="424" alt="image" src="https://user-images.githubusercontent.com/16353144/208623699-7e0591a6-8836-450e-b53c-7a10ac89bf59.png">

从源码中定位应该是这里：
https://github.com/Vanessa219/vditor/blob/6ad1713a68ebc34129aa606422f64badbf6ab93e/src/ts/outline/index.ts#L42

**Comment by BearD01001** [comment]
看 getSelection() 返回的 focusNode 是否为 vditor 元素

**Comment by Vanessa219** [comment]
这个是大纲的，demo 里面没有对大纲进行渲染。

**Comment by BearD01001** [comment]
> 这个是大纲的，demo 里面没有对大纲进行渲染。

那很奇怪，我项目中的 vditor 也没有渲染大纲，但是确实触发了这个函数 😳

**Comment by Vanessa219** [comment]
我这里不会触发，你再看看是不是调用了其他方法。

https://user-images.githubusercontent.com/970828/208668709-417184f2-ea17-4c4f-9aaf-da2cc1ec2671.mp4

**Comment by BearD01001** [comment]
> 我这里不会触发，你再看看是不是调用了其他方法。
> 
>  QQ20221220-203503-HD.mp4

只有在 vditor 的 react 组件【重新渲染】的时候才会触发的，比如在 react 中改了 vditor 的样式类，就会触发。

**Comment by BearD01001** [comment]
猜测应该是因为这个 getSelection() 是全局的，即使当前用户光标并不是聚焦在 vditor 这边，但是 getSelection().rangeCount 也是大于 0 的，所以进行了 focus() 动作

**Comment by BearD01001** [comment]
定位到问题了，在这个 setEditMode 函数中，无论是否开启 outline，都会调用 toggle 函数，而又该函数中的 focus 调用之前没有判断当前用户聚焦在 vditor，所以就强制进行聚焦了，跟用户抢光标。

https://github.com/Vanessa219/vditor/blob/c27e6518eb0c56aff7a85567293d8151b554655d/src/ts/toolbar/EditMode.ts#L148

已经提交了相关 PR，劳烦 Review 看看 😁：
https://github.com/Vanessa219/vditor/pull/1342

**Comment by Vanessa219** [comment]
已经 merge
