### ISSUE TITLE
加入使用 React Hook 的示例代码

### ISSUE THREAD

**Issue by lixiang810** [Vanessa219/vditor#1082]
#1080 
`React 16.8` 更新加入了 Hook 功能，使原有的类组件不再那么流行，函数式组件大行其道。函数式组件无法调用类组件的生命周期方法，而需要以 Hook 取而代之。类组件，以及组件的生命周期方法对新学习 React 的开发者而言已是比较陌生的概念。因此希望更新原有的 React 代码示例为函数式组件+ hook 的示例，或新增一示例。

**Comment by 88250** [comment]
欢迎 PR。
