### ISSUE TITLE
Security vulnerability

### ISSUE THREAD

**Issue by pwntester** [Vanessa219/vditor#1084]
Hello,

The GitHub Security Lab team has found a potential vulnerability. Please create a Security Advisory and invite me (pwntester) in to further disclose and discuss the vulnerability details and potential fix. Alternatively, please add a Security Policy containing a security email address to send the details to.

If you prefer to contact us by email, please reach out to securitylab@github.com with reference to <GHSL-ID-HERE>.

Kind regards,
Alvaro Muñoz
GitHub Security Lab

**Comment by 88250** [comment]
Hi, please email 845765@qq.com, thank you.
