### ISSUE TITLE
使用 method.min 的 preview渲染数学公式 频繁出现 katex is not defined

### ISSUE THREAD

**Issue by Taotao2Tingbao** [Vanessa219/vditor#1088]
### 描述问题

使用MathJax无问题， 使用Katex频繁出现 katex is not defined, 发现出现错误时没有请求字体文件，正常时会请求字体文件
````````markdown
###### 题目描述
> 计算 $ a + b $ 的值。
###### 输入描述
> 输入两个整数 $ a $ 和 $ b $。
###### 输出描述
> 输出一个整数 $ a + b $。
````````

### 期待的结果
希望正确渲染Katex

### 截屏或录像
![image](https://user-images.githubusercontent.com/71547744/136578476-eec0674b-8419-49c8-9520-34f8478905ec.png)

### 版本信息

* 版本：3.8.7
* 操作系统：Mac OS 10.15.7
* 浏览器：Chrome 94.0.4606.81

**Comment by Vanessa219** [comment]
可以描述一下重现的步骤么？Demo 里面是正常的
![image](https://user-images.githubusercontent.com/970828/136586498-ec9c8e75-5e42-4426-bcaf-7287e2b8e790.png)

**Comment by Taotao2Tingbao** [comment]
可能是我使用了自定义的cdn，默认真的没有问题，可是为什么啊？

**Comment by Vanessa219** [comment]
cdn 用的是 dist 里面的么？

**Comment by Taotao2Tingbao** [comment]
是的

**Comment by subinghong** [comment]
> 加载katex.min.js后，katex对象并没有挂载到window对象上，不知道为什么，于是我修改了katex.min.js, 直接把katex对象挂载到了window对象上，一点问题都没有了

katex.min.js加载的时候会检测有没有存在全局函数define，有这个函数的时候katex就不会挂载到window对象上，你是不是跟我一样，使用了requirejs。

**Comment by Vanessa219** [comment]
没加载的话为什么会存在 katex，是变量冲突还是已经加载过了？

**Comment by subinghong** [comment]
引入AMD模块加载工具requirejs后，再引入katex.min.js，katex就不会挂载到window对象上。
而是需要使用requirejs的 define 或 require 方法加载：
`
define(['/pathto/katex.min.js'],function(katex){ alert(katex)});
`
或者
`
requirejs(['/pathto/katex.min.js'],function(katex){ alert(katex)});
`
引入requirejs后，vditor直接使用全局引用katex时，应该会读取到undefined。

**Comment by Vanessa219** [comment]
虽然不太理解为什么引入也不会挂载，但感觉可以先加载 katex.min.js

**Comment by subinghong** [comment]
我上面的意思不是引入也不会挂载。
不知道你有没有了解过 [requirejs](https://requirejs.org/)，requirejs 是js模块化工具，使用requirejs来加载js模块，可以避免引入全局变量。
因为我是使用requirejs来加载vditor的，而后续viditor在自动加载katex.min.js时，katex.min.js里面的代码检测到当前环境有requirejs模块化加载环境（存在全局函数 define 和 require ），就会避免将katex自己引入到全局，vditor内部如果还是直接用全局的katex来调用的话，就会调用不到katex。
虽然可以像下面这样自己加载katex并挂载到window对象上来避免出现 katex is not defined 错误，但如果vditor能内部兼容下，那就更好了。

```
require([‘https://unpkg.com/vditor/dist/index.min.js’,'https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.js']
     ,function(Vditor,katex){
    if(katex){
        window.katex=katex;
    }
var editor=new Vditor(‘vditor’, {});
);
```

**Comment by Vanessa219** [comment]
Vditor 不会引入 requirejs，可能没有办法在内部进行兼容。而且除了 katex 外，其他渲染器也是用的全局变量。

**Comment by subinghong** [comment]
viditor或许可以在 addScript 的时候判断下是否有requirejs环境，有的话就用require方法的方式代替
```
if( !window.katex && "function"==typeof define && define.amd && "function"==typeof require){
    //使用requirejs加载katex
    require([`${options.cdn}/dist/js/katex/katex.min.js`],function(katex){
        window.katex=katex
    });
}else{
    //没有requirejs环境，使用addScript添加katex
    addScript(...)
}
```

**Comment by Vanessa219** [comment]
不添加了，能否让 katex 兼容一下。

**Comment by subinghong** [comment]
> vditor或许可以在 addScript 的时候判断下是否有requirejs环境，有的话就用require方法的方式代替
> 
> ```
> if( !window.katex && "function"==typeof define && define.amd && "function"==typeof require){
>     //使用requirejs加载katex
>     require([`${options.cdn}/dist/js/katex/katex.min.js`],function(katex){
>         window.katex=katex
>     });
> }else{
>     //没有requirejs环境，使用addScript添加katex
>     addScript(...)
> }
> ```

这个方案也不需要vditor引入requirejs，把上面几行兼容代码稍作修改放到 mathRender.ts中的addScript里面应该就可以了

**Comment by subinghong** [comment]
如果不能在mathRender.ts中添加兼容加载方式，那也没办法了，只能自己加载katex并挂到window对象上
