### ISSUE TITLE
如何通过js改变字体颜色和背景颜色

### ISSUE THREAD

**Issue by Jasstin** [Vanessa219/vditor#1095]
### 你在什么场景下需要该功能？

![image](https://user-images.githubusercontent.com/20336321/137661554-bfcb44ea-94cf-4468-ae8f-456035f40960.png)
现有需求通过通过点击快捷键可以更改选中的颜色。查看api，找到了updateValue的方法，尝试了设置font和style都只能更新文字。看了其他的相关issue，lute目前只会提取问题内容。
但是，下载了思源app，看见里面是支持的。
![image](https://user-images.githubusercontent.com/20336321/137661891-ebba5553-88ec-4a74-bd5e-a63cc40a9bb2.png)

### 描述最优的解决方案 

希望能提供相关的toolbar快捷项或者methods到vditor的开源版本

**Comment by 88250** [comment]
Vditor 用的是标准 Markdown 解析渲染，思源用的是 kramdown 来实现行级和块级属性。

这个比较复杂，如果你有空的话可以看下 Lute 的相关代码，我关闭了，谢谢。

**Comment by Fuxi-zy** [comment]
@Jasstin 不知道可否有解决这个问题 刚好需要这个功能😂
