### ISSUE TITLE
存在 XSS

### ISSUE THREAD

**Issue by wh0am1i** [Vanessa219/vditor#1096]
payload:
```
[<img src=x onerror=alert(1)>]()
[<video src=x onerror=alert(1)>]()
```
![result](https://user-images.githubusercontent.com/49847986/138019856-170f5606-59a6-4a5a-81ba-e2b3a8678951.jpg)

**Comment by wh0am1i** [comment]
啥时候能够部署呢

**Comment by 88250** [comment]
@wh0am1i 下次发版的时候会部署。
