### ISSUE TITLE
Use English as an international default

### ISSUE THREAD

**Issue by aleon1220** [Vanessa219/vditor#1108]
### 编辑模式
Thank you so much for your plugin. I would really like to continue using it. 
Could you add internationalization and English specially as the international default?

I have a hard time following the options as I don't know this language.

thanks

God bless

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
````````

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

**Comment by Vanessa219** [comment]
Thank you, but I think Chinese is also an international language.

**Comment by aleon1220** [comment]
> Thank you, but I think Chinese is also an international language.

Usually, most of the software is written in English. 
Would you consider having an English translation?

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/blob/master/README_en_US.md

**Comment by gh-interests2** [comment]
If you want this plugin to succeed you need to enable English as default. I just disabled it as I could not figure out how to get to an English language setting after hours of trying.

**Comment by Vanessa219** [comment]
This is not a plugin. The language can be set using `options.lang`.

**Comment by gh-interests2** [comment]
There are plenty of other markdown editors whose advocates are not ridiculous enough to consider Chinese "an international language". I am not wasting any more time on this nonsense.

**Comment by 88250** [comment]
@gh-interests2 Thanks, and good luck finding a project that works for you.

**Comment by gh-interests2** [comment]
Yes and good luck finding a userbase with such ridiculous conceits.

**Comment by 88250** [comment]
@gh-interests2 你好，我们已经尽量提供了英文文档和对英文用户的支持。如果你觉得我们在国际化方面有什么做得不够好的地方，欢迎贡献改进，而不是在这里用“如此荒谬的自负”来指责我们。

除此以外，我作为一个中国人，对该项目使用中文文档和中文注释感到自豪。但显然我也不希望这是该项目的短板，所以我们需要更多国际友人参与来帮助我们一起改善这个项目，谢谢。

**Comment by gh-interests2** [comment]
Exactly. Good luck. :D

**Comment by CofinCup** [comment]
我认为可以在安装界面加一个选择支……这样就可以不default English且默认中文。
I believe developers can add a choice when installing...Default Chinese & English Convenience can be both achieved then.

**Comment by PRINSIS** [comment]
Can PRINSIS be so transparent, that MAT. PAT. TERNAL. WHERE ARE NOT GOING WITH KINGSIS:
        FRIEND OR FOE, LENDERS AND BORROWERS, ROW, ARRAY?
THAT BEING ROMANS THAT ARE COUNTRYMEN. CONTRIMENT MAYBE THE QUEEN  IS NOT ADDRESED as!

**Comment by aleon1220** [comment]
> 你好，我们已经尽量提供了英文文档和对英文用户的支持。如果你觉得我们在国际化方面有什么做得不够好的地方，欢迎贡献改进，而不是在这里用“如此荒谬的自负”来指责我们。
> 
> 除此以外，我作为一个中国人，对该项目使用中文文档和中文注释感到自豪。但显然我也不希望这是该项目的短板，所以我们需要更多国际友人参与来帮助我们一起改善这个项目，谢谢。

Not everyone knows Chinese. Dont worry plugin removed...

**Comment by HengCC** [comment]
Not everyone knows english too,So need more capable people to improve it instead of blaming others .
