### ISSUE TITLE
md中输入网址后预览模式不显示端口号

### ISSUE THREAD

**Issue by Jerry379** [Vanessa219/vditor#1109]
### 编辑模式
* `wysiwyg` 所见即所得模式

### 描述问题
md中输入网址后预览模式不显示端口号
````````markdown
http://192.168.0.1:8080
````````
显示的是`http://192.168.81.39`
### 期待的结果

预览模式显示完整链接
http://192.168.0.1:8080

### 版本信息

* 版本：3.8.6
* 操作系统：macos 10.14.6
* 浏览器：chrome

**Comment by 88250** [comment]
你好，这个问题我这里重现不了， 先关闭了，如果你有空麻烦详细描述一下重现步骤，谢谢。
