### ISSUE TITLE
数学能否用上 mathlive 或者 mathquill?

### ISSUE THREAD

**Issue by glennhanks** [Vanessa219/vditor#1110]
### 你在什么场景下需要该功能？

VDITOR 已经非常完美了。如果数学能实现真正意义上的所见即所得，就太好了，特别是对于长公式，复杂公式，如果后期修改，能**直接**点击到正确的位置进行修改就太好了，对于用来写笔记的人来说，省心省力太多。

### 描述最优的解决方案 

mathlive 或 mathquill 好像可以

### 描述候选解决方案

用 mathlive 或 mathquill 取代或者结合 katex 不知道是否可行。

**Comment by Vanessa219** [comment]
mathlive 感觉很棒，后续会抽空进一步调研验证。

**Comment by glennhanks** [comment]
> mathlive 感觉很棒，后续会抽空进一步调研及验证其渲染效果、性能、兼容性等。从而再评估是否可行。
> 
> 目前发现直接拷贝 https://katex.org/ 上的公式到 mathlive 上，两者显示不一样，如果替换的话，数据可能无法进行兼容。

  谢谢哦！

**Comment by Vanessa219** [comment]
由于兼容性问题，目前就先不考虑了。感谢建议。

**Comment by ninesunqian** [comment]
我试了几个复杂的公式，发现基本没问题。兼容性问题，估计是一些宏打开或关闭的问题，用用户发现这问题的时候，基本能用latex 直接写了。我觉的可以引入mathlive 或 mathquill 帮助。如果没时间，我可以考虑帮忙。只是javascript不太专业，进度可能慢一些。

**Comment by Vanessa219** [comment]
以前看了，显示方面不一致。如果目前可以到达一直的话，欢迎 PR。
