### ISSUE TITLE
请问渲染markdown文章时，如何处理xss?

### ISSUE THREAD

**Issue by XGiton** [Vanessa219/vditor#1115]
### 编辑模式

* `ir` 即时渲染模式

### 描述问题

编写markdown时，添加了`<button>abc</button>`内容，在编辑器中不会显示按钮，但是当我用如下方法渲染到页面时，按钮还是会出现，是否是我使用方法错了，请问应该怎么处理？

```
import VditorPreview from 'vditor/dist/method.min';

VditorPreview.preview(contentEl, markdownContent);
```

### 截屏或录像

![image](https://user-images.githubusercontent.com/7584071/140988136-96e96801-08a9-45a4-b4df-56fe8e2a5148.png)

### 版本信息

* 版本：3.8.7
* 操作系统：macOS
* 浏览器：chrome

**Comment by 88250** [comment]
你好，`<button>` 是不敏感的 HTML 元素，不涉及 XSS 吧。
