### ISSUE TITLE
vditor怎么在vue中的替换tui-editor无法渲染啊啊啊

### ISSUE THREAD

**Issue by JingWZeng** [Vanessa219/vditor#1116]
![impicture20211117101910.png](https://b3logfile.com/file/2021/11/impicture_20211117_101910-9ad2c68e.png)这个vditor对象不见了，。这个是我在demo上写的，没问题可以正常渲染，但是在老项目上就是不行，只显示了version，F12检查元素那个div里面并没有这个组件。这到底是咋回事emmmm，代码我检查了好几遍，并没有错，该引进的scss也引进来了。是vue2项目

**Comment by JingWZeng** [comment]
![impicture_20211117_110957](https://user-images.githubusercontent.com/88088364/142127667-df33aed9-5d92-43de-9223-747614d329fc.png)
内网环境下，这个包本身还是引用了cdn，所以没办法渲染

**Comment by 88250** [comment]
请参考 https://github.com/Vanessa219/vditor/issues/1030
