### ISSUE TITLE
工具栏在固定的状态下，置顶显示时，工具栏位置会出现问题

### ISSUE THREAD

**Issue by 7h3R0ad** [Vanessa219/vditor#1117]
### 编辑模式

使用版本：Vditor 3.8.6

`wysiwyg` 所见即所得模式 + `ir` 即时渲染模式 + `sv` 分屏编辑预览模式
三种模式均遇到问题了

### 描述问题
编辑器初始化的options中， 配置了 工具栏固定，即
```js
toolbarConfig: {
	pin: true
},
```
再点击全屏显示时，toolbar 显示位置存在问题，并没有在页面上置顶显示。

### 期待的结果

期待在工具栏固定的情况下，点击全屏显示，工具栏依然会置顶。

### 截屏或录像
在固定了工具栏但是没点击全屏按钮的时候页面布局
![image](https://user-images.githubusercontent.com/44728964/142343534-8ad45d1a-0b37-4e02-a7bc-306054d31a4a.png)

当点击全屏按钮之后，工具栏的位置
![image](https://user-images.githubusercontent.com/44728964/142343201-00c7f654-536e-4163-80ef-315c8017ad44.png)

### 版本信息

* 版本：3.8.6
* 操作系统：Windows10
* 浏览器：Chrome 96

**Comment by 7h3R0ad** [comment]
[问题与849相同](https://github.com/Vanessa219/vditor/issues/849)

**Comment by Vanessa219** [comment]
这个使用了 position:sticky, 你可能需要调整一下外部的 css
