### ISSUE TITLE
显示异常

### ISSUE THREAD

**Issue by ggb6070** [Vanessa219/vditor#1119]
### 编辑模式

* `ir` 即时渲染模式

### 描述问题

````````markdown
元字符 ^（和数字 6 在同一个键位上的符号）和 $ 都匹配一个位置，这和\\b 有点类似。^ 匹配你要用来查找的字符串的开头，$ 匹配结尾。这两个代码在验证输入的内容时非常有用，比如一个网站如果要求你填写的 QQ 号必须为 5 位到 12 位数字时，可以使用：^\\d{5,12}$。
````````

### 截屏或录像

![Snipaste_2021-11-23_18-04-08](https://user-images.githubusercontent.com/41104132/143004904-9ca3cddf-680c-4ae8-bbd0-169c928f88a5.png)

### 版本信息

* 版本：v3.8.7
* 操作系统：win10
* 浏览器：firefox93.0

**Comment by 88250** [comment]
`$foo$` 是 Markdown 行级数学公式语法。
