### ISSUE TITLE
时序图再打开渲染失败

### ISSUE THREAD

**Issue by wylnevergiveup** [Vanessa219/vditor#1127]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

1：编辑好md时序图，并保存
![image](https://user-images.githubusercontent.com/60908543/143844366-5762c18a-9d52-491e-966f-23194aa4dd5a.png)

2：再次打开md，在确保接收数据正确的情况下，vditor渲染内容错误
![image](https://user-images.githubusercontent.com/60908543/143844563-96660f22-b6dc-4ca2-bf57-3c3c3a16926e.png)
``mermaid,sequenceDiagram,小程序 ->> 小程序 : wx.login()获取code,小程序 ->> + 服务器 : wx.request()发送code,服务器 ->> + 微信服务器 : code+appid+secret,微信服务器 -->> - 服务器 : openid,服务器 ->> 服务器 : 根据openid确定用户并生成token,服务器 -->> - 小程序 : token,``,,
代码如下：
![image](https://user-images.githubusercontent.com/60908543/143844794-4bb78f73-399f-4969-a503-b2c8422fc597.png)

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
````````

### 期待的结果

直接展示渲染好的流程图

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

**Comment by Vanessa219** [comment]
你数据返回的 md 是什么？应该是返回的 md 错误造成的

**Comment by Vanessa219** [comment]
没问题的话我现关闭了
