### ISSUE TITLE
markdown渲染时无法渲染

### ISSUE THREAD

**Issue by MUOU-HANG** [Vanessa219/vditor#1138]
### 编辑模式

全部存在

### 描述问题

markdown无法渲染，初步排查可能是  `https://cdn.jsdelivr.net/npm/vditor@3.8.7/dist/js/lute/lute.min.js`文件出了问题，cdn上引用的资源无法找到

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
````````
![image](https://user-images.githubusercontent.com/47207583/146724325-c7fe5839-0752-47a8-a879-964809290beb.png)

**Comment by varHarrie** [comment]
https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js
貌似都无法访问了

**Comment by yuqingvile** [comment]
怎么说？我也遇到这问题

**Comment by varHarrie** [comment]
临时方案，替换源码：`cdn.jsdelivr.net/npm` 为 `unpkg.com`

**Comment by yuqingvile** [comment]
有没有升级修复包

**Comment by 88250** [comment]
应该是 jsdelivr CDN 证书校验有问题，现在好像恢复了。

**Comment by 88250** [comment]
为稳定起见，建议参考 [API options](https://github.com/Vanessa219/vditor#options) 章节，将 CDN 切换为自建的：

![image](https://user-images.githubusercontent.com/873584/146747846-21348931-0b6b-458a-afa8-9dfb14c17a88.png)
