### ISSUE TITLE
请求在 Vditor.preview 模式下新增 Ant Design 模式

### ISSUE THREAD

**Issue by kamaellee** [Vanessa219/vditor#1139]
### 你在什么场景下需要该功能？

```
<template>
  <div id="vditorPreview"></div>
</template>

<script lang="ts" setup>
  import Vditor from "vditor";

  Vditor.preview(
      document.getElementById("vditorPreview") as HTMLDivElement,
      props.value,
      {
        mode: "light",   <-------- 此处
        hljs: { style: "github" },
      }
    );
  });
</script>
```

### 描述最优的解决方案 

目前 preview 只支持 light 或 dark 模式，但在编辑器中有 Ant Design 模式，所以请求新增 Ant Design 模式。

### 其他信息

暂时不知道是否有其它 preview 实装的方式，需求是实现带有 link 显示为蓝色带下划线的预览模式，谢谢。

**Comment by Vanessa219** [comment]
这个是深色和浅色模式， ant 是属于图标，可使用 icon 进行设置

**Comment by kamaellee** [comment]
抱歉，可能是表达不够清晰，我附图说明一下。
![image](https://user-images.githubusercontent.com/74295299/147053550-a175ee0f-0b8a-4f72-a068-6b5f406851f2.png)
![image](https://user-images.githubusercontent.com/74295299/147053566-fb9614e5-8f57-4219-aac0-a39b7fdd4e05.png)
![image](https://user-images.githubusercontent.com/74295299/147053574-8aca476e-1708-43ec-8087-34174f10913a.png)

**Comment by kamaellee** [comment]
补充说明：这是 preview 目前支持的模式，
使用的版本：3.8.10
环境：
vue 3.2.6
typescript
script setup

![image](https://user-images.githubusercontent.com/74295299/147053844-641addb4-b527-473d-8229-045a96c60d87.png)

**Comment by Vanessa219** [comment]
这个是内容主题的，无法适配编辑器外观，可参看 https://ld246.com/article/1549638745630#%E4%B8%BB%E9%A2%98

**Comment by kamaellee** [comment]
好的谢谢，了解了，那请问 preview 的情况下有办法可以让网页超链接显示成蓝色带下划线的样式吗？或者能否在未来实现？
