### ISSUE TITLE
有序列表合并问题

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#114]
Is it correct?
![lists](https://user-images.githubusercontent.com/15811943/74041184-cead4d80-498a-11ea-924d-2568cae2d003.gif)

**Comment by 88250** [comment]
1. The Same marker (`*`) will be merged into one list, so (`-`) starts another list
2. An ordered list can use the same number,  like this: 
   ````markdown
   1. list item 1
   1. list item 2
   ````
In this case `4. List` and `1) List` should not be merged, it a bug, we will fix it later, thanks for your report.

**Comment by jakekwak** [comment]
![Feb-08-2020 15-15-05](https://user-images.githubusercontent.com/15811943/74092162-11078500-4a86-11ea-999d-2a40e392423a.gif)
