### ISSUE TITLE
表格插入行和列

### ISSUE THREAD

**Issue by HuBoZhi** [Vanessa219/vditor#1141]
### 你在什么场景下需要该功能？

请问表格插入行和列能否手动触发，插入行和列的快捷键和浏览器快捷键发生冲突，我想自己指定这两个的快捷键然后在触发插入列的事件，发现API文档中并没有这个相关的说明，能否提供相关的说明，感谢大佬的开源项目，在自己的网站上使用体验还是很好的。

**Comment by Vanessa219** [comment]
这个目前是写死的，是哪一个快捷键和浏览器的冲突了？

**Comment by HuBoZhi** [comment]
> 这个目前是写死的，是哪一个快捷键和浏览器的冲突了？
冲突的
Ctrl +新增行：页面缩放了
Ctrl Shift - 删除列：无任何反应

删除行和新增列没冲突

**Comment by Vanessa219** [comment]
这个操作需要光标在 cell 里面操作才可以。

**Comment by HuBoZhi** [comment]
我的光标时在cell里面的，我看到你写的文档中特意提到关于这个的注意事项了

**Comment by Vanessa219** [comment]
https://ld246.com/guide/markdown 你到这里试试

**Comment by HuBoZhi** [comment]
一样的问题

**Comment by doglex** [comment]
即时渲染模式不会显示表格工具，所见即所得可以显示

**Comment by Vanessa219** [comment]
> 一样的问题，依旧不好使

你使用的是什么编辑模式？
