### ISSUE TITLE
使用有序列表之后，getValue首行缩进就会消失

### ISSUE THREAD

**Issue by duzhenyan** [Vanessa219/vditor#1142]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文

　这里有首行缩进\n\n1. 有序列表\n2. 啊啊啊\n3. 哦哦哦\n4. 嗯嗯嗯\n
````````

### 截屏或录像

编辑框截图：
![图片](https://user-images.githubusercontent.com/48480768/147060231-87578b1d-112e-42ed-bc9c-e911ab69dcd2.png)

浏览器控制台打印的getValue()的值，第一行的缩进没有了：

![图片](https://user-images.githubusercontent.com/48480768/147060161-c6beba64-bba2-4be4-87ff-cf9853ef0996.png)

### 版本信息

* 版本：3.8.10
* 操作系统：window10
* 浏览器：
![图片](https://user-images.githubusercontent.com/48480768/147060382-b4ef6919-4d01-4d47-9f12-b5d35362a811.png)

**Comment by Vanessa219** [comment]
CommonMark 规范中是不允许首行空格的
