### ISSUE TITLE
渲染报错

### ISSUE THREAD

**Issue by HuBoZhi** [Vanessa219/vditor#1144]
### 描述问题

页面 Markdown 文章渲染情况下报错：
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'copy')
话说我是少引什么东西了吗？

### 期待的结果

报该错误后，after中的方法无法正常调用

### 截屏或录像

![image](https://user-images.githubusercontent.com/36149293/147477054-b1a74b20-be15-408e-abc2-4ae32b2b2d1f.png)

![image](https://user-images.githubusercontent.com/36149293/147477018-2b7a1b18-c332-4944-b277-b2d9fdbb7186.png)

### 版本信息

* 版本：3.8.8
* 操作系统：win11
* 浏览器：Chrome 版本 96.0.4664.45（正式版本） （64 位）

**Comment by Vanessa219** [comment]
解决了？

**Comment by HuBoZhi** [comment]
更新到3.8.10之后这个问题就没有了

**Comment by HuBoZhi** [comment]
之前也没有这个问题，好像就在3.8.8时出现了这个问题

**Comment by Vanessa219** [comment]
ok

双子螺狮 ***@***.***> 于2022年1月1日周六 11:51写道：
