### ISSUE TITLE
HTML 标签下 ir、wysiwyg、sv 三种编辑模式全部错乱

### ISSUE THREAD

**Issue by foxfire881** [Vanessa219/vditor#1145]
https://ld246.com/article/1640365098965

**Comment by Vanessa219** [comment]
@88250

**Comment by foxfire881** [comment]
经测试，开启 sanitize: false 关闭 XSS 转义后，bug 仍然存在，表现为“即时渲染”模式无法对 HTML 标签渲染。

例如：

1、“分屏模式”输入以下代码实现 a 的 2 次方。

a<sup>2</sup>
切换到“即时渲染”模式后，显示的是 a2，而不是 a 的 2 次方。

2、“所见即所得”模式下插入表格，在单元格内回车换行，然后把编辑器转换成“即时渲染”模式后，换行符被过滤了，整个单元格变成非常一整行超长文本，顶破了屏幕，“所见即所得”模式下的排版被打乱。

**Comment by 88250** [comment]
最近没有时间改进，非常抱歉，我关闭了。

**Comment by foxfire881** [comment]
> 最近没有时间改进，非常抱歉，我关闭了。

理解，期待老板后续有时间了继续更新，这个bug影响挺大的，希望vditor可以更加完善。
