### ISSUE TITLE
在 option 中添加 SV 模式补全功能启用控制

### ISSUE THREAD

**Issue by WindSpiritSR** [Vanessa219/vditor#1147]
### 你在什么场景下需要该功能？

在 SV 模式下编辑体验较差，插入代码块、引用、空行等标记不好管理

例如插入代码块时输入 ` ``` `，在正文过于复杂的情况下需要手动删除补全出来的后半部分

而在引用标记 `>` 前按回车会出现如下情况

```markdown
> > text
```

在调整空行时有些空行可被删除，有些不能，添加空行时同样会出现类似的问题

### 描述最优的解决方案 

在 option 中增加标记自动补全选项，控制 SV 模式下是否开启补全功能，关闭补全功能时的 SV 模式编辑器相当于 [纯文本编辑器+标记高亮]

**Comment by Vanessa219** [comment]
以前是纯文本模式，结果效果没加好，回不去了。你找找以前的版本看看。
