### ISSUE TITLE
Mozilla Firefox 下的两个BUG

### ISSUE THREAD

**Issue by BeiyanYunyi** [Vanessa219/vditor#1148]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

1. vditor 在被加载时会被自动聚焦。
2. 在 `wysiwyg` 和 `ir` 模式下，若插入“任务列表”，则复选框无法被选中，也就是说，“任务”无法被标记为“完成”状态。

### 期待的结果

1. vditor 在被加载时不会被自动聚焦。
2. 任务列表的复选框可以被选中

### 版本信息

* 版本：vditor 3.8.8
* 操作系统：Windows 11 / Android 10 (Lineage OS)
* 浏览器：Mozilla Firefox Nightly 98.0a1 / Mozilla Firefox 95.2.0

### 其他信息

在 Blink 内核的浏览器（Chrome、Edge 等）下不存在上述的两个问题。

**Comment by Yu-Core** [comment]
关于复选框无法被选中 https://bugzilla.mozilla.org/show_bug.cgi?id=1261296

**Comment by BeiyanYunyi** [comment]
> 关于复选框无法被选中 https://bugzilla.mozilla.org/show_bug.cgi?id=1261296

感谢！我也是在 Milkdown/website#34 的时候才发现这个大概不是 Vditor 的问题。

**Comment by Vanessa219** [comment]
自动聚焦是不是有 form 或者调用了聚焦相关的方法？
