### ISSUE TITLE
wysiwyg 所见即所得模式下，输入会闪屏

### ISSUE THREAD

**Issue by Leo-Lee-j** [Vanessa219/vditor#1150]
### 编辑模式

wysiwyg 所见即所得模式

### 描述问题
文字数量大概是 15000 左右。
如果输入位置上下都有图片，会发生闪屏现象，并且光标会偶尔跳动错乱。场景如下：

图片

这里输入文字会闪屏，并且光标位置错乱

图片

### 期待的结果

修复闪屏

### 截屏或录像

![动画](https://user-images.githubusercontent.com/34913418/149293456-41a590b2-a174-4906-bb3c-8a51a5ec750b.gif)

### 版本信息

* 版本：3.8.8
* 操作系统：win10
* 浏览器：edge

**Comment by Vanessa219** [comment]
输入的时候会解析 MD，导致图片重新渲染。你把图片和文字分在不同的块里面试试。

**Comment by Leo-Lee-j** [comment]
刷新浏览器重新编辑没有出现闪烁了。目前看起来好像是持续输入内容很长时间后就会出现闪烁。（上面的例子是编辑器持续输入了大概一个多小时）

> 输入的时候会解析 MD，导致图片重新渲染。你把图片和文字分在不同的块里面试试。

**Comment by Vanessa219** [comment]
持续输入的话建议使用思源，这个只是网页端的，注意保存数据。我先关闭了。
