### ISSUE TITLE
Nuxt3 & Lute is not defined

### ISSUE THREAD

**Issue by ahriknow** [Vanessa219/vditor#1151]
### 编辑模式

初始化编辑器

### 描述问题

在 Nuxt3 框架中出现 Lute is not defined 错误，Network 中已加载 lute.min.js

````````vue
<script setup lang="ts">
import Vditor from "vditor"

const editor = ref(null)
const vditor = ref(null)

onMounted(() => {
    if (process.client) {
        vditor.value = new Vditor(editor.value, {
            height: 360,
            toolbarConfig: {
                pin: true,
            },
            cache: {
                enable: false,
            },
            after: () => {
                vditor.value.setValue('hello, Vditor + Vue!')
            },
        })
    }
})
</script>

<template>
    <div>
        <div ref="editor"></div>
    </div>
</template>
````````

### 截屏或录像

![image](https://user-images.githubusercontent.com/40590867/149325424-e9eef83c-61af-4334-890d-a05ea6f0157f.png)

### 版本信息

* 版本：vditor 3.8.10
* 操作系统：Debian 10
* 浏览器：Chrome

**Comment by Vanessa219** [comment]
你在Console 里面输入 Lute 看看变量是否存在

**Comment by ahriknow** [comment]
控制台中 Lute 未定义

![image](https://user-images.githubusercontent.com/40590867/149451359-41867bf6-6077-46cc-83fd-fb45c90122a4.png)

**Comment by Vanessa219** [comment]
![image](https://user-images.githubusercontent.com/970828/149453324-3bbd76be-5156-469f-89a8-c48f71736bd3.png)

**Comment by mlsjla** [comment]
@Vanessa219   实际测试  nuxt3同样问题。   
单独引入lute也不行。

**Comment by Vanessa219** [comment]
单独引入的话看一下 Lute 是否为 undefined，是否引入成功

**Comment by mlsjla** [comment]
@Vanessa219   单独引用一样失败， 我这边debug发现是lute里 $global.process 信息在nuxt3中有错误导致。
下载了lute，然后改了下，目前勉强能用了，  暂时没发现问题。

```
            var k, l, m, n, o, p;
            k = $global.process;
            if (k === undefined) {
                return QQ.nil;
            }
            l = k.env;
            if (l === undefined) {
                return QQ.nil;
            }
            
            m = $global.Object.keys(l);
            n = $makeSlice(QQ, $parseInt(m.length));
            o = 0;
```
大概这个地方， 我增加了一个判断
            if (l === undefined) {
                return QQ.nil;
            }


猜测大概是$global. 在nuxt3环境中没有获取到正确的值。

**Comment by Teeoo** [comment]
+1 nuxt3同样的错误

**Comment by Vanessa219** [comment]
这个应该是正常的脚本，是不是 nuxt3 识别后做了什么特殊处理？

**Comment by zipme** [comment]
有可能是vite配置导致的，我原先vite配置里面有:
```ts
define: {
    'process.browser': true,
},
```
去掉后就可以了

**Comment by newbill** [comment]
nuxt3-rc6 配合 最新的vditor-3.8.17还是会报这个错，是否有解决方案？

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/1094

不行的话就手动在 html 中加一下依赖吧

```
<script src="xxx/dist/js/lute/lute.min.js" id="vditorLuteScript"></script>
```

**Comment by xjbuzzle** [comment]
可以试一下window.Lute

**Comment by gaminglifex** [comment]
請問有解決方法嗎?

**Comment by ccitsxy** [comment]
> 請問有解決方法嗎?
在setup中加入如下
```typescript
useHead({
  script: [
    {
      src: "https://unpkg.com/vditor@3.8.18/dist/js/lute/lute.min.js",
      id: "vditorLuteScript",
    },
  ],
});
```

**Comment by xiaowansheng** [comment]
我也是这个问题，自己引入也是同样的报错，用的3.9.5

**Comment by cvpv** [comment]
lute.min.js:7 Uncaught Error: syscall/js: call of Value.Get on undefined
    at $callDeferred (lute.min.js:7:703)
    at $panic (lute.min.js:7:1217)
    at $packages.syscall/js.J.ptr.Get (lute.min.js:33:6373)
    at Object.$init (lute.min.js:34:35697)
    at Object.$init (lute.min.js:35:1358)
    at Object.$init (lute.min.js:38:66061)
    at Object.$init (lute.min.js:44:51755)
    at Object.$init (lute.min.js:45:86222)
    at Object.$init (lute.min.js:62:414494)
    at $init (lute.min.js:63:2726)
    at $goroutine (lute.min.js:7:1727)
    at $runScheduled (lute.min.js:7:2359)
    at $schedule (lute.min.js:7:2574)
    at $go (lute.min.js:7:2210)
    at lute.min.js:68:1
    at lute.min.js:71:4
$callDeferred @ lute.min.js:7
$panic @ lute.min.js:7
$packages.syscall/js.J.ptr.Get @ lute.min.js:33
$init @ lute.min.js:34
$init @ lute.min.js:35
$init @ lute.min.js:38
$init @ lute.min.js:44
$init @ lute.min.js:45
$init @ lute.min.js:62
$init @ lute.min.js:63
$goroutine @ lute.min.js:7
$runScheduled @ lute.min.js:7
$schedule @ lute.min.js:7
$go @ lute.min.js:7
（匿名） @ lute.min.js:68
（匿名） @ lute.min.js:71
vditor.js?v=acd62eb7:3691 Uncaught (in promise) ReferenceError: Lute is not defined
    at setLute (vditor.js?v=acd62eb7:3691:30)
    at vditor.js?v=acd62eb7:14629:55
