### ISSUE TITLE
Vditor依赖加载存在性能问题

### ISSUE THREAD

**Issue by HerbertHe** [Vanessa219/vditor#1152]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

Vditor 通过请求 CDN 拿到 lute.min.js, 但上述的文件体积似乎很影响 Vditor 请求以实现整体异步渲染的速度。

### 期待的结果

优化 Vditor 请求 Lute 的响应时间。

给 Lute PR 过，感觉 lute.min.js 的生成太依赖 gopherjs 了。单文件大小会直接影响整体的渲染速度，将会导致 Vditor 相对于其它markdown渲染和编辑的优势消失。跟我之前 PR Vditor 关于国际化问题的想法相同，lute 的代码文件需要被分割，与之对应的 Vditor 加载部分的代码也需要大量修改。所以，这似乎不只是仅 Lute 修改可以解决的。

之前在 Lute 的 issue 中也提到过这个 js 产生文件的问题，D大表示是因为 gopherjs 而全部打包在一起这个问题。或许是不是可以在下一个大版本实现 Lute 编译文件为 wasm 以供 Vditor 进行调用？通过 wasm 进行代码分割和浏览器优化以提升整体性能，似乎也是个不错的idea。并且可以通过webpack，rollup等对 lute.wasm 进行打包工作，可以实现 Vditor 进行同步渲染。

上述是个人的一点构想~ 希望 Vditor 和 Lute 可以越来越好！

### 截屏或录像

![image](https://user-images.githubusercontent.com/30955264/149342485-e7aac182-4b19-4593-9111-d515651ee04f.png)

### 版本信息

* 版本：3.8.10
* 操作系统：Win10
* 浏览器：Edge (chromium)

**Comment by Vanessa219** [comment]
这个 issue 应该先提到 Lute 上吧，可以尝试帮忙编译看看。谢谢。

**Comment by yinhaixiang** [comment]
确实存在严重的加载存在性能问题, lute.min.js就算我用自己的CDN, 还是因为太大, 加载很慢, 我的很多论坛用户都和我反馈编辑器假死(其实是在加载过程中), 体验相当差

**Comment by Vanessa219** [comment]
使用 https://jsdelivr.com/ 的应该还可以接受。

**Comment by HerbertHe** [comment]
> 使用 https://jsdelivr.com/ 的应该还可以接受。

jsdelivr总体上来说可以，我现在在新疆这个加载时间有时候很长。。主要原因还是体积比较大

**Comment by sidian123** [comment]
怎么解决呀，我这里不翻墙的话，访问不了lute.min.js，在手机上时使用极其不方便

https://cdn.jsdelivr.net/npm/vditor@3.8.1/dist/js/lute/lute.min.js

**Comment by HerbertHe** [comment]
> 怎么解决呀，我这里不翻墙的话，访问不了lute.min.js，在手机上时使用极其不方便
> 
> https://cdn.jsdelivr.net/npm/vditor@3.8.1/dist/js/lute/lute.min.js

@sidian123 这个问题目前无法解决，作者在最新的发行版中更换了cdn，要不升级Vditor、要不在原来版本自行修改cdn，但对于 lute.min.js 的问题来说治标不治本。
