### ISSUE TITLE
vditor 的生产代码未经 minify

### ISSUE THREAD

**Issue by lixiang810** [Vanessa219/vditor#1153]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

以 [3.8.8](https://cdn.jsdelivr.net/npm/vditor@3.8.8/dist/index.min.js) 为例，发现代码仅仅被 bundle，却没有被 minify，连注释都还留着，从而带来了不必要的流量开销。

### 版本信息

* 版本：3.8.8
* 操作系统：Windows 11
* 浏览器：Mozilla Firefox

### 其他信息

希望能检查一下 webpack 的配置。

![图片](https://user-images.githubusercontent.com/14120445/149449695-ae55a03e-44e8-4372-bf22-854da8bbab50.png)
图为 3.8.8 版本的“min”代码，似乎没有被 minify 到。

**Comment by lixiang810** [comment]
好耶！

**Comment by lixiang810** [comment]
看了一下用的 terser，我记得 webpack5 的 minify 可以让它自己干

**Comment by Vanessa219** [comment]
欢迎PR

**Comment by lixiang810** [comment]
好了，我是小丑。webpack 的 minify 本来就是 terser 干的。

**Comment by Vanessa219** [comment]
😊
