### ISSUE TITLE
Support mhchem for KaTex

### ISSUE THREAD

**Issue by NADESHIKON** [Vanessa219/vditor#1154]
### 你在什么场景下需要该功能？

使用化学equation的时候

### 描述最优的解决方案 

在 [这里](https://github.com/Vanessa219/vditor/blob/db2819f2c62e38441090fb5ce4893b5a9139f8d4/src/ts/markdown/mathRender.ts#L44) 之后(then之前) 也加一个 https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/contrib/mhchem.min.js  应该就没问题了

**Comment by Vanessa219** [comment]
要不直接 PR 一个？
