### ISSUE TITLE
无法通过快捷键/按钮使用多层引用

### ISSUE THREAD

**Issue by skadiD** [Vanessa219/vditor#1155]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

使用 md 语法 `>` 可以正确渲染多层引用，但使用快捷键或者按钮时不会继续增加引用，而是取消当前引用

### 期待的结果

区分取消当前引用和继续引用的快捷键？

### 版本信息

* 版本：v3.8.8
* 操作系统：windows 10
* 浏览器：edge

**Comment by Vanessa219** [comment]
按钮设计为 toggle 形式的，如果区分的话快捷键就会占用太多。
