### ISSUE TITLE
所见即所得行级 HTML 解析错误

### ISSUE THREAD

**Issue by skadiD** [Vanessa219/vditor#1156]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

使用font属性渲染内容,手动输入代码`<font size=12>test</font>`无法渲染，此时复制该行内容发现标签被转义。
通过粘贴 `<font size=12>test</font>`到编辑器同样无法解析，但粘贴`<font size=12 >test</font>`可以被正常实时渲染

````````markdown
<font size=12 >test</font>
````````

### 期待的结果
手动输入html代码可以被正确渲染

### 截屏或录像

![1](https://user-images.githubusercontent.com/50161715/149789896-02d19d5e-fc81-4216-a247-02b3af873b11.jpg)

![2](https://user-images.githubusercontent.com/50161715/149789878-8e783170-1c7e-47ff-a056-5492c8d212ed.jpg)

### 版本信息

* 版本：3.8.8
* 操作系统：win10
* 浏览器：edge

**Comment by 88250** [comment]
在处理 HTML 时会自动转换为 `<code>` 来包裹 HTML 代码。目前的问题是 spin 以后错误将语法节点解析为 code 而不是 html-inline，这个问题稍后会解决，感谢反馈。
