### ISSUE TITLE
本地文件跨域

### ISSUE THREAD

**Issue by coder163** [Vanessa219/vditor#1157]
按照官方文档的要求，我配置了cdn。但是在读取这个文件的时候依然有跨域问题，想请教一下怎么修复？
我并不想在本地启动服务

![2 1](https://user-images.githubusercontent.com/18748856/149874587-0e4dc111-d73d-48d7-9fb4-63d71e970ec3.png)

![2 2](https://user-images.githubusercontent.com/18748856/149874602-61a46c79-8de0-4c76-b0d4-3ff7b539c4f5.png)

![2 3](https://user-images.githubusercontent.com/18748856/149874573-5945da2e-40a6-4abd-969c-ab706a81d68c.png)

**Comment by Vanessa219** [comment]
需要搭建一个静态服务器，你这个直接访问的文件了。

**Comment by terry8650** [comment]
我和上面同样的跨域问题，但不是直接访问的文件，而是一个域名的站点，设置的cdn是外网加非80端口的地址，为啥这样也跨域？

**Comment by qianque7** [comment]
我用3.8的版本存在这个问题，降级到3.7后成功解决了

**Comment by Vanessa219** [comment]
参考一下 https://github.com/Vanessa219/vditor/blob/289c47342fa9ee13c8e2929f3fc473c6f627ff15/demo/static.html

**Comment by Noahs007** [comment]
请问解决了吗，我也遇到了这个问题。
