### ISSUE TITLE
希望能够推出适用于 VS Code 的扩展

### ISSUE THREAD

**Issue by topbardon** [Vanessa219/vditor#1159]
### 你在什么场景下需要该功能？

有的时候需要在 VS Code 中编辑 Markdown，但是目前在 VS Code 中似乎并没有能够接近**类似 Typora** 的**即使渲染**写作体验的扩展，而我在 vditor 上体验到了**即使渲染**的效果，很希望能够在 VS Code 上也能有这样的体验。

### 描述最优的解决方案 

希望能够在 VS Code 上**直接安装 vditor 的扩展**。

### 描述候选解决方案

vditor 提供教程允许其它人将 vditor 编辑 Markdown 的能力移植到其他扩展上。

### 其他信息

有一个 VS Code 扩展 [Office Viewer](https://github.com/cweijan/vscode-office/ "Office Viewer 的 GitHub 主页") 能够实现在 VS Code 中使用 vditor 的即使渲染编辑 Markdown 的功能，不过这个扩展本来是用来预览 Office 文件的，后来使用 vditor 实现了预览 Markdown 的功，希望 vditor 能推出单纯用于编辑、预览 Markdown 的 VS Code 扩展。

**Comment by 88250** [comment]
感谢提议，但这个超出了 Vditor 项目的范围，先关闭了。
