### ISSUE TITLE
支持 Plantuml 类图

### ISSUE THREAD

**Issue by forecasted** [Vanessa219/vditor#116]
虽然vditor已经支持了mermaid类图，可以应对很多情况。但是plantuml支持的图更多，希望可以支持一下。

**Comment by Vanessa219** [comment]
PlantUML 只有 Java 支持吧？纯前端的话，欢迎推荐一下可用的库。没有的话，只能遗憾的关闭这个特性了。

BTW：最近加支持了 Graphviz

**Comment by elderGinger** [comment]
https://plantuml.com/code-javascript-asynchronous 
可以把server做成个设置不, 如果能左右/上下实时预览就更好了

**Comment by Vanessa219** [comment]
你的意思是渲染结果从服务器端获取么？
但是这个服务我不太懂要怎么弄，可以帮忙弄一个 online 的接口及示例么？

**Comment by elderGinger** [comment]
https://plantuml.com/demo-javascript-asynchronous
这里有官方的demo
https://plantuml.com/code-javascript-asynchronous
这里的js就可以直接用, 我本地也试了下可以的 
官方意思
1. Encoded in UTF-8
2. Compressed using Deflate algorithm
2. Reencoded in ASCII using a transformation close to base64
utf-8编码, 压缩, 再用base4转换之后把内容发给server, 然后显示服务端对应url图片
我其实不太懂前端部分 = =!

**Comment by Vanessa219** [comment]
多谢，问题是我们没有 server

**Comment by elderGinger** [comment]
server也开源的, plantuml-server 
https://github.com/plantuml/plantuml-server 
也可以默认用用官方免费server嘛 :)

**Comment by Vanessa219** [comment]
官方的 Demo 打不开，修改以后点击提交也无法再次渲染。
