### ISSUE TITLE
3.8.11 的更新说明没有了吗

### ISSUE THREAD

**Issue by HuBoZhi** [Vanessa219/vditor#1161]
现在的新版本更新说明都没有了吗，完全不知道有没有什么新的东西可以用上的啥的，用的很好，所以经常关注更新状态，发现更新之后没有说明好难受。

**Comment by Vanessa219** [comment]
抱歉，马上加

**Comment by HuBoZhi** [comment]
> 抱歉，马上加

没没没，不用道歉，非常感谢你们提供的这么好的开源软件的，就是看你们好多个版本都没有说明了，所以也是有些疑惑。非常感谢大佬。今天看到消息没本来想回来者，奈何没有电脑，只能现在才回复。
