### ISSUE TITLE
toolbar padding不稳定变动

### ISSUE THREAD

**Issue by liuhaogui** [Vanessa219/vditor#1163]
切换编辑模式，再切换预览（来回切）， toolbar padding 不一样，图标来回动，`vditor-toolbar` 行内样式padding-left如何取消？

只有分屏预览模式一致。

**Comment by Vanessa219** [comment]
动态计算的，和编辑器保持一致。

**Comment by liuhaogui** [comment]
说的是有bug哇， 可以测试下

**Comment by Vanessa219** [comment]
没太清楚，麻烦录屏看一下，谢谢。
