### ISSUE TITLE
预览和编辑切换后padding不一致

### ISSUE THREAD

**Issue by liuhaogui** [Vanessa219/vditor#1164]
### 编辑模式
窗口大小一致的情况， 预览和编辑切换后padding不一致。 

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

padding问题

![image](https://user-images.githubusercontent.com/47664337/150975769-c65ad38a-1105-4c03-b918-8584e92bf728.png)
![image](https://user-images.githubusercontent.com/47664337/150975824-15533d8a-8af6-4060-9c3d-346cfcc7d09b.png)

**Comment by Vanessa219** [comment]
预览是自适应的，所以 padding 就不对齐了。
