### ISSUE TITLE
3.8.11初始化时始终报错GET https://cdn.jsdelivr.net/npm/vditor@3.8.11/dist/js/i18n/zh_CN.js net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by Cheng-x-c** [Vanessa219/vditor#1166]
3.8.11初始化时始终报错GET https://cdn.jsdelivr.net/npm/vditor@3.8.11/dist/js/i18n/zh_CN.js net::ERR_NAME_NOT_RESOLVED

**Comment by 88250** [comment]
请修改 options cdn 配置项。

**Comment by Cheng-x-c** [comment]
没有自建CDN咋整

**Comment by Vanessa219** [comment]
用自己服务器上的

**Comment by zhuyouzhufu** [comment]
你好，部分cdn不能内嵌到Veditor吗？我过年的时候跑到乡下来写代码（网络太差），结果就成这个样子了
![image](https://user-images.githubusercontent.com/34908518/152665872-e8d222c1-d306-45ff-a410-28610da8e85f.png)
![image](https://user-images.githubusercontent.com/34908518/152665880-1e85aed5-4c28-40e3-9f8d-7f5cfb2c6790.png)
像这种图标应该要支持自定义，但是一般来说改变的相对还是少数（也就是这个CDN的样式）。。所以最好可以内嵌一个。如果缺省的话就是默认。如果想自定义就添自己的CDN样式

**Comment by zhuyouzhufu** [comment]
就我们开发者而言，如果不是甲方特殊要求。图标要自定义，我们基本上都不会改图标样式之类的js。所以这个CDN访问图标相对来说我感觉效率不如放在本地。每次都要请求CDN服务器。

**Comment by Vanessa219** [comment]
cdn 配置可查看 https://ld246.com/article/1549638745630
