### ISSUE TITLE
换行时行间距太大！

### ISSUE THREAD

**Issue by tesla-cat** [Vanessa219/vditor#1167]
- 如图，换行时行间距太大，怎么办？

<img width="286" alt="image" src="https://user-images.githubusercontent.com/28215638/151809095-b343f21f-7296-4664-bc74-be3e8f2c6bce.png">

**Comment by pxim** [comment]
> * 如图，换行时行间距太大，怎么办？
> 
> <img alt="image" width="286" src="https://user-images.githubusercontent.com/28215638/151809095-b343f21f-7296-4664-bc74-be3e8f2c6bce.png">

怎么解决的，编辑器怎么设置，可以让换行间距变小

**Comment by tesla-cat** [comment]
我知道 shift + enter 可以，但是那样用户体验很不好 。
怎样设置能让编辑器只空一行？ 这样的话如果我想空一行我就压一次enter, 两行就两次enter, 这样才合理啊

**Comment by pxim** [comment]
> 我知道 shift + enter 可以，但是那样用户体验很不好 。 怎样设置能让编辑器只空一行？ 这样的话如果我想空一行我就压一次enter, 两行就两次enter, 这样才合理啊

我也觉得这样才合理

**Comment by Vanessa219** [comment]
重置一下 css

**Comment by Vanessa219** [comment]
```
.vditor-reset p {
    margin-bottom: 10px;
    margin-top: 0;
}
```
