### ISSUE TITLE
为 Vditor 添加文本版本 Diff

### ISSUE THREAD

**Issue by HerbertHe** [Vanessa219/vditor#1168]
### 你在什么场景下需要该功能？

Git Diff 在版本管理中非常的实用。若将Vditor作为评论输入使用，编辑评论进行 Diff 比较相比于现有的撤销、还原操作更有实际的 **“对比”** 意义，用户体验可能会更好一些。

### 描述最优的解决方案 

可以通过 Vditor 的配置项激活 Diff 模式（不影响现有用户使用），开启 Diff 则可以调用 [Undo](https://github.com/Vanessa219/vditor/blob/master/src/ts/undo/index.ts#L13) 逻辑部分的栈内数据（默认记录50条，可能对于Diff来说不够用，diff可以新开一个stack），渲染栈内数据到 Diff Tree 对比信息中（类似于VSCode的样式）。在工具栏添加 Diff 按钮激活 Diff Tree 渲染，以实现大量更改的对比。

**Comment by Vanessa219** [comment]
git diff 可以直接使用其库作为插件来对接，写到 vditor 中会不会太过臃肿

**Comment by HerbertHe** [comment]
我去看了一下diff-match-patch的这个库，似乎可以直接进行行级别的diff，粒度不需要Undo那么细。只需要记录初始化文本和焦点离开编辑器时的内容，默认情况下，在渲染diff tree的时候是不可编辑的。没有性能损失，只需要写diff渲染就可以了。

此外，我还发现vditor可以进一步实现在线协同编辑，Undo的粒度是够的（后话了属于是）。emmm Vditor或许可以设计一套生命周期进行插件加载，不仅仅在于markdown语法的渲染上，甚至可以改变页面渲染。这样可以把原来的渲染逻辑进一步分离出去，减小vditor自身的体积。

**Comment by Vanessa219** [comment]
wysiwyg 是需要渲染的，没有办法剥离。目前主要是 lute 比较大。
