### ISSUE TITLE
从别的窗口切换回来，光标没有在原编辑处

### ISSUE THREAD

**Issue by cdslily** [Vanessa219/vditor#1169]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题
在编辑过程中，将窗口切换到别的应用程序，例如浏览器，然后切换回VSCode，此时光标焦点没有落在原先编辑的地方。

### 期待的结果

返回VScode时，光标能保持在原先编辑处。

### 版本信息

* 版本：Viditor v3.8.4 / Lute v1.7.2
* 操作系统：Windows 10 家庭版 21H2 (19044.1466)
* 浏览器：VS Code 1.6.4

**Comment by Vanessa219** [comment]
VS Code 插件不是我写的，只是基于 Vditor，你需要到相关的库上去提 issue 哦。
