### ISSUE TITLE
代码编辑区域未能按照预期隐藏

### ISSUE THREAD

**Issue by KunerRick** [Vanessa219/vditor#1171]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

在演示[DEMO](https://ld246.com/guide/markdown)中，发现存在如下现象：
1. 在 ”语法高亮支持“ 一节，似乎语法高亮并未生效？
2. 当选中一个代码块进行编辑，此时直接点击另外一个代码块，上一个代码块的编辑区域未隐藏。

### 期待的结果
1. 默认代码高亮有样式
2. 能否点击另外一个代码块时，隐藏当前代码块的编辑区域

### 截屏或录像
 

https://user-images.githubusercontent.com/23055512/153193087-70987d4b-daa7-4fdc-ace9-d30265499c61.mp4

录频有点模糊，截个图

![image](https://user-images.githubusercontent.com/23055512/153193448-1028b1d5-0591-4a9c-a4e2-6adde68369f4.png)

### 版本信息

* 版本：latest
* 操作系统：window 10
* 浏览器：Chrome

**Comment by Vanessa219** [comment]
问题一可关注 https://github.com/Vanessa219/vditor/issues/1178
