### ISSUE TITLE
代码块编辑--部分类型代码块直接编辑，不进行编辑、预览分块

### ISSUE THREAD

**Issue by KunerRick** [Vanessa219/vditor#1172]
### 你在什么场景下需要该功能？

部分文本类代码块（非图形化展示，如流程图），比如java、javascript 等，能否给定一些配置项，直接在语法高亮的基础上进行编辑，不进行编辑区域和预览区域分割。

### 描述最优的解决方案 

就类似于 typora 的代码块编辑体验，又具有语法高亮。

### 描述候选解决方案

如果在现阶段进行该功能实现，我想尝试对特定的代码块的编辑区域代码进行高亮，并隐藏代码预览区域，因未完全深入阅读vditor ,不知这样操作是否会有其他的连带影响。

### 其他信息
vditor 一定会成为一款很棒的编辑器~

**Comment by 88250** [comment]
你好，这个没有计划，如果要修改的话可考虑引入 CodeMirror 编辑器实现，但是开发工作量可能比较大，有空的话可以试试看。

**Comment by KunerRick** [comment]
> 你好，这个没有计划，如果要修改的话可考虑引入 CodeMirror 编辑器实现，但是开发工作量可能比较大，有空的话可以试试看。

在CodeMirror确实工作量太大了，谢谢~我再取舍一下
