### ISSUE TITLE
代码规范 lint 从 Tslint 迁移至 Eslint

### ISSUE THREAD

**Issue by HerbertHe** [Vanessa219/vditor#1176]
- 解决 Tslint 已经被淘汰的问题
- 将 Tslint 迁移至 Eslint + Prettier + EditorConfig 的组合, 做到多端代码风格约束统一

**Comment by Vanessa219** [comment]
还麻烦先把这部分的代码单独 PR 了吧。谢谢。

**Comment by HerbertHe** [comment]
#1179
