### ISSUE TITLE
Firefox no cursor when ctrl+b pressed

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#118]
![Feb-07-2020 17-34-49](https://user-images.githubusercontent.com/15811943/74073562-62edd380-49d0-11ea-95ef-c147963a57f9.gif)

**Comment by 88250** [comment]
Could you give more details, I can't reproduce this issue.

**Comment by Vanessa219** [comment]
I can't reproduce this issue, but I recycle code. pls try it after 2.1.12

**Comment by jakekwak** [comment]
Ok after cleared cache. thanks

**Comment by 88250** [comment]
> Ok after cleared cache. thanks

Thanks, can we close this issue?

**Comment by jakekwak** [comment]
I think I found this message when no cursor.  (chrome 80??)
![Screen Shot 2020-02-08 at 2 28 31 PM](https://user-images.githubusercontent.com/15811943/74091662-5f655580-4a7f-11ea-9494-7a7b2bc4179d.png)

**Comment by jakekwak** [comment]
I can not find the reason.
i have still problem (chrome 80?)
I am not sure.
![Screen Shot 2020-02-08 at 2 40 24 PM](https://user-images.githubusercontent.com/15811943/74091785-131b1500-4a81-11ea-9c32-5b7ca7d503f2.png)

**Comment by jakekwak** [comment]
firefox
![ctrlbb](https://user-images.githubusercontent.com/15811943/74094177-913be380-4aa2-11ea-80e9-3b45843748e2.gif)

**Comment by Vanessa219** [comment]
Firefox has a lots of bug, and about issue can be recorded at https://github.com/Vanessa219/vditor/issues/124

**Comment by jakekwak** [comment]
I think this error message at chrome cause the no-cursor.

![Screen Shot 2020-02-08 at 10 05 33 PM](https://user-images.githubusercontent.com/15811943/74096106-f2be7b00-4abf-11ea-9e78-c8f7ad1a1ee7.png)

**Comment by Vanessa219** [comment]
no-cursor fixed by https://github.com/Vanessa219/vditor/commit/28870844aa9973db35bc164862126a9935dedc37

**Comment by jakekwak** [comment]
go to https://hacpai.com/guide/markdown at chrome 80
open chrome developer(f12).
click first of Vditor.
enter.
