### ISSUE TITLE
本地开发，打开 http://localhost:9000 时 http://localhost:9000/dist/js/i18n/zh_CN.js报404

### ISSUE THREAD

**Issue by TonyBJC** [Vanessa219/vditor#1181]
### 问题
下载最新版本3.8.11 源码。
npm install
npm run start
打开 http://localhost:9000 时 http://localhost:9000/dist/js/i18n/zh_CN.js报404
### 期待的结果
开发时静态资源加载正常，能打开 http://localhost:9000 页面。

### 截屏或录像
![image](https://user-images.githubusercontent.com/5052581/155031663-55b2d95d-4a0a-4a42-b9c0-45bbd37c4b7b.png)

### 版本信息

* 芯片：M1 Pro
* 操作系统：MacOS
* 操作系统版本：Monterey
* NodeJS版本：所有LTS版本
* 浏览器：所有浏览器

**Comment by Vanessa219** [comment]
需先运行一下 `npm run build`
