### ISSUE TITLE
通过import方式从本地读取js及css

### ISSUE THREAD

**Issue by dest1n1s** [Vanessa219/vditor#1183]
### 你在什么场景下需要该功能？

目前jsDelivr在国内处于半墙状态，连接过于缓慢，国内又缺乏好用的镜像站以设置为vditor的cdn源。

### 描述最优的解决方案 

在Vditor的options中提供选项以禁用cdn，转而通过es6 import方式从本地node_modules中读取js及css。

**Comment by Vanessa219** [comment]
以前版本用过webpack的动态加载，但是问题比较多（可参看提交记录），所以还是采取了目前的做法，目前可以通过设置自己的cdn 来加快速度
