### ISSUE TITLE
关闭 Counter tip

### ISSUE THREAD

**Issue by flaming-cl** [Vanessa219/vditor#1185]
### 编辑模式
All

### 描述问题
未开启工具栏 tooltip
独立于工具栏存在的 Counter，自动显示 tooltip

### 期待效果
options.counter 提供关闭 tooltip 参数

### 截屏或录像
![image](https://user-images.githubusercontent.com/51183663/156279248-76650c2a-9fc5-40f9-a009-c6e1bc6f9332.png)

**Comment by Vanessa219** [comment]
可以重置 `.vditor-counter` css 试试
