### ISSUE TITLE
cdn 问题，https://cdn.jsdelivr.net/gh/stevenjoezhang/live2d-widget@latest/waifu.css

### ISSUE THREAD

**Issue by ushergo** [Vanessa219/vditor#1187]
(index):1 Uncaught (in promise) https://cdn.jsdelivr.net/gh/stevenjoezhang/live2d-widget@latest/waifu.css
![image](https://user-images.githubusercontent.com/22043739/156318267-6e6b08ce-042f-4052-87ec-aefea2401b4e.png)

请问这个该怎么配置options，我看了文档也没有些怎么配置，就说了在options配置，key名是什么？ cdn？还是url?
![Uploading image.png…]()

**Comment by Vanessa219** [comment]
cdn
