### ISSUE TITLE
支持 vega & vega-lite 渲染

### ISSUE THREAD

**Issue by wu-kan** [Vanessa219/vditor#1189]
### 你在什么场景下需要该功能？

[vega](http://vega.github.io/)  & [vega-lite](https://vega.github.io/vega-lite/) 是与 [echarts](https://echarts.apache.org/) 类似的作图工具，但是是更加学术化的选择，其优点是提出了一个规范的语法，可以在不同平台和语言中交换可视化图表，例如 python 可视化库 [Altair](https://altair-viz.github.io/) 就使用了 [vega-lite](https://vega.github.io/vega-lite/) 作为后端。

### 描述最优的解决方案 

[vega-lite](https://vega.github.io/vega-lite/) 代码块中的内容将会被 vega-lite 渲染。

````markdown
```vega-lite
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A", "b": 28}, {"a": "B", "b": 55}, {"a": "C", "b": 43},
      {"a": "D", "b": 91}, {"a": "E", "b": 81}, {"a": "F", "b": 53},
      {"a": "G", "b": 19}, {"a": "H", "b": 87}, {"a": "I", "b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "nominal", "axis": {"labelAngle": 0}},
    "y": {"field": "b", "type": "quantitative"}
  }
}
```
````

[markdown-preview-enhanced](https://shd101wyy.github.io/markdown-preview-enhanced/#/zh-cn/diagrams?id=vega-%e5%92%8c-vega-lite) 实现了相同的功能，可以作为参考。

### 其他信息

非常感谢 vditor 项目开发的非常好用的编辑器~

**Comment by Vanessa219** [comment]
最近比较忙，可以参看 echarts 相关代码进行 PR。谢谢

**Comment by wu-kan** [comment]
好d，过几天有空试试看

**Comment by Vanessa219** [comment]
那我先关闭了，到时候直接 PR 即可
