### ISSUE TITLE
Joplin 插件支持

### ISSUE THREAD

**Issue by maghsk** [Vanessa219/vditor#1190]
### 你在什么场景下需要该功能？

替换原生[Joplin](https://github.com/laurent22/joplin)渲染引擎

### 描述最优的解决方案 

以[插件](https://github.com/joplin/plugins)的形式替换～

### 其他信息

Joplin 是一款跨平台、开源且完全免费的笔记和To-Do 应用程序，Joplin 特点有：免费、跨平台、数据安全（不存在后门、数据库自己管理、支持端到端加密）、多终端无限制同步、支持MarkDown、支持导出通用格式等。

**Comment by Vanessa219** [comment]
Vditor 没有插件体系，这个支持不了

**Comment by newproplus** [comment]
这个得先问问joplin允许插件替换编辑器吗
