### ISSUE TITLE
用dark主题时,编辑区域的文字颜色是黑色

### ISSUE THREAD

**Issue by yuhang9580** [Vanessa219/vditor#1191]
使用dark主题时间,编辑区的文字颜色是黑色,导航与功能按钮颜色正常
环境是vue2
![image](https://user-images.githubusercontent.com/47517414/157401665-5da77fd5-fe3a-4895-b0c5-b9dfdcbeb338.png)

**Comment by yuhang9580** [comment]
.vditor-reset {
	color: #24292e;
	font-variant-ligatures: no-common-ligatures;
	font-family: "Helvetica Neue", "Luxi Sans", "DejaVu Sans", "Hiragino Sans GB", "Microsoft Yahei", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Noto Color Emoji", "Segoe UI Symbol", "Android Emoji", "EmojiSymbols";
	word-wrap: break-word;
	overflow: auto;
	line-height: 1.5;
	font-size: 16px;
	word-break: break-word
}


已找到该字体颜色的CSS在此处,希望可以修复一下

**Comment by Vanessa219** [comment]
看一下是不是内容主题和编辑器主题设置不一致？ https://ld246.com/article/1549638745630#%E5%86%85%E5%AE%B9%E4%B8%BB%E9%A2%98
