### ISSUE TITLE
希望echarts支持js格式的json

### ISSUE THREAD

**Issue by WittonBell** [Vanessa219/vditor#1194]
### 你在什么场景下需要该功能？
在使用echarts图表时，比如下面的数据

```echarts
{
 // 设置
  settings: {
    theme: {
      categoryAxis: {
        axisLine: { show: false },
        axisTick: { show: false },
        splitLine: { show: false }
      },
      valueAxis: { axisLine: { show: false } }
    }
  },
  xAxis : [
    {
      type : 'category',
      data : ['周一', '周二', '周三', '周四', '周五', '周六', '周日']
    }
  ],
  yAxis : [{ type : 'value' }],
  series : [
    {
      name:'直接访问',
      type:'bar',
      barWidth: '60%',
      data:[10, 52, 200, 334, 390, 330, 220]
    }
  ]
}
```

echarts中的示例基本上都是以js为输入的数据，而vditor目前只支持严格的json格式，每一个字段都需要加双引号。
很多时候是从echarts示例中复制一些示例的输入数据来修改成自己的数据，但是每个字段需要添加双引号比较麻烦。如果能直接支持就好了。

### 描述最优的解决方案 
自己简单研究了一下，把src\ts\markdown\chartRender.ts中的
```js
const option = JSON.parse(text)
```
改为：
```js
var js = eval("(" + text + ")");
var strJS = JSON.stringify(js);
const option = JSON.parse(strJS)
```
即可实现，但是有一点问题就是输入数据中不支持注释。同时不知道会不会有其它问题。

**Comment by Vanessa219** [comment]
这会有安全问题吧

**Comment by WittonBell** [comment]
我的做法只是一个测试，可以考虑看有没一个安全的方案，提这个只是希望能支持这样的功能，以提供便捷性。

**Comment by Vanessa219** [comment]
有的话会进行采纳，感谢建议

**Comment by WittonBell** [comment]
可以考虑一下自定义一个函数，将输入的非严格的JSON，转换成严格的JSON，再调用JSON.parse

**Comment by zxniuniu** [comment]
有个新思路，参见本人博客：
[修改 Markdown 编译器 vditor 支持 JS 形式 JSON，并支持非 JSON 形式 Option](https://fuyiyi.imdo.co/articles/2023/02/10/1676015361827.html)
