### ISSUE TITLE
支持 dir 设置

### ISSUE THREAD

**Issue by HerbertHe** [Vanessa219/vditor#1197]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

默认情况下，键入 markdown 都遵循 LTR 的使用习惯，但是针对于 RTL 的语言没有特别的优化。会导致 LTR 和 RTL 文本混排的时候 markdown 的 加粗、斜体 等feat出现布局位置错误的情况，而 RTL 的布局会考虑修复这种缺陷

### 版本信息

* 版本：latest
* 操作系统：Win10
* 浏览器：Edge

**Comment by Vanessa219** [comment]
感觉问题有点多呀，还需要再改改。
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/970828/159493143-d0b7c895-44c2-4aaf-940a-251c0e90fedc.png">

**Comment by HerbertHe** [comment]
针对子工具栏的问题，增加 DOM 和修改 CSS 样式可以解决。

**Comment by HerbertHe** [comment]
我感觉迁移到 Less，并且重构样式表似乎是必要i的，可以借助三方工具来进一步减小样式表的体积。

**Comment by Vanessa219** [comment]
如果是打包工具的话，可以看一下具体减少的大小和使用成本。减少不大的话可以先不引入。

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/1200

**Comment by HerbertHe** [comment]
> 如果是打包工具的话，可以看一下具体减少的大小和使用成本。减少不大的话可以先不引入。

还有个问题是，Windows 端的 Sass 环境配置始终是个大问题 emmm，尤其是本地已经有 Python3

**Comment by Vanessa219** [comment]
> > 如果是打包工具的话，可以看一下具体减少的大小和使用成本。减少不大的话可以先不引入。
> 
> 还有个问题是，Windows 端的 Sass 环境配置始终是个大问题 emmm，尤其是本地已经有 Python3

PR 合并了，可以重构 sass -> less 了

**Comment by HerbertHe** [comment]
> PR 合并了，可以重构 sass -> less 了

我看时间重构一下，可能部分样式得重写了

**Comment by Vanessa219** [comment]
嗯嗯，重构完多测测。

pnpm 用下来感觉有些依赖要手动添加，npm 就不会，太奇怪了。

**Comment by HerbertHe** [comment]
> 嗯嗯，重构完多测测。
> 
> pnpm 用下来感觉有些依赖要手动添加，npm 就不会，太奇怪了。

依赖的话npm和pnpm都是一样的，可能之前注释掉了sass的包，就得手动添加了。我打算更新测试用例了，这样也能及时发现问题。。。emmm不过得过段时间了，摔着腰住院了😂

**Comment by Vanessa219** [comment]
多休息，祝早日康复。

vditor 没这个问题，我是把思源换成 pnpm，打安装包的时候就残了。

**Comment by HerbertHe** [comment]
哈哈哈，俺也不知道思源源码，没法发现问题哈哈哈哈🙈不过我感觉vditor还是建一个组织仓库集中维护比较好一点

**Comment by Vanessa219** [comment]
就是 electron-builder 的时候有几个项目内没有用到的依赖会导致无法启动。

目前没有太多的精力，后面有空可以迁移一下。

**Comment by HerbertHe** [comment]
目前确实还没遇到过这个问题emmm

**Comment by Vanessa219** [comment]
先关闭了，后期有精力再折腾。
