### ISSUE TITLE
调用 insertValue 后第一次用户输入没有触发 input 回调函数

### ISSUE THREAD

**Issue by lzfee0227** [Vanessa219/vditor#1198]
由于 #1193 还没 fix 就被 closed 了，只好这里重新提一个新的…

这里 https://github.com/Vanessa219/vditor/issues/1193#issuecomment-1066292517 仅仅是提供了一个 **绕过** 而非 **修复** 问题的方法…

---

### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

调用 `insertValue` 后第一次用户输入没有触发 `input` 回调函数，但第二次开始又好了（次数是按 debounce 之后算的）

### 期待的结果

调用 `insertValue` 后第一次用户输入也能触发 `input` 回调函数

### 版本信息

* 版本：`3.8.12`
* 操作系统：macbook m1 版本 12
* 浏览器：chrome 版本 98

### 其他信息

* 调用 `insertValue` 那一次本身是能够正常触发 `input` 回调函数的，并且 `value` 也是对的
* 虽然接下来的第一次用户输入后没有触发 `input`，但如果此时主动调用 `getValue()` 方法拿到的数据依然是对的
* 第二次用户输入开始一切都恢复正常了，带上了中间没触发那次的数据变更

**Comment by Vanessa219** [comment]
e755d8e
