### ISSUE TITLE
代码渲染问题，抛出KaTeX的错误信息。

### ISSUE THREAD

**Issue by xianjerry** [Vanessa219/vditor#12]
输入下面的文本，发出错误：

对象的赋值是个引用的过程，上列中$b=new a; $c=$b; 其实等效于$b=new a; $c=&$b;

[![QJ0V0g.md.jpg](https://s2.ax1x.com/2019/12/06/QJ0V0g.jpg)](https://imgse.com/i/QJ0V0g)

**Comment by Vanessa219** [comment]
& 需要进行转义`\&`

**Comment by xianjerry** [comment]
嗯~ o(*￣▽￣*)o，tanks，从别的markdown拷贝过来的，批量转义一下就行，就是有点担心不能通用。

**Comment by Vanessa219** [comment]
我们严格遵循 commonmark 规范，支持 gfm。请放心使用。
