### ISSUE TITLE
refactor: 抽象toolbar的生成

### ISSUE THREAD

**Issue by HerbertHe** [Vanessa219/vditor#1200]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

在 #1196 中子菜单 RTL 样式的问题，经过分析是 LTR 和 RTL 文本混排的顺序问题。看了 toolbar 的源码，每个子项单独处理了各自部分的渲染逻辑，似乎不太够抽象，如果要做 DOM 修改的话成本很高。但是，如果解决 RTL 的问题，似乎仅能通过使用 span 标签分隔的方式进行完成。

整体的 DOM 修改示例如下：

```html
<button data-mode="ir" class="vditor-menu--current" style="display:flex;">
    <span>即时渲染</span>
    <span>Alt+Ctrl+8</span>
</button>
```

>  需要注意的是，上面的示例中，`block` 的值已经改成了 `flex`（于 #1199 提交）。

文本的注入，如果采取现有的方式将变得异常的麻烦。我还是建议将文本提示和快捷键分开（快捷键符号在不同语言里面是通用的）

通过弹性盒子布局，RTL 支持将会变得自动实现。

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/pull/1199 中已经都处理完了么？

**Comment by HerbertHe** [comment]
> #1199 中已经都处理完重构了么？

aria-label 这个没法处理，语言混排的时候只能用 DOM 来强制阻断，这个依赖此 issue 了， #1199 处理了样式表导致的问题

**Comment by Vanessa219** [comment]
rtl 这个估计有点难，看了 pdf.js 中的 rtl，做的很细致。

**Comment by HerbertHe** [comment]
文本这个混排的话，默认 LTR 除了强制打断，几乎是无解的（RTL的混排逻辑完全不一样。依赖 flex 的布局的话 RTL 是可以自动适配的，但是 Vditor 目前样式表的很多部分就得重写的，比如：单方向的 padding。

**Comment by Vanessa219** [comment]
嗯嗯，加油

**Comment by Vanessa219** [comment]
先关闭了，后期有精力再折腾。
