### ISSUE TITLE
自动补全@

### ISSUE THREAD

**Issue by xinyiPig** [Vanessa219/vditor#1202]
### 你在什么场景下需要该功能？

自动补全@插入到编辑器的值，希望能高亮，给以用户友好的提示，目前设置value为html标签也无法实现

**Comment by 88250** [comment]
大部分 HTML 标签都无法直接插入，解析时会被剔除，估计得想其他方案或者换其他编辑器项目了，抱歉抱歉。

如果实在需要，估计只能魔改 [Lute](https://github.com/88250/lute) 项目，但是不太建议，工作量不小。
