### ISSUE TITLE
不知道为什么总是出现有序列表渲染不上的问题，有一段时间可以渲染，安装version@3.8.13后又不行了

### ISSUE THREAD

**Issue by coldairance** [Vanessa219/vditor#1210]
![2022-04-07_12-38](https://user-images.githubusercontent.com/67637508/162121444-381ed1a3-580d-4bf1-811b-751477f4d3d3.png)

甚至调用 Vditor.preview 同样无法进行渲染
![2022-04-07_12-47](https://user-images.githubusercontent.com/67637508/162122264-dff8edbe-3ea7-46e8-9d9d-009e9ccc894e.png)
我的底层架构为 vite+vue3，是否某些地方发生了冲突？

**Comment by Vanessa219** [comment]
这里ok，不行的话你等 3.8.14 再看看
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/970828/162182396-3763db18-27f5-4108-9859-3629828635ea.png">

**Comment by de1ck** [comment]
+1

**Comment by de1ck** [comment]
排查发现 引用tailwind.css 导致
ol, ul {
    list-style: none; // 这行样式导致有序列表失效
    margin: 0;
    padding: 0;
}
本地可以使用样式覆盖
