### ISSUE TITLE
粗体 渲染问题

### ISSUE THREAD

**Issue by TsLenMo** [Vanessa219/vditor#1211]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

渲染问题，在上面3个模式下都有出现。下面有截图，实际MarkDown。应该就不需要我描述了

````````markdown
## API 面试四连杀：接口如何设计？安全如何保证？签名如何实现？防重如何实现？

**说明：**在实际的业务中，难免会跟第三方系统进行数据的交互与传递，那么如何保证数据在传输过程中的安全呢（防窃取）？除了https的协议之外，能不能加上通用的一套算法以及规范来保证传输的安全性呢？

下面我们就来讨论下常用的一些API设计的安全方法，可能不一定是最好的，有更牛逼的实现方式，但是这篇是我自己的经验分享.



# **一：token 简介**
````````

### 期待的结果

![图片](https://user-images.githubusercontent.com/23328499/162659097-2cf39a79-f1e8-4d7d-9a67-d8d18e2d59f0.png)

### 截屏或录像
![图片](https://user-images.githubusercontent.com/23328499/162658642-5ccabacc-1f5d-44f6-93aa-8e88665c97a1.png)
![图片](https://user-images.githubusercontent.com/23328499/162658690-114d626d-df21-4548-bafc-6764430c03a1.png)

### 版本信息

* 版本：https://ld246.com/guide/markdown 演示站点版本
* 操作系统：Win10
* 浏览器：火狐，Edge均能复现

**Comment by 88250** [comment]
就目前的 Markdown 规范（CommonMark/GFM）来说，不解析渲染为粗体是正确的，细节可参考这里的分析 https://ld246.com/article/1597581380183

**Comment by TsLenMo** [comment]
> 就目前的 Markdown 规范（CommonMark/GFM）来说，不解析渲染为粗体是正确的，细节可参考这里的分析 https://ld246.com/article/1597581380183

好的，那应该就没问题了。
看来是别的编辑器没有按规范来。
