### ISSUE TITLE
在markdown中输入input button的代码渲染后会变成输入框和按钮

### ISSUE THREAD

**Issue by zwxs** [Vanessa219/vditor#1212]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

````````markdown
在markdown中输入input button的代码渲染后会变成输入框和按钮

<input>

<button>

````````

### 期待的结果

希望可以不渲染这些标签等HTML代码

### 截屏或录像

![image](https://user-images.githubusercontent.com/18496323/162710114-85f9805e-a0ca-468d-a9c9-bd6bf7ccad10.png)

### 版本信息

* 版本： 100.0.4896.75（正式版本） （64 位）
* 操作系统：window系统
* 浏览器：chrome

**Comment by 88250** [comment]
这是符合 Markdown 标准的，如果不需要请自行过滤。

**Comment by zwxs** [comment]
哦哦 那请问如何过滤呢

**Comment by 88250** [comment]
@zwxs 找一个 XSS 相关的库过滤。

**Comment by dreamncn** [comment]
如果需要直接显示html标签，可以使用代码块解决。

```html
在markdown中输入input button的代码渲染后会变成输入框和按钮

<input>

<button>
```
