### ISSUE TITLE
实时协作

### ISSUE THREAD

**Issue by wideweide** [Vanessa219/vditor#1213]
### 你在什么场景下需要该功能？

* 多个小伙伴突击完成一篇文稿
* 实时查看一篇文稿被修改的状态
* 别的编辑器有的，vditor也应该有:-)

### 描述最优的解决方案 

* 基于sockjs进行通讯，可兼容部分不支持websocket通讯的场景
* 选择开源的消息通讯组件，如https://centrifugal.dev，可选择的成熟产品很多
* 参考实现：https://etherpad.org/ 轻量级，但编辑器功能一般

### 描述候选解决方案

* 全部插件支持难度及工作量较大，能支持基础的编辑工作也好，不支持的组件协作时禁用掉，避免数据冲突

**Comment by 88250** [comment]
之前考虑过 https://github.com/Vanessa219/vditor/issues/699 目前暂时没有精力实现，感谢提议。
