### ISSUE TITLE
extraData动态修改

### ISSUE THREAD

**Issue by wight3** [Vanessa219/vditor#1214]
### 你在什么场景下需要该功能？

做图片上传oss云存储时需要在表单中动态添加token等信息，现在如果直传需要file(), validate()中异步请求获取token后直接赋值给vditor.vditor.options.upload.extraData

### 描述最优的解决方案 
修改 extraData成 extraData?(files: File[]): { [key: string]: string | Blob } | Promise<{[key: string]: string | Blob}>;

在extraData()中异步获取后端的额外信息并直接赋值给form表单
```javascript
if (vditor.options.upload.extraData) {
          const extraData = await vditor.options.upload.extraData(fileList);
          for (const key of Object.keys(extraData)) {
            formData.append(key, extraData[key]);
          }
        }
```

**Comment by Vanessa219** [comment]
已经写好的话可以直接 PR。记得判断类型，还有修改 readme 😊
