### ISSUE TITLE
sv 模式 setValue 导致状态错误

### ISSUE THREAD

**Issue by xkx0215** [Vanessa219/vditor#1215]
### 编辑模式

* `sv` 分屏编辑预览模式

### 描述问题

setValue后工具栏功能失效，如表格、列表等等。
手动输入修改编辑框内容或者切换编辑模式后，功能恢复正常。
官方demo也有同样情况。

### 版本信息

* 版本：3.8.13
* 操作系统：windows
* 浏览器：chrome 版本 100

**Comment by Vanessa219** [comment]
参数是什么？

**Comment by xkx0215** [comment]
> 参数是什么？

https://b3log.org/vditor/demo/method-CRUD.html
可以看这个demo，也有一样的问题

**Comment by Vanessa219** [comment]
没看出问题，可以再详细描述一下么？

**Comment by xkx0215** [comment]
> 没看出问题，可以再详细描述一下么？

https://user-images.githubusercontent.com/51985134/165007686-b4c78526-ae46-43e2-b4c8-e68ade7692ce.mp4

setValue后添加表格、列表等点击无效。如果手动修改输入内容，功能又恢复正常了。

**Comment by xkx0215** [comment]
> 没看出问题，可以再详细描述一下么？

https://user-images.githubusercontent.com/51985134/165007686-b4c78526-ae46-43e2-b4c8-e68ade7692ce.mp4

setValue后添加表格、列表等点击无效。如果手动修改输入内容，功能又恢复正常了。

**Comment by xkx0215** [comment]
> 没看出问题，可以再详细描述一下么？
![idsgm-kv4w3](https://user-images.githubusercontent.com/51985134/165009069-c0c398bb-e528-440e-a77b-cc8ad37cbd5f.gif)
setValue后，工具栏添加表格等功能点击无效，重新修改输入框值后，功能恢复正常

**Comment by yep0908** [comment]
初始init时，setValue传入值后，工具栏点击无效，可以触发事件，但是不能正常渲染，重新输入修改值，功能恢复正常

**Comment by Vanessa219** [comment]
是不是 CSS 被覆盖了？
