### ISSUE TITLE
代码块功能添加代码语言后显示高度异常

### ISSUE THREAD

**Issue by jiangzhaojie22** [Vanessa219/vditor#1217]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题
未选择代码语言显示正常:
![image](https://user-images.githubusercontent.com/66808427/165458411-c475c646-a518-40fc-abc2-13d4c089ae76.png)
选择代码语言后高度坍塌了:
![image](https://user-images.githubusercontent.com/66808427/165458690-2b568958-4420-4461-a553-5904e55bbb76.png)

### 期待的结果

选择代码语言后高度正常,完整显示代码块

### 版本信息

* 版本：3.8.13
* 操作系统：windows11
* 浏览器：chrome

**Comment by Vanessa219** [comment]
无法重现，还麻烦录屏详述重现步骤。
https://user-images.githubusercontent.com/970828/167062573-c49a0b18-c50a-4163-91b0-3f318d18ce72.mp4
