### ISSUE TITLE
高度设置为 string 时，大纲锚点失效

### ISSUE THREAD

**Issue by de1ck** [Vanessa219/vditor#1218]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
````````

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

**Comment by Vanessa219** [comment]
这里无法重现，我先关闭了。如果可以重现请跟帖描述详细步骤

https://user-images.githubusercontent.com/970828/167062405-202f368d-ac4e-43ba-8cfa-6eff594fa2d8.mp4

**Comment by de1ck** [comment]
在通过 cala(100vh - xpx); 设置下，滚动失效
目前通过 hash锚点实现该动能
after() {
          Vditor.outlineRender(previewElement!, outlineElement!);
          if (outlineElement?.innerText.trim() !== '') {
            outlineElement!.style.display = 'block';
            outlineElement?.addEventListener('click', (event) => {
              let target = event.target as HTMLElement | null;
              while (target) {
                const id = target.getAttribute('data-target-id');
                console.log(target, id);
                if (target.classList.contains('vditor-outline__action')) {
                  break;
                } else if (id) {
                  window.location.hash = id;
                  break;
                }
                target = target.parentElement;
              }
            }, {
              capture: true,
              // passive: true,
            });
          }
        },
