### ISSUE TITLE
图片能缩放吗？按比例，或者手动设置值。

### ISSUE THREAD

**Issue by mike-boost** [Vanessa219/vditor#1222]
### 你在什么场景下需要该功能？
编辑或插入图片

### 描述最优的解决方案 

右键点击图片，可选按照比例缩放图片

### 描述候选解决方案

添加设置图片大小的参数

**Comment by 88250** [comment]
Markdown 对这个没有标准，通过 `<img>` 实现的话跨平台兼容性堪忧，所以暂时无法支持。
