### ISSUE TITLE
图片粘贴

### ISSUE THREAD

**Issue by ConanJordan** [Vanessa219/vditor#1224]
### 你在什么场景下需要该功能？
使用微信或其他截图工具截图后，将ClipBoard里的内容写入编辑区，并实时渲染。

### 描述最优的解决方案 
将图片内容转换成Base64格式的文本，写入编辑区，并交由引擎渲染。
[tui.editor](https://github.com/nhn/tui.editor)已实现了此功能。

### 其他信息
我想尝试在**paste**事件监听里添加一种pattern,即`clipboardData.types == 'file'`，但不知道具体要修改哪个js文件。
如果方案可行，请给予帮助，万分感谢。

**Comment by Vanessa219** [comment]
fixBrowserBehavior.ts 中的 paste

**Comment by ConanJordan** [comment]
创始人你好，
经你的指点，我找到了要目标文件并做了部分修改。暂时未测出问题。
有空的话劳烦看一下，再次感谢。
