### ISSUE TITLE
视频渲染问题

### ISSUE THREAD

**Issue by ZohyCao** [Vanessa219/vditor#1226]
### 描述问题
多媒体视频渲染后，长宽比例不协调，且不支持全屏播放等功能

````````markdown
参考[【Advanced控制理论】8_LQR 控制器_状态空间系统Matlab/Simulink建模分析_哔哩哔哩_bilibili](https://www.bilibili.com/video/BV1RW411q7FD)
````````

### 期待的结果
渲染结果能够自适应纵横比，或者尽量保持较为正常的纵横比，感觉大多数情况视频都被压扁了。
如果可以支持全屏播放，就更好了

### 截屏或录像
![image](https://user-images.githubusercontent.com/30723386/167811053-854dfc53-85e6-4f0d-98d7-5b7daae1a9e6.png)
![image](https://user-images.githubusercontent.com/30723386/167811158-140b7775-8a68-4877-a653-fec46420cd6a.png)

### 版本信息

* 版本：3.7.4
* 操作系统：win10\win11
* 浏览器：microsoft edge

**Comment by Vanessa219** [comment]
md 没有类似的语法，可以直接用 HTML 来进行设置
