### ISSUE TITLE
回车换行，getHtml()获取不到空的换行是自动排除了嘛

### ISSUE THREAD

**Issue by dukang0417** [Vanessa219/vditor#1227]
生成的 md内容 是# 啊实打实大苏打

## 啊大苏打送到家从vv从v从

飒飒大大十分是德国的发表

发士大夫DVD是山豆根士大夫v的方向

色发射点发的犯罪手法 
渲染出来后就是没有回车的，使用getHtml获取到的东西也是没有空的换行

**Comment by 88250** [comment]
Markdown 渲染没有空行这个元素。
