### ISSUE TITLE
使用删除图标删除后，大纲没有自动更新

### ISSUE THREAD

**Issue by de1ck** [Vanessa219/vditor#1228]
![image](https://user-images.githubusercontent.com/26627486/168044561-7816536b-55aa-4eab-bd47-ed794a86b2c8.png)

所见即所得模式下：

1. 使用删除icon删除后，大纲没有自动更新

2. 点击 标题后显示操作工具栏，滚动后工具栏一直显示，删除时，删除之前点中的标题
这里是否需要滚动后隐藏工具栏呢？

**Comment by Vanessa219** [comment]
第二个问题设计如此
