### ISSUE TITLE
分屏预览（SV）模式下，表格单元格内容里不能输入标签类文档，比如换行的`<br/>,

### ISSUE THREAD

**Issue by blueskyawen** [Vanessa219/vditor#1234]
### 编辑模式

* `sv` 分屏编辑预览模式

### 描述问题

表格单元格内容里不能输入标签类文档，比如换行的`<br/>,

### 期待的结果

表格单元格内容里可以输入标签类文档，比如换行的`<br/>,

**Comment by 88250** [comment]
请关注 https://github.com/Vanessa219/vditor/issues/1204
