### ISSUE TITLE
我想开发一个拖拽文字内容的需求，请求一个思路

### ISSUE THREAD

**Issue by cmcQDGCS** [Vanessa219/vditor#1236]
### 你在什么场景下需要该功能？

1. 需要拖拽其他地方的文字内容到Vditor编辑器中
2. 自由拖拽编辑器中的内容

### 描述最优的解决方案 

拖拽其他地方的文字内容到Vditor编辑器中
例如：
问题1：
![image](https://user-images.githubusercontent.com/64002336/168707935-e2ad47ac-c6b3-4cc4-93ce-eb4fefb168b1.png)
问题2：
![image](https://user-images.githubusercontent.com/64002336/168707766-e19a028a-870f-4dd4-b73f-753f16cd14af.png)

### 描述候选解决方案

我看了文档但是没有思路去开发一个这样的功能，希望可以提供一个思路或者api 

### 其他信息

感激不尽！

**Comment by Vanessa219** [comment]
可以研究一下 drag 相关的 API
