### ISSUE TITLE
首行无法输入空格 或者缩进  如果首行有多个缩进会自动变成代码块

### ISSUE THREAD

**Issue by zwxs** [Vanessa219/vditor#1238]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

````````markdown

````````

### 版本信息

* 版本：3.8.11
* 操作系统：window 
* 浏览器：chrome浏览器

**Comment by Vanessa219** [comment]
这是 CommonMark 规范

**Comment by ffanglaili** [comment]
能不能解决或者配置？

**Comment by df257** [comment]
加一，我看lute是有关闭选项的，但vditor好像没有做关联的样子
