### ISSUE TITLE
请问怎么样可以达到初始化就在预览模式上

### ISSUE THREAD

**Issue by r0ckysec** [Vanessa219/vditor#1243]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

编辑模式分为 3种，但是我想要页面初始化就在预览模式上，只停留在预览模式不能编辑的效果
类似下图，直接页面加载就在预览模式

### 期待的结果

![image](https://user-images.githubusercontent.com/44518337/170651412-a2bc5569-516d-4bbf-9250-a09b7fc7ec26.png)

### 截屏或录像

![image](https://user-images.githubusercontent.com/44518337/170651437-e134470f-a7ec-4f29-a6ec-224c3ba3a0e0.png)

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

**Comment by Vanessa219** [comment]
https://ld246.com/article/1549638745630#static-methods

**Comment by meguoe** [comment]
初始化就在预览模式上你实现了吗？我现在也遇到这个需求。。。

**Comment by Jinpeng-ctrl** [comment]
有人实现了吗?

**Comment by Jinpeng-ctrl** [comment]
> 有人实现了吗?
在需要的地方使用下面代码
 const buttons = document.querySelectorAll(".vditor-toolbar button");
                                    buttons.forEach(button=>{
                                        if (button.getAttribute("data-type")==="preview"){
                                            button.click()
                                        }
                                    })
