### ISSUE TITLE
锚点问题

### ISSUE THREAD

**Issue by coldairance** [Vanessa219/vditor#1253]
我注意到锚点ID添加不是递归的，这样会导致索引不到正确的标题，如

```
# 标题一
## 简介
## 使用方法
# 标题二
## 简介
## 使用方法

渲染后的HTML大致为
<h1 id="标题一">标题一</h1>
<h2 id="简介">简介</h2>
<h2 id="使用方法">使用方法</h2>
<h1 id="标题二">标题二</h1>
<h2 id="简介">简介</h2>
<h2 id="使用方法">使用方法</h2>
```

若点击目录的 **标题二>简介** ，则会索引到 **标题一>简介**，我希望渲染得到的HTML为

```
<h1 id="标题一">标题一</h1>
<h2 id="标题一简介">简介</h2>
<h2 id="标题一使用方法">使用方法</h2>
<h1 id="标题二">标题二</h1>
<h2 id="标题二简介">简介</h2>
<h2 id="标题二使用方法">使用方法</h2>
```

同时需要修改目录 a标签的`href`属性为对应`#id`。

即，我希望在`Vditor.preview()`函数的`anchor`添加另外一个支持递归渲染标题的模式。

**Comment by Vanessa219** [comment]
这里是没有问题的哦

<img width="398" alt="image" src="https://user-images.githubusercontent.com/970828/174702706-09a1be41-8026-4a86-9079-c83e87d2deea.png">

**Comment by coldairance** [comment]
# 我说的是`Vditor.preview()`方法
## 这是编辑器
![image](https://user-images.githubusercontent.com/67637508/174704220-d37f3233-1076-4b96-b814-5df855bf0223.png)
## 这是`Vditor.preview()`方法渲染之后
![image](https://user-images.githubusercontent.com/67637508/174704383-95852392-c7d1-4814-836c-4ef3212b209c.png)
## 由于我的目录是自己做的，而我是根据id来设置 a 标签的 `href` 属性的
![image](https://user-images.githubusercontent.com/67637508/174704845-787a1d03-4aca-4e4a-8f68-7ac589497f0b.png)
## 您可以自己去我这篇文章尝试点击一下这两个目录
![image](https://user-images.githubusercontent.com/67637508/174705009-6195f668-30d8-4b08-a506-26c36ddeca5a.png)
它的网址是：http://www.coldairance.com/article/eecfad96-139c-4c0c-9152-df2976b90d26
另外吐槽一下为什么第一次渲染这么慢，还是我的问题还是`Vditor.preview()`方法的问题呢？

**Comment by Vanessa219** [comment]
你可以对比一下代码中的 render.html
