### ISSUE TITLE
ctrl+z快捷键会影响页面其他位置的ul元素

### ISSUE THREAD

**Issue by Marstonchan** [Vanessa219/vditor#1254]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

1. 使用的是wysiwyg模式，其他模式是否存在问题不清楚。
2. 在编辑之后，点击页面其他位置的ul(vditor失焦)，再使用ctrl+z快捷键，会改变ul中的内容。如向该被点击的ul元素挂载data-tight，data-marker，data-block等属性，向其中的li元素挂载data-marker，向被点击的li元素中插入<wbr>。
3. 除此之外，还会移除该ul元素下的所有非li子级标签，若该ul元素为空，或该ul元素下的子级标签全不为li，则会直接移除整个ul元素。

### 期待的结果

期望vditor不要影响到页面中其他位置的dom元素，以免造成困扰。

### 截屏或录像

![vditor-issue](https://user-images.githubusercontent.com/65653843/174865886-f2d3f24b-901d-4c85-9bf1-fd6bf520ac4c.gif)

### 版本信息

* 版本：3.8.15
* 操作系统：Windows10
* 浏览器：Chrome

**Comment by Vanessa219** [comment]
ctrl+z 以后列表正常，如果可以的话麻烦修改 https://github.com/Vanessa219/vditor/blob/fdc7aea970e4044a172a4515c4c6af38bbda8abd/demo/index.html 后看看是否能重现，如果可以重现的话，贴一下代码。

https://user-images.githubusercontent.com/970828/175286802-2f6f870c-bb79-45dd-ad42-46308f778654.mp4
