### ISSUE TITLE
代码块编辑的时候内容重复

### ISSUE THREAD

**Issue by littleyanglovegithub** [Vanessa219/vditor#1256]
### 编辑模式
未编辑的时候：
![image](https://user-images.githubusercontent.com/26239080/176326437-ba31b7fa-ecb7-46d6-ac93-02bd4c4fee75.png)
编辑的时候：
![image](https://user-images.githubusercontent.com/26239080/176326502-590561e1-7171-4b07-a8bc-9d1ba8ddf2e4.png)

**Comment by 88250** [comment]
下面是预览区域。

**Comment by bl-sky** [comment]
大佬有办法合成一个吗？预览和编辑合成一个实时编辑渲染的区域

**Comment by Vanessa219** [comment]
目前没有精力，可参考思源笔记中的进行修改。
