### ISSUE TITLE
全屏或者取消全屏的时候能触发相应的回调吗?

### ISSUE THREAD

**Issue by HengCC** [Vanessa219/vditor#1258]
### 你在什么场景下需要该功能？

现在全屏模式和外面的CSS有一些冲突. 导致toolbar无法吸顶.   但是外面的整个布局又不太好动.. 

### 描述最优的解决方案 

有没有可能全屏和取消全屏的时候触发一些事件. 监听事件后 通知外部容器动态的去调整样式. 

### 描述候选解决方案

增加toolbar的一些按钮事件机制

### 其他信息

无

**Comment by Vanessa219** [comment]
全屏会增加一个 css，你可以看看，然后重置 css
