### ISSUE TITLE
Line spacing at BOLD

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#126]
![Screen Shot 2020-02-09 at 6 12 06 AM](https://user-images.githubusercontent.com/15811943/74101801-48684700-4b03-11ea-83c8-9d356391c0bf.png)

**Comment by Vanessa219** [comment]
![image](https://user-images.githubusercontent.com/970828/74102168-f7e10000-4b7b-11ea-9ccb-65097c6cb44b.png)

which browser and version?

**Comment by jakekwak** [comment]
Macbook pro
![Screen Shot 2020-02-09 at 6 44 53 AM](https://user-images.githubusercontent.com/15811943/74102279-b6167200-4b07-11ea-8def-96031fabc9d2.png)

**Comment by Vanessa219** [comment]
this a hacpai.com problem, pls refresh it
