### ISSUE TITLE
SV 模式表格中输入 `<` 丢失光标

### ISSUE THREAD

**Issue by HengCC** [Vanessa219/vditor#1260]
### 编辑模式

* `sv` 分屏编辑预览模式

### 描述问题
复现步骤:
1. 插入任意一表格
2. 表格任意一个单元格输入非"<"和">"内容
3. 在内容前面输入"<" , 继续输入任何字符. 光标都会发生跳转.

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
````````

### 期待的结果
本来是想输入html标签用来改变文本颜色. 但是输入"<" 后就无法在输入. 因为光标漂移

### 截屏或录像

https://user-images.githubusercontent.com/6167532/177091195-8efed4a4-a59c-4497-82b6-a3a8250a92aa.mp4

### 版本信息

* 版本：3.8.15
* 操作系统：
* 浏览器：

**Comment by Vanessa219** [comment]
`<` 需进行转义处理 @88250

**Comment by HengCC** [comment]
@Vanessa219 有计划什么时候修吗?  或者有什么临时的解决方案可以用的呢?

**Comment by Vanessa219** [comment]
> @Vanessa219 有计划什么时候修吗? 或者有什么临时的解决方案可以用的呢?

这个还没有计划，需等 @88250 有空了才行。

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/1319
