### ISSUE TITLE
《文档增量修改事件》方案

### ISSUE THREAD

**Issue by xmings** [Vanessa219/vditor#1261]
### 你在什么场景下需要该功能？

长篇文章编辑时每次输入后需要保存内容到库，每次都是全量保存导致效率低下

### 描述最优的解决方案 

建议提供获取增量变更的方法或者事件，每一行都有一个唯一的非连续的行Id
- 如果修改了已存在的行，就告知要“删除旧行的ID”和“增加新行的ID、内容、上一行的ID”，用户可以按这些信息去数据库执行删除和插入动作，并把下一行的”上一行ID“列为新行的ID
- 如果在某个两个行之间新插入新行，就告知“新行的ID、内容、上一行的ID”，用户只需要在数据库把新行插入数据库，并把下一行的”上一行ID“列设置为新行的ID即可

> 如果行id的可以保持一定的顺序又可以足够插入新行就完美了，这样每次加载时直接排序就能组织好文档而不需要递归查询

**Comment by 88250** [comment]
感谢提议，但是解析器里没有定义“行”，估计做不了。

这个如果实在需要的话，可以参考一下[思源笔记](https://github.com/siyuan-note/siyuan)的方案，使用分块+局部事务操作实现，但是整个方案比较复杂，Vditor 还是作为一个文本编辑器比较好一点。
