### ISSUE TITLE
所见即所得和即使渲染只有空格输入时，不会触发 input 事件

### ISSUE THREAD

**Issue by 1962247851** [Vanessa219/vditor#1263]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式

### 描述问题

在编辑器输入框有内容时（字数统计不为0）
- 全选后输入任意空格，编辑器内容清空，但不触发input回调，并且右上角的字数统计无变化
- 全选后输入回车，编辑器内容清空，回调 `\n` ，右上角字数统计变为0

### 期待的结果

全选后输入空格正常回调 '\n'

### 截屏或录像

https://user-images.githubusercontent.com/43869694/178147342-3ef6d90b-ce89-4910-bcc2-6b3602b5fc3f.mp4

### 版本信息

* 版本：3.8.15
* 操作系统：Win10
* 浏览器：Edge

### 其他信息

"nuxt": "^2.15.8",
 "vue": "^2.6.14",

**Comment by Vanessa219** [comment]
这是 CommonMark 规范，段前和段尾的空格会被移除。

**Comment by 1962247851** [comment]
不好意思，我改正一下，分屏编辑模式下会触发回调

**Comment by Vanessa219** [comment]
你的意思是 ir 下输入空格会触发 input，但是 wysiwyg 不会触发？
按道理是应该触发 input 事件的，因为这是用户在 input。

**Comment by 1962247851** [comment]
昨天视频传不上去
在分屏预览模式下会触发input回调，而在所见即所得和及时渲染这两个模式里不会触发

https://user-images.githubusercontent.com/43869694/178635697-21ded1ab-d45a-4a02-968f-95fee2c24d35.mp4

**Comment by Vanessa219** [comment]
收到，已修改 issue 标题，后期修复
