### ISSUE TITLE
链接中，会强制将&reg解析为 ® 字符

### ISSUE THREAD

**Issue by Twistedviv** [Vanessa219/vditor#1264]
### 编辑模式
* `ir` 即时渲染模式

### 描述问题

当输入以下内容时，会将 &reg 显示为 ® 符号。
但我理解是不是应该在 &reg 后方加上分号才转义展示

````````markdown
[link](http://baidu.com?q=test&region=china)
````````

### 期待的结果

仅在 &reg 后方紧跟分号时才展示 ® 符号

### 截屏或录像
![image](https://user-images.githubusercontent.com/52268514/178514899-763c5d68-ecb1-4650-92b6-a2ff48b73bec.png)

### 版本信息

* 版本：3.8.11
* 操作系统：MacOS
* 浏览器：Chrome

### 其他信息
该问题会在**使用链接语法时**稳定复现

**Comment by Twistedviv** [comment]
小姐姐，有预计修复时间吗 ：）

**Comment by Vanessa219** [comment]
这块主要是 @88250 来修。

**Comment by Twistedviv** [comment]
@88250 你好，这个issue是否还在跟进呢
