### ISSUE TITLE
自定义Emoji显示异常

### ISSUE THREAD

**Issue by tobylai-toby** [Vanessa219/vditor#1267]
### 编辑模式

* `ir` 即时渲染模式

### 描述问题

````````markdown
:homo:
````````

#### 自定义emoji时出现的问题
按照文档，`hint.emojiPath`已经设置，自动补全emoji里的图像没有问题，可是显示出来的emoji使用的路径还是unpkg，导致图裂了
想要正常显示图像，是否有临时解决办法？
`hint.emoji`加了一条：
`"homo": "${emojiSite}/homo.gif",`

### 截屏或录像

<img width="225" alt="image" src="https://user-images.githubusercontent.com/60289741/179900048-0c53c082-2cf1-4d40-9437-193feebe02c1.png">
<img width="131" alt="image" src="https://user-images.githubusercontent.com/60289741/179900069-eada378a-cbd1-4f10-8de5-59aa5068f0f7.png">

### 版本信息

* 版本：'3.8.15'
* 操作系统：Windows 11 Version 21H2 (Build 22000.795)
* 浏览器：103.0.5060.114 (正式版本) （64 位） (cohort: Stable)

**Comment by tobylai-toby** [comment]
这里是要加上自定义cdn吗？我看到文档文档写着表情图片地址`emojiPath`

**Comment by Vanessa219** [comment]
参照以下进行设置
```
      emojiPath: 'https://unpkg.com/vditor@1.8.3/dist/images/emoji',
      emojiTail: '<a href="https://ld246.com/settings/function" target="_blank">设置常用表情</a>',
      emoji: {
        'sd': '💔',
        'j': 'https://unpkg.com/vditor@1.3.1/dist/images/emoji/j.png',
      },
```

**Comment by lizwxup** [comment]
emojiPath 这个地址可以为本地项目的相对路径吗？还是必须为线上地址？

**Comment by Vanessa219** [comment]
都可以的
