### ISSUE TITLE
代码块自动补全会包含链接引用和脚注

### ISSUE THREAD

**Issue by Polepoint-CHN** [Vanessa219/vditor#1269]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

问题1：
输入代码块语法，会自动包裹到不必要的内容。
如：1、当页面有脚注时，输入```会自动将脚注包裹在代码块中。
       2、粘贴进编辑器的文本，在前方输入代码块起始标记\`\`\`时，自动补充的结束标记\`\`\`，只能将第一行文本包裹在代码块中，而不是整个粘贴进来的文本。（这个现象是偶现的）

问题2：
只想要删除结束标记\```，把他重新写在正确的位置。但是在删除时，代码块开始标记\```也会同时被删除，导致整个代码块标记都被删掉。

### 期待的结果

1、代码块开始标记和结束标记的位置可以由用户自己输入。而不是自动生成结束标记，导致不必要的文本被包裹在代码块中。
2、删除代码块结束标记时，不会导致代码块开始标记```被删掉。

### 截屏或录像

https://user-images.githubusercontent.com/92731086/181038004-9af1e439-fbbb-49d3-a213-f33a720e4d67.mp4

### 版本信息

* 版本：3.8.15
* 操作系统：windows
* 浏览器：chrome

### 其他信息

官方demo中存在同样问题。

如有临时对策可以暂时屏蔽这个问题，还请大佬指点一下！

**Comment by lizhangyi** [comment]
同问，我们项目也遇到同样的问题~ 不知道该怎么处理了。。

**Comment by Polepoint-CHN** [comment]
@Vanessa219 我升级到了3.8.17版本，发现代码块包裹脚注的问题仍然存在。同时还新增了几个问题：
1、编辑输入内容时，编辑栏内的文本会重复输入很多份，并包裹在代码块中。
2、当输入文本内容后，编辑页面会卡死，导致页面崩溃。
3、删除代码块结束标记\```，仍然不能结束掉代码块。并且代码块开始标记\```同样会被删掉。
4、ir模式下，输入\```标记，再删除掉，脚注会跑到光标位置。

问题视频：
问题1、2：

https://user-images.githubusercontent.com/92731086/183463048-b53bce68-6e0f-4391-8b33-0e8187e8bd7b.mp4

问题3：

https://user-images.githubusercontent.com/92731086/183462988-2ffd83f1-3e80-4a69-9cc4-e41065403669.mp4

问题4：

https://user-images.githubusercontent.com/92731086/183464305-b363b541-c031-4914-98a0-17c44ff0094c.mp4



期待的结果
1、代码块开始标记和结束标记的位置可以由用户自己输入。而不是自动生成结束标记，导致不必要的文本被包裹在代码块中。
2、删除代码块结束标记时，不会导致代码块开始标记```被删掉。

**如果这个问题较难修复，是否可以有暂时禁用代码块补全功能的方式呢？**
希望大佬指点一下，感谢！

编辑模式
wysiwyg 所见即所得模式
ir 即时渲染模式
sv 分屏编辑预览模式

版本信息
版本：3.8.17
操作系统：windows10
浏览器：chrome

**Comment by 88250** [comment]
最近可能没有时间解决这个问题了，抱歉抱歉。
