### ISSUE TITLE
more keyboard shortcut after ctrl+h

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#127]
any shortcut key for selecting heading(when starting, i don't want to use mouse)
![Screen Shot 2020-02-09 at 6 38 32 AM](https://user-images.githubusercontent.com/15811943/74102221-0b05b880-4b07-11ea-8bef-2280b7747ea7.png)

[MS Word style](https://www.knowledgewave.com/blog/msoffice/word/microsoft-word-2010-shortcuts-for-applying-heading-styles.html)

**Comment by jakekwak** [comment]
I think we need UI improvement(suggestion) after fixing the bug.

**Comment by Vanessa219** [comment]
yes, we need modern UI. thank you suggestion
