### ISSUE TITLE
当返回参数格式完全正确时，js文件报错不知道是不是bug

### ISSUE THREAD

**Issue by JanYork** [Vanessa219/vditor#1271]
我将vditor封装非组件，在后端返回值与官方文档完全一致时，vditor的js文件出现报错，原因是js中开头!function（e，t）这个函数的开始就没有e和t两个元素，现实未定义，但是在初始化vditor时（我打了断点），after函数可以正常使用这个js..

**Comment by Vanessa219** [comment]
new 以后立即执行的操作需在 after 回掉中执行。否则 js 加载不完整。
