### ISSUE TITLE
请问vditor的文本可以实现双向绑定功能吗？

### ISSUE THREAD

**Issue by Cloud-Iris** [Vanessa219/vditor#1272]
### 你在什么场景下需要该功能？

我在尝试基于vditor写一个多人协作即时文档，因此很明显我需要在某一个恰当的时刻为该文本编辑器赋值

### 描述最优的解决方案 

我希望您可以像mavonEditor那样直接给出一个可以赋值的属性or文本，在我从官方的手册上并没有找到，谢谢您！

**Comment by ccitsxy** [comment]
如果是Vue3的话，可以这样
```vue
// VueVditor.vue
<script setup lang="ts">
import { onMounted, ref, watch, toRaw, onUnmounted, unref } from 'vue'
import Vditor from 'vditor'
import 'vditor/dist/index.css'

const emit = defineEmits([
  'update:modelValue',
  'after',
  'focus',
  'blur',
  'esc',
  'ctrlEnter',
  'select',
])

const props = defineProps({
  options: {
    type: Object,
    default() {
      return {}
    },
  },
  modelValue: {
    type: String,
    default: '',
  },
})

const contentEditor = ref<Vditor | null>(null)
const editorRef = ref<HTMLElement | null>(null)

onMounted(() => {
  contentEditor.value = new Vditor(editorRef.value as HTMLElement, {
    ...props.options,
    value: props.modelValue,
    cache: {
      enable: false,
    },
    fullscreen: {
      index: 3000,
    },
    after() {
      emit('after', toRaw(contentEditor.value))
    },
    input(value: string) {
      emit('update:modelValue', value)
    },
    focus(value: string) {
      emit('focus', value)
    },
    blur(value: string) {
      emit('blur', value)
    },
    esc(value: string) {
      emit('esc', value)
    },
    ctrlEnter(value: string) {
      emit('ctrlEnter', value)
    },
    select(value: string) {
      emit('select', value)
    },
  })
})

watch(
  () => props.modelValue,
  (newVal) => {
    if (newVal !== contentEditor.value?.getValue()) {
      contentEditor.value?.setValue(newVal)
    }
  }
)

onUnmounted(() => {
  const editorInstance = unref(contentEditor)
  if (!editorInstance) return
  try {
    editorInstance?.destroy?.()
  } catch (error) {
    console.log(error)
  }
})
</script>

<template>
  <div ref="editorRef"></div>
</template>

```
使用例子
```vue
<script setup lang="ts">
import { ref } from 'vue'

const text = ref('')
</script>

<template>
  <div>
    <h1>{{ text }}</h1>
    <vue-vditor
      v-model="text"
      :options="{
        height: 480,
      }"
    />
  </div>
</template>
```
截图
![image](https://user-images.githubusercontent.com/39737565/182178368-fee4a9da-d4c5-4fc1-ade7-95cc2ba0c350.png)

**Comment by hashqueue** [comment]
> 如果是Vue3的话，可以这样
> 
> ```
> // VueVditor.vue
> <script setup lang="ts">
> import { onMounted, ref, watch, toRaw, onUnmounted, unref } from 'vue'
> import Vditor from 'vditor'
> import 'vditor/dist/index.css'
> 
> const emit = defineEmits([
>   'update:modelValue',
>   'after',
>   'focus',
>   'blur',
>   'esc',
>   'ctrlEnter',
>   'select',
> ])
> 
> const props = defineProps({
>   options: {
>     type: Object,
>     default() {
>       return {}
>     },
>   },
>   modelValue: {
>     type: String,
>     default: '',
>   },
> })
> 
> const contentEditor = ref<Vditor | null>(null)
> const editorRef = ref<HTMLElement | null>(null)
> 
> onMounted(() => {
>   contentEditor.value = new Vditor(editorRef.value as HTMLElement, {
>     ...props.options,
>     value: props.modelValue,
>     cache: {
>       enable: false,
>     },
>     fullscreen: {
>       index: 3000,
>     },
>     after() {
>       emit('after', toRaw(contentEditor.value))
>     },
>     input(value: string) {
>       emit('update:modelValue', value)
>     },
>     focus(value: string) {
>       emit('focus', value)
>     },
>     blur(value: string) {
>       emit('blur', value)
>     },
>     esc(value: string) {
>       emit('esc', value)
>     },
>     ctrlEnter(value: string) {
>       emit('ctrlEnter', value)
>     },
>     select(value: string) {
>       emit('select', value)
>     },
>   })
> })
> 
> watch(
>   () => props.modelValue,
>   (newVal) => {
>     if (newVal !== contentEditor.value?.getValue()) {
>       contentEditor.value?.setValue(newVal)
>     }
>   }
> )
> 
> onUnmounted(() => {
>   const editorInstance = unref(contentEditor)
>   if (!editorInstance) return
>   try {
>     editorInstance?.destroy?.()
>   } catch (error) {
>     console.log(error)
>   }
> })
> </script>
> 
> <template>
>   <div ref="editorRef"></div>
> </template>
> ```
> 
> 使用例子
> 
> ```
> <script setup lang="ts">
> import { ref } from 'vue'
> 
> const text = ref('')
> </script>
> 
> <template>
>   <div>
>     <h1>{{ text }}</h1>
>     <vue-vditor
>       v-model="text"
>       :options="{
>         height: 480,
>       }"
>     />
>   </div>
> </template>
> ```
> 
> 截图 ![image](https://user-images.githubusercontent.com/39737565/182178368-fee4a9da-d4c5-4fc1-ade7-95cc2ba0c350.png)



> 如果是Vue3的话，可以这样
> 
> ```
> // VueVditor.vue
> <script setup lang="ts">
> import { onMounted, ref, watch, toRaw, onUnmounted, unref } from 'vue'
> import Vditor from 'vditor'
> import 'vditor/dist/index.css'
> 
> const emit = defineEmits([
>   'update:modelValue',
>   'after',
>   'focus',
>   'blur',
>   'esc',
>   'ctrlEnter',
>   'select',
> ])
> 
> const props = defineProps({
>   options: {
>     type: Object,
>     default() {
>       return {}
>     },
>   },
>   modelValue: {
>     type: String,
>     default: '',
>   },
> })
> 
> const contentEditor = ref<Vditor | null>(null)
> const editorRef = ref<HTMLElement | null>(null)
> 
> onMounted(() => {
>   contentEditor.value = new Vditor(editorRef.value as HTMLElement, {
>     ...props.options,
>     value: props.modelValue,
>     cache: {
>       enable: false,
>     },
>     fullscreen: {
>       index: 3000,
>     },
>     after() {
>       emit('after', toRaw(contentEditor.value))
>     },
>     input(value: string) {
>       emit('update:modelValue', value)
>     },
>     focus(value: string) {
>       emit('focus', value)
>     },
>     blur(value: string) {
>       emit('blur', value)
>     },
>     esc(value: string) {
>       emit('esc', value)
>     },
>     ctrlEnter(value: string) {
>       emit('ctrlEnter', value)
>     },
>     select(value: string) {
>       emit('select', value)
>     },
>   })
> })
> 
> watch(
>   () => props.modelValue,
>   (newVal) => {
>     if (newVal !== contentEditor.value?.getValue()) {
>       contentEditor.value?.setValue(newVal)
>     }
>   }
> )
> 
> onUnmounted(() => {
>   const editorInstance = unref(contentEditor)
>   if (!editorInstance) return
>   try {
>     editorInstance?.destroy?.()
>   } catch (error) {
>     console.log(error)
>   }
> })
> </script>
> 
> <template>
>   <div ref="editorRef"></div>
> </template>
> ```
> 
> 使用例子
> 
> ```
> <script setup lang="ts">
> import { ref } from 'vue'
> 
> const text = ref('')
> </script>
> 
> <template>
>   <div>
>     <h1>{{ text }}</h1>
>     <vue-vditor
>       v-model="text"
>       :options="{
>         height: 480,
>       }"
>     />
>   </div>
> </template>
> ```
> 
> 截图 ![image](https://user-images.githubusercontent.com/39737565/182178368-fee4a9da-d4c5-4fc1-ade7-95cc2ba0c350.png)



请问下你的这个VueVditor.vue在项目中作为子组件使用的时候(比如在ant design Vue的a-modal中的a-form中使用)，第一次打开model时有没有遇到过下面这种报错【TypeError: Cannot read properties of undefined (reading 'VditorIRDOM2Md')】
```bash
runtime-core.esm-bundler.js:40 [Vue warn]: Unhandled error during execution of watcher callback 
  at <MarkdownEditor content-value="# 取消订单后，界面显示空白\n\n取消订单后，界面显示空白👎" onUpdate:contentValue=fn editor-options= {height: '500px', width: '100%'} > 
  at <ACol class="ant-form-item-control" > 
  at <Anonymous name="desc" label="描   述" hasFeedback=false  ... > 
  at <ARow class="ant-form-item" key="row" > 
  at <AFormItem name="desc" label="描   述" > 
  at <AForm ref="createUpdateFormRef" model= {deadline: '', name: '取消订单后，界面显示空白', owner: 'jack', type: 2, priority: 4, …} rules= {name: Array(2), owner: Array(1), priority: Array(1), status: Array(1)} > 
  at <BaseTransition onBeforeEnter=fn<onBeforeEnter> onAfterEnter=fn<onAfterEnter> onAfterLeave=fn<onAfterLeave>  ... > 
  at <Transition name="zoom" appear=true enterFromClass="zoom-enter zoom-enter-prepare"  ... > 
  at <Content title="修改缺陷" width="60%" maskTransitionName="fade"  ... > 
  at <Dialog title="修改缺陷" width="60%" maskTransitionName="fade"  ... > 
  at <Portal getContainer=fn<getContainer6> ref=Ref< Proxy {…} > > 
  at <PortalWrapper visible=true forceRender=undefined getContainer=undefined > 
  at <DialogWrap title="修改缺陷" okText="提交" cancelText="取消"  ... > 
  at <AModal visible=true width="60%" title="修改缺陷"  ... > 
  at <StandardModal modal-visible=true modal-width="60%" modal-title="修改缺陷"  ... > 
  at <WorkItemUpdateForm key=1 visible=true all-user-list= (12) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]  ... > 
  at <WorkItemList sprint-id=4 work-item-type=2 > 
  at <BugList onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {__v_skip: true} > > 
  at <RouterView> 
  at <ACard class="work-item" > 
  at <ACol span=20 > 
  at <ARow type="flex" justify="space-between" > 
  at <SprintDetail onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {__v_skip: true} > > 
  at <RouterView> 
  at <ContentLayout> 
  at <Anonymous hasSider=undefined prefixCls="ant-layout-content" tagName="main"  ... > 
  at <ALayoutContent class="main-container" > 
  at <Anonymous hasSider=undefined prefixCls="ant-layout" tagName="section"  ... > 
  at <ALayout class="root-container" > 
  at <BasicLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {__v_skip: true} > > 
  at <RouterView> 
  at <ALocaleProvider locale= {locale: 'zh-cn', Pagination: {…}, DatePicker: {…}, TimePicker: {…}, Calendar: {…}, …} ANT_MARK__="internalMark" > 
  at <LocaleReceiver children=fn<children> > 
  at <AConfigProvider locale= {locale: 'zh-cn', Pagination: {…}, DatePicker: {…}, TimePicker: {…}, Calendar: {…}, …} > 
  at <App>
index.min.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'VditorIRDOM2Md')
    at a (index.min.js:1:61621)
    at t3.getValue (index.min.js:1:258063)
    at MarkdownEditor.vue:27:44
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:182:21)
    at job (runtime-core.esm-bundler.js:1812:17)
    at flushPreFlushCbs (runtime-core.esm-bundler.js:336:13)
    at updateComponentPreRender (runtime-core.esm-bundler.js:5789:9)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5702:21)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:25)
```
我的MarkdownEditor.vue文件内容如下(报错显示是在27行，就是这行`if (newContentValue !== mdEditor.value.getValue()) {`)
```vue
<template>
  <div :id="editorId"></div>
</template>

<script setup>
import { ref, onMounted, onUnmounted, watch } from 'vue'
import Vditor from 'vditor'
import 'vditor/dist/index.css'

const mdEditor = ref(null)
const editorId = Math.random().toString(36).slice(-10)
const props = defineProps({
  contentValue: {
    type: String,
    required: true
  },
  editorOptions: {
    type: Object,
    required: true
  }
})
const emit = defineEmits(['update:contentValue'])

watch(
  () => props.contentValue,
  async (newContentValue, oldContentValue) => {
    if (newContentValue !== mdEditor.value.getValue()) {
      mdEditor.value.setValue(newContentValue)
    }
  }
)

onMounted(() => {
  mdEditor.value = new Vditor(editorId, {
    after() {
      // vditor.value is a instance of Vditor now and thus can be safely used here
      mdEditor.value.setValue(props.contentValue)
    },
    placeholder: 'Please enter text...',
    cache: {
      enable: false
    },
    blur(value) {
      // 编辑器失焦后触发
      // console.log('blur', value)
      if (value !== props.contentValue) {
        emit('update:contentValue', value)
      }
    },
    ...props.editorOptions
  })
})
onUnmounted(() => {
  // 销毁mdEditor
  mdEditor.value.destroy()
})
</script>

<style scoped></style>
```

**Comment by hashqueue** [comment]
vditor版本是"vditor": "^3.9.0"

**Comment by hashqueue** [comment]
上边的报错不影响功能的使用，暂时先把watch加了个try/catch了，`Vditor`很好用的一个组件，已推荐给身边朋友们。
```JavaScript
watch(
  () => props.contentValue,
  async (newContentValue, oldContentValue) => {
    try {
      if (newContentValue !== mdEditor.value.getValue()) {
        mdEditor.value.setValue(newContentValue)
      }
    } catch (error) {
      console.log(error)
    }
  }
)
```

**Comment by noenif** [comment]
> input

input好像会导致编辑器失焦,因此只能在blur的时候进行触发吗?

**Comment by HCenggel** [comment]
大佬，有最小实现项目可供下载吗？

**Comment by Vanessa219** [comment]
检查一下是否在初始化完成后才调用相关方法？
