### ISSUE TITLE
可以让编辑器一进来的时候就是预览吗

### ISSUE THREAD

**Issue by Fan223** [Vanessa219/vditor#1273]
就比如我回显内容。一进来的时候不应该是编辑状态，应该是预览状态。假如我需要编辑，再取消预览就可以直接编辑。

我也用了 提供的假如不需要编辑只需要渲染的方法。首先是这个渲染存在一些问题，和编辑器的预览状态不太一样，渲染出来的效果不好，其次渲染出来没有大纲，无法快速跳转。也可能是我没有找到这个配置。

所以我觉得个人使用的话，可不可以让编辑器一进来就是预览状态。假如我要编辑了再点击工具栏取消预览，进入编辑模式。做到上面的不需要编辑只需要渲染的效果，编辑不编辑由我自己选择，甚至我也可以自定义工具栏在工具栏里不显示编辑选项，也可以实现不需要编辑的情况。

**Comment by Vanessa219** [comment]
可参考 https://b3log.org/vditor/demo/preview.html

**Comment by Vanessa219** [comment]
可参考 https://b3log.org/vditor/demo/preview.html

**Comment by Fan223** [comment]
这个 https://b3log.org/vditor/demo/preview.html，就是我说的
【我也用了 提供的假如不需要编辑只需要渲染的方法。首先是这个渲染存在一些问题，和编辑器的预览状态不太一样，渲染出来的效果不好，其次渲染出来没有大纲，无法快速跳转。也可能是我没有找到这个配置。】 
这种情况。参考之后可以实现了。

但是我还是希望可以像我的标题说的一样，可不可以有个配置让编辑器一进来就是预览状态，假如我要编辑，取消预览就可以编辑，不只是渲染。
因为我是个人使用，现在是 我回显内容时点进去编辑器会自动聚焦，直接编辑状态。可能我只想浏览，不一定就编辑。编辑状态下不管哪种编辑模式，或多或少都会有文本符号，然后鼠标点击会有编辑的提示那些，图片也不能点击放大。相比之下预览状态就符合我想要的情况。

**Comment by Vanessa219** [comment]
参考一下 https://github.com/Vanessa219/vditor/issues/321

**Comment by Fan223** [comment]
好了，非常感谢！

**Comment by Fan223** [comment]
再问一下。就是我是用的vue2。然后我是把Vditor封装成了一个组件，mounted 时就 new Vditor(...)。使用的的时候作为子组件，接收父组件通过props传进来的参数作为值，这个参数是通过axios查到然后再赋值的，所以mounted 时就收不到props的值，是空的。
![This is an image](https://img-blog.csdnimg.cn/c32749a3a6d24a26a67226ada8a3ab60.png)
我最开始的解决办法是父组件查到值之后，直接使用`this.$refs.markdownEditor.setValue(res.data.data.content);` 设置编辑器的值
![This is an image](https://img-blog.csdnimg.cn/19e56dad802448679c12eac3446603b0.png)
之后是在子组件里监视props传进来的参数值，再通过 `renderPreview` 设置预览区域的值
![This is an image](https://img-blog.csdnimg.cn/b1bbfa8b7080443f90d5e0857287ddb6.png)
因为我在 mounted 时就是设置了一进来就是预览，所以通过 `renderPreview` 设置预览区域的值
![This is an image](https://img-blog.csdnimg.cn/43db0838de1f47498c8f5172bff83f92.png)
但都会出现一样的情况，就是加载不了大纲，然后我切换到另一个页面大纲又加载出来了
![This is an image](https://img-blog.csdnimg.cn/16c2c093383f4c0e84d44b457f0d2132.png)
![This is an image](https://img-blog.csdnimg.cn/2675564aa1b64872a1b3132eceb2a231.png)
请问这个可以解决吗？我主要是后端，对前端了解不是很深---_---，我现在想到的解决办法就是，把new Vditor(...)写在方法里，然后 mounted  时就调用这个方法，创建一次编辑器。后面每次监视到更新，都调用这个方法重新创建编辑器。能达到效果。但是每次都调用创建方法，页面内容加载的速度就会慢一点。
还有就是可以通过先取消预览，再点击预览来实现
![This is an image](https://img-blog.csdnimg.cn/3ef2c4a210434481b98026fcdee31604.png)
但是这个取消预览的时候会加载编辑状态下的大纲，然后闪一下又加载预览状态，效果不友好

**Comment by Vanessa219** [comment]
你搜一下相关 issue 看看吧

**Comment by Fan223** [comment]
好的，感谢！
