### ISSUE TITLE
在特定情况无法从CDN获取文件

### ISSUE THREAD

**Issue by am-abudu** [Vanessa219/vditor#1276]
### 编辑模式

ALL

### 描述问题

/js/i18n/zh_CN.js 等文件的获取会自动在url头加上一个`/dist/`, 但如果我使用的是 CDNJS 类的 CDN , 他们并不包含这个 `/dist/` , 而程序自动的在前方添加了这个前缀, 导致文件无法获取

### 期待的结果

去除强制地在 options.cdn 后加入 `/dist/` , 将选择权留给用户

### 版本信息

* 版本：3.8.17
* 操作系统：ALL
* 浏览器：Edge

### 其他信息

例子: 

将 options.cdn 设置为 `https://cdn.staticfile.org/vditor/3.8.17/`

程序自动地访问了 `https://cdn.staticfile.org/vditor/3.8.17/dist/js/i18n/zh_CN.js` => 404

而正确的链接为 `https://cdn.staticfile.org/vditor/3.8.17/js/i18n/zh_CN.js`

**Comment by Vanessa219** [comment]
所有资源文件都在 dist 目录下。前端一般都是这样放置的，看一下是不是资源网站的定向问题。

**Comment by LLLPY** [comment]
我也遇到了同样的问题，一开始用的cdn.jsdelivr，但是这个cdn国内访问似乎变慢了很多，然后改为cdn.staticfile,但是staticfile的路径中不包含dist，导致访问不了。
<img width="1302" alt="image" src="https://github.com/Vanessa219/vditor/assets/61370857/d46dd349-c172-4192-b1c0-87aa2da20b8b">

**Comment by Vanessa219** [comment]
不行就用自己服务器上的。cdn.staticfile 这个没有研究过

**Comment by am-abudu** [comment]
> 我也遇到了同样的问题，一开始用的cdn.jsdelivr，但是这个cdn国内访问似乎变慢了很多，然后改为cdn.staticfile,但是staticfile的路径中不包含dist，导致访问不了。 <img alt="image" width="1302" src="https://private-user-images.githubusercontent.com/61370857/304942470-d46dd349-c172-4192-b1c0-87aa2da20b8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NzA5NTgsIm5iZiI6MTcwNzk3MDY1OCwicGF0aCI6Ii82MTM3MDg1Ny8zMDQ5NDI0NzAtZDQ2ZGQzNDktYzE3Mi00MTkyLWIxYzAtODdhYTJkYTIwYjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDA0MTczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzNGRkMDlmOTZhMTRlYzQ5MGU2NjNmMjY5ZjhhYzc4MDA5NDk0NjI1MTZiZDQ4MzkxYTEyODNlYzA2ZDQwYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xL1UrfYojIVOJAcNpIXDUzVegCJYzCeNB-4WANApwUw">

我已经向cdnjs提交了修复，但是由于cdnjs的bug无法合并，详见 https://github.com/cdnjs/packages/pull/1266
