### ISSUE TITLE
行内代码输入问题

### ISSUE THREAD

**Issue by running-bugs** [Vanessa219/vditor#1277]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

````````markdown
行内代码块先输入 ` `, 再输入内容, 不能完整输入, 或者在开头结尾处进行修改
````````

### 期待的结果

行内代码可以支持先输入 \`\`, 再输入内容的习惯

### 截屏或录像

![行内代码块输入问题](https://user-images.githubusercontent.com/36567382/183319813-75ec75bd-e055-4200-91c7-612ab501aff5.gif)

### 版本信息

* 版本：v2.1.5
* 操作系统：win 10
* 浏览器：chrome

**Comment by 88250** [comment]
这个无法支持，只能使用其他模式顶顶，感谢反馈。
