### ISSUE TITLE
已配置cdn，但部分文件仍然走默认cdn

### ISSUE THREAD

**Issue by wfx0805** [Vanessa219/vditor#1282]
下图是我的配置：
![image](https://user-images.githubusercontent.com/48720127/185795757-0257e926-db60-452c-91f6-765a99c66411.png)
下图是正常走我配置的cdn的文件：
![image](https://user-images.githubusercontent.com/48720127/185795852-393117f9-ea3c-4879-a537-7231b9802d21.png)
下图是没有走cdn配置的文件：
![image](https://user-images.githubusercontent.com/48720127/185795965-b21053ab-ec44-4d03-a718-9e3ac90c48d2.png)

**Comment by Vanessa219** [comment]
参见 https://ld246.com/article/1549638745630#CDN-%E5%88%87%E6%8D%A2

**Comment by Keeyuu** [comment]
太坑了需要改很多地方

**Comment by Vanessa219** [comment]
> 太坑了需要改很多地方

这个可以翻阅已有 issue，有用户是需要分开的。
