### ISSUE TITLE
hint触发不强制左边加空格

### ISSUE THREAD

**Issue by JiaweiUTSCHINA** [Vanessa219/vditor#1285]
### 你在什么场景下需要该功能？

评论功能中@功能触发选人弹窗，希望在正常输入文本中一旦打@就直接触发，而不是 xxxx空格@ 触发

### 描述最优的解决方案 

hint中加入配置项，可默认关闭

### 描述候选解决方案

key支持Reg语法

**Comment by Vanessa219** [comment]
这样的话输入邮箱会比较麻烦。空格看上去也会比较美观一点，就不修改了。
