### ISSUE TITLE
支持颜色选择器（或自定义功能）

### ISSUE THREAD

**Issue by TalexDreamSoul** [Vanessa219/vditor#1287]
### 你在什么场景下需要该功能？

提供颜色选择器，拾取器 色轮 推荐色号等
或者可以出 api 方面的，由开发者自己适配

### 描述最优的解决方案 

例如 gitbook 中的颜色拾取器

### 描述候选解决方案

可以出 api 方面的，由开发者自己适配

### 其他信息

暂无。

**Comment by 88250** [comment]
* https://github.com/Vanessa219/vditor/issues/1170
* https://github.com/Vanessa219/vditor/issues/1095
* https://github.com/Vanessa219/vditor/issues/960

**Comment by TalexDreamSoul** [comment]
> * [添加 设置字体颜色的功能 #1170](https://github.com/Vanessa219/vditor/issues/1170)
> * [如何通过js改变字体颜色和背景颜色 #1095](https://github.com/Vanessa219/vditor/issues/1095)
> * [是否可以改变 字体颜色、段落间距、背景颜色 #960](https://github.com/Vanessa219/vditor/issues/960)

Thanks!
