### ISSUE TITLE
vscode插件中，使用“行内代码”功能，被标记的部分变成全黑，看不清里边记录的是什么内容

### ISSUE THREAD

**Issue by fishANDdog** [Vanessa219/vditor#1288]
### 编辑模式

vscode插件，所见即所得模式

### 描述问题

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
````````

### 截屏或录像

![image](https://user-images.githubusercontent.com/17683935/187165900-ca95f64d-b5ad-4962-b69c-42408335131a.png)

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

**Comment by 88250** [comment]
请给 VSCode 插件仓库反馈，谢谢。
