### ISSUE TITLE
Safari 和 iOS/macOS WebView 的输入时的光标位置问题

### ISSUE THREAD

**Issue by Lagrange1813** [Vanessa219/vditor#1289]
### 编辑模式
wysiwyg 所见即所得模式
### 描述问题
经过测试，在 Safari 和 iOS 的 WebView 上使用 Vditor 时，每次换新行后先输入英文再删除再插入中文，此时光标相对于最后一个预览的拼音会有一点错位。
### 期待的结果
修复该问题
### 截屏或录像
https://user-images.githubusercontent.com/54029053/187360430-62268e4b-a48f-4da2-a0fe-dfc51c80529f.mov
### 版本信息
版本：v3.8.17
操作系统：macOS 12.5
浏览器：WKWebView，Safari
### 其他信息
试着调试了一下，发现当按enter到新行时，页面元素如图
<img width="287" alt="截屏2022-08-30 18 56 55" src="https://user-images.githubusercontent.com/54029053/187420412-029e3095-1ef3-4e2c-8a39-58c538027f8b.png">
当在此页面切换输入法时，
<img width="210" alt="截屏2022-08-30 19 03 15" src="https://user-images.githubusercontent.com/54029053/187420688-9e80e386-3d49-4b55-b796-2d57517b62e8.png">
输入时，
<img width="311" alt="截屏2022-08-30 18 59 31" src="https://user-images.githubusercontent.com/54029053/187420795-8088b26d-29e2-43ba-8fb7-25e622886de0.png">
此时中文拼音并没有出现错位现象。

但如果删除英文后切换中文输入法，再输入，则会变成
<img width="236" alt="截屏2022-08-30 19 05 14" src="https://user-images.githubusercontent.com/54029053/187421079-008ae1d5-759b-4578-9e3c-ef71d6759307.png">

与Safari不同的是，Chrome直接以zerowidthspace占位，并不会出现这种情况
<img width="348" alt="截屏2022-08-30 18 58 54" src="https://user-images.githubusercontent.com/54029053/187421212-606d2bc9-9a7c-41c4-9d00-bf7b1380a20a.png">

---

发现WkWebView似乎和Safari不太一样，这个问题更严重一点，直接换行就会出现光标错位。
<img width="366" alt="截屏2022-08-30 20 55 31" src="https://user-images.githubusercontent.com/54029053/187442096-2ea1be65-491f-4b3b-8fd4-ba1bd5239dff.png">
测试了一下，还是wysiwyg的input有点问题 🙉

**Comment by Lagrange1813** [comment]
试着调试了一下，发现当按enter到新行时，页面元素如图
<img width="287" alt="截屏2022-08-30 18 56 55" src="https://user-images.githubusercontent.com/54029053/187420412-029e3095-1ef3-4e2c-8a39-58c538027f8b.png">
当在此页面切换输入法时，
<img width="210" alt="截屏2022-08-30 19 03 15" src="https://user-images.githubusercontent.com/54029053/187420688-9e80e386-3d49-4b55-b796-2d57517b62e8.png">
输入时，
<img width="311" alt="截屏2022-08-30 18 59 31" src="https://user-images.githubusercontent.com/54029053/187420795-8088b26d-29e2-43ba-8fb7-25e622886de0.png">
此时中文拼音并没有出现错位现象。

但如果删除英文后切换中文输入法，再输入，则会变成
<img width="236" alt="截屏2022-08-30 19 05 14" src="https://user-images.githubusercontent.com/54029053/187421079-008ae1d5-759b-4578-9e3c-ef71d6759307.png">

与Safari不同的是，Chrome直接以zerowidthspace占位，并不会出现这种情况
<img width="348" alt="截屏2022-08-30 18 58 54" src="https://user-images.githubusercontent.com/54029053/187421212-606d2bc9-9a7c-41c4-9d00-bf7b1380a20a.png">

**Comment by Lagrange1813** [comment]
WkWebView似乎和Safari不太一样，这个问题更严重一点，直接换行就会出现光标错位。
<img width="366" alt="截屏2022-08-30 20 55 31" src="https://user-images.githubusercontent.com/54029053/187442096-2ea1be65-491f-4b3b-8fd4-ba1bd5239dff.png">

**Comment by Vanessa219** [comment]
是不是浏览器渲染光标的时候有问题，更新再看看。

**Comment by axiaoxin** [comment]
ios safari上我的编辑框点击后没有任何反应，键盘都没出现，这个是需要配置什么吗？

**Comment by axiaoxin** [comment]
> ios safari上我的编辑框点击后没有任何反应，键盘都没出现，这个是需要配置什么吗？

忽略，已解决。父元素用了bootstrap的user-select-all导致的

**Comment by Lagrange1813** [comment]
因为用不到朝鲜语，我直接注释掉了processKeydown里的fixCJKPosition，目前使用似乎一切正常🤔

**Comment by Vanessa219** [comment]
没有问题的话我就先关闭了。

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/pull/1314
