### ISSUE TITLE
切换标题的级别，比预计的需要多点几次鼠标

### ISSUE THREAD

**Issue by bluesaiz** [Vanessa219/vditor#1291]
【问题】
在所见即所得模式下， 切换标题级别的时候（比如从二级标题切换成三级标题），点击工具栏的H图标，会把标题先变成普通的文本，然后再点击H图标，才能重新选择标题的级别，这样操作多有不便。
【建议】
建议改成：选中文本后， 能够直接选择标题的级别或者正文。

**Comment by Vanessa219** [comment]
可以使用快捷键
