### ISSUE TITLE
构建产物支持scss或原生css

### ISSUE THREAD

**Issue by Laffery** [Vanessa219/vditor#1292]
### 你在什么场景下需要该功能？

我使用next.js搭建应用，主要使用scss，唯独vditor这一依赖使用less（也没有原生css），另外next.js对less支持不是很好。

### 描述最优的解决方案 

当然我们知道维护scss / less两套样式比较困难，我建议在构建的时候可以将less转成css，导出less / css两份样式，供用户多样性选择。

### 其他信息

附上antd的产物

![image](https://user-images.githubusercontent.com/49607541/187957730-a10d3abc-3e65-431a-938b-867595f4b9af.png)

**Comment by Vanessa219** [comment]
可以直接引用打包好的 css
