### ISSUE TITLE
工具栏增加段落缩进、居左、居中、居右功能

### ISSUE THREAD

**Issue by liangning0628** [Vanessa219/vditor#1293]
### 你在什么场景下需要该功能？
编辑段落和公告时，需要用到居中、居右对齐等功能，格式如下，
![image](https://user-images.githubusercontent.com/95679856/188056916-fa896256-7a78-4664-8ad4-b34de689740e.png)

**Comment by Vanessa219** [comment]
CommonMark 不支持这个语法，目前只能用 html 来写。
