### ISSUE TITLE
移动端设置编辑光标位置

### ISSUE THREAD

**Issue by HumorSmith** [Vanessa219/vditor#1299]
<img width="584" alt="image" src="https://user-images.githubusercontent.com/3163232/190063919-445178cb-00c6-4375-98f7-29a442e2cb67.png">

**Comment by HumorSmith** [comment]
## 自问自答  

function moveLeft(){
    document.getSelection()["modify"]("move","left","character")
  }

  function moveRight(){
    document.getSelection()["modify"]("move","right","character")
  }

**Comment by Vanessa219** [comment]
???
