### ISSUE TITLE
任务列表跳出

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#130]
enter, enter...  backspace, backspace 

![Feb-09-2020 19-12-24](https://user-images.githubusercontent.com/15811943/74114532-412b5280-4b70-11ea-8e2b-3a4bb29feb41.gif)

need tab(ctrl+shift+e), shift tab(ctrl+shift-s)

**Comment by 88250** [comment]
@Vanessa219 修复了乱码问题。
