### ISSUE TITLE
选中文本后粘贴网址自动生成链接

### ISSUE THREAD

**Issue by grandsong** [Vanessa219/vditor#1301]
### 你在什么场景下需要该功能？

很多时候，我需要复制一个网址，然后让一段文字变成对应的链接。

### 描述最优的解决方案 

操作如下：

1. 复制一个网址
2. 在编辑器里选中一段文字
3. 粘贴
4. 编辑器智能地识别出被粘贴的数据是一个网址，然后把被选中的文字变成对应的链接。

### 其他信息

在“思源笔记”里，就是这样的。

**Comment by caiweihan** [comment]
@Vanessa219 我今天尝试了，也没有自动生成链接啊？这个 Commit 正确吗
