### ISSUE TITLE
如何移除这些默认示例项

### ISSUE THREAD

**Issue by zhuhuanzi** [Vanessa219/vditor#1303]
### 编辑模式

* `sv` 分屏编辑预览模式

### 描述问题

一次加载不会加载此内容，第二次加载会自动加载如下内容

![image](https://user-images.githubusercontent.com/26531688/191404310-8f9d897c-4937-4b1e-bcae-a631dcf43a75.png)

### 期待的结果
期待结果为空白
![image](https://user-images.githubusercontent.com/26531688/191404430-f8b07ea9-6906-42c0-b28c-a7510ea94e38.png)

### 版本信息

* 版本：3.9.15
* 操作系统：win11
* 浏览器：Microsoft Edge 版本 105.0.1343.33 (正式版本) (64 位)

**Comment by Vanessa219** [comment]
加载的时候让传入的 dom 内容为空
