### ISSUE TITLE
Vue3，代码块字体颜色变成了白色

### ISSUE THREAD

**Issue by seepine** [Vanessa219/vditor#1304]
### 编辑模式

* `ir` 即时渲染模式

### 描述问题
直接引入使用，代码块样式字体颜色是白色
```js
import Vditor from 'vditor'
import 'vditor/dist/index.css'

vditor.value = new Vditor( 'divId' , {})
```

### 期待的结果
正常显示

### 截屏或录像
![image](https://user-images.githubusercontent.com/93666053/191404598-84b6966f-fe24-4cc8-b434-6dbe29ae6466.png)
![image](https://user-images.githubusercontent.com/93666053/191404911-e333a279-5830-491a-9b40-130579d2f7ff.png)
![image](https://user-images.githubusercontent.com/93666053/191405252-69eeeef1-a542-4e22-ac1b-e6c32c173f6c.png)
![image](https://user-images.githubusercontent.com/93666053/191405552-5b027b39-bf0f-4821-881e-eaf0feff714c.png)

### 版本信息

* 版本："vditor": "^3.8.17"
* 操作系统：macos12
* 浏览器：edge

**Comment by Vanessa219** [comment]
需要设置一下代码块的主题

**Comment by Vanessa219** [comment]
这个代码是哪里的？修改或重置一下
<img width="607" alt="image" src="https://user-images.githubusercontent.com/970828/203329157-41990c68-8017-4334-98e1-c90d397b8517.png">
