### ISSUE TITLE
input事件的触发时机?

### ISSUE THREAD

**Issue by HengCC** [Vanessa219/vditor#1307]
### 你在什么场景下需要该功能？

在input中设置监听事件. 发现内部似乎有防抖的机制. 当我一直输入的时候input一直不会被触发. 不在输入大概1秒左右 会触发input事件. 
这块有没有可能input是实时触发的呢? 只要内容变动就立刻通知? 

### 描述最优的解决方案 

可能vditor内部对这块的设定是为了preview的时候性能做的一个平衡. 但是我觉得输入和渲染应该是2个分开的逻辑.  即使没有渲染. 那内容也应该算是输入了. 并且应该被持久化到数据库中. 如果是为了preview做的平衡.是否可以考虑用节流的模式去做. 单位的时间内如果内容变动了. 只处理一次渲染

**Comment by Vanessa219** [comment]
vditor 每次输入都会经过 lute 进行 MD 解析，所以需要 debounce

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/blob/33ad2b30dcbbaa0b6517256ea959b1e2bc9edc10/src/ts/wysiwyg/afterRenderEvent.ts
