### ISSUE TITLE
内容超过一页，编辑器错误滚动的问题，编辑中间部分内容，会滚动到末尾

### ISSUE THREAD

**Issue by thinkido** [Vanessa219/vditor#1309]
### 编辑模式
* `ir` 即时渲染模式

### 描述问题
内容超过一页，编辑器错误滚动的问题，编辑中间部分内容，会滚动到末尾

### 期待的结果
编辑最下面一行内容时滚动；
编辑最底部内容，则不滚动。

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

**Comment by Vanessa219** [comment]
重复 https://github.com/Vanessa219/vditor/issues/1308

**Comment by thinkido** [comment]
> 重复 #1308

没有重复，是不同的2个问题。

**Comment by Vanessa219** [comment]
还麻烦发一下 md 和具体的录屏
