### ISSUE TITLE
标题后面的`#`setValue后会被移除

### ISSUE THREAD

**Issue by axiaoxin** [Vanessa219/vditor#1310]
### 编辑模式

* `sv` 分屏编辑预览模式

### 描述问题

一个表单用于创建和修改文本，由于某种需求，我的markdown标题需要写一个结尾的标记用于文本处理，比如

````````markdown
### 三级标题 ###
````````

上面这个三级标题我需要使用 `###`结尾，在通过vditor编辑写入后文本没有异常。修改时使用`vditor.setValue`后，后面的`###`就不见了。

我尝试使用`"fixTermTypo": false`，但是没有作用。

### 期待的结果

不移除后面的`###`

### 版本信息

* 版本：3.8.17
* 操作系统：macos
* 浏览器：safari

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/1319
