### ISSUE TITLE
 渲染不出来##### { Guarantee }

### ISSUE THREAD

**Issue by wangyunteng** [Vanessa219/vditor#1315]
这样写的话，渲染不出来{  Guarantee     }     #####  {  Guarantee     }

![image](https://user-images.githubusercontent.com/49503411/196353979-ce0ef1c8-9c43-4dd5-ae69-22c13a1ed748.png)

**Comment by 88250** [comment]
这个是开启了自定义标题 ID 解析选项，可以通过 Lute 实例 [`SetHeadingID`](https://github.com/88250/lute/blob/9d271d512c927ec97143aa41669fbd3ef895da49/lute.go#L363) 函数关闭。

目前 Vditor 中好像没有包装该函数，请参考其他类似开关选项代码调整，欢迎 PR。
