### ISSUE TITLE
upload.format 自动将图片插入了编辑区却没有触发编辑器的 input 事件

### ISSUE THREAD

**Issue by BearD01001** [Vanessa219/vditor#1316]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

upload.format 自动将图片插入了编辑区却没有触发编辑器的 input 事件，导致上层应用无法拿到插入图片后的 markdown 字符串，
由于 format 函数的运行先于编辑器内容的变更，所以在 format 函数中也无法用同步方式直接取到插入图片后的 md 内容。
目前一个不太优雅的解决方案是在 format 函数末尾加一个定时器，触发一下上层的事件：
```js
          // 图片上传成功并不会触发 input 事件，故此处手动触发一次
          setTimeout(() => {
            onChange?.(editor.getValue());
          }, 300);
```

### 期待的结果

format 函数运行后可以触发一下编辑器的 input 事件

### 版本信息

* 版本：3.8.12
* 操作系统：macOS
* 浏览器：Chrome

**Comment by Vanessa219** [comment]
成功插入图片后通过以下方法最终会触发 input 事件的。
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/970828/197369617-b852ff3c-dd54-4724-8c6e-9a1255da7814.png">
<img width="347" alt="image" src="https://user-images.githubusercontent.com/970828/197369632-9206f509-9c80-4bb7-b670-7053b4e7e84f.png">
