### ISSUE TITLE
不支持TS? 在使用ts开发引入 提示一堆错误，setValue问题，opt:value初始值加载不出来

### ISSUE THREAD

**Issue by fuile** [Vanessa219/vditor#1317]
editor.setValue后一直这个错误，该如何使用？
![image](https://user-images.githubusercontent.com/29008869/196762710-563e80fb-77cd-4a86-a6b0-3c81b2bb1bd0.png)
在使用ts开发引入 提示一堆错误
![image](https://user-images.githubusercontent.com/29008869/196762450-cce0b56e-c9eb-4069-80f4-68de1f982800.png)

**Comment by Vanessa219** [comment]
应该是可以导入定义文件的，setValue 后报错还需要更多信息，这里重现不了，看不出问题。

**Comment by Vanessa219** [comment]
没有其他问题，我先关闭了。
