### ISSUE TITLE
表格在渲染的时候,编辑后能不能保持原有的数据格式

### ISSUE THREAD

**Issue by HengCC** [Vanessa219/vditor#1318]
### 你在什么场景下需要该功能？

有的人喜欢用分屏模式. 在插入表格后, 编辑完成会产生很多个"------"这样的格式. 这对于编辑来说非常不友好. 会导致一堆不该产生的换行. 另外表格在换行的时候会有些问题. 看视频吧.

https://user-images.githubusercontent.com/6167532/196840619-80532e85-e6be-42e1-9e7c-e1b11a917d3d.mov

**Comment by HengCC** [comment]
另外在分屏预览模式下.既然直接是针对的源文件进行编辑. 是否可以考虑 复制粘贴进去的是原始md内容.而不是格式化后的内容, 比如下面这样的视频

https://user-images.githubusercontent.com/6167532/196927954-8f3c3975-4a16-4b53-b23c-2960208a7250.mov

**Comment by Vanessa219** [comment]
横线是为了对齐， md 语法 table 中的换行要使用 `<br>`

第二个问题解决方案参见 https://github.com/Vanessa219/vditor/issues/1319

**Comment by HengCC** [comment]
但是横线过多了不就产生了很多换行了吗. 如果一个单元格内容很多 . 那大部分都是横线. 而md的语法里面,其实只要几个横线就能标识这个表头了吧 @Vanessa219 , 横线太多了在分屏编辑模式下 那是灾难性的诶. 一眼望去全是横线.

**Comment by Vanessa219** [comment]
横线不会导致换行

**Comment by HengCC** [comment]
不是只有"\r\n"才会换行啊. sv模式下 屏幕总共那么长. 内容多了 它不就自动换行了.  视频中只有几列. 如果多一些列. 就更离谱. @Vanessa219  如果能固化表头那块的横线数量不就能完美解决了吗?

**Comment by Vanessa219** [comment]
内容过多导致换行，换行处并不会出现 "\r\n"

**Comment by HengCC** [comment]
不用纠结是是不是"\r\n"吧. 我提这个issue的目的本身就是希望你们能解决这样的换行问题. 无论是不是因为"\r\n"导致的.  只要在编辑器不要呈现那么多的横线不就行了吗?

而且重点是. 比如如果我编辑源文件 只输入三个"---", 结果编辑器在我输入了一些过长的值后. 可能就变成了 类似这样的"---------------",  那算不算是BUG呢.  因为多出来的内容并不是我输入的.

**Comment by Vanessa219** [comment]
这个不是 bug，一开始就说了“横线是为了对齐”。

**Comment by HengCC** [comment]
看这个图. 这2个写法都能完成渲染.  
![image](https://user-images.githubusercontent.com/6167532/197429788-788f53a3-a2d3-4315-bbd4-ecc2c9c101f5.png)
其他没啥说的了.  只是个建议.

**Comment by Vanessa219** [comment]
@88250 这在中文和编辑器中不太适用，能否去除这个优化？

**Comment by 88250** [comment]
我觉得暂时先不加选项了，再接受更多一些反馈再考虑，谢谢。
