### ISSUE TITLE
Nuxt.js 使用 options.value 设置默认值后，输入任意内容后，浏览器卡死。

### ISSUE THREAD

**Issue by know-that** [Vanessa219/vditor#1320]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
````````

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

### 其他信息
![image](https://user-images.githubusercontent.com/31246220/197721700-c0230221-4545-4fb5-95ed-2560f07bda19.png)

**Comment by Vanessa219** [comment]
是不是内容过多，如果用 setValue 呢？

**Comment by know-that** [comment]
> 是不是内容过多，如果用 setValue 呢？

应该是内容过多导致的，我辅助了两边官网的介绍。`setValue` 也同样卡死。

另外 有关焦点的问题，在nuxtjs上会存在。第一次点击不聚焦，然后输入内容，取消聚焦，后面再次点击页面，无论如何都是聚焦的。

**Comment by know-that** [comment]
> 是不是内容过多，如果用 setValue 呢？

出现卡死的情况仅在 options.mode 为 sv 的情况

**Comment by know-that** [comment]
> > 是不是内容过多，如果用 setValue 呢？
> 
> 应该是内容过多导致的，我复制了两遍官网的介绍。`setValue` 也同样卡死。
> 
> 另外 有关焦点的问题，在nuxtjs上会存在。第一次点击不聚焦，然后输入内容，取消聚焦，后面再次点击页面，无论如何都是聚焦的。

当只复制一遍内容，不会造成卡顿，是不是有什么冲突。

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/1319
