### ISSUE TITLE
在Vite2中使用，遇到Lute is not defined , 与vite的define配置有关

### ISSUE THREAD

**Issue by wssnail** [Vanessa219/vditor#1321]
### 描述问题

在vite2中使用遇到了Lute is not defined的错误，

在这个issues中找到了解决办法，https://github.com/Vanessa219/vditor/issues/1151#issuecomment-1209801819

```
define: {
      // 'process.env': process.env,  // 该代码会造成vditor报错Lute is not define
    },
```
我把process.env注释了就可以了

**Comment by Vanessa219** [comment]
应该是 Lute 没有加载
https://github.com/Vanessa219/vditor/issues/1151#issuecomment-1209801819
