### ISSUE TITLE
复制word内容时可以把word内的图片粘贴进来

### ISSUE THREAD

**Issue by tanxiaodan** [Vanessa219/vditor#1326]
### 你在什么场景下需要该功能？

在word里全选复制内容时，word内的图片是复制不过来的，只能一张张的复制图片。

### 描述最优的解决方案 

粘贴时能触发上传图片。

### 描述候选解决方案

无

### 其他信息

vditor 3.8.13
浏览器 chrome
操作系统 windows 10

**Comment by Vanessa219** [comment]
抱歉，这个没有办法实现。当文字和图片混合在一起后，浏览器无法读取。
