### ISSUE TITLE
v3.8.15(不含)之后的两个最新版本分屏预览模式下，贴入的内容在编辑时会重复生成很多份 导致内存泄漏卡死

### ISSUE THREAD

**Issue by davi-dsl** [Vanessa219/vditor#1328]
### 编辑模式

* `sv` 分屏编辑预览模式

### 描述问题

贴入的内容在编辑时会重复生成很多份 导致内存泄漏卡死
````````markdown
[Markdown 教程](https://ld246.com/guide/markdown)   官方的这篇内容贴入就可以测试出来 随便在输入几个字 或 改变两次局部内容 就会卡死
````````

### 版本信息

* 版本：[v3.8.17](https://github.com/Vanessa219/vditor/tree/v3.8.17) [v3.8.18](https://github.com/Vanessa219/vditor/tree/v3.8.18)
* 操作系统：windows11
* 浏览器：Microsoft Edge 版本 107.0.1418.26 (正式版本) (64 位)      Chrome 107.0.5304.88（正式版本） （64 位）

### 其他信息

目前正常的相关依赖
{
    "@wangeditor/editor": "^5.1.1",
    "axios": "0.18.1",
    "clipboard": "2.0.4",
    "codemirror": "5.45.0",
    "core-js": "3.6.5",
    "driver.js": "0.9.5",
    "dropzone": "5.5.1",
    "e-icon-picker": "1.1.1",
    "echarts": "4.2.1",
    "element-ui": "2.13.2",
    "file-saver": "2.0.1",
    "fuse.js": "3.4.4",
    "js-cookie": "2.2.0",
    "jsonlint": "1.6.3",
    "jsonwebtoken": "^8.5.1",
    "jszip": "3.2.1",
    "normalize.css": "7.0.0",
    "nprogress": "0.2.0",
    "path-to-regexp": "2.4.0",
    "pinyin": "2.9.0",
    "screenfull": "4.2.0",
    "script-loader": "0.7.2",
    "sortablejs": "1.8.4",
    "vditor": "^3.8.15",
    "vue": "2.6.10",
    "vue-count-to": "1.0.13",
    "vue-highlightjs": "^1.3.3",
    "vue-i18n": "7.3.2",
    "vue-json-views": "^1.3.0",
    "vue-router": "3.0.2",
    "vue-splitpane": "1.0.4",
    "vuedraggable": "2.20.0",
    "vuex": "3.1.0",
    "xlsx": "0.14.1"
  }

**Comment by Vanessa219** [comment]
无法重现
https://user-images.githubusercontent.com/970828/200121092-238e66a2-7348-4435-b92f-d32bec6e5089.mp4

**Comment by xjbuzzle** [comment]
还是有这个问题，只复制了一遍大纲内的内容

**Comment by Vanessa219** [comment]
可以录屏并发复制的内容么？

**Comment by xjbuzzle** [comment]
https://reccloud.cn/u/lb1ghkn

**Comment by xjbuzzle** [comment]
在分屏预览模式下，使用insertValue插入之后会导致浏览器卡死，有时候没有插入只是切换成分屏预览也会，是我漏了什么事件处理吗？求指教

**Comment by Vanessa219** [comment]
你在 Demo 里面试一下 inserValue，是不是事件循环了？

**Comment by xjbuzzle** [comment]
前两种编辑模式不会，没事已经放弃了
