### ISSUE TITLE
输入半角左括号会自动添加右括号，但再输入右括号会再次出现一个右括号而不是移动光标，导致出现两个右括号

### ISSUE THREAD

**Issue by Dradows** [Vanessa219/vditor#1329]
### 编辑模式

ir

### 描述问题

输入左括号会自动添加右括号，但再输入右括号会再次出现一个右括号而不是移动光标，导致出现两个右括号

### 期待的结果

希望要么不自动添加右括号，要么添加右括号后再次输入右括号不会添加新的右括号，确保输入(和)后出现()而不是())

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

**Comment by Vanessa219** [comment]
这个应该是输入法自动添加的吧？
