### ISSUE TITLE
insertValue方法中插入wbr标签出现错乱

### ISSUE THREAD

**Issue by xjbuzzle** [Vanessa219/vditor#1337]
### 编辑模式

* `wysiwyg` 所见即所得模式
仅采用这种模式

### 描述问题

编辑器外存在一个插入按钮，用于点击后将字符串内容插入编辑器焦点处，点击事件中调用insertValue方法，出现问题：插入时反应比较慢，其次会在编辑器外，也就是我自己新增的这个插入按钮前后出现<wbr>标签，换行后导致布局错乱

````````markdown
与markdown原文无关，但如果是在代码块前后插入可能更容易触发这个问题
````````

### 截屏或录像
类似：
![12C11A1F-28D8-4259-960F-3B172CDE465F](https://user-images.githubusercontent.com/40881581/202659365-0f87c23a-1a1c-4f35-9ed0-ae50ae4eb4e9.png)

**Comment by Vanessa219** [comment]
无法重现

https://user-images.githubusercontent.com/970828/202672321-a69c373f-3679-43b1-af7e-237c109ab1ae.mp4
