### ISSUE TITLE
Nuxt3 Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by gaminglifex** [Vanessa219/vditor#1340]
### 描述问题

Trying to implement Vditor to Nuxt3, but an error occurred

### 期待的结果

What I expected to see is to be able to make Vditor appear on my page.

![image](https://user-images.githubusercontent.com/72642816/208659606-50f3cb99-6e0a-47ed-ba07-d3ceba7ebfc3.png)

### 截屏或录像
![image](https://user-images.githubusercontent.com/72642816/208659566-1bc14cb3-21e8-4daf-ac4d-01aea4933411.png)

### 版本信息

* 版本： "vditor": "^3.8.18"
* 操作系统：Windows 10
* 浏览器：Chrome

**Comment by gaminglifex** [comment]
Here's the latest issue after modifying the above code to:
```vue
<template>
  <div id="vditor">haha</div>
</template>

<script lang="ts">
import Vditor from "vditor";
import "vditor/dist/js/lute/lute.min.js";
// import Editor from "@/components/Editor/Vditor.vue";
export default {
  data() {
    return {
      vditor: null,
      isMobile: window.innerWidth <= 960,
    };
  },
  mounted() {
    this.initVditor();
  },
  methods: {
    initVditor() {
      const that = this;
      const options = {
        width: this.isMobile ? "100%" : "100%",
        height: "650",
        tab: "\t",
        counter: "999999",
        typewriterMode: true,
        mode: "wysiwyg",
        comment: true,
        preview: {
          delay: 100,
          show: !this.isMobile,
        },
        theme: "classic",
        outline: true,
        upload: {
          max: 5 * 1024 * 1024,
          // linkToImgUrl: 'https://sm.ms/api/upload',
          handler(file) {
            let formData = new FormData();
            for (let i in file) {
              formData.append("smfile", file[i]);
            }
            let request = new XMLHttpRequest();
            // 图片上传路径
            request.open(
              "POST",
              process.env.PICTURE_API +
                "/file/ckeditorUploadFile?token=" +
                getToken()
            );
            request.onload = that.onloadCallback;
            request.send(formData);
          },
        },
      };
      this.vditor = new Vditor("vditor", options);
      console.log(this.vditor);
      return this.vditor;
    },
  },
};
</script>

```
but still having the error:
![image](https://user-images.githubusercontent.com/72642816/208693927-5e41bb05-eb2b-4dd4-a71a-c6bfad573224.png)

**Comment by gaminglifex** [comment]
After including lute.min.js in nuxt.config.ts, I succussfully made it to appear on my page. However, more bugs are coming
![image](https://user-images.githubusercontent.com/72642816/208804565-21a2cba4-3acb-4434-ad46-306305d87413.png)

**Comment by gaminglifex** [comment]
Now there is only one error left:
![image](https://user-images.githubusercontent.com/72642816/208807929-0cc0c14f-a7ba-4018-b4ee-2c13dee48f53.png)

**Comment by gaminglifex** [comment]
Thank you for your reply. May I know is it because variable/id "replace" does not exist?

**Comment by Vanessa219** [comment]
这样还是没有办法定位问题哦。

**Comment by gaminglifex** [comment]
Thank you for your reply. Here is the reproduction link: https://stackblitz.com/edit/nuxt-vditor-repro
I believe this could be useful for locating the error :))) Thank you

**Comment by Vanessa219** [comment]
没有你说的错误
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/970828/209901496-180ee0ce-ff75-4984-b8ed-d1972e8a76b9.png">

**Comment by gaminglifex** [comment]
Thank you for your reply. However, it did occur the error when I am trying to type in some words
![image](https://user-images.githubusercontent.com/72642816/210482418-c583ed74-bb25-4f71-aecf-af61d40aba12.png)

It also has another error in terminal
![image](https://user-images.githubusercontent.com/72642816/210482503-6de2f3a7-728c-4c70-9790-8bf5cf85c0eb.png)

**Comment by gaminglifex** [comment]
I found that the error only occur in "wysiwyg" & "ir" mode

**Comment by Vanessa219** [comment]
网站一片黑，打不开了
<img width="733" alt="image" src="https://user-images.githubusercontent.com/970828/210915263-073683d4-6703-4c25-afe1-68c4ec96d9c0.png">

**Comment by gaminglifex** [comment]
Nevermind, thank you for your hard work 👍

**Comment by Vanessa219** [comment]
可以看看是不是 Nuxt3 需要什么特殊的配置？一般环境无法重现，那我就先关闭了。
