### ISSUE TITLE
输入公式块后，回车又会自动生成公式块

### ISSUE THREAD

**Issue by mqingqing123** [Vanessa219/vditor#1344]
**编辑模式**
sv 分屏编辑预览模式

输入
`
$$
a^b=c
$$
`

![image](https://user-images.githubusercontent.com/22250695/209889883-a64f6e2b-66c5-4efd-b0e9-674f2a67a3f8.png)
在$$后，回车后，又出现公式块
![image](https://user-images.githubusercontent.com/22250695/209889922-bddce123-56bd-4039-b317-93da333cc3b2.png)

希望
(1)或者让用户手动输入 $$ 开始和结束 标记。
(2)或者后面回车后，就不再生成公式块。

**Comment by 88250** [comment]
现有的 SV 模式缺陷较多，后期可能会改为纯文本模式 https://github.com/Vanessa219/vditor/issues/1319
