### ISSUE TITLE
中文光标错位

### ISSUE THREAD

**Issue by webpon** [Vanessa219/vditor#1346]
### 编辑模式
所见即所得

### 描述问题
第一步：输入第一个字符没有问题
![image](https://user-images.githubusercontent.com/50807258/211039779-d4b45825-1048-43f0-bc63-5b652510befb.png)
当输入第二个字符，直接跳到上面的代码块中去了，
![image](https://user-images.githubusercontent.com/50807258/211040132-4cee08c5-6335-40ba-8de4-299bd0b02632.png)

### 期待的结果
期待不跳光标

### 版本信息

* 版本：3.8.18
* 操作系统：win10
* 浏览器：electron 22版本

**Comment by Vanessa219** [comment]
同 https://github.com/Vanessa219/vditor/issues/1083

**Comment by webpon** [comment]
怎么就closed了呀，1083反馈的问题也没解决呀

**Comment by webpon** [comment]
有解决方案吗

**Comment by Vanessa219** [comment]
和 1083 是同一个问题
