### ISSUE TITLE
标题首光标换行后大纲不对齐了，官方demo可以复现

### ISSUE THREAD

**Issue by webpon** [Vanessa219/vditor#1347]
### 描述问题
![image](https://user-images.githubusercontent.com/50807258/211046692-69da66f9-744c-453f-a8d6-195bf83d5625.png)

````````markdown

**Comment by Vanessa219** [comment]
是哪里和哪里没对齐？

**Comment by webpon** [comment]
![image](https://user-images.githubusercontent.com/50807258/211126335-2a9e7e9f-4233-4ab3-a9e2-690dabdad3a6.png)

**Comment by Vanessa219** [comment]
无法重现 
https://user-images.githubusercontent.com/970828/211861686-e2259315-6927-4366-835e-0c3cbee9db5d.mp4

**Comment by Vanessa219** [comment]
没有问题的话我就关闭了
