### ISSUE TITLE
弹出latex语法提示，实现快捷输入公式

### ISSUE THREAD

**Issue by cbamls** [Vanessa219/vditor#1349]
看到一个非常有用的功能：当输入$$ 时，弹出latex语法提示，实现快捷输入公式。
<img width="645" alt="image" src="https://user-images.githubusercontent.com/12781382/211159895-c8cf26f5-1bca-45b4-bfa3-afa69f8c04f4.png">

**Comment by 88250** [comment]
这个无法支持。
