### ISSUE TITLE
can not delete the first char. at first field of links

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#135]
![links3](https://user-images.githubusercontent.com/15811943/74154345-1aa10200-4bd8-11ea-9409-47a31ff53d27.gif)

**Comment by Vanessa219** [comment]
link at least a char

**Comment by jakekwak** [comment]
But I mistyped ther first character, Sometimes I want other shortcut key instead of ctrl+k

**Comment by Vanessa219** [comment]
which hotkey do you want?

**Comment by jakekwak** [comment]
I mean I want to cancel when I accidentally type `ctrl+k` instead of `ctrl+j`(or other shortcut key)
