### ISSUE TITLE
table类型中，excel的单行内容超过固定宽度时，不采用滚动条而是自动生成下一个表格

### ISSUE THREAD

**Issue by xjbuzzle** [Vanessa219/vditor#1352]
### 你在什么场景下需要该功能？

当表格的宽度较大，在正常展示的情况下，横向滚动条可用，能够看到全部内容，导出该文章时，滚动条不可用，内容被隐藏
![image](https://user-images.githubusercontent.com/40881581/215940810-b0a48970-e0ce-416d-a2e0-443fff1734c0.png)

### 描述最优的解决方案 

能否考虑在表格过长时，自动复制表头等主要信息生成新的表格，如下：
![image](https://user-images.githubusercontent.com/40881581/215940690-4ca3e2f4-f5a7-4998-8d70-9c325e91dd77.png)

**Comment by 88250** [comment]
你好，这个不考虑了，要达到这个效果需要修改 Markdown 文本，并且效果不一定好，因为宽度未知。
