### ISSUE TITLE
分屏模式下，回车失效，无法编辑并另起一行

### ISSUE THREAD

**Issue by LiangChengming** [Vanessa219/vditor#1353]
### 编辑模式

* `sv` 分屏编辑预览模式

### 描述问题

````````markdown
回车失效，输入文字后无法回车正常进入下一行，
````````

### 截屏或录像
另外控制台有不相干的错误，无规律出现

<img width="463" alt="image" src="https://user-images.githubusercontent.com/45283486/216557767-f37eff56-d9a6-4926-8d91-124f27fd48d2.png">

### 版本信息

* 版本：vditor 3.9.0
* 操作系统：mac 
* 浏览器：

### 其他信息

非分屏模式下，回车正常，开另起一行，只有分屏模式下失效.

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/1319
