### ISSUE TITLE
SV模式公式的BUG是不是这里引起的？

### ISSUE THREAD

**Issue by mqingqing123** [Vanessa219/vditor#1355]
vditor：3.9版本
sv模式： 分屏编辑预览模式
bug出现情况：在录入数学公式时，在$$后回车，就一直生成$$
基本上，其它问题没发现，所以，也不建议把SV重新为textarea模式。

![image](https://user-images.githubusercontent.com/22250695/218244226-d4d72903-2dd1-466b-b3b5-566d5c095342.png)

但是输入code则没这个bug，从界面上看，math公式和code非常类似
![image](https://user-images.githubusercontent.com/22250695/218244266-1f375bf9-337c-4858-8a1a-f7968f3a4aad.png)

昨天我查看了一下 src/ts/sv/inputEvent.ts 源代码
比较了code和math模式，发现2个代码段不一样。
那么数学出现的bug，是不是这段代码造成的？

把code那一段，把单词“code”替换为“ math” ，然后用新代码段 是不是就可以了？

因为，不懂怎么编译打包JS，所以，这里给出一些建议。

![image](https://user-images.githubusercontent.com/22250695/218244341-6be8bf9d-6299-4980-b829-c6a31810fc94.png)

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/1319
