### ISSUE TITLE
Add support for Swedish (sv_SE)

### ISSUE THREAD

**Issue by DennisL68** [Vanessa219/vditor#1358]
### In what scenarios do you need this feature?？

I'd like to add support for the Swedish language to vditor.

### Describe the optimal solution 

I've found the five files that needs to be changed and what additional file to be added.
Change all the files needed and add sv_SE.js to the `i18n` folder.

### Describe the candidate solution

There really is no option for non-english speaking suedes that like to use vditor.

### Additional Information

I've prepared a fork in https://github.com/DennisL68/vditor with all required changes that is ready to be merged if this request is approved.

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/pull/1359
