### ISSUE TITLE
[BUG] 3.8.18版本的vditor在react环境下报错

### ISSUE THREAD

**Issue by zyzcss** [Vanessa219/vditor#1360]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

问题1：进入即报错 lute is not defined
见: [https://codesandbox.io/s/vditor-react-minimal-example-forked-1j9flf?file=/src/App.tsx](url)
```
ReferenceError Lute is not defined
```

问题2
使用3.8.7版本进入测试案例
[https://codesandbox.io/s/vditor-react-minimal-example-forked-fpc94z?file=/package.json](url)
切换左侧vditor版本至3.8.18及以上，随意输入单词，回车后任意输入内容会弹出报错
```
Cannot read properties of null (reading 'replace')
```

### 期待的结果

不报错 正常运行

### 版本信息

* 版本：3.8.18
* 操作系统：Ubuntu 18.04.5 LTS
* 浏览器：chrome 107.0.5304.110

**Comment by Vanessa219** [comment]
看了下日志，两个都是同一个错误。你需要看第一个错误，Lute 解析的时候异常了，不知道是不是这个环境的问题。可以参考一下这个页面是正常的
https://github.com/Vanessa219/vditor/blob/37eb838ba75ec809cf7863405f50c933c9a3d78d/demo/static.html

**Comment by glacierck** [comment]
vue 环境同样有这问题，在输入文本时就会报这个错，但不影响使用，不知道有啥弊端。

**Comment by Vanessa219** [comment]
这个错误信息是？

**Comment by xiaowansheng** [comment]
请问这个问题需要怎么解决
