### ISSUE TITLE
希望改进分屏模式下的同步精准滚动功能

### ISSUE THREAD

**Issue by wiseguy-sky** [Vanessa219/vditor#1361]
### 编辑模式

* `sv` 分屏编辑预览模式

### 描述问题

同样的问题之前已经有多人提过。原本列在 [#355](https://github.com/Vanessa219/vditor/issues/355) 中， [#3](https://github.com/Vanessa219/vditor/issues/3) 最后发现已经被移出了改进计划，希望重新考虑。

### 实现建议

希望能实现类似 [bytemd](https://github.com/bytedance/bytemd) 的做法，[如何实现一个能精确同步滚动的Markdown编辑器](https://segmentfault.com/a/1190000041881142)

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/1319
