### ISSUE TITLE
Vditor preview加上是否渲染链接和图片的开关

### ISSUE THREAD

**Issue by ooyyloo** [Vanessa219/vditor#1362]
### 你在什么场景下需要该功能？

公司项目，要求不渲染链接和图片

### 描述最优的解决方案 

vditor preview增加是否渲染链接和图片，不渲染的时候直接输出markdown文本。

### 描述候选解决方案

无

### 其他信息

目前貌似只有创建editor的时候可以传入是否让链接可打开以及是否渲染图片

**Comment by Vanessa219** [comment]
可以改为调用相关的 render  方法。
