### ISSUE TITLE
vditor3.8.13 https://cdn.jsdelivr.net/npm/vditor@3.8.13/dist/js/lute/lute.min.js 无响应

### ISSUE THREAD

**Issue by TiAmo-Forever** [Vanessa219/vditor#1369]
vditor3.8.13 https://cdn.jsdelivr.net/npm/vditor@3.8.13/dist/js/lute/lute.min.js 无响应

页面第一次加载这个js耗时特别长

**Comment by Vanessa219** [comment]
可以使用自己搭建的 CDN 或更新版本

**Comment by wuxin0011** [comment]
可以试试换个CDN
https://jsd.onmicrosoft.cn/npm/vditor@3.8.13/dist/js/lute/lute.min.js
