### ISSUE TITLE
实时监听切换当前的编辑器模式

### ISSUE THREAD

**Issue by lizwxup** [Vanessa219/vditor#1371]
### 你在什么场景下需要该功能？

根据不同的编辑器模式需要改变页面展示方式，请问支持吗？患者哪种实现方式可以支持此功能！
谢谢

以及添加图表时未能根据主题色变化 请问在那里配置呢

**Comment by Vanessa219** [comment]
目前只能使用 `getCurrentMode` 获取，主题可参考 https://ld246.com/article/1549638745630#%E4%B8%BB%E9%A2%98
