### ISSUE TITLE
苹果系统在分屏预览下进行输入，回车无效，光标错乱

### ISSUE THREAD

**Issue by xiaowansheng** [Vanessa219/vditor#1372]
### 编辑模式

* `sv` 分屏编辑预览模式

### 描述问题

苹果系统在分屏预览下输入，在字符后面回车换行无效（在新的一行换行有效），有时候还会卡住，并且在按了回车后，在换行无效的情况下，删除字符时光标乱跳。
iPhone和ipad都有这个问题，安卓和pc没有。
我以为是我配置的问题，但是我在官网给的实例进行测试，发现也是同样的结果。

### 期待的结果

iPhone和ipad能正常回车换行就行。

### 版本信息

* 版本：3.9
* 操作系统：ios
* 浏览器：谷歌

**Comment by Vanessa219** [comment]
鉴于 https://github.com/Vanessa219/vditor/issues/1319，相关 bug 不再进行修改。
