### ISSUE TITLE
文本选中弹出组件 speech 位置被多屏影响

### ISSUE THREAD

**Issue by lz6060788** [Vanessa219/vditor#1373]
### 编辑模式

非编辑模式，仅使用渲染功能

### 描述问题

**当机子存在多屏幕时**，选中文本后，所出现的vditor-speech元素属性left计算方式存在问题，有可能会溢出屏幕，
[官方示例](https://b3log.org/vditor/demo/preview.html)
可稳定复现

### 期待的结果

样式计算不被屏幕数量影响

### 截屏或录像

![image](https://user-images.githubusercontent.com/98386138/226347599-7ae39e42-b846-431b-8c9c-9c6ee99eb1d7.png)

### 版本信息

* 版本：3.9.1
* 操作系统：win10
* 浏览器：chrome111.0

**Comment by Vanessa219** [comment]
这是划选哪一段话出现的？这里不太好复现。

**Comment by lz6060788** [comment]
任一一段话都可以，我估计是给这组件定位的时候错误获取了所在屏幕的位置，我两块屏幕，放在右边的屏幕时就会有问题，left计算多了一块屏幕的像素，如果放在左边的话定位就是正常的。

**Comment by Vanessa219** [comment]
如果可以的还麻烦切换到 dev 分支启动后访问 http://localhost:9000/render.html  看一下是否正常。

**Comment by lz6060788** [comment]
我这边验证了一下已经确认修复了，铁子辛苦了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Vanessa219/vditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月25日(星期六) 中午11:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Vanessa219/vditor] 文本选中弹出组件 speech 位置被多屏影响 (Issue #1373)





 
如果可以的还麻烦切换到 dev 分支启动后访问 http://localhost:9000/render.html  看一下是否正常。

**Comment by tenglongwentian** [comment]
speech: {
          enable: true,
        },这个配置没生效

**Comment by Vanessa219** [comment]
需在预览界面才有作用

**Comment by tenglongwentian** [comment]
@Vanessa219 预览模式吗

**Comment by Vanessa219** [comment]
嗯

**Comment by tenglongwentian** [comment]
```
Vditor.preview(document.getElementById('Editor1'), 'markdown', {
                speech: {  // 对选中后的内容进行阅读
                    enable: true,
                },
            })
```
V姐上面这个方式与下面这个方式，点击预览有什么不一样吗？toolbar中的preview不是预览吗？
```
this.contentEditor = new Vditor('Editor', {
                height: window.innerHeight,
                cdn: 'vditor',
                placeholder: '此处为笔记内容……',
                theme: 'classic',
                counter: {
                    enable: true,
                    type: '字数统计'
                },
                speech: {  // 对选中后的内容进行阅读
                    enable: true,
                },
                preview: {
                    speech: {
                        enable: true,
                    },
                },
toolbar: ['preview']
})
```

**Comment by Vanessa219** [comment]
上面的是不在编辑器中使用

**Comment by tenglongwentian** [comment]
在编辑器中使用的话，如何开启speech

**Comment by Vanessa219** [comment]
这个选中时会干扰输入，编辑的时候没有这个功能。
