### ISSUE TITLE
Just wonder why image upload does not work 

### ISSUE THREAD

**Issue by gaminglifex** [Vanessa219/vditor#1375]
### 编辑模式

* `sv` 分屏编辑预览模式

### 描述问题

I am trying to implement Imgur API to vditor, and encounterd some issues.

### 期待的结果

What I want to achieve is simple: the image link will be automatically inserted to editor in markdown format when uploading a photo.

### 截屏或录像

What I've got so far:

![image](https://user-images.githubusercontent.com/72642816/227458994-7f2cc455-385f-4b99-8026-fe6ccd416a1e.png)
![image](https://user-images.githubusercontent.com/72642816/227458915-ec552fa5-9e21-43ba-a3db-24aaaa0a38be.png)
### 版本信息

* 版本：3.9
* 操作系统：Windows
* 浏览器：Chrome

**Comment by Vanessa219** [comment]
`format` must be return [JSON string](https://github.com/Vanessa219/vditor/blob/master/README_en_US.md#optionsupload)
