### ISSUE TITLE
目录锚点问题

### ISSUE THREAD

**Issue by lizwxup** [Vanessa219/vditor#1376]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

预览模式下 当新建markdown文章时，设置title为"2.10 表格”时 预览模式下初始化加载outline时会报错

![image](https://user-images.githubusercontent.com/29390455/227497094-58a031f0-bf2c-4257-a563-6e4e09937aa0.png)

![image](https://user-images.githubusercontent.com/29390455/227496561-fabe679b-54ff-42a7-a1d0-7a317b185df9.png)
请问是什么问题？
````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
````````

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

**Comment by Vanessa219** [comment]
是这样操作么？好像重现不了

https://user-images.githubusercontent.com/970828/227689747-7b19b70d-5bee-40aa-a07b-5e7b03c1b01d.mp4
