### ISSUE TITLE
iamge upload Format() does not display image appropiately

### ISSUE THREAD

**Issue by gaminglifex** [Vanessa219/vditor#1377]
### 编辑模式

* `sv` 分屏编辑预览模式

### 描述问题

I have successfully inserted the image link using Format(). However, it only contains the last character of image name and the inserted text is missing an "!".

![image](https://user-images.githubusercontent.com/72642816/227715694-1be27e72-30f2-4f44-90e0-2df658358631.png)
![image](https://user-images.githubusercontent.com/72642816/227715730-4885f7ba-a4c7-4319-907b-a4f70eb41e40.png)

### 期待的结果

Successfully display the image

### 版本信息

* 版本：3.9.1
* 操作系统：Windows
* 浏览器：Chrome

**Comment by Vanessa219** [comment]
Pls update key: `afb40lv` => `afb40lv.jpg`
