### ISSUE TITLE
vscode插件预览模式下复制问题

### ISSUE THREAD

**Issue by yuexiaying** [Vanessa219/vditor#1378]
### 编辑模式

* `ir` 即时渲染模式

问题：vscode插件，在使用预览模式时，无法复制一段文字，后者代码等

期待：可以复制某一段代码、文字等。

### 截屏或录像
![image](https://user-images.githubusercontent.com/58901054/227852474-8959081d-8232-474e-8a65-9e70ee28b433.png)
![image](https://user-images.githubusercontent.com/58901054/227852556-6334e9bb-4d85-4617-bc17-fbb784b3987f.png)

![image](https://user-images.githubusercontent.com/58901054/227852695-ccae0be0-f4f4-46cc-ac45-a60bfeba52d7.png)

**Comment by Vanessa219** [comment]
插件问题请到对应的 GitHub 上提交。
