### ISSUE TITLE
linktoImgURL did not trigger in all editing modes 

### ISSUE THREAD

**Issue by gaminglifex** [Vanessa219/vditor#1379]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

I have just pasted a random image link of imgur to the editor, and the editor did not trigger linkToImgUrl()
![image](https://user-images.githubusercontent.com/72642816/228118758-9fc1ab7b-8c10-42a1-88cb-9933dded26a5.png)

### 期待的结果

it will change the url link to self-defined one.

Thank you for all your hard work:)))

### 版本信息

* 版本：3.9.1
* 操作系统：Windows
* 浏览器：Chrome

**Comment by Vanessa219** [comment]
Please check if `options.upload.linkToImgUrl` returns 200?

**Comment by gaminglifex** [comment]
It does not give any response when I paste a link to the editor.
![image](https://user-images.githubusercontent.com/72642816/228738226-1be247cb-4d0a-4324-8bfa-92d2c17a27e6.png)

**Comment by gaminglifex** [comment]
But when I try to upload a photo to log the options.upload.linkToImgUrl, it returns "https://api.imgur.com/3/image"
![image](https://user-images.githubusercontent.com/72642816/228738439-b2e165fb-f3d3-4311-ac3b-a1c224362ba2.png)

**Comment by Vanessa219** [comment]
`format` is different from `linkToImgFormat`, see [README](https://github.com/Vanessa219/vditor/blob/master/README_en_US.md#optionsupload)
