### ISSUE TITLE
ctrl+b, ctrl+i, enter with no text

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#138]
![ctrl+bctrl+ienter](https://user-images.githubusercontent.com/15811943/74499981-13fddd80-4eab-11ea-98da-18e181858222.gif)

**Comment by 88250** [comment]
Can you reproduce it on https://hacpai.com/guide/markdown at present?

**Comment by jakekwak** [comment]
![Feb-16-2020 07-19-34](https://user-images.githubusercontent.com/15811943/74605331-deb0e580-508c-11ea-9237-5287bf48c4ba.gif)

**Comment by jakekwak** [comment]
`ctrl+b`, `ctrl+i`, `enter`, `backspace`
![issue138](https://user-images.githubusercontent.com/15811943/74854895-90f2e200-5305-11ea-8845-cccfe2e4ad13.gif)

**Comment by Vanessa219** [comment]
@88250
