### ISSUE TITLE
可以实现支持文本高亮吗

### ISSUE THREAD

**Issue by tinghenb** [Vanessa219/vditor#1380]

**Comment by Vanessa219** [comment]
`==test==`

**Comment by tinghenb** [comment]
> `==test==`

<img width="918" alt="image" src="https://user-images.githubusercontent.com/100949942/229115129-534bab77-5a34-44ee-b4f6-01ae43c138a2.png">
<img width="926" alt="image" src="https://user-images.githubusercontent.com/100949942/229115401-b34fd768-771d-4591-906a-e07b94adfb49.png">

使用了这样的语法，但是没有出现高亮

**Comment by Vanessa219** [comment]
升级到 3.9.0 试试。 https://ld246.com/guide/markdown 这个上面是可以的。
