### ISSUE TITLE
有序列表和无序列表显示不出?

### ISSUE THREAD

**Issue by zsq44** [Vanessa219/vditor#1381]
![error](https://user-images.githubusercontent.com/84017819/229169249-dc39e80a-bf07-446a-8fe1-ff340b3a8dcd.png)

# 有序列表和无序列表没有符号

- 没有前面圆点

1. 没有前面序号
   1. 没有序号

- 没有圆点
  - 没有圆点

**Comment by Vanessa219** [comment]
https://b3log.org/vditor/demo/option-mode.html 这个上面是可以显示的，看一下是不是样式被重置了？

**Comment by zsq44** [comment]
在样式检查中，li标签没有::markdown



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月1日(星期六) 上午9:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Vanessa219/vditor] 有序列表和无序列表显示不出? (Issue #1381)





 
https://b3log.org/vditor/demo/option-mode.html 这个上面是可以显示的，看一下是不是样式被重置了？
 
&mdash;

**Comment by Vanessa219** [comment]
那应该是被重置了，移除重置的样式即可。

**Comment by longyu2** [comment]
我也遇到这样的问题，于是搜了搜 issue ，检查发现被使用的组件库的 css 覆盖了，感谢！
