### ISSUE TITLE
请问能支持自定义echats解析吗，我加了个世界地图和词云，都显示不出来

### ISSUE THREAD

**Issue by dodudo** [Vanessa219/vditor#1383]
### 你在什么场景下需要该功能？

插入世界地图，和词云

### 描述最优的解决方案 

希望有自定义解析echarts的方法，谢谢！

**Comment by wu-nian** [comment]
您好，大佬，我想了解那个msns的音乐社交网站。如果您看到这条评论能联系我一下嘛？真的很急，求求您，谢谢了。我的Q：2214457497

**Comment by Vanessa219** [comment]
这个不是我们做的，你应该发错了
