### ISSUE TITLE
代码块颜色问题

### ISSUE THREAD

**Issue by youjunxiaji** [Vanessa219/vditor#1385]
**在我使用代码块功能时，有一个很有意思的bug，但是不知道是不是我的设置没设置好，具体问题如下：**
* 当我使用vscode原主题时，渲染后的代码不在显示
![image](https://user-images.githubusercontent.com/94896689/231333929-01203dce-f1ad-4bfc-8d1f-270983ab1912.png)
* 但是在我编辑状态下是这样的
![image](https://user-images.githubusercontent.com/94896689/231333997-dd66c109-0379-4501-88cd-b3845e540d83.png)
**这个问题只出现在深色主题中，我不知道为什么，如果是我设置的不对，请给一个解决方法，感谢博主！**

**Comment by Vanessa219** [comment]
我这里是正常的，需要一下你的操作步骤，和配置参数，以及 md 原文。
<img width="960" alt="image" src="https://user-images.githubusercontent.com/970828/231644749-ebcd20f1-9a03-4b5d-883c-77191f6770de.png">

**Comment by youjunxiaji** [comment]
> 我这里是正常的，需要一下你的操作步骤，和配置参数，以及 md 原文。 <img alt="image" width="960" src="https://user-images.githubusercontent.com/970828/231644749-ebcd20f1-9a03-4b5d-883c-77191f6770de.png">

> 是的 我这里也变得正常了，可能是我外接显示器的原因？？？

**Comment by Vanessa219** [comment]
可以重现的话麻烦记录一下以上信息。
