### ISSUE TITLE
在内网中，vditor包中有CDN，导致内网中无法使用，请问如何解决！

### ISSUE THREAD

**Issue by JackFrancisLiu** [Vanessa219/vditor#1388]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
````````

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

**Comment by tenglongwentian** [comment]
new Vditor('MarkdownEditor', {
cdn: '自建地址，比如assert',
})
