### ISSUE TITLE
通过插件实现一些不常使用的功能以便减少vditor体积

### ISSUE THREAD

**Issue by rts-gordon** [Vanessa219/vditor#1389]
### 你在什么场景下需要该功能？

Hi there.
   很高兴能够使用vditor编辑器。对于一个简单的markdown应用来说，vditor还是太大了。是否可以考虑把部分不常用的功能分解出来，通过plugin的方式引用，这样可以有效减少vditor基础功能发布包的体积？

### 描述最优的解决方案 

分解后的vditor plugin:
  vditor-core: vditor核心功能插件；
  vditor-plugin-mermaid: 流程图插件；
  vditor-plugin-uml: UML图插件；
  vditor-plugin-abc: 五线谱插件；
  vditor-plugin-media: 媒体插件；

**Comment by Vanessa219** [comment]
感谢反馈。目前这几个插件代码都很少，主要是用第三方的实现，且第三方代码是通过异步按需加载的。

基于没有插件体系和目前精力有限，就先不处理了。
