### ISSUE TITLE
添加功能：通过鼠标点击实现checkbox的勾选与取消

### ISSUE THREAD

**Issue by Chopong** [Vanessa219/vditor#1390]
### 你在什么场景下需要该功能？

How about toggling task checkbox between checked and unchecked by clicking.

在分屏模式下，通过更改源码：添加或者删去 x 实现 checkbox 的勾选和取消，如不勾选`- [ ] Task`，勾选`- [x] Task`.
除了分屏浏览，在所见即所得和即时渲染两个模式下，都需要重新删掉checkbox 重新输入。

而目前很多markdown编辑器是支持通过鼠标点击的方式，实现checkbox的勾选与取消的。

**Comment by Vanessa219** [comment]
由于 https://github.com/Vanessa219/vditor/issues/1319 ，将不再为该编辑模式添加新功能。
