### ISSUE TITLE
html2md(getHTML()) 不能正确转换复原数学公式

### ISSUE THREAD

**Issue by LePtC** [Vanessa219/vditor#1392]
### 编辑模式

* `ir` 即时渲染模式

### 描述问题

比如 `vditor.setValue("笔记示例 $y=e^z$ 。\n\n$$\n\\int_0 x dx\n$$\n\n")`

![image](https://user-images.githubusercontent.com/6371171/235295075-edd4a3da-c9ed-4979-a1f3-96161219e519.png)

做 `vditor.html2md(vditor.getHTML())` 

得到的是inline数学公式变成了粗体，块公式变纯文本：

````````markdown
笔记示例 **y=e^z** 。\n\n\\\\int\\_0 x dx\n
````````

![image](https://user-images.githubusercontent.com/6371171/235295027-b7463ba4-27b5-44ec-8afe-765ccaac5721.png)

### 期待的结果

希望 `html2md` 能还原和 `vditor.getValue()` 一样的结果，数学公式以 `$` 和 `$$` 正确包裹

### 版本信息

* 版本：3.9.2
* 操作系统：Win10
* 浏览器：Edge 111.0

**Comment by 88250** [comment]
使用 `vditor.getHTML()` 返回的是“标准 DOM”，这个没有办法还原为 Markdown。

只有编辑模式下的 DOM 可以相互转换。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by LePtC** [comment]
@88250 感谢解答！请问编辑模式的DOM指的是什么样的获取方式呀？

我尝试了 `vditor.html2md(document.querySelector('.vditor-ir pre').innerHTML)`

得到的结果还是很怪：
'笔记示例 **$**`y=e^z`$ 。\n\n$$\n```math\n\\int_0 x dx\n```\n$$\n'
（行内$周围还是有加粗，块公式周围有代码环境，重新setValue不能复原笔记）

**Comment by 88250** [comment]
你可能需要看下 Vditor 是如何在 IR/WYSIWYG 模式切换的，那里会涉及到 DOM 之间的转换。

**Comment by PCSK01** [comment]
你好，请问你最后怎么解决的
