### ISSUE TITLE
ul、ol、blockquote按钮在存在选区时只对第一行生效

### ISSUE THREAD

**Issue by LePtC** [Vanessa219/vditor#1393]
### 编辑模式

* `ir` 即时渲染模式

### 描述问题

ul、ol、blockquote按钮在存在选区时只对第一行生效

![录制_2023_04_29_17_29_20_165](https://user-images.githubusercontent.com/6371171/235295862-01f0a381-7382-4ebb-a166-1745d4a47e7e.gif)

### 期待的结果

如 typora，应对全部生效

![录制_2023_04_29_17_27_23_429](https://user-images.githubusercontent.com/6371171/235295871-080b8459-663c-4c9d-b7be-1469f22e198a.gif)

### 版本信息

- 版本：3.9.2
- 操作系统：Win10
- 浏览器：Edge 111.0

### 其他信息

如果作者就是想要只生效一行的效果，那能教一下如何DIY一个对全部选区生效的按钮也可以…

**Comment by Vanessa219** [comment]
目前精力有限，这个功能短期内无法实现。相关代码如下，需要对所选的 blockElement 依次进行添加
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/970828/236591931-7e73b46e-b890-40b0-b9fe-678ba66c603e.png">
