### ISSUE TITLE
分屏预览模式(sv)，粘贴过多内容，开始编辑会卡死，内容暴增!

### ISSUE THREAD

**Issue by wangxiang365** [Vanessa219/vditor#1396]
### 编辑模式

* `sv` 分屏编辑预览模式

### 描述问题

````````markdown
分屏预览模式粘贴较多内容，然后开始编辑例如: 回车输入文字， 此时编辑器会卡死，内存会不停的增加，能增加到5-6个G，导致崩溃
````````

### 截屏或录像
![image](https://user-images.githubusercontent.com/20636009/236363333-a501434b-4e86-4f87-9714-fce2ed7904c9.png)
此截图是已经卡死状态

### 版本信息

* 版本：
* 操作系统：windows10
* 浏览器：chrome 当前最新版本

**Comment by Vanessa219** [comment]
后期不再支持 https://github.com/Vanessa219/vditor/issues/1319
