### ISSUE TITLE
第一次进入页面初始化正常，第二次进入页面输入框出现诡异的代码

### ISSUE THREAD

**Issue by tgpx1899** [Vanessa219/vditor#1398]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

第一次进入页面初始化正常，第二次进入页面输入框出现诡异的代码

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
````````

### 版本信息

* 版本：3.9.2
* 操作系统：windows
* 浏览器：chrom

### 其他信息

页面如下
![image](https://user-images.githubusercontent.com/42924764/236798317-7ce05fac-866a-4887-82be-d88ab4a5d8f7.png)

**Comment by Vanessa219** [comment]
可运行对比一下 demo/index.html 中的代码配置
