### ISSUE TITLE
文档更新: cdn 和 upload | 功能请求: 支持视频上传

### ISSUE THREAD

**Issue by ZehuaZhang** [Vanessa219/vditor#1399]
首先非常感谢这个强大的富文本编辑器 非常厉害。我有些问题想问问你

1. 我想问下CDN这个option property是用来干什么的 能详细阐述下吗
2. 对于图片上传 我只要把Amazon S3, 或者其他Cloud provider的API 放在option.upload.url就可以了吗
3. linkToImgUrl 可以详细阐述下吗 文档解释的不是特别清楚
4. 我看了源码，是否可以支持上传视频吗 可以作为一个功能请求吗

**Comment by Vanessa219** [comment]
1. 用于配置自建 CDN 地址
2. 可能需要 TOKEN 之类的参数
3. 参考 https://ld246.com/article/1549638745630#options-upload ，具体是哪里不清楚呢？
4. 可以的

**Comment by ZehuaZhang** [comment]
感谢回复 🙏
1. 我在vditor写的资源会上传到默认的cdn? 可以稍微具体解释一下吗
2. 我可能得写自己的upload.handler 谢谢你的接口 因为我不想让用户看到S3的上传链接 而是自己网站后端API
3. 我不太理解的点是，它上传到哪里呢，哪个服务器上，是upload.url自定义的云端存储吗, 源码[vditor/src/ts/upload](https://github.com/Vanessa219/vditor/tree/master/src/ts/upload)
/index.ts 没看到相关的代码， · linkToImgUrl· 指的是站外图片原地址，还是自定义云端存储，不需要token吗想upload.url一样？
4. 你是指upload功能吗 我看了[源码](https://github.com/Vanessa219/vditor/blob/dd89bde0f6b0cfda96f49347d54a0a26c006b8a3/src/ts/upload/index.ts#L108-L137) 视频好像不支持

**Comment by Vanessa219** [comment]
1.  不会，可查阅一下 cdn 相关资料，这里就不展开细说了
2. 用自己的后端服务就可以了，相关配置可参阅文档
3. 上传到指定的 url 上
4. 支持的
```
            if (vditor.currentMode === "wysiwyg") {
                succFileText += `<a href="${path}">${filename}</a>\n`;
            } else {
                succFileText += `[${filename}](${path})\n`;
            }
```

**Comment by ZehuaZhang** [comment]
谢谢啊 是因为文档不清楚 所以才在这请教您的
1. 所以cdn 我不填保持默认就好了
2. option.upload.url 指的是什么呢 是云端存储API吗 还是云端存储地址 一般的话都是调用第三方api再返回文件在云端存储地址的
3. 能举个例子吗 剪贴板中包括图片地址的例子 如果剪贴版中有多个图片地址呢 而且指定的url 对于云端存储不能适用 因为一般都是调用api再返回文件在云端存储地址的 为什么不能像 option.upload一样呢 可以自定义上传

> 为了防止站外图片失效， linkToImgUrl 可将剪贴板中的站外图片地址传到服务器端进行保存处理，其数据结构如下：
>```
>// POST data
>xhr.send(JSON.stringify({url: src})); // src 为站外图片地址
>// return data
>{
>   msg: '',
>   code: 0,
>   data : {
>     originalURL: '',
>     url: ''
>   }
>}
>```
文档里写的`url:src` 中的`src`就是`linkToImgUrl`吗 真的不太理解 因为对不上
5. 所以只是一个a tag link 会解析链接中的视频是吗 那如果我把视频存在Amazon S3就没有办法了 可以提供接口让我渲染一个简单的media player吗 文档有些提供的视频地址解析 像其他的文档pdf上传都是不支持的是吗 文档没看到
6. 能追加一个问题吗 图片上传了 如何缩放 手动还是写markdown的方式 来调整

**Comment by Vanessa219** [comment]
* option.upload.url 是服务端上传的地址
* src 和 linkToImgUrl 是两个完全不同地址
* 没太明白
* 使用 html 标记
