### ISSUE TITLE
*** after shift+enter

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#140]
It is converted to `<hr/>` automatically without `enter`.

`Foo`, `shift+enter`, `---`, `enter`
`Foo`, `shift+enter`, `***`

![autohr](https://user-images.githubusercontent.com/15811943/74500950-36ddc100-4eae-11ea-8f68-9ebf0f944290.gif)

**Comment by 88250** [comment]
https://github.com/Vanessa219/vditor/issues/125#issuecomment-586324327
