### ISSUE TITLE
在 Chrome 插件中运行，遇到CSP问题

### ISSUE THREAD

**Issue by lilee** [Vanessa219/vditor#1402]
### 描述问题

在 Chrome 插件中运行，报错：

Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-kLMTdbP3pLQRHzI4AYMXim60x6usVWoGAc2ydjKVFcc='), or a nonce ('nonce-...') is required to enable inline execution.

代码如下
``` tsx
function App() {
  React.useEffect(() => {
    const vditor = new Vditor("vditor", {
      mode: 'sv',
      after: () => {
        const content = localStorage.getItem('markdown');
        vditor.setValue(content ?? '');
      },
      cdn: './vditor',
    });
  }, []);
  return (
    <div id="vditor" className="vditor" />
  );
}
```

**Comment by Vanessa219** [comment]
源码里面没有使用 eval，具体原因还需要再帮忙排插排插

**Comment by v2-lab** [comment]
遇到了同样的问题，猜测是编辑栏的svg图标的问题，因为这些图标都展示不出来了

<img width="1744" alt="image" src="https://github.com/Vanessa219/vditor/assets/54586366/eced2dc0-4750-40ea-8587-86860c7cce8e">

**Comment by v2-lab** [comment]
v3的插件开发如果不用自定义的cdn同样会有CSP的问题，但因为安全策略的原因无法通过manifest的配置来解决

**Comment by v2-lab** [comment]
图标的问题应该是在插件环境下 vditorIconScript 执行有问题，在chrome插件中执行document.body.insertAdjacentHTML插入svg会有问题

**Comment by Vanessa219** [comment]
V3插件是？

**Comment by v2-lab** [comment]
用chrome manifestv3的规则
