### ISSUE TITLE
列表格式异常

### ISSUE THREAD

**Issue by SmartVive** [Vanessa219/vditor#1403]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

在输入了一个无序列表后按回车，第二行时按删除键，再输入两个空格和一个-，这时第一个列表变成了标题

### 期待的结果

第二行变成二级列表

### 截屏或录像

![截图](https://i.328888.xyz/2023/05/15/VZafIt.gif)

### 版本信息

* 版本：官方完整示例
* 操作系统：win10
* 浏览器：Chrome  113.0.5672.93

**Comment by Vanessa219** [comment]
子标题的话可以回车后使用 tab，你这种输入回触发规范中的另一种写法 https://spec.commonmark.org/0.30/#setext-headings
