### ISSUE TITLE
所见即所得模式将加粗和斜体混合操作会导致问题

### ISSUE THREAD

**Issue by LookForward1** [Vanessa219/vditor#1404]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

在demo里面，对下面一行做加粗和斜体操作。
“不熟悉 Markdown 可使用工具栏或快捷键进行排版”

首先将 "工具栏或快捷键进行排" 进行加粗
然后将 “快捷键进行排版”进行斜体操作。
获得下面的markdown输出.
* 不熟悉 Markdown 可使用**工具栏或*快捷键进行排****版*

````````markdown
* 不熟悉 Markdown 可使用**工具栏或*快捷键进行排****版*
````````

### 期待的结果
"工具栏或" 进行加粗, “快捷键进行排”是粗体加斜体，“版”是斜体

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

### 其他信息
直接操作 https://ld246.com/guide/markdown

目前尝试下来， ****被解析成 ** 的escape.
如果将输出改成,将斜体和粗体之间加空格，输出格式正常，只是多了一个空格:
* 不熟悉 Markdown 可使用**工具栏或*快捷键进行排*** *版*

**Comment by LookForward1** [comment]
建议将斜体和粗体在一块的时候，将斜体用<span></span>进行包裹起来。
```markdown
* 不熟悉 Markdown 可使用**工具栏或<span>*快捷键进行排*</span>**<span>*版*</span>
```

**Comment by Vanessa219** [comment]
交叉操作后遵循 CommonMark 后就是这样的，如果加 `<span>` 的话会使 md 结构复杂，无法使用 md 的标记。
