### ISSUE TITLE
SV模式下，mermaid流程图没有箭头

### ISSUE THREAD

**Issue by Hyggge** [Vanessa219/vditor#1405]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `sv` 分屏编辑预览模式

### 描述问题

我想使用mermaid来绘制一段流程图，对应mermaid代码如下图所示

````````markdown
```mermaid
flowchart LR
A[Hard] -->|Text| B(Round)
B --> C{Decision}
C -->|One| D[Result 1]
C -->|Two| E[Result 2]
```
````````

在wysiwyg模式下，渲染正常：

![image](https://github.com/Vanessa219/vditor/assets/92776215/24e8f34a-977f-4233-ad00-7067e9e07c0c)

此时切换到sv模式，发现流程图中没有了箭头：

![image](https://github.com/Vanessa219/vditor/assets/92776215/47e83a9d-389d-4f77-aec7-baead5bb6ba9)

此外，比较神奇的是，如果一刷新页面直接进入sv模式（此时内容为空），然后输入上述代码，发现渲染是正常的：

![image](https://github.com/Vanessa219/vditor/assets/92776215/7a535117-a66c-4523-a6b9-eba848b5417a)

但是，如果此时切换到wysiwyg模式，然后再切换回sv模式，箭头又消失了。

![image](https://github.com/Vanessa219/vditor/assets/92776215/2c7b31e9-25d7-410b-988a-bc4b49443784)

### 期待的结果

我希望在sv模式下，流程图的箭头可以正常渲染。

**Comment by Vanessa219** [comment]
需等待 https://github.com/mermaid-js/mermaid/issues/4089 修复
