### ISSUE TITLE
分屏编辑预览模式下-复制https://ld246.com/guide/markdown Demo内容，随便操作下就卡死了， 内存直接炸裂(哪怕是敲击个空格)

### ISSUE THREAD

**Issue by wangxiang365** [Vanessa219/vditor#1406]
分屏编辑预览模式下-复制https://ld246.com/guide/markdown Demo内容，随便操作下就卡死了， 内存直接炸裂(哪怕是敲击个空格)
下图为已卡死，怎么都操作不了
![image](https://github.com/Vanessa219/vditor/assets/20636009/10f5953b-8b36-4750-a15a-20b9acb2819c)

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/1319
