### ISSUE TITLE
React环境下 输入内容后立即点击工具栏下拉无反应

### ISSUE THREAD

**Issue by zyzcss** [Vanessa219/vditor#1408]
### 编辑模式
* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题
上次提了一个issues: 
[https://github.com/Vanessa219/vditor/issues/1391](https://github.com/Vanessa219/vditor/issues/1391)
我拉源码后运行发现工具栏正常,但是在react环境下仍会出现该问题(已确认版本为最新的3.9.3)
react demo 预览:
[https://zyzcss.github.io/vditor/index.html](https://zyzcss.github.io/vditor/index.html)
react demo 源码:
[https://github.com/zyzcss/vditor-demo](https://github.com/zyzcss/vditor-demo)
### 期待的结果
在react环境下工具栏正常

### 截屏或录像
![Peek 2023-04-28 17-29](https://github.com/Vanessa219/vditor/assets/34860281/e34cc507-98de-4a4d-98c7-4b8a05d0ec44)

### 版本信息

* 版本：3.9.3
* 操作系统：
* 浏览器：

**Comment by Vanessa219** [comment]
可以拉源码进行调试，目前我也没有办法进行定位。

**Comment by zyzcss** [comment]
@Vanessa219 发现问题了,与react环境无关,mode设置为wysiwyg时没问题,mode不填或者设置为sv或者ir的时候会出现这种情况

**Comment by Vanessa219** [comment]
好的，那我先关闭了。
