### ISSUE TITLE
IR, SV 模式下输入内容后立即点击工具栏下拉无反应

### ISSUE THREAD

**Issue by zyzcss** [Vanessa219/vditor#1414]
### 编辑模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题
IR, SV模式下输入内容后立即点击工具栏下拉无反应
源问题:
[https://github.com/Vanessa219/vditor/issues/1408](https://github.com/Vanessa219/vditor/issues/1408)
调试后发现是IR和SV模式的问题, 这两个模式下会再次触发focusEvent, wysiwyg模式下是正常的
配置:
```
{
  mode: 'ir'
}
```

### 期待的结果
工具栏无问题

### 截屏或录像

![image](https://github.com/Vanessa219/vditor/assets/34860281/e09a4512-9ecc-4c06-8951-0dbf9abe9bfe)

### 版本信息

* 版本：3.9.3
* 操作系统：
* 浏览器：

**Comment by Vanessa219** [comment]
s
