### ISSUE TITLE
lists when indented at wysiwyg mode

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#142]
i am expecting the same type at ordered(`1)`) & unordered list (`-`)

![Screen Shot 2020-02-13 at 11 59 28 PM](https://user-images.githubusercontent.com/15811943/74505526-fd608200-4ebc-11ea-8016-827fe4fec9ee.png)

I think new list that started after hit two `enter` should be the different list. (toggled between `*` and `-`(`+`) )

**Comment by 88250** [comment]
Sorry, I didn't understand what you meant. 😕

**Comment by jakekwak** [comment]
I expected 4, 5, 6
![Feb-16-2020 06-36-03](https://user-images.githubusercontent.com/15811943/74604772-ac03ee80-5086-11ea-8048-5d6dede318da.gif)

**Comment by jakekwak** [comment]
@Vanessa219 same shape when tabed at wysiwyg mode.
for example,
```
1) test
    1) test
    2) test

+ test
    + test
    + test
```

**Comment by jakekwak** [comment]
![unol](https://user-images.githubusercontent.com/15811943/75004198-f8a54c00-542f-11ea-87b8-811002287e95.gif)

**Comment by 88250** [comment]
Too many details need to handle...
