### ISSUE TITLE
支持自动链接配置 `gfmAutoLink`

### ISSUE THREAD

**Issue by 0214ggyy** [Vanessa219/vditor#1422]
### 文本案例
哈哈哈http://192.168.111.215:8080/哈哈哈
哈哈哈http://192.168.111.215哈哈哈12
[http://192.168.111.215:3000](http://192.168.111.215:3000)

### previewRender 模式显示
![image](https://github.com/Vanessa219/vditor/assets/45169483/71dfa236-f192-4876-9aa3-260bc9e9afe2)

### 即使渲染SpinVditorIRDOM/分屏SpinVditorSVDOM 所见所得/SpinVditorDOM  显示
![image](https://github.com/Vanessa219/vditor/assets/45169483/eb385199-47fb-4421-be48-a106e80d01a9)

期望能够一致 幸苦了

**Comment by Vanessa219** [comment]
需要设置 `autoSpace` 和准备添加的 `gfmAutoLink` 来使其保持一致。

**Comment by lulu2jinchi** [comment]
亲爱的作者大大，3.9.6版本sv模式，右侧实时渲染时，配置了
preview: {
      actions: [],
      markdown: {
        toc: true,
        gfmAutoLink: true,
      },
      math: {
        inlineDigit: true,
      },
      hljs: {
        lineNumber: true,
      },
    },但是链接还是没有自动变成a标签的自动链接，getHTML()里也是没有a标签的内容，是纯文本，这是咋回事呢。直接调用previewRender是可以变自动链接的，但是有场景需要getHTML()

**Comment by Vanessa219** [comment]
@88250 在编辑器里面确实不行，看一下是什么问题

**Comment by 0214ggyy** [comment]
在欢乐时，朋友们会认识我们；在患难时，我们会认识朋友。谢谢，来信！！！

**Comment by 88250** [comment]
Vditor 的三个模式均不支持 auto link，只有纯做渲染的时候才支持。
