### ISSUE TITLE
需求希望有一个数学公式的开关

### ISSUE THREAD

**Issue by 0214ggyy** [Vanessa219/vditor#1424]
## 描述：
 目前在markdown文本编写或者复制code其中 $$符号会被强制变成数学公式。

## 期望：
期望有一个如图开关
[另外一个markdown表现](https://bytemd.js.org/playground/)

![image](https://github.com/Vanessa219/vditor/assets/45169483/e3fef398-151e-4422-9003-1d2b88c82c2c)

**Comment by Vanessa219** [comment]
可以使用 `\` 转义
