### ISSUE TITLE
链接中间回车问题

### ISSUE THREAD

**Issue by hanxiaohuivc** [Vanessa219/vditor#1427]
### 编辑模式

* `sv` 分屏编辑预览模式

### 描述问题

在链接的文字的中间位置输入回车，会导致插入重复的文字。多次回车可能会导致页面卡住不动。
![image](https://github.com/Vanessa219/vditor/assets/8023520/e12336b2-75ec-4a03-8eb8-76d6abfeab2f)

### 期待的结果

链接失效或只保留一个有效链接。

### 版本信息

* 版本：v3.9.3
* 操作系统：win10
* 浏览器：chrome 113

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/1319 SV 模式将重新改造，相关问题不再进行修改。
