### ISSUE TITLE
[suggestion]  ctrl+m

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#143]
I think the first cell after `ctrl+m` should the selected text.
`Tab` or `shift+tab`  from cell to cell when text exists

`ctrl+m`, `tab`, `tab`, `tab`, `tab`, `a`, ....

![800595458_1581352825 2866](https://user-images.githubusercontent.com/15811943/74542726-bd73bc00-4f09-11ea-88bd-065463485eab.gif)

**Comment by jakekwak** [comment]
not keeping selected text
![ctrl+m](https://user-images.githubusercontent.com/15811943/74851791-54bd8280-5301-11ea-97d6-f8f08688389c.gif)

**Comment by Vanessa219** [comment]
It's just that ctrl + m doesn't keep the selected state. Can the tab key and Shift + tab keep the selected text?

**Comment by jakekwak** [comment]
not keep some cell. (`testtest` means not keeping at shift+tab)

**Comment by Vanessa219** [comment]
shift+tab cannot be reproduced, see the attachments.
[QQ20200220-133351.gif.zip](https://github.com/Vanessa219/vditor/files/4228966/QQ20200220-133351.gif.zip)

**Comment by jakekwak** [comment]
I think it is ok with new code.
