### ISSUE TITLE
在代码块中连按空格会导致错乱

### ISSUE THREAD

**Issue by jamebal** [Vanessa219/vditor#1430]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

在代码块中连按空格会导致错乱

### 截屏或录像

https://github.com/Vanessa219/vditor/assets/49510841/67ac00cf-c9e2-4dcf-b502-e4cac0dd9fbe

### 版本信息

vditor 示例可重现： https://ld246.com/guide/markdown

**Comment by Vanessa219** [comment]
是这样操作么？无法重现。

https://github.com/Vanessa219/vditor/assets/970828/06d90a4c-8720-4484-994c-bccf09cd39e1
