### ISSUE TITLE
选中并且删除代码块中的前N个字符串时，会删除当前整行

### ISSUE THREAD

**Issue by KevinBlandy** [Vanessa219/vditor#1432]
如图所示：

![GIF](https://github.com/Vanessa219/vditor/assets/17979625/a3f24477-2076-4e9c-a2ec-cbe9e7fa8be3)

如果一个一个字符删除，则是正常的。

![GIF](https://github.com/Vanessa219/vditor/assets/17979625/c4f8bc9a-a866-4961-9ff6-14b153f089d3)

**Comment by Vanessa219** [comment]
鉴于 https://github.com/Vanessa219/vditor/issues/1319 ，不在修复 sv 模式相关 bug。
