### ISSUE TITLE
Emoji popup when pressing enter with markdown editor not focused

### ISSUE THREAD

**Issue by ZehuaZhang** [Vanessa219/vditor#1433]
`ir`, when pressing enter with markdown editor not focused, e.g. focused on some other textfields, emoji modal pops up

**Comment by Vanessa219** [comment]
无法重现，还麻烦录屏，谢谢。

**Comment by ZehuaZhang** [comment]
I'm using MUI, Textfield single line when pressing enter shows emoji pop up, but Textfield multiline works fine
https://github.com/Vanessa219/vditor/assets/15708284/1a8f3398-c396-4d7b-aeb3-8dcd2206b396

**Comment by Vanessa219** [comment]
这个可能需要你自己调试一下是什么触发了 emoji 的显示。具体可在这里断点看看  https://github.com/Vanessa219/vditor/blob/4d429962215f7a98ce1404371af1ba6c68267a5a/src/ts/toolbar/Emoji.ts#L41

**Comment by ZehuaZhang** [comment]
Not sure why you marked this as completed, you could add a html `<input>`, I think it'd trigger the same

**Comment by Vanessa219** [comment]
因为我已经测试过了，不会出现你说的问题。如果你不相信的话我可以再测试一遍并进行录屏。

https://github.com/Vanessa219/vditor/assets/970828/da29b483-5165-4183-9f3a-ec9d544f7acb
