### ISSUE TITLE
mermaid.js最新版本语法支持

### ISSUE THREAD

**Issue by wisesean** [Vanessa219/vditor#1434]
### 你在什么场景下需要该功能？

通过vditor展示ER图时，使用mermaid 10.2.4最新版本语法的官网示例能够正常展示ER图。

### 描述最优的解决方案 

更新到最新版本的mermaid

### 描述候选解决方案

提供其他的ER图展示例如：CytoscapeJS
官网链接如下：
[https://js.cytoscape.org/](https://js.cytoscape.org/)

### 其他信息

<img width="877" alt="image" src="https://github.com/Vanessa219/vditor/assets/1955604/5718fade-b508-4105-9086-bed20d2a466d">

erDiagram
    CUSTOMER ||--o{ ORDER : places
    CUSTOMER {
        string name
        string custNumber
        string sector
    }
    ORDER ||--|{ LINE-ITEM : contains
    ORDER {
        int orderNumber
        string deliveryAddress
    }
    LINE-ITEM {
        string productCode
        int quantity
        float pricePerUnit
    }

**Comment by Vanessa219** [comment]
目前显示如下，想问一下是哪里显示不正常？以方便我在更新后进行检测。
<img width="916" alt="image" src="https://github.com/Vanessa219/vditor/assets/970828/0d20f325-c2c5-4373-97e6-eb105195a13e">

**Comment by wisesean** [comment]
> 目前显示如下，想问一下是哪里显示不正常？以方便我在更新后进行检测。 <img alt="image" width="916" src="https://user-images.githubusercontent.com/970828/254132162-0d20f325-c2c5-4373-97e6-eb105195a13e.png">

我这边显示没有带实体的属性呢，版本：3.9.1，chrome版本：版本 114.0.5735.198（正式版本） (x86_64)
操作系统：macos 12.3.1 (21E258)
显示内容如下：
![image](https://github.com/Vanessa219/vditor/assets/1955604/b9dbf65e-3a85-4974-902a-0ed2a2e90771)

**Comment by Vanessa219** [comment]
升级到 3.9.4 试试
