### ISSUE TITLE
When the Firefox browser accesses qexo and uses the form, there is no small frame for adjusting the form

### ISSUE THREAD

**Issue by cyolc932** [Vanessa219/vditor#1435]
### 编辑模式
wysiwy

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

When the Firefox browser accesses qexo and uses the form, there is no small frame for adjusting the form
````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
````````

### 截屏或录像
![](https://github.com/Qexo/Qexo/assets/46415893/0c51e1be-cdf4-4b8e-9873-19a3c66c8b9a)

### 版本信息

* 版本：Qexo v2.4.3
* 操作系统：Win11
* 浏览器：Firefox

### 其他信息
github.com/Qexo/Qexo/issues/416
![图片](https://github.com/Vanessa219/vditor/assets/46415893/23525aaf-f56e-414a-9f44-6bebfdb2204d)

**Comment by Vanessa219** [comment]
抱歉，没太看明白你的需求。

**Comment by cyolc932** [comment]
> 抱歉，没太看明白你的需求。

火狐浏览器访问qexo在使用表格的时候没有那个表格编辑项

**Comment by Vanessa219** [comment]
qexo 是什么？

**Comment by cyolc932** [comment]
> qexo 是什么？

使用了vditor的开源项目

**Comment by Vanessa219** [comment]
由于表格内不允许嵌套表格，所以在表格内时会被设置为不可用状态。
