### ISSUE TITLE
外部链接图片上传服务器功能

### ISSUE THREAD

**Issue by yanyuepeng** [Vanessa219/vditor#1438]
由于接口原因，外部链接图片上传直接通过linkToImgUrl写个url并不满足

能否像handler一样也支持自定义上传

**Comment by Vanessa219** [comment]
这个和上传不太一样，具体时那里不满足？相关代码在 https://github.com/Vanessa219/vditor/blob/ab1d1451f58a455f4f77b72030d3e59274e4bdec/src/ts/util/fixBrowserBehavior.ts#L1294

**Comment by yanyuepeng** [comment]
> 这个和上传不太一样，具体时那里不满足？相关代码在
> 
> https://github.com/Vanessa219/vditor/blob/ab1d1451f58a455f4f77b72030d3e59274e4bdec/src/ts/util/fixBrowserBehavior.ts#L1294

就是能否在上传出提供一个方法，可以获取到图片的url或者base64，方便前端处理成本地文件再上传
只写个url 和 自定义上传文件时不一致，还要改动接口

**Comment by Vanessa219** [comment]
文档中应该是按照接口来的，你说的和文档差异较大的接口是？

base64 支持可具体查看 https://github.com/Vanessa219/vditor/pull/1231
