### ISSUE TITLE
ctrl+shift+. 插入 blockquote

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#144]
`ctrl+.`, `test`, `enter`, 
`ctrl+.`, `test`, `enter`,
`ctrl+.`, `test`, `enter`,
`enter`, `enter`, `enter`

![blockquote1](https://user-images.githubusercontent.com/15811943/74546311-03338300-4f10-11ea-8aaa-57ce56fc1f36.gif)

**Comment by jakekwak** [comment]
@Vanessa219 Did you fix this issue? not working

**Comment by Vanessa219** [comment]
I think you need to cancel when you press `ctrl + .` in blockquote.

If not, pls tell me the details.

**Comment by jakekwak** [comment]
My idea is 
`ctrl+.':  nested inside blockquote
cancel : `backspace` or `ctrl+shift+.`
I think this one is better UI.

**Comment by Vanessa219** [comment]
Carte in blockquote, toolbar will highlight it.
In the toolbar, when highlighted, click to cancel; when normal, click to add.
I think what you said is better for the user experience, but this conflicts with the above and I don't know what to do.
![image](https://user-images.githubusercontent.com/970828/74934527-6302c000-5421-11ea-978f-d49721c4825a.png)

**Comment by jakekwak** [comment]
How about ctrl+shift+. (ctrl+>) and ctrl+shift+,(ctrl+<)

**Comment by jakekwak** [comment]
![blockquote](https://user-images.githubusercontent.com/15811943/74977976-5ebeae80-53f1-11ea-94bc-14e986f5414d.gif)
