### ISSUE TITLE
CDN地址改进

### ISSUE THREAD

**Issue by ygzhang-cn** [Vanessa219/vditor#1440]
CDN配置参数N多个地方，能否合为一个？
CDN配置后，发现起始地址都包含有/dist/，如使用国内CDN镜像，几家服务商镜像地址均不包含dist，路径中的dist是源码中直接写入的，每次官方更新后都要clone下来替换这个/dist/，请官方考虑是否可以直接删除这个/dist/

**Comment by Vanessa219** [comment]
初始化的时候应该配置一次就可以了，dist 直接把目录传上去应该就可以了。

**Comment by Vanessa219** [comment]
以前转换过有问题，不知道现在能不能完全支持了。

**Comment by Nyazira** [comment]
> 初始化的时候应该配置一次就可以了，dist 直接把目录传上去应该就可以了。

抱歉，我还是没弄明白这句话的意思
国内的公共cdn提供商默认在链接中删除了dist这个路径
但是您在项目中把dist写死了，这样我们是没有办法使用国内的公共cdn提供商的
如果在原代码中删除会造成破坏，是否可以提供一个新的接口？
