### ISSUE TITLE
复制微信公众号的内容格式错乱，图片不能显示，其它的网站内容应该也会出现

### ISSUE THREAD

**Issue by fanpocha** [Vanessa219/vditor#1441]
### 你在什么场景下需要该功能？

复制微信公众号的内容格式错乱，图片不能显示，其它的网站内容应该也会出现

### 描述最优的解决方案 
期望与原文一致

**Comment by Vanessa219** [comment]
图片的话应该是公众号无法识别你复制的图片地址。

**Comment by fanpocha** [comment]
> 图片的话应该是公众号无法识别你复制的图片地址。

不打算修复么

**Comment by fanpocha** [comment]
在其它富文本测试能正常展示

**Comment by Vanessa219** [comment]
麻烦发一下 md 文件，我看一下具体时什么错乱才能进行修复
