### ISSUE TITLE
[suggestion] ctrl+shift+j toggle checked

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#145]
`ctrl+j`, `test`, `enter`,
`ctrl+j`,`test`, `ctrl+j`, `enter`, 
`test`, `ctrl+j`

`ctrl+j`: toggle
`ctrl+j`: unchecked and `ctrl+shift+j`: checked

![ctrlj](https://user-images.githubusercontent.com/15811943/74547847-60303880-4f12-11ea-8546-78d1fc1bcc15.gif)

**Comment by Vanessa219** [comment]
`ctrl + shift + j` and `ctrl + alt + j` conflict with chrome, so I use `ctrl + shift`

**Comment by jakekwak** [comment]
@Vanessa219 Could you tell me where is the code handling `ctrl+j`?
I can not find how to bind `ctrl+j` key to toolbar button at the source code.
When I commented the hotkey `ctrl+b` and `ctrl+j` at `util/options.ts`, `ctrl+b` is still working but `ctrl+j` is not.

**Comment by Vanessa219** [comment]
I can not reproduce, see https://github.com/Vanessa219/vditor/blob/master/src/ts/util/editorCommenEvent.ts#L142
