### ISSUE TITLE
多媒体没渲染

### ISSUE THREAD

**Issue by HumorSmith** [Vanessa219/vditor#1450]
### 编辑模式
* `wysiwyg` 所见即所得模式

### 描述问题

多媒体渲染不起作用

````````markdown
[mp4](https://minewallpaper.oss-cn-hangzhou.aliyuncs.com/timenote_others/md_tutorial.mp4)
````````

### 期待的结果

期待能有视频的预览界面

### 截屏或录像

<img width="1332" alt="image" src="https://github.com/Vanessa219/vditor/assets/3163232/698d3524-d57b-4bab-bc5d-ce134d80da93">

### 版本信息

* 版本：3.9.4
* 操作系统：macos
* 浏览器：chrome

**Comment by Vanessa219** [comment]
只有在预览的时候才可以
