### ISSUE TITLE
plantuml能直接以svg的格式内嵌吗？

### ISSUE THREAD

**Issue by holmofy** [Vanessa219/vditor#1452]
### 你在什么场景下需要该功能？

希望有大佬能把plantuml的svg格式直接内嵌到DOM树中，因为plantuml支持超链接，如果用img的src方式引用，超链接就失效了。

### 描述最优的解决方案 

提供一个plantuml配置项，把plantuml server返回的svg嵌入到DOM中。

**Comment by Vanessa219** [comment]
这个我没有找到对应的接口，可以做的话直接 PR 就行了。
