### ISSUE TITLE
表情在Chrome中显示是黑白的，在Firefox中正常，是什么原因呢

### ISSUE THREAD

**Issue by zgpnuaa** [Vanessa219/vditor#1454]
### 编辑模式
* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

表情在Chrome中显示是黑白的，在Firefox中正常。

在Chrome中：
![image](https://github.com/Vanessa219/vditor/assets/38033949/db290851-dc8f-410a-a8cc-0471e9c1c79b)
在Firefox中：
![image](https://github.com/Vanessa219/vditor/assets/38033949/c63588f9-e9c4-473a-89a5-4bea32a86be5)

### 期待的结果
希望在Chrome中也能正常显示彩色的表情

### 版本信息

* [版本：Demo最新版](https://ld246.com/guide/markdown)
* 操作系统：ubuntu 22.04
* 浏览器：Chrome 114.0.5735.198、Firefox 115.0.2

**Comment by 88250** [comment]
是字体的问题，添加一下字体支持应该能解决。
