### ISSUE TITLE
编辑链接 ｜CMD + Click or Ctrl + Click ｜立即渲染模式

### ISSUE THREAD

**Issue by ZehuaZhang** [Vanessa219/vditor#1455]
状况
目前 在立即渲染模式下 如果想重新编辑链接 比较困难 需要点击链接的边缘
点击链接 直接前往链接地址

需求
如果是在编辑模式下 点击链接 应该是重新编辑 而不是前往链接
预览模式下 点击链接 才是前往链接

方案
这个在很多支持markdown编辑软件都是这种行为 他们解决方案是在编辑模式下 点击链接 会出现一个tooltip在上方 (Cmd + Click in Mac, Ctrl + Click in Windows 前往链接地址)
然而他们没有instand rendering 我们可以点接链接 出现`[链接](url)`的同时 有个tooltip在上方 说如想前往链接地址 请重新按住Cmd 或者 Ctrl点击链接
或者点击链接出现两个选项 一个是编辑 一个是前往 我比较偏向前者 这样可以省去用户一些操作 用户体验更好

**Comment by Vanessa219** [comment]
可以使用 `options.link.isOpen` 进行配置

**Comment by ZehuaZhang** [comment]
那能给个keyboard event接口吗 因为是Cmd / Ctrl + Click
还有点击是我想有个tooltip 怎么使用？

**Comment by Vanessa219** [comment]
options.link.click

**Comment by ZehuaZhang** [comment]
vditor tooltip 怎么使用？
