### ISSUE TITLE
初始化vditor时，换行只剩单个换行

### ISSUE THREAD

**Issue by pygc** [Vanessa219/vditor#1456]
![image](https://github.com/Vanessa219/vditor/assets/4996887/9a49185a-c914-4361-979d-1b5c273bf1f9)

其中console.log("text", text);的输出结果为：
![image](https://github.com/Vanessa219/vditor/assets/4996887/dee98ba5-bbde-49ed-9d18-d1f647f11cbc)

而显示出来后，换行消失了：
![image](https://github.com/Vanessa219/vditor/assets/4996887/59221f27-4e13-4501-94ea-0987e96ada11)

第二张图是有多个换行的，但是vditor渲染后就没有换行了，编辑器的mode: "ir"，操作系统windows，vditor版本3.9.2

**Comment by Vanessa219** [comment]
这个是参照 CommonMark 的规范将多个换行合并

**Comment by pygc** [comment]
但是有一些不一致的情况：
写文件前，多行没有合并，而是可以预览
写文件时，保存的仍然时多个换行的
用户可能认为多行是生效了的

但是读取文件后，发现预览时只有一行换行了，用户原本需要通过换行分隔的东西就不容易区分了

**Comment by Vanessa219** [comment]
写文件是通过什么方法获取数据的？

**Comment by pygc** [comment]
我是用input的value来（自动）保存的，用input(value)

**Comment by Vanessa219** [comment]
由于是基于 CommonMark 规范来的，这个目前没有办法。

**Comment by mlsjla** [comment]
换行

换行


换行
