### ISSUE TITLE
使用自建cdn时，有一个css仍然是调用的远程cdn

### ISSUE THREAD

**Issue by ooahz** [Vanessa219/vditor#1458]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

配置了自建cdn后，其它的js和css都没问题，但是有一个css（/content-theme/light.css）仍然是调用的远程cdn

### 期待的结果
希望这个css也是使用自建cdn而不是远程cdn。
还有就是这些资源文件地址可以去掉dist这层路径吗，不然使用自建cdn时还要多套一层dist路径

### 截屏或录像

![image](https://github.com/Vanessa219/vditor/assets/57132258/9aa9f15c-5707-4e20-8527-0765f031601c)

![image](https://github.com/Vanessa219/vditor/assets/57132258/7f74c76c-d0e3-4b34-9d7d-34e6affb577b)
![image](https://github.com/Vanessa219/vditor/assets/57132258/a06fba01-1e3d-4ddd-9fbb-a840c17a0d77)
![image](https://github.com/Vanessa219/vditor/assets/57132258/073ecbff-a2a9-42fe-b08e-bebebf4bdaca)

### 版本信息

* 版本：3.9.4
* 操作系统：windows11
* 浏览器：Chrome/116.0.0.0

**Comment by Vanessa219** [comment]
这个需要设置 preview.theme.path
