### ISSUE TITLE
[suggestion] ctrl+k

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#146]
`ctrl+k`, `google`, `Tab`, `https://google.com`, `Tab`, `google`, `Tab`(end) or `ctrl+enter`(any field)
 
![links1](https://user-images.githubusercontent.com/15811943/74548614-cbc6d580-4f13-11ea-8a7b-70ba66099a28.gif)

### Editing
`click or moving cursor`: **auto highlight**, `Tab`, `Tab`, `Shift+Tab`, `Shift+Tab`, `Google`, `ctrl+enter`

![links2](https://user-images.githubusercontent.com/15811943/74548620-cff2f300-4f13-11ea-956f-5ce60171a4e1.gif)

**Comment by Vanessa219** [comment]
Automatic highlighting is unfriendly if the user just through Tag a without making changes

**Comment by jakekwak** [comment]
using too many arrow key when `link`.
I recommend below.

`ctrl+enter` at any field
![Screen Shot 2020-02-22 at 7 20 08 PM](https://user-images.githubusercontent.com/15811943/75101888-835d8680-55a9-11ea-9b24-7b2b95effb09.png)
![Screen Shot 2020-02-22 at 7 34 36 PM](https://user-images.githubusercontent.com/15811943/75102045-6c6b6400-55aa-11ea-8308-5263a4525786.png)


I think it have to be waiting next character
![Screen Shot 2020-02-22 at 7 26 37 PM](https://user-images.githubusercontent.com/15811943/75101900-a25c1880-55a9-11ea-83c1-6dbc6d074253.png)

after input `space key`
![Screen Shot 2020-02-22 at 7 31 01 PM](https://user-images.githubusercontent.com/15811943/75101984-fbc44780-55a9-11ea-84f8-2bac0ff035a5.png)

**Comment by Vanessa219** [comment]
`alt + enter` is available for every input and cursor on the link, please try again.

I do not understand:
> I think it have to be waiting next character
after input space key

**Comment by jakekwak** [comment]
`ctrl+k`, `Google`, `tab`, `https://www.google.com`, `tab`, `Google`, `alt+enter`, `space`, `is the best search engine.`.

current:
![google](https://user-images.githubusercontent.com/15811943/75103834-389e3780-55c6-11ea-8b49-38aa7c4b4757.gif)

suggestion:
![google1](https://user-images.githubusercontent.com/15811943/75103836-3f2caf00-55c6-11ea-8ffb-bbf93ff01a25.gif)

**Comment by Vanessa219** [comment]
you mean after `alt + enter` at input, do not select tag a?
