### ISSUE TITLE
换行+冒号会被识别为表格

### ISSUE THREAD

**Issue by sizexl** [Vanessa219/vditor#1460]
### 编辑模式
wysiwyg 和 ir 直接粘贴会出现该问题， sv 粘贴和编辑时都会出现该问题

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

内容 + 换行（单行）+ 冒号会被渲染成表格
wysiwyg 和 ir 模式直接编辑时按回车可能是插入了两个换行符，所以不会被识别成表格
````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
th
:
td
````````

### 期待的结果

正常渲染换行，不要识别成表格
### 截屏或录像
![image](https://github.com/Vanessa219/vditor/assets/14197558/d1e6dc55-ba0b-4aea-b0d7-0296b8b324ac)

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

**Comment by 88250** [comment]
感谢反馈，下个版本修复。
