### ISSUE TITLE
是否有支持离线使用的考虑

### ISSUE THREAD

**Issue by xunxun10** [Vanessa219/vditor#1465]
目前离线使用时，很多地方会报错，目前已知 Constants.CDN 等地方写死了需要获取远程资源，是否还有其他核心功能需要远程资源支持？可否考虑支持离线使用，以便在electron等桌面应用中使用？

### 你在什么场景下需要该功能？

electron等桌面应用中离线使用时。

### 描述最优的解决方案 

暂无

**Comment by Vanessa219** [comment]
将 CDN 换位本地的即可

**Comment by xunxun10** [comment]
是的，我前面也手动修改了index.min.js中的这个值，不过目前会出现告警： index.min.js:1 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-xxx='), or a nonce ('nonce-...') is required to enable inline execution.
目前看，只是无法显示toolbar的图标，其他功能看起来正常，还没定位到出现问题的具体代码

**Comment by Vanessa219** [comment]
可以下载代码后自己编译
