### ISSUE TITLE
请问如何设置默认预览模式且全屏展示？

### ISSUE THREAD

**Issue by larryhu** [Vanessa219/vditor#1468]
### 你在什么场景下需要该功能？

不需要编辑模式，只是渲染markdown文件，禁用编辑模式。

### 描述最优的解决方案 

无

### 描述候选解决方案

 无

**Comment by Vanessa219** [comment]
不编辑的话直接参考 https://github.com/Vanessa219/vditor/blob/master/demo/render.js
