### ISSUE TITLE
linkToImgUrl 能否支持上传前检验，或者忽略某些符合规则的图片上传

### ISSUE THREAD

**Issue by zonewancheng** [Vanessa219/vditor#1469]
### 你在什么场景下需要该功能？

已经上传的图片再次粘贴还会上传，想要忽略已经在某域名下的图片上传

### 描述最优的解决方案 

增加一个函数，比如：linkToImgUrlBeforeUpload,在执行上传图片地址前增加一个函数，方便用户进行拦截

**Comment by Vanessa219** [comment]
可以在服务端判断一下，如果存在的话就不处理
