### ISSUE TITLE
[suggestion] ctrl+l, ctrl+o, ctrl + j add insert line

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#147]
`ctrl+l`, `test`, `enter`,
`tab`, `test`, `enter`,
`tab`, `test`, `enter`,
`ctrl+enter`: after block
`ctrl+shift+enter`: before block

![ctrll1](https://user-images.githubusercontent.com/15811943/74550126-78a25200-4f16-11ea-9a32-5985c68ae9b1.gif)

**Comment by Vanessa219** [comment]
![image](https://user-images.githubusercontent.com/970828/75112933-e28fc980-5683-11ea-80e4-8ef6ee92352b.png)
