### ISSUE TITLE
url 有特殊字符时不能正常显示

### ISSUE THREAD

**Issue by Fierygit** [Vanessa219/vditor#1472]
`wysiwyg` 所见即所得模式
 `ir` 即时渲染模式
 `sv` 分屏编辑预览模式

无法识别为一个 url ，当名字中有特殊字符时
[518. 零钱兑换 II.cc](518. 零钱兑换 II.cc) 无法展示为 url
<img width="330" alt="image" src="https://github.com/Vanessa219/vditor/assets/36060301/132bad78-c433-4ac1-b431-4b790ea0e1b2">

**Comment by Vanessa219** [comment]
这个不是标准，在 GitHub 中也无法显示为链接
[518. 零钱兑换 II.cc](518. 零钱兑换 II.cc)
