### ISSUE TITLE
希望能够扩展issues/1464的功能，自定义插入位置

### ISSUE THREAD

**Issue by ooahz** [Vanessa219/vditor#1473]
### 你在什么场景下需要该功能？

希望可以扩展https://github.com/Vanessa219/vditor/issues/1464 
中提到的功能，自定义光标位置。就像官方工具栏中，插入链接时，光标会自动定位到中括号之间一样。
不知道编辑器有没有移动光标位置的方法，我在目前的文档中只找到获取焦点（光标）位置的方法，却并未找到修改光标位置的方法

**Comment by Vanessa219** [comment]
这个就不提供了，可以自己使用 range 进行移动
