### ISSUE TITLE
希望把渲染器导出来

### ISSUE THREAD

**Issue by xiongyechang** [Vanessa219/vditor#1477]
### 你在什么场景下需要该功能？

我有一个编辑器的需求，编辑后数据保存到服务端，然后在另外一个页面里面看编辑的内容【这个页面没有编辑权限，只能看】，由于另外这个页面的markdown渲染器功能没有这么强大，所以很多数据渲染不出来，希望能把这个产品的渲染器抽出来

### 描述最优的解决方案 

导出渲染器

### 描述候选解决方案

导出渲染器，或者把渲染器代码移植到新包里面

### 其他信息
无

**Comment by Vanessa219** [comment]
后端渲染可走 https://github.com/88250/lute
