### ISSUE TITLE
gfmAutoLink识别带有端口号的url时识别不全

### ISSUE THREAD

**Issue by sizexl** [Vanessa219/vditor#1478]
### 编辑模式

* `sv` 分屏编辑预览模式

### 描述问题

原文中的链接地址如果附带端口号，则使用`preview`或者`md2html`方法渲染出的a标签只截止到端口号的部分，分屏预览模式也有体现

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
````````
点击如下链接直接进入查询：http://abc.com:8000/abc?a=bc
点击如下链接直接进入查询：http://abc.com:8000
点击如下链接直接进入查询：http://abc.com/abc?a=bc
### 期待的结果
渲染完整的链接地址

### 截屏或录像
![image](https://github.com/Vanessa219/vditor/assets/14197558/2d1b3698-2a31-4cac-bfbd-9ca66684df5e)

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/1513
