### ISSUE TITLE
即时渲染模式下无法对表格进行增加行和列的操作

### ISSUE THREAD

**Issue by xunxun10** [Vanessa219/vditor#1479]
### 编辑模式

* `ir` 即时渲染模式

### 描述问题

即时渲染模式下无法对表格进行增加行和列的操作

### 期待的结果

可以有增加行或列的tips提示或者快捷键提示

### 截屏或录像

无

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

**Comment by Vanessa219** [comment]
只能使用快捷键
