### ISSUE TITLE
视频上传 相关问题

### ISSUE THREAD

**Issue by ZehuaZhang** [Vanessa219/vditor#1481]
* `wysiwyg` 所见即所得模式
音频 有 <audio
图片 是 <img
视频就是链接
* `ir` 即时渲染模式
都是`![]()`

请问视频上传后会自动 渲染视频播放的html element 吗 code能指下吗 是用什么element渲染的 支持什么视频文件格式 mp4 还是其他

**Comment by Vanessa219** [comment]
<img width="966" alt="image" src="https://github.com/Vanessa219/vditor/assets/970828/276da600-907c-46c9-8396-e3cb6770b7b9">
