### ISSUE TITLE
从docx文档中直接复制内容，图片无法上传成功，显示图片链接为file协议!

### ISSUE THREAD

**Issue by hijjl** [Vanessa219/vditor#1484]
### 编辑模式

正常编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 从docx文档中直接复制内容，图片无法上传成功，显示图片链接为file协议!从PPT文件上面复制图片可以上传成功！

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
````````

### 截屏或录像

![image](https://github.com/Vanessa219/vditor/assets/22066916/ebc21136-3399-4e07-9682-9bd910016586)

### 版本信息

* 版本：vditor@3.9.6
* 操作系统：Windows 11 家庭中文版
* 浏览器：Google Chrome 版本 117.0.5938.150（正式版本） （64 位）

**Comment by 88250** [comment]
你好，浏览器不允许读取本地路径文件，请尝试使用思源桌面端，或者使用 网络图片转换为本地图片 功能。

![image](https://github.com/Vanessa219/vditor/assets/873584/7ee2a650-dd2b-4c18-b66c-8b92ecf9d9a2)

**Comment by HCenggel** [comment]
这个好像就是浏览器的事情了，我们也遇到了同样的问题
