### ISSUE TITLE
从 IDE 粘贴代码到编辑器中，会自动套一层代码块

### ISSUE THREAD

**Issue by gkn1234** [Vanessa219/vditor#1485]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

我们有用户在 IDE 中编写好了 markdown，但是粘贴到 Vditor 中后，内容会被自动套上一层代码块。

![image](https://github.com/Vanessa219/vditor/assets/31581858/079c40be-e9a5-4e0f-8146-3d6453210f29)

sv 模式下的 md 文本：
````````markdown
```
# OpenX 前端

内源平台前端的代码仓
```
````````

### 期待的结果

从 IDE 中复制出来的内容，复制进编辑器中呈现出纯文本的形式，而非套一层代码块。

之前的用例对应 sv 模式下的 md 文本：
````````markdown
# OpenX 前端

内源平台前端的代码仓
````````

### 版本信息

* 版本：3.9.4
* 操作系统：win10
* 浏览器：Chrome

**Comment by Vanessa219** [comment]
ctrl+shift+V

**Comment by jyginger** [comment]
我也有同样的问题，而且新增加的代码块很难删除。这应该是自动替换的什么机制，不知道有没有什么配置开关。您有解决吗/

**Comment by Vanessa219** [comment]
怎么难删除？

**Comment by Vanessa219** [comment]
删除的时候是这样操作的么？

https://github.com/user-attachments/assets/4a05c6b5-2949-46fc-8d94-4d6db926a108
