### ISSUE TITLE
是否考虑增加将上传的图片自动转为base64编码的设置？

### ISSUE THREAD

**Issue by lesliexufdu** [Vanessa219/vditor#1487]
### 你在什么场景下需要该功能？
很多文档需要上传图片，现在一般使用图床之类的工具，一来使用麻烦，二来需要额外维护图片库，还有失效的风险。
如果将图片内嵌进MD文件，就可以解决这个问题，代价是文件大小会稍微增大。

### 描述最优的解决方案 
我的做法通常是转换成base64的编码：
```HTML
<img src="data:image/png;base64,···">
```
仅作参考。

### 其他信息
我觉得可以增加一个设置，可以自动将图片转化成编码格式，也可以仍使用URL的形式。

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/pull/1231
