### ISSUE TITLE
We don't execute document.execCommand() this time, because it is called recursively.

### ISSUE THREAD

**Issue by seepine** [Vanessa219/vditor#1489]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

ctrl+x 快捷键剪切后，无法生效所选文本没有被删除，但此时ctrl+v能够粘贴出来
此时控制台出现警告
`We don't execute document.execCommand() this time, because it is called recursively.`

### 期待的结果

正常ctrl+x效果

### 截屏或录像
![image](https://github.com/Vanessa219/vditor/assets/93666053/a97f4c3b-5610-421f-9a63-2a5a4bbb0221)
![image](https://github.com/Vanessa219/vditor/assets/93666053/485ecd2a-6887-4e0e-897b-196e1fbb35e8)

### 版本信息

* 版本：3.9.6
* 操作系统：windows
* 浏览器：vscode内置webview

**Comment by Vanessa219** [comment]
浏览器中无法重现，可能需要你自己跟进一下了
