### ISSUE TITLE
[suggestion] UI Consistency

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#149]
# Keyboard only. (no mouse, less arrow key)

|  |  Windows |  New Keyboard Shortcut |
|---|------------|---------------------------|
| Headings |  `ctrl+h` |  see below |
| Bold |  `ctrl+b` |  `ctrl+b` |
| Italic |  `ctrl+i` |  `ctrl+i` |
| strikeout |  `ctrl+s` |  `ctrl+s` |
| links |  `ctrl+k` |  see below |
| unordered list |  `ctrl+l` |  see below |
| ordered list |  `ctrl+o` |  see below |
| checkbox |  `ctrl+j` |  see below |
| Blockquote |  `ctrl+.` |  see below |
| Horizontal |  `ctrl+shift+d` |   |
| Codeblock |  `ctrl+u` |  see below |
| Table |  `ctrl+m` |  see below |
| Inline Code |  `ctrl+g` |  see below |
| Toggle WYSIWYG |  `ctrl+shift+m` |   |
|  |  `ctrl+p` |   |
|  |  `ctrl+shift+p` |   |
|  |  `ctrl+shift+f` |   |
|  |  `ctrl+'` |   |
|  |   |   |
| **Headings** |   |   |
| Bigger |  `ctrl+=` |  `ctrl+alt+1`, 2, 3, 4, 5, 6(`⌘+Option+1`) |
| Smaller |  `ctrl+-` |   |
| Mistyped |   | `backspace` |
|  |   |   |
| **Links `ctrl+k`** |   |   |
| remove block |   |  ctrl+backspace |
| move in |  mouse click |  automatic first, selected all |
| move to next field |  tab |  tab |
| previous field |  shift+tab |  shift+tab |
| move out(end) |  mouse click |  ctrl+enter |
| Mistyped |   | `Escape`  |
|  |   |   |
| **List `ctrl+l` `ctrl+o`** |   |   |
| indent |  tab, ctrl+shift+e |  tab |
| outdent |  shift+tab, ctrl+shift+s |  shift+tab, enter(no text) |
| end |  enter at first level with no text |   |
| end of lists |  several enter with no text |  ctrl+enter |
| input before block |   | ctrl+shift+enter  |
| Mistyped | `backspace`  | `backspace` |
|  |   |   |
| **checkbox `ctrl+j`** |   |   |
|  |   |  ctrl+backspace |
| end of checkbox |  enter with no text |  ctrl+enter |
|  |   |  ctrl+shift+enter |
| indent |  ctrl+shift+e |  tab |
| outdent |  ctrl+shift+s |  shift+tab |
| unchecked box |   |  ctrl+shift+j (toggle??) |
| checked box |   |   |
| Mistyped | `backspace`  | `backspace` |
|  |   |   |
| **Blockquote `ctrl+.`** |   |   |
| remove block |  ctrl+shift+x |  ctrl+backspace |
| input before block |   |  ctrl+shift+enter |
| input after block | alter+enter  |  ctrl+enter |
| input after(prev leve) |  ctrl+shift+e |   |
| input before current |  ctrl+shift+s |   |
| input after |  enter |  enter |
| change next level |  > |  ctrl+. |
| change prev level |  ctrl+. |  ctrl+shift+. |
| Mistyped | `backspace`  | `backspace` |
|  |   |   |
| **Codeblock `ctrl+u`** |   |   |
| Quit editing, show only rendering | Escape |  |
| select all of the current code block | ctrl+a |  |
| remove block |  ctrl+shift+x |  ctrl+backspace |
| input before block |  ctrl+shift+s, up-arrow(first line) |  ctrl+shift+enter |
| input after block |  ctrl+shift+e, down arrow(last line) |  ctrl+enter |
| moving to language field |  alt+enter |  shift+tab |
| from language field |  alt+enter |  tab |
| Mistyped | `ctrl+shift+x` | `Escape` |
|  |   |   |
| **Table `ctrl+m`** |   |   |
| remove block |  ctrl+shift+x |  ctrl+backspace |
| input before block |  ctrl+shift+s, up-arrow(first line) |  ctrl+shift+enter |
| input after block |  ctrl+shift+e, down arrow(last line) |  ctrl+enter |
| add next row  | alt+enter  | ctrl++  |
| delete current row  | alt+backspace  | ctrl+-   |
| add next column  | alt+shift+enter  |  ctrl+shift++ |
| delete current column  | alt+shift+backspace  |  ctrl+shift+- |
| Left Alignment  |   | ctrl+alt+l (⌘+l)  |
| Center Alignment  |   |  ctrl+alt+e(⌘+e) |
| Right Alignment  |   |  ctrl+alt+r(⌘+r) |
| moving to prev cell |  shift-tab |  shift+tab |
| moving to next cell |  tab |  tab(input after block at end cell) |
| Mistyped | `ctrl+shift+x`  | `Escape` |
|  |   |   |
| **Inline code `ctrl+g`** |   |   |
| end of inline code |  right arrow |  ctrl+g same as bold, italic, strikeout |

**Comment by Vanessa219** [comment]
ctrl+backspace is confilct with markdown mode,
pls check `=>`, `?`, `TODO` position

**Comment by Vanessa219** [comment]
ctrl+backspace is conflict with markdown mode
ctrl+enter is conflict with options.ctrlEnter
I change something, see below

## 键盘快捷键

| 名称                               | 快捷键                                    | 备注                                                                            |
| ------------------------------------ | -------------------------------------------- | --------------------------------------------------------------------------------- |
| Headings                             | `ctrl+h`                                     | see below                                                                         |
| Bold                                 | `ctrl+b`                                     |                                                                                   |
| Italic                               | `ctrl+i`                                     |                                                                                   |
| strikeout                            | `ctrl+s`                                     |                                                                                   |
| links                                | `ctrl+k`                                     | see below                                                                         |
| unordered list                       | `ctrl+l`                                     | see below                                                                         |
| ordered list                         | `ctrl+o`                                     | see below                                                                         |
| checkbox                             | `ctrl+j`                                     | see below                                                                         |
| Blockquote                           | `ctrl+;`                                     | see below                                                                         |
| Horizontal                           | `ctrl+shift+d`                               |                                                                                   |
| Codeblock                            | `ctrl+u`                                     | see below                                                                         |
| Table                                | `ctrl+m`                                     | see below                                                                         |
| Inline Code                          | `ctrl+g`                                     |                                                                                   |
| Toggle WYSIWYG                       | `ctrl+shift+m`                               |                                                                                   |
| Fullscreen                           | `ctrl+'`                                     |                                                                                   |
| Mistyped                             | `backspace`                                  |                                                                                   |
|                                      |                                              | `ctrl+p` ?                                                                        |
|                                      |                                              | `ctrl+shift+p` ?                                                                  |
|                                      |                                              | `ctrl+shift+f` ?                                                                  |
|                                      |                                              |                                                                                   |
| **Headings `ctrl+h`**                |                                              |                                                                                   |
| Bigger                               | `ctrl+=`                                     |                                                                                   |
| Smaller                              | `ctrl+-`                                     |                                                                                   |
| H1-H6                                | `ctrl+alt+1/2/3/4/5/6`                       |                                                                                   |
| heading menu                         | `ctrl+h`                                     |                                                                                   |
|                                      |                                              |                                                                                   |
| **Links `ctrl+k`**                   |                                              |                                                                                   |
| remove block                         | `ctrl+shift+x` [TODO]                        |                                                                                   |
| move to field                        | `alt+ enter`                                 |                                                                                   |
| move to next field                   | `tab`                                        |                                                                                   |
| move to previous field               | `tab`                                        |                                                                                   |
| move to link                         | `alt+ enter`                                 |                                                                                   |
|                                      |                                              |                                                                                   |
| **List `ctrl+l` `ctrl+o`**           |                                              |                                                                                   |
| remove block                         | `ctrl+shift+x` [TODO]                        |                                                                                   |
| before block                         | `ctrl+shift+s`                               |                                                                                   |
| after block                          | `ctrl+shift+e`                               |                                                                                   |
| after of current list                | `enter`                                      | `enter`: no text                                                                  |
| indent                               | `tab`<br />`ctrl+shift+i`                    | `tab`: cursor must be in the first char                                           |
| outdent                              | `shift+tab`<br />`ctrl+shift+o`<br />`enter` | `shift+tab`: cursor must be in the first char<br />`enter`: no text               |
|                                      |                                              |                                                                                   |
| **checkbox `ctrl+j`**                |                                              |                                                                                   |
| remove block                         | `ctrl+shift+x` [TODO]                        |                                                                                   |
| before block                         | `ctrl+shift+s`                               |                                                                                   |
| after block                          | `ctrl+shift+e`                               |                                                                                   |
| indent                               | see List                                     |                                                                                   |
| outdent                              | see List                                     |                                                                                   |
| toggle check                         | `ctrl+shift+J`                               |                                                                                   |
|                                      |                                              |                                                                                   |
| **Blockquote `ctrl+;`**              |                                              |                                                                                   |
| remove block                         | `ctrl+shift+x`                               |                                                                                   |
| before block                         | `ctrl+shift+s`                               |                                                                                   |
| after block                          | `ctrl+shift+e`                               |                                                                                   |
| before top block                     | `alt+shift+enter` [TODO]                     |                                                                                   |
| after top block                      | `alt+enter`                                  |                                                                                   |
| after parent                         | `double enter`                               |                                                                                   |
| insert blockquote                    | `ctrl+shift+:`<br />`>`                      | `ctrl+shift+:`: current element must be a block element<br />`>`: Markdown marker |
| toggle blockquote                    | `ctrl+;`                                     |                                                                                   |
|                                      |                                              |                                                                                   |
| **Codeblock `ctrl+u`**               |                                              |                                                                                   |
| remove block                         | `ctrl+shift+x`                               |                                                                                   |
| before block                         | `ctrl+shift+s`                               |                                                                                   |
| after block                          | `ctrl+shift+e`                               |                                                                                   |
| move to language field               | `alt+enter`                                  |                                                                                   |
| move to code field                   | `alt+enter`                                  |                                                                                   |
| Quit editing, show only rendering    | `Escape`                                     |                                                                                   |
| select all of the current code block | `ctrl+a`                                     |                                                                                   |
|                                      |                                              |                                                                                   |
| **Table `ctrl+m`**                   |                                              |                                                                                   |
| remove block                         | `ctrl+shift+x`                               |                                                                                   |
| before block                         | `ctrl+shift+s`                               |                                                                                   |
| after block                          | `ctrl+shift+e`                               |                                                                                   |
| add next row                         | `ctrl++` [TODO]                              |                                                                                   |
| delete current row                   | `ctrl+-` [TODO]                              |                                                                                   |
| add next column                      | `ctrl+shift++` [TODO]                        |                                                                                   |
| delete current column                | `ctrl+shift+-` [TODO]                        |                                                                                   |
| Left Alignment                       | `ctrl+alt+l` [TODO]                          |                                                                                   |
| Center Alignment                     | `ctrl+alt+e` [TODO]                          |                                                                                   |
| Right Alignment                      | `ctrl+alt+r` [TODO]                          |                                                                                   |
| move to row filed                    | `alt+enter` [TODO]                           |                                                                                   |
| toggle row and column filed          | `tab` [TODO]                                 |                                                                                   |
| moving to previous cell                  | `shift+tab`<br />`delete`                    |                                                                                   |
| moving to next cell                  | `tab`                                        |                                                                                   |

**Comment by jakekwak** [comment]
Could you add one more shortcut for uploading picture(file)?
I think we need this shortcut key when the mouse is broken.

**Comment by Vanessa219** [comment]
`ctrl+shift+u`

**Comment by Vanessa219** [comment]
`ctrl+shift+u`

**Comment by Vanessa219** [comment]
`ctrl+shift+u`
