### ISSUE TITLE
vue3+vditor不显示toolbar图标

### ISSUE THREAD

**Issue by JunwayGuo** [Vanessa219/vditor#1490]
环境：vue3+vuetify3+vite

vditor样式都有加载，其他功能都没问题
toolbar可以操作，就是不显示图标，看了与svg相关的样式，也没有找到哪里有污染。

求大神指点。

![image](https://github.com/Vanessa219/vditor/assets/31336068/6e136a26-ab2d-4ff4-bfeb-65beb81200ab)

![image](https://github.com/Vanessa219/vditor/assets/31336068/49d1f560-f50b-4208-b21e-3c71c57270a7)

**Comment by Vanessa219** [comment]
看一下是不是 图标 的 js 没有加载

**Comment by JunwayGuo** [comment]
的确是因为js没有加载，手动引入就可以了。
`import 'vditor/dist/js/icons/ant.js'`
但，请问是何原因，让js没有自动加载？

**Comment by Vanessa219** [comment]
具体不太清楚，相关代码为 
<img width="1135" alt="image" src="https://github.com/Vanessa219/vditor/assets/970828/d514a045-c7c0-4368-a36d-947957cd82a1">
