### ISSUE TITLE
为什么进入预览后的菜单栏会往左侧偏移？

### ISSUE THREAD

**Issue by joshua7v** [Vanessa219/vditor#1493]
### 描述问题

为什么进入预览后的菜单栏会往左侧偏移

观察菜单栏有一个 padding-left，进入预览后就没有了
这是出于什么设计考量呢？有没有什么方式设定为菜单栏位置不要这样变动呢？

### 期待的结果

菜单栏维持

### 截屏或录像

<img width="1244" alt="image" src="https://github.com/Vanessa219/vditor/assets/4159858/333c81db-826c-434d-b234-2d59b2f5ec20">

**Comment by Vanessa219** [comment]
预览界面还有一种情况，外加其不需要编辑，点击 Mobile/Wechat 后无法对齐。因此统一左对齐。
<img width="1509" alt="image" src="https://github.com/Vanessa219/vditor/assets/970828/eac784b0-69df-4966-86e1-4b73ffee8ee1">
