### ISSUE TITLE
ir模式获取选中的markdown原文

### ISSUE THREAD

**Issue by FantasticPornTaiQiang** [Vanessa219/vditor#1495]
**问题描述**

ir模式下：

根据[文档](https://ld246.com/article/1549638745630#methods)，选中一段selection，vditor实例有insert/update/deleteValue等方法可以操作选区文本，**唯独没有根据选区获取markdown原文的方法**。

只有getValue方法获取整个文档的markdown原文，或者getSelection方法获取选区的innerText（非markdown原文）。

**自答**

想了一下，vditor在复制粘贴时，可以粘贴出与原文一模一样的内容，因而按理说markdown原文应该是存在的、可以被获取到的。因此，利用模拟复制操作，执行document.exec('copy')复制，然后用clipboard.readText()就可以读到markdown原文了。但感觉这算是一种投机的方式。

**提问**

不知道有没有其他直接能够获取选区markdown原文的正常方法？

**Comment by Vanessa219** [comment]
试一下获取后使用 html2md
