### ISSUE TITLE
在JS文件中import后控制台提示Vditor未定义

### ISSUE THREAD

**Issue by xmings** [Vanessa219/vditor#1501]
### 编辑模式

version : Vditor 3.9.5/3.9.4

### 描述问题

某个js文件内容：
```javascript
import "../common/js/jquery-3.6.0.min.js"
import "../common/js/vditor-index.min.js"

document.addEventListener('DOMContentLoaded', function () {

    console.log($("#editor"));
    console.log(new Vditor("editor"))
})
```

控制台显示：

![image](https://github.com/Vanessa219/vditor/assets/8492022/05be77c4-d802-4c1f-912b-7d3c70cc1577)

**Comment by Vanessa219** [comment]
可参考 https://github.com/Vanessa219/vditor/blob/ae93e5ad56c6762254be9b4babda18cde1e38998/demo/index.js
<img width="859" alt="image" src="https://github.com/Vanessa219/vditor/assets/970828/2451028a-7069-4c8b-8109-fb85acea16c2">
