### ISSUE TITLE
Cant copy text on Preview

### ISSUE THREAD

**Issue by ronen1n** [Vanessa219/vditor#1504]
Hello

I tried to copy from the "Preview" and its saying "已复制，可到微信公众号平台进行粘贴" but its not copying anything

**Comment by Vanessa219** [comment]
选中需要的内容进行复制（ctrl+c）会弹出其他提示。不要点击图标。

<img width="996" alt="image" src="https://github.com/Vanessa219/vditor/assets/970828/07beaeea-889f-416c-b91f-ab312e94dbbe">

**Comment by ronen1n** [comment]
here i tried 'copy' and ctrl+c and ctrl+v and it didnt work

![Animation](https://github.com/Vanessa219/vditor/assets/20344644/9a6cfdab-18a5-49bc-9447-387067679cb9)

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/assets/970828/03de9021-bb44-4aac-9d87-2f5b4d55521e

**Comment by ronen1n** [comment]
Sorry my bad it's working
Thanks for the help
