### ISSUE TITLE
getHTML()方法h1标签的锚点似乎没有被渲染

### ISSUE THREAD

**Issue by justice2001** [Vanessa219/vditor#1505]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

在使用getHTML()方法中获得到的HTML代码中，标题的锚点id似乎没有正常渲染出来，但是使用preview方法却可以正常渲染。

`# title` 使用getHTML方法渲染的结果是 `<h1>title</h1>`

### 期待的结果

正确的渲染结果我认为应当带有锚点信息: `<h1 id="title">title</h1>`

### 截屏或录像

<img width="166" alt="截屏2023-11-25 15 24 09" src="https://github.com/Vanessa219/vditor/assets/28425753/3910c55e-78a9-46de-97dd-d163632f9470">

### 版本信息

* 版本：Vditor 3.9.6
* 操作系统：macOS 14.1.1 
* 浏览器：Chrome 119.0.6045.159

**Comment by Vanessa219** [comment]
参照下图使用是可以的。

<img width="1100" alt="image" src="https://github.com/Vanessa219/vditor/assets/970828/8f70223c-7d77-4a93-a796-0c613504eb04">

**Comment by justice2001** [comment]
感谢您的回复，刚刚又读了一遍文档，发现有一个`options.preview.markdown.toc`的属性，昨天没有理解这个属性的含义，就没有测试，将这个属性设置成true就可以正常工作渲染标题了.
