### ISSUE TITLE
需求想禁止vditor 把CRLF转化为LF 想问一下 有没有暴露`EnsureLF`配置

### ISSUE THREAD

**Issue by 0214ggyy** [Vanessa219/vditor#1506]
需求想禁止vditor 把CRLF转化为LF 想问一下 有没有暴露`EnsureLF`配置

**Comment by 88250** [comment]
你好，没有接口，因为解析器在处理时会移除 `\r`。

**Comment by 0214ggyy** [comment]
在欢乐时，朋友们会认识我们；在患难时，我们会认识朋友。谢谢，来信！！！
