### ISSUE TITLE
pnpm add vditor 方式安装 不能正常引入控件 

### ISSUE THREAD

**Issue by 88act** [Vanessa219/vditor#1507]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

 pnpm add vditor 方式安装 不能正常引入控件 
使用 这个  https://github.com/pure-admin/vue-pure-admin  
安装  pnpm add vditor 
在vue 页面引入 
  import Vditor from 'vditor'
  const myVditor = ref(null);
  
运行报错 。

使用 npm install  vditor  这样的方式 在其他vue项目， 能正常使用 
 

### 版本信息

* 版本：最新版
* 操作系统： win10 
* 浏览器：chrome

**Comment by Vanessa219** [comment]
是不是 https://github.com/pure-admin/vue-pure-admin 的问题？
