### ISSUE TITLE
我在尝试自定义toolbar的图标，发现全屏涉及到两个icon（放大和缩小），请问怎么配置实现

### ISSUE THREAD

**Issue by subtlecooooder** [Vanessa219/vditor#1509]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题
我在尝试自定义toolbar的图标，发现全屏涉及到两个icon（放大和缩小），请问怎么配置实现？以下是目前的配置，通过该配置已经可以替换放大icon，但是全屏后显示的缩小icon依然是默认的
````````
{
    name: 'fullscreen',
    svg: '<svg></svg>'
}
````````

### 期待的结果

可以通过配置替换全屏的放大缩小两个icon

### 截屏或录像
<img width="519" alt="image" src="https://github.com/Vanessa219/vditor/assets/16059238/fcdbd863-4bfe-497a-8824-1a98059b92fb">
<img width="1440" alt="image" src="https://github.com/Vanessa219/vditor/assets/16059238/f78d8cc4-917a-4589-95e1-cf5823a26d10">

**Comment by Vanessa219** [comment]
看了一下，设置 icon 后添加对应的 图标 js 文件到相应的目录下应该可以。
<img width="946" alt="image" src="https://github.com/Vanessa219/vditor/assets/970828/e67c6081-158e-4740-b594-04fc1f58e408">
