### ISSUE TITLE
支持隐藏编辑器工具栏

### ISSUE THREAD

**Issue by 88250** [Vanessa219/vditor#151]
对于 Markdown 资深用户来说，编辑器工具栏并不是必须的。

![image](https://user-images.githubusercontent.com/873584/74500768-ece2f280-4f22-11ea-9e81-068273cb43c1.png)

增加个配置项，可设置为隐藏。

**Comment by jakekwak** [comment]
but, I think we need the floating menu at smartphone something like Redactor.
Try this <https://imperavi.com/redactor/> at smartphone.
