### ISSUE TITLE
上传图片或文件，已经产生上传成功回调了，但编辑器还是提示"上传中..."，要等好一会儿才消失。

### ISSUE THREAD

**Issue by zgpnuaa** [Vanessa219/vditor#1510]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

上传图片或文件，已经产生上传成功的回调了，但编辑器还是提示"上传中..."，要等好一会儿才消失。

### 期待的结果

希望上传完成，产生回调后"上传中.."的提示立马消失。
### 截屏或录像
![image](https://github.com/Vanessa219/vditor/assets/38033949/d0e77daa-665e-4373-b135-20b0a64f5320)

### 版本信息

* 版本：v3.9.6
* 操作系统：Ubuntu22.04
* 浏览器：Chrome

**Comment by Vanessa219** [comment]
上传成功后会在下列代码内进行关闭，是否传入了 options.upload.success 了？
<img width="947" alt="image" src="https://github.com/Vanessa219/vditor/assets/970828/2fba602f-73f9-4205-a3c0-17921778b210">

**Comment by zgpnuaa** [comment]
> 上传成功后会在下列代码内进行关闭，是否传入了 options.upload.success 了？ <img alt="image" width="947" src="https://private-user-images.githubusercontent.com/970828/290076526-2fba602f-73f9-4205-a3c0-17921778b210.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjU5OTAsIm5iZiI6MTcwMjUyNTY5MCwicGF0aCI6Ii85NzA4MjgvMjkwMDc2NTI2LTJmYmE2MDJmLTczZjktNDIwNS1hM2MwLTE3OTIxNzc4YjIxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQwMzQ4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzFkMjFiOGZlNGJhZjc4NzEyZmQ1ZWEyYzQxMTYxYjRkNmE4OGEwYTVhNzU1Y2Y2YmEzMWMyMjhlMzEwNzA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ros_rnRzKBrr7ZCbqD3WMItiI9SrEv5p4FH18TPwbIc">
我按下面这么写，显示genUploadedLabel is not defined
![image](https://github.com/Vanessa219/vditor/assets/38033949/15d7926e-6a46-4539-b038-3055d07df50d)

**Comment by Vanessa219** [comment]
这个需要自己关闭一下，`vditor.vditor.tip.hide()`

**Comment by zgpnuaa** [comment]
> 这个需要自己关闭一下，`vditor.vditor.tip.hide()`

`vditor.vditor.tip.hide()`这个可以了，谢谢~
