### ISSUE TITLE
npm run build

### ISSUE THREAD

**Issue by 812781385** [Vanessa219/vditor#1512]
After I installed the dependency, an ts error occurred when I executed npm run build, and packaging failed

[tsl] ERROR in /Users/wangrui/myProject/cdt-edit/vditor/src/ts/undo/index.ts(20,33)
      TS2694: Namespace 'diff_match_patch' has no exported member 'diff_match_patch'.
 @ ./src/index.ts 40:0-39 432:31-35

**Comment by Vanessa219** [comment]
Pls run this `npm i` and try again.
