### ISSUE TITLE
自建cdn报错

### ISSUE THREAD

**Issue by 160405103** [Vanessa219/vditor#1517]
### 编辑模式

* `ir` 即时渲染模式

### 描述问题

在react中使用vditor，代码是官方示例加上自建cdn和其他一些配置, 只成功加载了zh_cn.js，剩余的js和css没加载到
![image](https://github.com/Vanessa219/vditor/assets/51314891/89d735b7-2636-4ee1-bc1b-f195d37d3ed1)

控制台报错
![image](https://github.com/Vanessa219/vditor/assets/51314891/ee36bc31-8e4f-4218-ba82-616c1180b0de)

### 期待的结果

自建cdn能正常加载资源

### 版本信息

* 版本：3.9.6
* 操作系统：windows
* 浏览器：chrome

**Comment by 160405103** [comment]
![1702558791937](https://github.com/Vanessa219/vditor/assets/51314891/15af197e-f0f0-491f-b78b-964e4a099ea4)

这个也是一样的错误

**Comment by Vanessa219** [comment]
可先参见 https://github.com/Vanessa219/vditor/issues/1522 进行配置

**Comment by 160405103** [comment]
好的，十分感谢
