### ISSUE TITLE
sv 模式中在脚注下方输入文本出现渲染错误

### ISSUE THREAD

**Issue by justice2001** [Vanessa219/vditor#1518]
### 编辑模式

* `sv` 分屏编辑预览模式

### 描述问题

偶然发现的bug，`sv`模式中，在脚注下方输入任何文本会出现全篇复制的问题。

暂时测试出来的触发条件： 页面中存在两条脚注

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
````````

### 期待的结果

正常输入

### 截屏或录像

中间两次卡顿是输入了回车，其实输入任何字符都会把全文复制

![bug](https://github.com/Vanessa219/vditor/assets/28425753/e114f477-85bd-4725-892d-1e3937d3543b)

### 版本信息

* 版本：v3.9.7
* 操作系统：macOS 14.1.2
* 浏览器：Chrome 120.0.6099.71

**Comment by justice2001** [comment]
这个bug是从`v3.8.16`开始出现的，对比了下debugger输出的SpinVditorSVDOM的结构，好像是lute某些问题引起的。

3.8.16以前的lute渲染出来的结构是每一个脚注都用`div`包了起来，而`3.8.16`开始lute渲染出来的就是把所有脚注包在的一个`div`里。

<img width="544" alt="截屏2023-12-14 23 17 10" src="https://github.com/Vanessa219/vditor/assets/28425753/7b13451c-67fa-460c-bc15-d51cbe0ff07d">

在`sv/inputEvent.ts L183-L197`中处理还是原来的方式，不知道这个是属于vditor的bug还是lute的bug。

**Comment by Vanessa219** [comment]
贴入以下内容后输入会导致其他问题，还麻烦在修复一下，十分感谢。

https://github.com/Vanessa219/vditor/assets/970828/15b9c08d-0e77-4ca7-a36c-a0776df414a6



```
这里是一个脚注引用[^1]，这里是另一个脚注引用[^bignote]。
[^1]: 第一个脚注定义。
[^bignote]: 脚注定义可使用多段内容。

    缩进对齐的段落包含在这个脚注定义内。

    ```
    可以使用代码块。
    ```

    还有其他行级排版语法，比如**加粗**和[链接](https://b3log.org)。
```

**Comment by justice2001** [comment]
这个我在尝试修复，不过现在还在考虑怎么分辨是否为脚注部分，我应该需要先把#1270修复才能处理这个问题
