### ISSUE TITLE
some preview theme?

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#152]
any preview theme options like <http://mixu.net/markdown-styles/> and <https://markdowncss.github.io/>

**Comment by 88250** [comment]
Do you mean the theme in render result? For example, the 'Heading' and 'item' font style has multiple built-in themes?

![image](https://user-images.githubusercontent.com/873584/76156500-457a6980-6136-11ea-866b-94ce9975f4fc.png)

**Comment by jakekwak** [comment]
I mean I want to add some custom css file to decorate my blog.

**Comment by jakekwak** [comment]
`demo/static-preview.html`
```
      <link rel="stylesheet" href="./light.css"/>
```
or `dark.css` or some `custom.css`

It means the user can make own preview theme.

**Comment by Vanessa219** [comment]
Users can customize CSS. dark and light are now supported.

**Comment by 88250** [comment]
We will support some theme previews in #324
