### ISSUE TITLE
版本3.9.7 为什么icon是请求http ,这个文件在node_module中已经有了

### ISSUE THREAD

**Issue by noenif** [Vanessa219/vditor#1520]
![image](https://github.com/Vanessa219/vditor/assets/25174520/30269e88-8655-4158-9ee2-9df1b011af2e)

**Comment by Vanessa219** [comment]
这个是默认的， cdn 需要自己进行配置修改。

**Comment by noenif** [comment]
> 这个是默认的， cdn 需要自己进行配置修改。

我说的是npm依赖包...不是你的项目

**Comment by Vanessa219** [comment]
这些都可以自己进行配置。

**Comment by noenif** [comment]
> 这些都可以自己进行配置。

能配置到本地的,我看了是可以配置CDN的.我现在是本地加了一个express做静态资源.但是我想直接导入dist中的包

**Comment by Vanessa219** [comment]
参照文档直接填 cdn 地址就可以了
