### ISSUE TITLE
简化 CDN 配置

### ISSUE THREAD

**Issue by fangjue** [Vanessa219/vditor#1522]
### 描述问题

近日所在网络环境无法访问 unpkg.com，使用 `cdn` 属性指定自建 CDN 后，仍有少量资源通过 unpkg.com 访问，包括主题 CSS（例如 /dist/css/content-theme/light.css）与 Emoji 图片（例如 /dist/images/emoji/hacpai.png）。要使这些资源也使用自建 CDN，需要额外设置其他选项，较为麻烦，编辑器与预览选项还有一些差异。

### 期待的结果

只要设置好 `cdn` 这一个属性，所有资源都能通过自建 CDN 访问。

### 版本信息

* 版本：3.9.7
* 操作系统：Windows 11
* 浏览器：Edge 120

### 其他信息

完全使用自建 CDN 所需的完整选项实例：
```js
const CDN = '/third_party/vditor'

// 编辑器选项
new Vditor('vditor', {
  cdn: CDN,
  preview: {
    theme: {
      current: 'light',
      path: `${CDN}/dist/css/content-theme`,
    },
  },
  hint: {
    emojiPath: `${CDN}/dist/images/emoji`,
  },
})

// 预览选项
Vditor.preview(el, content, {
    cdn: CDN,
    mode: 'light',
    theme: {
      current: 'light',
      path: `${CDN}/dist/css/content-theme`,
    },
    emojiPath: `${CDN}/dist/images/emoji`,
})
```

**Comment by Vanessa219** [comment]
嗯嗯

**Comment by alenQingshan** [comment]
按照配置走的自建cnd,但是报401是什么问题
![WX20240929-100343@2x](https://github.com/user-attachments/assets/eca4765b-91e6-43f2-a763-b2c9ef650a86)

**Comment by Vanessa219** [comment]
看上去是服务器没授权。
