### ISSUE TITLE
是否能提供一个禁用CDN的参数

### ISSUE THREAD

**Issue by meguoe** [Vanessa219/vditor#1524]
强烈建议提供一个禁用CDN的参数，现在CND动不动就无法访问，严重影响使用了。

**Comment by Vanessa219** [comment]
cdn 设置为本地的地址就可以了。

**Comment by Vanessa219** [comment]
速度飞起呀

**Comment by bear-joe** [comment]
我感觉本地更快，cdn太不稳定了，大项目更是追求稳定，还是建议作者优先本地，cdn作为备选，这么好的插件cdn会劝退不少人感觉。。。。

**Comment by Vanessa219** [comment]
@bear-joe 可以使用本地的

**Comment by newproplus** [comment]
@Vanessa219 

请问本地cdn怎么写?

我在项目根目录建了个目录 vditor_cdn, 把 dist 目录放进去了, 即 dist 目录是 vditor_cdn 目录的子目录.

cdn 写成 `'./vditor_cdn'`

`import Vditor from 'vditor'` 但是会报错: 

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Md2VditorIRDOM')", source: http://192.168.1.20:1420/node_modules/.vite/deps/vditor.js?v=fdd27565 (5164)
```

`import Vditor from '@/../vditor_cdn/dist/index'` 会找不到文件

`import Vditor from '@/../vditor_cdn/dist/index.min.js'`  会报错:

```
11:20:23 [vite] Pre-transform error: Maximum call stack size exceeded
11:20:34 [vite] Internal server error: Maximum call stack size exceeded
```

按个人理解, 如果不配置cdn应该是把所有文件大打包, 只有明确指定了cdn才应该通过网络获取cdn上的文件吧. 但是我测试的结果是不设置cdn一样会从默认的cdn上获取文件. 这让想离线使用的项目难搞了..

版本 3.9.8, 请问该如何解决?

**Comment by Vanessa219** [comment]
修改为 dist 访问的路径 https://xxxx

**Comment by newproplus** [comment]
> 修改为 dist 访问的路径 https://xxxx

必须走网络,不能直接使用本地的文件打包到一起?

**Comment by Vanessa219** [comment]
用上线后的反问地址就可以了。
