### ISSUE TITLE
标题总是会定义到第一行

### ISSUE THREAD

**Issue by huankai** [Vanessa219/vditor#1527]
在不同的行输入内容且选择中，选择第一标题/第二标题.... ， 选中所在的行没有渲染为标题，原来的标题被修改。

https://github.com/Vanessa219/vditor/assets/16852503/a4d09c39-9034-41a9-89df-a553123e163a

**Comment by Vanessa219** [comment]
无法重现，浏览器、版本号和编辑模式发一下。

https://github.com/Vanessa219/vditor/assets/970828/e9e16d1e-109d-4ba1-bc89-6f42c9d8e9b2

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
