### ISSUE TITLE
能不能不用cdn啊，直接读本地吧。总是这个问题 GET https://unpkg.com/vditor@3.9.4/dist/js/lute/lute.min.js net::ERR_CONNECTION_TIMED_OUT 。 https://unpkg.com这个东西国内总是访问不了

### ISSUE THREAD

**Issue by hallejuyahaha** [Vanessa219/vditor#1528]
能不能不用cdn啊，直接读本地吧。总是这个问题 GET https://unpkg.com/vditor@3.9.4/dist/js/lute/lute.min.js net::ERR_CONNECTION_TIMED_OUT 。 https://unpkg.com这个东西国内总是访问不了

**Comment by 88250** [comment]
请阅读 README，里面有修改 CDN 的参数。

**Comment by newproplus** [comment]
为什么要强制使用cdn?打包到一起不好吗?断网的话app怎么做?

**Comment by Vanessa219** [comment]
使用本地
