### ISSUE TITLE
i18n加载影响组件初始化逻辑

### ISSUE THREAD

**Issue by git102347501** [Vanessa219/vditor#1531]
### 编辑模式

sv
* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题
由于国内网络原因，控件依赖的i18n资源无法访问，导致以下代码无法触发回调，整个组件会渲染失败，导致组件显示空白
代码位置：https://github.com/Vanessa219/vditor/blob/master/src/index.ts
![企业微信截图_17031380273492](https://github.com/Vanessa219/vditor/assets/37917403/e416c322-2a7c-45f4-bd2a-204fe5957ccd)

通过配置自主托管的资源地址到 options的CDN属性上，问题可以解决

### 期待的结果

从程序设计上看，i18n的加载不应该影响整个组件init的渲染，这看上去不是一个良好的设计
从使用层看，作为国内使用场景，需要首先考虑CDN资源加载失效的问题，这个程序的不良设计资源加载居然可以引发灾难性故障。

### 版本信息

* 版本：3.7.7
* 操作系统：windows
* 浏览器： chrome

**Comment by izhxxx** [comment]
同样的问题……

**Comment by izhxxx** [comment]
同样的问题，请问是怎么解决的呀？

“通过配置自主托管的资源地址到 options的CDN属性上”，请问是怎么配置的呀？

**Comment by izhxxx** [comment]
GET https://unpkg.com/vditor@3.9.4/dist/js/i18n/zh_CN.js net::ERR_TIMED_OUT

**Comment by Vanessa219** [comment]
配置 cdn 就可以了。

**Comment by git102347501** [comment]
> GET https://unpkg.com/vditor@3.9.4/dist/js/i18n/zh_CN.js net::ERR_TIMED_OUT

首先，将node_modules/vditor/dist内的文件，托管到你的网站或者OSS上，得到你的资源链接: https://xxxx.com/vditor/dist/*
然后，配置：new Vditror(options => options.CDN = 'https://xxxx.com/vditor' ) 即可。

**Comment by git102347501** [comment]
> 配置 cdn 就可以了。

我认为这不是一个良好的设计，首先会带来诊断问题的成本，在遇到类似错误真的阻断init时，至少应该抛出明显的错误

**Comment by Vanessa219** [comment]
感谢反馈，下个版本添加提示。

**Comment by offeeyang** [comment]
我的CDN文件明明可以打开的，浏览器里直接访问该地址都可以看到js代码，为何还是出错呢？

**Comment by Vanessa219** [comment]
打开网络开一下
