### ISSUE TITLE
打包之后太大

### ISSUE THREAD

**Issue by zhangdaiscott** [Vanessa219/vditor#1532]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
````````

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

**Comment by 88250** [comment]
这个没有办法，lute 编译为 js 后就这么大了，只能压缩一下尽量减小体积。
