### ISSUE TITLE
不同开关显示不同块功能

### ISSUE THREAD

**Issue by xiedeacc** [Vanessa219/vditor#1534]
### 你在什么场景下需要该功能？

比如给不同系统提供安装指引，不同的系统有不同的指引情况下，点击不同的开关，就显示不同内容，如下图所示
![image](https://github.com/Vanessa219/vditor/assets/8072296/506449b5-cfb9-4973-ad0d-21cba9f18e7b)

最好还支持列表选择，就更好了

**Comment by 88250** [comment]
这个目前不考虑了，因为没有通用的 Markdown 语法可以支持。
