### ISSUE TITLE
如何批量更改/删除选中的元素

### ISSUE THREAD

**Issue by FantasticPornTaiQiang** [Vanessa219/vditor#1536]
### 版本
vditor 3.9.6
wysywyg模式

### 你在什么场景下需要该功能？

wysywyg模式下：

我正在做一个对文章中图片批量处理的工具。我通过querySelector拿到了所有的\<img\>元素。
需求是勾选后可以批量删除它们。

#### 遇到的问题是：
看了文档发现，vditor实例只有一个deleteValue方法。但是调用一次后，貌似所有\<img\>元素就被重新加载了，不再是之前的实例，无法通过selection选中了。

换言之，deleteValue删除一处没有问题，但是没想到怎么删除多处，类似的需求还有批量更新，但vditor的updateValue也只能更新一处。想问下这个场景有什么解决方案吗？感谢。

**Comment by Vanessa219** [comment]
这个只能在 dom 中删除后用 setValue

**Comment by FantasticPornTaiQiang** [comment]
> 这个只能在 dom 中删除后用 setValue

昨天找到了个类似的办法，假设待删除的img的数组长度是length，那么对前length-1个元素执行selection.deleteFromDocument();，最后一个元素执行vditor.deleteValue();即可。看了下源码发现deleteValue就是调用了document.execCommand('delete')，猜想vditor对document变化作了监听，并重新渲染markdown。

多谢作者回复。
