### ISSUE TITLE
错误提示：GET https://unpkg.com/vditor@3.9.8/dist/js/i18n/zh_CN.js net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by lfopuljanq** [Vanessa219/vditor#1537]
我在 React 项目中引用 Vditor。
`
...
import Vditor from "vditor"
import "vditor/dist/index.css"

function App() {
    // Vditor ---- Begin
    const [vd, setVd] = useState(null)

    useEffect(() => {
        const vditor = new Vditor("vditor", {
            width: "100%",
            height: "100%",
            theme: "classic",
            mode: "ir",
            value: "Hello",
            cache: {
                enable: false
            },
            preview: {
                markdown: {
                    codeBlockPreview: false
                }
            },
            // cdn: "http://192.168.5.201/vditor",
            after: () => {
                // vditor.setValue("Hello")
                setVd(vditor)
            }
        })
    }, [])
    // Vditor ---- End

    ...
    return (
        <div className="container-fluid">
                    {/* <div id="vditor" className="vditor" /> */}
        </div>
    )
}

export default App
`

由于程序在刚刚启动的时候不显示 vditor 。所以需要隐藏，但是这在运行时提示了：
`
GET https://unpkg.com/vditor@3.9.8/dist/js/i18n/zh_CN.js net::ERR_ABORTED 404 (Not Found)
`
我猜测时初始化的时候找不到 ID 为 vditor 的标签引起的。请问有什么其他的方法可以消除这个错误。

**Comment by lfopuljanq** [comment]
补充：这个是当我在页面中没有渲染这个组件时出现的。
![image](https://github.com/Vanessa219/vditor/assets/142517083/ed11404f-a240-4ffc-99ad-41baa6302606)
也就是我将这行代码注释了。因为当某些情况下，是不需要显示这个组件。

**Comment by Vanessa219** [comment]
是不是这个请求网络不通，不行的话配置一下 cdn 为 ` cdn: 'https://cdn.jsdelivr.net/npm/vditor',`
