### ISSUE TITLE
全屏显示且options.toolbarConfig.pin: true时，toolbar显示位置异常

### ISSUE THREAD

**Issue by ZhengZhiGeorge** [Vanessa219/vditor#1539]
### 编辑模式

* 三种模式都有

### 描述问题

全屏显示且options.toolbarConfig.pin: true时，toolbar显示位置异常：太靠下了，应当的位置被空出来了，漏出了之前的内容

### 截屏或录像

<img width="724" alt="截屏2024-01-10 16 34 26" src="https://github.com/Vanessa219/vditor/assets/49386710/76248a6d-18ba-4921-98d3-dd83ab5942ab">

### 版本信息

* 版本：3.9.8
* 操作系统：macos
* 浏览器：Safari（Chrome上没有这个问题）
* 框架：Vue3

**Comment by ZhengZhiGeorge** [comment]
官方的demo：https://b3log.org/vditor/demo/advanced-toolbar.html 是没问题的

**Comment by Vanessa219** [comment]
是不是被其他样式干扰到了？
