### ISSUE TITLE
自定义渲染器支持

### ISSUE THREAD

**Issue by ryanlin1986** [Vanessa219/vditor#1540]
### 你在什么场景下需要该功能？

希望实现自定义的渲染器，比如以下可以执行sql得到结果，对于一些报告类的文档，需要从数据库读取一些动态数值非常有意义
$$sql
select count(*) from test
$$

**Comment by Vanessa219** [comment]
render 可参照 `plantumlRender`
```
    customRenders?: {
        language: string,
        render: (element: HTMLElement, vditor: IVditor) => void
    }[]
```
