### ISSUE TITLE
分屏模式下，代码块中的【注释前置空格】、【空行】会被自动消除

### ISSUE THREAD

**Issue by gkn1234** [Vanessa219/vditor#1541]
### 编辑模式

* `sv` 分屏编辑预览模式

### 描述问题

分屏模式下，代码块中的【`#` 符号前的空格】、【空行】会被自动消除

````````markdown
**【反例】**
注释虽然放在代码段的上方，但没有和被注释代码段保持同样的缩进。

```python
    # Get replicate sub system index and net indicator   
repssn_ind = ssn_data[index].repssn_index
repssn_ni = ssn_data[index].ni

```
````````

### 期待的结果

在下述两种场景中，都能渲染为下图中期待的内容
1. 复制示例中的代码块到 sv 模式
2. 复制示例中的代码块到其余两种模式，之后切换到 sv 模式

![image](https://github.com/Vanessa219/vditor/assets/31581858/8cbf7e63-bbc5-421e-afac-0f37d849f49f)

然而，sv 模式下却会错误地渲染为下图的内容：

![image](https://github.com/Vanessa219/vditor/assets/31581858/087d8c7a-31db-4fc6-a550-fcaaa7406194)

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

**Comment by 88250** [comment]
你好，这是目前 SV 模式的缺陷，不久以后我们会彻底废弃现在的 SV 模式 https://github.com/Vanessa219/vditor/issues/1319
