### ISSUE TITLE
提供readOnly模式

### ISSUE THREAD

**Issue by Sharang-heng** [Vanessa219/vditor#1546]
存在只希望用md格式显示数据的需求，不允许用户输入内容，
 const interceptKeyboardEvent = (e) => {
    // 禁止ctrl-c以外的键盘输入
    if (
      !(
        e.keyCode === 67 &&
        (navigator.platform.match("Mac") ? e.metaKey : e.ctrlKey)
      )
    ) {
      e.preventDefault();
      e.stopPropagation();
    }
  };
  尝试过以上方式拦截，但是无法拦截中文输入

**Comment by ryanlin1986** [comment]
editor.disabled()可以满足你的需求吗？

**Comment by ryanlin1986** [comment]
如果只是要显示，用renderPreview方法即可

**Comment by Sharang-heng** [comment]
> editor.disabled()可以满足你的需求吗？

不满足，需要允许用户选中内容进行复制

**Comment by Sharang-heng** [comment]
> 如果只是要显示，用renderPreview方法即可

这个似乎也不行，我目前是直接使用Vditor.preview

**Comment by Vanessa219** [comment]
没问题的话我就先关闭了。
