### ISSUE TITLE
Latex无法解析以数字开头的公式

### ISSUE THREAD

**Issue by justice2001** [Vanessa219/vditor#1547]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

无法解析以数字开头的公式，如果出现以数字开头的公式会直接原样输出。

````````markdown
$1234*\frac{a}b$
````````

### 期待的结果

应当正确渲染公式

### 截屏或录像

<img width="1019" alt="截屏2024-01-23 19 25 30" src="https://github.com/Vanessa219/vditor/assets/28425753/c11eda1b-1398-4787-99b4-3215f6192e7a">

### 版本信息

* 版本：Vditor 3.9.8
* 操作系统：macOS 14
* 浏览器：Safari

### 其他信息

https://github.com/justice2001/halo-plugin-vditor/issues/22 （第一条）

**Comment by Vanessa219** [comment]
需要设置
```
     preview: {
            math: {
                inlineDigit: true,
            },
        },
```
