### ISSUE TITLE
通过调用setValue方法给md设置内容，点击sql的复制按钮后会出现两个编辑框

### ISSUE THREAD

**Issue by Sharang-heng** [Vanessa219/vditor#1548]
如图，点了A的复制，出现了B
![image](https://github.com/Vanessa219/vditor/assets/69613396/2924e8c9-e311-4604-8e9b-643c45cf3a17)

**Comment by 88250** [comment]
好像没啥问题，下面一个是预览。

**Comment by Sharang-heng** [comment]
> 好像没啥问题，下面一个是预览。

不应该啊，我点复制为啥还要弹个东西出来，而且用Vditor.preview是不会出现的，用setValue才会，两边表现不太一致，或者有没有办法关掉这个预览

**Comment by 88250** [comment]
@Vanessa219
