### ISSUE TITLE
导出主题没有正确读取

### ISSUE THREAD

**Issue by ryanlin1986** [Vanessa219/vditor#1549]
![image](https://github.com/Vanessa219/vditor/assets/11850439/6bdab3e0-4c31-4c7b-95f1-e922861d280a)

可以看到，preview.theme是一个对象而不是文本，应该是preview.theme.current?

**Comment by Vanessa219** [comment]
markdown.theme 也是一个对象

**Comment by ryanlin1986** [comment]
所以应该用JSON.stringify(vditor.options.preview.theme)，否则字符串和对象相加，对象toString默认实现是[object Object]

**Comment by Vanessa219** [comment]
多谢，稍后修复
