### ISSUE TITLE
数学表达式matrix自从3.8.6版本开始，无法正常渲染

### ISSUE THREAD

**Issue by a1473838623** [Vanessa219/vditor#1554]
### 编辑模式

* `sv` 分屏编辑预览模式

### 描述问题

数学表达式matrix自从3.8.6版本开始，无法正常渲染。markdown原文如下
````````markdown
$\begin{pmatrix}
1 &  &   & \\
&  -1 &  & \\
&  &  -1 & \\
\end{pmatrix}$
````````

### 期待的结果

正常结果如以下截图：
### 截屏或录像
正常(3.8.5及之前)：
![image](https://github.com/Vanessa219/vditor/assets/71368946/6fd06509-9936-444e-b67e-aef93f585442)

不正常(3.8.6及以后)：
![image](https://github.com/Vanessa219/vditor/assets/71368946/3d780c08-ad99-4852-a18c-396c15543f47)

### 版本信息

* 版本：3.8.6
* 操作系统：mac
* 浏览器：safari

**Comment by a1473838623** [comment]
但是用两个$$就能渲染了。不过两个$$是居中的意思，如何做到正常渲染，又不用居中呢？
![image](https://github.com/Vanessa219/vditor/assets/71368946/f9c58450-4f11-4267-8f9a-680eb3a0222d)

**Comment by Vanessa219** [comment]
两个 $ 表示公式块，一个表示行内公示。行内公示是不允许有换行的。
