### ISSUE TITLE
是否有方式可以禁止 iframe 或是其它任何 html 标签

### ISSUE THREAD

**Issue by Noahs007** [Vanessa219/vditor#1555]
### 你在什么场景下需要该功能？
基于 electron 类似的框架做一个本地markdown编辑器。

想尽可能提高应用安全性，防注入，想知道是否有方式可以禁止 iframe 解析，甚至说可以不用 其它任何 html 标签。

### 描述最优的解决方案 
有没有解析规则配置之类的，禁用某些语法。例如 <iframe src="https://www.hao123.com"></iframe> 目前可以显示网页，希望这种标签直接显示文本好了。

**Comment by Vanessa219** [comment]
@88250

**Comment by ooyyloo** [comment]
> @88250 

有办法吗？没看懂这个什么意思

**Comment by 88250** [comment]
可以试试开关 `lute.SetSanitize(true)`，或者覆写相关渲染器：

![image](https://github.com/Vanessa219/vditor/assets/873584/c7b0e06a-c32b-44ab-8796-33a0ad62fd13)

**Comment by Vanessa219** [comment]
覆写后设置参数即可。
