### ISSUE TITLE
希望在编辑器渲染完成后包括大纲等配置项可以变更配置，大纲渲染完成后更新开关状态已强行解决

### ISSUE THREAD

**Issue by ponysb** [Vanessa219/vditor#1556]
### 描述问题

我翻找了官网文档没有找到这种这种方法，也看了评论区看到有不少类似需求，但是并没有找到答案
目前解决方案是用class获取大纲的dom强行变更display进行实现，如下，但是这种实现方法并不优雅，想知道有没有更优雅地方式实现
![image](https://github.com/Vanessa219/vditor/assets/37097190/173bf0d7-f435-4b5e-ba2f-69b795b8e50d)

### 期待的结果

官方给出最为优雅地解决方案以及其他配置项渲染完成之后的更新方案

### 版本信息

* 版本：3.9.8
* 操作系统：Windows
* 浏览器：electron

**Comment by Vanessa219** [comment]
如果需要修改的话可以为功能单独提供方法
