### ISSUE TITLE
想自建cdn用github最新源码打包报错，直接打包报以下错误

### ISSUE THREAD

**Issue by ponysb** [Vanessa219/vditor#1558]
### 描述问题

想自建cdn用github最新源码打包报错，cnpm install   npm build直接打包报以下错误

BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
assets by status 17.4 MiB [cached] 306 assets
Entrypoint index.min = index.css index.min.js
Entrypoint method.min = method.min.js
orphan modules 526 KiB (javascript) 937 bytes (runtime) [orphan] 86 modules
runtime modules 1.31 KiB 6 modules
cacheable modules 646 KiB (javascript) 39.9 KiB (css/mini-extract)
  modules by path ./src/ts/ 66.8 KiB
    modules by path ./src/ts/markdown/*.ts 39 KiB 15 modules
    modules by path ./src/ts/util/*.ts 20.8 KiB 8 modules
    modules by path ./src/ts/ui/*.ts 1.18 KiB 2 modules
    ./src/ts/preview/image.ts 2.93 KiB [built] [code generated]
    ./src/ts/constants.ts 2.92 KiB [built] [code generated]
  modules by path ./src/*.ts 505 KiB
    ./src/index.ts + 75 modules 484 KiB [built] [code generated]
    ./src/method.ts + 4 modules 20.5 KiB [built] [code generated]
  css ./node_modules/.store/css-loader@5.2.7/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].use[1]!./node_modules/.store/postcss-loader@5.3.0/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!./node_modules/.store/less-loader@10.2.0/node_modules/less-loader/dist/cjs.js!./src/assets/less/index.less 39.9 KiB [built] [code generated]
  ./node_modules/.store/diff-match-patch@1.0.5/node_modules/diff-match-...(truncated) 74.6 KiB [built] [code generated]

ERROR in C:\Users\Administrator\Desktop\vditor-master\src\ts\undo\index.ts
./src/ts/undo/index.ts
[tsl] ERROR in C:\Users\Administrator\Desktop\vditor-master\src\ts\undo\index.ts(20,33)
      TS2694: Namespace 'diff_match_patch' has no exported member 'diff_match_patch'.
 @ ./src/index.ts 40:0-39 436:31-35

ERROR in C:\Users\Administrator\Desktop\vditor-master\src\ts\undo\index.ts
./src/ts/undo/index.ts
[tsl] ERROR in C:\Users\Administrator\Desktop\vditor-master\src\ts\undo\index.ts(139,36)
      TS7006: Parameter 'patch' implicitly has an 'any' type.
 @ ./src/index.ts 40:0-39 436:31-35

ERROR in C:\Users\Administrator\Desktop\vditor-master\src\ts\undo\index.ts
./src/ts/undo/index.ts
[tsl] ERROR in C:\Users\Administrator\Desktop\vditor-master\src\ts\undo\index.ts(140,38)
      TS7006: Parameter 'diff' implicitly has an 'any' type.
 @ ./src/index.ts 40:0-39 436:31-35

webpack 5.90.1 compiled with 3 errors in 5048 ms

### 版本信息
* 版本：3.9.8
* 操作系统：win11

**Comment by Vanessa219** [comment]
安装一下 diff_match_patch
