### ISSUE TITLE
自定义渲染器输出的HTML与内置渲染器不同

### ISSUE THREAD

**Issue by justice2001** [Vanessa219/vditor#1559]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

在新发布的功能：自定义渲染器中，自定义渲染器生成的 HTML 与内置渲染器生成格式不一致。例如我编写一个`test`的自定义渲染器，其生成的格式是这样的:

```html
<pre><code class="language-test">12345\n</code></pre>
```

然而内置的渲染器生成的结果是：

```html
<div class="language-mermaid">graph TD;     A--&gt;B;     A--&gt;C;     B--&gt;D;     C--&gt;D;\n</div>
```

### 期待的结果

建议自定义渲染器输出的HTML与内置渲染器的生成结果一致。

### 版本信息

* 版本：3.9.9
* 操作系统：macOS
* 浏览器：Safari

### 其他信息

之前魔改过这部分，发现好像渲染器输出的判断在lute中，似乎没有做拓展的设计，感觉不太好改。但我有一个思路，就是在 Vditor 生成 HTML 的部分后进行后处理，使用正则进行匹配，来将自定义渲染器的`<pre><code class="language-test">`修改为`<div class="language-test">`，不知道这样设计是否可行。

**Comment by Vanessa219** [comment]
这个是默认的，需要渲染的内容需要自己填充。可参见 xxxRender.ts 文件
