### ISSUE TITLE
li 缩进后没有渲染代码块

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#156]
> ### This is a H3
> * List
>   ```
>   code
>   ```

![blockquote2](https://user-images.githubusercontent.com/15811943/74801148-6704d580-529b-11ea-8607-6ac81533a04c.gif)

**Comment by Vanessa219** [comment]
pls tell me how to press the last list item?

**Comment by jakekwak** [comment]
`ctrl+.`,  `ctrl+alt+3`, `This is a H3`, `enter`
`ctrl+l`, `List`,  `shift+enter`
`ctrl+u`, `code`, `ctrl+shift+e`, `enter`, `enter`, `enter`

**Comment by jakekwak** [comment]
another error: `ctrl+.`, `ctrl+alt+3`
![notcombined](https://user-images.githubusercontent.com/15811943/74853953-3e64f600-5304-11ea-849c-fb6c6f12a48f.gif)

still not working (`enter`, `enter`, `enter`, `enter`)

![enterenter](https://user-images.githubusercontent.com/15811943/74854235-af0c1280-5304-11ea-83a1-a32b750df34d.gif)
