### ISSUE TITLE
回车后标光标位置闪动

### ISSUE THREAD

**Issue by shuke0104** [Vanessa219/vditor#1565]
### 编辑模式

* `WYSIWYG` 所见即所得

### 描述问题

内容为空的情况下，直接回车编辑器内会变成两行然后再变回一行

### 期待的结果

首次输入时，直接回车后只出现一行

### 版本信息

* 版本：3.9.9
* 操作系统：win11
* 浏览器：google

**Comment by shuke0104** [comment]
内容为空 直接回车还是会跳动

**Comment by Vanessa219** [comment]
还没有发布，你是使用线上最新代码测试的么？
