### ISSUE TITLE
IR 模式滚动时隐藏代码块语言提示

### ISSUE THREAD

**Issue by Excalibur-king** [Vanessa219/vditor#1567]
### 编辑模式

* `ir` 即时渲染模式

### 描述问题

在代码块弹出语法选择下拉菜单后，滚动页面，下拉菜单不跟随页面滚动，点击后会报错。

### 截屏或录像

![20240229-165805](https://github.com/Vanessa219/vditor/assets/63062773/2430f1be-b088-4f7f-9fd8-cafd9e9f7b7f)
![20240229-165812](https://github.com/Vanessa219/vditor/assets/63062773/96ae4e57-e9b0-4726-80b0-c737a2245c89)

### 版本信息

* 版本：3.9.9
* 操作系统：macos
* 浏览器：chrome

**Comment by Vanessa219** [comment]
和 wysiwyg 保持一致，进行隐藏

**Comment by Excalibur-king** [comment]
收到
