### ISSUE TITLE
在即时渲染模式中，无法删除无序列表中出现的空行

### ISSUE THREAD

**Issue by a1473838623** [Vanessa219/vditor#1569]
### 编辑模式

* `ir` 即时渲染模式

### 描述问题

一旦无序列表中的某一行出现了空行，其他同级列表都会插入一空行，且该空行无法单独删除，只能通过 JS **一起**删除全部空行。
````````markdown
- 1
  
  - 2
- 3
  
  - 4
````````

### 期待的结果

应该能够删除无序列表中的空行。删除后如下所示
````````markdown
- 1
  - 2
- 3
  - 4
````````

### 截屏或录像

以下录屏（分屏编辑）中，删除键不起作用；在即时渲染模式中光标无法移动到空行，但是间距比其他没有空行的间距大
![](https://github.com/Vanessa219/vditor/assets/71368946/d102c57d-04df-48fb-8256-168a733167b2)

### 版本信息

* 版本：3.9.8
* 操作系统：win10 or ubuntu
* 浏览器：chrome

**Comment by Vanessa219** [comment]
这个应该是 SV 模式。由于 https://github.com/Vanessa219/vditor/issues/1319 ，SV 模式相关问题不再进行修改。

**Comment by a1473838623** [comment]
仅使用ir模式的情况下也会出现这种情况。录屏中使用分屏只是为了展示。
目前使用css暂时解决了，但个人认为在一个地方插入空行就会导致全文插入空行，而且无法删除空行，这种行为的破坏性较大。
```
.vditor>* {

  li>p {
    margin-block-start: 0em !important;
    margin-block-end: 0em !important;
  }

  li {
    margin-top: 0.4em !important;
  }

}
```

**Comment by Vanessa219** [comment]
IR 模式下是可以进行删除的。如果没有空行的话不会有间距的，这个空行是根据 CommonMark 规范生成的一个 p 标签。

https://github.com/Vanessa219/vditor/assets/970828/3637cac3-5ecd-46f2-8c07-825fc6a215ce
