### ISSUE TITLE
Difference between GFM spec. and vditor

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#157]
https://github.github.com/gfm/

Example 41, 42, 43 https://github.github.com/gfm/#example-41
![Example41-42-43(low)](https://user-images.githubusercontent.com/15811943/75085728-9e6cbf80-54f1-11ea-881f-fa1ad5ea1926.gif)

Example 282 https://github.github.com/gfm/#example-282
![Example282](https://user-images.githubusercontent.com/15811943/75085740-c65c2300-54f1-11ea-9420-e8d04dbd9e9b.gif)

--- 

### May have been fixed

Example6, 7 https://github.github.com/gfm/#example-6
![Example6-7](https://user-images.githubusercontent.com/15811943/75085708-7ed59700-54f1-11ea-91d3-eade74aef1c4.gif)

Example 345, 347 https://github.github.com/gfm/#example-345
![Example345-347](https://user-images.githubusercontent.com/15811943/75085743-c9efaa00-54f1-11ea-8d0f-4555c5d61f4f.gif)

Example 661, 662 https://github.github.com/gfm/#example-661
![Example661-662](https://user-images.githubusercontent.com/15811943/75085746-cf4cf480-54f1-11ea-88cc-10d6eb915628.gif)

###  Expected do not render with WYSIWYG

Example 49 https://github.github.com/gfm/#example-49
![Example49](https://user-images.githubusercontent.com/15811943/75085730-a6c4fa80-54f1-11ea-9491-51fa9e61f0dc.gif)
With WYSIWYG mode we do not render empty ATX headings is expected.

Example 11, 21, 24 https://github.github.com/gfm/#example-11
![Example11-21-24(low)](https://user-images.githubusercontent.com/15811943/75085710-872dd200-54f1-11ea-8b12-128a0164ed48.gif)
The final rendering result is `<hr />` is correct.

Example 23 https://github.github.com/gfm/#example-23
![Example23](https://user-images.githubusercontent.com/15811943/75085718-944ac100-54f1-11ea-9090-045caf19c153.gif)
The input flow cause to render as expected, so I think should test it with copy-paste the whole text `-     -      -      -`.

**Comment by 88250** [comment]
Thanks, we will check it later.

**Comment by 88250** [comment]
I edit your post directly for classifying these issues.

**Comment by jakekwak** [comment]
@88250 Example6, 7 but I don't know the other effect.
previewPanel.innerHTML = `<pre><code class="${codeElement.className}">${innerHTML.~~trim()~~}</code></pre>`;

**Comment by jakekwak** [comment]
Example 19:
I think the `lute` have to be return it including space before `enter` input(not `shift+enter`)

**Comment by Vanessa219** [comment]
> @88250 `Example6, 7` but I don't know the other effect.
> `processCodeRender.ts`
> previewPanel.innerHTML = `<pre><code class="${codeElement.className}">${innerHTML.~trim()~}</code></pre>`;

```
previewPanel.innerHTML = `<pre><code class="${codeElement.className}">${innerHTML.trimRight()}</code></pre>`;
```

**Comment by 88250** [comment]
I moved 6,7 to section `May have been fixed`

**Comment by jakekwak** [comment]
I made separate issue.
