### ISSUE TITLE
粘贴网页图片，不能触发upload.linkToImgCallback回调

### ISSUE THREAD

**Issue by Minhat-GitHub** [Vanessa219/vditor#1571]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

粘贴网页图片，不能触发upload.linkToImgCallback回调

### 期待的结果

粘贴网页图片，能触发upload.linkToImgCallback回调

### 截屏或录像

![image](https://github.com/Vanessa219/vditor/assets/35595109/f72ea8b8-9939-4d41-948a-26169a1a14ee)

### 版本信息

* 版本：3.9.9
* 操作系统：Win11
* 浏览器：版本 120.0.6099.217（正式版本） （64 位）

**Comment by Vanessa219** [comment]
检查一下是不是 linkToImgUrl 接口返回错误
