### ISSUE TITLE
甘特图时间轴重叠

### ISSUE THREAD

**Issue by Sharang-heng** [Vanessa219/vditor#1574]
import { useEffect, useState } from "react";
import Vditor from "vditor";
import "vditor/dist/index.css";

const App = () => {
  const [vd, setVd] = useState<Vditor>();
  useEffect(() => {
    const vditor = new Vditor("vditor", {
      after: () => {
        vditor.setValue("```mermaid\ngantt\ntitle 开发项目计划\ndateFormat  YYYY-MM-DD\nsection 平台开发\na平台     :active, a1, 2023-01-01, 1d\nb平台    :after a1  , 2023-01-01, 3d\nc平台    :after a1, 2023-01-04, 3d\n```\n\n");        setVd(vditor);
      },
    });
    // Clear the effect
    return () => {
      vd?.destroy();
      setVd(undefined);
    };
  }, []);
  return <div id="vditor" className="vditor" />;
};

export default App;
![image](https://github.com/Vanessa219/vditor/assets/69613396/f11d067e-7c48-4e4b-8622-e0c33ef4e1ac)

**Comment by Vanessa219** [comment]
这个是由于宽度不够，编辑器宽一点就可以了
<img width="1264" alt="image" src="https://github.com/Vanessa219/vditor/assets/970828/14dbf55f-f354-419b-9208-5acf7e0f7aee">

**Comment by Sharang-heng** [comment]
能不能做个自适应优化一下，而且这个时间轴也很奇怪

**Comment by Vanessa219** [comment]
好的，下个版本改进
