### ISSUE TITLE
为什么代码块渲染时会出现两次复制的情况，一次在外面，一次是里面的代码块折叠

### ISSUE THREAD

**Issue by hgtc2698334504** [Vanessa219/vditor#1576]
![image](https://github.com/Vanessa219/vditor/assets/89202323/e7868d38-e898-49a7-ab0b-e2bd372e2cb5)
渲染的逻辑是这样的，不知道怎么会出现上面的错误
`javascript
VditorPreview.preview(vditorPreview, outerHTML, {
                    theme: {
                        current: 'Light'
                    },
                    hljs: {
                        style: "borland",
                        lineNumber: true,

                    },

                });

`

**Comment by Vanessa219** [comment]
只有一个复制按钮，你的重现步骤是？
<img width="998" alt="image" src="https://github.com/Vanessa219/vditor/assets/970828/988eb28d-c18a-4bee-9e0a-15ca48589a0a">
