### ISSUE TITLE
不支持图片粘贴上传？，please config: options.upload.ur

### ISSUE THREAD

**Issue by Javahhhh** [Vanessa219/vditor#1580]
我遇到的问题是在http://localhost:5173/
点击上传按钮无法上传图片与文件，我找不到相关信息，如果没有后端是不是还不可以上传本地图片？代码添加了 upload: {
            accept: 'image/*,.mp3, .wav, .rar',
            token: 'test',
            url: '/api/upload/editor',
            linkToImgUrl: '/api/upload/fetch',
            filename(name) {
                return name.replace(/[^(a-zA-Z0-9\u4e00-\u9fa5\.)]/g, '').replace(/[\?\\/:|<>\*\[\]\(\)\$%\{\}@~]/g, '').replace('/\\s/g', '')
            },
        },，不管用，

**Comment by Vanessa219** [comment]
这个需要服务的配合的，否则无法把图片传到服务器上。
