### ISSUE TITLE
Markdown粘贴过去的普通链接可否自动渲染成可以点击的超链接

### ISSUE THREAD

**Issue by GuGuGee** [Vanessa219/vditor#1585]
### 你在什么场景下需要该功能？

在Halo中使用，发现如果Markdown下粘贴过去的链接是一个普通的链接，渲染之后是普通的文本，无法实现点击跳转。

只有严格写成
```
[https://www.google.com/](https://www.google.com/)
```
这种模式，才能渲染出超链接。

![image-20240320105809605](https://img.laoda.de/i/2024/03/20/105813-1.webp)

有时候文章里面的链接比较多，需要逐一来写成

```
[https://www.google.com/](https://www.google.com/)
```
这种形式，比较费劲 = =

是否考虑可以给这些链接自动渲染成可以点击的超链接？或者是给用户一个选项是否开启的功能。

### 其他信息

- 外部访问地址: https://blog.laoda.de
- 启动时间: 2024-03-15 09:22
- 版本: 2.13.1
- 构建时间: 2024-03-06 17:40
- Git Commit: 9473261
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.1.0
- 操作系统: Linux / 6.1.0-18-amd64
- 已激活主题: [Theme Joe3](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [朋友圈](https://github.com/chengzhongxue/plugin-friends)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

**Comment by Vanessa219** [comment]
由于有些用户可能只是想显示链接文本。如果需要的话可以使用 ctrl+K

**Comment by lulu2jinchi** [comment]
为什么demo里的编辑器在sv模式时支持自动链接呢

**Comment by Vanessa219** [comment]
那个是用了Lute 服务端的渲染

**Comment by sunny12308** [comment]
ctrl+K是咋用的？我按ctrk+K会跳转到浏览器地址上【使用google搜索】
