### ISSUE TITLE
初始化的时候， 在main.js引入less文件编译错误

### ISSUE THREAD

**Issue by f2511571150** [Vanessa219/vditor#1587]
### 描述问题

引入less文件的时候解析错误：
![image](https://github.com/Vanessa219/vditor/assets/75900359/c9efda07-f1b8-439a-b04f-c7b2faed540d)
我的vite版本： 4.4.5
引入： 在main.js文件引入的index.less
![image](https://github.com/Vanessa219/vditor/assets/75900359/925e568a-e138-45c8-ae01-4f0ea485e222)

### 期待的结果

能够编译成功

### 版本信息

* 版本：3.10.2
* 操作系统：windows11
* 浏览器：chrome

**Comment by Vanessa219** [comment]
vditor less 的打包代码参见 https://github.com/Vanessa219/vditor/blob/8ede475d8cbcc65305487ae27b9bc15e94e12193/webpack.config.js#L120

可对照进行修改。
