### ISSUE TITLE
五线谱连奏线显示错误.

### ISSUE THREAD

**Issue by will-mei** [Vanessa219/vditor#159]
跨行的五线谱联奏线, 部分是正常的, 但是有一部分位置是错乱的， 这是个很基本的功能, 可以考虑给修一下, 同样的代码在 abcConverter  (在官方文档找到的另一个在线渲染的工具, [abcConverter](http://www.mandolintab.net/abcconverter.php) )的页面上可以正常显示.
代码:
```
%abc-2.1
X:1
M:C
L: 1/4
K:C
V:PianoRightHand clef=treble
V:PianoLeftHand clef=treble 
[V: PianoRightHand]     !1!(c e c e | g e c e | d g f d | e c g e | (c) e c e |
[V: PianoLeftHand] "_1\n2\n4"[CEG]4 | [CEG]4  | [B,DG]4 | [CEG]4  | [CEG]4    |
\
[V: PianoRightHand]     g e c e | d g f d | c e c2) :|]|: (d e f d | e g e c |
[V: PianoLeftHand]       [CEG]4 | [B,FG]4 | [CEG]4  :|]|:  [B,DG]4 | [CEG]4  |
\
[V: PianoRightHand]    d e f d  |  e g f d       | (c) e c e | g e c e |  d g f d        | c e c2) :|]
[V: PianoLeftHand]      [B,DG]4 | [CEG]2 [B,DG]2 | [CEG]4    | [CEG]4  | [B,FG]2 [B,FG]2 | [CEG]4  :|]
```
如果访问 abcConverter太慢 (至少我是这样), 看这里也行:
https://hacpai.com/article/1582044218709  
在 NO11, 我贴了图可以对比.

**Comment by Vanessa219** [comment]
帖子中的链接版本太老了，显示应该是正确的，可能是括号的问题，你可以看一下 https://www.abcjs.net/abcjs-editor.html

**Comment by will-mei** [comment]
> 帖子中的链接版本太老了，显示应该是正确的，可能是括号的问题，你可以看一下 https://www.abcjs.net/abcjs-editor.html

试了, 这个渲染的结果也是错误的.
![ABC](https://user-images.githubusercontent.com/24793917/74914147-e100a000-53fc-11ea-95a0-547b92e43c85.png)
而 abcConverter 结果是正常的.
![image](https://user-images.githubusercontent.com/24793917/74914823-093cce80-53fe-11ea-92f9-eb8d315f8497.png)

**Comment by Vanessa219** [comment]
好像是被冒号影响了，这个冒号是代表什么么？
```
[V: PianoRightHand]     g e c e | d g f d | c e c2) |]| (d e f d | e g e c |
[V: PianoLeftHand]       [CEG]4 | [B,FG]4 | [CEG]4  |]|  [B,DG]4 | [CEG]4  |
```
中间改成这样好像就可以了

**Comment by will-mei** [comment]
> 
> 
> 好像是被冒号影响了，这个冒号是代表什么么？
> 
> ```
> [V: PianoRightHand]     g e c e | d g f d | c e c2) |]| (d e f d | e g e c |
> [V: PianoLeftHand]       [CEG]4 | [B,FG]4 | [CEG]4  |]|  [B,DG]4 | [CEG]4  |
> ```
> 
> 中间改成这样好像就可以了

这个冒号代表 反复记号 , 用两个相对的反复记号就表示了一个 反复演奏的区间, 代表这一段内容要被反复演奏然后再继续, 没有了这里的冒号, 那就只有末尾有反复记号了, 末尾的反复记号找不到前面对应的开始标记就得从开头开始重复演奏, 内容重复的方式就完全不一样了.

**Comment by Vanessa219** [comment]
可以先把反复演奏符放在末尾
也可以关注一下这个 issue https://github.com/paulrosen/abcjs/issues/347
