### ISSUE TITLE
大纲对不齐

### ISSUE THREAD

**Issue by wmkai** [Vanessa219/vditor#1591]
<img width="297" alt="image" src="https://github.com/Vanessa219/vditor/assets/39148461/1ccdc78f-3c54-4f1b-923d-a58c31eed931">
请问一下作者，有没有支持调整大纲宽度的计划。
还有想问下，为啥这里子标题之间不是对齐的？
谢谢作者！

**Comment by zxniuniu** [comment]
我也遇到这个问题了，貌似是大纲中如果有中英文混合的情况，就对不齐了。

**Comment by wmkai** [comment]
> 我也遇到这个问题了，貌似是大纲中如果有中英文混合的情况，就对不齐了。

我试了一下，有时候有中英文混合也能对齐，有时候不行。很玄学。。。
