### ISSUE TITLE
Vditor再次创建渲染问题

### ISSUE THREAD

**Issue by ZehuaZhang** [Vanessa219/vditor#1592]
Vditor在React里，第二次创建的时候，文本好像样式Style不对，标题文字都变小，得再次刷新一下页面就对了，还有Line Chart和Bar Chart用的是echart也是这个问题

我第一次创建的时候`new vditor()`，在最后会`destroy`
还想请问 如果中途要改darkmode，是否需要先`destroy`再次`new vditor`，这个会自动销毁上一次的实例吗

一下是问题的截图
![image](https://github.com/Vanessa219/vditor/assets/15708284/1b172e4c-6fbc-441e-b129-d21a9288d1a1)

**Comment by Vanessa219** [comment]
会根据 Dom 中的内容进行 MD 渲染。如果不需要的话清空 Dom 的 innerHTML 即可。

destroy 中会使用原始只清理 dom 
```
 this.vditor.element.innerHTML = this.vditor.originalInnerHTML;
```

**Comment by ZehuaZhang** [comment]
`new Vditor`会出现多个实例吗，需要手动销毁吗

**Comment by ZehuaZhang** [comment]
> 会根据 Dom 中的内容进行 MD 渲染。如果不需要的话清空 Dom 的 innerHTML 即可。
> 
> destroy 中会使用原始值清理 Dom
> 
> ```
>  this.vditor.element.innerHTML = this.vditor.originalInnerHTML;
> ```

我用了你的方法 每次重新创建新实例前清楚之前的`innerHtml` 但问题依旧存在

**Comment by Vanessa219** [comment]
new 一个就会出现一个。你可能是多次 new 了

**Comment by ZehuaZhang** [comment]
> new 一个就会出现一个。你可能是多次 new 了

 `vditor.preview` 会new一个吗？
 new一个了 但是图表还是存在这个问题

**Comment by Vanessa219** [comment]
1. 不会
2. 我这里重现不了，具体步骤是？
3. 调用对应的方法
4. PR
