### ISSUE TITLE
图表自适应

### ISSUE THREAD

**Issue by ZehuaZhang** [Vanessa219/vditor#1593]
图表初始渲染正常，但是当浏览器窗口宽度改变到较小时，mermaid 和 echarts 有些图会变的特别窄，不是100%宽度，宽度大概是207px, 随意拉动几次会恢复正常

如下
![Screenshot 2024-03-26 at 3 54 26 PM](https://github.com/Vanessa219/vditor/assets/15708284/a864e6a3-cb72-4faf-8a77-7c98f978df70)
![Screenshot 2024-03-26 at 3 54 29 PM](https://github.com/Vanessa219/vditor/assets/15708284/5257017b-de7b-406a-8b76-55a91663e3e7)
![Screenshot 2024-03-26 at 3 54 33 PM](https://github.com/Vanessa219/vditor/assets/15708284/81495092-ca8b-49d5-bba4-b4506c5ff2e1)

**Comment by Vanessa219** [comment]
我这里好像是自适应的。

https://github.com/Vanessa219/vditor/assets/970828/a7974b3f-3b80-4ca5-91c9-22d8c0af6680
