### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'currentMode')

### ISSUE THREAD

**Issue by XCLHove** [Vanessa219/vditor#1595]
### 编辑模式

* `ir` 即时渲染模式

### 描述问题

代码：
```js
<script setup lang="ts">
import {onMounted} from "vue";
import Vditor from 'vditor'
import 'vditor/dist/index.css'

let vditor: Vditor = null

onMounted(() => {
  vditor = new Vditor('vditor', {})
  console.log(vditor.getValue())
})
</script>

<template>
  <div class="container">
    <div id="vditor"></div>
  </div>
</template>

<style scoped>
.container {
  box-sizing: border-box;
  padding: 30px 0;
}
</style>
```

报错：
```
TypeError: Cannot read properties of undefined (reading 'currentMode')
    at a (index.min.js:1:64846)
    at t3.getValue (index.min.js:1:262946)
    at App.vue?t=1711609992352:12:26
```

````````markdown

````````

### 截屏或录像
![image.png](https://xnote.xclhove.top/api/image/downloadByName/1f446b16-71f1-46e3-a6ec-9fb0acfb6b0b.png)

### 版本信息

* 版本："**vditor**": "^3.10.2","**vue**": "^3.4.21"
* 操作系统：Ubuntu 22.04
* 浏览器：Microsoft Edge 版本 121.0.2277.128 (正式版本) (64 位)

**Comment by Vanessa219** [comment]
demo 上是正常的，这个错误信息看不出具体的问题。

**Comment by 0000005** [comment]
请问怎么解决的？

**Comment by 0000005** [comment]
如果new了Vditor之后，马上操作vditor对象，就会报错。把操作逻辑移动到 点击事件里，延迟操作vditor的时机。 就运行正常了。
目测Viditor没有初始化完成。

**Comment by 0000005** [comment]
这里有初始化完成的回调事件吗？ @Vanessa219  这种情况下如何处理比较好？
![image](https://github.com/Vanessa219/vditor/assets/9690089/31fd1154-da3d-4461-9106-f9ffc942d0a6)

**Comment by 0000005** [comment]
我看到了，用after回调函数
