### ISSUE TITLE
建议针对宽屏显优化

### ISSUE THREAD

**Issue by will-mei** [Vanessa219/vditor#160]
所见即所得模式下, 编辑器区的宽度能不能自动适应页面的宽度.

如果用户用的是宽屏显示器, 比如有长代码的时候,  编辑的时候想让一行内容能显示的多一点,  但是页面宽度是固定的, 宽度太窄了看着真的很不舒服, 希望可以改进一下.

**Comment by Vanessa219** [comment]
宽度可以使用 options.preview.maxWidth 参数进行设置
