### ISSUE TITLE
缩放比例变小了，不知道怎么恢复

### ISSUE THREAD

**Issue by wmkai** [Vanessa219/vditor#1600]
用的是mac系统，之前正常的时候，缩放比例如图一，今天打开同一个文件，缩放比例变成图二了，感觉尺寸缩小了很多。期间我安装了nodejs，但把nodejs卸载后，尺寸还是和第二张图一样。
<img width="1171" alt="image" src="https://github.com/Vanessa219/vditor/assets/39148461/c9c5159a-7d96-4873-b33a-9b552b229f18">

<img width="1206" alt="image" src="https://github.com/Vanessa219/vditor/assets/39148461/bf47f1a5-4973-4512-ba24-cdd55a73b415">

**Comment by Vanessa219** [comment]
你应该提错项目了。

**Comment by wmkai** [comment]
emm我应该没找错地方呀，这里不是vscode的typora插件吗

**Comment by Vanessa219** [comment]
这里是  vditor 项目

**Comment by wmkai** [comment]
不好意思，感谢提醒
