### ISSUE TITLE
对options.preview.hljs的linenumber设置时,会导致复制按钮消失掉

### ISSUE THREAD

**Issue by qingtang1003** [Vanessa219/vditor#1601]
### 编辑模式
默认编辑模式

### 描述问题

如题,是不是因为这样参数设置  hljs: {lineNumber: true, style: 'ant-design'} 会导致默认的renderMenu失效掉?
那renderMenu该怎么设置文档里面也没有说明清楚
顺便问一下hljs.style能不能传入自定义的主题

### 版本信息

* 版本：    "vditor": "^3.10.2"
* 操作系统：macos
* 浏览器：chrome

**Comment by Vanessa219** [comment]
`renderMenu(code: HTMLElement, copy: HTMLElement)` 使用参数添加自定义的元素和事件
