### ISSUE TITLE
vditor@3.10.3 mermaid 不起作用，流程图、甘特图、甘特图无法渲染

### ISSUE THREAD

**Issue by ponysb** [Vanessa219/vditor#1602]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

v3.10.3 mermaid 不起作用，流程图、甘特图、甘特图无法渲染，同样的代码3.10.1没问题，3.10.2我没有测试

````````markdown
复制的官方代码确定没有问题
```mermaid
graph TB
    c1-->a2
    subgraph one
    a1-->a2
    end
    subgraph two
    b1-->b2
    end
    subgraph three
    c1-->c2
    end
```
````````

### 版本信息

* 版本：v3.10.3
* 操作系统：win
* 浏览器：edge\chrome

**Comment by Vanessa219** [comment]
我这里是正常的，看看有没有报错信息

<img width="1068" alt="image" src="https://github.com/Vanessa219/vditor/assets/970828/b50503d1-674d-471c-b11c-dd865b810bfa">
