### ISSUE TITLE
cdn使用相对地址/相对协议时css被重复加载

### ISSUE THREAD

**Issue by lz6060788** [Vanessa219/vditor#1606]
### 编辑模式

任何模式

### 描述问题

由于在内网环境访问不到cdn，于是我把cdn资源搬到了我的nuxt服务上，因此设置的cdn地址为相对地址。
此时引入代码高亮主题的js在判断link元素的href前后一致时有误。
```javascript
const vditorHljsStyle = document.getElementById("vditorHljsStyle") as HTMLLinkElement;
const href = `${cdn}/dist/js/highlight.js/styles/${style}.css`;
// .href将获取到dom的完整地址，.getAttribute('href')才能够获取到相对地址，与href变量计算一致。
if (vditorHljsStyle && vditorHljsStyle.href !== href) {
    vditorHljsStyle.remove();
}
```

### 期待的结果

支持相对地址/相对协议

### 截屏或录像

![image](https://github.com/Vanessa219/vditor/assets/98386138/f2b1b3cd-1018-4b42-8232-08a931de39d7)
![image](https://github.com/Vanessa219/vditor/assets/98386138/5c8edbac-e784-4171-ba1d-0718663e394d)

### 版本信息

* 版本：3.9.1
* 操作系统：windows 10
* 浏览器：chrome 123.0.6312.106

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/pull/1607
