### ISSUE TITLE
工具栏选择主题图标+文字，显示方式重复，只需要图标就行

### ISSUE THREAD

**Issue by bosunrunner** [Vanessa219/vditor#1608]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

上方工具栏选择主题图标+文字，显示方式重复，只需要图标就行，或者支持自定义即可

### 期待的结果
上方工具栏支持自定义，或者选择主题文字+图标，去掉文字，保留图标即可

### 版本信息

* 版本：VsCode Office Viewer(Markdown Editor)  v3.3.2
* 操作系统：Windows 
* 浏览器：

**Comment by Vanessa219** [comment]
具体指的是哪里？这里么？
<img width="376" alt="image" src="https://github.com/Vanessa219/vditor/assets/970828/8caabfd2-59f5-4c65-9880-f9516c6732cd">
