### ISSUE TITLE
你好，支持自定义字数统计吗

### ISSUE THREAD

**Issue by dengsong666** [Vanessa219/vditor#1613]
自带的字数统计，底层似乎是str.length，表情的统计不准，支持自定义统计吗?

**Comment by tenglongwentian** [comment]
举个例子？

**Comment by dengsong666** [comment]
> 举个例子？

比如表情的长度在js中可能会按2到3个字符算，甚至更长，但我想把它当成一个字符，还有图片链接之类的，我想仅计算`![我是图片](https://xxx/123.jpg)`4个字符，但Vditor也把url算上了，不过这似乎不是必须的，我也不需要精确统计，就这样吧
