### ISSUE TITLE
尖括号`<>`中的英文会被识别为html标签渲染，导致渲染结果看不到尖括号中的内容

### ISSUE THREAD

**Issue by sizexl** [Vanessa219/vditor#1618]
### 编辑模式

* `sv` 分屏编辑预览模式

### 描述问题

分屏预览模式下，或编辑器的preview()方法，最终输出的html会将尖括号中的英文转换成html标签
````````markdown
您可以参考如下方法配置交换机的ssh登陆功能：

# 通过Console口登录设备，进入系统视图，并开启Telnet服务。
<Sysname> system-view
[Sysname] ssh server enable
# 设置通过VTY用户线登录设备使用用户名+密码的认证方式。
````````

### 期待的结果

如果`<>`中匹配到非html关键字，按原文输出
### 截屏或录像

![image](https://github.com/Vanessa219/vditor/assets/14197558/73c11422-220b-47db-8e47-ecfeabe997b7)
![image](https://github.com/Vanessa219/vditor/assets/14197558/121b0e45-83f4-481d-bf70-021952fa29c5)

### 版本信息

* 版本：v3.9.5
* 操作系统：Windows 10 21H1
* 浏览器：chrome 124.0.6367.78

**Comment by 88250** [comment]
这是 Markdown 语法特性，建议使用转义 `\<`。
