### ISSUE TITLE
中文标题删除

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#162]
1. `tab`, `tab`, `backspace, `backspace`
![tab1](https://user-images.githubusercontent.com/15811943/75078330-f5ab6980-54ca-11ea-9ed1-aa8f47c6ec82.gif)

2. `backspace` before `compositonend` at korean character.(is it similar to chinese character?)
![hangul](https://user-images.githubusercontent.com/15811943/75078654-c812f000-54cb-11ea-905d-e0c3acb91800.gif)

3. I applied my site.   every `tab is working good but only tab at list, task is different (it is going to `enter`)
![mysite](https://user-images.githubusercontent.com/15811943/75079046-f93ff000-54cc-11ea-820a-e4bf53326577.gif)

**Comment by Vanessa219** [comment]
1. It's a code block, do you have a good suggestion.
3. pls set options.tab

**Comment by jakekwak** [comment]
I think no processing when backspace.  When I changed from `tab: '\t'` to `tab: '    '`(4 spaces), it is ok.

**Comment by Vanessa219** [comment]
3. can you reproduce in demo use `tab: '\t'`?

**Comment by jakekwak** [comment]
demo is ok,  but i think some kind of conflict of my CMS code.
