### ISSUE TITLE
不支持单个 $ 包围多行公式左对齐. 两个 $$ 包围多行公式又得居中显示比较麻烦.

### ISSUE THREAD

**Issue by zhuwenzhuang** [Vanessa219/vditor#1620]
不支持单个 $ 包围多行公式左对齐. 两个 $$ 包围多行公式又得居中显示比较麻烦.

比如

$\begin{align*}\label{2}
&\empty_b = \\
& AB
\end{align*}$

实际需要下面这么写才行

$$
\begin{align*}
\empty_b =& \\
 = &AB
\end{align*}
\hspace{100cm}
$$

另外还发现了几个问题, 比如

- 在使用 office viewer 导出 markdown 为 pdf 时和原始展示的差别比较大. 比如在换行上原来的预览是换行的, pdf 中没有换行.
- 引用块中的换行, 预览是换行的, pdf 中没有换行.

**Comment by Vanessa219** [comment]
换行用 `\n` 试试。
PDF 导出使用的是浏览器自带的，升级浏览器再看看。

**Comment by zhuwenzhuang** [comment]
还有两个使用上遇到的情况:
1.不支持单个 $ 包含多行公式.
2.在使用 office viewer 还发现引用中双空格换行, 在保存时会自动去掉行末的空格, 导致引用中双空格换行部分被消除掉. (当前写了个专门加空格的脚本绕过)

**Comment by Vanessa219** [comment]
导出使用的是浏览器的，这个取决于浏览器，我们是没有办法进行修改的。
1. 这个规范上没有，所以不支持
2.  office viewer  不太了解
