### ISSUE TITLE
有时需要在vditor渲染完毕的时候触发事件，是否可以提供一个方法vditor.rendered=callback?

### ISSUE THREAD

**Issue by Wteakenji** [Vanessa219/vditor#1621]

**Comment by Vanessa219** [comment]
具体指的是？
目前有 option.input 和 option.after 回掉。

**Comment by Wteakenji** [comment]
> 具体指的是？ 目前有 option.input 和 option.after 回掉。

具体是说，当div.editor-container里面的dom都不再更改时，比方说editor.setVal(str)，str里面有数学公式，那么它渲染比较慢，有没有办法可以做到：当数学公式（或者说整个内容）完全展现出来时（即div.editor-container里面的dom都不再变动了此时）弄一个回调（触发事件）？

**Comment by Vanessa219** [comment]
数学公式没有渲染完成的回调，这个可能没有办法。

**Comment by IamException** [comment]
vditor的setValue函数是否会触发input回调

**Comment by Vanessa219** [comment]
会的
