### ISSUE TITLE
谷歌浏览器，vditor 即时渲染模式下，首行为标题，然后全选，接着中文输入，就会奔溃

### ISSUE THREAD

**Issue by lls174** [Vanessa219/vditor#1622]
![image.png](https://b3logfile.com/file/2024/05/image-pChSrVg.png)
![image.png](https://b3logfile.com/file/2024/05/image-GUZccLt.png)

然后这个在火狐浏览器上是正常的，就很神奇

**Comment by Vanessa219** [comment]
无法重现，更新浏览器试试。
