### ISSUE TITLE
似乎会自动吞掉换行用的两个空格

### ISSUE THREAD

**Issue by DuckDuckStudio** [Vanessa219/vditor#1624]
### 编辑模式

* `sv` 分屏编辑预览模式

### 描述问题

换行时会自动删掉行尾的两个空格。
重现：
1. 写一段话
2. 行尾打两个空格
3. ENTER换行

### 期待的结果

保留换行使用的两个空格，否则在某些平台可能不会换行。

### 截屏或录像

[录像](https://github.com/Vanessa219/vditor/assets/89643991/95c21925-45e2-4950-959f-30d898f367b5)

### 版本信息

* 版本：使用的是 [Demo](https://b3log.org/vditor/demo/index.html) > [完整示例](https://ld246.com/guide/markdown)
* 操作系统：Windows11
* 浏览器：edge

**Comment by Vanessa219** [comment]
鉴于 https://github.com/Vanessa219/vditor/issues/1319 ， sv 模式问题不再进行修改
