### ISSUE TITLE
如何把一键markdown文档的图片URL地址转为本地地址？

### ISSUE THREAD

**Issue by sdfvsdcw** [Vanessa219/vditor#1625]
### 你在什么场景下需要该功能？

[我把html网页一键转成了markdown格式，但是考虑到md文件中的URL有时会失效，因此想把url转成本地地址，如何一键实现？咱们的插件是否由相应的功能
![image](https://github.com/Vanessa219/vditor/assets/157508341/baaa5da8-01ec-4c5f-9ac9-b53225a93548)
![image](https://github.com/Vanessa219/vditor/assets/157508341/1a02a2a2-3c36-4360-b368-588c22696cec)

**Comment by Vanessa219** [comment]
在提交到服务器的时候，后台去解析一下吧。
