### ISSUE TITLE
引入antd css ， 编辑器内全选长文本 删除 会卡顿，如果没有引入，则很丝滑

### ISSUE THREAD

**Issue by xppcnn** [Vanessa219/vditor#1626]
import Vditor from "vditor";
import "vditor/dist/index.css";
import "antd/dist/antd.css";
const App = () => {
  const [vd, setVd] = useState<Vditor>();
  useEffect(() => {
    const vditor = new Vditor("vditor", {
      after: () => {
        vditor.setValue("`Vditor` 最小代码示例");
        setVd(vditor);
      },
    });
    // Clear the effect
    return () => {
      vd?.destroy();
      setVd(undefined);
    };
  }, []);
  return <div id="vditor" className="vditor" />;
};

export default App;

{
  "name": "vditor-react-minimal-example",
  "version": "1.0.0",
  "description": "",
  "keywords": [],
  "main": "src/index.tsx",
  "dependencies": {
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-scripts": "5.0.1",
    "vditor": "3.9.8",
    "antd": "4.10.2"
  },
  "devDependencies": {
    "@types/react": "18.2.48",
    "@types/react-dom": "18.2.18",
    "typescript": "5.3.3"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "browserslist": [">0.2%", "not dead", "not ie <= 11", "not op_mini all"]
}

**Comment by Vanessa219** [comment]
具体是哪一个样式干扰到了？不行就换其他主题试试。
