### ISSUE TITLE
链接结尾回车不应该复制到下一行

### ISSUE THREAD

**Issue by 88250** [Vanessa219/vditor#163]
![image](https://user-images.githubusercontent.com/873584/75085451-694d8500-5564-11ea-9c6f-3e6d224ee02b.png)

**Comment by Vanessa219** [comment]
无法重现，可以重现的时候再打开此 issue

**Comment by 88250** [comment]
![f](https://user-images.githubusercontent.com/873584/75088916-52bc2380-558e-11ea-9a00-3394df401062.gif)
