### ISSUE TITLE
insertValue插入文本无法正确渲染

### ISSUE THREAD

**Issue by Ellen0604** [Vanessa219/vditor#1631]
### 编辑模式

* `ir` 即时渲染模式

### 描述问题

通过insertValue插入的文本无法正确渲染，需要重新在文章末尾回车一下才会正确渲染

editor.insertValue(`**考勤管理12**- 支持三班倒制度的排班和考勤管理
- 数据收集和整合，确保准确性和完整性
- 解决跨班排班导致的数据异常问题
- 支持不同工厂和研究院的考勤管理需求
- 支持办公人员和研究人员的考勤管理需求`)

````````markdown
**考勤管理12**- 支持三班倒制度的排班和考勤管理
- 数据收集和整合，确保准确性和完整性
- 解决跨班排班导致的数据异常问题
- 支持不同工厂和研究院的考勤管理需求
- 支持办公人员和研究人员的考勤管理需求
````````

### 期待的结果

insertValue时可以立即渲染MD或者插入后有方法可以渲染MD

### 截屏或录像

![image](https://github.com/Vanessa219/vditor/assets/24667299/95c8771b-7528-40ae-b4dd-9ddae74d7ea2)

### 版本信息

* 版本："vditor": "^3.10.4"
* 操作系统：window
* 浏览器：chrome

**Comment by Vanessa219** [comment]
我这里是正常的。

https://github.com/Vanessa219/vditor/assets/970828/58a6579c-5a6a-45b5-9401-c2d0a2dcaaa6

**Comment by Ellen0604** [comment]
> .insertValue

是否跟版本有关呢

**Comment by Vanessa219** [comment]
这个最近没有动过
