### ISSUE TITLE
超大体积文件

### ISSUE THREAD

**Issue by tenglongwentian** [Vanessa219/vditor#1632]
### 你在什么场景下需要该功能？
超大体积，内容通过二进制文件流传输以及提交。

### 描述最优的解决方案 
流分片加载二进制文件流，并解析展示。

**Comment by Vanessa219** [comment]
文件过大的话加载和使用都会卡的

**Comment by tenglongwentian** [comment]
> 文件过大的话加载和使用都会卡的

试了几个，ace-editor中500W不卡顿

**Comment by Vanessa219** [comment]
这个文件有多大？

**Comment by tenglongwentian** [comment]
> 这个文件有多大？

280MB+

**Comment by tenglongwentian** [comment]
> 这个文件有多大？

500W行，每行几十个字。

**Comment by Vanessa219** [comment]
这个需要在服务端自己处理，最后拼接返回给 vditor 即可。
