### ISSUE TITLE
编辑界面，如何隐藏左边的 </> 这个符号？？

### ISSUE THREAD

**Issue by HaleyZY** [Vanessa219/vditor#1633]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式 

### 描述问题

````````markdown
编辑界面，如何隐藏左边的 </> 这个符号？？
````````

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

**Comment by Vanessa219** [comment]
没太理解，隐藏的话不要输入即可。
如果是需要转义的话可用 `\`
