### ISSUE TITLE
在及时渲染和所见及所得模式下代码块的编辑是否可以直接编辑而不是分为上下两栏

### ISSUE THREAD

**Issue by buqingyishi123** [Vanessa219/vditor#1634]
码块的编辑是否可以直接编辑而不是分为上下两栏
![image](https://github.com/Vanessa219/vditor/assets/167609119/650a0ae8-2674-402e-be65-a667f53db228)

**Comment by xygengcn** [comment]
+1，很容易操作失误

**Comment by Vanessa219** [comment]
下面是渲染的结果，不需要的话可用 css 隐藏。

**Comment by doglex** [comment]
有效， vue写法

<style scoped>
:deep(.vditor-wysiwyg__block[data-type="code-block"] .vditor-wysiwyg__pre[style="display: block;"]+.vditor-wysiwyg__preview){
	display:none;
}
:deep(.vditor-ir__node--expand[data-type="code-block"] .vditor-ir__preview) {
	display: none;
}
</style>
