### ISSUE TITLE
能否提供一个配置编辑模式的选项呢

### ISSUE THREAD

**Issue by cooperGao** [Vanessa219/vditor#1638]
### 你在什么场景下需要该功能？

在工具栏只展示编辑模式中的一种或者两种，希望edit-mode是可配置的

### 描述最优的解决方案 

类似这样：
`
edit-mode: ['wysiwyg', 'sv']
`
这个时候只编辑模式只显示所见即所得和分屏预览模式

**Comment by Vanessa219** [comment]
这个目前没有配置，但应该可以用 css 将不需要的隐藏
