### ISSUE TITLE
分屏预览模式左右同步滑动

### ISSUE THREAD

**Issue by aox7** [Vanessa219/vditor#1639]
### 你在什么场景下需要该功能？

分屏预览模式左右同步滑动

lute有什么api支持render html到源代码的行号对应吗。
比如一个解析后的代码块，我能确认它是源代码中对应的起始行和结束行吗。
SetJSRenderers只能拿到解析后的ILuteNode，直接设置lute options似乎也没有提供类似功能的api

**Comment by 88250** [comment]
抱歉，拿不到行号的。

另外，分屏预览模式后续计划重写 https://github.com/Vanessa219/vditor/issues/1319
