### ISSUE TITLE
添加 `insertMD` 方法

### ISSUE THREAD

**Issue by qiuchengw** [Vanessa219/vditor#1640]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

通过insertValue接口插入一段markdown代码，代码如下：

````````markdown
**hello**

```cpp
int main() {
    // <p style='color: red;'> hello <b>world222</b> </p>
    printf("<p style='color: red;'> hello <b>world222</b> </p>");
    return 0;
}
```

**world**
````````

### 期待的结果

code block部分的内容，应该是原样输出。结果其中的html标签都会被转换为markdown语法了。

### 截屏或录像

![ab](https://github.com/Vanessa219/vditor/assets/1762183/87637e72-96e0-47d7-a955-9af4165a8e95)

### 版本信息

* 版本：最新版本
* 操作系统： window 11 
* 浏览器：microsoft edge

### 其他信息

无

**Comment by Vanessa219** [comment]
@88250 可能是 lute 解析的问题

**Comment by Vanessa219** [comment]
由于 https://github.com/Vanessa219/vditor/issues/716 和 https://github.com/Vanessa219/vditor/issues/917 只能新添加一个方法
