### ISSUE TITLE
如何获取被选中的图片

### ISSUE THREAD

**Issue by Goldgom** [Vanessa219/vditor#1641]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

我调用getSelection获取被选中的文本，但是如果这中间有图片的话就没法正常获取到图片相关数据

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
````````

### 期待的结果

getSelection或者其他api能够正常返回被选中的图片的markdown文本

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

**Comment by Vanessa219** [comment]
range.cloneContents() 用这个
