### ISSUE TITLE
upload 插件样式不太对劲，不知道是我哪里配置的问题

### ISSUE THREAD

**Issue by kill136** [Vanessa219/vditor#1642]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

样式溢出了

<template>
  <div id="vditor" />
</template>

<script setup lang="ts">
import { ref, onMounted, defineProps } from 'vue';
import Vditor from 'vditor';
import 'vditor/dist/index.css';

// Define the props
const props = defineProps<{
  initialValue: string;
}>();

const vditor = ref<Vditor | null>(null);

onMounted(() => {
  vditor.value = new Vditor('vditor', {
    after: () => {
      // Use the prop to set the initial value
      vditor.value!.setValue(props.initialValue);
    },
  });
});
</script>

<style></style>

### 截屏或录像
![1721011258346](https://github.com/user-attachments/assets/ad66dd69-807b-4516-aa42-df8009141528)

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

**Comment by kill136** [comment]
知道问题了 ，uniapp  修改了 咱们的默认的样式

**Comment by aylitat** [comment]
> 知道问题了 ，uniapp 修改了 咱们的默认的样式

如果用uniapp做开发，如何在APP端引用vditor呢？
