### ISSUE TITLE
请问一下大佬 upload.handler这个如何使用，一直显示不了图片，没理解您发的意思

### ISSUE THREAD

**Issue by kill136** [Vanessa219/vditor#1643]
使用 upload.handler 需更新上传后地址可参考[index.ts#L76](https://github.com/Vanessa219/vditor/blob/master/src/ts/upload/index.ts#L76)，非特殊需求不建议使用。  @Vanessa  请问一下大佬 这个如何使用，一直显示不了图片，没理解您发的意思

我的代码：

<template>
	<div id="vditor" />
</template>

<script setup lang="ts">
	import { ref, onMounted, defineProps } from 'vue';
	import Vditor from 'vditor';
	import OSS from 'ali-oss';
	const chatobj = uniCloud.importObject('chatobj');
	// Define the props
	const props = defineProps<{
		initialValue : string;
	}>();

	const vditor = ref<Vditor | null>(null);
	const loadVditorCSS = () => {
		const link = document.createElement('link');
		link.rel = 'stylesheet';
		link.href = 'https://cdn.jsdelivr.net/npm/vditor/dist/index.css'; // Use a CDN to avoid local compilation
		document.head.appendChild(link);
	};
	onMounted(() => {
		loadVditorCSS();
		vditor.value = new Vditor('vditor', {
			after: () => {
				// Use the prop to set the initial value
				vditor.value!.setValue(props.initialValue);
			},

			upload: {
				url: '', // 将通过自定义方法进行上传
				handler: async (files) => {
					try {
						// 调用 getOssSTS 获取临时凭证
						const stsData = await chatobj.getossSTS();
						if (stsData.error) {
							throw new Error(stsData.error);
						}

						// 配置 OSS 客户端
						const client = new OSS({
							region: 'oss-cn-beijing',
							accessKeyId: stsData.AccessKeyId,
							accessKeySecret: stsData.AccessKeySecret,
							stsToken: stsData.SecurityToken,
							bucket: 'poducttalk'
						});

						// 上传文件
						const file = files[0];
						const result = await client.put(file.name, file);
                        genUploadedLabel(result, vditor);

						return {
							msg: '',
							code: 0,
							data: {
								errFiles: [],
								succMap: {
									[file.name]: result.url, // 使用计算属性名语法
								}
							}
						};
					} catch (error) {
						console.error(error);
						return {
							msg: error.message,
							code: 1,
							data: {}
						};
					}
				},
				fieldName: 'file' // 上传文件的字段名
			}
		});
	});
</script>

**Comment by kill136** [comment]
能否给一个handler  的demo 吗

**Comment by kill136** [comment]
已经通过修改源码 完成了，但是 我不知带如何提交PR

**Comment by heifengli001** [comment]
无需修改源码：自定义上传作者的意图就是如果存在自定义上传，则包括上传和插入都得自己去写而不是只是发请求。
所以在上传完毕后务必需要自行处理插入操作

```
  import { uploadFile } from '@/api/upload';
  import { getFileTypeByMimeType } from '@/utils/file';
// .... more options 
      upload: {
        url: '/api/upload/file',
        async handler(files: File[]) {
          const file = files[0];
//getFileTypeByMimeType 这个是我自己写的方法根据mimeType 返回文件类型，用来判断插入时的语句
          const fileType = getFileTypeByMimeType(file.type);
          if (fileType) {
             // 调用自己的api方法上传文件
            const result = await uploadFile(file);
            const url = result.data;
            if (fileType === 'image') {
              vditor.value.insertValue(`![image](${url})`);
            } else {
              vditor.value.insertValue(`[${file.name}](${url})`);
            }
            return '';
          }
          return '文件格式错误';
        },
      },
```
