### ISSUE TITLE
Support for newline at start of file

### ISSUE THREAD

**Issue by irvnriir** [Vanessa219/vditor#1645]
### 你在什么场景下需要该功能？

Working with files which don't have headings, for example:
* Notes.
* Files which are: embedded in other files, or serve as linked details.

<details><summary> list example
</summary>

![image](https://github.com/user-attachments/assets/03435069-b223-4ed9-9e51-28acd8e8f5a9)

![image](https://github.com/user-attachments/assets/0190fa0b-a8c5-41ed-ba0c-1725ae16f34d)

</details>

<details><summary> description example
</summary>

![image](https://github.com/user-attachments/assets/dff9c429-8a97-41d8-81c6-0bd74fe4aaad)

![image](https://github.com/user-attachments/assets/2455a341-0b7b-4b6b-9aac-94b3cefefa7f)

</details>

### 描述最优的解决方案 

1. When opening a file, don't delete last newline at it's top.
3. Make Enter before all such characters of a file that aren't newlines, work the same as Shift+Enter (add a single newline instead of 2).
	* 2 newlines which are entered by using Shift+Enter are already correctly converted to paragraph separator.

Some viewers and WSYIWYG editors, instead, add padding at top of the page, for example: by allowing to scroll past the text editing area. But:
* That disturbs use of such heading content that should be faded, for example: lines with system tags, and copyright messages.
	
	![image](https://github.com/user-attachments/assets/d72c4c99-1d6e-411d-a174-252ee8f13735)
	
* That isn't compatible with plain-text editors.

* The viewers, and most of the editors, ignore empty lines at start of file, so are compatible with the newline-powered padding.

**Comment by Vanessa219** [comment]
CommonMark 规范中无法渲染空行。
