### ISSUE TITLE
Handling of Enter and Shift+Enter at Details tag

### ISSUE THREAD

**Issue by irvnriir** [Vanessa219/vditor#1646]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

Can't expectedly finish `<details>` tag, nor write newlines into it's content.

### 期待的结果

The Enter and Shift+Enter, add newlines into the `<details>` block unless the cursor is located after the corresponding `</details>` tag.

### 截屏或录像

https://github.com/user-attachments/assets/0fb82284-2a63-4d18-8935-26de109a3e5f

Also. When adding 2 newlines, for example: after corresponding `</summary>` tag. The cursor, and content which follows it, exit the `<details>` block.

### 版本信息

* 版本：presumably 3.8.3 -- [vscode-office](https://github.com/cweijan/vscode-office/tree/master) 3.3.9
* 操作系统：Windows
* 浏览器：VS Code/Electron/Chromium

**Comment by Vanessa219** [comment]
这个是 CommonMark 的规范

**Comment by irvnriir** [comment]
> 这个是 CommonMark 的规范
How? This is a text input issue.

**Comment by Vanessa219** [comment]
输入内容会按照  CommonMark 的规范进行解析，解析后就是这样了。

**Comment by Vanessa219** [comment]
输入的内容全部内容都是需要进行整体解析的。
