### ISSUE TITLE
Handling for Sup tag

### ISSUE THREAD

**Issue by irvnriir** [Vanessa219/vditor#1647]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

`<sup>` tags aren't correctly rendered, and are auto-enclosed in `` ` `` when written, edited, copied or pasted.

````````markdown
<sup>1</sup>
````````

### 期待的结果

`<sup>` tags are rendered the same as in HTML, and can be written, copy-pasted and edited without being auto-enclosed in `` ` ``.

### 截屏或录像

![image](https://github.com/user-attachments/assets/ad87605f-3eeb-41d5-a493-ef68c0bbda7b)

### 版本信息

* 版本：presumably 3.8.3 -- [vscode-office](https://github.com/cweijan/vscode-office/tree/master) 3.3.9
* 操作系统：Windows
* 浏览器：VS Code/Electron/Chromium

**Comment by Vanessa219** [comment]
可以使用 `vditor.lute.SetSup(true)` 用`^` 来实现语法上标就不会出现标签了。
