### ISSUE TITLE
代码块相关，我觉得还是挺影响体验的

### ISSUE THREAD

**Issue by quanzhongxian** [Vanessa219/vditor#1649]
能不能不要出现这块内容，看着真的别扭
![image](https://github.com/user-attachments/assets/a9b89b99-ddb7-4e0c-97da-5ec96e879045)

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/1648 重复了

**Comment by quanzhongxian** [comment]
> #1648 重复了

如果代码块出现滚动条，你会发现输入中文是有问题的，还有回车的时候也有问题，并且一开始点击代码块的时候聚焦一直都是在前面，并没有根据用户点哪里就聚焦到哪里。这一部分我下载源码已经处理好了，不知道是否更新到上面

**Comment by Vanessa219** [comment]
可以先PR看一看
