### ISSUE TITLE
所见即所得模式的功能

### ISSUE THREAD

**Issue by quanzhongxian** [Vanessa219/vditor#1651]
这个东西能不能出一个配置、只有在表格的时候才显示，其它情况不显示啊，挺影响使用的，只有表格的时候才有用，其他情况，几乎用不上，还占地方
![image](https://github.com/user-attachments/assets/c2bcb682-b8ca-44e2-86ff-18f4d3ea17ab)

**Comment by Vanessa219** [comment]
这个在代码块、标题上也是需要的。
