### ISSUE TITLE
图片保存方式支持 base64保存，省的这么多图片

### ISSUE THREAD

**Issue by panhf** [Vanessa219/vditor#1654]

**Comment by tenglongwentian** [comment]
首先方案提供给你，如下所示，其次会特别卡顿，尤其是当图片体积是>=10MB，同时md类客户端暂时没有支持超大体积文本的工具（GB级别）：
toolbar[
  {
    hotkey: '',
    name: 'upload',
    tip: '插入图片',
    icon: '<span class="el-icon-picture-outline" style="font-size: 15px;"></span>',
    className: 'right'
  },
],
upload: {
                    accept: '.png,.jpg,.jpeg,.gif',
                    multiple: false,
                    max: 5 * 1024 * 1024,
                    filename (name) {
                        return name.replace(/[^(a-zA-Z0-9\u4e00-\u9fa5\.)]/g, '').replace(/[\?\\/:|<>\*\[\]\(\)\$%\{\}@~]/g, '').replace('/\\s/g', '')
                    },
                    handler (files) {
                        function callback (path) {
                            const name = files[0] && files[0].name
                            let succFileText = ''
                            if (
                                    that.contentEditor &&
                                    that.contentEditor.vditor.currentMode === 'wysiwyg'
                            ) {
                                succFileText += `\n <img alt=${ name } src="${ path }">`
                            } else {
                                succFileText += `  \n![${ name }](${ path })`
                            }
                            const command = document.execCommand("insertHTML", false, succFileText)
                            if (!command) {
                                that.contentEditor.insertValue(succFileText, true)
                            }
                        }

                        that.handleImageUpload(files, callback)
                    },
                    url (files, callback) {
                        that.handleImageUpload(files, callback)
                    }
                }



handleImageUpload (file, callback) {
            const reader = new FileReader()
            reader.onload = () => {
                const base = reader.result
                callback(base)
            }
            reader.readAsDataURL(file[0])
        },

**Comment by tenglongwentian** [comment]
@Vanessa219 V姐这个方案我记得之前出现过光标的问题。

**Comment by Vanessa219** [comment]
具体是什么问题？
