### ISSUE TITLE
任务列表功能bug

### ISSUE THREAD

**Issue by quanzhongxian** [Vanessa219/vditor#1660]
![image](https://github.com/user-attachments/assets/f10715e1-e858-40a8-8fa3-aa10d6ad4ec1)
在选择框前面输入，就会导致这样情况，我看了一下源码，是input.ts文件html = vditor.lute.SpinVditorDOM(html);这个导致的，但是因为用到vditor.lute.SpinVditorDOM方法，外部引入的方法，无法解决

**Comment by Vanessa219** [comment]
可以详细说一下么？或者是录屏

**Comment by quanzhongxian** [comment]
> 可以详细说一下么？或者是录屏

https://github.com/Vanessa219/vditor/issues/1663#issue-2457142288
