### ISSUE TITLE
编辑器所见即所得模式，空的编辑器状况下， 连续插入多个表情，然后快捷键ctrl+A全选内容，表情会自动被换行。

### ISSUE THREAD

**Issue by mlsjla** [Vanessa219/vditor#1662]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

1. 编辑器所见即所得模式，空的编辑器状况下， 连续插入多个表情，然后快捷键ctrl+A全选内容，表情会自动被换行。
2. 某些情况下，左右移动光标、或者回退删除表情，也会触发换行。

````````markdown
空的编辑器状况下， 连续插入多个表情
````````

### 截屏或录像

暂无，如需要可以提供

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

**Comment by Vanessa219** [comment]
是这样操作么？无法重现

https://github.com/user-attachments/assets/c5a36348-d3f5-481b-bb20-008b3672be7d

**Comment by mlsjla** [comment]
@Vanessa219   需要点击工具栏图标 插入表情
