### ISSUE TITLE
所见即所得模式，任务列表bug

### ISSUE THREAD

**Issue by quanzhongxian** [Vanessa219/vditor#1663]
所见即所得模式，任务列表bug，在选择框前面（任务列表前面）输入：
![Snipaste_2024-08-09_11-59-44](https://github.com/user-attachments/assets/119b84c3-77c2-4ad7-9de9-df90f86f52bf)

**Comment by Vanessa219** [comment]
这是正常的，冒号或其他符号会打断 markdown 语法 `* [ ]`
