### ISSUE TITLE
在无界微前端框架下，预览模式没有显示出来

### ISSUE THREAD

**Issue by lai397826696** [Vanessa219/vditor#1665]
### 编辑模式
* `sv` 分屏编辑预览模式

ps:   wysiwyg模式和ir模式未测试

### 描述问题

子应用：react项目， vditor组件在node_modules拷贝至public目录下，设置CDN使用，项目单独使用时正常的；
主应用：react项目，使用了wuji微前端框架，主应用中打开子应用的页面，第一次进入页面vditor组件正常，在主应用切换路由出去再切换回来，输入编辑内容后，预览模式没有显示出来，打开控制台报错：
![image](https://github.com/user-attachments/assets/45857f2f-ecca-4e97-93de-81c89fad987a)

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
````````

### 期待的结果

菜单切换出去再切换回来后，输入内容，预览模式可以正常显示

### 版本信息

* vditor：3.10.4
* 版本：node-v16.20.2
* 操作系统：win11
* 浏览器：google浏览器-v127.0.6533.120

**Comment by Vanessa219** [comment]
看上去是焦点的问题，可以看看具体是哪一行的代码么？

**Comment by lai397826696** [comment]
![image](https://github.com/user-attachments/assets/d5ee7435-f9eb-4c88-981e-3312096ed452)

**Comment by lai397826696** [comment]
![image](https://github.com/user-attachments/assets/3435a68b-825a-4ad2-b878-61a0cda97cca)

**Comment by lai397826696** [comment]
![image](https://github.com/user-attachments/assets/058950e4-a11b-4901-ba02-eafe00d6cfcf)
就在upload的success方法做了操作，目前我的猜测，子应用里插件获取的window，不是主应用的window

**Comment by Vanessa219** [comment]
具体还需要单步调试一下，在一楼里没有看到相关的上传操作，应该和上传没有关系。
