### ISSUE TITLE
ir 模式下标题删除报错

### ISSUE THREAD

**Issue by ixiumu** [Vanessa219/vditor#1666]
1. ir 编辑模式
将光标移动到标题的 `#` 前面
依次按下 `enter`  >  `up`  >  `backspace`
错误 `index.min.js:1 Uncaught DOMException: Failed to execute 'setStart' on 'Range': The offset 4294967295 is invalid.`

2. toolbar 中 如果没有 emoji 键盘无法选择代码块语言 up down 会切换其他行 esc 可以正常隐藏弹出的语言选择菜单

**Comment by Vanessa219** [comment]
第二个问题是这样操作么？

https://github.com/user-attachments/assets/a174b9d1-c07b-4d04-a44b-16f521dc87c0
