### ISSUE TITLE
内容替换问题

### ISSUE THREAD

**Issue by fox1730** [Vanessa219/vditor#1667]
![image.png](https://b3logfile.com/file/2024/08/image-sxZkFNs.png)

选择内容  输入内容请求后端获取数据  后替换选择的内容 如何实现呢  现在因为点击输入框 导致编辑器焦点丢失 会导致选择的内容丢失 无法进行替换 大佬们 这个如何解决

**Comment by Vanessa219** [comment]
看看这个 `cloneRange` 行不行
