### ISSUE TITLE
能否增加完全本地的cdn加载选项

### ISSUE THREAD

**Issue by filusilia** [Vanessa219/vditor#1669]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

esm支持不太好，
vue3的示例文档现在也无法查看

npm已经更新到3.10.5了，但是当前的release仍然是3.10.4

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
````````

### 期待的结果

能否增加完全本地加载的设置，取消掉cdn，自建electron软件时加载外部地址默认情况下是会报错的，而且有完全断网的需求

### 截屏或录像

![send加载](https://github.com/user-attachments/assets/3aca920a-53b4-4daa-ad1b-a05720047b12)
![image](https://github.com/user-attachments/assets/1049ba07-79f0-4ac3-a036-8f97dab78c1c)

### 版本信息

* 版本：3.10.5
* 操作系统：win
* 浏览器：electron31

**Comment by ixiumu** [comment]
我也遇到这个错误了 在iframe沙盒中加载和electron 都可以触发这个错误 
先说结论 设置了cdn为本地是完全断网的

ant.js是工具栏图标 
我猜本意应该是体积较大 想按需加载 于是发了一个同源的xmlhttp请求
但是开发环境下浏览器因为安全策略拦截了
发布的时候不会有这个错误

你也可以自己找到代码处 改成fetch请求就可以了

**Comment by quanzhongxian** [comment]
本地可以啊

**Comment by quanzhongxian** [comment]
我也是看源码，才知道这样写，你们按照自己的路径参考一下，不用谢，我是雷锋
![image](https://github.com/user-attachments/assets/d1630f85-be8f-4632-9e8e-3dd2b5bb42ff)

**Comment by Vanessa219** [comment]
选项设置为空即可 `cdn: ''`

**Comment by filusilia** [comment]
我的解决方案是下载下来js引用一下，cdn的引用会报错，但是不影响接下来的功能
