### ISSUE TITLE
filename没有按期望处理掉空格，然后再上传

### ISSUE THREAD

**Issue by onefawn** [Vanessa219/vditor#1670]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 源代码
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FastAPI + Vditor</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vditor/dist/index.css" />
    <script src="https://cdn.jsdelivr.net/npm/vditor/dist/index.min.js"></script>
</head>
<body>
    <div id="vditor"></div>
    <script>
        const vditor = new Vditor('vditor', {
            height: 360,
            upload: {
                url: 'http://localhost:8000/upload/',
                multiple: true,
                fieldName: 'files',
                max: 10 * 1024 * 1024,
                filename: name => {
                    // eslint-disable-next-line no-console
                    console.log('Original filename:', name);
                    const processedName = name.replace(/\s/g, '');
                    // eslint-disable-next-line no-console
                    console.log('Processed filename:', processedName);
                    return processedName;
                  },
                format: (files, msg, xhr) => {
                    const response = JSON.parse(msg);
                    const imgMarkdown = response.filenames.map(filename => `![${filename}](uploads/${filename})`).join('\n');   
                    vditor.insertValue(imgMarkdown);
                    return imgMarkdown;
                }
            }
        });
    </script>
</body>
</html>

### 描述问题

上传pig-new - 副本 - 副本.png文件，filename没有按期望处理掉空格，然后再上传。但是上传中的信息仍旧未变
------WebKitFormBoundaryWHkh1efbcSOBqtFI
Content-Disposition: form-data; name="files"; filename="pig-new - 副本 - 副本.png"
Content-Type: image/png

------WebKitFormBoundaryWHkh1efbcSOBqtFI--

### 期待的结果

filename可以把文件名中的空格去掉后，再上传。

### 截屏或录像
![image](https://github.com/user-attachments/assets/591093d8-1970-440b-8e10-b2bda4f450a6)

### 版本信息

* 版本：3.10.5
* 操作系统：windows 11
* 浏览器：edge

**Comment by Vanessa219** [comment]
这个可以在返回值中自己进行处理。
