### ISSUE TITLE
希望支持setCursorPosition、insertElement的能力

### ISSUE THREAD

**Issue by mengjian-github** [Vanessa219/vditor#1671]
### 你在什么场景下需要该功能？

想要实现类似于代码编辑那样的inlineSuggestion的能力，对写作的帮助会很大

现在缺乏这两个API，可以更改光标位置，支持插入任意HTML元素，就可以实现这个能力了

**Comment by Vanessa219** [comment]
插入内容实用 `insertValue` ，修改光标需要自己使用原生的 `Range` 即可。
