### ISSUE TITLE
ir及wysiwyg模式下部分html标签渲染问题

### ISSUE THREAD

**Issue by intblank** [Vanessa219/vditor#1674]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式

### 描述问题

部分html标签分屏模式下可以渲染，ir及wysiwyg不能渲染

````````markdown
<font color="#E6A23">**需要满足气象条件**</font>

<span style="color: blue;">这是蓝色文字</span>

**<font color="red">**这是红色文字**</font>** **<br>** **<span style="color: blue;">**这是蓝色文字**</span>** **<br>**
````````

### 期待的结果

即时渲染和所见即所得也能正常渲染

### 截屏或录像

![image](https://github.com/user-attachments/assets/21b90953-498d-4452-b862-b24e0ebebdc6)
![image](https://github.com/user-attachments/assets/42d6b999-96f0-469d-8ec2-7350b65824d5)
![image](https://github.com/user-attachments/assets/ae7d93a6-ee6c-497b-88d9-24816603dc30)

### 版本信息

* 版本：3.10.6
* 操作系统：windows11
* 浏览器：chrome

**Comment by Vanessa219** [comment]
点击预览都是正常的，在 wysiswyg 和 ir 模式下是渲染为 html 标签，因此不显示颜色。
