### ISSUE TITLE
不支持导入md文件，复制粘贴过来后_前面多了\，代码块也会被分割成多块，加粗也不能正常显示

### ISSUE THREAD

**Issue by Masterfans** [Vanessa219/vditor#1675]

**Comment by Masterfans** [comment]
测试后发现是从vscode中复制了带有” ``` “ 标记的代码，代码块就会出现类似的情况，比如我直接从md原文中复制了带格式的稳定就会出现
例如复制了下面的带有格式的文本
![image](https://github.com/user-attachments/assets/77544d38-b35a-4522-9a40-ef960e530f89)
粘贴到官网demo中就会出现下面情况
![image](https://github.com/user-attachments/assets/28f6af3c-e251-4cdd-8479-94fa168c0aec)


```
```
    axk_mqtt_client_config_t mqtt_cfg = {
        .uri = "ws://broker.emqx.io:8083/mqtt",
        .event_handle = event_cb,

        //指定客户端名称
        .client_id = "axk mqtt",
        //设置服务器证书文件
        // .cert_pem = CA_CRT,
        // .cert_len = strlen(CA_CRT) + 1,
        // .username = "wb2",
        // .password = "wb2",
        
        //客户端证书
        // .client_cert_pem = CLIENT_CA,
        // .client_key_pem = CLIENT_KEY,

        
    };

    axk_mqtt_client_handle_t client = axk_mqtt_client_init(&mqtt_cfg);
    axk_mqtt_client_start(client);
```
```

**Comment by Masterfans** [comment]
粘贴到评论里面github里面会正确解析，可以试着从vscode里面复制看看会不会复现

**Comment by Vanessa219** [comment]
可以使用 ctrl+shift+V
