### ISSUE TITLE
除了分栏显示的状态下，获取选中内容，图片和格式会丢失

### ISSUE THREAD

**Issue by ic-xu** [Vanessa219/vditor#1677]
### 你在什么场景下需要该功能？

在编辑器中选中一段文本，这段文本包含图片还有其他 markdown 的内容，但是返回的只有文本内容；我希望获取选中内容的时候，返回包含图片的 markdown 文本。

获取选中内容进行二次渲染时，图片还有格式会丢失

### 描述最优的解决方案 

- 新增一个返回选中部分的 markdown 原文的方法

**Comment by Vanessa219** [comment]
是这样操作么？

https://github.com/user-attachments/assets/526de99f-1695-420a-b0da-5eed4c0cfa85
