### ISSUE TITLE
dark模式下字体颜色没有跟随

### ISSUE THREAD

**Issue by 172724542** [Vanessa219/vditor#1681]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

````````markdown
在dark模式下字体样式没有跟随改变
````````

### 期待的结果

![Weixin Screenshot_20240923111137](https://github.com/user-attachments/assets/ac80be12-c9ab-4c3c-85ab-34dedd2e6d8e)

### 截屏或录像
![Weixin Screenshot_20240923110708](https://github.com/user-attachments/assets/34c8264c-496c-4a9f-ae1a-f8f7cb00a0fb)

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

### 其他信息
将类vditor-reset的color改为var(--textarea-text-color);即可

**Comment by Vanessa219** [comment]
参见 demo

![QQ_1727189817569](https://github.com/user-attachments/assets/fd8e1aef-6561-4ccc-92af-5036f4b1ddc1)
