### ISSUE TITLE
dark模式下table底色

### ISSUE THREAD

**Issue by 172724542** [Vanessa219/vditor#1682]
### 你在什么场景下需要该功能？

在dark模式下，table使用默认的白色底色会导致视觉疲惫

### 描述最优的解决方案 

将table的background删掉，只需要使用默认的背景色即可

**Comment by Vanessa219** [comment]
对比一下 demo
![QQ_1727145364870](https://github.com/user-attachments/assets/ad5c7c48-c374-4d36-af49-eb69c9534f17)
