### ISSUE TITLE
支持化学物质结构渲染

### ISSUE THREAD

**Issue by night-nl** [Vanessa219/vditor#1683]
### 你在什么场景下需要该功能？

学化学的，记笔记
### markdown原文
```smiles
C1=CC=CC=C1-C(=O)C2=CC=CC=C2
```
### 描述最优的解决方案 
这里应该渲染出一个分子的化学式
![图片](https://github.com/user-attachments/assets/83dacc2c-ec98-48c0-a621-94afe34aabf2)

集成SMILES语言支持

**Comment by Vanessa219** [comment]
5ed8c285d379d132950f8411af32c4c8f2c8ac0c
