### ISSUE TITLE
使用了VditorPreview 进行渲染，渲染时间太长

### ISSUE THREAD

**Issue by liukkm** [Vanessa219/vditor#1684]
![image](https://github.com/user-attachments/assets/c9a5ebd0-2ac1-4fa8-82cb-1feb59270b9a)
如图所示 我只使用了 VditorPreview， 但是渲染页面（在没有图表的情况下）的时候 一个预览器就渲染了 8000多ms，
![image](https://github.com/user-attachments/assets/4db9ef94-f94b-4aa1-9123-afb5e79eac7a)

```
mounted() {
    this.$nextTick(async () => {
      this.$nextTick(async () => {
        const el = document.getElementById('markdown-' + this.id)
        
        console.time()
        let html = await VditorPreview.md2html(this.content, {
            cdn: 'https://unpkg.com/vditor@3.10.2'
          })
        if (el) {
          el.innerHTML = html
          VditorPreview.chartRender(el)
          this.isShow  =true
          console.timeEnd()
        }
      })
    })
  },
```

### 期待的结果

可以快速进行渲染

### 版本信息

* 版本：3.10.6
* 操作系统：macos
* 浏览器：Google

**Comment by liukkm** [comment]
可以判定的是： md2html 耗时过长

**Comment by quanzhongxian** [comment]
> https://unpkg.com/vditor@3.10.2

应该是你使用了cdn:https://unpkg.com/vditor@3.10.2慢

**Comment by liukkm** [comment]
> > https://unpkg.com/vditor@3.10.2
> 
> 应该是你使用了cdn:[https://unpkg.com/vditor@3.10.2慢](https://unpkg.com/vditor@3.10.2%E6%85%A2)

这个有解决方案吗？

**Comment by quanzhongxian** [comment]
> > > https://unpkg.com/vditor@3.10.2
> > 
> > 
> > 应该是你使用了cdn:[https://unpkg.com/vditor@3.10.2慢](https://unpkg.com/vditor@3.10.2%E6%85%A2)
> 
> 这个有解决方案吗？

改为本地的呗，或者cdn置为空字符串看看

**Comment by quanzhongxian** [comment]
> > > https://unpkg.com/vditor@3.10.2
> > 
> > 
> > 应该是你使用了cdn:[https://unpkg.com/vditor@3.10.2慢](https://unpkg.com/vditor@3.10.2%E6%85%A2)
> 
> 这个有解决方案吗？

[看看这个](https://github.com/Vanessa219/vditor/issues/1669)

**Comment by Vanessa219** [comment]
我先关闭了，有其他问题继续留言。
