### ISSUE TITLE
vditor-panel支持自定义吗？

### ISSUE THREAD

**Issue by ueiheng** [Vanessa219/vditor#1687]
### 你在什么场景下需要该功能？

需要在panel弹出层加入其他自定义功能

**Comment by Vanessa219** [comment]
vditor-panel 这一个类在多个地方用到，你具体指的是？

**Comment by ueiheng** [comment]
所见即所得的Popup 弹出层

**Comment by ueiheng** [comment]
我需要在即时渲染模式下，也要有这个popup，应该怎么操作

**Comment by ueiheng** [comment]
> vditor-panel 这一个类在多个地方用到，你具体指的是？

<img width="182" alt="image" src="https://github.com/user-attachments/assets/84338e34-7531-421f-a44c-6cad51ba480f">

**Comment by ueiheng** [comment]
请问这个弹出层如何在ir即时渲染模式下使用？
