### ISSUE TITLE
五线谱渐强减弱无法显示

### ISSUE THREAD

**Issue by will-mei** [Vanessa219/vditor#169]
在 [这里](https://paulrosen.github.io/abcjs/visual/classes.html#test-tune)是可以正常显示的, 但是 veditor 里渐强和渐弱符号却没法显示, 你可以用下面的代码来复现这个问题.
```
%abc-2.1
X:1
M:4/4
L:1/8
K:C
!<(! DE EF GA AB !<)! | !>(! BA AG FE ED !>)! || 
!crescendo(! DE EF GA AB !crescendo)! | !diminuendo(! BA AG FE ED !diminuendo)! || 
```
这里的最后两行用了分别测试了两种写法, 但是veditor都不能获得正确的结果.

**Comment by Vanessa219** [comment]
弱弱的问一句渐强和渐弱符号长啥样？

**Comment by will-mei** [comment]
> 是这个不显示么？
> ![image](https://user-images.githubusercontent.com/970828/75113296-9181d480-5687-11ea-9081-84b40bc828fa.png)

你看的哪里的结果, 你这个是abcjs 给出的测试页面的效果吧. 在 Veditor 的教程页面 https://hacpai.com/guide/markdown 里测试, 还有下面这个页面 
https://hacpai.com/article/1582457438130

好像并得不到正确的结果...

**Comment by will-mei** [comment]
体谅你们开发的辛苦, 但是希望你们能看清反馈的描述, 把项目越做越好, 谢谢了

**Comment by 88250** [comment]
感谢反馈，我们会继续努力的。

**Comment by Vanessa219** [comment]
> > 是这个不显示么？
> > ![image](https://user-images.githubusercontent.com/970828/75113296-9181d480-5687-11ea-9081-84b40bc828fa.png)
> 
> 你看的哪里的结果, 你这个是abcjs 给出的测试页面的效果吧. 在 Veditor 的教程页面 https://hacpai.com/guide/markdown 里测试, 还有下面这个页面
> https://hacpai.com/article/1582457438130
> 
> 好像并得不到正确的结果...

这个已经修复，只是还没有发布，具体可以看代码提交记录

![image](https://user-images.githubusercontent.com/970828/75124761-2d452c00-56ec-11ea-8620-d036397d44c4.png)

和 CHANGELOG.md

![image](https://user-images.githubusercontent.com/970828/75124774-42ba5600-56ec-11ea-8d89-fe71d37ec1b7.png)
