### ISSUE TITLE
当使用tab缩进后，在删除尾部内容就会变成代码，怎么实现首行缩进呢？

### ISSUE THREAD

**Issue by liutt1312** [Vanessa219/vditor#1700]
![image](https://github.com/user-attachments/assets/a8a36625-d7c2-488b-802a-7fed7470e5e5)

**Comment by Vanessa219** [comment]
markdown 的规范就是这样的，支持不了。

**Comment by wuzheng228** [comment]
![image](https://github.com/user-attachments/assets/32fc190c-e724-4e08-a7ca-2637482fc899)
链滴社区 评论的 Tab缩进怎么实现的

**Comment by Vanessa219** [comment]
tab 以后输入就不在了。
