### ISSUE TITLE
<u></u>在wysiwyg模式下不显示下划线，怎么解决

### ISSUE THREAD

**Issue by bjcaizh** [Vanessa219/vditor#1704]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
````````

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

**Comment by Vanessa219** [comment]
这个需要点击预览才可以看到。
