### ISSUE TITLE
ir模式下有代码块，撤销内容时代码块内容会乱

### ISSUE THREAD

**Issue by xhmygt** [Vanessa219/vditor#1709]
### 描述问题

ir模式下，输入代码块后撤销输入，代码块会乱
正常输入后：
![image](https://github.com/user-attachments/assets/faa96ad7-a5ea-4478-96e2-23a2120e8ef7)
撤销后变成：
![image](https://github.com/user-attachments/assets/7259836a-7866-44f5-ad19-9f4604020645)

### 截屏或录像

https://github.com/user-attachments/assets/761fe7f7-2f6c-4888-913d-221ac101d9f6

### 版本信息

* 版本：3.10.7
* 操作系统：macos
* 浏览器：chrome 130.0.6723.70（正式版本） (arm64)

**Comment by xhmygt** [comment]
3.10.1版本没有出现这个问题

**Comment by Vanessa219** [comment]
乱指的是代码块出现2次么？这是正常的，代码块上面是输入，下面是颜色高亮的预览。

**Comment by xhmygt** [comment]
不是上下展示两块的问题
正常代码块输入后展示是这样的
![image](https://github.com/user-attachments/assets/126e94b5-c5c8-4c9c-bcea-b519bec9a6bf)
md格式的内容是：
'```java\npublic static void main(String[] args) {\n  \n    }\n```\n'
但是撤销后就变成：
![image](https://github.com/user-attachments/assets/bb226fe5-498a-4f1f-b215-888bb7370a2d)
md格式的内容是：'```java\n\n```java\n\n\n```\n'

**Comment by xhmygt** [comment]
> 乱指的是代码块出现2次么？这是正常的，代码块上面是输入，下面是颜色高亮的预览。
跟https://github.com/Vanessa219/vditor/issues/1706
这个提的问题很像，

**Comment by Vanessa219** [comment]
这个已经解决了，可以更新到最新版本看看，或者等待发布。
