### ISSUE TITLE
Escaping Pipe (|) Characters in Tables

### ISSUE THREAD

**Issue by datgausaigon** [Vanessa219/vditor#1711]
### 描述问题

Hi, 

Sorry I don't know Chinese `yet`...

I can't find a way to add pipe (|) in Table at the moment.

Can you add this feature?
According to markdownguide.org they use HTML character code (&#124;).

https://www.markdownguide.org/extended-syntax/#:~:text=You%20can%20display%20a%20pipe,(%20%7C%20).

```
Escaping Pipe Characters in Tables
You can display a pipe (|) character in a table by using its HTML character code (&#124;).
```

### 版本信息

* 版本：v3.10.7
* 操作系统：macOS 15.1
* 浏览器：FireFox 133.0b3 (64-bit)

Thanks 
🐻

**Comment by Vanessa219** [comment]
You can solve this by typing `\|`

**Comment by datgausaigon** [comment]
Hi @Vanessa219 
It's work like a charm.
Thanks
🐻
