### ISSUE TITLE
vditor3.10.7 github 下载下来的源码，build 报错

### ISSUE THREAD

**Issue by lotoze** [Vanessa219/vditor#1712]
![image](https://github.com/user-attachments/assets/82011897-7357-447a-b5f5-af1704d2c090)
看其他的Issues说需要 pnpm install ，试了不好使，实在不知道啥原因，大神救命！

**Comment by Vanessa219** [comment]
看上去好像是 eslint 的问题，使用项目的配置，不要用 IDE 的。
