### ISSUE TITLE
当文本过长时，增加自动滚动到最新内容的API

### ISSUE THREAD

**Issue by devount** [Vanessa219/vditor#1714]
### 你在什么场景下需要该功能？

仅将vditor当做一个markdown的渲染器，输出流式文本到vditor时，当文本过长，超过预设的vditor高度后，会出现滚动条，但不能再代码里设置自动滚动。

### 描述最优的解决方案 

提供对滚动条的操作API，使其自动定位到最新内容上，并在手动滚动时，关闭此功能

**Comment by Vanessa219** [comment]
这个可以自己用 js 操作滚动条。

**Comment by devount** [comment]
您好，我已收到您的邮件，我会尽快处理。

**Comment by devount** [comment]
> 这个可以自己用 js 操作滚动条。

我尝试用js操作进度条，我将vditor绑定到了一个id为robot的div上，并尝试直接操作这个div的scrollTop属性，但是我失败了，vditor并没有按照预期的工作，确切的说是没有任何反应。以下是我的代码：
function autoScroll(vditorDivID) {
            console.log(vditorDivID);
            const chatMessages=document.getElementById("chat-messages")
            //window.scrollTo(0, document.body.scrollHeight);
            chatMessages.scrollTop = chatMessages.scrollHeight;//外层的滚动正常工作
            //vditor绑定的div的dom对象
            const vditorDIV = document.getElementById(vditorDivID);           
            vditorDIV.scrollTop = vditorDIV.scrollHeight;//内层的div滚动不工作

        } 
请问，我应该用js操作哪个对象的进度条？

**Comment by Vanessa219** [comment]
debugger 调试了看看吧

**Comment by devount** [comment]
您好，我已收到您的邮件，我会尽快处理。

**Comment by devount** [comment]
您好，我已收到您的邮件，我会尽快处理。
