### ISSUE TITLE
移动端代码块里粘贴多行文本，只会保留第一行

### ISSUE THREAD

**Issue by Yu-Core** [Vanessa219/vditor#1719]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式

### 描述问题

移动端，在代码块里粘贴多行文本，只会保留第一行

### 截屏或录像

https://github.com/user-attachments/assets/fdd9c974-9891-433e-b39a-27a6f21bdf60

### 版本信息

* 版本：3.10.7
* 操作系统：Android 11
* 浏览器：Chrome 130.0.6723.58

### 其他信息
wysiwyg、ir都存在这个问题
sv模式下是吞掉换行符

**Comment by Vanessa219** [comment]
无法重现

https://github.com/user-attachments/assets/030ff2f4-28d3-445a-b86f-543605fc687e

**Comment by Yu-Core** [comment]
感谢。原来是输入法的原因。讯飞输入法有这个问题，搜狗输入法或者讯飞输入法小米版是正常的。
