### ISSUE TITLE
bold and italic

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#172]
second line
`ctrl+b`, `test and `, `ctrl+i`, `test`, `ctrl+i`, `ctrl+b`, ` test`
![bold_underline2](https://user-images.githubusercontent.com/15811943/75121475-e9094b80-5659-11ea-9779-e110db744a33.gif)

**Comment by jakekwak** [comment]
still problem.
line 1: underline after last test.  \*\*test and \_test\_\*\* test
line 2: removing the space when `ctrl+i`

**Comment by Vanessa219** [comment]
@88250 
1. **test and _test_** test error
2. throw error
```
vditor.lute.VditorDOM2Md(`<strong data-marker="**">test and <em data-marker="_">test</em></strong> test`)
```
error
