### ISSUE TITLE
代码块主题预览失效

### ISSUE THREAD

**Issue by raisetwist** [Vanessa219/vditor#1722]
1. Vditor有一个预览各种代码主题的按钮，现在那个里面调用的url好像是旧版的格式（没有min），导致多数主题出现网络错误，希望修复成正确的地址
2. 设置defaultLang之后，在指定语言的代码块也会当成defaultLang高亮，是不是||两边的顺序反了
谢谢！

**Comment by Vanessa219** [comment]
按照以下进行设置后，defaultLang 这个重现不了，你的参数和具体表现是？
```
 preview: {
            markdown: {
                toc: true,
                mark: true,
                footnotes: true,
                autoSpace: true,
            },
            math: {
                engine: 'KaTeX',
                inlineDigit: true,
            },
            hljs: {
                defaultLang:"js"
            }
        },
```

**Comment by raisetwist** [comment]
就这个参数也会有问题，可以试一下开一个语言为python的代码块，然后比较一下两种语言的注释如：
````
```python
# let this be a python comment
// this is a javascript comment
```
````
我这里第二行会是注释的颜色，第一行不是，let this还会被高亮

**Comment by Vanessa219** [comment]
是这样么？

https://github.com/user-attachments/assets/e93596c5-e8e1-4d9f-bb31-984c4fba3614

**Comment by raisetwist** [comment]
奇怪，我这边(3.10.7)会两个block都当成默认的js，你那好像两个都当成了python，但反正都不是正常行为……

https://github.com/user-attachments/assets/acb99740-89be-414b-92fa-4d0c7a43e1c6
