### ISSUE TITLE
任务列表下无法新增普通列表

### ISSUE THREAD

**Issue by leihenshang** [Vanessa219/vditor#1724]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式

### 描述问题

在已有的任务列表下，使用 markdown 语法无法新增普通列表
操作步骤：
1. 先创建一个任务列表
2. 回车到下一行，删除任务列表
3. 按下tab键增加空行，然后使用 `-+空格`的列表标记
4. 出现无法添加的问题，可以看图

### 期待的结果

任务列表下可以新增普通列表

### 截屏或录像

![20241203_175116](https://github.com/user-attachments/assets/e4e13863-d0dd-40c7-97a5-35a7d77e3a4d)

### 版本信息

* 版本： 3.10.7
* 操作系统： win11 64bit
* 浏览器： EDGE 131.0.2903.70

**Comment by Vanessa219** [comment]
这样操作

https://github.com/user-attachments/assets/5dfdf467-0b20-490f-b1cd-18ef10402b8f
