### ISSUE TITLE
lists start with 1) and enter error

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#173]
`shift-tab` is ok but `enter` is not ok
![list_alt](https://user-images.githubusercontent.com/15811943/75121708-27a00580-565c-11ea-91c1-f0305e273301.gif)

**Comment by Vanessa219** [comment]
Thank you, there are too many details and I forgot to deal with it.

**Comment by jakekwak** [comment]
II'd like to make a little perfect editor before business trip.  
thank you for fixing everyday.

**Comment by 88250** [comment]
Thank you for your patience and careful testing 👍

**Comment by jakekwak** [comment]
still at multi level.
![Screen Shot 2020-02-24 at 4 16 54 AM](https://user-images.githubusercontent.com/15811943/75144475-a0cf4500-56bc-11ea-84b4-68b043ae9f51.png)
