### ISSUE TITLE
列表删除内容后，键入-或=出现错误

### ISSUE THREAD

**Issue by ycodingall** [Vanessa219/vditor#1732]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式

### 描述问题

所见即所得，以及即时渲染模式下，使用有序列表或者无序列表的时候，使用退格键删除输入的内容，直到本行的无序列表的小圆点消失，但是不删除本行，此时按 “-” 或者 “=”，会将上一行的文本变为标题

### 期待的结果

删除掉小圆点，也能正常输入文本

### 截屏或录像
![image](https://github.com/user-attachments/assets/58714829-d04c-4f95-8dc6-f979afc13bca)
![image](https://github.com/user-attachments/assets/65e6b6c8-7162-4a48-ae2d-b0eb005bdfd8)
![image](https://github.com/user-attachments/assets/194c602e-2fe9-4992-a1cf-c6cc01c1b9a0)

### 版本信息

* 版本：3.10.5
* 操作系统：windows/mac
* 浏览器：chrome

**Comment by Vanessa219** [comment]
这个是 commanMark 的规范。

**Comment by ycodingall** [comment]
这更像是识别错误，列表行删除至空，输入“-”导致上述现象，会添加分割线加粗文本
![image](https://github.com/user-attachments/assets/7d8d086b-b24d-4e54-b86d-00ea71b84d42)
切换至分屏预览，显示的内容也不正确。
![image](https://github.com/user-attachments/assets/2fd3fbcd-6e79-4c83-a87b-5cdfc4c2dc79)
再次切换模式
![image](https://github.com/user-attachments/assets/fbad97eb-b908-4bc2-b9c1-334c90a64db3)

现象有点神奇，请问应该如何避免这种情况？

**Comment by Vanessa219** [comment]
@88250 看一下应该是解析的问题

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/1737
