### ISSUE TITLE
Vscode插件即时渲染模式下，<u></u>等命令会被解析为code，无法使用html等。

### ISSUE THREAD

**Issue by CYx-HHH** [Vanessa219/vditor#1734]
### 编辑模式

* `ir` 即时渲染模式

### 描述问题

Vscode插件Typora中的即时渲染，md的标签`<bold>` `</bold>`会被自动解析为代码块。
````````markdown
<i>xieti italic </i>
会变成
`<i>` xieti italic `</i>`
````````

### 期待的结果
<i>xieti italic </i>

### 截屏或录像
<img width="488" alt="微信图片_20241213162150" src="https://github.com/user-attachments/assets/ad43d15f-4775-4299-b1ca-125bb218aec9" />

### 版本信息

* 版本：vscode Typora     
    Published: 2021-06-02, 15:27:40
   Last released: 2024-12-13, 15:36:56

* 操作系统：win11
* 浏览器：无

**Comment by Vanessa219** [comment]
这是被解析为 html 块，是正常的。预览就可以看到斜体了。

**Comment by CYx-HHH** [comment]
> 这是被解析为 html 块，是正常的。预览就可以看到斜体了。

是在即时渲染模式下编辑的html，预览会变成`<i>` `</i>` 代码块。
在编辑模式下写html标签，只要ctrl alt e到即时渲染后，html都会被识别成代码块

**Comment by Vanessa219** [comment]
预览的时候标签会按照浏览器进行解析，看上去是正常的，`ctrl alt e` 是？

![image](https://github.com/user-attachments/assets/9b89428b-a705-4365-a957-b12aab2f71c2)
