### ISSUE TITLE
复制公式，自动变成了代码

### ISSUE THREAD

**Issue by mlsjla** [Vanessa219/vditor#174]
从其他页面代码块，复制以下公式，自动变成了代码。
估计是因为自动解析html到mark语法所致。
建议可视化编辑的时候，如果是代码块， 向上、向下、插入旁边增加个“去掉代码块”

```
$$\sum_{i=0}^n i^2=\frac{(n^2+n)(2n+1)}{6}$$
```

比如复制上面代码块，我希望编辑器内显示公司，但是缺仍然显示代码块。。。搞得很郁闷

<img width="484" alt="aaa123" src="https://user-images.githubusercontent.com/9654331/75127525-92a01980-56fa-11ea-8919-73a4ebd7674e.png">

**Comment by mlsjla** [comment]
<img width="484" alt="aaa123" src="https://user-images.githubusercontent.com/9654331/75127554-b5323280-56fa-11ea-9ab9-6d4b29aa7656.png">

**Comment by 88250** [comment]
亲，右键“粘贴为纯文本”即可：

![image](https://user-images.githubusercontent.com/873584/75127779-f840d580-56fb-11ea-8201-892ea3191e3d.png)
