### ISSUE TITLE
List+blockquote

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#176]
problem:
![list+blockquote](https://user-images.githubusercontent.com/15811943/75181840-ba947a80-5704-11ea-9adf-72ca7d6c68b6.gif)

![list+hr](https://user-images.githubusercontent.com/15811943/75181869-cc761d80-5704-11ea-8658-2cea346a7a10.gif)

expected:
![list+blockquote1](https://user-images.githubusercontent.com/15811943/75181887-d1d36800-5704-11ea-9f33-1477482fa6e7.gif)

**Comment by jakekwak** [comment]
`ctrl+l`, `test`, `shift+enter`, `ctrl+.`
![Feb-25-2020 05-49-49](https://user-images.githubusercontent.com/15811943/75245170-ccbcfa00-5792-11ea-8eff-8c04337f6d13.gif)

Is it correct? `shift+enter` instead of `enter`.
`ctrl+l`, `test`, `shift+enter`, `>`, `test`, `enter`, `backspace`, `shift+enter`, 
`test`, `enter`, `backspace`, `ctrl+shift+.`, `ctrl+shift+.`
![Feb-25-2020 05-50-32](https://user-images.githubusercontent.com/15811943/75245176-d0e91780-5792-11ea-8850-6bcc6fcaf784.gif)

**Comment by Vanessa219** [comment]
I think it's ok, it's better than using blockquote for the wrapping list

`shift+enter` is different from enter
`enter` will generate a tag p, `ctrl+shift+.` change the block element to blockquote. `shift+enter` is a tag p, and can not insert blockquote.

**Comment by jakekwak** [comment]
Ok.
Which one is right? 
`ctrl+l`, `test`, `shift+enter`, `ctrl+.`
![blockquote inside list](https://user-images.githubusercontent.com/15811943/75280079-62c44500-57d2-11ea-891d-81fa641d14a3.PNG)
or
![blockquote inside list1](https://user-images.githubusercontent.com/15811943/75280088-6788f900-57d2-11ea-9284-fb0d6c69d085.PNG)

I expected like when `ctrl+shift+.`
![blockquote inside list2](https://user-images.githubusercontent.com/15811943/75280608-5d1b2f00-57d3-11ea-9359-e755254c4d3b.PNG)


and the event.key at mac is `.`  but `>` at windows.
![event](https://user-images.githubusercontent.com/15811943/75280274-c189be80-57d2-11ea-9b73-235d27377305.PNG)

**Comment by Vanessa219** [comment]
blockquote is a block element, `shift + enter` cannot create a new block element, and therefore cannot create a new blockquote.
It is recommended that you press `shift+enter`, `shift+enter`, `ctrl+.`

thanks for your reminder

**Comment by Vanessa219** [comment]
windows can not support `ctrl+>`, maybe change hotkey 😢

**Comment by jakekwak** [comment]
use both like
```
(blockElement && isCtrl(event) && event.shiftKey && (event.key === "." || event.key === ">"))
```

**Comment by Vanessa219** [comment]
Thanks, I have refactored it to `ctrl+:` and `ctrl+shift+:`
