### ISSUE TITLE
GFM Example 19, 40, 57 - shift+enter, four space rule from issue #157

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#179]
https://github.github.com/gfm/#example-19

Foo
    ***

![Example19](https://user-images.githubusercontent.com/15811943/75264335-e3744880-57b4-11ea-9d0d-0aabfe11454c.gif)

foo
    # bar

![Example40](https://user-images.githubusercontent.com/15811943/75264342-e66f3900-57b4-11ea-8340-82ff985e5b1f.gif)

foo
    ----

foo
    ----
![Example57](https://user-images.githubusercontent.com/15811943/75264613-4960d000-57b5-11ea-8739-37196326b786.gif)

**Comment by 88250** [comment]
Thanks for classifying them, more clear now :+1:

**Comment by 88250** [comment]
The example 57 is a parser's bug, which has been fixed in Lute. The indent space examples should be trimmed while rendering. @Vanessa219
