### ISSUE TITLE
GFM Example52,54 - Setex 支持

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#181]
Example 52 https://github.github.com/gfm/#example-52
```
  Foo *bar
baz*→
====
```
not converted
![wrong1](https://user-images.githubusercontent.com/15811943/75278458-8639c080-57cf-11ea-9b4c-133a97d4f823.PNG)

Example54 https://github.github.com/gfm/#example-54

Automatically converted
![wrong2](https://user-images.githubusercontent.com/15811943/75278461-88038400-57cf-11ea-9138-0b4da08424d1.PNG)

**Comment by 88250** [comment]
We improved it, if you find any problems, please continuing comment.
