### ISSUE TITLE
HTML Popup for high end user?

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#183]
I think this issue is almost last one at editing. If I have more time, I try to test the compatibility(firefox, Mac etc).

* I found a `div` popup for richer text.   If possible, could you fix the problem inside heading, list, check etc?
![div](https://user-images.githubusercontent.com/15811943/75373520-13dce500-5890-11ea-92fa-0f3034f3538e.gif)

**Comment by 88250** [comment]
Firstly, thank you for spending a lot of valuable time helping Vditor become better! Vditor is a long-term project (I think it will accomplish my whole life), we can improve it all the time.

Back to the problem, it depends on CommonMark parsing rules of "Inline HTML" and "HTML Block": in Heading and List block-like elements will render different although the same input HTML content.

I close this issue, continuing comment if you find other problems, thanks.

**Comment by jakekwak** [comment]
thank you.
I made the CMS site include Vditor.  

I am debugging #162-3 issue currently.

If you have time, just visit my site (https://docker.apachezone.com/bbs/write.php?bo_table=test)
`ctrl+l`, `test`, `enter`, `tab` .

**Comment by jakekwak** [comment]
@88250  #162-3 issues,  same problem when `ctrl+shift+I`.

Could you add more debugging feature. (log level #1, 2, 3, 4 higher level means more detail logging)?

**Comment by 88250** [comment]
This is my test on your site: 

![f](https://user-images.githubusercontent.com/873584/75412397-49033900-595d-11ea-95f2-36ea19428040.gif)

Debugging log is using `console.log` at present, I think it works well. If you want to debug it, just add it to where you want to debug, for example, the keymap binding part. The Vditor frontend is charged by @Vanessa219, she is sorting out keymap now.

**Comment by jakekwak** [comment]
I found a problem.
Due to some delays, the `preventDefault ()` function does not completely delete the existing keys and seems to cause malfunctions.

at highlightToolbar.ts
put `preventDefault()` at end of `indent` and `outdent`.
```
    afterRenderEvent(vditor);
    highlightToolbar(vditor);
    event.preventDefault();
```

Even if do this, there is a malfunction very often.
Thanks.

**Comment by Vanessa219** [comment]
pls update it and try again.
src/ts/wysiwyg/processKeydown.ts 540
```
                if (event.shiftKey) {
                    vditor.wysiwyg.popover.querySelector('button[data-type="outdent"]').dispatchEvent(new CustomEvent('click'))
                    // (vditor.wysiwyg.popover.querySelector('button[data-type="outdent"]') as HTMLElement).click();
                } else {
                    vditor.wysiwyg.popover.querySelector('button[data-type="indent"]').dispatchEvent(new CustomEvent('click'))
                    // (vditor.wysiwyg.popover.querySelector('button[data-type="indent"]') as HTMLElement).click();
                }
```
