### ISSUE TITLE
korean character composition at mac chrome

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#188]
**korean character composition at mac chrome**

![Feb-27-2020 09-42-53](https://user-images.githubusercontent.com/15811943/75460822-8bba1680-5947-11ea-8a46-d7997a8c2694.gif)

pls change the subject.

**Comment by Vanessa219** [comment]
Chinese: press `enter`/`space` and then `tab` 
Does Korean need to press `enter`/`space`?

**Comment by jakekwak** [comment]
Mac Chrome
![Screen Shot 2020-02-28 at 5 41 47 AM](https://user-images.githubusercontent.com/15811943/75546043-5d8f1200-59ed-11ea-87d7-4d66af20f580.png)

Mac Firefox(OK)
![Screen Shot 2020-02-28 at 5 42 19 AM](https://user-images.githubusercontent.com/15811943/75546086-6ed81e80-59ed-11ea-8857-9b19a3c217c1.png)

keyboard events(chrome)
![Screen Shot 2020-02-28 at 5 30 56 AM](https://user-images.githubusercontent.com/15811943/75546121-80b9c180-59ed-11ea-915f-e9c0eef4352f.png)

keyboard events(firefox)
![Screen Shot 2020-02-28 at 5 50 09 AM](https://user-images.githubusercontent.com/15811943/75546562-60d6cd80-59ee-11ea-9750-2193138e9a86.png)

**Comment by Vanessa219** [comment]
Which one should I choose?
![image](https://user-images.githubusercontent.com/970828/75552236-d4b9ba00-5a70-11ea-9b68-14143ccb0464.png)

**Comment by jakekwak** [comment]
use `2-Set` 
`ctrl+b`, `xptmxm`, `ctrl+b`  
thanks

**Comment by Vanessa219** [comment]
2.2.11 is right?

**Comment by jakekwak** [comment]
have to press the end key twice.
![Feb-28-2020 11-14-26](https://user-images.githubusercontent.com/15811943/75569874-9219c280-5a1b-11ea-9e2f-701556ef9070.gif)

**Comment by Vanessa219** [comment]
Korean seems to need a Space or Enter to trigger compositionend, as well as in textarea.
In the browser, I don't know how to trigger compositionend, so trigger it before the hotkey.
