### ISSUE TITLE
heading at first time(windows firefox)

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#199]
1. wrong cursor location at first time
2. no placeholder message when backspace
3. wrong heading input location. 
![firefox05](https://user-images.githubusercontent.com/15811943/75847691-80cb1000-5da5-11ea-8043-5a3fdfab3a89.gif)

**Comment by Vanessa219** [comment]
1 is a Firefox bug and I cannot find a solution

**Comment by jakekwak** [comment]
I think first, third one are fixed at version 2.2.15

**Comment by Vanessa219** [comment]
OK, I close the issue
