### ISSUE TITLE
table (windows firefox)

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#201]
1. left and right key at no text
2. cursor location is little high when tab
3. up and down key is not same the chrome
![firefox06](https://user-images.githubusercontent.com/15811943/75848289-63974100-5da7-11ea-8690-90a3b9bfd244.gif)

**Comment by Vanessa219** [comment]
1 and 3 is firefox feature

**Comment by jakekwak** [comment]
I think this one is problem when I added the row and column.
![18](https://user-images.githubusercontent.com/15811943/75893418-64a48e80-5df8-11ea-8a1f-144ed891c108.PNG)
1. when press `ctrl+m`, <br> inside <td>
![19](https://user-images.githubusercontent.com/15811943/75893925-193eb000-5df9-11ea-9ab7-166613cabc79.PNG)

2. after start typing
![20](https://user-images.githubusercontent.com/15811943/75894088-560aa700-5df9-11ea-8014-b4a3d6bbd55d.PNG)

3. added row and column
![21](https://user-images.githubusercontent.com/15811943/75894217-85211880-5df9-11ea-9f19-4e7736d0d388.PNG)

**Comment by Vanessa219** [comment]
I can not find the online demo...

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/commit/4b9d6eca85b98d8745c5077a8d510fd598dbb186
