### ISSUE TITLE
when cache:false, use cache

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#203]
![22](https://user-images.githubusercontent.com/15811943/75936133-e8856780-5e46-11ea-9b50-9bb77006df40.PNG)

**Comment by Vanessa219** [comment]
It's ok, see index.html 46:17

**Comment by jakekwak** [comment]
when delete `***` like `<div id="vditor"></div>`
![23](https://user-images.githubusercontent.com/15811943/75945758-c3055780-5e60-11ea-8221-75f462eedf3a.PNG)

**Comment by Vanessa219** [comment]
remove it will
