### ISSUE TITLE
Which one is correct?

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#204]
chrome
![chrome07](https://user-images.githubusercontent.com/15811943/75936353-80835100-5e47-11ea-9542-77646c21ec8a.gif)

firefox
![firefox07](https://user-images.githubusercontent.com/15811943/75936361-85e09b80-5e47-11ea-9546-f22fcca37ccc.gif)

**Comment by Vanessa219** [comment]
It's Firefox bug: 

1. can not delete hr
2. when empty, can not enter

**Comment by Vanessa219** [comment]
hr in Firefox move to https://github.com/Vanessa219/vditor/issues/208
This issue is more complicated and will be resolved later.
