### ISSUE TITLE
combined blockquote and lists tab (windows firefox)

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#206]
![firefox08](https://user-images.githubusercontent.com/15811943/75937550-d73e5a00-5e4a-11ea-8b3f-809285afc85c.gif)

**Comment by jakekwak** [comment]
still problem at firefox.

**Comment by Vanessa219** [comment]
release info at CHANGELOG.md

![image](https://user-images.githubusercontent.com/970828/75975314-3d8eaf80-5f13-11ea-815b-aab50d20eb08.png)

**Comment by jakekwak** [comment]
need `tab` processing?
![Screen Shot 2020-03-05 at 5 04 49 AM](https://user-images.githubusercontent.com/15811943/75975936-0aaad400-5e9f-11ea-9508-9b16d5628b5f.png)

**Comment by Vanessa219** [comment]
why? this wysiwyg

**Comment by jakekwak** [comment]
I think we don't need this feature. but have to process the `tab` key. 
![tab](https://user-images.githubusercontent.com/15811943/75987036-cb877d80-5eb4-11ea-9540-f8dc4c85ddb7.gif)
