### ISSUE TITLE
hr in Firefox

### ISSUE THREAD

**Issue by Vanessa219** [Vanessa219/vditor#208]

**Comment by jakekwak** [comment]
when delete
![Screen Shot 2020-03-29 at 12 13 35 AM](https://user-images.githubusercontent.com/15811943/77840955-5e34d880-7152-11ea-90aa-7b19a86f1e4c.png)

chrome (no \<br>)

![Screen Shot 2020-03-29 at 12 12 52 AM](https://user-images.githubusercontent.com/15811943/77840957-642ab980-7152-11ea-9d53-9741801af8e9.png)

firefox with \<br>

![Screen Shot 2020-03-29 at 12 12 10 AM](https://user-images.githubusercontent.com/15811943/77840959-6725aa00-7152-11ea-9d51-9ade8594acdb.png)

**Comment by jakekwak** [comment]
another difference.
same node but different offset.

Chrome
![Screen Shot 2020-03-29 at 5 14 35 PM](https://user-images.githubusercontent.com/15811943/77862443-05f8e780-71e1-11ea-88d2-aec8e330fac2.png)

firefox
![Screen Shot 2020-03-29 at 5 15 00 PM](https://user-images.githubusercontent.com/15811943/77862450-0e512280-71e1-11ea-97bc-fb1816591470.png)

**Comment by jakekwak** [comment]
[suggestion] IR mode.
![ir0](https://user-images.githubusercontent.com/15811943/78046285-95ff7400-733c-11ea-966c-02ceaaf79c62.gif)

**Comment by Vanessa219** [comment]
Sorry, I can not  understand.

**Comment by jakekwak** [comment]
to delete the HR by step by step  at IR mode.

**Comment by Vanessa219** [comment]
remove these, can not input
```
heading
---
```

**Comment by jakekwak** [comment]
@Vanessa219 at IR mode only
wait until `three ---` at lute.

![Screen Shot 2020-04-04 at 5 51 14 AM](https://user-images.githubusercontent.com/15811943/78425160-7c11aa00-7638-11ea-9527-dca4cd2f9c6e.png)

like
![Apr-04-2020 05-55-46](https://user-images.githubusercontent.com/15811943/78425403-00642d00-7639-11ea-9487-dd14b715ecc7.gif)

**Comment by Vanessa219** [comment]
try it again

**Comment by jakekwak** [comment]
at wysiwyg mode
@88250 Please implement the above markdown block at `lute? 
I think this one is better than modifying vditor code.
![ir29](https://user-images.githubusercontent.com/15811943/78459306-ad609900-767d-11ea-8f37-35fd4766d9c1.gif)
