### ISSUE TITLE
希望添加快捷键自定义和离线版本

### ISSUE THREAD

**Issue by Stars-One** [Vanessa219/vditor#21]
用着很舒服，想要有个离线版本的

**Comment by Vanessa219** [comment]
快捷键自定义参见 https://hacpai.com/article/1549638745630#toc_h4_11
离线版本参见 https://hacpai.com/article/1549638745630#toc_h3_24

**Comment by Stars-One** [comment]
有没有封装好的那种exe包？没学过node.js开发..

**Comment by Vanessa219** [comment]
可参见 https://hacpai.com/article/1549638745630#toc_h3_6

你可以完整的阅读一下文档

**Comment by Vanessa219** [comment]
没问题我先关了，有事可以文档下留言
