### ISSUE TITLE
links with korean character(windows chrome & firefox)

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#210]
`alt+enter` is not working before compositionend.
![구글](https://user-images.githubusercontent.com/15811943/75974892-2e6d1a80-5e9d-11ea-9c43-2cf8ab43cff3.gif)

**Comment by Vanessa219** [comment]
![QQ20200305-194012](https://user-images.githubusercontent.com/970828/75978294-28b51a80-5f19-11ea-8e9e-1a02b67608df.gif)

**Comment by jakekwak** [comment]
Mac is ok but windows has the problem both chrome and firefox.

**Comment by jakekwak** [comment]
Chrome at Mac is OK. but when this three line comments out,  chrome at windows is ok.
please make event.isComposing && MAC
```
        if (event.isComposing) {
            return;
        }
```

![22](https://user-images.githubusercontent.com/15811943/77601348-81545380-6ed8-11ea-8123-a769572d879f.PNG)
