### ISSUE TITLE
Heading when backspace (Windows Firefox)

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#211]
![heading+bold](https://user-images.githubusercontent.com/15811943/76005862-3e065680-5ed1-11ea-9d5c-2d28e7a59781.gif)

**Comment by Vanessa219** [comment]
same as https://github.com/Vanessa219/vditor/issues/199 third point.

https://github.com/Vanessa219/vditor/issues/199#issuecomment-594472105

**Comment by jakekwak** [comment]
firefox setting
![26](https://user-images.githubusercontent.com/15811943/77801385-c3030c80-7046-11ea-9494-36c0baa8f12d.PNG)

starting firefox.(clear everything), working good only first time.
![ir14](https://user-images.githubusercontent.com/15811943/77801451-df06ae00-7046-11ea-9fbc-eda0f7c746fd.gif)

one more character returned (firefox: 9).  I think it include `\n`
![ff1](https://user-images.githubusercontent.com/15811943/77801539-11b0a680-7047-11ea-8fbf-64cd897ac145.PNG)

Chrome
![chrome1](https://user-images.githubusercontent.com/15811943/77801620-3442bf80-7047-11ea-8081-1fc5650c2779.PNG)
