### ISSUE TITLE
Sync XMLHttpRequest Deprecation message

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#212]
1. Synchronous XMLHttpRequest
2. DevTools SourceMap
![24](https://user-images.githubusercontent.com/15811943/76009464-dce18180-5ed6-11ea-9bc4-ff1cb1932fc6.PNG)

**Comment by Vanessa219** [comment]
1. This is dependent on lute.js, so it can be used after synchronization.
2. We haven't used jquery-migrate.

**Comment by jakekwak** [comment]
Jquery-migrate is my CMS.  that one is no warning.  warning at Devtools and XMLHttpRequest

**Comment by jakekwak** [comment]
FYI
async await 
https://www.freecodecamp.org/news/javascript-from-callbacks-to-async-await-1cc090ddad99/

**Comment by Vanessa219** [comment]
If I use async/await, I have to change xxxRender, md2html.ts and  their related calls to Promise, and the related API will change to Promise. So, we need another solution.

**Comment by jakekwak** [comment]
Thanks
