### ISSUE TITLE
lists when last enter

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#215]
![lists1](https://user-images.githubusercontent.com/15811943/76365413-43aad480-62f5-11ea-96b3-5ab37dc3b485.gif)
![lists2](https://user-images.githubusercontent.com/15811943/76365418-45749800-62f5-11ea-9d46-f01e2816d2ef.gif)

**Comment by Vanessa219** [comment]
Can not reproduce, pls give more details.

**Comment by jakekwak** [comment]
chrome and firefox at windows.
