### ISSUE TITLE
所见即所得模式下，insertValue渲染*和~的时候似乎不是很正确

### ISSUE THREAD

**Issue by csfwff** [Vanessa219/vditor#218]
键盘输入`**测试`后，使用`insertValue('*',true)`后，`测试`没有变成斜体，而是生成了无序列表，但是如果全部用键盘输入就没有问题，`~`同理，没有生成删除线

**Comment by Vanessa219** [comment]
insertValue 方法仅修改了需要插入的内容，没有联系上下文，因此导致单独的 `*` 即转为列表。
这可能需要修改以下
