### ISSUE TITLE
when delete the inline-code, one more delete key

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#219]
![inline-code](https://user-images.githubusercontent.com/15811943/76646393-e008ed00-6528-11ea-8419-e3a3348ba315.gif)

**Comment by Vanessa219** [comment]
Due to the nature of the browser, this is the only way to allow users to choose to input in the bold or out of the bold

**Comment by Vanessa219** [comment]
If you have a good method, please reopen it.
