### ISSUE TITLE
输入复选框时出现乱码

### ISSUE THREAD

**Issue by Kmeyel** [Vanessa219/vditor#221]
![image](https://user-images.githubusercontent.com/43575500/76705365-80723380-671a-11ea-8207-a2179bd908d1.png)

输入"  - [ ]  " --会自动填充为--> "  - [ ] ��]  "

**Comment by Kmeyel** [comment]
感谢开发者及时修复。

**Comment by 88250** [comment]
不用客气，这是我们应该做的 :joy:
