### ISSUE TITLE
Vulnerable to Self-XSS

### ISSUE THREAD

**Issue by NateScarlet** [Vanessa219/vditor#226]
https://en.wikipedia.org/wiki/Self-XSS
![image](https://user-images.githubusercontent.com/21083014/77040931-eb11c080-69f3-11ea-8164-96cb302f9f24.png)

I tried tui.editor and stackedit, they will auto sanitize such input

**Comment by 88250** [comment]
感谢反馈，确实存在安全隐患，后续会进行修复。

**Comment by jakekwak** [comment]
option for `HTML` like `HyperMD`
`html: true or false`
![27](https://user-images.githubusercontent.com/15811943/78165178-8cdfd700-7410-11ea-90c3-6312ed9f8ca8.PNG)

**Comment by NateScarlet** [comment]
Rather than turn off html completely, I prefer sanitize html with a whitelist (use library like [DomPurify](https://github.com/cure53/DOMPurify) or [xss](https://github.com/leizongmin/js-xss))

**Comment by 88250** [comment]
We will fix this issue in recent releases, thank you all. The main implementation will [be done in Lute](https://github.com/88250/lute/issues/51).

**Comment by jakekwak** [comment]
![16](https://user-images.githubusercontent.com/15811943/79034149-8f150480-7b79-11ea-9bb1-0ba195259ff0.gif)

**Comment by 88250** [comment]
Oh, it's a new issue not related with XSS fix. I created a new issue to resolve it.
