### ISSUE TITLE
涂鸦板&图片裁剪功能

### ISSUE THREAD

**Issue by lhlyu** [Vanessa219/vditor#234]
1. 文件导入导出
2. 涂鸦或者画图板
3. 搜索 替换
4. 表格自定义(弹出一个框，可以调表格列和行，文字对齐方式，单元格可以填写内容，然后点击插入)
5. 图片可裁剪
6. 插入当前时间
7. 目录

**Comment by Vanessa219** [comment]
1. 使用接口或者 链滴笔记
2. 可否提供一个 md 示例
3. 这个可以有
4. wysiwyg 模式可以直接调整
5. 这个可以有
6. 这个的用意是？
7. 使用 [toc] 即可插入目录

**Comment by lhlyu** [comment]
@Vanessa219 这里有个[例子](https://xkeditor.ixk.me/)，可以添加涂鸦

**Comment by 88250** [comment]
> 6. 插入当前时间

这个似乎不是很常用，有的输入法也可以很方便输入当前时间，所以暂时不考虑了。

**Comment by lhlyu** [comment]
@88250 OK，只是想自定义时间格式，并非必要功能

**Comment by 88250** [comment]
感谢反馈，特性暂时延后考虑，现在还在实现其他必要的基础功能。

**Comment by 88250** [comment]
1. 导出功能现已实现，支持导出 PDF、HTML、Markdown
2. 暂不考虑
3. 可关注 https://github.com/Vanessa219/vditor/issues/317
4. 所见即所得模式已经支持
5. 可关注 https://github.com/Vanessa219/vditor/issues/366
6. 暂不考虑
7. 已经支持大纲
