### ISSUE TITLE
工具栏图标出现错位的情况

### ISSUE THREAD

**Issue by Sakura0408** [Vanessa219/vditor#236]
![image](https://user-images.githubusercontent.com/42940527/77656829-67397480-6faf-11ea-91dd-a54a69b133ba.png)
如图，其他图标位置douzhengch都正常，只有这个上传图标错位。
我尝试在浏览器控制台内指定其行内样式position为absolute后位置正常，只指定这一个图标的行内样式，如果修改css，把图标的定位全部改为absolute时，就会出现下面这种情况。
![image](https://user-images.githubusercontent.com/42940527/77657142-d616cd80-6faf-11ea-95b4-f7659870ab5e.png)

**Comment by Vanessa219** [comment]
你看一下 https://hacpai.com/guide/markdown 这个上面会错位么？
如果不会的话请复查一下是否被该页面的 CSS 重置了？

**Comment by Sakura0408** [comment]
找到原因了，是因为从父元素继承的line-height属性导致的。谢谢。

**Comment by Sakura0408** [comment]
> 你看一下 https://hacpai.com/guide/markdown 这个上面会错位么？
> 如果不会的话请复查一下是否被该页面的 CSS 重置了？
找到原因了，是因为从父元素继承的line-height属性导致的。谢谢。

**Comment by Sakura0408** [comment]
> 你看一下 https://hacpai.com/guide/markdown 这个上面会错位么？
> 如果不会的话请复查一下是否被该页面的 CSS 重置了？

找到原因了，是因为从父元素继承的line-height属性导致的。谢谢。
