### ISSUE TITLE
代码块支持自定义主题(highlight.js中多个主题可选择）

### ISSUE THREAD

**Issue by hectorwill** [Vanessa219/vditor#237]
代码块支持自定义主题吗？

像highlight.js中多个主题可选择，可以通过配置来根据个人需求设置
😄

**Comment by hectorwill** [comment]
解决了，开始没看清文档

**Comment by codingcn** [comment]
@hectorwill 你是使用的`highlight.js`的主题还是用的vditor指定的那个`Chroma`
