### ISSUE TITLE
be converted after spaces in FF

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#239]
Vditor
![ir1](https://user-images.githubusercontent.com/15811943/77670231-ea2ce180-6f53-11ea-9a90-8186ec16f18c.gif)

typora
![ir2](https://user-images.githubusercontent.com/15811943/77670249-ef8a2c00-6f53-11ea-81a2-fad2c2be4f3d.gif)

**Comment by Vanessa219** [comment]
同 #240

**Comment by jakekwak** [comment]
not working at windows firefox
![ir13](https://user-images.githubusercontent.com/15811943/77790520-fc318180-7032-11ea-9d75-489bb25ede1e.gif)
