### ISSUE TITLE
multiple markdown at one line

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#240]
Vditor
![ir3](https://user-images.githubusercontent.com/15811943/77670607-72ab8200-6f54-11ea-8d96-dca9898afa10.gif)

Typora
![ir4](https://user-images.githubusercontent.com/15811943/77670623-7808cc80-6f54-11ea-9d05-9610d681b994.gif)

**Comment by 88250** [comment]
May be related to tailing spaces #239
