### ISSUE TITLE
can not delete the table with "backspace"

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#243]
![ir7](https://user-images.githubusercontent.com/15811943/77672976-90c6b180-6f57-11ea-893f-a6047bb2c14d.gif)

**Comment by jakekwak** [comment]
![ir12](https://user-images.githubusercontent.com/15811943/77765543-6420a180-700c-11ea-9e13-cc7d9a6fcf93.gif)

**Comment by jakekwak** [comment]
chrome(windows)
![ir15](https://user-images.githubusercontent.com/15811943/77840020-51ab8280-7148-11ea-8104-9e0071278730.gif)

**Comment by Vanessa219** [comment]
pls update code

**Comment by jakekwak** [comment]
Thanks
