### ISSUE TITLE
[suggestion]copy & Paste the links

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#245]
![ir8](https://user-images.githubusercontent.com/15811943/77674276-4b0ae880-6f59-11ea-9384-7522f1c0104b.gif)

**Comment by Vanessa219** [comment]
if do not want input text?

**Comment by jakekwak** [comment]
I am not sure which one is better. However, this IR mode should be easy to type on mobile.

**Comment by Vanessa219** [comment]
In this case, I will close the issue.
