### ISSUE TITLE
怎么调出分屏预览模式

### ISSUE THREAD

**Issue by hectorwill** [Vanessa219/vditor#247]
怎么调出左右两侧预览模式，像这个白色的主题：
![image](https://user-images.githubusercontent.com/35887903/77676300-1a629780-6fc9-11ea-84d0-5376db6d831c.png)

**Comment by hectorwill** [comment]
![image](https://user-images.githubusercontent.com/35887903/77681135-e6d73b80-6fcf-11ea-8259-1801fd70457b.png)
这块文档少了个edit-mode，新手小白刚入坑，完整需要到src/ts/util/Options.ts文件寻找。。。

**Comment by Vanessa219** [comment]
文档还没有更新，请稍等
