### ISSUE TITLE
支持配置是否开启 wysiwyg 模式下代码块渲染

### ISSUE THREAD

**Issue by codingcn** [Vanessa219/vditor#250]
目前在wysiwyg模式下写代码时，会在上方显示当前编辑的代码块，下方显示渲染后的代码块。这个样式问过身边的几个人，都是感觉使用起来很变扭，这可以支持修改或关闭吗，就是别把渲染前后渲染后的代码块分成两部分显示。

**Comment by 88250** [comment]
感谢反馈。

* 应该可以加个参数来配置是否需要代码块渲染
* 另外这里可以加个视觉区分
  ![image](https://user-images.githubusercontent.com/873584/77846812-43fb0900-71eb-11ea-9af4-586db3a5f4a3.png)
 
@Vanessa219
