### ISSUE TITLE
是否有支持 服务端渲染（SSR）的计划？

### ISSUE THREAD

**Issue by imjeen** [Vanessa219/vditor#254]
### 你在什么场景下需要该功能？

在服务端 [SSR  (Server-Side-Render)](https://hacpai.com/article/1521615160212) 处理  markdown 和 HTML格式转化时，转换出的结果过与浏览器初始化渲染出的字符串不一致，然而，vditor目前不支持渲染字符串。

主要处理服务端返回 或 接受 的数据。可做完接口返回客户端，并用vditor编辑。

### 描述可能的解决方案

希望有 服务端渲染（SSR） 时也能够有 markdown 和 HTML 两种格式互相转化

可以提供一个独立的文件，在服务端引用，并渲染出对应的格式。

### 描述你认为的候选方案

无

**Comment by Vanessa219** [comment]
字符串渲染可参见 https://hacpai.com/article/1549638745630#static-methods
服务端可使用 https://github.com/88250/lute
