### ISSUE TITLE
希望能添加一个支持根据 系统主题 自动切换深色/浅色模式的 主题

### ISSUE THREAD

**Issue by ydq** [Vanessa219/vditor#255]
### 你在什么场景下需要该功能？

如今随着 `Win10` 和 `MacOS` 的 **深色模式** 逐渐流行，希望 **vditor** 能支持根据系统的主题 **自动切换** 

### 描述可能的解决方案

独立一套自动变色的主题，或者允许通过 options 开启/关闭 这个功能。
使用 `@media (prefers-color-scheme: dark)` 来实现自动切换深色模式

### 描述你认为的候选方案

也可以将深模式的css文件单独打包，然后使用
~~~html
<link media="(prefers-color-scheme: dark)" rel="stylesheet" href="dark.css">
~~~
来实现自动切换的效果

### 其他信息

浏览器兼容性：https://developer.mozilla.org/zh-CN/docs/Web/CSS/@media/prefers-color-scheme

**Comment by Vanessa219** [comment]
页面中 vditor 不可能单独存在，还会有其他的元素，如果 vditor 自动切换的话会不会和其他样式产生冲突？

**Comment by ydq** [comment]
> 页面中 vditor 不可能单独存在，还会有其他的元素，如果 vditor 自动切换的话会不会和其他样式产生冲突？

期望是针对vditor的自动颜色切换不用干预其他样式，因为我个人认为哈如果有这种需求的，页面其他部分应该也会自己做过适配，只是目前vditor不支持自动根据系统的主题色来切换，所以提了这么一个”伪“需求

**Comment by Vanessa219** [comment]
其他页面做过适配的话，可以直接传入 `them` 或者调用 `setTheme` 即可。如果自动的话，页面没有适配就比较麻烦了。那我就先把这个 issue 关了。多谢。

**Comment by ydq** [comment]
@Vanessa219  V大 还是上回的问题，我还是 希望V大考虑一下 能提供一个 “auto” 的主题，实现效果如下图：
![vditor](https://user-images.githubusercontent.com/8097340/79597049-29de8780-8114-11ea-9e99-463d574fe52d.gif)


当目标页面本身已经适配了系统自动主题自适应时，当前的vditor却只能支持手动触发 **使用js去切换主题**，亦或者是 像上图一样使用很不优雅的定时器 去不停的检查当前系统主题实现动态切换，No fashion。如果vditor能添加一款原生`auto`主题使用css去适配的话感觉会更优雅一点。

---

另外，既然当前vditor提供了`vditor.setTheme('dark'/'classic')`这个方法来切换 整个vditor编辑器的主题，那么希望可以添加一个配置项，支持配置两套 highlight 的主题，然后跟随vditor主编辑器自动进行切换，比如配置：
~~~javascript
hljs:{
    style:'default Theme',
    darkStyle:'dark Theme'//（这里只是举例叫这个名字，没配置的时候默认style生效）
}
~~~
这样当手动调用了 editor.setTheme('dark')方法时，自动使用 darkStyle 的样式去渲染着色，避免和主编辑器显得割裂

**Comment by Vanessa219** [comment]
我感觉手动切换的缺点正是他的优点，让用户自主控制。
代码主题高亮这个是个好建议， https://github.com/Vanessa219/vditor/issues/323

PS：主题切换不需要定时器，可以使用
```
window.matchMedia('(prefers-color-scheme: dark)').addListener(e => {
  if (e.matches) {
    console.log('dark mode is enabled');
  } else {
    console.log('dark mode is disabled');
  }
});
```

**Comment by ydq** [comment]
> 我感觉手动切换的缺点正是他的优点，让用户自主控制。
> 代码主题高亮这个是个好建议， #323
> 
> PS：主题切换不需要定时器，可以使用
> 
> ```
> window.matchMedia('(prefers-color-scheme: dark)').addListener(e => {
>   if (e.matches) {
>     console.log('dark mode is enabled');
>   } else {
>     console.log('dark mode is disabled');
>   }
> });
> ```

哈哈 学到了，非常感谢

**Comment by ihewro** [comment]
你好，请问一下 Vditor.preview("id","content",options?)  这个`options` 里面有设置主题的吗 @Vanessa219

**Comment by Vanessa219** [comment]
请参见文档 https://hacpai.com/article/1549638745630#static-methods 中的 IPreviewOptions

**Comment by ihewro** [comment]
![image](https://user-images.githubusercontent.com/20165605/83411480-e5504680-a44a-11ea-86dd-849810032f8a.png)


> 请参见文档 https://hacpai.com/article/1549638745630#static-methods 中的 IPreviewOptions
是没有theme的设置吗 在给的demo中也没看到只渲染页面的api的theme设置

**Comment by Vanessa219** [comment]
在 markdown 里面
