### ISSUE TITLE
全屏与编辑模式来回切换会导致编辑器内容样式宽度变形

### ISSUE THREAD

**Issue by codingcn** [Vanessa219/vditor#256]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 编辑模式

请选择你遇到问题时使用的编辑模式：

* [ x] 所见即所得模式
* [x ] 即时渲染模式
* [ x] 分屏编辑预览模式

### 描述问题
复现步骤
1.进入 https://hacpai.com/guide/markdown（当前为所见即所得模式）
2.进入全屏模式（无问题）
3.切换到及时渲染模式（此时编辑器内容左边距已经错了）
4.再退出全屏模式（此时编辑器内容宽度已经严重挤压变形了）
![宽度变形](https://user-images.githubusercontent.com/16743078/78110066-f8d03880-742c-11ea-951a-6c885b4a8238.png)
### 其他信息
mac和linux操作系统，高分辨率屏幕编辑器内容变形比较明显

### 其它问题

分屏模式下，插入有序列表和无序列表回车后，不会自动插入下一个列表元素。现在是只有列表第一行会自动插入，之后的就不会了；别的很多编辑器都会支持这个操作哈。

**Comment by Vanessa219** [comment]
dev 分支已经修复，其他问题会重新提一个新的 issue 来解决

**Comment by 88250** [comment]
分屏预览模式列表项自动完成 #259
