### ISSUE TITLE
When link  with "" and ctrl+k

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#261]
comment with `"` `"`.
![ir17](https://user-images.githubusercontent.com/15811943/78164430-5a81aa00-740f-11ea-9801-0299279561d0.gif)

`crtl+k`
![ir18](https://user-images.githubusercontent.com/15811943/78164468-67060280-740f-11ea-8f49-e55b2c581cad.gif)

**Comment by lhlyu** [comment]
@jakekwak What tool did you use to make your GIF picture？

**Comment by jakekwak** [comment]
@lhlyu I'm using `screentogif portable` (https://www.screentogif.com/)

**Comment by lhlyu** [comment]
@jakekwak Thank you very much.
