### ISSUE TITLE
超链接打开新窗口

### ISSUE THREAD

**Issue by lhlyu** [Vanessa219/vditor#263]
类似这样的
```
[百度](https://www.baidu.com){:target="_blank"}
```

**Comment by Vanessa219** [comment]
这种语法我没见到过，请问一下是哪一个里面的规范或者是有哪一些编辑器在支持，或者是有其他的语法？

**Comment by lhlyu** [comment]
@Vanessa219 可能规范没有，但是我看到简书有做特殊处理,我看到的有两种
```
[超链接的名字](url?_blank)
[超链接的名字](url){:target="_blank"}
```
还有有道云笔记支持Mark和下划线
```
++下划线++
==Mark==
```

**Comment by 88250** [comment]
感谢反馈，扩展语法方面目前暂缓支持，因为还有其他更重要的任务需要做。

**Comment by jakekwak** [comment]
I suggest this method at this time. 
![10](https://user-images.githubusercontent.com/15811943/78504174-f4f42d00-7730-11ea-9b84-b13672103d7c.JPG)

**Comment by lhlyu** [comment]
@jakekwak In fact, you can press the mouse wheel to open a new window

**Comment by 88250** [comment]
暂时不打算支持了，这个语法目前几乎不通用……
