### ISSUE TITLE
table at IR mdoe

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#264]
1. some garbage after deleting the table using `ctrl+shift+-`
![ir20](https://user-images.githubusercontent.com/15811943/78253893-b9e8c400-74ba-11ea-8ef6-192636d2d851.gif)

2. If can not delete table header using `ctrl+-` at header position, stop the `zoom out`
![ir21](https://user-images.githubusercontent.com/15811943/78254191-28c61d00-74bb-11ea-8c84-f7ab3272d65e.gif)

**Comment by Vanessa219** [comment]
I think use press delete mean delete. like code block and blockquote
