### ISSUE TITLE
设置 codeBlockPreview false， esc 后代码块消失

### ISSUE THREAD

**Issue by codingcn** [Vanessa219/vditor#267]
### 编辑模式

请选择你遇到问题时使用的编辑模式：

所见即所得模式
即时渲染模式
分屏编辑预览模式

### 描述问题

新加的`VditorCodeBlockPreview`应该还是有问题的，我自己npm装的3.0.8和官方demo `https://hacpai.com/guide/markdown`出现了不同的错误
当所见即所得模式

### 复现步骤

所见即所得模式，直接手动敲入以下代码（别复制粘贴），显示就会出现异常；然后再切换到分屏模式，生成的md文本也是错误的
```
<?php
phpinfo();

### 哈哈哈
```

### 期待的结果
`VditorCodeBlockPreview`能正常使用

**Comment by Vanessa219** [comment]
代码块需要先输入
````
```
````
Markdown 语法不熟悉的话，可以使用工具栏。直接输入`<?` 会被 markdown 规范认为是 html

**Comment by codingcn** [comment]
@Vanessa219 我npm装的3.0.8，即时渲染模式没有问题；但使用所见即所得模式时，不管`codeBlockPreview`设为`true`还是`false`,通过工具栏插入代码块，输入的文本总是错位，就是文本不会被包含在代码块标签内。

比如我实际输入的是
```
alert(1);
```

但编辑器给我的结果是

alert(1);
```
```

**Comment by Vanessa219** [comment]
可以给一下具体步骤么？这里是好的呦
![QQ20200403-085814](https://user-images.githubusercontent.com/970828/78313449-5a0d1e80-7589-11ea-9bac-cc0a351a7b03.gif)

**Comment by codingcn** [comment]
@Vanessa219 
![2020-04-03 01 00 11](https://user-images.githubusercontent.com/16743078/78318719-10780000-7598-11ea-8125-291276b5f60b.gif)

**Comment by codingcn** [comment]
这是我使用的配置
```
                    width: '100%',
                    tab: '\t',
                    counter: '999999',
                    typewriterMode: true,
                    // mode: 'sv',
                    // mode: 'ir',
                    mode: 'wysiwyg',
                    preview: {
                        hljs: {
                            enable: true,
                            style: 'github',
                            lineNumber: 1
                        },
                        markdown: {
                            codeBlockPreview: false,
                        },
                        delay: 100,
                        mode: 'both',
                        show: true,
                    },
```

**Comment by Vanessa219** [comment]
要不你在 demo/static.html 这个上面试一下，我这里还是不能重现。

**Comment by codingcn** [comment]
@Vanessa219 我用`demo/static.html `尝试了下，的确不会产生这个问题，应该是我自己的失误，我再自查下，抱歉哈。

### 后面我用`static.html `时，发现了个新问题：

当`codeBlockPreview: false`且所见即所得模式，我输入一行代码，然后按下`ESC`键，代码就不会显示了，切换到分屏模式，再切换回所见即所得，代码又出现了。
