### ISSUE TITLE
Vue中有更为详细的使用方法吗，直接安装依赖之后导入会报错。

### ISSUE THREAD

**Issue by hectorwill** [Vanessa219/vditor#268]
![image](https://user-images.githubusercontent.com/35887903/78301397-96318680-756b-11ea-8b21-46b0dfa4c5fe.png)

**Comment by hectorwill** [comment]
我是用vue脚手架部署的，是不是最新的版本没有发布到npm的原因导致，还是？

**Comment by Vanessa219** [comment]
看上去是依赖不对，和 Vditor 貌似没太大关系

**Comment by hectorwill** [comment]
好哒
