### ISSUE TITLE
分屏预览支持 list-style-type CSS

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#269]
We can change `list-style-type` using
```
    ul[data-marker="*"] ul ul {
      list-style-type: square;
    }

    ul[data-marker="*"] ul {
      list-style-type: circle;
    }

    ul[data-marker="*"] {
      list-style-type: disc;
    }
    
    ul[data-marker="+"] ul ul {
      list-style-type: disc;
    }

    ul[data-marker="+"] ul {
      list-style-type: square;
    }

    ul[data-marker="+"] {
      list-style-type: circle;
    }

    ul[data-marker="-"] ul ul {
      list-style-type: circle;
    }

    ul[data-marker="-"] ul {
      list-style-type: disc;
    }

    ul[data-marker="-"] {
      list-style-type: square;
    }
```
![ir24](https://user-images.githubusercontent.com/15811943/78302795-27b7de80-7501-11ea-81b8-2be726d895f8.gif)

@88250 When you put the "data-marker="1)" at OL tag.
```
    ol[data-marker="1)"] ol ol {
      list-style-type: korean-hangul-formal;
    }

    ol[data-marker="1)"] ol {
      list-style-type: trad-chinese-informal;
    }

    ol[data-marker="1)"] {
      list-style-type: trad-chinese-formal;
    }
```
![ir23](https://user-images.githubusercontent.com/15811943/78302912-5df55e00-7501-11ea-8397-a216875a46cc.gif)

**Also need this attribute at preview mode.

**Comment by 88250** [comment]
I think the user can customize CSS for this feature, so we do not necessary to support it built-in.

**Comment by jakekwak** [comment]
@88250 Could you put  the "data-marker="1)" or "data-marker="1."at OL tag.(also at preview)
It means the user can customize CSS. thanks.

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/78314905-09e48b00-758e-11ea-97ec-91f15f6c82bc.png)

Do you mean just in split-view mode?

**Comment by jakekwak** [comment]
Yes, if  you can, but not `li`, only `OL`, `UL`

**Comment by 88250** [comment]
Thank you, I will add an option `RenderListMarker` in Lute to resolve it.

**Comment by 88250** [comment]
https://github.com/88250/lute/commit/61b190a2664f9c7548463b78cc883227f67e8525

We will include this feature in the next release.

**Comment by 88250** [comment]
该特性在 https://github.com/Vanessa219/vditor/issues/494 中有变更，请知悉。
