### ISSUE TITLE
支持类似 Typora 的即时渲染模式（保留 Markdown 标记符）

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#27]
Can you do like this ( Typora markdown editor)
![typora](https://user-images.githubusercontent.com/15811943/71553038-e8876800-29bc-11ea-92de-31a3e741c197.gif)

**Comment by 88250** [comment]
Please refer to [Vditor 所见即所得](https://hacpai.com/article/1577370404903)。

**Comment by 88250** [comment]
We will implement it in v3.

**Comment by jakekwak** [comment]
Personally I think the Wysiwyg editor should be Mobile First.
I think it supports Tiptap's menu bubble and Typora style mode support.

**Comment by 88250** [comment]
@jakekwak Thanks, we will try the best.

**Comment by jakekwak** [comment]
@88250 [suggestion] floating menu for mobile(ios and android) input at IR mode.
It is difficult to enter a special character on the smartphone. So I made a menu with only special character. but I don't know which method can be typed easily and conveniently on the smartphone. 
The below is just my idea.
menu1
![m1](https://user-images.githubusercontent.com/15811943/76710910-47659f00-66d9-11ea-81cf-89600187a19f.PNG)
menu2
![m2](https://user-images.githubusercontent.com/15811943/76710913-4df41680-66d9-11ea-81f9-d362bda5dec3.PNG)
menu3
![m3](https://user-images.githubusercontent.com/15811943/76710914-56e4e800-66d9-11ea-8bee-7477b24a5202.PNG)
menu4
![m4](https://user-images.githubusercontent.com/15811943/76710916-5d735f80-66d9-11ea-97b6-1dfb34dd53a6.PNG)
menu5
![m5](https://user-images.githubusercontent.com/15811943/76710918-65330400-66d9-11ea-9a16-c5d68a9abefb.PNG)

**Comment by Vanessa219** [comment]
Maybe it is better to float this menu in empty p?

![image](https://user-images.githubusercontent.com/970828/76743445-97ae3100-67ad-11ea-963b-2933c9bd7e55.png)

**Comment by 88250** [comment]
![1](https://user-images.githubusercontent.com/873584/77182100-32d53c80-6b07-11ea-8397-380f9be40325.gif)
![2](https://user-images.githubusercontent.com/873584/77182221-60ba8100-6b07-11ea-95cc-0f1aa023df40.gif)

**Comment by jakekwak** [comment]
![typora2](https://user-images.githubusercontent.com/15811943/77202105-b2d5b500-6abb-11ea-91da-821995b96211.gif)

I think the below idea is good.
![typora1](https://user-images.githubusercontent.com/15811943/77202128-bd904a00-6abb-11ea-9006-471a256cd37d.gif)

**Comment by 88250** [comment]
@jakekwak Thank you, we will keep going to handle some details.
