### ISSUE TITLE
编辑完成之后存储在数据库中，前端如何来渲染呢？

### ISSUE THREAD

**Issue by hectorwill** [Vanessa219/vditor#272]
编辑完成之后存储在数据库中，前端如何来渲染呢？
存储在数据库中的格式是html，怎么渲染出预览的效果。

**Comment by Vanessa219** [comment]
文档： https://hacpai.com/article/1549638745630#static-methods
示例：demo/static-preview.html

**Comment by hectorwill** [comment]
好的

**Comment by hectorwill** [comment]
> 最好是存 md 原文
> 文档： https://hacpai.com/article/1549638745630#static-methods
> 示例：demo/static-preview.html
> 
> HTML 的话可以需要调用 https://hacpai.com/article/1549638745630#static-methods 中的 xxxRender 方法

有vue的渲染方案吗?

**Comment by Vanessa219** [comment]
import 就可以了

**Comment by 88250** [comment]
对了，需要注意自行过滤 XSS。

**Comment by hectorwill** [comment]
解决了，不过好像有些写代码主题，不支持，像https://xyproto.github.io/splash/docs/longer/all.html?utm_source=hacpai.com
中的dracula主题。
![image](https://user-images.githubusercontent.com/35887903/78387202-83718d00-7611-11ea-8811-5541e47d2d19.png)

**Comment by Vanessa219** [comment]
这个是 go 解析的，前端用的 hljs，想要这个效果的话需要底层使用 https://github.com/88250/lute
