### ISSUE TITLE
为什么vditor不支持codemirror原生侧边栏的行号和折叠

### ISSUE THREAD

**Issue by lhlyu** [Vanessa219/vditor#280]
![codemirror](https://user-images.githubusercontent.com/41979509/78735452-6aecd400-797d-11ea-81cc-98458ef4895c.jpg)
RT

**Comment by Vanessa219** [comment]
因为没有使用 codemirror，这个功能需要一定的开发量。

另外像 stackoverflow，github 这类以代码为主的网站在主要功能上也没有类似的设计，也许大部分用户并不需要这个需求吧。
