### ISSUE TITLE
希望upload可以支持单文件上传

### ISSUE THREAD

**Issue by dongjing03** [Vanessa219/vditor#281]
### 你在什么场景下需要该功能？

请尽量清晰精准地描述你碰到的问题。

### 描述可能的解决方案

请尽量清晰精准地描述你期待我们要做的，描述你想到的实现方案。

### 描述你认为的候选方案

请尽量清晰精准地描述你能接受的候选解决方案。

### 其他信息

请提供关于该功能建议的其他附加信息。

**Comment by Vanessa219** [comment]
是修改接口还是只允许用户选择一个文件？

**Comment by dongjing03** [comment]
修改接口好一些吧，但是可能每个用户的需求都不同，可否让用户自己选择呢

**Comment by Vanessa219** [comment]
现在接口即支持单个文件，也支持多个文件的。

**Comment by dongjing03** [comment]
![image](https://user-images.githubusercontent.com/57089862/78774965-0f940380-79c8-11ea-8d34-00c3f00b4ddf.png)
现在是这种，
期待可以支持这种
![image](https://user-images.githubusercontent.com/57089862/78775041-2b97a500-79c8-11ea-9524-34c88b557efc.png)

**Comment by 88250** [comment]
批量接口适用性更好，服务端按接口对接一下就行了嘛。

**Comment by limodou** [comment]
能否设置只选一个文件？

**Comment by Vanessa219** [comment]
@limodou https://github.com/Vanessa219/vditor/issues/548
