### ISSUE TITLE
添加自定义加载动画

### ISSUE THREAD

**Issue by lhlyu** [Vanessa219/vditor#282]
内容较多时，渲染需要时间

**Comment by 88250** [comment]
麻烦把 md 文本打包上传一下，我看下是不是解析问题。

**Comment by lhlyu** [comment]
@88250 我用的就是本库的例子，你可以多复制几次

**Comment by 88250** [comment]
收到，目前性能方面已经优化差不多了，不过也不排除挤挤还能有空间。
加载动画 @Vanessa219 考虑下，我觉得有必要。

**Comment by Vanessa219** [comment]
你指的是 `previewRender` 方法么？

**Comment by lhlyu** [comment]
@Vanessa219 ` Vditor.preview`

**Comment by Vanessa219** [comment]
如下有些 render 方法没有回调，这样的话无法等待所有区域渲染完成才关闭 loading
![image](https://user-images.githubusercontent.com/970828/78760286-8246b400-79b3-11ea-9633-17a899a6ed6d.png)

**Comment by lhlyu** [comment]
@Vanessa219 好吧，我自己处理一下
