### ISSUE TITLE
When touched the bottom pane after code

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#287]
Can input? `not ctrl+shift+e`
![ir3](https://user-images.githubusercontent.com/15811943/78811194-16525480-798f-11ea-9743-c6ed4e0e2354.gif)

**Comment by Vanessa219** [comment]
use arrowdown or arrowright.
![image](https://user-images.githubusercontent.com/970828/78873758-ef268080-7a7d-11ea-8e3e-62140b542e39.png)

**Comment by jakekwak** [comment]
@Vanessa219 I found the another keyboard. https://github.com/klausw/hackerskeyboard
Everything is good. but not support korean.
