### ISSUE TITLE
Android phone chrome

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#288]
Problem
1. Disapear top text
2. When back space

Suggestion 
Button style(heading)

![20200408_121241](https://user-images.githubusercontent.com/15811943/78813473-ae057200-7992-11ea-8907-ec20ab5615e4.gif)

**Comment by Vanessa219** [comment]
I can not reproduce, pls unzip attachment
[Screenrecorder-2020-04-10-09-54-17-140.mp4.zip](https://github.com/Vanessa219/vditor/files/4459498/Screenrecorder-2020-04-10-09-54-17-140.mp4.zip)

**Comment by jakekwak** [comment]
My pixel 4 XL has still problem.
chrome version:
![Screenshot_20200409-212000](https://user-images.githubusercontent.com/15811943/78956665-96b8a880-7aa8-11ea-8c62-8c96401af20f.png)

New dev version:
![14](https://user-images.githubusercontent.com/15811943/78956682-a46e2e00-7aa8-11ea-8f97-649e32786ad1.gif)

**Comment by jakekwak** [comment]
I think only pixel 4(android 10) problem.
other chrome browser's version is 81.  but this one is 80.
If you have the other android 10, please try it.

**Comment by Vanessa219** [comment]
This Version is OK
![image](https://user-images.githubusercontent.com/970828/78970395-c82e8400-7b3b-11ea-857b-6a02536b9817.png)
