### ISSUE TITLE
Not sticky at iphone safari

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#289]
![EB976CF8-F3FB-4063-B02C-A1D9C7BB4681](https://user-images.githubusercontent.com/15811943/78818126-c5942900-7999-11ea-886c-6a45feb22237.png)

**Comment by stevapple** [comment]
Meeting the same problem.

**Comment by jakekwak** [comment]
https://www.w3schools.com/howto/howto_css_sticky_element.asp

**Comment by Vanessa219** [comment]
https://trix-editor.org/ has the same problem.

**Comment by jakekwak** [comment]
same problem other editor.  https://github.com/froala/wysiwyg-editor/issues/3395

**Comment by jakekwak** [comment]
flickering but it is working good. https://imperavi.com/redactor/

**Comment by jakekwak** [comment]
how about this example. https://www.w3schools.com/howto/howto_js_navbar_sticky.asp

**Comment by Vanessa219** [comment]
got, thanks

**Comment by Vanessa219** [comment]
when keyboard popup, https://imperavi.com/redactor/ has the same problem. I think it's the iPhone's bug

**Comment by Vanessa219** [comment]
If there is a new solution, please reopen it.
Thank you very much.

**Comment by nightknight77** [comment]
Having the same issue with Chrome (does not work at all), Edge, Safari and Firefox (only second line the unfolded extensions are sticky) on mobile view.
