### ISSUE TITLE
iOS Safari 快捷键显示为 Windows 版本

### ISSUE THREAD

**Issue by stevapple** [Vanessa219/vditor#293]
### 编辑模式

所见即所得模式
即时渲染模式
分屏编辑预览模式

### 描述问题

在 iOS 设备上，快捷键映射（显示）被错误地设置为 Windows 快捷键(ctrl-alt）。

### 期待的结果

iOS 设备的快捷键映射应沿袭 macOS 快捷键（⌘-⌥）。

### 截屏或录像

![image](https://user-images.githubusercontent.com/26525394/78856129-6ea15900-7a58-11ea-9dd9-1daac0b712c1.jpeg)

### 其他信息

无

**Comment by Vanessa219** [comment]
移动端上是不是不应该显示快捷键？

**Comment by stevapple** [comment]
鉴于 iOS 对外接键盘支持良好，我认为可以沿用 macOS 版快捷键。

**Comment by Vanessa219** [comment]
多谢
