### ISSUE TITLE
打字机模式下字数统计标签不可见

### ISSUE THREAD

**Issue by stevapple** [Vanessa219/vditor#296]
### 编辑模式

所见即所得模式
即时渲染模式
分屏编辑预览模式

### 描述问题

打字机模式下，字数统计标签默认位置可能位于屏幕外，处于不可见的状态。
### 期待的结果

修改现有打字机模式实现或字数统计定位规则，从而使打字机模式下始终可以看到字数统计标签。

### 截屏或录像

无

### 其他信息

无

**Comment by stevapple** [comment]
修改方案还需要 brainstorm

**Comment by Vanessa219** [comment]
字数统计好像不需要实时查看，想要看的话就滚动一下？

**Comment by stevapple** [comment]
滚动会打断输入过程，感觉有点割裂。

有没有办法能调整一下打字机算法，保持底部一行的显示？或者干脆换个位置固定字数统计标签。

在写作长文的时候随时了解字数还是有点用的。
