### ISSUE TITLE
表格解析异常

### ISSUE THREAD

**Issue by pengpengmz** [Vanessa219/vditor#299]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 编辑模式

请选择你遇到问题时使用的编辑模式（把正常情况模式删掉）：
分屏编辑预览模式

### 描述问题
从别的md 文档复制内容，粘贴到编辑文档失败
F12 观察到报错内容：
````````markdown
VM433:4 Uncaught Error: runtime error: invalid memory address or nil pointer dereference
    at $callDeferred (<anonymous>:4:22511)
    at $panic (<anonymous>:4:22957)
    at AK (<anonymous>:10:1369)
    at Object.$throwNilPointerError (<anonymous>:4:486)
    at Object.$packages.github.com/88250/lute/parse.AV.ptr.closeUnmatchedBlocks (<anonymous>:29:117991)
    at $b (<anonymous>:29:225681)
    at Object.$packages.github.com/88250/lute/parse.AX.ptr.incorporateLine (<anonymous>:29:25738)
    at Object.$packages.github.com/88250/lute/parse.AX.ptr.parseBlocks (<anonymous>:29:23425)
    at Object.AU [as Parse] (<anonymous>:29:115746)
    at Object.$packages.github.com/88250/lute.K.ptr.Markdown (<anonymous>:31:22050)
    at Object.$packages.github.com/88250/lute.K.ptr.MarkdownStr (<anonymous>:31:22991)
    at Object.$packages.github.com/88250/lute.K.ptr.Md2HTML (<anonymous>:31:33031)
    at Object.e.$externalizeWrapper.e.$externalizeWrapper (<anonymous>:4:28925)
    at <anonymous>:6:3937
    at Object.e.$externalizeWrapper.e.$externalizeWrapper [as Md2HTML] (<anonymous>:4:28925)
    at s (VM110 index.min.js:27)
    at VM110 index.min.js:27
````````

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
“粘贴为纯文本”报错么？麻烦把 md 原文打个 zip 包上传到这里，谢谢。

**Comment by pengpengmz** [comment]
对不起，我可能用法用问题，我用这个地址的demo测试没有问题
https://hacpai.com/guide/markdown
我再检查一下我的代码

**Comment by 88250** [comment]
没事，有问题请继续反馈 :smile:

**Comment by pengpengmz** [comment]
我比较了一下，https://hacpai.com/guide/markdown的用法和我不太一样。
我是仿照 demo/static.html 写的，我测试static.html 也会出现同样错误

**Comment by pengpengmz** [comment]
附件是我用的md 文件，和截图

**Comment by 88250** [comment]
> 附件是我用的md 文件，和截图

我没有看到附件哦 😂

**Comment by pengpengmz** [comment]
[temp.zip](https://github.com/Vanessa219/vditor/files/4460730/temp.zip)

**Comment by pengpengmz** [comment]
另外还发现几个小问题
- 1、#和内容之间必须有空格。我的文档是用 Typora.exe写的，它可以支持没有空格的方式
- 2、图片居中我用了
<div align=center>
![](/images/logo.png)
</div>
图片显示不出来了
去掉<div> 就可以了
- 3、图片不支持这种方式，Typora.exe是可以的
![测试][1]
[1]:/_App_Res/images/logo.png
- 4、大文章加载有点时延
 这是传入的参数，不知有没有问题
```
   	var options = {  
            	   anchor: true,     // 为标题添加锚点
            	   theme:  'classic',   // 主题：'classic' | 'dark'，默认为 'classic'
             	   //lang: 'zh_CN',    // 语言，默认为 'zh_CN'  
           	       cdn:  '${rootURL }/markdown/vditor',    // cdn路径 
             	   emojiPath:  '${rootURL }/markdown/vditor/images/emoji',    // 表情图片路径 
    			   
                   value:'please wait...',
             	   preview:{
              		    mode: 'preview',  //显示模式：'both', 'editor', 'preview'
              	    	delay:1,
   				   },
             	   hljs:{   
	    			   lineNumber:true, 
	             	   style: 'native'                //github 
	             	},  
	            	markdown:{
						toc:true,  //插入目录
					},
	         	   cache:{  
             	        enable: false,  //是否使用 localStorage 进行缓存
             	   },
              	   speech: {  // 对选中后的内容进行阅读
             	        enable: true,
             	   }
            	};
 
```

**Comment by 88250** [comment]
1. ATX 标题后面是必须要有空格的（不打算怎加选项来兼容），尽量遵循 GFM 规范减少兼容性问题
2. 这一行 `![](/images/logo.png)` 上下加空行，否则整个 div 会被判断为一个 html block（这也是 GFM 规范定义的）   
   ![image](https://user-images.githubusercontent.com/873584/78979872-5102eb00-7b4f-11ea-991a-be163dd9667e.png)
   ![image](https://user-images.githubusercontent.com/873584/78979888-5829f900-7b4f-11ea-8daf-9f2b5f40c03c.png)
3. 引用图片语法我这里测试似乎没有问题
   ![image](https://user-images.githubusercontent.com/873584/78979629-d2a64900-7b4e-11ea-8064-5407b40de45f.png)
4. @Vanessa219 帮忙看下参数

**Comment by pengpengmz** [comment]
多谢，我再试试图片显示

**Comment by pengpengmz** [comment]
![新建位图图像](https://user-images.githubusercontent.com/6553133/78983705-48aeae00-7b57-11ea-91eb-6447409ddb82.png)
图片的问题我测试了，引用行和 变量之间必须有空行才行

**Comment by pengpengmz** [comment]
纠正一下：
我又测试一下，和输入的内容大小没有关系，和输入的内容有关
```
# 表格
markdown生成表格是比较麻烦的。
1.使用 | 来分隔不同的单元格，使用 - 来分隔表头和其他行：
name | age
---- | ---

# 小技巧

```

**Comment by pengpengmz** [comment]
![新建位图图像 (2)](https://user-images.githubusercontent.com/6553133/78985492-844b7700-7b5b-11ea-9eda-a422c83328c9.png)

**Comment by 88250** [comment]
收到，感谢帮忙定位问题，稍后进行修复。

**Comment by 88250** [comment]
表格引起的异常会在即将发布的版本中修复，我关闭这个 issue 了。如果还有其他问题，欢迎单独再开 issue 进行反馈，谢谢。
