### ISSUE TITLE
编辑预览同步滚动改进

### ISSUE THREAD

**Issue by Vanessa219** [Vanessa219/vditor#3]
https://hacpai.com/article/1558270349379/comment/1566437781465?r=88250

可基于源码映射来进行改进，编辑区中间一行位置映射到某个 DOM 节点上，这样就非常精确了。

**Comment by 88250** [comment]
SV 模式重做完成，可以开始考虑优化这个问题了。

**Comment by 88250** [comment]
没有时间精力，暂时不考虑了。
