### ISSUE TITLE
添加 option.value

### ISSUE THREAD

**Issue by XShellv** [Vanessa219/vditor#30]
当前如果在react中使用父组件传递过来的defaultValue值时无法通过数据流渲染到vditor，只能通过setValue方法处理，该方法只能在compoenntDidUpdate中调用，可能存在堆栈溢出的现象。

**Comment by Vanessa219** [comment]
有一个 after 方法，可以在里面 setValue，不行的话我加一个 defaultValue 参数？

**Comment by XShellv** [comment]
期待！

**Comment by Vanessa219** [comment]
初始值顺序为：

* 如果启用缓存，且缓存有值的话，优先使用缓存值
* option.value 和 DOM 中都存在值的话，优先使用 option.value
