### ISSUE TITLE
hiding top text(input) at pixel 4 xl chrome.

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#307]
pin: false
![17](https://user-images.githubusercontent.com/15811943/79050245-6713b880-7bee-11ea-83cf-e42ab930edf7.gif)

pin: true
![18](https://user-images.githubusercontent.com/15811943/79050250-6bd86c80-7bee-11ea-8d5d-bc0998353f98.gif)

**Comment by Vanessa219** [comment]
how to pin: false? I can not reproduce
[1586668597429822.mp4.zip](https://github.com/Vanessa219/vditor/files/4466087/1586668597429822.mp4.zip)

**Comment by jakekwak** [comment]
I don't have any new android phone(samsung galaxy s10 or s20). I think my phone(pixel 4 xl) has the problem(https://github.com/Vanessa219/vditor/issues/288)
Anyway fix the hiding top at pin:true.

**Comment by Vanessa219** [comment]
you can set `options.height=400` or remove it.
It's Browser issue.
