### ISSUE TITLE
[suggestion] Custom toolbar for mode

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#308]
I want to use the toolbar as below at IR and mobile.
If possible,  can make some option of custom toolbar?
ir:mobile, ir:pc
sv:mobile, sv:pc
wysiwyg:mobile, wysiwyg:pc

![19](https://user-images.githubusercontent.com/15811943/79056145-d7373400-7c18-11ea-8fcd-325efa11ed82.gif)

**Comment by Vanessa219** [comment]
I think you can use `getCurrentMode` and https://stackoverflow.com/questions/11381673/detecting-a-mobile-browser
