### ISSUE TITLE
上传图片的请求体中Content-Disposition中name为file[]，后端应该如何适配

### ISSUE THREAD

**Issue by 3042885921** [Vanessa219/vditor#310]
![image](https://user-images.githubusercontent.com/48979893/79093165-fd2e1700-7d85-11ea-92ad-1d5964515499.png)

**Comment by 3042885921** [comment]
正常的name不是应该为file嘛

**Comment by Vanessa219** [comment]
这个接口可以支持多个文件上传，后端表单获取的 name 修改为 `file[]` 就可以了。
