### ISSUE TITLE
html 页面 点击禁用button 引起回调

### ISSUE THREAD

**Issue by pengpengmz** [Vanessa219/vditor#313]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 编辑模式

请选择你遇到问题时使用的编辑模式（把正常情况模式删掉）：

所见即所得模式    - 有问题
即时渲染模式        - 有问题
分屏编辑预览模式 - 没问题

### 描述问题
```
我的html页面 有<form id="Form1"  method="post">，
```
点击toolbar 上任意一个禁用button 引起回调

**Comment by pengpengmz** [comment]
[index.zip](https://github.com/Vanessa219/vditor/files/4479948/index.zip)
附件是我测试用页面

**Comment by pengpengmz** [comment]
错误截图
![新建位图图像](https://user-images.githubusercontent.com/6553133/79316073-6785b980-7f36-11ea-863c-79b9d72d46c4.png)

**Comment by Vanessa219** [comment]
3.1.11 中修复
