### ISSUE TITLE
反斜杠转义处理

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#32]
![double underscore](https://user-images.githubusercontent.com/15811943/71774839-b3ce6000-2f2a-11ea-9f50-5bb9096c3d05.gif)

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/71774912-31897e80-2fb2-11ea-91cd-53f11b2a1a27.png)

Dose the whole line enclose with \<strong\>? Which marker (** or __) the strong used?

**Comment by jakekwak** [comment]
I used H4(####).

#### extensions are lazy initialized.(app/extensions.py, app/\_\_init__.py)
