### ISSUE TITLE
代码区点击复制代码时自动去掉行号

### ISSUE THREAD

**Issue by kangaroo1122** [Vanessa219/vditor#320]
在开启行号显示的情景下，点击复制按钮，会把代码前边的行号复制进去，可以不可以优化一下，复制时去掉行号

**Comment by Vanessa219** [comment]
源码中的 Demo 加上对应的配置并不会重现，请详细描述一下或给出示例

**Comment by kangaroo1122** [comment]
我的博客里边，随便给个地址，复制出来都是有行号的
[https://www.kangaroohy.com/articles/2019/11/20/1574235633965.html](https://www.kangaroohy.com/articles/2019/11/20/1574235633965.html)
像这样：
1docker run --detach --name solo --network=host \
2    --env RUNTIME_DB="MYSQL" \
3    --env JDBC_USERNAME="solo" \
4    --env JDBC_PASSWORD="你的密码" \
5    --env JDBC_DRIVER="com.mysql.cj.jdbc.Driver" \
6    --env JDBC_URL="jdbc:mysql://127.0.0.1:3306/solo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC" \
7    b3log/solo --listen_port=8585 --server_scheme=http --server_host=solo.kangaroohy.top --server_port=

**Comment by Vanessa219** [comment]
哦。明天更新再试试
