### ISSUE TITLE
移动端如何调用toolbar的方法

### ISSUE THREAD

**Issue by Karthus1110** [Vanessa219/vditor#321]
### 你在什么场景下需要该功能？

移动端需要键盘顶部的按钮点击实现输入md，而不是自带的toolbar

### 描述可能的解决方案

vditor提供接口供移动端调用，类似viditor.boldSelect即可输入加粗

### 其他信息

  @@移动端关于所见即所得的MD编辑器很迫切，找了很多资料就看到贵项目实现比较接近。
@Vanessa219

**Comment by Vanessa219** [comment]
目前没有，你使用 `toolbarIconElement.dispatchEvent(new CustomEvent("click"))` 试试。

**Comment by Vanessa219** [comment]
没问题的话我先关闭了，有问题可以随时反馈。

**Comment by Karthus1110** [comment]
调用这个方法在移动端无效 @Vanessa219 
请问是否还有其他解决方案

**Comment by Vanessa219** [comment]
不好意思，少了一层

```
vditor.vditor.toolbar.elements.bold.firstElementChild.dispatchEvent(new CustomEvent("click"))
```

**Comment by Karthus1110** [comment]
![image](https://user-images.githubusercontent.com/13864988/79846923-9c3fb800-83f1-11ea-963c-4605318329fe.png)
还是没有效果，不管我是在App端调用该方法 还是在网页内部调用

**Comment by Vanessa219** [comment]
直接在 console 中输入以上代码片段即可。要保证 toolbar 中有 'bold', wysiwyg mode 体现为工具栏上 b 高亮

**Comment by Karthus1110** [comment]
![image](https://user-images.githubusercontent.com/13864988/79929488-6a256900-8478-11ea-9924-e5e8c2544c2f.png)
还是没有效果，而且移动端需要隐藏toolbar
不知道在toolbar隐藏的状态下 使用此种方法是否有效。
或者是否可以通过模拟快捷键来实现格式输入？

**Comment by Vanessa219** [comment]
移动端的 iPhone 是 touchstart 了，其余为 click

**Comment by Karthus1110** [comment]
非常感谢 解决了大部分问题 ，还有一些问题请教
如何隐藏这个popover
![image](https://user-images.githubusercontent.com/13864988/80193690-e2905380-864b-11ea-9e47-6e744b98497d.png)

还有是否能实现完全离线使用，我看到有一些CDN下载的东西，论坛里和issue里的离线使用的问题我看过了，没找到相应答案

**Comment by Vanessa219** [comment]
开发文档里面搜索 cdn，修改为本地的就可以了。不需要情景菜单的话可以设置为 ir 模式

**Comment by Karthus1110** [comment]
所见即所得模式没法隐藏这个菜单吗

**Comment by Vanessa219** [comment]
你覆盖一下 css 试试 `display:none !important`

**Comment by Karthus1110** [comment]
再请问一下 heading的 H1到H6因为按钮是隐藏 即使获取到了元素也没法模拟点击事件，有什么处理方案吗
![image](https://user-images.githubusercontent.com/13864988/80338941-33908980-8890-11ea-978a-78bd1192c694.png)

**Comment by Vanessa219** [comment]
先触发 heading 就可以显示按钮了

**Comment by Karthus1110** [comment]
![image](https://user-images.githubusercontent.com/13864988/80436821-a18d8d00-8932-11ea-8241-3ba10e97bc3a.png)
这样操作会有异常显示 会把已经隐藏的toolbar显示出来 不知是否还有其他解决方案

**Comment by Karthus1110** [comment]
还有是否有回调监听删除了某一个格式的代码，比如删除了check/code/list应该如何监听，方便将按钮状态置为非选中

**Comment by Vanessa219** [comment]
隐藏的 toolbar 移除显示区域 left： -100000px

**Comment by Vanessa219** [comment]
有个 input 回调，你试试

**Comment by Karthus1110** [comment]
input回调我在使用 感谢回答，还有最后一个问题 headings点击后，我不想显示这个选择框需要如何使用代码隐藏选择框 并完成h1-h6的点击事件呢
![image](https://user-images.githubusercontent.com/13864988/80440471-6e033080-893b-11ea-8c89-6f01c23712f7.png)

**Comment by Vanessa219** [comment]
```
.vditor-hint {
    position: fixed;
    left: -1000px;
}
```

```
vditor.vditor.toolbar.elements.headings.querySelectorAll('button')[0].dispatchEvent(new CustomEvent("click"))
```

**Comment by Karthus1110** [comment]
谢谢！非常感谢你的耐心解答

**Comment by Karthus1110** [comment]
![image](https://user-images.githubusercontent.com/13864988/80469555-4def6380-8973-11ea-8c1e-a75c7d497fb6.png)
![image](https://user-images.githubusercontent.com/13864988/80469581-56479e80-8973-11ea-8126-a7e63791c301.png)
无法呼出inline-code 和ordered-list这两个控件

**Comment by Vanessa219** [comment]
```
vditor.vditor.toolbar.elements["inline-code"].firstElementChild.dispatchEvent(new CustomEvent('click'))
```

**Comment by Karthus1110** [comment]
![image](https://user-images.githubusercontent.com/13864988/80555191-1ed40300-8a02-11ea-9e25-6325a4c8bb33.png)
![image](https://user-images.githubusercontent.com/13864988/80555206-272c3e00-8a02-11ea-8ed6-197dd354b211.png)
`vditor.setValue(json['content']) `时  部分换行和回车消失了

**Comment by Vanessa219** [comment]
部分换行和回车在 markdown 规范中解析出来会被移除。想要不被解析可以试试`vditor.setValue(json['content'], false)`

**Comment by Karthus1110** [comment]
试了`insertValue(json['content'], false) 和 setValue(json['content'], false)` 都没有效果

**Comment by Vanessa219** [comment]
更新到最新版试试。

**Comment by Karthus1110** [comment]
更新到最新版本3.1.9依然存在这个问题，并且hidetoolbar有bug，不会隐藏或者要键盘弹起之后才会隐藏

**Comment by Vanessa219** [comment]
更新到 3.1.19 试试。配置项已经修改，可以看一下 CHANGELOG.md
```
  toolbarConfig: {
    pin: true,
    hide: true
  }
```

**Comment by Karthus1110** [comment]
![image](https://user-images.githubusercontent.com/13864988/80573876-66bf4e00-8a33-11ea-9fec-dd4d7a1e09a2.png)
![image](https://user-images.githubusercontent.com/13864988/80574675-de41ad00-8a34-11ea-8dca-ca77923e9641.png)

去掉换行的问题还是存在，我在初始化的方法中也试了

**Comment by Vanessa219** [comment]
没太明白你的意思

**Comment by Karthus1110** [comment]
就是我传入的string里面的换行和回车还是消失了

**Comment by Vanessa219** [comment]
根据 CommonMark，会删除多余的换行和空格

**Comment by Karthus1110** [comment]
有没有什么办法处理一下，用户如果输入了内容需要重新编辑的时候，回来中间的换行和空格都删掉了 会比较奇怪

**Comment by 88250** [comment]
@Karthus1110 在 Markdown 解析层面恐怕办不到，但如果一定要实现，可以考虑将连续换行中的 `\n` 后插入 `&nbsp;`，比如：

```markdown
foo
&nbsp;
&nbsp;
&nbsp;
bar
```

渲染结果如下：

foo
&nbsp;
&nbsp;
&nbsp;
bar

不过细节处理有点麻烦，仅供参考。

**Comment by Karthus1110** [comment]
@88250 添加这个符号 会影响后续的md解析，会将line解析会heading或者没有解析后面的md,打印的时候看到没有解析的文字前面有个&nbsp;

**Comment by 88250** [comment]
我的意思是仅在提交服务端保存时连续空行 `\n\n` 之间添加，后面加载到编辑器之后要把这些去掉。有点麻烦，而且有可能有其他问题，所以仅供参考。

**Comment by Karthus1110** [comment]
我保存到数据库的md string是`vditor.getValue()`获得的，之后再用同样的加载到编辑器就没有空行了 ，这个跟你说的添加这个符号加载到编辑器再去掉好像并没有什么区别 @88250

**Comment by 88250** [comment]
Markdown 解析渲染是在 [Lute](https://github.com/88250/lute) 中实现的，Lute 实现了 CommonMark 规范，解析过程不建议修改，否则会有带来一些冲突，这也是遵循 CommonMark 规范的目的。

前面说的方案要在解析之前，也就是用户输入后做替换，手动演示过程如下，一开始 foo 和 bar 之间的空行会被解析过程“吃掉”，但是加入替换字符后就不会了：

![f](https://user-images.githubusercontent.com/873584/81150921-0c823800-8fb3-11ea-82c2-e65ccdff5e1d.gif)

* 格式化走了 Markdown 解析，所以用格式化功能来演示
* 替换字符用的是 `&emsp;`，如果用程序实现的话可以用汉字的全角空格，用 `&nbsp;` 的话只能解析一次，有点问题

当然，我只是大致想了个解决方案，实操过程还需要你自己探索。另外，我也不保证这个方案不会引发其他问题，最好先手动多测试下，比如行级元素（强调、加粗和链接等）嵌套、块级元素（段落、加粗、列表等）嵌套和块级容器（列表、块引用）嵌套的场景。

祝你好运！

**Comment by Vanessa219** [comment]
规范里面会删除多余的换行和空格，这也是为了排版的好看。是什么场景一定要加上不必要的换行和空格呢？

**Comment by Karthus1110** [comment]
目前我将vditor用于移动端，用户编辑书写了一个文章，段落、图片或者内容中间可能插入一行或者多行的空行保证间隔，让文章看起来更清晰，如果保存了这个md string再次回来编辑的时候 中间的空行消失了，可能会造成用户的困扰

**Comment by Vanessa219** [comment]
这可能要看你的用户了，vditor 用在 https://hacpai.com/ 上还没出现用户提出类似的需求。

你也可以做一个换行按钮，点击以后插入替换字符

**Comment by 88250** [comment]
可以这样看，如果你的用户用过 Markdown 的话那么应该明白多个空行实际上没有作用，即段落不会存在多余空行，如果需要内容分隔，可以用 `---` 分隔线。

但如果你的用户没用过 Markdown 的话，那解释起来就费劲了。其实也没有什么解释的必要，用户不会关注这个 😂 这种场景下，我个人建议还是用富文本编辑器，满足用户需求第一。

**Comment by Karthus1110** [comment]
可能用户并不会在意md和富文本的区别😂

**Comment by Karthus1110** [comment]
![image](https://user-images.githubusercontent.com/13864988/81162223-68eb5480-8fbf-11ea-9313-12cfd5cbf69a.png)
不知道为什么会出现这个报错，好像是我开了第二个网页加载编辑器

**Comment by Vanessa219** [comment]
可以详细描述一下么？我这里重现不了

**Comment by Karthus1110** [comment]
不知道是不是我js写的不对
`var vditor
func config(json) {
vditor = new Vditor(
value: json.content
)
}
`
大概是这样写的 我提供了一个config方法供iOS原生调用，让原生传入一些配置信息，比如原始的value，mode之类的，不知道是不是我这样的写法有问题

**Comment by Vanessa219** [comment]
这样看不出你的参数。

**Comment by Karthus1110** [comment]
![image](https://user-images.githubusercontent.com/13864988/81248670-7819e300-904f-11ea-8407-780816feb3b2.png)

实际问题就是我有一个文章列表，每次我再初始化方法中需要传入json进行初始化，打开第一个文章初始化编辑不会报错，关掉再重新打开另一个文章就会报错，如果这时候关掉当前的编辑器再重新打开第一个文章，也同样报错

**Comment by Vanessa219** [comment]
你把 vditor.vditor... 放在 options.after 中试试

**Comment by Karthus1110** [comment]
应该不是这个问题 我把代码注释了也一样

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/new

那你可以添加一下 'edit-mode' 或稍等 https://github.com/Vanessa219/vditor/issues/373 修复

**Comment by Karthus1110** [comment]
好的 感谢 已解决

**Comment by Karthus1110** [comment]
![image](https://user-images.githubusercontent.com/13864988/81276789-14f77300-9086-11ea-85a3-dd067d3163bd.png)
![image](https://user-images.githubusercontent.com/13864988/81276898-38222280-9086-11ea-9201-2c2132b00e93.png)


当初始化的value 为空字符串""时，会出现该错误，控制台没有报错
我试过初始化的value设为有内容的字符串不会出现该情况，不知道什么问题

复现的步骤是：移动端加载网页打开编辑器，关掉，再打开，再关掉，第三次打开基本必现

**Comment by Vanessa219** [comment]
重复加载的时候把 dom 里面清空了
```
document.getElementById('vditor').innerHTML = ''
```

**Comment by Karthus1110** [comment]
![image](https://user-images.githubusercontent.com/13864988/81461236-f952b080-91dc-11ea-9d48-6224c52d5592.png)
请问是否有隐藏这个的配置项

**Comment by 88250** [comment]
@Karthus1110 老铁，开个新的 issue 吧

**Comment by yiviiii** [comment]
`vditor.vditor.toolbar.elements.headings.querySelectorAll('button')[0].dispatchEvent(new CustomEvent("click"))`
您好，像这一行代码这些的调用的方法是在哪里看啊，我在仿照这行代码，模拟点击其他toolbar按钮的时候不知道调用什么。

**Comment by yiviiii** [comment]
@Vanessa219 您好！麻烦问一下，
![屏幕截图 2024-04-12 173139](https://github.com/Vanessa219/vditor/assets/74703057/224a9d6d-99f6-4bed-8c14-95d8b453e77f)
这个命名中间加"-"的按钮，应该在哪里调用？按上面的方法替换没用啊

**Comment by Vanessa219** [comment]
@karthuszY 没有，用 css 试试
