### ISSUE TITLE
即时渲染模式下表格无法调整行列等属性

### ISSUE THREAD

**Issue by ydq** [Vanessa219/vditor#322]
### 编辑模式

即时渲染模式

### 描述问题

即时渲染模式下无法用markdown代码调整表格行列，也没有没有弹出浮动工具栏去进行操作，typora是会弹出浮动工具栏的。

### 期待的结果

能支持弹出所见即所得模式下的浮动工具栏，或者干脆像代码编辑一样，上面显示markdown源码，下面及时渲染表格样式

---

> 另外之前有个 “脑洞大开、异想天开” 的 Issues 虽然被关闭了，但是现在还是觉得可以尝试一下，重新评论了一下，并且 @ 了 V大，但是怕因为状态是关闭了看不见，所以就无耻的在这里贴一下评论地址：https://github.com/Vanessa219/vditor/issues/255#issuecomment-615379574  希望V大能再看看

**Comment by jakekwak** [comment]
try `ctrl_+`, `ctrl_-`, `ctrl_shift_+`, `ctrl_shift_-`.

**Comment by Vanessa219** [comment]
https://hacpai.com/article/1582778815353 快捷键汇总在这里。
不太想把 wysiwyg 和 ir 模式做的太像，情景工具栏的话可能先不考虑了。

@jakekwak The table uses a similar code block in ir mode, do you think it is better?

**Comment by jakekwak** [comment]
@Vanessa219 I am testing various toolbar menus for each mode.
On the smartphone, the toolbar has too many items, which makes it a little inconvenient. Especially in Pixel 4 XL.
I think one or two line will be good.

**Comment by Vanessa219** [comment]
you can custom it. e.g:
![image](https://user-images.githubusercontent.com/970828/79628764-85416180-8176-11ea-8878-667059753f5a.png)

**Comment by Vanessa219** [comment]
我先关闭了，有更好的方式再打开即可。
