### ISSUE TITLE
sv 模式高度错误

### ISSUE THREAD

**Issue by lhlyu** [Vanessa219/vditor#328]
- 版本3.1.12
- mode: 'sv'

![演示](https://user-images.githubusercontent.com/41979509/79678320-a82e4d00-822c-11ea-82d7-581b161e36e5.gif)

- 问题
1. 点击编辑框区域，光标不会自动聚焦，要点击第一行才会聚焦
2. 光标初始化很小

**Comment by Vanessa219** [comment]
你看一下源码里面的 Demo 有没有这种问题？我这里无法重现。

**Comment by lhlyu** [comment]
@Vanessa219 
我重新尝试了一下，下面的代码是有问题的
```
new Vditor('editor', {
    minHeight: 600,
    mode: 'sv',
})
```
改成这样就没问题了
```
new Vditor('editor', {
    height: 600,
    mode: 'sv',
})
```
