### ISSUE TITLE
html at code block

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#331]
when put the html code like below,  How can I prevent? (see picture)

\-\------
# test

```html
<textarea>
<p>hello</p>
</textarea>
```

test

```bash
cd test
```
\-\---

![Screen Shot 2020-04-19 at 4 35 08 PM](https://user-images.githubusercontent.com/15811943/79700511-cf504300-825b-11ea-826a-af5a75c2f268.png)

**Comment by 88250** [comment]
If we filter the tag `<textarea>`, do you think it works?

**Comment by jakekwak** [comment]
@88250 I think this Github style is good.
![1](https://user-images.githubusercontent.com/15811943/79772275-82b94600-82f5-11ea-8c43-f6c1b93fdadf.PNG)

**Comment by 88250** [comment]
Thank you, I will try it later.

**Comment by jakekwak** [comment]
@88250 FYI,  ckeditor 4
![2](https://user-images.githubusercontent.com/15811943/79823356-36075680-8359-11ea-8a38-3abb52ec397c.PNG)

**Comment by 88250** [comment]
@Vanessa219 Oh, this is not the xss-like issue, it caused by dom select content not work as our expected. 

![image](https://user-images.githubusercontent.com/873584/79849371-f3935780-83f4-11ea-8314-a06af161945c.png)

**Comment by Vanessa219** [comment]
textarea is broken by itself tag. you can use  template to transfer it.

**Comment by jakekwak** [comment]
@Vanessa219 Could you make some preview demo including `textarea`.  I don't know how to use Template.  Thanks

**Comment by Vanessa219** [comment]
The demo is static html. You can use Lute to convert it and then render, for example https://github.com/88250/symphony or https://github.com/88250/solo
