### ISSUE TITLE
希望 Markdown 编辑器 可以上传 .svg 格式的图像

### ISSUE THREAD

**Issue by cuijianzhe** [Vanessa219/vditor#340]
### 你在什么场景下需要该功能？

编辑博客时，有部分图像是.svg格式，希望可以实现此功能

### 描述可能的解决方案

无

### 描述你认为的候选方案

无

### 其他信息

无

**Comment by Vanessa219** [comment]
@88250 solo 需要修改一下么？

**Comment by Vanessa219** [comment]
https://github.com/88250/solo/issues/113

**Comment by 88250** [comment]
考虑再三，暂时还是不支持了，因为 SVG 内可能包含不安全的脚本，暂时没有找到过滤解决方案。
