### ISSUE TITLE
&lt; &gt; not showing at preview

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#342]
SV editor mode
![1](https://user-images.githubusercontent.com/15811943/80271683-0bced500-8688-11ea-9c48-cfe30dcc69e3.PNG)

preview
![2](https://user-images.githubusercontent.com/15811943/80271684-0d989880-8688-11ea-9f1b-844d45a938a2.PNG)

SV edttor mode
![3](https://user-images.githubusercontent.com/15811943/80271685-0ec9c580-8688-11ea-8de5-0c644d05d257.PNG)

preview
![4](https://user-images.githubusercontent.com/15811943/80271686-10938900-8688-11ea-8077-964b08c8bffa.PNG)

**Comment by Vanessa219** [comment]
Same as https://github.com/Vanessa219/vditor/issues/331
When using the browser API `textContent`, it will be converted to` <`

**Comment by jakekwak** [comment]
testing at github
< : \&lt;, `&lt;`
\> : \&gt;, `&gt;`

**Comment by Vanessa219** [comment]
vditor same as it at https://hacpai.com/article/1543688051168
![image](https://user-images.githubusercontent.com/970828/80283814-1acb8b00-874d-11ea-8950-3e802cbe3d28.png)

**Comment by jakekwak** [comment]
you can convert it as below In `md2html`,

![5](https://user-images.githubusercontent.com/15811943/80284988-9f83be00-86e7-11ea-8cae-96de2007082e.PNG)

`preview`
![6](https://user-images.githubusercontent.com/15811943/80284992-a8748f80-86e7-11ea-9bfb-bce45654030c.PNG)

**Comment by Vanessa219** [comment]
Please print markdown. it's different.

**Comment by jakekwak** [comment]
`static-preview.html`
```
<textarea id="zh_CNText" style="display:none;">
< : `&lt;` \&lt;
\> : `&gt;` \&gt;
</textarea>
```
![8](https://user-images.githubusercontent.com/15811943/80295583-81df4480-8739-11ea-8a5d-97f98820187e.PNG)

`markdown mode`
![7](https://user-images.githubusercontent.com/15811943/80295590-93285100-8739-11ea-8b40-e798511886a1.PNG)

**Comment by Vanessa219** [comment]
> Same as #331
> When using the browser API `textContent`, it will be converted to` <`

You should use template or ajax.

**Comment by jakekwak** [comment]
I am not good at programming.
If possible, please make the demo with `template` and `ajax`.
Thanks,

**Comment by 88250** [comment]
![](https://user-images.githubusercontent.com/873584/79849371-f3935780-83f4-11ea-8314-a06af161945c.png)

Let me explain the scenario for more details. In the browser, we can't get `textarea` via DOM API as we expected, so we should rendering the markdown text separate from browser DOM, just like Vanessa said, using backend template rendering result or pass the rendering result via AJAX.

`template` approach like this:

```html
<textarea>
${mdResultHTML}
</textarea>
```

The `${mdResultHTML}` is a template data model variable, it processed by backend server via Lute 
 or other markdown engines.

`AJAX`  approach is to make an AJAX request from browser to get the markdown rendering result from the backend server.

**Comment by jakekwak** [comment]
@88250 thanks. I solved it.
