### ISSUE TITLE
内容主题推荐

### ISSUE THREAD

**Issue by Vanessa219** [Vanessa219/vditor#346]
请大家跟帖来推荐主题，我们会按点赞数进行参考并融入自己的风格后进行制作。当然，也欢迎大家参考对应的 css 自行开发。

### 已完成

- [x] wechat 
- [x] dark 
- [x] light

**Comment by codingcn** [comment]
个人感觉内容主题都是次要的，这些对于开发者都是可以自己编写样式定制的。

推荐考虑参考以下两款编辑器有书写模式来做优化方向，medium.com的书写体验感觉真的很棒！

https://github.com/sofish/pen

https://github.com/yabwe/medium-editor

**Comment by Vanessa219** [comment]
场景菜单在移动端或许比较方便，有兴趣的话可以参与 https://github.com/Vanessa219/vditor/issues/414 讨论

在 PC 端我们还是希望减少用户的鼠标操作，让用户更加方便快捷专业的进行编辑。感谢你提供的宝贵建议。

**Comment by jakekwak** [comment]
I made the seperate [repo](https://github.com/jakekwak/vditor-content-themes/) for preview themes.  I found this [repo](https://github.com/evgo2017/typora-theme-orange-heart).
If it is ok,  I will add one by one (MIT license only..)

**Comment by 88250** [comment]
> I made the seperate [repo](https://github.com/jakekwak/vditor-content-themes/) for preview themes. I found this [repo](https://github.com/evgo2017/typora-theme-orange-heart).
> If it is ok, I will add one by one (MIT license only..)

Well done 🍻

**Comment by cbamls** [comment]
1. 导出到知乎
2. 更多的样式模版

**Comment by Vanessa219** [comment]
1. https://github.com/Vanessa219/vditor/issues/534
2. 欢迎推荐具体的样式模版

**Comment by cbamls** [comment]
> 1. #534
> 2. 欢迎推荐具体的样式模版

https://mdnice.com/ 这个项目是开源的，他们开源代码里很多css样式模版。选择模版的时候，作者通过juice 注入css样式到html，这样就可以复制出来自带css了

**Comment by Vanessa219** [comment]
他的 License 不允许哦

**Comment by cbamls** [comment]
> 他的 License 不允许哦

那能否Vditor类对外提供静态   HTMLstring renderCSS(“css string”)方法， 让使用vditor的人可以自定义html样式。renderCSS方法内部 将入参 通过juice注入html——juice.inline(Vditor.getHTML(), "css string")。

**Comment by Vanessa219** [comment]
@cbamls https://github.com/Vanessa219/vditor/issues/519 下个版本可以支持主题扩展

**Comment by ElderJames** [comment]
可否支持ant design的排版样式？

**Comment by Vanessa219** [comment]
@ElderJames 可以给一个具有以下元素 http://vditor.b3log.org/demo/preview.html 的排版示例么？

**Comment by HerbertHe** [comment]
定制自定义主题样式: https://github.com/HerbertHe/vditor-theme

**Comment by 88250** [comment]
关闭了，谢谢。
