### ISSUE TITLE
Good outline demo

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#347]
Is it possible? https://www.markdownguide.org/basic-syntax/

![vditor1](https://user-images.githubusercontent.com/15811943/80650810-4b0b7600-8a3a-11ea-9583-508f9525f331.gif)

**Comment by 88250** [comment]
Do you mean to:

* Fold the subheading?
* Highlight the heading and subheading at the same time?

**Comment by jakekwak** [comment]
@88250 Yes,  I think that is cool.

**Comment by 88250** [comment]
Personally, I prefer unfolded outline more 😂

**Comment by jakekwak** [comment]
I will close this issue.
