### ISSUE TITLE
有五线谱怎么能没有简谱呢

### ISSUE THREAD

**Issue by loocao** [Vanessa219/vditor#348]
### 你在什么场景下需要该功能？

请尽量清晰精准地描述你碰到的问题。

### 描述可能的解决方案

请尽量清晰精准地描述你期待我们要做的，描述你想到的实现方案。

### 描述你认为的候选方案

请尽量清晰精准地描述你能接受的候选解决方案。

### 其他信息

请提供关于该功能建议的其他附加信息。

**Comment by Vanessa219** [comment]
说的好像很有道理，请问一下有没有类似的前端库？

**Comment by Vanessa219** [comment]
找了一下，好像只找到这个，https://felixhao28.github.io/react-jianpu/ 这个怎么样？

**Comment by loocao** [comment]
> 找了一下，好像只找到这个，https://felixhao28.github.io/react-jianpu/ 这个怎么样？

有点简单啊~没有全面的标注，貌似现在没得什么库能方便的生成简谱

**Comment by loocao** [comment]
学了一 年笛子，突然想整个画简谱的东西~

**Comment by Vanessa219** [comment]
这样的话，要不你学学五线谱，这比写一个简谱的代码要简单很多吧

**Comment by loocao** [comment]
> 这样的话，要不你学学五线谱，这比写一个简谱的代码要简单很多吧

简谱看着简单啊~五线谱看起来好复杂~

**Comment by Vanessa219** [comment]
加油，你可以挑战写个简谱.js 或者学看五线谱
