### ISSUE TITLE
static-preview.html

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#352]
When the user can add their own `css` file and `js` file at `static-preview.html`, It will be better.
(it means there are no automatic inserting `css` and `js`)

for exampe. 
```
<link rel="stylesheet" href="myown.css">
<link rel="stylesheet" href="something_more">
<script src="../dist/method.min.js></script>
<script src="../dist/js/lute/lute.min.js></script>
<script src="../dist/js/abcjs/abcjs_basic.min.js></script>
<script src="../dist/something_more"></script.
```

**Comment by Vanessa219** [comment]
static-preview.html is a demo, anyone can modify it by themselves
