### ISSUE TITLE
list demo at static-preview.html

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#353]
lists
![Screen Shot 2020-05-01 at 7 24 51 PM](https://user-images.githubusercontent.com/15811943/80850549-03275300-8be2-11ea-8aeb-0c6690d71b18.png)

Wrong
![Screen Shot 2020-05-01 at 7 26 02 PM](https://user-images.githubusercontent.com/15811943/80850553-06224380-8be2-11ea-93bc-0fd9151c2614.png)

expected
![Screen Shot 2020-05-01 at 7 26 46 PM](https://user-images.githubusercontent.com/15811943/80850559-08849d80-8be2-11ea-802a-d287c6888ecd.png)

**Comment by Vanessa219** [comment]
this demo is error, pls use
```
1. Node.js
   1. Express
   2. Koa
   3. Sails
2. Go
   1. gofmt
   2. Wide
3. Java
   1. Latke
   2. IDEA
```
