### ISSUE TITLE
Block 可以支持拖动排序么？

### ISSUE THREAD

**Issue by takashiki** [Vanessa219/vditor#356]
### 你在什么场景下需要该功能？

现在 vidtor 里的 block 在 active 态可以通过悬浮的 上下箭头 完成排序，但这并不如拖动排序来得方便。

### 描述可能的解决方案

如果 block 能支持类似 notion 的拖动排序的话使用会便捷一些。
另外目前列表的单个子元素不能单独排序，动的时候是整个列表一起动，如果能像幕布一样拖动单个子元素进行排序的话，整理大纲类知识点会很方便。

**Comment by Vanessa219** [comment]
子列表拖动可以支持
至于拖拽，我个人用了下 wordpress 的 gutenberg，如果拖拽距离过远或块元素过长的的话体验不太好。

**Comment by Vanessa219** [comment]
我先关闭了，如果有更好的交互方式再打开

**Comment by takashiki** [comment]
好的，希望考虑先支持子列表的排序

**Comment by Vanessa219** [comment]
好的，https://github.com/Vanessa219/vditor/issues/371
