### ISSUE TITLE
typing fast(code block) at IR

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#360]
![vditor3](https://user-images.githubusercontent.com/15811943/80990886-be2b3880-8dfc-11ea-959d-ecad03b07214.gif)

**Comment by Vanessa219** [comment]
After ```, which key do you press?
BTW, after bash, you can press Enter twice to switch to the code block.

**Comment by jakekwak** [comment]
try to \``` + `anykey`
