### ISSUE TITLE
Copy Paste (HTML2Markdown) issue 

### ISSUE THREAD

**Issue by 88250** [Vanessa219/vditor#363]
@88250 try to readme file  (https://github.com/Vanessa219/vditor/blob/master/README.md).
table and code block has problem

_Originally posted by @jakekwak in https://github.com/Vanessa219/vditor/issues/359#issuecomment-623799314_

**Comment by jakekwak** [comment]
@88250 wrapping long lines inside code block.
readme
![Screen Shot 2020-05-05 at 5 52 05 AM](https://user-images.githubusercontent.com/15811943/81058917-0ac25280-8e95-11ea-9afd-6731077c2d12.png)
vditor
![Screen Shot 2020-05-05 at 5 52 25 AM](https://user-images.githubusercontent.com/15811943/81058930-101f9d00-8e95-11ea-96a5-f1cacc4ed329.png)

**Comment by jakekwak** [comment]
@88250 multiline inside `table` 
https://www.markdownguide.org/cheat-sheet/

![Screen Shot 2020-05-05 at 6 04 27 AM](https://user-images.githubusercontent.com/15811943/81059606-53c6d680-8e96-11ea-94f5-9bb6d8d0af8b.png)

**Comment by jakekwak** [comment]
![vditor5](https://user-images.githubusercontent.com/15811943/81099948-50047580-8ed1-11ea-826b-440d166fea26.gif)

**Comment by jakekwak** [comment]
https://www.markdownguide.org/basic-syntax/
![Screen Shot 2020-05-05 at 2 53 37 PM](https://user-images.githubusercontent.com/15811943/81110022-957c6f00-8ee0-11ea-96c0-ef3b91759ec8.png)

**Comment by 88250** [comment]
> ![vditor5](https://user-images.githubusercontent.com/15811943/81099948-50047580-8ed1-11ea-826b-440d166fea26.gif)

https://github.com/Vanessa219/vditor/issues/81

**Comment by jakekwak** [comment]
@88250 problem also https://commonmark.org/help/
