### ISSUE TITLE
Emoji 6️⃣ 

### ISSUE THREAD

**Issue by 88250** [Vanessa219/vditor#365]
![image](https://user-images.githubusercontent.com/873584/81046966-04ab9080-8eec-11ea-99b4-bc05b8ea6fc2.png)

![image](https://user-images.githubusercontent.com/873584/81046816-beeec800-8eeb-11ea-8638-5979de5a56e0.png)

On GitHub:

![image](https://user-images.githubusercontent.com/873584/81046882-dd54c380-8eeb-11ea-8a1f-0b6061b3be3f.png)

**Comment by Lee981265** [comment]
6️⃣ 6️⃣ 6️⃣
