### ISSUE TITLE
when paste, code can not highlight

### ISSUE THREAD

**Issue by 88250** [Vanessa219/vditor#369]
@88250 wrapping long lines inside code block. (WYSIWYG mode)
readme
![Screen Shot 2020-05-05 at 5 52 05 AM](https://user-images.githubusercontent.com/15811943/81058917-0ac25280-8e95-11ea-9afd-6731077c2d12.png)
vditor
![Screen Shot 2020-05-05 at 5 52 25 AM](https://user-images.githubusercontent.com/15811943/81058930-101f9d00-8e95-11ea-96a5-f1cacc4ed329.png)

_Originally posted by @jakekwak in https://github.com/Vanessa219/vditor/issues/363#issuecomment-623986874_

**Comment by Vanessa219** [comment]
@jakekwak preview is nowrap， editor is wrap

![image](https://user-images.githubusercontent.com/970828/81134174-88b25680-8f86-11ea-93c3-e227efe0546e.png)

```
{  
 hotkey: '⌘-⇧-f',  
 name: 'format',  
 tipPosition: 'ne',  
 tip: 'format',  
 className: '',
 icon: '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="768" height="768" viewBox="0 0 768 768"><path d="M342 426v-84h426v84h-426zM342 256v-86h426v86h-426zM0 0h768v86h-768v-86zM342 598v-86h426v86h-426zM0 214l170 170-170 170v-340zM0 768v-86h768v86h-768z"></path></svg>',  
 click: () => {  
   alert('custom toolbar')  
 },  
}
```

**Comment by jakekwak** [comment]
working good at IR mode.
![vditor9](https://user-images.githubusercontent.com/15811943/81136166-67b71a80-8f20-11ea-8689-1af50ef9f7a9.gif)

**Comment by Vanessa219** [comment]
Oh, It's another bug: when paste, code can not highlight.
