### ISSUE TITLE
hover style in Mobile

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#378]
pixel 4 xl chrome 81.0.4044.117
1. `touch bold icon`test`touch bold icon` is not working (iphone is ok)
2. `touch bold icon`test`space``touch bold` is working but not unselected bold icon
![vditor12](https://user-images.githubusercontent.com/15811943/81359332-7aeff480-909e-11ea-87ff-9a4fe597a12f.gif)

**Comment by Vanessa219** [comment]
When you press the toolbar icon, sometimes the keyboard is hidden, but sometimes it is not.
I think this caused this problem.

**Comment by jakekwak** [comment]
I think problem 1 might be pixel 4 xl.
But problem 2 is the same for pixel and iphone. (ICON not toggled)
![vditor14](https://user-images.githubusercontent.com/15811943/81407052-5462a580-9100-11ea-9905-f639e1fe8931.gif)
