### ISSUE TITLE
Not sticky  at IOS

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#379]
Previous Issue https://github.com/Vanessa219/vditor/issues/289

I found [one stackoverflow issue](https://stackoverflow.com/questions/58226087/position-sticky-doesnt-work-when-virtual-keyboard-is-open-in-safari)

please review the [virtual viewport api](https://developer.mozilla.org/en-US/docs/Web/API/Visual_Viewport_API)

**Comment by Vanessa219** [comment]
Thx, but need to set `options.height`, otherwise the toolbar will be shaken
