### ISSUE TITLE
移动端移除侧边提示

### ISSUE THREAD

**Issue by Karthus1110** [Vanessa219/vditor#383]
![image](https://user-images.githubusercontent.com/13864988/81461236-f952b080-91dc-11ea-9d48-6224c52d5592.png)
请问是否有隐藏这个的配置项

**Comment by Vanessa219** [comment]
目前没有，你可以重置一下 CSS

**Comment by 88250** [comment]
我觉得移动端默认就不要显示了，界面小。

**Comment by Karthus1110** [comment]
😂😂其实我只是在预览的时候想隐藏，编辑全文展示的时候 觉得挺好看的😂

**Comment by Vanessa219** [comment]
预览的时候就是隐藏的。

**Comment by Karthus1110** [comment]
可能我的话引起了歧义 我说的是移动端自己做的预览并不是vditor的预览 还是感谢老铁们的回复

**Comment by 88250** [comment]
![5U2B U(9ZYZAD418`T %I}E](https://user-images.githubusercontent.com/873584/81468070-c83fa380-920f-11ea-8e67-f32819fbf3ca.jpg)
