### ISSUE TITLE
image title at wysiwyg

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#385]
`![alt text](https://example.com "title")`
![47](https://user-images.githubusercontent.com/15811943/81486727-676a9800-921c-11ea-8a90-fbb3d50fc539.PNG)

**Comment by Vanessa219** [comment]
If the image is wrapped in link, it is href

**Comment by jakekwak** [comment]
I didn't wrap the link. 
When I put the image like `![alttxt](https://link.com "title")`, after that I want to change the title.

**Comment by jakekwak** [comment]
I think `alt text` field is not important at image tag.  change this input field to `title` field.
