### ISSUE TITLE
[wysiwyg] 在代码块尾部按 arrowdown 插入空行

### ISSUE THREAD

**Issue by gclove** [Vanessa219/vditor#386]
### 编辑模式

所见即所得模式

### 描述问题

当插入一个代码块后，没有好办法另起一行

### 期待的结果

当通过 ```，或快捷键 或 按钮， 自动插入代码块时。应该在后面新增一个空行。

**Comment by Vanessa219** [comment]
you can press this button or use hotkey
![image](https://user-images.githubusercontent.com/970828/81488879-a55dcf80-92a1-11ea-8181-4e88704a9c42.png)

**Comment by gclove** [comment]
@Vanessa219 

1. 如果自动加一个空行的话，代码输入完成后按 `↓` 就能开始其它内容 . 感觉更方便一些

2. 这个快捷键会跟搜狗输入法的中英文切换冲突 ,  `Command + Enter`  `Shift+Enter` 做此处的新行快捷键会更好

![image](https://user-images.githubusercontent.com/3645410/81489881-8cf3b200-92ad-11ea-8944-45b7af411ec8.png)

**Comment by gclove** [comment]
我刚试了一下 **Typora** ,  它好像就是采用自动插入新行解决这个问题的 @Vanessa219

**Comment by Vanessa219** [comment]
那就采取这个吧
> 如果自动加一个空行的话，代码输入完成后按 ↓ 就能开始其它内容 . 感觉更方便一些

`Command + Enter` 一般用于提交，`Shift+Enter` 一般用于软换行，因此不太适合。输入法切换不是按 `caps lock`么，要不重新设置一个快捷键？

**Comment by gclove** [comment]
🥰 非常感谢 @Vanessa219 

按 **`↓`** 才插入空行在编辑之前的代码块时会不会遇到问题，最好在生成代码块样式的时候就插入新行

类似这样

![2020-05-10](https://user-images.githubusercontent.com/3645410/81494777-f8ee0e80-92dd-11ea-88d3-4d71e800313b.gif)

**Comment by Vanessa219** [comment]
你可以体验一下 ir 模式。生成的时候就插入，如果代码块下面本身有内容可能差个空行会不太好。

**Comment by jakekwak** [comment]
If possible, when touched outside(below pane) of block(no text below current block), insert after block.
It means we can remove the two icon at toolbar. (much easier UI at smartphone)

**Comment by Vanessa219** [comment]
> If possible, when touched outside(below pane) of block(no text below current block), insert after block.
> It means we can remove the two icon at toolbar. (much easier UI at smartphone)

https://github.com/Vanessa219/vditor/issues/396
