### ISSUE TITLE
npm install error 

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#387]
npm install error after this commit https://github.com/Vanessa219/vditor/commit/633741cc84cb050b82345ee2ebe7cbd91152aca3 at windows (Mac is ok) 

![48](https://user-images.githubusercontent.com/15811943/81506424-dba84880-92bb-11ea-9e22-7636081554ce.PNG)

**Comment by Vanessa219** [comment]
pls remove node_modules and package-lock.json, and try agian.
