### ISSUE TITLE
你这么优秀，肯定没结婚吧？

### ISSUE THREAD

**Issue by andrew2558** [Vanessa219/vditor#394]
因为只有我配得上你呀，你不是一直在等我吗？我来了。。。。。

**Comment by 88250** [comment]
你来晚了 :trollface: :trollface: :trollface:

**Comment by adlered** [comment]
观光团，人家孩子都上学了 ![](https://github.githubassets.com/images/icons/emoji/trollface.png)

**Comment by biehaiyang** [comment]
哈哈哈哈，伤心欲绝

**Comment by ellenbboe** [comment]
哦吼，完蛋

**Comment by gitors** [comment]
我也来了

**Comment by Lee981265** [comment]
同样是九年义务教育，为何你如此优秀？

**Comment by JssDream** [comment]
都这么优秀了嘛:trollface:
