### ISSUE TITLE
图片居中渲染问题

### ISSUE THREAD

**Issue by chxuu** [Vanessa219/vditor#404]
使用`<center>![](图片地址)</center>`使图片居中，将center标签里面的图片内容解析成了纯文本，预览的结果是`<center>![](图片地址)</center>`。 
期望结果： 预览得到的结果应该使一个居中的图片

**Comment by Vanessa219** [comment]
这个标签没见过，有没有相关的介绍？

目前可以像 GitHub 这样使用
```
<p align="center">
<img alt="Vditor" src="https://b3log.org/images/brand/vditor-128.png" />
</p>
```

**Comment by 88250** [comment]
> HTML5 不支持 `<center>` 标签。请用 CSS 代替。
> 在 HTML 4.01 中，`<center>` 元素 已废弃。
> `<center>` 对其所包括的文本进行水平居中。

https://www.runoob.com/tags/tag-center.html
