### ISSUE TITLE
cursor moving at tables(safari & firefox)

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#407]
mac/chrome(it is ok)
![Chrome-1](https://user-images.githubusercontent.com/15811943/81876423-45d51d80-9548-11ea-8a10-0dcab568a36c.gif)

firefox(mac and windows)
![firefox](https://user-images.githubusercontent.com/15811943/81876438-4d94c200-9548-11ea-9890-caac684e1e80.gif)

safari
![safari](https://user-images.githubusercontent.com/15811943/81876466-60a79200-9548-11ea-8d3b-d8cb81e5fb64.gif)

safari(delete problem)
![safari-delete](https://user-images.githubusercontent.com/15811943/81876486-7026db00-9548-11ea-95f4-6356bb789a6b.gif)

safari (tab)
![safari-table-tab](https://user-images.githubusercontent.com/15811943/81876551-951b4e00-9548-11ea-8b54-dccf883e4579.gif)

**Comment by jakekwak** [comment]
please fix the cursor moving at firefox table.  
I think almost done at firefox (mac and windows)

**Comment by Vanessa219** [comment]
Okay, recently coding vditor.b3log.org.
This week will be repaired.
