### ISSUE TITLE
conflict ctrl+m, alt+L, alt+o(mac safari)

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#408]
![safari-ctrl-m](https://user-images.githubusercontent.com/15811943/81884941-df0f2e80-955e-11ea-93ea-d61a0ffda257.gif)

**Comment by jakekwak** [comment]
I tested other wysiwyg editor. I think this keyboard shortcut have to be disabled at only mac safari.

**Comment by Vanessa219** [comment]
Sorry, in Safari, I do not know how to capture the command + m

**Comment by jakekwak** [comment]
I will close this issue. I don't have any good idea.
