### ISSUE TITLE
delete table When every cells empty

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#413]
![deleteWhenemptycell](https://user-images.githubusercontent.com/15811943/81952391-08b26f00-95cc-11ea-9318-f295ba77201b.gif)

**Comment by Vanessa219** [comment]
This is a feature, but not friendly. 
In IR mode, I don't know how to remove this table, so this function was added...

**Comment by jakekwak** [comment]
@Vanessa219 Ok, It is OK.
