### ISSUE TITLE
Not showing Video at wysiwyg mode

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#416]
Is it correct?

![vditor27](https://user-images.githubusercontent.com/15811943/82009093-ff5ced00-9633-11ea-8b69-570f508ccc37.gif)

**Comment by Vanessa219** [comment]
Yes, in the "WYSIWYG" and "ir" mode, if you convert the text link to an automatic link, the original text has changed, so the text link cannot be parsed
