### ISSUE TITLE
上传图片成功后如何在当前光标处显示？

### ISSUE THREAD

**Issue by tianzhich** [Vanessa219/vditor#417]
### 编辑模式

所见即所得模式

### 描述问题

1. 请问像[demo](https://hacpai.com/guide/markdown)里这种上传完图片就直接在编辑器中光标位置显示的操作，是需要额外的一些代码还是配置option.upload就可以？

2. 我配置了upload的format，但是方法好像没有执行。请问如何实现1的效果呢。有没有一些online的demo，而且可以看到示例代码那种

### 期待的结果

图片上传成功后能正确在Markdown编辑器光标处显示

### 其他信息

目前上传图片成功后format函数在断点处没有停下，貌似没有执行。success回调中responseText还是原来的结构。而且无法知道怎么实现demo的效果

**Comment by Vanessa219** [comment]
像 https://github.com/Vanessa219/vditor/blob/master/demo/index.js 配置就可以了
你的 format 是怎么配置的？

**Comment by tianzhich** [comment]
> 像 https://github.com/Vanessa219/vditor/blob/master/demo/index.js 配置就可以了
> 你的 format 是怎么配置的？

upload配置如下：
```typescript
const upload = {
  url: `xx`,
  format(files: File[], respText: string) {
    const { data, result }: CDNResponse = respText ? JSON.parse(respText) : {};
    const success = result === 1 && data.success;

    const errFiles = success
      ? []
      : files.filter((file, i) => data.fileResults[i].status === 0).map(file => file.name);
    const succMap = success
      ? files.reduce((prev, cur, i) => {
          return {
            ...prev,
            [cur.name]: data.fileResults[i].cdnUrl
          };
        }, {})
      : {};
    const formatRes: VditorResponse = {
      code: 0,
      msg: '',
      data: {
        errFiles,
        succMap
      }
    };
    return JSON.stringify(formatRes);
  },
  extraData: {
    pid: 'my-pid'
  }
}
```

`success`和`error`回调就是简单打印了下参数

**Comment by tianzhich** [comment]
其实我在`success`回调里面拿到`responseText`，然后使用`vditor.inserValue()`倒是也可以实现效果。

但是我看你给的示例代码里面没有写回调，我理解只要将返回值转换成你们的格式应该就可以实现效果了吧。但是formate应该是没执行，`success`回调中的参数是formate前的

**Comment by Vanessa219** [comment]
你看一下请求，需要 url post 返回 200 才会触发

**Comment by Vanessa219** [comment]
哦。配置了 success 就不会走这个了。

**Comment by tianzhich** [comment]
理解了，我以为format只是中间一层，把数据转换后还会执行success。那我想问一下format的执行时机呢？如果我不想自己执行插入，使用了format，但是我还想执行success和error回调。这时候是在format中执行吗？他的时机和success一样吗

**Comment by Vanessa219** [comment]
format 只是为了转换后端数据以适应前端的插入和展现，调用时机如下
```
            if (xhr.status === 200) {
                if (vditor.options.upload.success) {
                    vditor.options.upload.success(editorElement, xhr.responseText);
                } else {
                    let responseText = xhr.responseText;
                    if (vditor.options.upload.format) {
                        responseText = vditor.options.upload.format(files as File [], xhr.responseText);
                    }
                    genUploadedLabel(responseText, vditor);
                }
            } else {
                if (vditor.options.upload.error) {
                    vditor.options.upload.error(xhr.responseText);
                } else {
                    vditor.tip.show(xhr.responseText);
                }
            }
```

**Comment by tianzhich** [comment]
> format 只是为了转换后端数据以适应前端的插入和展现，调用时机如下
> 
> ```
>             if (xhr.status === 200) {
>                 if (vditor.options.upload.success) {
>                     vditor.options.upload.success(editorElement, xhr.responseText);
>                 } else {
>                     let responseText = xhr.responseText;
>                     if (vditor.options.upload.format) {
>                         responseText = vditor.options.upload.format(files as File [], xhr.responseText);
>                     }
>                     genUploadedLabel(responseText, vditor);
>                 }
>             } else {
>                 if (vditor.options.upload.error) {
>                     vditor.options.upload.error(xhr.responseText);
>                 } else {
>                     vditor.tip.show(xhr.responseText);
>                 }
>             }
> ```

感谢~觉得可以在文档中说明一下

**Comment by Vanessa219** [comment]
谢谢提醒，立马去更新
