### ISSUE TITLE
outline after update at smartphone

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#419]
![Screen Shot 2020-05-16 at 3 51 14 PM](https://user-images.githubusercontent.com/15811943/82130027-4ca0a200-978d-11ea-9e27-ffeeca17721d.png)

**Comment by Vanessa219** [comment]
In mobile, hide outline?

**Comment by jakekwak** [comment]
automatically no outline in mobile(showing outline in desktop)
