### ISSUE TITLE
在内联数学公式前进行删除操作会删除公式

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#42]
first click, delete key after second click

![inline](https://user-images.githubusercontent.com/15811943/71829239-0ad25300-3059-11ea-9c57-39b50d3cd4b1.gif)

**Comment by Vanessa219** [comment]
![image](https://user-images.githubusercontent.com/970828/71863189-11cf9300-3137-11ea-8a57-4a779ee76783.png)

0.27s（45 frame） to 0.61s （46 frame）, Could you tell me what keys you pressed？

**Comment by jakekwak** [comment]
click, enter, click, enter, delete

**Comment by jakekwak** [comment]
Still not working. click, enter, (wrong cursor location), click, click, delete
![math](https://user-images.githubusercontent.com/15811943/71909519-0e331080-3125-11ea-90c7-3468fdb49835.gif)
