### ISSUE TITLE
inserted one line before table block(windows/Firefox)

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#422]
![vditor33](https://user-images.githubusercontent.com/15811943/82401681-14fd5880-9a20-11ea-83a8-c5bb162c6fb4.gif)

**Comment by Vanessa219** [comment]
Sorry, I can not reproduce. pls update and try again

**Comment by jakekwak** [comment]
![vditor2](https://user-images.githubusercontent.com/15811943/82563048-f5f3e900-9b3b-11ea-8e72-6a3e6cfc7c77.gif)

**Comment by 88250** [comment]
![f](https://user-images.githubusercontent.com/873584/82572436-e36ac580-9bb6-11ea-9428-7bd8919cc9e5.gif)

**Comment by jakekwak** [comment]
@88250 try to modify col1, col2, col3 to test.

**Comment by jakekwak** [comment]
windows/firefox
![vditor36](https://user-images.githubusercontent.com/15811943/82672806-75e68580-9c06-11ea-8a7d-cc9fcfd00a76.gif)

**Comment by Vanessa219** [comment]
f9856ec4a23041e6620a07030426a37ab063e2fb
