### ISSUE TITLE
same problem at the Android studio

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#423]
I installed the Android studio to check my Pixel 4 XL's problem using emulator with the latest image.

I got the same problem. (also can not delete the line with backspace.)

I think the problem happen only the Google's original image. (or please check the build number. (2020 version)

![studio](https://user-images.githubusercontent.com/15811943/82471173-f46ae800-9a8b-11ea-9576-5a6b52f6c763.gif)

**Comment by Vanessa219** [comment]
I installed Android Studio, how to open the simulate

![image](https://user-images.githubusercontent.com/970828/82547605-9c67da80-9b8c-11ea-9770-42b4ef026c6c.png)

**Comment by jakekwak** [comment]
Configure>AVD Manger
![9](https://user-images.githubusercontent.com/15811943/82562150-4d915500-9b3a-11ea-9e2e-56c30fc32807.PNG)
![10](https://user-images.githubusercontent.com/15811943/82562156-4ff3af00-9b3a-11ea-853b-07295a0ba615.PNG)
![11](https://user-images.githubusercontent.com/15811943/82562161-51bd7280-9b3a-11ea-9b88-eb8f02a0127f.PNG)
![12](https://user-images.githubusercontent.com/15811943/82562166-52ee9f80-9b3a-11ea-99fe-805b52a210e0.PNG)

**Comment by Vanessa219** [comment]
Thx, but 

![image](https://user-images.githubusercontent.com/970828/82570950-dcdb4e80-9bb4-11ea-84ba-95a90173c2a9.png)

**Comment by jakekwak** [comment]
You can access via IP address (this one is another computer)

**Comment by Vanessa219** [comment]
![QQ20200521-231347](https://user-images.githubusercontent.com/970828/82573825-d6e76c80-9bb8-11ea-9937-fae34d20ec55.gif)

**Comment by jakekwak** [comment]
Hmm, I don't know the difference between here and there. 
All of my device(Pixel 4 XL, Android Studio, etc) has same problem.
What is your main computer? Mac or windows?

**Comment by Vanessa219** [comment]
Mac, I follow you choose Pixel 3 XL, not Pixel 4 XL
![image](https://user-images.githubusercontent.com/970828/82576893-d2bd4e00-9bbc-11ea-9f0f-f3043f542e6d.png)

**Comment by jakekwak** [comment]
My real device is PIXEL 4 XL.  That Pixel 3 XL means just screen size and density.
For example, You can make Pixel 4 XL using 1440x3040 and 537dpi.

**Comment by jakekwak** [comment]
pls let me know the version of node and npm. thanks

**Comment by Vanessa219** [comment]
Maybe I have not x84_24?
![image](https://user-images.githubusercontent.com/970828/82627453-04660180-9c1d-11ea-8638-0a1b3b496f6c.png)
![image](https://user-images.githubusercontent.com/970828/82627497-1c3d8580-9c1d-11ea-8b01-8f4348f7ccf4.png)
![image](https://user-images.githubusercontent.com/970828/82627512-23649380-9c1d-11ea-94e9-95102d4b3954.png)
