### ISSUE TITLE
支持调整字号和文字颜色

### ISSUE THREAD

**Issue by Vanessa219** [Vanessa219/vditor#428]
`<font>` 标签大部分平台都不支持，所以文档中需要特别注明。

**Comment by yuanxiongwei** [comment]
是否会支持字号和文字颜色？

**Comment by Vanessa219** [comment]
目前标签已经可以用，准备使用 https://github.com/88250/lute/issues/89 来进行颜色和字号的支持

**Comment by 88250** [comment]
暂时不考了。
