### ISSUE TITLE
localStorage被禁用时，报错

### ISSUE THREAD

**Issue by TobiasTao** [Vanessa219/vditor#429]
### 截屏

![image](https://user-images.githubusercontent.com/37654563/82719268-90d6f980-9cdb-11ea-82bf-64dd51c20057.png)

### 临时修复方法
将 index.min.js 中：
```
var n=localStorage.getItem(e.options.cache.id);
```
修改为
```
 var n = e.options.cache.enable? localStorage.getItem(e.options.cache.id): ""
```
并将 cache.enable 设为 false

**Comment by Vanessa219** [comment]
如何禁用 localStorage

**Comment by TobiasTao** [comment]
chrome中可以设置
chrome://settings/content/cookies
![image](https://user-images.githubusercontent.com/37654563/82722061-b40ea280-9cf5-11ea-86c0-f3416021ef2b.png)

**Comment by ixiumu** [comment]
> 如何禁用 localStorage

不启用缓存的情况下,依然会触发clearCache  报 localStorage 禁用的错误
```
n.prototype.clearCache = function() {
    localStorage.removeItem(this.vditor.options.cache.id)
}
```
