### ISSUE TITLE
支持 TextBundle 

### ISSUE THREAD

**Issue by JackalZhao** [Vanessa219/vditor#436]
一直以来，md 文档插入图片都是问题：

* 用图床链接，不稳定

* 用本地文件链接，容易丢

这也是我在用 md 做记录时候的烦恼。

不过，Marked 开发者和 Ulysses 团队开发出了一种解决方法，就是 TextBundle，简要解释一下，它是这样的结构：

一个叫 文档.textbundle 的文件夹，内包含：

o    一个 assets 文件夹，用于存放图片等附件

o    一个 info.json 文件，用于存放相关的元数据

o    一个 text.md 文件，用于存放文档内容。文档通过相对路径引用 assets 文件夹内的图片和其它媒体文件。

可以实现一个文包内，既包含 md 文档，也包含图片，预览时无需询问权限，同时又方便直接编辑，非常便捷。

每一个文档都存储在一个 textbundle 中，这样，即便导出，复制到其它设备、平台上，都可以用各种 markdown 编辑器打开文档，正常浏览里面的图片。

Ulysses, Bear这样的流行的写作工具，甚至是Mindnode等思维导图工具，都支持 textbundle。

如果支持textbundle格式。那么我们在快速写作的时候，就可以更加安心。因为我们确认所有的创作内容都可以方便导出带格式、带图片资源版本，轻松在其他专用工具中进一步加工。

**Comment by 88250** [comment]
该功能会在链滴笔记中实现，谢谢。
