### ISSUE TITLE
使用ace或codemirror增加代码块的编写体验

### ISSUE THREAD

**Issue by TobiasTao** [Vanessa219/vditor#442]
目前代码块编写体验欠佳，能否考虑集成 [Ace](https://ace.c9.io/) 或者 [CodeMirror](https://codemirror.net/)来完善用户体验？

**Comment by 88250** [comment]
谢谢建议，但不考虑集成其他编辑器，代码块一般场景下是从 IDE 中直接拷贝进来的。后期会考虑实现 https://github.com/Vanessa219/vditor/issues/110 对换行进行优化。
