### ISSUE TITLE
table(IR mode)

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#449]
I think prefix ==> suffix.
ir/process.ts line 180
```
html = `${prefix}${range.toString()}<wbr>${prefix}`;
```

Is is possible to make same as wysiwyg mode. (select first cell)
![vditor55](https://user-images.githubusercontent.com/15811943/82924235-aa797a80-9f41-11ea-9b2f-b8f01ddb2bdc.gif)

**Comment by Vanessa219** [comment]
I can't understand gif.

**Comment by jakekwak** [comment]
selected first cell like wysiwyg mode.
![vditor58](https://user-images.githubusercontent.com/15811943/82977224-daa73480-9fa6-11ea-98b4-a91f8b2f3436.gif)
