### ISSUE TITLE
IR 模式保留 Emoji 原始输入

### ISSUE THREAD

**Issue by TobiasTao** [Vanessa219/vditor#451]
希望可以添加一个配置选项，让 `:emoji:` 不会自动转成真正的 emoji图标。
类似于 Typora：
![image](https://user-images.githubusercontent.com/37654563/82969020-369ea700-a001-11ea-93a0-3113ee7064bf.png)

**Comment by 88250** [comment]
即时渲染模式可以通过配置项决定是否保留 alias，但是所见即所得模式似乎不好处理，有建议么？

**Comment by Vanessa219** [comment]
我觉得不用配置，如果用户输入的是 :xxx: 就保留，如果直接用输入法输入表情就不用处理。

wysiwyg 直接表情？

**Comment by jakekwak** [comment]
Typing :xxx: should keep :xxx: in markdown mode.
![vditor68](https://user-images.githubusercontent.com/15811943/83960748-eec61e00-a851-11ea-8db9-a95dca33b72d.gif)

**Comment by 88250** [comment]
已做调整，保留原始输入：

![ir_emoji](https://user-images.githubusercontent.com/873584/88484463-1e1b2080-cfa1-11ea-92b0-ff0f1c27e2c5.gif)
