### ISSUE TITLE
请教一下如何将图片上传到七牛云储存

### ISSUE THREAD

**Issue by rieval** [Vanessa219/vditor#457]
我看了下文档说明，好像是自己内部实现了上传策略，只需要提供 `url` 和 `token` 就能上传图片。

但我使用的 [qiniu-js](https://developer.qiniu.com/kodo/sdk/1283/javascript) 也是使用内部实现的上传策略。

我不知道该如何将这两者结合在一起，请指教。

我之前用过一款 `markdown` 编辑器是当选中本地的图片后会触发一个自定义上传的函数，这个函数有两个参数，一个是 `File` 对象，一个是字符串（`markdown` 图片的 `url` ）

**Comment by 88250** [comment]
你好，请参考 [Vditor 的文件上传 demo](https://vditor.b3log.org/demo/advanced-upload.html)，如果还有疑问欢迎跟帖，我先关闭 issue 了。
