### ISSUE TITLE
关于 Table 操作的优化

### ISSUE THREAD

**Issue by 88250** [Vanessa219/vditor#458]
https://hacpai.com/article/1438049659432/comment/1590629034236?r=88250

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/pull/456

**Comment by codingcn** [comment]
我觉得`tui-editor`的表格操作是比较舒服的，无论是创建表格（拖选）还是给表格增删行（通过右键），ui表现上都特别简洁。
`https://ui.toast.com/tui-editor/`

**Comment by Vanessa219** [comment]
Table 上已有相关操作
![image](https://user-images.githubusercontent.com/970828/89093392-9132f580-d3ec-11ea-88f1-e1a6de0a096c.png)
