### ISSUE TITLE
add row 添加快捷键

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#46]
1. more cell  (suggestion: shift+tab)
2. how to escape (same as other shortcut key shift+ctrl+e)
![table](https://user-images.githubusercontent.com/15811943/71915534-d3cf7080-3130-11ea-8df9-0c8311f27d37.gif)

**Comment by Vanessa219** [comment]
2. escape: use `\`

**Comment by Vanessa219** [comment]
use `->`

**Comment by jakekwak** [comment]
I can't input any more text after cell.
![Screenshot_20200108-173836](https://user-images.githubusercontent.com/15811943/72030737-e33cdf80-323e-11ea-831d-e68da5d3438c.png)
