### ISSUE TITLE
换行符被吞掉或折叠

### ISSUE THREAD

**Issue by Hansanshi** [Vanessa219/vditor#464]
----

### 编辑模式

即时渲染模式

### 系统环境
macOS 10.15.3
浏览器是 FireFox 76.0.1
Chrome 83.0

开发环境是vue + elementUI

### 描述问题

您好，换行符遇到了很多困惑
尝试通过Vditor的 setValue方法设置一段包含多个换行符的文本，发现如果有连续的两个或三个换行符，会被折叠为包含一个空格的一行字符串；
如果是四个及以上，则所有换行都会被吞掉。
不知道这是刻意为之还是bug

还有一个仅在Chrome浏览器下会出现的问题，开头的换行符至多输入一个，再按回车键，不会再有换行的效果

### 期望结果
我的理解是，应当尽可能展示用户的原始输入，无论是多少换行，有意义或无意义，都应当展示出来，不进行转换

**Comment by 88250** [comment]
你好，请参考[这里](https://github.com/Vanessa219/vditor/issues/321#issuecomment-621075435)的讨论。

**Comment by Hansanshi** [comment]
理解，但仍觉得不太好，请问可否做成一个配置项，或者您可以说说大概在哪个地方改改吗 @88250

**Comment by 88250** [comment]
抱歉，目前我们没有去做这个的计划，大致的解决方案我已经在前面提到的讨论中进行过描述。

**Comment by Hansanshi** [comment]
多谢
