### ISSUE TITLE
字数计数器的bug

### ISSUE THREAD

**Issue by TobiasTao** [Vanessa219/vditor#465]
字数是1，正确：
![image](https://user-images.githubusercontent.com/37654563/83350837-88349200-a371-11ea-86d4-1209ddea394a.png)
按下enter键后，变成了2，应该是1：
![image](https://user-images.githubusercontent.com/37654563/83350819-6dfab400-a371-11ea-85a2-3d6d3d7b9fb6.png)
另外，无法正确统计英文单词，输入hello，显示7，应该是2：
![image](https://user-images.githubusercontent.com/37654563/83350929-36d8d280-a372-11ea-90c8-2b86b5db25ce.png)

希望可以像typora那样同时显示字数与字符
![image](https://user-images.githubusercontent.com/37654563/83350794-3c81e880-a371-11ea-91ea-9725e7ffd1ad.png)

**Comment by 88250** [comment]
感谢反馈，稍后我们研究一下如何实现 🙏

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/315

**Comment by Vanessa219** [comment]
合并到 #315 中进行处理

**Comment by Vanessa219** [comment]
@TobiasTao 问一下你的是什么浏览器，看上去工具栏图标没居中

**Comment by TobiasTao** [comment]
chrome

**Comment by Vanessa219** [comment]
很奇怪，我这里是居中的

![image](https://user-images.githubusercontent.com/970828/83948523-48c5e400-a850-11ea-9128-02c3fb1fd432.png)

**Comment by TobiasTao** [comment]
![image](https://user-images.githubusercontent.com/37654563/83948640-110b6c00-a851-11ea-8781-4574bf22cb13.png)

**Comment by Vanessa219** [comment]
@TobiasTao 可以的话挪到 svg 上发我看看，谢谢了

**Comment by TobiasTao** [comment]
![image](https://user-images.githubusercontent.com/37654563/84036388-bc422f80-a9cf-11ea-9fc9-ca10d82107c8.png)

**Comment by Vanessa219** [comment]
为啥我的是好的。帮忙看看在 https://hacpai.com/guide/markdown 这个页面正常么？
![image](https://user-images.githubusercontent.com/970828/84100192-e8949500-aa3d-11ea-98d1-1634ffaeab83.png)

**Comment by TobiasTao** [comment]
这个是好的：
![image](https://user-images.githubusercontent.com/37654563/84107197-9fe5d780-aa4f-11ea-8b31-e2b2b7cf7bba.png)

**Comment by TobiasTao** [comment]
我看了下，除了 `完整示例`，其它都有这个问题。
![image](https://user-images.githubusercontent.com/37654563/84107346-f6ebac80-aa4f-11ea-87de-3c3e6dc7335d.png)

**Comment by Vanessa219** [comment]
系统和 chrome 版本报一下。我在 mac 和 Windows 上看了都没问题呀

**Comment by TobiasTao** [comment]
![image](https://user-images.githubusercontent.com/37654563/84218825-c7957800-ab01-11ea-89ce-302c28fbf5af.png)
![image](https://user-images.githubusercontent.com/37654563/84218844-d419d080-ab01-11ea-88fc-d8704177c1b6.png)

**Comment by Vanessa219** [comment]
要哭了。要不小哥哥帮我对比一下 demo 和 hacpai.com 上为啥两个显示不一样呢，都是一样的代码呀。

**Comment by TobiasTao** [comment]
可能是这个font-size？：
![image](https://user-images.githubusercontent.com/37654563/84221854-bc921600-ab08-11ea-87e0-209fbaa5189c.png)

**Comment by TobiasTao** [comment]
可是这里也有font-size，但没问题：
![image](https://user-images.githubusercontent.com/37654563/84222430-25c65900-ab0a-11ea-8d99-218303bcfa4d.png)

**Comment by Vanessa219** [comment]
> 可能是这个font-size？：
> ![image](https://user-images.githubusercontent.com/37654563/84221854-bc921600-ab08-11ea-87e0-209fbaa5189c.png)

但是还有一个上传位置不对呀

**Comment by TobiasTao** [comment]
![image](https://user-images.githubusercontent.com/37654563/84232601-359e6700-ab23-11ea-91d5-19aa9ae69551.png)

把div改为button：
![image](https://user-images.githubusercontent.com/37654563/84232525-0a1b7c80-ab23-11ea-908c-4e028c561e26.png)

**Comment by Vanessa219** [comment]
好奇怪，我再看看。多谢

**Comment by TobiasTao** [comment]
屏幕没有缩放
![image](https://user-images.githubusercontent.com/37654563/84333689-0b03eb00-abc3-11ea-9222-7f8bafd22ebf.png)

font-size: 0 有用

**Comment by Vanessa219** [comment]
由于 https://hacpai.com/article/1549638745630/comment/1576226645918?r=Vanessa，上传的 div 不能改为 button。在 div 上加上 font-size:0 可行否

**Comment by TobiasTao** [comment]
可以：
![image](https://user-images.githubusercontent.com/37654563/84342202-8ec7d280-abd7-11ea-8f51-b56863d6bc45.png)

**Comment by Vanessa219** [comment]
非常感谢你的耐心
