### ISSUE TITLE
chrome extensions中使用，无法聚焦到编辑区

### ISSUE THREAD

**Issue by gorkys** [Vanessa219/vditor#468]
### 描述问题

在开发chrome extensions使用vditor时，渲染后，无法聚焦到编辑区。click时会激活工具栏首个按钮。

### 截屏或录像
[
![工艺](https://user-images.githubusercontent.com/29664101/83382678-38f46d00-a416-11ea-94bb-88efe9dec6fc.gif)
](url)

### 其他说明
vditor是本地引用，其中代码中包含`lute.min.js`而引发的CSP，已在清单文件中定义。

**Comment by Vanessa219** [comment]
在页面中不会，只有在插件中会么？
CSP 可以[配置 cdn](https://hacpai.com/article/1549638745630#CDN-%E5%88%87%E6%8D%A2) 为本地进行使用。

**Comment by gorkys** [comment]
不在插件中运行，也是一样的。不知道是什么原因导致，没有任何信息抛出。

**Comment by gorkys** [comment]
找到问题了
```
<label>
     内容
     <div id="artContent"></div>
</label>
```
因为vditor放在了label标签内导致的。
