### ISSUE TITLE
希望粘贴网页图片、本地图片时可以触发 upload.handler()

### ISSUE THREAD

**Issue by TobiasTao** [Vanessa219/vditor#469]
### 你在什么场景下需要该功能？
自定义upload逻辑：
```js
 upload: {
      accept: 'image/*',
      handler(files) {
        handleImg(files);
      }
    },
```
现在，如果复制网页中的图片：
![image](https://user-images.githubusercontent.com/37654563/83394376-0dc84880-a42b-11ea-9a67-5540104315eb.png)
将其粘贴，那么这个路径是图片源连接：
![image](https://user-images.githubusercontent.com/37654563/83394472-3cdeba00-a42b-11ea-8b6d-67ec8ce3147f.png)
自定义的handler() 未生效，希望粘贴网页图片时可以触发 upload.handler()

**Comment by TobiasTao** [comment]
粘贴本地图片时也无法触发 upload.handler()

**Comment by Vanessa219** [comment]
粘贴的时候可以使用 [linkToImgUrl](https://hacpai.com/article/1549638745630#options-upload)

**Comment by TobiasTao** [comment]
我在写一个vscode插件，想用vditor替代内置的markdown编辑器。
https://github.com/TobiasTao/vscode-md
我现在的想法是拖拽（已实现）、剪切板粘贴的图片都可以通过 upload.handler() 拦截下来，进行自定义处理，例如写入本地，上传到图床等。
用 linkToImgUrl 好像无法完成

**Comment by jakekwak** [comment]
This idea is for mobile.  At the mobile,  everybody is not typing.  they just copy & paste.
If it is useful, I will PR.  I think @Vanessa219 will upgrade my code.

![vditor66](https://user-images.githubusercontent.com/15811943/83478196-db364400-a45a-11ea-97e3-682b631a19ae.gif)

**Comment by Vanessa219** [comment]
In SV mode, should be wait  #355 & #354

**Comment by Vanessa219** [comment]
> This idea is for mobile. At the mobile, everybody is not typing. they just copy & paste.
> If it is useful, I will PR. I think @Vanessa219 will upgrade my code.
> 
> ![vditor66](https://user-images.githubusercontent.com/15811943/83478196-db364400-a45a-11ea-97e3-682b631a19ae.gif)

I think @TobiasTao wants to listen to the paste event and trigger `upload.handler`, what you want to PR is to paste the URL and convert it to an image?

**Comment by jakekwak** [comment]
I don't know what @TobiasTao exactly want , but I think he want `upload.handler` to make `markdown image text` when he copy & paste the image. 
If it is correct,  this one is much better than 'upload.handler`.

**Comment by TobiasTao** [comment]
I want: from`handler(files: File[])` to `handler(files: File[] | string)`
if drag and drop images, I can get `File[]` in handler, if  paste a  image from clipboard, I can get `string `in handler, which is image's path.

**Comment by Vanessa219** [comment]
handler 和 linkToImgUrl 的参数和返回值不一致，因此新加了一个 `options.upload.linkToImgCallback`

https://github.com/Vanessa219/vditor/issues/614

**Comment by aircjm** [comment]
你好 我试了下粘贴剪贴板的图片

![image](https://user-images.githubusercontent.com/18283183/100101580-6427b880-2e9d-11eb-9682-028285c2dc3e.png)
这种方式是可以触发上传,调用后端接口的

但是我想要自定义上传带其他参数 所以想要使用axios调用的方式上传 但是只有上传本地文件是可以进入的
![image](https://user-images.githubusercontent.com/18283183/100102199-3abb5c80-2e9e-11eb-86c0-d3153b1fdb02.png)

粘贴剪贴板图片(不是图片地址)是截图
是无法进handler的  这个有什么办法进去吗?? 


```js
        upload: {
          filename (name) {
            return name.replace(/\?|\\|\/|:|\||<|>|\*|\[|\]|\s+/g, '-')
          },
          handler (files) {
            debugger
            console.log(files)
            for (let i = 0; i < files.length; i++) {
              that.uploadFiles(files[i])
                .then({})
                .catch(e => {
                  console.log(e)
                })
            }
          },
          linkToImgUrl (files) {
            debugger
          }
        }
```
