### ISSUE TITLE
改进ir模式下table编辑体验

### ISSUE THREAD

**Issue by TobiasTao** [Vanessa219/vditor#470]
### 你在什么场景下需要该功能？
wysiwyg模式下有悬浮框，表格编辑体验很好：
![image](https://user-images.githubusercontent.com/37654563/83402921-44f22600-a43a-11ea-9c49-eae1682171e8.png)
可不可以给ir模式下的表格也加一个这样的悬浮框？

**Comment by Vanessa219** [comment]
IR 模式下想弄的简洁一些，所以都没有添加情景菜单。你试一下快捷键是否可以解决问题？

**Comment by jakekwak** [comment]
we need some icon menu on a touch device like smartphone and tablet. https://github.com/Vanessa219/vditor/issues/467
I think simple IR mode is good only Desktop.(we can type the text without mouse and cursor key lik VI)
If possible, I suggest 9 different menu mode.
(wysiwyg, IR, markdown), (desktop, tablet, smartphone)

**Comment by Vanessa219** [comment]
This is too complicated. Maybe we can add Phone mode.

**Comment by TobiasTao** [comment]
I will close this issue, maybe you need to open a new issue for Phone mode @jakekwak

**Comment by zaaack** [comment]
快捷键太麻烦了，有优化的可能么？
