### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#474]
When put the image like below at github.
```
![alt text](https://user-images.githubusercontent.com/15811943/83709014-3dba4c00-a5e3-11ea-8e1d-49b136a0b982.jpg "image")
```

![74](https://user-images.githubusercontent.com/15811943/83709625-8d4d4780-a5e4-11ea-8586-469c15a8311a.PNG)

but missing A links
![73](https://user-images.githubusercontent.com/15811943/83709668-a0601780-a5e4-11ea-8501-dc346b2ff638.PNG)

It means when you clicked the image, you can see the original image.

**Comment by 88250** [comment]
Which edit mode do you use?

**Comment by jakekwak** [comment]
@88250 this one is preview mode.

**Comment by 88250** [comment]
In GFM spec https://github.github.com/gfm/#images 

```markdown
![foo](/url "title")
```

Render result:

```html
<p><img src="/url" alt="foo" title="title" /></p>
```

So, I think this is a "feature" of GitHub.  We do not follow it at present, but we follow spec as we can. 
Thank you for pointing out this issue.

**Comment by jakekwak** [comment]
@88250 Thanks.
I will use
```
[![foo](/url "title")](/url)
```
When I uploaded the big picture image from smartphone,  The traffic is too much.
I want to use some thumbnail function to reduce to 800x600.  When click the image, can see the original image.  (if the limit of hosting server, just keep the thumbnail image only.)
