### ISSUE TITLE
从网页和其它 md 编辑器中复制的 iframe 和 视频标签 无法粘贴到 Vditor

### ISSUE THREAD

**Issue by JackalZhao** [Vanessa219/vditor#475]
例如，在 Typora 中的文章有一 video 标签、一 iframe，全选文章复制后，复制到 Hacpai Vditor 或者 链滴笔记后，发现这两个标签都没有被粘贴上。

**Comment by 88250** [comment]
做了一些修复，稍后发版，有空的话请帮忙验证，谢谢！
