### ISSUE TITLE
快捷键映射图

### ISSUE THREAD

**Issue by JackalZhao** [Vanessa219/vditor#476]
HacPai 中关于 Vditor 的快捷键使用的是表格方式，如下图：

![Screenshot_2020-06-05-00-27-25-757_com android chrome](https://user-images.githubusercontent.com/19181833/83785455-e8a23700-a6c3-11ea-9aba-3cf8a4b5dde1.jpg)

虽然很详尽，但是表格列出快捷键本身就不符合直觉。

由此，我推荐再使用 ShortcutMapper 做一个快捷键映射图，如 [这个PS快捷键示例](http://waldobronchart.github.io/ShortcutMapper/#AdobePhotoshop)，这是个开源项目，简单填入就可以生成一张可交互的快捷键地图。

**Comment by lhlyu** [comment]
太复杂了，还不如表格

**Comment by Vanessa219** [comment]
@JackalZhao 欢迎 PR 到 https://github.com/Vanessa219/b3log-index/tree/master/src/vditor 项目中
