### ISSUE TITLE
add tip to footnote 

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#478]
Is it correct?

IR mode
![Screen Shot 2020-06-06 at 9 15 37 PM](https://user-images.githubusercontent.com/15811943/83958757-1493f880-a83b-11ea-85c0-4e2fc02c0dd0.png)

Wysiwyg mode
![Screen Shot 2020-06-06 at 9 15 59 PM](https://user-images.githubusercontent.com/15811943/83958758-1bbb0680-a83b-11ea-95b0-cf37640b1736.png)

Preview Mode
![Screen Shot 2020-06-06 at 9 18 26 PM](https://user-images.githubusercontent.com/15811943/83958800-a7349780-a83b-11ea-91c3-850e4d0bab5c.png)

**Comment by Vanessa219** [comment]
yes, do you have any good suggestion?

**Comment by jakekwak** [comment]
No,  thanks
but this one is good(preview mode)
![vditor70](https://user-images.githubusercontent.com/15811943/83992563-59d92880-a916-11ea-8cb3-2599a4a8f5e5.gif)

**Comment by Vanessa219** [comment]
but bignote can not show all tip

**Comment by jakekwak** [comment]
When showing all tip,  it covered all text, so it limited the number of char.
