### ISSUE TITLE
react 如何引入vditor哈？

### ISSUE THREAD

**Issue by xhaoxiong** [Vanessa219/vditor#483]
直接通过组件的方式引入直接报错了？

import Vditor from 'vditor'
import "vditor/src/assets/scss/index.scss"

<>
<Vditor/>
</>

**Comment by xhaoxiong** [comment]
@Vanessa219 没啥问题了，就是之前对demo不是很理解，用ref 写了下

**Comment by Vanessa219** [comment]
好的，那我关闭了。
