### ISSUE TITLE
IR 模式下，<details>的编辑问题

### ISSUE THREAD

**Issue by TobiasTao** [Vanessa219/vditor#485]
![1](https://user-images.githubusercontent.com/37654563/84341695-52e03d80-abd6-11ea-9f9c-121ba160b68a.gif)
'ir'模式下编辑区域会自动关闭

**Comment by Vanessa219** [comment]
?

**Comment by TobiasTao** [comment]
刚刚按错快捷键了。。。

**Comment by TobiasTao** [comment]
所见即所得模式编辑时预览区域也会自动关闭：
![2](https://user-images.githubusercontent.com/37654563/84342364-fb42d180-abd7-11ea-8334-2d943e1cc80d.gif)

**Comment by Vanessa219** [comment]
一楼是 bug，展开的话需要修改为
```
<details open>
<summary>这里是摘要部分fs。eswesddf</summary>
这里是细节部分。weesdffsffd
</details>
```

**Comment by 88250** [comment]
@Vanessa219 Lute 上已经修改。另外这里间距似乎不够：

![image](https://user-images.githubusercontent.com/873584/84557978-ee51e980-ad61-11ea-89fe-25710283ae5c.png)
