### ISSUE TITLE
为 vditor.b3log.org/demo 添加源码

### ISSUE THREAD

**Issue by Vanessa219** [Vanessa219/vditor#489]
如：https://www.jeasyui.com/demo/main/index.php

**Comment by ronger-x** [comment]
[Vant](https://youzan.github.io/vant/#/zh-CN/home)
建议新增,变更参数/方法时加入版本号及不可用状态
![image](https://user-images.githubusercontent.com/29698602/87274345-23428f00-c50e-11ea-97e4-f79cac03a4b3.png)

**Comment by Vanessa219** [comment]
目前使用的人比较少。从下个版本开始添加吧
