### ISSUE TITLE
所见即所得与即时渲染模式下，长文输入卡顿

### ISSUE THREAD

**Issue by lixiang810** [Vanessa219/vditor#490]
### 编辑模式  
所见即所得模式  
即时渲染模式  

### 描述问题  
字儿多了（万字以上）输入时卡顿厉害。不清楚是不是每次更改都要全局重渲染一遍还是咋地。不太懂优化这一块。  
配置：AMD Ryzen R5 2500U 8G DDR4
浏览器：chrome dev
操作系统：Archlinux，各类驱动齐全

### 期待的结果  
当然是不卡啦……不是太懂优化这一块，就不乱说话了。

**Comment by 88250** [comment]
方便的话请给一下 md 原文

**Comment by lixiang810** [comment]
> 方便的话请给一下 md 原文

[就是我那小说](https://hacpai.com/article/1592228237013)。  
经过再次验证，卡顿主要发生于删除字符期间，时长大致为1s

**Comment by 88250** [comment]
经过排查，是因为整篇文章都在 Markdown 的一个段落 `<p>` 里……

Vditor 对局部解析渲染进行过优化，只用“重绘”一定范围内受影响的部分，在没有块级容器节点（列表项、块引用）时，段落节点就是一个范围，如果整篇文章都在一个段落里，相当于该优化就没有起作用了，按照常规 Markdown 排版的话建议用空行分段。

我关闭 issue 了，如果还有相关反馈请继续跟帖，谢谢。
