### ISSUE TITLE
@功能中，如果有同名选项如何知道是哪一个选项被选中了

### ISSUE THREAD

**Issue by svkd9** [Vanessa219/vditor#491]
比如在下拉项中，有两个人都叫 "张三"，姓名相同但userid、头像等不同，此时点击了其中一个，如何知道是哪个"张三"被选中了呢

有没有类似于点击后onSelect的回调方法

**Comment by Vanessa219** [comment]
value 应该不同，选中后会把 value 值填到编辑器中

**Comment by svkd9** [comment]
感谢回复，如果把value填到编辑器里面，可能会有点长，这个地方我再考虑考虑
