### ISSUE TITLE
三种模式支持 list-style 样式

### ISSUE THREAD

**Issue by 88250** [Vanessa219/vditor#494]
之前在 SV 模式做过 https://github.com/Vanessa219/vditor/issues/269 现在需要进行改进，不能使用 `data-mark` 属性，因为 WYSIWYG、IR 模式依赖 `data-marker` 做解析，无法根据开关指定是否渲染，只能固定渲染该属性，这会导致这两个模式固定显示列表样式。

为了改进，我们需要新引入属性 `data-style`，三种模式统一基于该属性做列表项样式控制，开关名称由 `RenderListMarker` 变更为 `RenderListStyle`。

**Comment by Vanessa219** [comment]
wysiwyg & ir mode 和 sv mode 添加的 data-style 位置不一致，应统一为 sv mode

@88250
