### ISSUE TITLE
Vditor的扩展render机制

### ISSUE THREAD

**Issue by amoydavid** [Vanessa219/vditor#502]
### 你在什么场景下需要该功能？

我希望由 Lute 渲染出来的 a 标签，在特定url和特定title的情况下，渲染成 iframe

### 描述可能的解决方案

目前我只能在 mediaRender 基础上改，或是添加一个自己的 render ，然后编译成自己的版本。

### 描述你认为的候选方案

如果有一个 Vditor.addRender(xxx) 方法，是不是能把耦合度降下来。大家也可以根据自己的业务需要去写自己的渲染方法。

### 其他信息

Vditor is cool.

**Comment by Vanessa219** [comment]
可以查看 http://vditor.b3log.org/demo/preview-config.html 中的自定义渲染

**Comment by Vanessa219** [comment]
有问题再 reopen，我先 close 了。
