### ISSUE TITLE
可以提供一个目录渲染功能吗？向后端请求数据会返回内容及目录

### ISSUE THREAD

**Issue by hectorwill** [Vanessa219/vditor#503]
![image](https://user-images.githubusercontent.com/35887903/85101689-8ace2d00-b235-11ea-8478-51017367b9c5.png)

**Comment by 88250** [comment]
你是在前端渲染 Markdown 还是后端渲染的？

**Comment by hectorwill** [comment]
> 你是在前端渲染 Markdown 还是后端渲染的？

前端渲染的

**Comment by hectorwill** [comment]
> 你是在前端渲染 Markdown 还是后端渲染的？

目前的解决方案是在前端渲染的时候使用js，遍历一遍htm内容的标签，如h1,h2，以及对应的锚点内容，然后在侧边生成目录。

**Comment by Vanessa219** [comment]
可参考 http://vditor.b3log.org/demo/preview.html
