### ISSUE TITLE
照片方向问题

### ISSUE THREAD

**Issue by HaujetZhao** [Vanessa219/vditor#505]
Typora 中实时预览也有这个问题，不过Typora 导出的 html 中，不会有这个问题。

手机相机拍的竖屏照片，本质上是横屏照片， exif 信息里加上了 orient 90度 的信息。

竖屏拍出的照片，在图库、图片编辑软件里显示正常，但是放到 Vditor 里，会忽略 exif 里的方向信息，横屏显示图片。

例如下图，下载下来用看图软件查看其实是竖屏照片：

![IMG20200620154211.jpg](https://b3logfile.com/file/2020/06/IMG20200620154211-00e3c471.jpg)

**Comment by 88250** [comment]
不好意思，这个问题是黑客派[自动去除上传照片的 Exif](https://hacpai.com/article/1548290712008)导致，稍后会进行修复，和 Vditor 没有关联，感谢帮忙反馈！
