### ISSUE TITLE
上传文件时无法输入改进

### ISSUE THREAD

**Issue by HaujetZhao** [Vanessa219/vditor#506]
描述见视频：

[e.mp4](https://b3logfile.com/file/2020/06/e-6b75967f.mp4)

建议是像 GitHub 那样，上传时候，用一个 `[uploading 1592538863176.mp4..]()` 占位，上传时候不影响后续输入。

**Comment by Vanessa219** [comment]
应该是可以的，但是怕用户修改了`[uploading 1592538863176.mp4..]()` 这个，后面就无法替换为上传好的链接了

**Comment by TobiasTao** [comment]
我觉得在文件上传过程中将 `[uploading 1592538863176.mp4..]()`设置为 `contenteditable="false"` 就可以了
![image](https://user-images.githubusercontent.com/37654563/86233408-f1553280-bbc7-11ea-84c0-dc4fef01cbea.png)

 或者在上传完成前将这一块先用loading图标覆盖：
![image](https://user-images.githubusercontent.com/37654563/86234350-5b220c00-bbc9-11ea-9245-82cb313579df.png)

**Comment by Vanessa219** [comment]
字符设置为 contenteditable="false" 也可以被整块删掉的，覆盖住也是可以被删掉的

**Comment by 88250** [comment]
暂时不考虑了，以后如果需要再看，感谢反馈。
