### ISSUE TITLE
Gboard & Swiftkey backspace issue

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#507]
Previous Issue https://github.com/Vanessa219/vditor/issues/434#issuecomment-633264060

I think two keyboards are most popular in America(Android): [Goolge Gboard](https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin&hl=en_US), [Microsoft Swiftkey](https://www.microsoft.com/en-us/swiftkey?activetab=pivot_1%3aprimaryr2)

The backspace comes out only first of input. (they are using the composition event in the middle of English input mode.  Other soft keyboard is not using composition event.)

![Screenshot_20200620-134040](https://user-images.githubusercontent.com/15811943/85209320-8e78b700-b2fc-11ea-9d51-f5a7c043c1ee.png)

I tested other popular editor. (for example, Froala)
I think the froala is ok because  every line is input mode.
![froala](https://user-images.githubusercontent.com/15811943/85209350-c849bd80-b2fc-11ea-8b26-ca64f4c99965.PNG)

But Vditor is whole area is input mode.
![vditor](https://user-images.githubusercontent.com/15811943/85209374-f9c28900-b2fc-11ea-8e18-069e5b55249b.PNG)

Could you check this issue one more time.
Thanks

**Comment by Vanessa219** [comment]
Changing one input to multiple inputs is a huge project. 
But now, I can not delete empty and I can not reproduce [the fourth image](https://github.com/Vanessa219/vditor/issues/434#issuecomment-633264060). 

[QQ20200621-112006.gif.zip](https://github.com/Vanessa219/vditor/files/4808867/QQ20200621-112006.gif.zip)

**Comment by jakekwak** [comment]
@Vanessa219 not wysiwyg mode, try to IR mode.
Thanks.   I will try to contact Google to update Gboard.

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/508
