### ISSUE TITLE
软键盘 bug

### ISSUE THREAD

**Issue by Vanessa219** [Vanessa219/vditor#508]
- [x] 空段落不能删除
- [x] IR 模式下删除： [the fourth image](https://github.com/Vanessa219/vditor/issues/434#issuecomment-633264060).

**Comment by jakekwak** [comment]
Please check the `deleteContentBackward` inputType for fixing this problem. 
![800588803_1592625329 9635](https://user-images.githubusercontent.com/15811943/85230616-fa1f5a80-b3b6-11ea-9d2d-e6a590101c99.gif)

**Comment by Vanessa219** [comment]
I fixed this issue in the dev branch, but I only have one simulator, can you help me test it, thx!

**Comment by jakekwak** [comment]
It is working good both Gboard, Swiftkey.  and I think also fixed this issue https://github.com/Vanessa219/vditor/issues/511
Thanks.
