### ISSUE TITLE
upload选项是否可以增加上传单张图片的配置

### ISSUE THREAD

**Issue by ihewro** [Vanessa219/vditor#509]
### 你在什么场景下需要该功能？

```js
        formData.append("file[]", validateResult[i]);
```

我看源码里面的formdata是上面这样的。**现在我的后端接口是固定的，只能处理单张图片的上传情况**

请问upload能增加一个选项是单张上传还是多张上传吗?

**Comment by ihewro** [comment]
已经通过修改后端接口解决了

**Comment by Vanessa219** [comment]
嗯嗯。一般批量接口都兼容单个的，但是单个的确无法兼容批量的，所以我们最终只支持了批量接口。
