### ISSUE TITLE
引用多层嵌套无法一次性回到最外层

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#51]
![blockquote](https://user-images.githubusercontent.com/15811943/71950996-2ee38080-318e-11ea-94e1-16d9002a5817.gif)

**Comment by 88250** [comment]
We can use `\` to escape blockquote marker `>`:

````markdown
```
> foo
> \>bar
```
````

It will render:

> foo
> \> bar

**Comment by jakekwak** [comment]
when press ctrl+shift+e
![23](https://user-images.githubusercontent.com/15811943/71978931-57d93500-31d1-11ea-95ee-8cf4ffe8cfbc.PNG)

**Comment by Vanessa219** [comment]
`alt + enter`

**Comment by jakekwak** [comment]
alt+enter is not working. please double check
