### ISSUE TITLE
Korean input problem at second line

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#511]
`Android`/`Chrome`/`Gboard` Korean Keyboard

When I type the first consonant(ㅎ) in the second line, the compositionend event will comes out.

I made some tesing site http://74.208.27.41/keyevent.html 

no compositionend event at testing site.

![vditor2](https://user-images.githubusercontent.com/15811943/85248673-2d91d180-b417-11ea-97de-9a88e93f9156.gif)

**Comment by Vanessa219** [comment]
Sorry i don't understand what is the problem

**Comment by jakekwak** [comment]
after https://github.com/Vanessa219/vditor/commit/3e636f139ce5e09a0a5848ccbe9fb91dd699c904, it is working good.
Thanks.
