### ISSUE TITLE
插入最新上传的文件

### ISSUE THREAD

**Issue by HaujetZhao** [Vanessa219/vditor#512]
领导的话让我有了一个新的需求：

* 在vditor“更多”选项里，添加一个按钮，功能是“插入最新上传的文件”。

有两个用途：

* 上传文件过程中如果因用户修改了 [xxx]\(uploading...) 这样的句子，导致没能自动替换，用户可以手动把上传的文件链接插入
* 有时候，电脑发帖子，需要插入手机上的图片，就需要先用通讯工具传到电脑，再从电脑粘贴图片，步骤繁琐。用这个功能就可以，在手机上 vditor 上传一张图片，电脑上 vditor 中的文章一键插入刚刚上传的图片、文件。

![Screenshot20200623135908069com.android.chrome.jpg](https://b3logfile.com/file/2020/06/Screenshot20200623135908069com.android.chrome-69b271e1.jpg)

**Comment by Vanessa219** [comment]
这个要后台支持吧，vditor 是纯前端的

**Comment by HaujetZhao** [comment]
> 这个要后台支持吧，vditor 是纯前端的

那是不是提错地方了，应该提到 sym?

**Comment by Vanessa219** [comment]
我来 Transfer 吧。

**Comment by 88250** [comment]
对了，黑客派可以浏览自己上传过的文件 https://hacpai.com/settings/file 从这里可以找到图片 URL 然后手动插入，暂时先这样凑合用，后续可能会在 Vditor 中加入一个获取已上传文件的接口，从后端拉取最新上传过的一些图片，以支持快捷插入操作。
