### ISSUE TITLE
[Question] Duplicate CSS(render.html)

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#517]
Is there any option not to include CSS?  (below <style>.... </style>)

<img width="872" alt="Screen Shot 2020-06-29 at 8 58 47 AM" src="https://user-images.githubusercontent.com/15811943/86015644-72090880-b9e7-11ea-80ec-2b75a5fa4ad5.png">

**Comment by Vanessa219** [comment]
render.html has not this css

**Comment by jakekwak** [comment]
@Vanessa219  it is automatically added when I checked the chrome developer.

**Comment by Vanessa219** [comment]
this is added by webpack, you just import xxx.css is OK.

**Comment by jakekwak** [comment]
When adding the custom css(xxx.css), this will be inserted at the below, it causing a crash.

**Comment by Vanessa219** [comment]
This is a development method, we can change the `setTheme` API and extend `markdown.theme`.

**Comment by jakekwak** [comment]
Ok, thanks

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/519

**Comment by jakekwak** [comment]
no duplicate  at demo/render.js
```
// import '../src/assets/scss/index.scss'
```

**Comment by Vanessa219** [comment]
Sorry, what do you mean?

**Comment by jakekwak** [comment]
I found the reason of `duplicate css`

**Comment by Vanessa219** [comment]
which css is  duplicate?

**Comment by jakekwak** [comment]
render.html index.css and <style> </style>
so I can test my own theme.

**Comment by Vanessa219** [comment]
pls update this code 
9f63cf5
