### ISSUE TITLE
设置 「编辑器初始化值」不生效，「全屏」没有浏览器全屏，好像只是父级元素的宽高

### ISSUE THREAD

**Issue by naiba** [Vanessa219/vditor#523]
嗨，正在把 lute & vditor 集成到 https://github.com/naiba/solitudes 里面，目前已经集成成功，编辑器有些问题，希望得到二位的帮助，祝好。

补充 Vditor 版本：

```
<!-- Begin Vditor -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vditor@3.3.3/dist/index.css"
    integrity="sha256-XDt1XMo1cdszL2MTR+210fRPDo4JSuA3DGnk5wF0Szs=" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/vditor@3.3.3/dist/index.min.js"
    integrity="sha256-RsQBHGzBu0yVnC8baqkYjMMwOcWHHK8XC0nLGW/FvFk=" crossorigin="anonymous"></script>
<!-- End Vditor -->
```

1. 编辑器初始化时设置了 `value` 但是没生效，控制台正常

```
const vditor = new Vditor('editSection', {
        value: '{{.Data.article.Content}}',
        outline: true,
        minHeight: '500px',
        upload: {
            handler: uploadImage,
        },
    })
```

2. 在初始化后主动设置 `value` 控制台有错误

```
const vditor = new Vditor('editSection', {
        outline: true,
        minHeight: '500px',
        upload: {
            handler: uploadImage,
        },
    })
    vditor.setValue('{{.Data.article.Content}}', true);
错误：
index.min.js:27 Uncaught TypeError: Cannot read property 'Md2VditorDOM' of undefined
    at we (index.min.js:27)
    at t.setValue (index.min.js:27)
    at publish?id=f1071baf-e4e1-4e54-89a1-a57c5ea3939e:197
```

3. 点击全屏之后没有在整个窗口全屏

<img width="1280" alt="Xnip2020-06-30_22-28-25" src="https://user-images.githubusercontent.com/29243953/86138427-0a56d880-bb21-11ea-810a-bc4c98449c93.png">

4. 可以补充一下 upload 自定义 handler 部分的说明吗，上传成功后 handler return null，怎么让图片插入到编辑器中？

**Comment by Vanessa219** [comment]
谢谢补充，版本修改的话，integrity 会变化吧？

1. 请核对 http://vditor.b3log.org/demo/advanced-cache.html 中的注意事项
2. setValue 需在 after 中使用，可参见 https://vditor.b3log.org/demo/option-callback.html
3. 目前只能重置 `.vditor--fullscreen {z-index}` 
4. 不太建议使用 `handler`，如果数据结构不符合的话可以使用 `format`。如果一定要使用只能参考 https://github.com/Vanessa219/vditor/blob/master/src/ts/upload/index.ts#L76。

**Comment by naiba** [comment]
> 谢谢补充，版本修改的话，integrity 会变化吧？
> 
> 1. 请核对 http://vditor.b3log.org/demo/advanced-cache.html 中的注意事项
> 2. setValue 需在 after 中使用，可参见 https://vditor.b3log.org/demo/option-callback.html
> 3. 目前只能重置 `.vditor--fullscreen {z-index}`
> 4. 不太建议使用 `handler`，如果数据结构不符合的话可以使用 `format`。如果一定要使用只能参考 [https://github.com/Vanessa219/vditor/blob/master/src/ts/upload/index.ts#L76。](https://github.com/Vanessa219/vditor/blob/master/src/ts/upload/index.ts#L76%E3%80%82)

是的，integrity 会变化。
Wow，太棒了，上传文件这里我改一下后端让他成为编辑器需要的请求和返回格式，下一步自用小博客可以说会非常好用了，感谢。

**Comment by Vanessa219** [comment]
客气了
