### ISSUE TITLE
Copy & paste excel data.

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#525]
@88250 When copy & paste microsoft word's data,  it is OK,
I want to test the excel data

![13](https://user-images.githubusercontent.com/15811943/86202774-d7184780-bb28-11ea-8415-6e2d9c839365.PNG)

I got the error message.
![12](https://user-images.githubusercontent.com/15811943/86202808-ebf4db00-bb28-11ea-8cf8-a9820eca40e4.PNG)

**Comment by 88250** [comment]
Thank you report it, but I can not reproduce it.

![GIF 2020-7-1 23-04-04](https://user-images.githubusercontent.com/873584/86260046-5b350280-bbef-11ea-8af1-fc4503812779.gif)

**Comment by jakekwak** [comment]
@88250 Ok, I will test it again after updating.
