### ISSUE TITLE
移除格式化按钮

### ISSUE THREAD

**Issue by Vanessa219** [Vanessa219/vditor#529]
sv 模式已经修改为变输入边格式化了，因此不再需要工具栏上的格式化按钮

**Comment by DevSum** [comment]
请问如何关掉格式化功能呢？有配置项可以控制吗

**Comment by 88250** [comment]
@DevSum 关闭不了，输入的时候需要做解析，解析过程进行了格式化。

**Comment by DevSum** [comment]
也就是说，例如：
![image](https://user-images.githubusercontent.com/32128614/146118312-6c92aa24-6238-478e-b457-6ebf8d2c95ca.png)
被自动格式化为
![image](https://user-images.githubusercontent.com/32128614/146118339-86a52a96-3748-4dbd-a8f3-ab96f0cf5691.png)
(去掉了\`yarn`前面的空格）这样是无法避免的吗

**Comment by 88250** [comment]
@DevSum 目前来说是的，如果需要改变的话得改一下 Lute 的代码：https://github.com/88250/lute/blob/6015e5d898c2358ec00f13b74f51200ace027584/render/vditor_sv_renderer.go#L913

**Comment by shuzijun** [comment]
> @DevSum 关闭不了，输入的时候需要做解析，解析过程进行了格式化。

@88250  有方案可以只格式化编辑的区域么，而不是对整个内容格式化，相关issues: https://github.com/shuzijun/markdown-editor/issues/69

**Comment by 88250** [comment]
@shuzijun 这个比较复杂，需要改为分块解析。我们目前没有时间进行调整，见谅。
