### ISSUE TITLE
图片 title 丢失问题

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#53]
Inline-style: 
![alt text](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 1")

Reference-style: 
![alt text][logo]

[logo]: https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 2"

![logo text](https://user-images.githubusercontent.com/15811943/71952910-525df980-3195-11ea-80b2-4d36fcf0c063.gif)

* when typing [logo]: it does not take the remain text.

**Comment by 88250** [comment]
The link reference converts to inline link will be fixed in https://github.com/Vanessa219/vditor/issues/55
