### ISSUE TITLE
中文输入过程中不应记录 UndoStack

### ISSUE THREAD

**Issue by zTree** [Vanessa219/vditor#532]
### 你在什么场景下需要该功能？

提个建议，你重构 Undo 部分的代码时，是否可以考虑一下 中文输入过程中不应记录 UndoStack ，否则在 undo 的时候，会看到正在输入的中文拼音；我刚提交了一个 pull request，测试感觉还有点儿问题，就取消了。

### 描述可能的解决方案

检测到正在输入中文时，不执行 addToUndoStack，只有最后中文输入结束时，才去执行。

![Vditor 示例 - 黑客派](https://user-images.githubusercontent.com/682855/86351353-ba9a1d80-bc96-11ea-8047-f285b893c1a9.gif)

**Comment by Vanessa219** [comment]
收到，多谢

**Comment by Vanessa219** [comment]
这个 bug 是不是不太好重现呀？

**Comment by Vanessa219** [comment]
我也不知道修好没，因为我只重现了一次，凭感觉改了改。有空麻烦到分支上试试。

**Comment by zTree** [comment]
> 我也不知道修好没，因为我只重现了一次，凭感觉改了改。有空麻烦到分支上试试。

抱歉，这么久才看到，我大概测试了一下，用的是你最新的 master 上的代码，应该是没问题啦！辛苦辛苦
