### ISSUE TITLE
中文字符串中间插入 \ 字符导致乱码

### ISSUE THREAD

**Issue by zTree** [Vanessa219/vditor#533]
### 编辑模式

所见即所得模式
即时渲染模式

### 描述问题

中文字符串中间插入 \ 字符会导致乱码
原文：
![image](https://user-images.githubusercontent.com/682855/86356348-ace89600-bc9e-11ea-96a4-e32546a79dad.png)
所见即所得模式 插入 \ 后：
![image](https://user-images.githubusercontent.com/682855/86356410-cbe72800-bc9e-11ea-92b7-5f8d59ca3f42.png)
即时渲染模式 插入 \ 后：
![image](https://user-images.githubusercontent.com/682855/86356492-e91bf680-bc9e-11ea-8624-e12210d4919b.png)

**Comment by 88250** [comment]
dev 分支上已经做了修复，如果方便的话请帮忙验证，谢谢。

**Comment by Vanessa219** [comment]
pls update
