### ISSUE TITLE
请问可以支持自定义语法渲染吗

### ISSUE THREAD

**Issue by HerbertHe** [Vanessa219/vditor#535]
### 你在什么场景下需要该功能？

文档内插入自定义视频播放器及相类似的自定义渲染语法

### 描述可能的解决方案

通过传递正则表达式进行对于自定义结构进行文本内容获取返回，然后自定义DOM渲染函数

### 描述你认为的候选方案

- 通过传递正则表达式给解析文本结构的引擎
- 传递自定义class控制自定义DOM的样式
- 传递自定义渲染函数进行DOM的插入

### 其他信息

无

**Comment by Vanessa219** [comment]
你参考一下 http://vditor.b3log.org/demo/preview-custom.html 和 https://hacpai.com/article/1588412297062

**Comment by HerbertHe** [comment]
没太理解自带渲染函数的整个文档、段落和文本的区别，但是觉得这部分可以作为额外的语法扩展。

**Comment by 88250** [comment]
@HerbertHe 你好，Vditor 的 Markdown 引擎（Lute）目前不支持自定义解析器（Parser），但是支持自定义渲染器（Renderer），在 Vditor 上层也提供了通过 JS 自定义渲染器的支持。

技术方面的细节请参考文档 [Markdown 解析原理详解和 Markdown AST 描述](https://hacpai.com/article/1587637426085)，渲染器的工作原理是遍历整个语法树，然后根据不同的语法节点元素进行不同的渲染处理。你可以试着根据 Vditor 的自定义渲染器文档来简单做个实验，修改一下 renderDocument 的实现，看下输出结果。

**Comment by HerbertHe** [comment]
@88250 好，我大致了解了解析器的工作原理。语法拓展的话，通过自定义渲染函数也可以实现，我尝试实现一下。对应结构返回的内容，通过修改渲染器的方式来二次渲染内容。

**Comment by Vanessa219** [comment]
我先关闭了，有问题可以 reopen 或 new issue

**Comment by mouse0w0** [comment]
> 你参考一下 http://vditor.b3log.org/demo/preview-custom.html 和 https://hacpai.com/article/1588412297062

您好，第一篇的链接和第二篇的Demo链接均已失效，方便补一下吗？
