### ISSUE TITLE
麻烦向 cdnjs 提交，让我们享受国内免费 cdn 服务

### ISSUE THREAD

**Issue by cipchk** [Vanessa219/vditor#538]
### 你在什么场景下需要该功能？

国内免费 cdn 主要是 [bootcdn](https://www.bootcdn.cn/)，而它又是基于 [cdnjs](https://github.com/cdnjs/cdnjs) 自动同步的，所以希望能向 cdnjs 提交一个描述，以更好的在国内使用免费 cdn。

- https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md

感谢提供这么好的组件。

**Comment by Vanessa219** [comment]
现在用的 jsdelivr 感觉还可以。不太清楚要怎么弄，如果你熟悉的话可以直接 PR 到 master 上。多谢。
