### ISSUE TITLE
请问 编辑器为什么要使用pre+contenteditable而不是div+contenteditable

### ISSUE THREAD

**Issue by fubd** [Vanessa219/vditor#540]
pre比div有什么优势吗，div加了`white-space: pre-wrap;`换行和空格也能解析，有些好奇，希望大佬赐教。
@Vanessa219

**Comment by Vanessa219** [comment]
主要是参考了一些其他的编辑器。

div 和 pre 之间即使加了 CSS，他们底层也会有许多的不同，至于其细微的差别可能要在非常特殊的场景下才能察觉（目前没有用 div，所以不太好察觉两者的区别）。但这就好比 div 和 button 可以通过 CSS 来使他们展现一致，但是他们在点击事件上对 Range 的处理是有细微的差别一样。
