### ISSUE TITLE
SV 模式工具栏状态切换问题

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#542]
![vditor4](https://user-images.githubusercontent.com/15811943/86944724-bf832500-c10d-11ea-9a0f-2f5e0a02985c.gif)

code block

![vditor5](https://user-images.githubusercontent.com/15811943/86945880-3371fd00-c10f-11ea-8409-2a6cfb5a6bf5.gif)

**Comment by Vanessa219** [comment]
In the code and table, you can not enter other marker, which is the same as ir mode.

**Comment by jakekwak** [comment]
Sorry,  please check the `end of each block`
![vditor12](https://user-images.githubusercontent.com/15811943/86990894-50d0b680-c163-11ea-81d5-0c859ed86f31.gif)

**Comment by Vanessa219** [comment]
this is also the same as ir mode and Word
![image](https://user-images.githubusercontent.com/970828/86991958-f2dbb780-c1d2-11ea-8962-2f21ba75554a.png)

**Comment by jakekwak** [comment]
How about the code block?  When I input the `enter` several times, I can not input the shortcut key.

**Comment by Vanessa219** [comment]
this bug fixed by #543

**Comment by jakekwak** [comment]
Thanks
