### ISSUE TITLE
SV 模式丢失 headingID

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#546]
![vditor11](https://user-images.githubusercontent.com/15811943/86970702-6fb85400-c135-11ea-9ce4-738611d71d8f.gif)

**Comment by jakekwak** [comment]
@88250 
![vditor3](https://user-images.githubusercontent.com/15811943/87069311-9c737680-c1dc-11ea-876b-f4ed16b75a8f.gif)

**Comment by 88250** [comment]
Oh, it's a feature 😋

**Comment by Vanessa219** [comment]
It's a bad feature 😒

**Comment by Vanessa219** [comment]
I think we should be improve it.

**Comment by 88250** [comment]
Improved, check it please after release new version, thank you.
