### ISSUE TITLE
[Mermaid] State diagram rendering of multiple same node loops

### ISSUE THREAD

**Issue by tsagkase** [Vanessa219/vditor#550]
The following should render two loops:

    ```mermaid
    stateDiagram
      I: Vditor
      [*] --> I
      I --> I: love
      I --> I: hate
    ```
Instead, the rendered result is 
![2020-07-09-115919_281x204_scrot](https://user-images.githubusercontent.com/1290451/87020084-10614f00-c1dc-11ea-9a13-1b8bef0055cf.png)

**Comment by Vanessa219** [comment]
It is OK in my demo. Can you show more details?

![image](https://user-images.githubusercontent.com/970828/87021817-3bfa2e80-c208-11ea-8f92-8013827331ca.png)

**Comment by jakekwak** [comment]
https://mermaid-js.github.io/mermaid-live-editor/

![Screen Shot 2020-07-09 at 5 09 16 AM](https://user-images.githubusercontent.com/15811943/87027166-62857e80-c1a2-11ea-99df-0108d7ead8a3.png)

**Comment by Vanessa219** [comment]
443afd16a0943e3307d59306ddd7c9530d3eba78
