### ISSUE TITLE
blockquote 换行需逐层跳出 

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#552]
![vditor1](https://user-images.githubusercontent.com/15811943/87033481-ebed7e80-c1ab-11ea-8fc7-2cfda3686e84.gif)

**Comment by 88250** [comment]
Sorry, I can not get you 😕

**Comment by jakekwak** [comment]
@88250 I think the `>` is removed one by one when key in the 'enter'.

**Comment by 88250** [comment]
Enter used to continue the blockquote at the same level, so if we reduce the level it will let users press `>` after entering the newline, and a blockquote usually contains more then one line, it will cause users press `>` at every line start.

**Comment by jakekwak** [comment]
@88250 Ok,  I checked same behavior every mode(wysiwyg, sv, IR).
