### ISSUE TITLE
SV 模式段落块拆分问题

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#555]
![vditor6](https://user-images.githubusercontent.com/15811943/87072135-ee1e0000-c1e0-11ea-8815-fdf0f19dce29.gif)

**Comment by Vanessa219** [comment]
Sorry, I don’t know where to add the line? Please mark it.

**Comment by jakekwak** [comment]
@Vanessa219 When entered the end of paragraph,  the below paragraph  is merged automatically.
