### ISSUE TITLE
[suggestion] shift+enter and end the lists.

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#558]
shift+enter
```
1. test
2. test
   |  <= cursor
```

the end 

```
3. test
4. test
5. | <= enter and next paragraph input mode
```

![vditor4](https://user-images.githubusercontent.com/15811943/87098858-e88adf00-c20d-11ea-9310-202dc6194362.gif)

**Comment by jakekwak** [comment]
the end of list....
When I finish the list, I hope to enter the next sentence input mode.(not same as shift+enter)

**Comment by Vanessa219** [comment]
Markdown requires two `\n`, so you can press Enter again. https://stackedit.io/app# is also like this.
