### ISSUE TITLE
代码块结束 ``` 优化

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#559]
less cursor key like `VI` editor.

or any good idea?

![vditor1](https://user-images.githubusercontent.com/15811943/87098922-0d7f5200-c20e-11ea-8e90-eb5123d165b8.gif)

**Comment by 88250** [comment]
Press ` ``` ` to end code block is better, we will improve it as your suggestion.

**Comment by Vanessa219** [comment]
I think you can press arrowdown like IR mode

**Comment by jakekwak** [comment]
@Vanessa219 I think the `press arrowdown` is not bad. 
but `less use arrow key` is better at markdown mode.

**Comment by Vanessa219** [comment]
` ``` ` already exists at the end of the code block, in order to jump out of the code block and press ` ``` ` Is it a bit strange

**Comment by jakekwak** [comment]
I think `ctrl+enter` is best. but this key is using the others.
How about `ctrl+shift+enter` key
```
test
test| <= 1. ctrl+shift+enter 
```

| <= 2. go here

**Comment by 88250** [comment]
But use combination keys need more key to press, it not better than one arrow key.

**Comment by jakekwak** [comment]
@88250 Ok
