### ISSUE TITLE
希望数学公式单独变成一个工具，且能够变成更加可视化编辑

### ISSUE THREAD

**Issue by herbert888** [Vanessa219/vditor#560]
### 你在什么场景下需要该功能？

目前AI是未来，但是AI运用到了很多的数据知识和公式，我们在做AI教育传播的时候，希望有简单的输入公式的方式。

### 描述可能的解决方案

希望数学公式单独变成一个工具，且能够变成更加可视化编辑

### 描述你认为的候选方案

类似百度的 kityformula 和 https://math.edrawsoft.cn/

**Comment by Vanessa219** [comment]
kityformula 这个的 demo 好像用不了，我看了下知乎编辑器中的数学公式，你是想要哪样的么？

**Comment by herbert888** [comment]
嗯嗯，感谢回复。

如果能有知乎这个，也挺好的。目前有2种方式：
1、知乎这种公式方式，然后旁边在增加一个常用格式的下拉（二级下拉）

- 小学
 -算术定律
- 初中
- 高中
 -导数
 -不等式
 -方程
- 大学
 -微积分

**下拉菜单自定义**
2、还有一种是像 https://math.edrawsoft.cn/ 这网站一张，可以都不用了解Tex规则（语法）都能画出公式。

-----------------------
第一种能实现，已经很不错了

**Comment by Vanessa219** [comment]
需要变成一个单独的工具，可能要以插件的方式新开一个项目了。

我们现在的侧重点是改善编辑体验，这个特性可能要等下个月了。

**Comment by herbert888** [comment]
OK，期待，多谢

**Comment by yuanxiongwei** [comment]
期待

**Comment by 88250** [comment]
> 需要变成一个单独的工具，可能要以插件的方式新开一个项目了。
> 
> 我们现在的侧重点是改善编辑体验，这个特性可能要等下个月了。

更正一下，下个月不一定能做 😂 目前暂时没有额外精力开新坑，先把 Vditor 做好吧，感谢大家的关注！

**Comment by wizweishijun** [comment]
好像有工具可以将手绘的公式自动转换为latex语法。没必要自己做一个可视化的编辑器

**Comment by Dup4** [comment]
> 好像有工具可以将手绘的公式自动转换为latex语法。没必要自己做一个可视化的编辑器

https://webdemo.myscript.com/

**Comment by 88250** [comment]
有点偏离 Vditor 的主要路线，先关闭了，感谢讨论。
