### ISSUE TITLE
Multiple text editors with one common toolbar; separated toolbar

### ISSUE THREAD

**Issue by NikolayMakhonin** [Vanessa219/vditor#561]
I am developing a mobile application (notepad) with a vertical list of entries that can be edited without closing the keyboard for switch between them, in order to save user time.
This will be a list of ~20 instances of text editors.
And I would like to remove the toolbar from all text editors, and make one common toolbar.
Like for example I did this on [this site](http://mitani-kun.wiki/_th/lib/upload/#%D0%93%D1%80%D1%83%D0%BF%D0%BF%D0%B0%20(%D0%BC%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D1%82%D0%B8%D0%BA%D0%B0)) (click edit button to see this).
You can see that there are several text editors, but the toolbar is one. (there is also used a CodeMirrror engine)

I achieved this by adding the following code [here](http://mitani-kun.wiki/_th/lib/upload/#%24%3A%2Fplugins%2Ftiddlywiki%2Fcodemirror%2Fengine.js):

```
if (!lastFocusedInstance) {
	lastFocusedInstance = self;
}
this.cm.on('focus', function() {
	lastFocusedInstance = self;
});

this.base_handleEditTextOperationMessage = this.widget.handleEditTextOperationMessage;
this.widget.handleEditTextOperationMessage = function(event) {
	var instance = (lastFocusedInstance || self);
	return instance.base_handleEditTextOperationMessage.call(instance.widget, event);
};
```

But I do not know how to do something similar in your editor.

**Comment by Vanessa219** [comment]
I am in China and I cannot open your website. I don't know why you should delete the toolbar and use the toolbar for the 20 instances of editors. Maybe there is a better way.

Vditor can not implement your feature, you need to write your own code.

1. Hidden toolbar
2. Use Range object to check the current vditor instance
3. Trigger click event of toolbar icon

**Comment by Vanessa219** [comment]
If you have no problems, I will close it first.
