### ISSUE TITLE
SV 模式列表分段问题

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#564]
automatically added line between the lists.

![vditor3](https://user-images.githubusercontent.com/15811943/87184230-3e629400-c2ad-11ea-81c0-bd457020c6eb.gif)

**Comment by 88250** [comment]
Hi, the editing flow will generate a loose list, like this:

```markdown
* foo

* bar
```

We rendering it as a loose list, so inserting a blank line between each list item.
