### ISSUE TITLE
SV 模式块引用嵌套列表、代码块问题

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#567]
list inside blockquote (*sv*, *ir*,  wysiwyg ok)
![vditor6](https://user-images.githubusercontent.com/15811943/87206649-d83b3880-c2cf-11ea-927e-049d9d413ef0.gif)

code block inside blockquote
![vditor7](https://user-images.githubusercontent.com/15811943/87206651-d96c6580-c2cf-11ea-9159-aa829c2f6c2e.gif)
![vditor7-1](https://user-images.githubusercontent.com/15811943/87206656-db362900-c2cf-11ea-9511-80b951494932.gif)

**Comment by Vanessa219** [comment]
The first picture, in ir mode, you forgot to press the space after the point

**Comment by jakekwak** [comment]
Yes, you're right.

**Comment by Vanessa219** [comment]
Now, we change the SV mode structure, so, at the first point, @88250 thinks the user can accept.
![QQ20200716-164434](https://user-images.githubusercontent.com/970828/87650060-af112100-c783-11ea-84e2-402693f8b335.gif)

**Comment by jakekwak** [comment]
please check this markdown
```
> 1. test
> 2. ```bash
>    test
>    ```
> 3. test
```

```
> test
> 
> ```bash
> test
> test
> ```| <= enter here
```

**Comment by Vanessa219** [comment]
Is this correct？
![QQ20200716-233440](https://user-images.githubusercontent.com/970828/87691238-f49e1000-c7bc-11ea-96fa-886a441d18be.gif)

**Comment by jakekwak** [comment]
![vditor11](https://user-images.githubusercontent.com/15811943/87695581-4612b480-c755-11ea-9f1d-4d4f94a4fce2.gif)
![vditor12](https://user-images.githubusercontent.com/15811943/87695592-47dc7800-c755-11ea-8fa3-29b5137d72cc.gif)

**Comment by Vanessa219** [comment]
Please update the dev code and Lute code, we have not merged.

**Comment by jakekwak** [comment]
I used updated dev code and latest lute.

**Comment by 88250** [comment]
Sorry for that, we are releasing a new version, please help us test Vditor after the new version released.

**Comment by jakekwak** [comment]
@88250 no problem
