### ISSUE TITLE
预览区域工具栏配置

### ISSUE THREAD

**Issue by cipchk** [Vanessa219/vditor#569]
### 你在什么场景下需要该功能？

我们是内部项目，这个功能并不是我们必须的，但是无法找到可以移除的选项。

png:

![image](https://user-images.githubusercontent.com/2987467/87222537-caa4b200-c3a6-11ea-8840-b173b7f3fe05.png)

**Comment by Vanessa219** [comment]
目前没有方法，你可以重置 `.vditor-preview__action` 样式试一试

**Comment by cipchk** [comment]
@Vanessa219 不考虑在 `preview` 设置一个选项吗？我觉得这并不复杂。

**Comment by Vanessa219** [comment]
我在想是不是要为每一个按钮加个配置？

**Comment by cipchk** [comment]
我建议重新打开这个 Issues 以便更好的跟踪进度。

**Comment by cipchk** [comment]
@Vanessa219 @88250 建议给 github 项目设置合并分支只需要 `Allow squash merging` 模式，减少类似 ` Merge branches 'dev' and 'master' of github.com:Vanessa219/vditor` 这种无意义的合并。

**Comment by Vanessa219** [comment]
谢谢。已取消 Allow merge commits

**Comment by Vanessa219** [comment]
61e57df7da40657f8b619f32aef423f40fce67d0

**Comment by tenglongwentian** [comment]
能改名吗
