### ISSUE TITLE
关于 process 下 `800` 延迟的疑问

### ISSUE THREAD

**Issue by cipchk** [Vanessa219/vditor#574]
在 [process.ts](https://github.com/Vanessa219/vditor/blob/master/src/ts/sv/process.ts#L46) 下会有一个 `800` 的延迟我不知道这是出于什么考虑，而且在配置项中没有可以修改的地方，因为这在分屏下有非常明显的视觉感观，同时他也影响了 `input` 的响应，就我个人页言是一种非常不好的体验。

基于此，我建议 `800` 值由配置项自行配置，如果性能的考虑，那么也可以将这种性能交给使用者。

**Comment by Vanessa219** [comment]
最近在重写 SV 模式，这个点忘记了，preview 本身已经有 options.preview.delay。现已修改。

至于 800 毫秒是文本内容较多时，经过反复测试，为 lute 解析所预留的时间。这个如果交给使用者配置的话，可能会影响解析性能。当然如果需要的话，也是可以做为配置项的，你觉得呢？

**Comment by cipchk** [comment]
@Vanessa219 事实上我不知道你们测试的环境是怎么样，就这个过程我试过 30000 字的 markdown 文档，基本上是最多在 `120ms` 时间，这对于人的视觉感观可以无视的；做为配置项是一种选择，但我建议可以把值调到一个合理的值（例如：`50`），毕竟 markdown 在绝大多数的情况下字数都是在几千之间。同时，可以针对**性能**这一块提供一个调优的描述说明，甚至可以根据**文档大小**自动适当弧度调整。

同时我建议应该**尽可能快**的调用 `vditor.options.input(text);`，不应该等待，因为预览与数据他们是分开的，数据不需要处理，对于接口而言应该尽可能的被调用。

**Comment by Vanessa219** [comment]
IR 模式的 input 可以立即调用，但是 SV 和 WYSIWYG 模式是需要调用 lute 进行计算以获取 markdown 原文。

由于每个模式的 Dom 结构不一样，每种 DOM （如：列表、引用、代码块等）的解析性能也不一样，这样根据文档大小和内容来计算会比较复杂。不如把接口开放出去，由开发人员根据自己的使用场景进行设置如何？

PS：[测试样例](https://img.hacpai.com/file/2019/06/V2Ray%E9%85%8D%E7%BD%AE%E6%8C%87%E5%8D%97-e6455feb.rar)：
```
Characters as Unicode: 102,750
Characters as ANSI: 157,990
Words: 9,433
Lines: 3,930
Size: 154K
```

**Comment by Vanessa219** [comment]
如果需要添加配置项的话，可以新开 issue 说明，这个 issue 我先关闭了。
