### ISSUE TITLE
粘贴 XML 代码问题

### ISSUE THREAD

**Issue by xianjerry** [Vanessa219/vditor#577]
粘贴xml代码到代码块中，没有任何效果，或者内容会缺失

（1）复制如下代码
```
<context-param>
    <!-- 不配置默认为applicationContext.xml -->
    <param-name>contextConfigLocation
    <param-value>/WEB-INF/springConfig.xml
</context-param>
```

（2）在分屏模式下面粘贴到已经有的代码块里面，出现如下效果
![](https://s1.ax1x.com/2020/07/12/U3r79S.jpg)

**Comment by 88250** [comment]
@Vanessa219 似乎和之前的 https://github.com/Vanessa219/vditor/issues/549 比较像。
