### ISSUE TITLE
添加 ant-design 及 Material 风格的图标

### ISSUE THREAD

**Issue by ElderJames** [Vanessa219/vditor#578]
### 你在什么场景下需要该功能？

与ant design的几个框架集成时，让体验一致

### 描述可能的解决方案

用ant-design的样式变量，从按钮、图标、边距等参数做一下调整

**Comment by Vanessa219** [comment]
图标可以统一换成 ant design 的（如果都有的话），至于边距、按钮的细节可能还需要你指导或 PR 一下。

**Comment by ElderJames** [comment]
可以，请问我是可以直接按默认主题再写一个样式？

**Comment by Vanessa219** [comment]
目前有一个classic 和 dark 的样式，你可以再加一个 ant design 的。如果接口或代码无法扩展的话，我会配合即使修改的。

**Comment by ElderJames** [comment]
图标有的，有一套编辑类图标 https://ant.design/components/icon-cn/

**Comment by Vanessa219** [comment]
好的，使用线框风格么？

**Comment by ElderJames** [comment]
对，线框就很不错~

**Comment by Vanessa219** [comment]
以下选中的图标为没有找到 ant-design 相对应的，只能沿用原有的或者找一下相似的。

![image](https://user-images.githubusercontent.com/970828/88359681-23f8e200-cda6-11ea-9c4c-0472c4769a2c.png)

以下为 ant-design 对应的图标

![image](https://user-images.githubusercontent.com/970828/88359694-2eb37700-cda6-11ea-885e-65bbb8c91e9e.png)

**Comment by ElderJames** [comment]
非常棒！
源码的文档有svg
https://gw.alipayobjects.com/zos/rmsportal/wSAkBuJFbdxsosKKpqyq.svg
https://gw.alipayobjects.com/zos/rmsportal/OpROPHYqWmrMDBFMZtKF.svg

**Comment by Vanessa219** [comment]
多谢，为啥我们找到呢？

**Comment by ElderJames** [comment]
在demo的打开源码那个按钮扣下来的

**Comment by Vanessa219** [comment]
牵强的找了几个，不行再换吧。
![image](https://user-images.githubusercontent.com/970828/88368210-2831f900-cdc0-11ea-9938-59e8c851b0ff.png)

**Comment by ElderJames** [comment]
👌谢谢，非常好

**Comment by Vanessa219** [comment]
Material 
![image](https://user-images.githubusercontent.com/970828/88388233-af926300-cde6-11ea-968a-998bf5e143d8.png)

**Comment by Vanessa219** [comment]
@ElderJames 我先关闭了，你样式弄好直接 PR 吧

**Comment by ElderJames** [comment]
样式不太会加😂
我还是在用的时候外部修改吧，大概就是字体和排版

**Comment by Vanessa219** [comment]
不行的话，你发一份给我，然后截个图。我来试试
