### ISSUE TITLE
代码块的最后一行尾部换行没有作用

### ISSUE THREAD

**Issue by hellotomoro** [Vanessa219/vditor#581]
（分屏模式）我在代码块里面手写一段代码，第一行写完后，按回车准备切换下一行继续，然后无论按多少次回车都没有换行。

**Comment by hellotomoro** [comment]
分屏模式的编辑区域能不能设置成单纯的文本输入，这样我就能避免这样的问题了。

**Comment by 88250** [comment]
SV 模式我们刚刚从纯文本方案切换成 DOM 方案……现在的确存在不少问题，正在完善中，感谢关注。

**Comment by Vanessa219** [comment]
我这里是可以换行的
![QQ20200714-192922](https://user-images.githubusercontent.com/970828/87420731-608b4780-c608-11ea-8a91-9ba836c4c4f7.gif)

**Comment by xianjerry** [comment]
我现在没问题了，当时确实换行不了，好像换行之前粘贴过xml，现在我没办法重现。

**Comment by Vanessa219** [comment]
那我现关闭了，如果可以重现的话再新建或打开都可以。
