### ISSUE TITLE
IR & SV 保留 Setext 风格标题

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#587]
https://github.github.com/gfm/#example-52

Is is possible to support?
Test1
Test2
===

![vditor15](https://user-images.githubusercontent.com/15811943/87744697-bd763180-c7b1-11ea-8d78-ef4cb75bc74c.gif)

**Comment by 88250** [comment]
At present, we convert Setext headings to ATX headings forcibly, so multi-lines heading has this issue. Later we will try to remain Setext headings format.

**Comment by jakekwak** [comment]
Ok, when Setext heading available,  I will test again.

**Comment by 88250** [comment]
We will implement it in this issue, I reopen it, thank you.

**Comment by 88250** [comment]
https://github.com/Vanessa219/vditor/issues/626

**Comment by 88250** [comment]
@Vanessa219 待解决 WG 切换 IR/SV 后 `{test}` 丢失。
