### ISSUE TITLE
第五版 SV 模式 bug 记录

### ISSUE THREAD

**Issue by Vanessa219** [Vanessa219/vditor#588]
- [x] 粘贴会换行
- [ ] ~~选择段前文字进行删除，感觉会卡（突然重现不了）~~
- [x] 列表中有 inline code 时换行无 marker 
- [x] 回车没有调用打字机模式

---

* 第一版 textarea
* 第二版 div contenteditable
* 第三版 使用 lute 解析对应的 DOM 转换为结构化的 DOM
* 第四版 使用 lute 直接解析 Markdown 转换为结构化的 DOM
* 第五版 使用 lute 直接解析 Markdown 转换为平铺的 DOM

😭 😭 😭 😭 😭 😭

**Comment by 88250** [comment]
加油！
