### ISSUE TITLE
GFM #19, #40, #57

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#589]
https://github.github.com/gfm/#example-19
Foo
    ***

https://github.github.com/gfm/#example-40
foo
    # bar

https://github.github.com/gfm/#example-57
Foo
    ----

![vditor16](https://user-images.githubusercontent.com/15811943/87745256-07abe280-c7b3-11ea-93c5-cae710e2b4a0.gif)

**Comment by Vanessa219** [comment]
lute can not implement this.

**Comment by 88250** [comment]
Some cases we can not input in Vditor, caused by the writing and rendering is real-time: every typed character will effect the next rendering result. I think most of these cases are meanless in the real world, or we can use another typing sequence to render it for the same result.
