### ISSUE TITLE
blockquote insdie ordered list.

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#596]
need more improvements

![vditor19](https://user-images.githubusercontent.com/15811943/87862864-38f2f280-c91a-11ea-919f-6ce50909485a.gif)

**Comment by Vanessa219** [comment]
I just changed a little. If you have a better UED, please reopen it.

**Comment by jakekwak** [comment]
How about this sequence.

"**1. test**<kbd>enter</kbd> 
"2.  **> test** <kbd>enter</kbd>. <== current <kbd>shift+enter</kbd>
"&nbsp;&nbsp;&nbsp;        > **test**<kbd>enter</kbd>
"&nbsp;&nbsp;&nbsp;        > **test**<kbd>enter</kbd>
"&nbsp;&nbsp;&nbsp;        > <kbd>enter</kbd>. <=== when <kbd>enter</kbd> here,  will be `3. `

**Comment by Vanessa219** [comment]
If "shift+enter" => "enter", this scene cannot be output.
![image](https://user-images.githubusercontent.com/970828/88999296-b1987c80-d326-11ea-9cb2-d5f021f725d9.png)

If "" => "3.", violates the rule that enter will be indented when the content is empty.
