### ISSUE TITLE
one more backspace before delete lists

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#597]
![vditor20](https://user-images.githubusercontent.com/15811943/87862938-1f9e7600-c91b-11ea-8d76-9b01a46ee1e4.gif)

**Comment by jakekwak** [comment]
also at heading

Chrome
![vditor28](https://user-images.githubusercontent.com/15811943/87866618-a5d1b100-c949-11ea-9698-5edd9441964f.gif)

Firefox
![vditor29](https://user-images.githubusercontent.com/15811943/87866621-ac602880-c949-11ea-8cd5-685f6d73eece.gif)

**Comment by Vanessa219** [comment]
a270ce708725e2d0594341da6143633406032a90
