### ISSUE TITLE
handling Mention?

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#598]
![vditor21](https://user-images.githubusercontent.com/15811943/87862986-c97e0280-c91b-11ea-8365-44a684465adf.gif)

**Comment by Vanessa219** [comment]
This is not a bug, because `options.hint.at` is hard code in index.js

```
at: (key) => {
      return [
        {
          value: '@Vanessa',
          html: '<img src="https://avatars0.githubusercontent.com/u/970828?s=60&v=4"/> Vanessa',
        }]
    },
```

**Comment by jakekwak** [comment]
Is it correct that if you type text after entering the mention, the mention continues to appear?(It disappears after 26 characters.)

![vditor30](https://user-images.githubusercontent.com/15811943/87876712-ac8b1300-c99f-11ea-97f8-f75e57182f80.gif)

**Comment by Vanessa219** [comment]
I cannot ignore spaces or any characters in the user input, so I defined the maximum key length as 32

**Comment by jakekwak** [comment]
Already selected `@test`.  after that,  I think there is no mention '@'. it means do not show the mention lists after. or please let me know how to use the mention lists.

**Comment by Vanessa219** [comment]
If there is `test a`, after selecting test, should the hint be displayed?

The relevant code is in `src/ts/hint`.

example:
```
at: (key) => {
      if ('vanessa'.indexOf(key.toLocaleLowerCase()) > -1) {
        return [
          {
            value: '@Vanessa',
            html: '<img src="https://avatars0.githubusercontent.com/u/970828?s=60&v=4"/> Vanessa',
          }]
      }
      return []
    },
```

**Comment by jakekwak** [comment]
thanks
