### ISSUE TITLE
行内代码删除错误

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#60]
![still](https://user-images.githubusercontent.com/15811943/71996717-8830cb80-31f1-11ea-8c4f-8579a1dd5794.gif)

**Comment by Vanessa219** [comment]
which is LButtonUp and LbuttomDown? when click at `公式 ` after， and press delete，I can not reappear.

![image](https://user-images.githubusercontent.com/970828/72051586-899bea00-32fe-11ea-8b08-f3f5046a965f.png)

**Comment by jakekwak** [comment]
Left button up/down at mouse.

Click,  enter, click again, delete please

or move the cursor key the front of a,  enter,  move the cursor back, and delete

**Comment by jakekwak** [comment]
click , del, del, del, del, del, del... (can not delete)
ctrl+z, ctrl+z, ctrl+z, ctrl+z.....
![cannotdelete](https://user-images.githubusercontent.com/15811943/73130553-c1be5080-3fbf-11ea-8433-4609bfbdeab1.gif)

**Comment by 88250** [comment]
Edit inline/block math and code should move caret into its content other than in render result:

![image](https://user-images.githubusercontent.com/873584/73130585-2fa55f00-4036-11ea-82b3-457856459865.png)

Undo related issues we will fix in https://github.com/Vanessa219/vditor/issues/85 thank you!

**Comment by jakekwak** [comment]
I think all text should be erased with only one backspace. try it from bottom.
