### ISSUE TITLE
[suggestion] Consitency

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#601]
Automatically added `Heading` and `code block`

but not `lists`.

When user enter the end of list,  it means he want to finish.

What do you think?

![vditor24](https://user-images.githubusercontent.com/15811943/87863196-48743a80-c91e-11ea-8b78-8c2143bc3464.gif)

**Comment by Vanessa219** [comment]
Maybe the user wants to input a paragraph with multiple lines in the list.

**Comment by jakekwak** [comment]
In that case, the user will use the `shift+enter`

**Comment by Vanessa219** [comment]
But when there is no list in this paragraph, the user only needs to press "enter" instead of "shift + enter"

**Comment by 88250** [comment]
@Vanessa219 I think we should handle <kbd>Enter</kbd> be the same regardless it in plain paragraph and list item paragraph, when the user press <kbd>Enter</kbd>, create a blank newline and move the caret to start of the second blank newline.

**Comment by Vanessa219** [comment]
I think in plain paragraph, most user press `enter` instead of `shift + enter`.

**Comment by jakekwak** [comment]
I know this well, but the current `sv` mode is improved markdown mode, so I need to think a little more flexible.
