### ISSUE TITLE
是否可以增加 markdown 包含js 的html代码，也可以执行到js代码

### ISSUE THREAD

**Issue by ihewro** [Vanessa219/vditor#606]
### 你在什么场景下需要该功能？

比如markdown中包含

```
<script>
alert("ok");
</script>
```

希望也可以解析出来，希望可以增加一个开关

因为我的使用场景，预览的文本都是可控的，没有xss风险。

在options里面，sanitize 设置为 false，仍然不能执行出这个js

**Comment by Vanessa219** [comment]
设置后 XSS 并没有过滤，可查看 http://vditor.b3log.org/demo/advanced-markdown.html

只是 script 脚本使用 innerHTML 渲染时时无法执行的。但导出成 HTML 以后时可以执行的。

**Comment by ihewro** [comment]
好的，我也通过别的方法实现了需求了
http://www.jcodecraeer.com/a/javascript/2012/0625/278.html
这篇文章中 有innerhtml 执行js脚本的方法，但是可能和vditor的功能无关啦
我先close 掉
