### ISSUE TITLE
wysiwyg 段落文字的情景菜单放左侧

### ISSUE THREAD

**Issue by HaujetZhao** [Vanessa219/vditor#607]
![image](https://user-images.githubusercontent.com/19181833/88030674-1f49e900-cb6e-11ea-9f36-d855bac36833.png)

左侧箭头指的地方好像是可以容下这个悬浮控件的

**Comment by fuyans20** [comment]
或者做成自定义显示？需要的时候就开启它，不需要的时候就不显示。
文字编辑的时候，这个东西漂浮在光标上面，比较影响感官。

**Comment by Vanessa219** [comment]
文字的话就放侧边，其余就老样子？

**Comment by fuyans20** [comment]
可以试试，不放在正文里面，遮挡住其他的字就行

**Comment by Vanessa219** [comment]
@HaujetZhao 不行呀，移动端没放出嘛
![image](https://user-images.githubusercontent.com/970828/88306449-515d7580-cd3d-11ea-8b16-8f9f1b56ffa3.png)

**Comment by YahuiAn** [comment]
可以提供一个配置控制是否启用该功能吗？

**Comment by Vanessa219** [comment]
用样式重置一下看看。
