### ISSUE TITLE
html 与 markdown 混写 某种情况下无法解析图片的语法

### ISSUE THREAD

**Issue by ihewro** [Vanessa219/vditor#609]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题

下面的markdown 无法解析
```
<div><!--这个地方加一个空行就可以解析了-->
![Jietu20200720-220655.jpg][1]
![Jietu20200720-220655.jpg][2]

这样的模块可以吗

</div>

  [1]: http://localhost/build/usr/uploads/2020/07/4008311631.jpg
  [2]: http://localhost/build/usr/uploads/2020/07/4008311631.jpg
```

`<div>`下面加一个空行就可以了

### 期待的结果

希望没有空行也可以解析

**Comment by 88250** [comment]
你好，这是 CommonMark/GFM 规范定义的，Vditor 遵循该规范。可以在 GitHub Issue 上对比一下解析渲染结果。
