### ISSUE TITLE
只引入method.min.js下的主题设置问题

### ISSUE THREAD

**Issue by HerbertHe** [Vanessa219/vditor#610]
### 描述问题

开发中有个需求是可以前端动态切换渲染编辑器的主题，在直接引入`index.js`设置中可以改变页面的`states`达到切换主题的目的，但是单纯只做渲染的话，`method.min.js`好像并不能达到在线通过请求CDN动态修改主题的文件，下面的代码在页面更新时触发无效。`index.js`可以将Vditor对象存入states中，但是用`method`好像达不到这个需求，想知道是`method`本身的显示还是引入的姿势不对。

```ts
Vditor.setContentTheme(
            !darkNow ? "light" : "dark",
            "http://localhost:3000/css"
        )
```

### 期待的结果

可以通过`setContentTheme`等函数实现编辑器渲染的主题样式切换

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by Vanessa219** [comment]
我刚才在 http://vditor.b3log.org/demo/preview.html 页面上试了一下是 OK 的。
```
Vditor.setContentTheme("dark", "https://cdn.jsdelivr.net/npm/vditor@3.3.10/dist/css/content-theme")
```

这个静态方法是用于切换渲染页面而不是编辑器的。编辑器需要使用编辑器的实例来调用方法 `vditor.setTheme` 具体可以参见http://vditor.b3log.org/demo

**Comment by HerbertHe** [comment]
@Vanessa219 我发现了bug在哪，我引入了Mobx作为全局的数据管理，然后注入到组件中。但是光用渲染的话拿不到vditor这个实例，无法触发componentDidUpdate这个方法，执行不了里面的静态方法，这个可以有替代方案吗？

**Comment by Vanessa219** [comment]
渲染的话就不需要使用编辑器，直接用 Vditor 对象就可以了。

**Comment by HerbertHe** [comment]
触发不了更新的生命周期，切换不了夜间模式，我得想想咋解决了emmmmm

**Comment by HerbertHe** [comment]
bug fixed了，我强制把页面刷新解决了

**Comment by Vanessa219** [comment]
感觉这个不需要 mobx，直接调用 Vditor 就可以了。 
```
Vditor.setContentTheme('dark', 'https://cdn.jsdelivr.net/npm/vditor/dist/css/content-theme')
```

**Comment by HerbertHe** [comment]
我把切换夜间模式的button绑定到了mobx的action上，，然后通过顶层数据注入来传递的，vditor实例化之后可以自动更新，静态方法不行，然后渲染器只渲染了无状态我调用reload刷新了页面。

**Comment by Vanessa219** [comment]
不太清除你的具体需求，http://vditor.b3log.org/demo/preview.html 在这个页面中直接运行 `Vditor.setContentTheme('dark', 'https://cdn.jsdelivr.net/npm/vditor/dist/css/content-theme')` 是可以的。页面渲染是不需要示例话的。

**Comment by HerbertHe** [comment]
emmmm我的需求是通过外部的组件通过action触发页面的渲染

**Comment by Vanessa219** [comment]
感觉应该是可以的，不论如何，解决就好。

**Comment by HerbertHe** [comment]
触发不了更新的生命周期，已经解决了嗯嗯
