### ISSUE TITLE
代码块-所见即所得

### ISSUE THREAD

**Issue by scucat** [Vanessa219/vditor#613]
### 插入代码块，查看代码高亮
vditor作者,你好!
如下图，我在编写代码块的时候，想实时查看代码高亮，以确定字符串之类的双引号是否写上等等。
但是vditor高亮代码在单独的一块区域，像下图就会出现遮挡，这样我不得不重新调整编辑区大小才行。
所以，代码块编辑能不能直接在高亮区域编辑呢？
![image](https://user-images.githubusercontent.com/51307285/88264993-4683f000-ccff-11ea-8809-ba53b2320efe.png)

### 高亮区域之间编写代码
希望能在高亮区域之间编写代码

**Comment by Vanessa219** [comment]
确定字符串之类的引号在书写过程中应该就可以确定的，下面只是为了给用户展现最终的渲染结果。如果觉得占位置的话可以 `options.preview.markdown. codeBlockPreview` 进行预览区域的配置

**Comment by Vanessa219** [comment]
我先关闭了，如有问题可以继续留言
