### ISSUE TITLE
添加 linkToImgUrl 回调

### ISSUE THREAD

**Issue by Vanessa219** [Vanessa219/vditor#614]

**Comment by Vanessa219** [comment]
@ihewro 有空的话可以具体说一下你的需求，我先挂着，等你呦

**Comment by ihewro** [comment]
> @ihewro 有空的话可以具体说一下你的需求，我先挂着，等你呦

和普通的图片上传接口一样的，需要在图片上传后进行一些界面处理

比如我的需求是，外链上传图片后或者普通上传图片后，右侧会有一个图片列表的显示
