### ISSUE TITLE
options.preview.theme.current 需设置不使用主题样式

### ISSUE THREAD

**Issue by ihewro** [Vanessa219/vditor#617]
### 你在什么场景下需要该功能？

说明 | 默认值
-- | --
current | 当前主题 | "light"
list | 可选主题列表 | { dark: "Dark", light: "Light", wechat: "WeChat" }
path | 主题样式地址 | https://cdn.jsdelivr.net/npm/vditor@${VDITOR_VERSION}/dist/css/content-theme

可以设置current值为null，表示不加载主题吗，我的项目中对markodwn已经写好了一份样式

现在可能有一个方法是，我在path里面填写我的项目的markdown的css地址，可以解决，但是需要拆分我的项目中的css

**Comment by Vanessa219** [comment]
好像不行，会报错，等我改改。如果不加载的话还需要在 toolbar 中把 content-theme 移除

PS: 如果拆分出来的话可以共享给我一份么？

**Comment by ihewro** [comment]
辛苦啦，拆分是说把我的项目的markdown css成总的css文件里面拆分成一个单独文件，然后path属性填写这个文件的资源地址，应该可以加载我自己的markodwn css文件 ，对vditor应该没啥帮助

**Comment by Vanessa219** [comment]
嗯，目前内置主题比较少，还在收集 https://github.com/Vanessa219/vditor/issues/346
