### ISSUE TITLE
怎么对特定内容不解析

### ISSUE THREAD

**Issue by liaosunny123** [Vanessa219/vditor#618]
能不能让vditor不在前台解析代码块，然后我用别的解析代码块的区域，剩下的区域就用vditor解析，然后后台也是vditor的编辑器

**Comment by 88250** [comment]
可以的，请自定义渲染器函数，参考 [Vditor 自定义渲染](https://hacpai.com/article/1588412297062)。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢。
