### ISSUE TITLE
粘贴数学公式时渲染报错

### ISSUE THREAD

**Issue by zTree** [Vanessa219/vditor#621]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

当粘贴多行文本中，且有多个 Mathjax 块时解析会不正常

#### 案例1：
````````markdown
-----------------------粘贴以下内容 --------------
下面是 A 的式子：

$$a = 1 + 2$$

下面是 B 的式子：

$$b = 2+3$$

下面是 C 的式子：

$$c = 3+4$$
-----------------------------------------------------
````````
直接出现解析错误，图片如下：
![image](https://user-images.githubusercontent.com/682855/88373682-db9feb00-cdca-11ea-85e9-914f895f34f6.png)
![image](https://user-images.githubusercontent.com/682855/88373739-f4100580-cdca-11ea-899c-929125444c8d.png)
![image](https://user-images.githubusercontent.com/682855/88373786-0ee27a00-cdcb-11ea-95f2-b5005e7f31db.png)

#### 案例2：
````````markdown
-----------------------粘贴以下内容 --------------
下面是 A 的式子：

$$
a = 1 + 2
$$

下面是 B 的式子：

$$
b = 2+3
$$

下面是 C 的式子：

$$
c = 3+4
$$
-----------------------------------------------------
````````
在 案例2 中 `分屏编辑预览模式` 显示完全正常；`所见即所得模式` 和 `即时渲染模式` 解析内容块正常，但是没有对 MathJax 进行渲染，除非粘贴后再进行 Keydown 输入内容
![image](https://user-images.githubusercontent.com/682855/88374315-22daab80-cdcc-11ea-92a6-0b38fe2ba01f.png)
![image](https://user-images.githubusercontent.com/682855/88374349-338b2180-cdcc-11ea-89ab-a080f4da5f29.png)

### 期待的结果

正确结果应该是粘贴后，对 Mathjax 块进行正确识别，并且进行渲染
![image](https://user-images.githubusercontent.com/682855/88374429-54ec0d80-cdcc-11ea-94e6-224a3c8fc2ef.png)

**Comment by 88250** [comment]
感谢反馈，这个问题主要是因为对形如 `$$foo$$` 的数学公式块解析有缺陷导致，已经改进。
