### ISSUE TITLE
html2md转换table有问题

### ISSUE THREAD

**Issue by zhicheng99** [Vanessa219/vditor#622]
html这样的table代码
![image](https://user-images.githubusercontent.com/2619464/88385261-98e90d80-cde0-11ea-8a6e-4cdd18ac5d3f.png)
 

转换后 缺少 |---| 而且都是换行的  
vditor 3.1.15

**Comment by 88250** [comment]
你好，请帖一下 HTML 代码，不要截图，谢谢。

**Comment by zhicheng99** [comment]
> 你好，请帖一下 HTML 代码，不要截图，谢谢。

`<table><tr><td><p>事件编号</p></td><td><p>事件类别(category)</p></td><td><p>事件操作(action)</p></td><td><p>事件标签(label)</p></td><td><p>事件值(value)</p></td></tr><tr><td><p>1</p></td><td><p>合作行业标签</p></td><td><p>点击</p></td><td><p>选择条件</p></td><td></td></tr><tr><td><p>2</p></td><td><p>营销目的标签</p></td><td><p>点击</p></td><td><p>选择条件</p></td><td></td></tr><tr><td><p>3</p></td><td><p>合作资源标签</p></td><td><p>点击</p></td><td><p>选择条件</p></td><td></td></tr><tr><td><p>4</p></td><td><p>合作平台标签</p></td><td><p>点击</p></td><td><p>选择条件</p></td><td></td></tr><tr><td><p>5</p></td><td><p>卡片</p></td><td><p>查看详情</p></td><td><p>案例名称</p></td><td></td></tr><tr><td><p>6</p></td><td><p>卡片</p></td><td><p>点赞</p></td><td><p>案例名称</p></td><td><p>点赞数</p></td></tr><tr><td><p>7</p></td><td><p>卡片</p></td><td><p>取消点赞</p></td><td><p>案例名称</p></td><td><p>点赞数</p></td></tr><tr><td><p>8</p></td><td><p>卡片</p></td><td><p>下载分享图</p></td><td><p>案例名称</p></td><td></td></tr></table>`

**Comment by 88250** [comment]
我刚刚在最新版上测试了一下，似乎没有问题：

![image](https://user-images.githubusercontent.com/873584/88483449-a6e28e00-cf9a-11ea-8930-97f20f591c76.png)

**Comment by 88250** [comment]
我先关闭提议了，如果还有问题欢迎继续跟帖反馈，谢谢。

**Comment by zhicheng99** [comment]
> 我先关闭提议了，如果还有问题欢迎继续跟帖反馈，谢谢。

升级到最新版本 可以了 谢谢
