### ISSUE TITLE
[New feature]extended Emoji for Font Awesome

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#625]
Font Awesome 4.7
```
<i class="fa fa-coffee" aria-hidden="true"></i>
```

:fa-coffee:  
:coffee:
:fa-ambulance: 
:ambulance:
:fa-address-book:

Font Awesome 5
:fas fa-coffee fa-2x:  
:fas fa-ambulance fa-xs: 
:fas fa-address-book fa-10x:
:fab fa-apple fa-lg:
:fab fa-apple-pay fa-5x:

**Comment by Vanessa219** [comment]
？

**Comment by jakekwak** [comment]
if possible

**Comment by Vanessa219** [comment]
We only set up the basic emoji, which can be extended with `options.hint.emoji`.

**Comment by jakekwak** [comment]
So I closed it.  thanks
