### ISSUE TITLE
为 <kbd> 提供单独的渲染效果

### ISSUE THREAD

**Issue by 88250** [Vanessa219/vditor#627]
https://github.com/WizTeam/WizNoteLite/issues/56

**Comment by 88250** [comment]
目前大致可以做到这样的效果：

![issue](https://user-images.githubusercontent.com/873584/88658259-b9c5a180-d105-11ea-94e0-365fb3d6d7c2.gif)

后续关于 HTML 标签方面的优化：

* 输入时自动完成闭合
* 光标在标签中时应该同时展开开始 `<tag>` 节点和结束 `</tag>` 节点

**Comment by jakekwak** [comment]
@88250 not working at wysiwyg mode
<img width="263" alt="Screen Shot 2020-07-30 at 3 08 13 PM" src="https://user-images.githubusercontent.com/15811943/88969630-c0bff180-d276-11ea-96c9-5344e6461436.png">

**Comment by 88250** [comment]
@jakekwak Thank you, no we just add this feature in IR mode. Later will add it in WG mode.
