### ISSUE TITLE
SV 模式 Setext 标题问题

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#636]
1. when enter
2. can not delete. 
![vditor1](https://user-images.githubusercontent.com/15811943/88697829-d7294a00-d0ca-11ea-8a7b-0b9f997d2081.gif)

if possible, after `three =` like, it looks more like GFM Spec.

![vditor2](https://user-images.githubusercontent.com/15811943/88698061-2cfdf200-d0cb-11ea-81cc-6ecf1c4d9a1a.gif)

**Comment by 88250** [comment]
Thank you, we will change the length of `=` or `-` to the length of the last line of the heading text.

**Comment by jakekwak** [comment]
@88250 Did you fix the first image issue? (when enter, have to go to the next line and delete issue)

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/642

**Comment by Vanessa219** [comment]
I fixed 1 and 2

@88250, pls research it. 

> if possible, after `three =` like, it looks more like GFM Spec.
> 
> ![vditor2](https://user-images.githubusercontent.com/15811943/88698061-2cfdf200-d0cb-11ea-81cc-6ecf1c4d9a1a.gif)

**Comment by Vanessa219** [comment]
The CommonMark just has one `=`
