### ISSUE TITLE
emoji at sv

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#637]
current:
![vditor3](https://user-images.githubusercontent.com/15811943/88710925-f6c96e00-d0dc-11ea-8a8c-73959b7888a5.gif)

I think this one is better
![vditor4](https://user-images.githubusercontent.com/15811943/88710950-034dc680-d0dd-11ea-9975-8fae1806c379.gif)

**Comment by 88250** [comment]
`:j:` is an image emoji, so I think we should not insert the `<img>` directly.

**Comment by jakekwak** [comment]
@88250 I know, can we make this image same as wysiwyg mode when select it.(not typing it)

**Comment by Vanessa219** [comment]
This is the sv mode, only markdown text can be entered.
