### ISSUE TITLE
列表嵌套代码块后输入中文的问题

### ISSUE THREAD

**Issue by 88250** [Vanessa219/vditor#639]
# 描述问题
> 出代码块后, 输入1次回车, 跳到本层列表, 再输入一次回车, 跳到上层列表, 此时输入文字, 无法直接输入, 会跳回代码块, 必须先输入数字, 然后才能输入文本
# 期待的结果
> 不论往上跳几层, 输入文字应该不应该回跳
# 截屏或录像
![bug](https://user-images.githubusercontent.com/25242107/87289977-f606d880-c52f-11ea-8328-27660e57d8f3.gif)

原始 issue https://github.com/88250/liandi/issues/84

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/361
