### ISSUE TITLE
SV 模式 setext 问题

### ISSUE THREAD

**Issue by Vanessa219** [Vanessa219/vditor#642]
- [x] 光标位置删除后标题无法渲染
![image](https://user-images.githubusercontent.com/970828/88770714-c94df480-d1b0-11ea-8b08-680c89467329.png)

- [ ] test 后换行异常 
```
test
====
```
- [ ] 光标前无法删除
![image](https://user-images.githubusercontent.com/970828/88789061-d37bed00-d1c8-11ea-84ec-7aefd21debd3.png)

**Comment by 88250** [comment]
> 光标前无法删除

ATX 标题也有这个问题，暂时不处理了吧，亲。
