### ISSUE TITLE
[BUG] 复制 markdown 格式的文本 会 自动添加  ``` ```

### ISSUE THREAD

**Issue by dreamer2q** [Vanessa219/vditor#649]
将下面一段markdown格式文本复制到vditor会自动添加 ` ``` ``` `

```
# example

this is an example 
```

怎么说，我都是在vscode上面写好后md往博客上面复制就完事了。

但是，博客某主题升级后强制使用`vditor`, 导致我无法复制粘贴发布完事。

就折腾到这里发布一个issue好了。

**Comment by Vanessa219** [comment]
这是特性，识别到从 vscode 中复制，会自动加上代码符号。不需要的话，可以使用 ctrl+shift+v

**Comment by dreamer2q** [comment]
@Vanessa219   上面一段不是从vscode 里面复制（例如从浏览器中复制）也会产生同样的效果。这还是特性吗？

**Comment by Vanessa219** [comment]
只要识别到代码片段就会自动为其加上 Markdown 的代码块标记符

**Comment by dreamer2q** [comment]
明白了

但是上面那一段文字显然不是代码格式却被看成了代码，希望能改进一下识别方式。

此外，一般情况下往markdown里面复制代码的时候都会手动加入` ``` + language `用来表明这是何种语言的代码。

vditor这个特性是否对我们重度使用者有些多余呢？因为复制粘贴的表现完全不符合预期（我以为是bug）。

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/88824698-44d39400-d1f9-11ea-9801-604264d15b04.png)

识别方式应该没问题，如果代码块（pre code）上存在 `class="language-xxx"`，还能自动加上` ```xxx `，习惯一下就好了，感谢反馈。
