### ISSUE TITLE
移动端访问jsdelivr的链接，全部报错403

### ISSUE THREAD

**Issue by xianjerry** [Vanessa219/vditor#652]
移动端访问jsdelivr的链接，全部报错403，以后是要把dist目录的全部下载放到自己的服务器了吧。

突然移动端用不了，就炸了，笔记也看不到。

![auaS3Q.jpg](https://s1.ax1x.com/2020/07/30/auaS3Q.jpg)

**Comment by xianjerry** [comment]
下午3点多才恢复了访问。

**Comment by Vanessa219** [comment]
可使用自行搭建的 CDN https://hacpai.com/article/1549638745630#CDN-%E5%88%87%E6%8D%A2
