### ISSUE TITLE
SV 模式打字机模式问题

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#658]
![vditor8](https://user-images.githubusercontent.com/15811943/88981376-69784c00-d28b-11ea-8e76-24f69818ecf1.gif)

**Comment by jakekwak** [comment]
still same issue
![vditor13](https://user-images.githubusercontent.com/15811943/89094408-26040780-d389-11ea-8b43-f08eddc02ec1.gif)

**Comment by Vanessa219** [comment]
fixed in 3.4.2
