### ISSUE TITLE
IR 模式复制粘贴 <kbd> 问题

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#659]
![vditor9](https://user-images.githubusercontent.com/15811943/88981943-b90b4780-d28c-11ea-8843-e019dfc9ddda.gif)

**Comment by jakekwak** [comment]
I think this one is working good.

**Comment by Vanessa219** [comment]
Long time no see, I close it.

**Comment by jakekwak** [comment]
I have been to Korea for 5 months.
