### ISSUE TITLE
[New Feature] auto increase the height

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#671]
I want to use Vditor for  comments.

![vditor17](https://user-images.githubusercontent.com/15811943/89095662-a892c400-d395-11ea-99ec-a382d3b051f6.gif)

![vditor18](https://user-images.githubusercontent.com/15811943/89095686-dd9f1680-d395-11ea-88c9-a655d37dad85.gif)

**Comment by Vanessa219** [comment]
Pls refer this demo: http://vditor.b3log.org/demo/option-size.html

**Comment by jakekwak** [comment]
thanks
