### ISSUE TITLE
代码块中输入三个 `

### ISSUE THREAD

**Issue by Vanessa219** [Vanessa219/vditor#672]
代码块中输入三个 `
在 Typora 中，代码块中是可以在行首输入三个 ` 的。Vditor 中不行了。查看 Markdown 源格式，发现 Typora 会在代码块这种特殊行的行首加入一个占位符：

![image](https://user-images.githubusercontent.com/970828/89098876-d7547d00-d41d-11ea-939b-e77d20e87075.png)

**Comment by aysaml** [comment]
同样遇到此问题，导致从 IDEA 直接复制代码到编辑器中代码块格式不正确。

**Comment by 88250** [comment]
@aysaml 试试粘贴为纯文本
