### ISSUE TITLE
[Feature Request] music player for abcjs

### ISSUE THREAD

**Issue by woosungchoi** [Vanessa219/vditor#675]
![abcjs-musiplayer](https://user-images.githubusercontent.com/5674610/89147850-ef014200-d592-11ea-8c96-5e344c0b07b0.png)

I think abcjs has a built in music player.

https://www.abcjs.net/abcjs-editor.html

You can check it in the link above.

It would be better if the music player is automatically output when music(score) is attached.

**Comment by 88250** [comment]
I won't consider it, for now, thanks for the suggestion.
