### ISSUE TITLE
请求：增加 Ant Design 主题

### ISSUE THREAD

**Issue by ElderJames** [Vanessa219/vditor#676]
基于 #578 中的讨论，添加了图标后，再开一个issue。

可以参考原样式: 

- markdown渲染样式: https://github.com/ant-design/ant-design/blob/master/site/theme/static/markdown.less
- 代码高亮样式:  https://github.com/ant-design/ant-design/blob/master/site/theme/static/highlight.less
- 文本框的样式: https://github.com/ant-design/ant-design/blob/master/components/input/style/index.less
- 按钮动画效果：https://github.com/ant-design/ant-design/blob/master/components/button/style/index.less

这样就能很好地跟ant design结合了，可以推荐到使用ant design的项目中，与react、angular、vue和blazor都能集成起来。

十分感谢作者的付出！

**Comment by yuanxiongwei** [comment]
非常支持，或者增加自定义主题

**Comment by Vanessa219** [comment]
@yuanxiongwei 编辑器分为三类主题，其方法如下： https://hacpai.com/article/1549638745630#%E4%B8%BB%E9%A2%98

**Comment by Vanessa219** [comment]
@ElderJames 

* 按钮没有用到就不添加了
* 输入框只在 wysiwyg 模式中的场景菜单中使用到，为无边框设计。目前没找到好的适配样式，有合适的可以推荐一下
* 其余将在 3.4.6 中发布
