### ISSUE TITLE
多级列表下取消列表的方式改进

### ISSUE THREAD

**Issue by NoverNobida** [Vanessa219/vditor#678]
### 你在什么场景下需要该功能？

在二级(或二级以下)列表，无法快速的转换为非列表，只能一步一步按 <kbd>enter</kbd> 退到一级列表，再按 <kbd>enter</kbd> 转换为非列表，转换到非列表后，不能返回到原先的二级二级(或二级以下)列表，因此，无法完成 【两个二级(或二级以下)列表之间输入文本，代码框等】，例如下图所示的输入(由：[mark text](https://github.com/marktext/marktext) 实现)
![image](https://user-images.githubusercontent.com/46912250/89165689-7f4b8100-d5ab-11ea-91e1-2b71e1eff66d.png)

![1](https://user-images.githubusercontent.com/46912250/89168805-f97e0480-d5af-11ea-9a21-357a66f5e196.gif)
上面的输入在vditor中无法实现：
![2](https://user-images.githubusercontent.com/46912250/89168821-fe42b880-d5af-11ea-8340-902d3edab45d.gif)

清除了列表符号后，一方面没有办法把输入内容层级调整到和二级列表一样，既不美观，也容易把层级搞混，因为会受到另一个特性(输入多个空格或者点击<kbd>tab</kbd>，会转换为代码框，无法输入普通文本)的干扰。另一方面，没有办法回到二级列表了，如上图，当我还有一个b3要输入的时候，没有办法输入二级列表。

### 描述可能的解决方案

在空白二级标签的时候，点击<kbd>backspace</kbd>应该是清除列表符号（而不是直接退格，返回之前内容），再点击一次回到之前内容，正如[mark text](https://github.com/marktext/marktext) 所展现的那样。

**Comment by 88250** [comment]
列表项中使用 Shift+Enter 就可以在该列表项中换行了，感谢细致的反馈。

![issue](https://user-images.githubusercontent.com/873584/89171077-326ba880-d5b3-11ea-97cc-6f6d1bb86150.gif)

**Comment by NoverNobida** [comment]
感谢解决问题！
