### ISSUE TITLE
html2md (Copy & Paste)

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#680]
I try to copy & paste [the keyboard shortcut](https://hacpai.com/article/1582778815353)

Original
<img width="561" alt="Screen Shot 2020-08-03 at 1 49 52 PM" src="https://user-images.githubusercontent.com/15811943/89216590-44881f80-d590-11ea-9df1-77f1891a0684.png">

copy & paste it, `(adsbygoogle = window.adsbygoogle || []).push({});`

<img width="727" alt="Screen Shot 2020-08-03 at 1 51 01 PM" src="https://user-images.githubusercontent.com/15811943/89216660-6681a200-d590-11ea-8cd7-52c38b7721c8.png">

**Comment by Vanessa219** [comment]
this is google ads. you can login and try it.

**Comment by jakekwak** [comment]
When copying & pasting, can you make it disappear?

**Comment by Vanessa219** [comment]
I cannot control the user's copying, but the user can choose what to copy. 

If I delete what the user wants, the user will never be able to paste it.
