### ISSUE TITLE
图片使用引用风格时的解析问题

### ISSUE THREAD

**Issue by ihewro** [Vanessa219/vditor#684]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 编辑模式

请选择你遇到问题时使用的编辑模式（把正常情况模式删掉）：

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

首页在分屏编辑模式下 **复制粘贴**下面的代码：

```
![90331d51a2d6ea49b9e9f777db757eb1.png][1]

[1]: https://b3logfile.com/file/2020/08/df3010e2c713428eb0e6edb9458bc826.png
```

编辑器里面显示的内容是：

```
![90331d51a2d6ea49b9e9f777db757eb1.png][1](https://b3logfile.com/file/2020/08/df3010e2c713428eb0e6edb9458bc826.png)

[1]: https://b3logfile.com/file/2020/08/df3010e2c713428eb0e6edb9458bc826.png

```

编辑器没有把`[1]`去掉，这个时候切换到所见即所得模式，再切换到分屏预览模式，编辑器显示的是：

```
![90331d51a2d6ea49b9e9f777db757eb1.png](https://b3logfile.com/file/2020/08/df3010e2c713428eb0e6edb9458bc826.png)(https://b3logfile.com/file/2020/08/df3010e2c713428eb0e6edb9458bc826.png)

[1]: https://b3logfile.com/file/2020/08/df3010e2c713428eb0e6edb9458bc826.png
```

就会多一个图片的链接文本

### 期待的结果

对参考式的语法进行正确解析，如果可以不改变参考式的原本源码就好了

---

还有一个定义部分的冒号问题： https://github.com/Vanessa219/vditor/issues/696

**Comment by 88250** [comment]
图片使用链接引用风格的两个问题应该已经修复，稍后待版本发布后请更新帮忙测试，谢谢。
