### ISSUE TITLE
options.icon 增加判断如果没有该属性则不引入js

### ISSUE THREAD

**Issue by ihewro** [Vanessa219/vditor#685]
### 你在什么场景下需要该功能？

因为我自己前端使用vdtior 进行解析markdown，而不需要图标和外部样式，所以希望可以不引入这个图标库，默认的是ant.js

### 描述可能的解决方案

https://github.com/Vanessa219/vditor/blob/916366faaa6a370c4bb499e7b2023616db3d09b0/src/ts/markdown/previewRender.ts#L105

增加判断属性是否存在

**Comment by ihewro** [comment]
3.4.5 似乎又取消掉了

**Comment by ihewro** [comment]
https://github.com/Vanessa219/vditor/blob/dead8ca4fd1d052f277892e286f0e8b7566a59bf/src/ts/markdown/previewRender.ts#L105

**Comment by Vanessa219** [comment]
抱歉，只在编辑器里面加了。预览的时候没有进行处理
