### ISSUE TITLE
Code 内 Enter/Backspace/Delete 可能不触发 input，并导致 Code 不及时渲染

### ISSUE THREAD

**Issue by zTree** [Vanessa219/vditor#687]
### 编辑模式

请选择你遇到问题时使用的编辑模式（把正常情况模式删掉）：

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式

### 描述问题

在 Code 内输入 回车/Delete/Backspace 增加或删除空行， 代码段不会及时渲染。
经排查，发现 input 事件没有被触发，从而导致渲染没有被执行，怀疑可能是 Lute 导致，请进行排查

![CodeEnterDeleteBackspace](https://user-images.githubusercontent.com/682855/89386696-fe6bc100-d733-11ea-9ff5-1f7297526eba.gif)

**Comment by xingyuzhe** [comment]
请教下 delete 可能不触发input的问题解决了不, 有啥上下文不?

**Comment by Vanessa219** [comment]
请新开 issue 把重现步骤描述一下
