### ISSUE TITLE
Backspace 操作导致 previousElement 内开头的 软换行丢失

### ISSUE THREAD

**Issue by zTree** [Vanessa219/vditor#690]
### 编辑模式

* `ir` 即时渲染模式

### 描述问题
此 Issue 是在修正 Issue  https://github.com/Vanessa219/vditor/pull/689 后，产生的。

通过截图，可以发现，由于 Lute 处理导致的 开头换行丢失

![BackspaceIssue02](https://user-images.githubusercontent.com/682855/89398931-54e0fb80-d744-11ea-9f1c-1277cc8b4c69.gif)

### 探讨：
按照一般 markdown 解析来讲，在文本开头部分的 换行被抛弃是很正常的。但 在目前编辑器的显示逻辑上来说，就产生了一定的矛盾。

例如：
```
abc



xyz
```
以上这段文字，在正常的 markdown 渲染中，肯定会把中间多余的换行处理为以下情况：
```
abc
xyz
```

而目前 Vditor 在 即使渲染模式 和 所见即所得模式 中 编辑时是允许插入多个空行的。 所以，这个问题到底应该如何修改，我也没有想好一个非常妥善的解决方案，

想法1：在满足当前逻辑的情况下，是否可以区分 初始化时的渲染 和  编辑时的渲染，这样，就可以保证在编辑过程中的渲染时，并不会直接扔掉开头的回车（这里面有个问题是，是否编辑时所有的 在开头的空行都是绝对不能删除的么？）

想法2：换个思路，同样的渲染，但这个问题在 所见即所得模式中，并不存在，因为这个模式的 input.ts 中 并没有 “// 换行时需要处理上一段落” 这个逻辑，所以他并没有产生这个问题。

原谅我，写到这里的时候，我发现按照 Lute 的处理逻辑 所见即所得模式 也会有空行跳动的情况
![BackspaceIssue03](https://user-images.githubusercontent.com/682855/89400662-cae66200-d746-11ea-99ff-3b5c0062b0b0.gif)

现在我也有些迷惑了，这种情况，到底是否属于 Issue？ 可能更多的是属于 对 Markdown 渲染规则的处理。

我去看了一下 Typora，他是始终保留 空行，所以也就不会产生此类问题。

**Comment by Vanessa219** [comment]
这个主要是考虑到导出后，渲染出的 HTML 会和编辑器里有点不一致。但是阻止用户输入又不太友好，综合考虑就做出了一个比较矛盾的体验。我们也一直在纠结这个问题。

**Comment by 88250** [comment]
这问题我也有点迷 😂 

之前也[讨论](https://github.com/Vanessa219/vditor/issues/464)过， 暂时没有解决方案。也许熟悉 Markdown 的用户能够理解（这是一个特性），但是对于不太熟悉 Markdown 的用户来说就有点难理解了，用户会觉得这是一个缺陷。

反过来看，如果保留段落间的空行，那么最终渲染时根据 Markdown 规范肯定是踢掉空行的，这对于不熟悉 Markdown 的用户来说也会产生疑问。类似的问题还有中文段首缩进。

我个人认为还是先坚持 Markdown 规范吧，尽量做到编辑时和最终渲染时效果一致。也许以后 Markdown 变得普及了，可能也就顺其自然了。

**Comment by Vanessa219** [comment]
我先关闭了，如果有新的想法在 reopen
