### ISSUE TITLE
图片显示问题

### ISSUE THREAD

**Issue by Kmeyel** [Vanessa219/vditor#693]
### 编辑模式
直接调用 preview 方法 对页面中的 Markdown 进行渲染。

### 描述问题
渲染出来的图片不是响应式的；若图片大，则易超出边界。

### 期待的结果
希望渲染出来的图片是响应式的，大小随div宽度变化而自动适应。

### 截屏或录像
![image](https://user-images.githubusercontent.com/43575500/89438163-10248700-d77b-11ea-9722-16db560f30e9.png)

### 其他信息
现场还原
```html
<body>
<div id="text-show"></div> 
<script src="./method.min.js"></script>
<script>
        var show = document.getElementById("text-show");
        var md = “一个md文档的内容” ;
        Vditor.preview(show,md);
</script>
</body>
```

**Comment by Vanessa219** [comment]
你在内容上加一个 `class="vditor-reset"` 试一下？

**Comment by Kmeyel** [comment]
谢谢您，折腾一下午终于解决了，是我自己的锅，sorry。
