### ISSUE TITLE
sv 模式下删除操作的问题

### ISSUE THREAD

**Issue by ihewro** [Vanessa219/vditor#695]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 编辑模式

请选择你遇到问题时使用的编辑模式（把正常情况模式删掉）：

* `sv` 分屏编辑预览模式

### 描述问题

https://vditor.b3log.org/demo/option-mode.html

在这个页面中，先点击最后一个按钮：“sv 模式 - 编辑器 & 预览”

然后鼠标点在这一段文字的中间，按下键盘的删除键，光标后面的文本也被删掉了。

后续再进行操作，结果是正常的了，只有第一次的时候会这样。

### 期待的结果

希望只删除光标前面的一个字符。

**Comment by cysui** [comment]
在前面一段内容里回车，也会导致下一段的内容消失

**Comment by Vanessa219** [comment]
你更新到 3.4.4 再试试

**Comment by ihewro** [comment]
是正常的了～～
