### ISSUE TITLE
图片参考式解析问题：Uncaught Error: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ihewro** [Vanessa219/vditor#696]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 编辑模式
三种模式下都会报错

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

http://vditor.b3log.org/demo/option-mode.html

在这个编辑器中，输入下面的文本，打开控制台，三个模式下都会有报错
````````markdown
![][1]

[1]:https://gravatar.helingqi.com/wavatar/d9645f85fb9ecddfe23b1c7325fe6af6
````````

**Comment by ihewro** [comment]
```
![][1]

[1]: https://gravatar.helingqi.com/wavatar/d9645f85fb9ecddfe23b1c7325fe6af6
```

冒号后面加一个空格就正常了，但是希望可以不报错，保留原文本或者给出一个错误位置的提示

**Comment by 88250** [comment]
合并到 https://github.com/Vanessa219/vditor/issues/684 中一并修复，感谢反馈。
