### ISSUE TITLE
实时协同编辑

### ISSUE THREAD

**Issue by 88250** [Vanessa219/vditor#699]
diff/OT/CRDT

**Comment by naiba** [comment]
最近在做个小工具，线上面试，webrtc视频，vditor实时协同编辑，运行代码， [naiba/helloengineer](https://github.com/naiba/helloengineer)
使用了 halfmoon，一键darkmode， @Vanessa219 可以给编辑器增加 darkmode 吗，嘻嘻

今天是来提 darkmode 的，就无耻的接在协同编辑这里，请问一下：

1. 现在展示多个光标在编辑器中是可行的吗？（展示多个人光标所在位置）可以提供一下指引吗？
2. 同步多个人的编辑器内容现在最优方案是啥？因为预计会在代码预览那里的 copy 按钮旁边加一个运行按钮，运行结果在预览框下面加一个运行结果框。希望把执行结果也同步给每个人。


私事：hacpai 用户 naiba 密码忘了，帮忙重置一下 hi@nai.ba ，要donate 😄

**Comment by Vanessa219** [comment]
有在线的么？
darkmode 指的是： https://b3log.org/vditor/demo/method-theme.html 这个么？

1. 目前光标使用 `<wbr>` 标签 ，可以替换他以显示多人位置
2. 同步应该要找一个算法来合并内容吧

PS：密码已重置

**Comment by naiba** [comment]
darkMode 找到了，已经用上了

> PS：密码已重置

因为之前 1@5.nu 的邮箱不用了，GitHub也没绑定，还是要麻烦换绑到我的邮箱或者绑定一下 GitHub，我的 GitHub ID 29243953 登录名 naiba

**Comment by 88250** [comment]
@naiba 邮箱地址已经帮你更新了，GitHub 绑定请自己操作 https://hacpai.com/settings/account

**Comment by naiba** [comment]
找到一个关键词，Operational Transform。
- 通过 setValue 来同步更新会有性能问题吗？
- 现在vditor 会分片渲染，还是onChange后整个文档重新渲染？

**Comment by Vanessa219** [comment]
1. 看 value 值大小
2. 仅打字的时候会分片渲染，首次加载不会

**Comment by 88250** [comment]
暂时不考了。
