### ISSUE TITLE
支持站点、视频、音频解析

### ISSUE THREAD

**Issue by Vanessa219** [Vanessa219/vditor#7]
Is is possible to support to embed youtube link ( see https://ckeditor.com/ckeditor-5/demo/ )

looks like below image

![](https://user-images.githubusercontent.com/15811943/64065919-6b4c1200-cbd9-11e9-9415-7ba428111943.png)

**Comment by ColinLQ** [comment]
@Vanessa219 只想贴给个链接，点击跳转过去，不想被解析，请问有什么方法实现没？

**Comment by Vanessa219** [comment]
参照 https://github.com/Vanessa219/vditor/blob/fdc7aea970e4044a172a4515c4c6af38bbda8abd/src/ts/markdown/previewRender.ts ，最后不要调用 mediaRender
