### ISSUE TITLE
光标非正常移动

### ISSUE THREAD

**Issue by speakice** [Vanessa219/vditor#706]
![image](https://user-images.githubusercontent.com/18417722/89807759-aede2880-db6b-11ea-9104-fb98bef19ad3.png)

看中间那个s， 我由于输入法切换的问题，删除s之后，光标自动移动到h3那行的开头了，因为输入>号需要切换成英文输入，后面应该有很多人都会忘记切输入法直接输入，发现输入法错误，删除，然后光标莫名其妙地跑了，再切换到下一行，再输入> , 可能会循环好几次，很不舒服

**Comment by Vanessa219** [comment]
ir 模式没有返回 wbr @88250 
![image](https://user-images.githubusercontent.com/970828/89852722-0b6c3280-dbc2-11ea-8610-4325f12985a9.png)

**Comment by speakice** [comment]
辛苦，辛苦
