### ISSUE TITLE
优化移动端体验

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#71]
![Screenshot_20200112-184527_Chrome](https://user-images.githubusercontent.com/15811943/72230722-3e870e80-356c-11ea-8195-1e149c1964d8.jpg)

And more toolbar option for testing.

**Comment by Vanessa219** [comment]
I tried some methods, but it didn't work out well. Do you have any good suggestions or demo?

**Comment by jakekwak** [comment]
I mean the toolbar is not showing when i try to click the editor pane.

**Comment by Vanessa219** [comment]
I know, but I don't have a good solution. Can you give some suggestions?

**Comment by jakekwak** [comment]
I want to test the vditor at the mobile. Is it mobile first? right?
When I click the editor pane at the demo, the toolbar pane have to be remained with more icon(same as desktop)

**Comment by jakekwak** [comment]
I want to test this editor using smartphone.  please activate all toolbar.
![2](https://user-images.githubusercontent.com/15811943/73130460-68a1ed00-3fbe-11ea-8f27-5c2ffa04c09b.PNG)

**Comment by Vanessa219** [comment]
pls reload again

**Comment by jakekwak** [comment]
I don't know which one is good for mobile. 
but my idea is like picture..(WYSIWYG mode)
or special charater icon ( Markdown mode)
![7](https://user-images.githubusercontent.com/15811943/73370967-a6cb3500-427a-11ea-9a2c-b579d2f0a3e2.png)

**Comment by jakekwak** [comment]
@88250  I think the next plan will be mobile browser.  android phone, iphone, android tablet, iPad etc.
What do you think about your next plan?

**Comment by 88250** [comment]
@jakekwak Yes, you are right, it's time to keep moving on mobile-end. We can discuss it with @Vanessa219, decide the first thing we should do.

**Comment by stevapple** [comment]
I personally suggest the toolbar to keep floating on the top when it’s in a mobile(narrow) browser. When it comes to tablet side, the exisiting desktop experience may win. It works well with iPadOS.

**Comment by jakekwak** [comment]
@stevapple I'm testing various browser at mobile environment.
I think `trix` is good ui.  https://trix-editor.org/

**Comment by stevapple** [comment]
@jakekwak I think `trix` is no better than `vditor` st the moment. Tested on iOS, the former has a problem of UI dislocation while the latter works pretty well. 

`vditor` can consider to pin its bar onto the top of the screen and increase button sizes by a little bit. That’s the point.

**Comment by Vanessa219** [comment]
@stevapple  @jakekwak do you like pin toolbar or floating bar?
![image](https://user-images.githubusercontent.com/970828/78539954-f6ebe800-7825-11ea-9012-15b0a1ede4eb.png)

**Comment by jakekwak** [comment]
How about the `trix` style.  sticky toolbar style.

**Comment by Vanessa219** [comment]
@jakekwak pin toolbar is trix style

**Comment by jakekwak** [comment]
@Vanessa219 I tested the popular html editor. (froala, ckeditor4, Redactor, trix, summernote, tiptap etc.)
I think pin toolbar style is easier than others

**Comment by stevapple** [comment]
The improvements of top bar may introduce a new mode in which the `height` of the editor is set to be the full length of content (dynamically) and virtual scrolling (scrolling `inside` the editor instead of `window`) is disabled. When the user scrolls over the content, top bar is sticked to (pinned at) the top of the `window`. (Like the `trix` one, I’ve got the point)

When it comes to the floating bar (currently), I think the biggest problem now is the size...Too small for smartphones (fairly speaking, not even big enough for desktop), thus hard to touch. 

I think the size issue is more urgent, as full-screen mode is a fine substitute except for button sizes.

**Comment by 88250** [comment]
So, is the "pin bar" the best design on the mobile-end? Can I consider that we have reached an agreement? 😃

**Comment by stevapple** [comment]
I think so. Just pin it on the top of the `window` If it should be above.

**Comment by jakekwak** [comment]
@88250 Me, yes.  
What is the best tesing env for smartphone?  When I use the `ngrok`,  the error msg is "invalid Host Header",
Can I disable this error temporarily? or any other good testing env.

**Comment by stevapple** [comment]
@jakekwak What do you mean by “testing env”? Running the dev server on a PC and try it out on a phone within the same LAN is easy and stable enough.

**Comment by jakekwak** [comment]
If possible, could you make experimental branch for IR mode.
Can type special symbols that are difficult to type on the keyboard.
![Screenshot_20200331-110556](https://user-images.githubusercontent.com/15811943/78581299-5089ed80-77f9-11ea-8b55-37a14e2cedd0.png)

**Comment by 88250** [comment]
@jakekwak I agree with @stevapple: use the same WiFi with phone and PC should work.

**Comment by jakekwak** [comment]
@stevapple @88250 thanks.

**Comment by Vanessa219** [comment]
> If possible, could you make experimental branch for IR mode.
> Can type special symbols that are difficult to type on the keyboard.
> ![Screenshot_20200331-110556](https://user-images.githubusercontent.com/15811943/78581299-5089ed80-77f9-11ea-8b55-37a14e2cedd0.png)

you can set the toolbar yourself.
```
toolbar: [
    {
      name: "point",
      prefix: ".",
      icon: ".",
      tip: 'point',
      tipPosition: 'ne',
      click: () => {
        vditor.insertValue('.', false)
      },
    }
  ],
```

**Comment by jakekwak** [comment]
@Vanessa219 Thanks, Can I put custom svg icon instead of  text icon(`icon: "."`.)?

**Comment by Vanessa219** [comment]
@jakekwak of course

**Comment by lhlyu** [comment]
like:
![IMG_20200408_095016](https://user-images.githubusercontent.com/41979509/78735923-7c82ab80-797e-11ea-98b0-b84768d329e7.jpg)

**Comment by stevapple** [comment]
@lhlyu Since `vditor` is a web-based editor, it cannot copy the approach of designing a native editor app which provides heavy functions nested in the same button. Also, it should consider the experience consistency between desktop and mobile-end. 

However, a bottom bar may be introduced in the full-screen mode to provide text inserts, like the one @jakekwak suggests.

**Comment by Vanessa219** [comment]
Maybe there is no API, so the pin top may be better than compatible with the bottom calculation?

**Comment by stevapple** [comment]
It’s necessary to pin the top bar. Meanwhile, @jakekwak is adding some text insertion buttons on it, which may make it a little bit messy. @jakekwak, can the existing buttons like `heading` and `bold` satisfy your need? It works well on iOS.

**Comment by jakekwak** [comment]
@stevapple Always I don't know which method is good.
but if make some experimental branch for testing at every device.
Everybody can test which one is good.
My first idea is that user can select normal toolbar for wysiwyg mode or text toolbar for ir mode.
I try to test custom toolbar option (combined toolbar). 
if I may not find it, but I am trying to find an easier way than current input method.

**Comment by jakekwak** [comment]
Here is some demo at android phone(chrome).
1. sticky toolbar and touch friendly button.
2. custom toolbar for indent, outdent like trix
3. When touched the bottom after code, can not input
![20200407_223150](https://user-images.githubusercontent.com/15811943/78741789-e881f700-791f-11ea-99e8-2aa28f6c69fe.gif)

**Comment by Vanessa219** [comment]
@jakekwak how does trix customize indent and outdent?

**Comment by jakekwak** [comment]
@Vanessa219 I mean the user can do to put the indent in the toolbar.

**Comment by Vanessa219** [comment]
@jakekwak you mean this issue https://github.com/Vanessa219/vditor/issues/286

**Comment by jakekwak** [comment]
@Vanessa219 Yes,  Thank you
