### ISSUE TITLE
建议 Markdown 解析的 a 标签加上 rel="nofollow"

### ISSUE THREAD

**Issue by ronger-x** [Vanessa219/vditor#712]
建议 Markdown 解析的 a 标签加上 rel="nofollow",此举可以优化文章的 SEO 权重.希望官方可以支持

> nofollow 是 HTML 页面中 a 标签的属性值。这个标签的意义是告诉搜索引擎 " 不要追踪此网页上的链接或不要追踪此特定链接 "。
>
> nofollow 是 HTML 页面中 a 标签的属性值。它的出现为网站管理员提供了一种方式，即告诉搜索引擎 "不要追踪此网页上的链接" 或 "不要追踪此特定链接"。这个标签的意义是告诉搜索引擎这个链接不是经过作者信任的，所以这个链接不是一个信任票。
>
> nofollow 标签是由谷歌领头创新的一个 “反垃圾链接” 的标签，并被百度、yahoo 等各大搜索引擎广泛支持，引用 nofollow 标签的目的是：用于指示搜索引擎不要追踪（即抓取）网页上的带有 nofollow 属性的任何出站链接，以减少垃圾链接的分散网站权重！
>
> 简单的说就是，如果 A 网页上有一个链接指向 B 网页，但 A 网页给这个链接加上了 rel="nofollow" 标注，则搜索引擎不把 A 网页计算入 B 网页的反向链接。搜索引擎看到这个标签就可能减少或完全取消链接的投票权重

**Comment by 88250** [comment]
后续考虑扩展，目前只能先在外围应用层加。
