### ISSUE TITLE
insertValue 无法插入html文本

### ISSUE THREAD

**Issue by ihewro** [Vanessa219/vditor#716]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

```javascript
                        vditor.insertValue('<font color="red">dsds</font>',true);
                        vditor.insertValue('<span style="color:red">dsds</span>',false);
                        vditor.insertValue('<span style="color:red">dsds</span>',true);

```

插入html文本，编辑器中只有文字，html标签都过滤掉了

这个函数是不支持html文本的吗 求解答

**Comment by ihewro** [comment]
#428

**Comment by ihewro** [comment]
今天升级到3.8.1 版本后，发现此问题又出现了

**Comment by Vanessa219** [comment]
应该是 @88250 改了底层的解析规则造成的

**Comment by 88250** [comment]
@ihewro 目前 font 标签仅会提取其中的文本。如果需要单独插入 HTML 的话估计要新开特性提议后再考虑，感谢反馈。

**Comment by z-950** [comment]
插入html的hack。
``` js
editor.insertValue(`&lt;embed src="${url}" width="100%" height="750px"&gt;`);
```

**Comment by u19900101** [comment]
> 

求问大佬，按照您的方式能成功插入，但是插入这个`<img src="http://lpgogo.top/a4.jpg" alt="a4.jpg" style="zoom:50%;" />`后，显示为灰色代码，必须按回车键才能渲染img标签，请问有什么解决办法吗？
![image](https://user-images.githubusercontent.com/38379042/143148807-44e9cecd-1b8f-4c64-b985-945f3493ed2f.png)
