### ISSUE TITLE
不支持toc目录语法吗？

### ISSUE THREAD

**Issue by linyinian** [Vanessa219/vditor#72]
不支持toc目录语法吗？希望能够支持
![image](https://user-images.githubusercontent.com/39898791/72313027-f2031680-36c4-11ea-9380-96b203175a91.png)
![image](https://user-images.githubusercontent.com/39898791/72313042-034c2300-36c5-11ea-88a8-587fca19e2d6.png)

**Comment by 88250** [comment]
Markdown 的 ToC 语法目前尚未形成标准或者一致的通用用法，所以暂不支持。另外 Solo 大部分皮肤都已经自动处理目录了。
