### ISSUE TITLE
是否可以开启代码块折叠的功能？

### ISSUE THREAD

**Issue by cuijianzhe** [Vanessa219/vditor#727]
### 你在什么场景下需要该功能？
代码太长怎么办？影响阅读·体验怎么办？代码块折叠你值得拥有……
 Atlassian Confluence 文章编辑有这个功能，感觉挺好的哦！
![image](https://user-images.githubusercontent.com/48144475/91012302-754ff780-e618-11ea-8a6a-1a32f8d98a12.png)
![image](https://user-images.githubusercontent.com/48144475/91012362-8ef13f00-e618-11ea-9e3f-df1f142d232b.png)

**Comment by Vanessa219** [comment]
代码块渲染的时候会和 https://stackoverflow.com/ 一样最多占用屏幕高度-40px
