### ISSUE TITLE
井号后输入空格就渲染标题

### ISSUE THREAD

**Issue by HaujetZhao** [Vanessa219/vditor#729]
![Screenshot_2020-08-26-11-37-35-300_com tencent mobileqq](https://user-images.githubusercontent.com/19181833/91252742-c08d1600-e790-11ea-8c0f-fce1cc06243a.jpg)

**Comment by vCloudSail** [comment]
这么久了还没优化呢？

**Comment by Vanessa219** [comment]
这个在思源笔记里面更新了， Vditor 还没有时间弄，抱歉。

**Comment by luoluoqixi** [comment]
这个现在有办法实现吗 >_>
