### ISSUE TITLE
编辑器初始化后，希望可以改变 options.hint.extend: IHintExtend[]

### ISSUE THREAD

**Issue by TobiasTao** [Vanessa219/vditor#733]
### 你在什么场景下需要该功能？
我在vscode中利用 `options.hint.extend: IHintExtend[]` 初步实现了文件路径自动补全：
![suport-autocomplete](https://user-images.githubusercontent.com/37654563/91640519-b9942b00-ea50-11ea-90ba-bfab5a0bb3bf.gif)
但是当vscode的文件增、删、重命名后，这个路径提示就不正确了，可以改变 options.hint.extend: IHintExtend[] 而不重新初始化vditor吗？

**Comment by Vanessa219** [comment]
路径可以在输入的时候即使获取应该就可以了吧？
```
extend: [
                    {
                        key: "((",
                        hint: (key) => {
                            // return new path
                        },
                    }]
```

**Comment by TobiasTao** [comment]
没问题了🤣，是我用法错了
