### ISSUE TITLE
支持HTML的wysiwyg模式

### ISSUE THREAD

**Issue by ElderJames** [Vanessa219/vditor#737]
### 你在什么场景下需要该功能？

客户如果是需要用在传统内容网站，使用者也是传统编辑岗位，那么只用markdown可能不能满足对文本样式的需求。
还比如邮件模板等，一些诸如居中、图片尺寸调整、元素背景颜色等需要内嵌样式和attribute。

### 描述可能的解决方案

提供简单的html样式编辑功能，默认是markdown，当编辑后变成html标签

### 其他信息

类似：https://github.com/syfxlin/xkeditor

**Comment by jakekwak** [comment]
FYI https://github.com/88250/lute/issues/84#issuecomment-675172835

**Comment by 88250** [comment]
暂时不考了。
