### ISSUE TITLE
anchor 中移除 `.`

### ISSUE THREAD

**Issue by luoyunchong** [Vanessa219/vditor#74]
作者您好！
使用vue的单页面
```
<div id="preview" class="preview" style="width:100% !important" />

import Vditor from "vditor/dist/method.min";
Vditor.preview(document.getElementById("preview"), this.model.content, {
          anchor: true
 });
```
当h标签中的特殊字符。比如现这个 **.NET-Core3.1** 中的 **.**,a标签的id有特殊字符，无法导航锚点，希望作者对这个生成的id进行特殊字符处理

https://github.com/Vanessa219/vditor/blob/master/src/ts/markdown/anchorRender.ts

![image](https://user-images.githubusercontent.com/18613266/72331139-a6fff800-36f2-11ea-8ef2-2f00627071ff.png)

**Comment by Vanessa219** [comment]
我这里无法重现，可以告知一下浏览器么？或者将 https://github.com/Vanessa219/vditor/blob/master/demo/static-preview.html 页面下载后修改标题，看一下是否可以重现。
![image](https://user-images.githubusercontent.com/970828/72352975-379ffd80-371e-11ea-8321-903263fe1dcd.png)

**Comment by luoyunchong** [comment]
我知道原因了。
我用的是vue vue-router,定位锚点是通过 vue router中的配置，router.push或router.replace导航路由，而不是通过href。会出现锚点问题。
```
const scrollBehavior = function (to, from, savedPosition) {
  if (to.hash) {
    return {
      selector: to.hash,
      offset: {
        y: 100
      }
    }
  }
}
```
这是他报的错。
![image](https://user-images.githubusercontent.com/18613266/72508914-7dc1a200-3881-11ea-9c25-553c2aa9b819.png)
内部调用的是这个方法,document.querySelector(shouldScroll.selector);
selector为#vditorAnchor-.NET-Core3.1,存在.这个字符。
![image](https://user-images.githubusercontent.com/18613266/72509038-b5304e80-3881-11ea-930d-37ac4d394cd8.png)

**Comment by hectorwill** [comment]
> 作者您好！
> 使用vue的单页面
> 
> ```
> <div id="preview" class="preview" style="width:100% !important" />
> 
> import Vditor from "vditor/dist/method.min";
> Vditor.preview(document.getElementById("preview"), this.model.content, {
>           anchor: true
>  });
> ```
> 
> 当h标签中的特殊字符。比如现这个 **.NET-Core3.1** 中的 **.**,a标签的id有特殊字符，无法导航锚点，希望作者对这个生成的id进行特殊字符处理
> 
> https://github.com/Vanessa219/vditor/blob/master/src/ts/markdown/anchorRender.ts
> 
> ![image](https://user-images.githubusercontent.com/18613266/72331139-a6fff800-36f2-11ea-8ef2-2f00627071ff.png)

大神，你这个在vue中怎么弄的呢，我怎么在vue cli中怎么都没弄好。

**Comment by luoyunchong** [comment]
@hectorwill  最新的代码已经修复这个问题了.vue router 有二种路由模式，如果mode是默认的hash，就通过  router.replace({ path: `/post/${articleId}#${id}` });来导航，
```
new Router({
   scrollBehavior
})
```

```
const scrollBehavior = function (to, from, savedPosition) {
  if (to.hash) {
    return {
      selector: to.hash,
      offset: {
        y: 100
      }
    }
  }
}
```


如果mode是history ,就是通过href 链接直接导航。

**Comment by hectorwill** [comment]
> @hectorwill 最新的代码已经修复这个问题了.vue router 有二种路由模式，如果mode是默认的hash，就通过 router.replace({ path: `/post/${articleId}#${id}` });来导航，
> 
> ```
> new Router({
>    scrollBehavior
> })
> ```
> 
> ```
> const scrollBehavior = function (to, from, savedPosition) {
>   if (to.hash) {
>     return {
>       selector: to.hash,
>       offset: {
>         y: 100
>       }
>     }
>   }
> }
> ```
> 
> 如果mode是history ,就是通过href 链接直接导航。

好哒。
