### ISSUE TITLE
分屏编辑预览模式代码块粘贴首行缩进消失

### ISSUE THREAD

**Issue by thisdaydayde** [Vanessa219/vditor#745]
请选择你遇到问题时使用的编辑模式：
* `sv` 分屏编辑预览模式

### 描述问题

分屏编辑模式下，将带有缩进（整体有tab）的代码片段复制进来时，缩进就乱掉了

### 截屏或录像
原本在vscode中的代码：
![image](https://user-images.githubusercontent.com/6762068/92321580-b35c0b00-f05d-11ea-822d-0bda608896df.png)
整个复制（连同缩进）粘贴到编辑器中后缩进异常：
![image](https://user-images.githubusercontent.com/6762068/92321690-8bb97280-f05e-11ea-8eda-f574d704313e.png)

另外，所见在所得模式理上面的代码粘贴后缩进正常，但是如果切换为分屏模式的话，则缩进也会乱

**Comment by Vanessa219** [comment]
复制前可以先把代码块缩进到顶层再进行复制
![image](https://user-images.githubusercontent.com/970828/92324048-71889000-f070-11ea-8cfe-1a7622cd9bca.png)

**Comment by thisdaydayde** [comment]
可是如果想要代码保持缩进呢？

**Comment by thisdaydayde** [comment]
> 复制前可以先把代码块缩进到顶层再进行复制
> ![image](https://user-images.githubusercontent.com/970828/92324048-71889000-f070-11ea-8cfe-1a7622cd9bca.png)

可是如果想要代码保持缩进呢？

**Comment by Vanessa219** [comment]
缩进是可以保持的，不会移除原有缩进，只是拷贝的时候需要注意第一个缩进有没有被拷贝进来

**Comment by thisdaydayde** [comment]
> 缩进是可以保持的，不会移除原有缩进，只是拷贝的时候需要注意第一个缩进有没有被拷贝进来

所有缩进都复制了的，这个问题在所见所得模式和即时模式都是没问题的，只是分屏下有问题

**Comment by Vanessa219** [comment]
看上去是只有第一个缩进没有复制进来
![image](https://user-images.githubusercontent.com/970828/92340829-58bebf80-f0ee-11ea-87fb-8f0c32807ac1.png)

**Comment by thisdaydayde** [comment]
> 看上去是只有第一个缩进没有复制进来
> ![image](https://user-images.githubusercontent.com/970828/92340829-58bebf80-f0ee-11ea-87fb-8f0c32807ac1.png)
我把操作录屏了：
![Untitled](https://user-images.githubusercontent.com/6762068/92349313-481b4300-f108-11ea-84f6-30898b77e85d.gif)

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/1319
