### ISSUE TITLE
代码片段都没了

### ISSUE THREAD

**Issue by thisdaydayde** [Vanessa219/vditor#746]
### 编辑模式

请选择你遇到问题时使用的编辑模式（把正常情况模式删掉）：

* `wysiwyg` 所见即所得模式

一篇文章，持续写了两天了，期间保存、再编辑若干次，今天再次编辑，发现代码段都空了，markdown的标记还在，但里面的代码都没有了，看起来就像这样：
```javascript
```
暂时没找到重现方式，找到后我会补充进来

**Comment by Vanessa219** [comment]
是打开就没有，还是进行了什么操作？

**Comment by thisdaydayde** [comment]
> 是打开就没有，还是进行了什么操作？

打后写了一段时间发现的，不确定是不是刚打开就没了的，我继续留意，争取重现

**Comment by Vanessa219** [comment]
有劳了

**Comment by thisdaydayde** [comment]
> 有劳了

重现方式：在最新的solo博客系统后台编辑一篇有代码块的文章，通过vditor预览，然后在不关闭预览的情况下直接提交发布，再次打开编辑代码就没了：

![Untitled](https://user-images.githubusercontent.com/6762068/92435527-2fc52a00-f1d5-11ea-9619-a571d7521515.gif)
