### ISSUE TITLE
firefox 代码块中 enter 键换行问题

### ISSUE THREAD

**Issue by thisdaydayde** [Vanessa219/vditor#751]
### 编辑模式

* `ir` 即时渲染模式

### 描述问题
从IDE中粘贴过来的代码，想继续修改，enter换行后虽然出现了新行，但光标却没有移到下一行，这时只能手动将光标定位到下行起始处，再用tab缩进时发现缩进太多和上一行代码对不齐，具体见下面的动图：
![Untitled](https://user-images.githubusercontent.com/6762068/92430439-6300bc80-f1c7-11ea-8e7a-77214d89b950.gif)

**Comment by Vanessa219** [comment]
换行的问题我无法重现，
缩进需要统一在  https://github.com/Vanessa219/vditor/issues/110 中处理

**Comment by thisdaydayde** [comment]
> 换行的问题我无法重现，
> 缩进需要统一在 #110 中处理

环境：macOS Catalina Version 10.15.6 + Firefox Browser 80.0.1 (64 bit)
打开这个[示例网址](https://b3log.org/vditor/demo/sweet-two.html)，在vidtor里，写js代码，我录屏里是粘贴代码，其实不用，直接写就行了，每写一行，只要enter换行，就会发现光标没有移到下一新行，得再回车一下才行，导致的结果如下图可以看出就是多了很多空行：


![Untitled](https://user-images.githubusercontent.com/6762068/92694925-4f498780-f37a-11ea-824c-25ab58af7b3f.gif)

**Comment by Vanessa219** [comment]
可以重现了，这个 firefox 上的 bug，稍后修复
