### ISSUE TITLE
希望使用 css 完成 outline 的缩进

### ISSUE THREAD

**Issue by Elypha** [Vanessa219/vditor#754]
### 你在什么场景下需要该功能？

作为typecho文章的渲染

### 描述可能的解决方案

最近刚改用 vditor 进行渲染，发现 vditor 生成的 outline 是使用不同数量的`&emsp;`完成 h1~h6 的缩进的。

目前遇到的问题是对 outline 文字进行选中操作时，前面的空格字符似乎也是可选中的。

希望可以改用/增加一种使用 css 的方法完成缩进，类似这样（不会写 ts…见谅）

https://github.com/Vanessa219/vditor/blob/master/src/ts/markdown/outlineRender.ts#L23

```typescript
...
            item.id = lastId + "_" + index;
            tocHTML += `<div data-id="${item.id}" class="vditor-outline__item vditor-outline_heading${headingNo}">${text}</div>`;
        }
...
```

增加一个 class，然后在 css 里分别对 `.vditor-outline_heading${headingNo}` 设置类似 padding-left 这样。

目前想到这个方法，感觉用 css 实现的话可能扩展性也更好一点？想了解一下这个功能是否有改善的可能性。感谢！

**Comment by Vanessa219** [comment]
后期会进行优化的。

**Comment by Vanessa219** [comment]
合并到 https://github.com/Vanessa219/vditor/issues/479 中一起修改
