### ISSUE TITLE
脑图渲染优化

### ISSUE THREAD

**Issue by 88250** [Vanessa219/vditor#767]
![image](https://user-images.githubusercontent.com/873584/93752964-fd361b00-fc31-11ea-8fae-c52f0847d016.png)

现在的渲染不够好看，需要改进。

**Comment by ShenQingchuan** [comment]
希望能为不熟悉该类扩展 Markdown 语法的用户提供一个内建可视化的脑图增删改查编辑栏。

**Comment by 88250** [comment]
暂时不考虑了。
