### ISSUE TITLE
建议添加snippet功能

### ISSUE THREAD

**Issue by Tonjar** [Vanessa219/vditor#771]
### 你在什么场景下需要该功能？

1. 记录一些随想的时候需要添加一段时间。
2. 画图时添加一些固定的结构性的代码

### 描述可能的解决方案

片段（snippet）

即，通过快捷键插入一段预设的代码或者文字。

可参考[vnote文档：片段](https://tamlok.github.io/vnote/zh_cn/#!docs/%E7%94%A8%E6%88%B7/%E7%89%87%E6%AE%B5.md) ；[vnote文档:幻词](https://tamlok.github.io/vnote/zh_cn/#!docs/%E7%94%A8%E6%88%B7/%E5%B9%BB%E8%AF%8D.md) 

### 描述你认为的候选方案

暂无

### 其他信息

无

**Comment by Vanessa219** [comment]
提错项目了，我挪到思源笔记中
