### ISSUE TITLE
输入时自动填充了一堆乱七八糟的东西

### ISSUE THREAD

**Issue by ttangao** [Vanessa219/vditor#772]
**请先看[《提问的智慧》](https://ld246.com/article/1536377163156)**，并尝试到[链滴](https://ld246.com)搜寻资料解决问题。

----

### 编辑模式

请选择你遇到问题时使用的编辑模式（把正常情况模式删掉）：

* `ir` 即时渲染模式

### 描述问题

输入的时候文版框自动给我填充了一堆东西

````````markdown
d
````````

### 期待的结果

输入啥就是啥

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。
![image](https://user-images.githubusercontent.com/49038271/94365233-a92fa880-0101-11eb-92b3-68a738c20814.png)

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by Vanessa219** [comment]
看一下是否样式没加载

**Comment by Vanessa219** [comment]
看没有反馈，我先关闭了。
