### ISSUE TITLE
时间线timeline语法实现

### ISSUE THREAD

**Issue by Jonnyan404** [Vanessa219/vditor#775]
### 你在什么场景下需要该功能？

1. 版本更新记录
2. 说明文档更新
3. 日志/心情记录
4. 任何需要以时间作为标志的记录

### 描述可能的解决方案

\```timeline
\# 标题
内容
\```

### 效果图:

![image](https://user-images.githubusercontent.com/20352705/95643850-7fed2000-0ae4-11eb-924a-3626ca9c31f1.png)

**Comment by Vanessa219** [comment]
这个语法是通用的还是？

**Comment by Jonnyan404** [comment]
> 这个语法是通用的还是？

属于扩展语法,不通用.

**Comment by Vanessa219** [comment]
图中的编辑器是？

**Comment by Jonnyan404** [comment]
> 图中的编辑器是？

是 editormd

**Comment by 88250** [comment]
不考虑了，感谢提议。

**Comment by KING754** [comment]
> editormd

editormd好像不支持这个呀？还是第三方的？
