### ISSUE TITLE
利用preview.transform做渲染回调仅在`sv`模式预览区生效

### ISSUE THREAD

**Issue by Trojan0523** [Vanessa219/vditor#778]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题
我们在preview.transform中成功将传入的HTMLString经过处理，转换为适配flowchart语法并且在预览区进行展示，但是当我们切换到其他两个模式的时候并没有成功的展示出来，我想请问下您是不是transform回调的方法没有经过其他两种模式的渲染流程导致没有返回解析的字符串呢,或者是是否有其他的api可以供使用？

````````markdown

```flow
st=>start: Start|past:>http://www.google.com[blank]
e=>end: End|future:>http://www.google.com
op1=>operation: My Operation|past
op2=>operation: Stuff|current
sub1=>subroutine: My Subroutine|invalid
cond=>condition: Yes
or No?|approved:>http://www.google.com
c2=>condition: Good idea|rejected
io=>inputoutput: catch something...|future

st->op1(right)->cond
cond(yes, right)->c2
cond(no)->sub1(left)->op1
c2(yes)->io->e
c2(no)->op2->e
```

````````

### 期待的结果

期待得到我们经过处理的字符串能在三个模式中都能使用

### 截屏或录像

这是`sv`模式经过处理返回的渲染预览
![image](https://user-images.githubusercontent.com/44562268/95813638-e5dae100-0d4a-11eb-890a-2fcba21d18f3.png)
`ir`模式下渲染失败
![image](https://user-images.githubusercontent.com/44562268/95822022-b2ee1880-0d5d-11eb-8baf-08e8745bd896.png)

**Comment by Vanessa219** [comment]
transform 只能处理预览结果。其他两个模式是输入模式。

flowchart 升级版本即可内置支持。

**Comment by Trojan0523** [comment]
好的，半小时前在官网上看到了新版本的更新，谢谢您
