### ISSUE TITLE
列表换行处理问题

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#78]
![orderedlist1](https://user-images.githubusercontent.com/15811943/72547863-17be2600-3853-11ea-892f-366f367275e4.gif)
任务列表
![orderedlist](https://user-images.githubusercontent.com/15811943/72547533-71722080-3852-11ea-97b0-a48b278c2bfd.gif)

**Comment by 88250** [comment]
We should have fixed it, and if you find other issues, please tell us, thanks.
