### ISSUE TITLE
上传图片时无法有效禁止编辑器输入

### ISSUE THREAD

**Issue by eeezae** [Vanessa219/vditor#782]
----

### 描述问题

期望：上传图片时使用`disabled`方法禁止编辑器输入操作，然后图片上传完成后使用`enable`方法允许编辑器输入。
结果：编辑器`disabled`之后无法插入已经上传的图片地址，只能在编辑器`enable`状态时插入。

### 期待的结果

如何在上传图片时禁用编辑器，并图片上传成功后插入编辑器enable编辑器？

**Comment by Vanessa219** [comment]
目前上传就是禁止编辑的。可查看 https://github.com/Vanessa219/vditor/issues/506

**Comment by eeezae** [comment]
> 目前上传就是禁止编辑的。可查看 #506

我目前用的`handler`上传，似乎并没有触发编辑器禁止的事件。

**Comment by Vanessa219** [comment]
可以调用以下 disabled

**Comment by eeezae** [comment]
谢谢，是我调用的位置有问题，应该在上传成功后插入前enable的，提了一个糟糕😰的issue不好意思
