### ISSUE TITLE
初次进入有内容的编辑器使用撤销会清空所有

### ISSUE THREAD

**Issue by eeezae** [Vanessa219/vditor#783]
----

### 编辑模式

请选择你遇到问题时使用的编辑模式（把正常情况模式删掉）：

* `ir` 即时渲染模式

### 描述问题

点击一篇文章后，使用`setValue`将文章内容读到编辑器中进行编辑，此时可以使用`撤销按钮`撤销或者使用`撤销快捷键`，使用之后会清空整个编辑器。

### 期待的结果

希望编辑器的初始set的内容不要撤销。

### 其他信息

P.s. 在编辑器内容`setValue`之后，进行输入或者粘贴操作，然后撤销，撤销的不是上一步输入的内容，同样也是编辑器内全部内容，用户体验非常不友好。

**Comment by Vanessa219** [comment]
每次 setValue 都会进行记录，你可以初始化的时候传入默认值，这样再 setValue 就会使用默认值。

**Comment by eeezae** [comment]
就是说如果多篇文章点击切换，每切换一篇文章就要初始化一次编辑器是吗？

**Comment by Vanessa219** [comment]
可以用 `setValue("", true)`，但是这个好像有点问题，等我看看

**Comment by eeezae** [comment]
> 可以用 `setValue("", true)`，但是这个好像有点问题，等我看看

我试用了一下满足我这边的需求了，还没有发现问题o(*￣︶￣*)o

**Comment by Vanessa219** [comment]
好的，有问题再提 issue
