### ISSUE TITLE
markdown 编写时会出现html干扰代码块

### ISSUE THREAD

**Issue by demajie** [Vanessa219/vditor#788]
### 编辑模式
所有模式

### 描述问题

我用 `vditor.setValue()` 将之前写好的文本填充到 编辑框中时，会出现html样式干扰，**默认聚焦会聚焦到html代码块中**

### 期待的结果

能不能把那个html代码块取消

### 截屏或录像
截屏地址:https://upload-images.jianshu.io/upload_images/23501476-db60e90ee4f00e47.png

**Comment by Vanessa219** [comment]
图片地址看不到
