### ISSUE TITLE
Wikilinks

### ISSUE THREAD

**Issue by Pablo2m** [Vanessa219/vditor#789]
I am adapting Vditor to an existing project that uses links similar to wiki, that is, within the markdown text they appear as [[numerical_id]], is there an option to use this type of links?

Example

"Lorem [[000004]]"

File content [[000004]]:
"#Ipsum

pain sit amet, adipiscing consectetur"

Rendering

"Lorem Ipsum" 

Thanks

**Comment by 88250** [comment]
Vditor just an editor rather than an application, it can not read another file content for rendering. But I think the syntax element `[[wiklink]]` should be implemented.
