### ISSUE TITLE
用户体验，上传图片后直接显示图片，图片链接影响你漂亮的界面

### ISSUE THREAD

**Issue by thinkido** [Vanessa219/vditor#790]
### 编辑模式
模式：即时渲染，

### 描述问题
建议：用户体验，上传图片后直接显示图片，不用显示编辑模式。
一般用户不会想去编辑图片的名称，如果要编辑用户，可以一次性再点击图片编辑。

### 期待的结果
直接显示图片，不显示网址。在上传图片后，直接添加一个换行即可。

### 截屏或录像
[vditor上传图片后的用户体验](https://reccloud.cn/u/ocv3zfu?action=client-auto-login)

**Comment by Vanessa219** [comment]
这个是模式是参考 Typora 设计的，你可以使用 wysiwyg 模式

**Comment by thinkido** [comment]
我需要用这种模式。我自己要如何实现？大概在哪里修改逻辑。我先去看文档了

**Comment by thinkido** [comment]
试了几种方式都不行。
success(editor,msg){
              if( !msg ) return console.error({"msg": "网络异常", code: 1000 }) 
              let { errno , errmsg , data } = JSON.parse(msg) ;
              if( errno ) return console.error('upload error:' , errmsg)
              let md = self.editorMD.getValue() ;
              // self.editorMD.setValue( `${md}\n![](${ data })\n` ) ;
              self.editorMD.insertValue( `\r\n![](${ data })\t` ) ;
              var e = jQuery.Event("keydown");//模拟一个键盘事件
              e.keyCode = 13;//keyCode=13是回车
              $('#editor .vditor pre').trigger(e);
              // self.editorMD.focus()
            },

**Comment by thinkido** [comment]
vditor.insertValue( `\n![](http:xxx.jpg)\n` ) ; 没有渲染。
模式：即时渲染，

**Comment by Vanessa219** [comment]
抱歉，这样没办法实现。

**Comment by thinkido** [comment]
> 抱歉，这样没办法实现。

vditor.insertValue( \n![](http:xxx.jpg)\t) ; 就直显示了图片，\t触发了渲染。多增加了一个空格。先解决眼前问题。

**Comment by Vanessa219** [comment]
光标移上去还是会显示地址的，没有办法隐藏
