### ISSUE TITLE
vditor.insertValue( `\n![](http:xxx.jpg)\n` ) ; 没有渲染。 模式：即时渲染，

### ISSUE THREAD

**Issue by thinkido** [Vanessa219/vditor#792]
**请先看[《提问的智慧》](https://ld246.com/article/1536377163156)**，并尝试到[链滴](https://ld246.com)搜寻资料解决问题。

----

### 编辑模式
 模式：即时渲染，

### 描述问题
success(editor,msg){
          if( !msg ) return console.error({"msg": "网络异常", code: 1000 })  ,self.editorMD.tip("网络异常");
              let { errno , errmsg , data } = JSON.parse(msg) ;
              if( errno ) return console.error('upload error:' , errmsg) , self.editorMD.tip( errmsg ) ;
              let md = self.editorMD.getValue() ;
              // self.editorMD.setValue( `${md}\n![](${ data })\n` ) ;
              self.editorMD.insertValue( `\n![](${ data })\n` ) ;
              self.editorMD.tip('上传成功')
              // self.editorMD.focus()
},

### 期待的结果
自定义代码，上传图片后只写显示图片效果，不显示图片网址。

**Comment by Vanessa219** [comment]
ir 模式无法实现

**Comment by u19900101** [comment]
> ir 模式无法实现

现在可以了，但是当加入的字符串为 <img src="http://lpgogo.top/a4.jpg" style="zoom:50%;" /> 时，则还是无法污染，请问大佬这个解决了吗？

**Comment by Vanessa219** [comment]
可以的
