### ISSUE TITLE
编辑器在页面顶部时，鼠标移动到编辑器按钮时，tip显示在屏幕外，看不到

### ISSUE THREAD

**Issue by thinkido** [Vanessa219/vditor#793]
### 编辑模式
模式：所有

### 描述问题
编辑器在页面顶部时，鼠标移动到编辑器按钮时，tip显示在屏幕外，看不到
![image](https://user-images.githubusercontent.com/5847958/96953331-62c44280-1523-11eb-9ba6-8fb8dbe271ff.png)

**Comment by Vanessa219** [comment]
可参看文档自己定义 tooltip 的显示位置
