### ISSUE TITLE
列表效果完全看不见。容易出现编辑器的css被污染，导致界面显示效果差

### ISSUE THREAD

**Issue by thinkido** [Vanessa219/vditor#794]
### 编辑模式
模式：所有

### 描述问题
整合到代码中发现css很容易被污染，列表效果完全看不见。

请提供其他附加信息帮助我们诊断问题。
![image](https://user-images.githubusercontent.com/5847958/96954272-9ef8a280-1525-11eb-90f7-c6559be2a0d6.png)

**Comment by Vanessa219** [comment]
请不要使用全局的 CSS 来污染 Vditor 的渲染就可以了。
