### ISSUE TITLE
粗体字会变成符号。模式：即时渲染，含视频演示。

### ISSUE THREAD

**Issue by thinkido** [Vanessa219/vditor#797]
### 编辑模式
模式：即时渲染

### 描述问题
**粗体字会变成符号。**现在显示正常，一旦后面有文字全部变成符号，并没有粗体字效果。在当前的编辑器中，后面持续输入文字都只会显示符号，不会显示粗体字。

### 截屏或录像
![image](https://user-images.githubusercontent.com/5847958/97097678-6801c880-16ae-11eb-8566-84377442f4a3.png)

[vditor粗体字只显示符号，视频](https://reccloud.cn/u/vx1i7so?action=client-auto-login)

**Comment by Vanessa219** [comment]
https://ld246.com/article/1597581380183
