### ISSUE TITLE
vditor 是否可以动态显示和隐藏大纲 outline

### ISSUE THREAD

**Issue by thinkido** [Vanessa219/vditor#799]
### 你在什么场景下需要该功能？
屏幕resize之类的情况下使用，自动显示隐藏大纲。

### 描述可能的解决方案
希望可以提供一个方法控制显示隐藏大纲。

```
const vditor = new Vditor(id, {options...})
vidtor.outline(true); 打开大纲，
vidtor.outline(false); 隐藏大纲。
```
尝试了jquery控制显示隐藏大纲， $('.vditor-outline').show() hide()，
可以控制大纲显示或隐藏。但是无法控制大纲配套的列表渲染和顶部菜单。

**Comment by Vanessa219** [comment]
大纲的顶部菜单是？

**Comment by Vanessa219** [comment]
https://ld246.com/article/1603625074828
