### ISSUE TITLE
第一次 ctrl+z 无法设置光标

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#80]
add `t`, ctrl+z, moved top
ctrl+shift+s, ctrl+z(I expect only ctrl+shift+s but deleted some text also)
![ctrlz](https://user-images.githubusercontent.com/15811943/72626951-46023b00-3911-11ea-99e6-3362f29f66ee.gif)

**Comment by 88250** [comment]
Could you give some details on `Ctrl+Shift+s` mean?

**Comment by jakekwak** [comment]
![40](https://user-images.githubusercontent.com/15811943/72775445-f901bb80-3bd3-11ea-9a1b-bf7d64d00be0.PNG)
