### ISSUE TITLE
粘贴后需滚动到粘贴内容的末尾

### ISSUE THREAD

**Issue by thinkido** [Vanessa219/vditor#802]
### 编辑模式
模式：即时渲染，和所见即所得。分屏没测试。

### 描述问题
粘贴内容显示到屏幕外没有自己滚动，导致看不到新添加的内容。体验很少，到知道使用app作为高效输入工具基本难以使用。

### 期待的结果
粘贴内容后可以自己滚动到显示区，

### 截屏或录像

[粘贴的内容超过一屏不会自己滚动](https://reccloud.cn/u/8r06e3t?action=client-auto-login)

**Comment by thinkido** [comment]
手机版中的语音输入法就难以使用了。

**Comment by thinkido** [comment]
粘贴后需滚动到粘贴内容的末尾，在版本v3.6.2中没有看到这个功能效果呢？
https://cdn.jsdelivr.net/npm/vditor@3.6.2/dist/index.min.js

**Comment by Vanessa219** [comment]
https://ld246.com/article/1605410523094/comment/1605419034827#comments
