### ISSUE TITLE
请求增加"全屏"按钮的回调函数

### ISSUE THREAD

**Issue by KaloSora** [Vanessa219/vditor#804]
### 你在什么场景下需要该功能？

初始化的编辑器
<img width="963" alt="image" src="https://user-images.githubusercontent.com/35422660/97665627-e7303b80-1ab6-11eb-8deb-4031b72aed28.png">

在使用编辑器的时候，点击全屏按钮，会导致原有的布局被打乱。（如下图）
<img width="978" alt="image" src="https://user-images.githubusercontent.com/35422660/97665403-4c376180-1ab6-11eb-8aca-eca41b040901.png">

1.顶部的导航栏遮蔽了toolbar
2.左侧的菜单在全屏时依然显示，由于业务需要希望能够在点击全屏的时候自动折叠，以达到最好的输入效果

### 描述可能的解决方案

希望能够新增全屏的回调函数，或者通过一个状态标示判断是否进入了全屏

**Comment by Vanessa219** [comment]
设置 xxx 为高于遮住 vditor 元素的 z-index 值
```
.vditor--fullscreen {
    z-index: xxx
}
```
