### ISSUE TITLE
列表多行内容无法添加缩进vditor，现在最多只能一行。有录像

### ISSUE THREAD

**Issue by thinkido** [Vanessa219/vditor#805]
### 编辑模式
即时和可视，分屏为测试。

### 描述问题
列表多行内容无法添加缩进vditor，现在最多只能一行

### 期待的结果
可以给多行列表缩进。

### 截屏或录像
视频：
[列表多行内容无法添加缩进vditor](https://reccloud.cn/u/cetm0ny?action=client-auto-login)

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/761 中已修复
