### ISSUE TITLE
弹窗选择后没有回调吗？

### ISSUE THREAD

**Issue by WadeQi** [Vanessa219/vditor#809]
interface IHintExtend {
    key: string;

    hint?(value: string): Array<{
        html: string;
        value: string;
    }>;
}

**Comment by Vanessa219** [comment]
```
hint: {
              
                extend: [
                    {
                        key: "((",
                        hint: hintCallback,
                    }]
}
```

**Comment by WadeQi** [comment]
![image](https://user-images.githubusercontent.com/44157692/98783539-b516c600-2434-11eb-9fee-8e5b2cd6e521.png)
是截图中选择后的回调，这个区域监听keydown也监听不到
另外选择后插入可以高亮颜色吗，谢谢回答

**Comment by WadeQi** [comment]
> ```
> hint: {
>               
>                 extend: [
>                     {
>                         key: "((",
>                         hint: hintCallback,
>                     }]
> }
> ```

![image](https://user-images.githubusercontent.com/44157692/98783539-b516c600-2434-11eb-9fee-8e5b2cd6e521.png)
是截图中选择后的回调，这个区域监听keydown也监听不到
另外选择后插入可以高亮颜色吗，谢谢回答

**Comment by Vanessa219** [comment]
* 这个没有回调，已经在内部封装好了，只需要把值写到 `value`  中就回车或选中就可以回填到界面上
* 不可以高亮

**Comment by WadeQi** [comment]
> * 这个没有回调，已经在内部封装好了，只需要把值写到 `value`  中就回车或选中就可以回填到界面上
> * 不可以高亮

好的，谢谢，希望能扩展一下，这样没办法通知到用户

**Comment by Vanessa219** [comment]
在提交的时候通知会更好一点，因为用户可能在编辑的过程中会删除。

**Comment by GrumpyOnes** [comment]
+1 使用@user时，下拉list选中某人，建议增加回调传出选中的人的信息。某些场景会用到。

**Comment by Vanessa219** [comment]
可以说一下场景么？ @gr

**Comment by HengCC** [comment]
> 在提交的时候通知会更好一点，因为用户可能在编辑的过程中会删除。我没有删除 at 用户的回调，你无法进行通知后撤销通知

能问下如何在提交的时候知道 @ 了哪些呢?   感觉这块得做成行内块级渲染才能知道 @了哪些. 但是这似乎不符合编辑器的能力范围.

**Comment by Vanessa219** [comment]
这只能 getValue 后，自己进行解析了。
