### ISSUE TITLE
所见及所得模式渲染和value不一致

### ISSUE THREAD

**Issue by yulei745** [Vanessa219/vditor#811]
### 问题

所见及所得模式，getValue()值 与 渲染有差异

````````markdown
getValue() 得到的 markdown 原文

1. asdjfklasdf
2. asdgasdg
3. asdgsdagsdg
4. asdgsadg

* asdgasdgasdg
* asdgasdg
* [ ] asdgasdgasdg

* [ ] asdg
* [ ] asd
* [ ] ga
* [ ] sdg


````````

![image](https://user-images.githubusercontent.com/1788251/98911615-d7c1e100-24ff-11eb-96fd-c9ef1d1516ee.png)

**Comment by Vanessa219** [comment]
请更新到最新版后再试一下

![image](https://user-images.githubusercontent.com/970828/98939285-297c6280-2524-11eb-84fd-fad5f734a921.png)
