### ISSUE TITLE
将图片错误渲染为 base64 代码块了

### ISSUE THREAD

**Issue by PBK-B** [Vanessa219/vditor#813]
### 编辑模式

请选择你遇到问题时使用的编辑模式（把正常情况模式删掉）：

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

复制粘贴有道云笔记中的图片，渲染出来的图片资源格式错误！将图片错误渲染为 base64 代码块了。

### 期待的结果

将粘贴进来的图片进入正常的处理及渲染逻辑

### 截屏或录像

![1122xxxttt.png](http://cos.haxibiao.com/images/5faf8c48daabf.png)

### 其他信息

有道云笔记相关链接：https://note.youdao.com/ynoteshare1/index.html?id=6488664c8920990d3c20e434090481a3&type=note

**Comment by Vanessa219** [comment]
有道云在复制的时候会将图片转换为 base64 存在剪切板中

**Comment by PBK-B** [comment]
> 有道云在复制的时候会将图片转换为 base64 存在剪切板中

之后会考虑提供一个粘贴事件处理接口让开发者自己处理这样的奇葩设计嘛？

**Comment by Vanessa219** [comment]
这个粘贴下来应该 lute 解析的问题。https://github.com/88250/lute/issues/109
