### ISSUE TITLE
所见即所得的模式下，字体颜色的改变

### ISSUE THREAD

**Issue by Freedomhxb** [Vanessa219/vditor#816]
### 你在什么场景下需要该功能？
运营需要写文章的时候，他们不太会用markdown的语法

所见即所得的模式下，字体颜色的改变，字体背景的颜色的改变
### 其他信息
作者你写的很棒！如果你暂时不想实现这个功能，可不可以给我一些思路，我自己修改下源码，非常感谢。

**Comment by Vanessa219** [comment]
目前可以用 font 标签。后期做思源笔记的时候会一起进行修改。
