### ISSUE TITLE
How to?: Style at match and setting cursor to wherever I want

### ISSUE THREAD

**Issue by flyingatm** [Vanessa219/vditor#817]
Hello sir,

I have two question.

1) How Can I declare new markdown-ish elements?

Example: **hey** -> makes it bold. So basically it adds <strong> tags where ** ** condition matches.

I wanna make a custom data-marker like this: (lot:some text). And I wanna style it like this
-> `(lot:<span class="any-style">some text</span>)`  (or I'm all open to another way to style my child text if there is another one. I does'nt have to be a span tag. I just wanna make my "some text" colorful.)

2) How can I set Cursor?

Example: I created a custom button that inserts (lot:) on click. But I wanna focus the cursor to (lot:*HERE*).

I hope I was be clear. Thank you!

**Comment by Vanessa219** [comment]
Hi,

1. There are no related regulations in the commonmark specification, so you need to deal with it yourself. In the near future we will implement font color functions
2. use `vditor.insertValue/setValue` method

**Comment by flyingatm** [comment]
Hi,
Wow that was fast lol, tank you for your quick reply.

For the 2st question: I guess you miss understood me. I'm already using insertValue/Update value but I wanna **set cursor** to a spesific ch of the line. --> exp. (lot:) after I update/InsertValue this text I wanna move cursor to the (lot:HERE).

**Comment by Vanessa219** [comment]
Sorry, we don’t have this method, maybe you can use `Range` and 
```
const selection = window.getSelection();
selection.removeAllRanges();
selection.addRange(range);
```
