### ISSUE TITLE
iOS下，浏览器里无法点击上传图片

### ISSUE THREAD

**Issue by huangxiaomenggit** [Vanessa219/vditor#818]
iOS下，浏览器里无法点击上传图片，点击之后没任何反应。安卓下操作一切正常。

**Comment by Vanessa219** [comment]
麻烦你登录 https://ld246.com/guide/markdown 这个看一下是否能上传

**Comment by huangxiaomenggit** [comment]
这个可以，放到uni-app框架里就不行，是有冲突吗？

**Comment by huangxiaomenggit** [comment]
另外，咱们编辑器能增加居中、文字颜色的功能吗？

**Comment by Vanessa219** [comment]
后期会增加颜色功能，你要开启 app 的上传权限

**Comment by huangxiaomenggit** [comment]
> 后期会增加颜色功能，你要开启 app 的上传权限

会增加内容居中能力吗？

**Comment by Vanessa219** [comment]
这个还没有考虑哦

**Comment by GitHubForQiuKai** [comment]
> 麻烦你登录 https://ld246.com/guide/markdown 这个看一下是否能上传

我这边在ios的浏览器下也无法点击上次

**Comment by Vanessa219** [comment]
> > 麻烦你登录 https://ld246.com/guide/markdown 这个看一下是否能上传
> 
> 我这边在ios的浏览器下也无法点击上次

上传需要登录一下
