### ISSUE TITLE
Problem with custom button suffix-prefix

### ISSUE THREAD

**Issue by flyingatm** [Vanessa219/vditor#821]
Hello, this code above:

```
new Vditor('vditor', {
  toolbar: [
    { 
      name: "sponsor", // problem is here
      tipPosition: "s",
      prefix: "(lat:",
      suffix: ")",
      icon: "...",
    }],
});
```
causing this error on console:

`Uncaught TypeError: n.click is not a function
    at HTMLButtonElement.<anonymous>`

But when I change it's **name** like this:

```
new Vditor('vditor', {
  toolbar: [
    { 
      name: "bold", // problem is here
      tipPosition: "s",
      prefix: "(lat:",
      suffix: ")",
      icon: "...",
    }],
});
```
Button working as expected and inserting text into editor like this-> (lat:)

I guess there is a bug with the name label.

**Comment by Vanessa219** [comment]
"sponsor" is a custom button, so it must implement `click`, see: 
https://ld246.com/article/1549638745630#options-toolbar

**Comment by flyingatm** [comment]
> "sponsor" is a custom button, so it must implement `click`, see:
> https://ld246.com/article/1549638745630#options-toolbar

Yes I know that but I need prefix and suffix to focus my cursor after (:lat and before ).

**Comment by Vanessa219** [comment]
You can choose one of "bold", "italic", "strike", "line", "quotation mark", "list", "sorted list", "check", "code", "inline code", " Link", "Form" and set it.
