### ISSUE TITLE
大佬，切换主题好像有问题，背景颜色不对

### ISSUE THREAD

**Issue by lululuting** [Vanessa219/vditor#829]
![image](https://user-images.githubusercontent.com/26959652/100237603-1c229780-2f6a-11eb-9608-7283ceac00d9.png)

切换黑色主题样式不对
![image](https://user-images.githubusercontent.com/26959652/100237989-9fdc8400-2f6a-11eb-839c-bc6b47fb3c51.png)

**Comment by Vanessa219** [comment]
这个是内容主题，我们内容主题没有区分暗合和明亮模式，因此需要自己对编辑器主题进行切换。
