### ISSUE TITLE
优化最末行的输入体验

### ISSUE THREAD

**Issue by TankNee** [Vanessa219/vditor#831]
### 你在什么场景下需要该功能？
当我编辑到页面中能够显示的最后一行的时候，此时如果直接继续输入那么光标就会一直在最后一样，紧贴着编辑器的边界，虽然还是可用的，但我觉得Typora的实现方式可能更加优雅

### 描述最优的解决方案 
在Typora中，如果输入到最后一行，那么会自动的在下面填充margin。例如下图
![image](https://user-images.githubusercontent.com/43956168/100316547-b4b22980-2ff5-11eb-9729-e39ee6ca2c38.png)
当我在最后一行输入文字时，typora就会自动向下延展一部分
![image](https://user-images.githubusercontent.com/43956168/100316593-cf849e00-2ff5-11eb-9807-3e1b0c0c66f7.png)
![image](https://user-images.githubusercontent.com/43956168/100316633-e0cdaa80-2ff5-11eb-85ba-84e897735c04.png)

### 其他信息
我不确定这一部分的优化是由vditor来做还是由我自己在实际应用中来调整，我发现Typora的实现是在点击最末行时自动向下延展一部分，但是此时滚动条并没有滚动，当我开始在最后一行填充字符时，滚动行自动滚动到底部，非常流畅。
如果有好的实现方法能否分享一下呢？

**Comment by Vanessa219** [comment]
开启 `options.typewriterMode`
