### ISSUE TITLE
自动补全特殊符号

### ISSUE THREAD

**Issue by cweijan** [Vanessa219/vditor#833]
@Vanessa219 老哥我把你这个集成进vscode了, https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-office, 你可以试下, 现在相比typora有两个问题
1. 不能自动补全括号, 单引号, 双引号, $等等
2. 编辑大文件的情况下卡顿, 而typora勉强能冲

这两个问题解决后就能完美替代typora了

**Comment by Vanessa219** [comment]
大文本发我看看。自动补全可以用输入法自带的功能

**Comment by cweijan** [comment]
啊这, 我看你这头像还以为是个阿宅, 万万没想到, 哈哈.

**Comment by cweijan** [comment]
发到你邮件了, 估计是因为latex渲染

**Comment by cweijan** [comment]
自动补全还是得这个库提供好一点, 我用的win10自带输入法是没有这个功能的

**Comment by Vanessa219** [comment]
数学公式引擎用的是 mathjax 么？

**Comment by cweijan** [comment]
- 当公式多的情况下, 两种引擎都很卡, 数学公式的渲染能做缓存吗?
- 尝试了一下, 发现符号的自动补全还是比较简单, 下面的代码就可以实现, 相比typora还有三项要完成:
  - 当光标右侧是符号时, 此时不补全, 而是将光标右移
  - 当按下删除键时, 符号内如果内容为空, 则一对一起删了
  - 当有选中内容时, 可将选中的内容用符号包起来
```js
const keys = ["'", '"', "$"];
window.onkeydown = e => {
  if (keys.indexOf(e.key) == -1) {
    return;
  }
  const selectText = document.getSelection().toString();
  if (selectText != "") { return; }

  document.execCommand('insertText', false, e.key);
  document.getSelection().modify('move', 'left', 'character')
}
```

**Comment by Vanessa219** [comment]
* 这个思源笔记里面已经优化过了，稍后迁移过来
* typora
  * 自动挪过去了还要在手动挪回来会比较麻烦吧？
  * 这个可以考虑下
  * 这个可以使用快捷键
