### ISSUE TITLE
历史记录添加时间间隔配置

### ISSUE THREAD

**Issue by ihewro** [Vanessa219/vditor#837]
### 编辑模式

all
* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

比如，输入
````````markdown
这是一段文字，我要撤销了
````````

这个时候cmd+z 撤销，会撤销整段文字，

如果在GitHub编辑框里面输入，是一个字或者两个字一起的撤销了。

### 期待的结果

希望撤销的过程能够更短一点，和一般的编辑器效果一致

**Comment by Vanessa219** [comment]
考虑性能问题，目前是按键间隔 800 毫秒进行一次记录。我把这个弄成配置项，这样就可以根据各自情况进行配置了。
