### ISSUE TITLE
流程图支持 Flow 扩展语法

### ISSUE THREAD

**Issue by scvoet** [Vanessa219/vditor#838]
现在已经实现了 mermaid - flowchart 语法，而不支持另一流程图 flow 语法。

### 相关链接

- [flowchart.js](https://github.com/adrai/flowchart.js)

**Comment by Vanessa219** [comment]
已经支持
![image](https://user-images.githubusercontent.com/970828/101481220-c8637580-398f-11eb-9c10-2e6bb972b44d.png)

**Comment by scvoet** [comment]
啊，是我思源没开代码块预览。（
