### ISSUE TITLE
大纲无法展示

### ISSUE THREAD

**Issue by Hansanshi** [Vanessa219/vditor#842]
### 编辑模式

* `ir` 即时渲染模式

### 描述问题

我将vditor的版本升级至3.7.1后发现大纲不再展示，始终为空，无论如何输入，见下图

### 截屏或录像

![](https://gitee.com/hansanshi/image/raw/master/20201212181136.png)

### 版本信息

* 版本：3.7.1
* 操作系统：macOS
* 浏览器：Chrome&FireFox

**Comment by Hansanshi** [comment]
发现图片没展示 附上链接 
https://gitee.com/hansanshi/image/raw/master/20201212181136.png

**Comment by Vanessa219** [comment]
* 文档修改
  * 3.7.0
    * `preview` 静态方法添加 `mode` 配置
    * 大纲 DOM 结构和 class 变更

请检查一下样式，本地运行无法重现。
![image](https://user-images.githubusercontent.com/970828/101982360-57350280-3cae-11eb-9a8d-e0ff5296de4f.png)

**Comment by Hansanshi** [comment]
@Vanessa219 我测试了下

用一个空白vue项目（[github地址](https://github.com/Hansanshi/vditor-demo)）做了测试，没有设置任何样式

唯一自己写的代码如下

```html
<template>
  <div id="app">
        <div  id="vditor"  class="vditor"/>
  </div>
</template>
<script>
import Vditor from 'vditor'
import 'vditor/dist/index.css'

export default {
  data () {
    return {
      vditor : null
    }
  },
  mounted() {
    this.vditor = new Vditor('vditor');
  }
}
</script>
```
vditor@3.7.0还是不能展示大纲，切换版本到3.6.6就可以，麻烦帮忙看看是哪里有问题，我看这个问题也有其他人[反馈](https://ld246.com/article/1607266549935)。

**Comment by umi-soft** [comment]
我也有同样的问题，3.7.1，大纲无法渲染

**Comment by Vanessa219** [comment]
3.7.2 中会进行修复，如果着急的话可以设置 `options.preview.markdow.toc = true`
