### ISSUE TITLE
图片缩放的拓展语法

### ISSUE THREAD

**Issue by HaujetZhao** [Vanessa219/vditor#844]
### 你在什么场景下需要该功能？

从高分屏截图，粘贴，在 html 上就会图片很大，需要缩小才能正常显示。

### 描述最优的解决方案 

通过 `![image | 200x400, 40%](path/to/image.png)` 的语法控制图片大小。

其实就是抄 Discourse 的作业：https://meta.discourse.org/t/quick-image-resizing-and-markdown-image-dimensions/66812

**Comment by Vanessa219** [comment]
D 说要用 Kramdown.....

**Comment by HaujetZhao** [comment]
如果语法解析问题不大的话，希望能兼容这种语法。因为 kramdown 是写在 id 属性中的，对用户不显示，而图片名字在即时渲染模式是显示的，这种语法可以提供在编辑器中通过手动输入调整图片大小的方式。

**Comment by Vanessa219** [comment]
嗯，目前重心还是在思源。

**Comment by u19900101** [comment]
> 嗯，目前重心还是在思源。

这个功能暂时还没实现吧

**Comment by Vanessa219** [comment]
> > 嗯，目前重心还是在思源。
> 
> 这个功能暂时还没实现吧

思源实现了

**Comment by HaujetZhao** [comment]
👍

**Comment by 88250** [comment]
暂时不考虑了，这个语法差异有点大，兼容性堪忧。
