### ISSUE TITLE
文字环绕的导出效果

### ISSUE THREAD

**Issue by HaujetZhao** [Vanessa219/vditor#845]
### 你在什么场景下需要该功能？

行内有大图时。

### 描述最优的解决方案 

当在行内有大图时，它的显示效果就是这样：
![image](https://user-images.githubusercontent.com/19181833/102208900-fa825380-3f0a-11eb-870d-88fa9e308b64.png)

图片右边浪费了很大一片空间，看着效果也不好。

而在百科中，会有这样的效果：
![image](https://user-images.githubusercontent.com/19181833/102208986-1be33f80-3f0b-11eb-8616-4757639391dd.png)

所以希望可以做一个解析，如果在段首、末尾有大图，做成图片左置或右置的文字在旁边的效果。这个效果应该并不适合实时预览，不期待在编辑时就有。不过，如果导出时可以优化成这样的排版，观感会好很多。

好像是个没什么卵用的大投入、小产出的 feature……

**Comment by Vanessa219** [comment]
好吧，大后期可以考虑

**Comment by Vanessa219** [comment]
这个 md 有点难，放在有扩展 md 的思源笔记里面吧
