### ISSUE TITLE
在HTML块中使用markdown语法问题

### ISSUE THREAD

**Issue by dyxcloud** [Vanessa219/vditor#846]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式

### 描述问题

想要实现这种可折叠的markdown块的效果

> <details>
> <summary>code</summary>
>
> ## title
> a simple line
> ```java
> System.out.println("hello world");
> ```
> </details>

源码如下:

````````markdown
<details>
<summary>code</summary>

### title

a simple line

​```java
System.out.println("hello world");
​```

</details>
````````

编辑器在分屏模式下可以正常解析展示, 但是在所见即所得模式和IR模式下解析不正常

### 截屏或录像

分屏模式下的效果:

![Snipaste_2020-12-16_22-48-54](https://user-images.githubusercontent.com/31332427/102364160-1fe98d00-3ff1-11eb-8df8-77ba7fe1f313.png)

IR模式下的效果:

![Snipaste_2020-12-16_22-49-22](https://user-images.githubusercontent.com/31332427/102364176-2415aa80-3ff1-11eb-8a3b-9e7d07ae381e.png)

### 版本信息

使用官网demo( https://ld246.com/guide/markdown ) 进行的测试

**Comment by Vanessa219** [comment]
这是正常解析，标签的解析会被隔断。最后导出和存库都是正常的，请放心使用。
