### ISSUE TITLE
即时渲染状态下 Firefox 删除线出错

### ISSUE THREAD

**Issue by Hansanshi** [Vanessa219/vditor#847]
### 编辑模式

* `ir` 即时渲染模式

### 描述问题

即时渲染状态点击`删除线`图标，预期输出是

```
~~~~
```

但实际输出是
```
~~~~

~~~~
```
其他两种编辑模式没有出现这个问题

### 版本信息

* 版本：3.7.2
* 操作系统：macOS Big Sur
* 浏览器：FireFox&Chrome

**Comment by Vanessa219** [comment]
参见附件，无法进行重现。如果能稳定重现，请再次打开该 issue。谢谢。
[QQ20201217-231301-HD.mp4.zip](https://github.com/Vanessa219/vditor/files/5710338/QQ20201217-231301-HD.mp4.zip)

**Comment by Hansanshi** [comment]
@Vanessa219 

可以稳定复现（我在macOS和windows上都测试，使用的是官方demo网址，其中windows上为全新安装），只是刚好你这种操作在Chrome浏览器上是没问题。

在FireFox浏览器和Chrome浏览器上表现是不同，后者需要切换编辑方式才能复现。


参见[附件](https://github.com/Hansanshi/vditor-demo/blob/master/src/assets/%E5%88%A0%E9%99%A4%E7%BA%BF%E9%97%AE%E9%A2%98.zip?raw=true)

**Comment by Vanessa219** [comment]
Firefox 还是无法重现。

CommonMark 中 `~~~~` 为代码块

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/commit/6bc8c07f369aebe3348cbc225f3c1a8fa0715221
