### ISSUE TITLE
即时渲染模式下FireFox浏览器光标问题

### ISSUE THREAD

**Issue by Hansanshi** [Vanessa219/vditor#848]
### 编辑模式

* `ir` 即时渲染模式

### 描述问题

工具栏的`加粗`、`斜体`、`删除线`和`行内代码`均有这个问题，举个例子（例子中`|`代表光标的位置）：

Chrome浏览器下点击`斜体`图标，会插入两个星号，并且光标自动移动到两个星号之间，形如`*|*`

而FireFox浏览器则是光标在两个星号后边，形如`**|`

FireFox浏览器其他两种模式是正常的。

### 版本信息

* 版本：3.7.2
* 操作系统：macOS
* 浏览器：FireFox

**Comment by Vanessa219** [comment]
参见附件，无法进行重现。如果能稳定重现，请再次打开该 issue。谢谢。

[QQ20201217-231547-HD.mp4.zip](https://github.com/Vanessa219/vditor/files/5710333/QQ20201217-231547-HD.mp4.zip)

**Comment by Hansanshi** [comment]
@Vanessa219 

可以稳定复现，在macOS和windows上的FireFox浏览器都可以复现，不知道你这个为啥是正常的

参见[附件](https://github.com/Hansanshi/vditor-demo/blob/master/src/assets/FireFox%E6%B5%8F%E8%A7%88%E5%99%A8%E5%85%89%E6%A0%87%E9%97%AE%E9%A2%98.zip?raw=true)。

**Comment by Vanessa219** [comment]
还是不行，你是做了什么特殊操作么？
[QQ20201218-165143-HD.mp4.zip](https://github.com/Vanessa219/vditor/files/5714641/QQ20201218-165143-HD.mp4.zip)

**Comment by Vanessa219** [comment]
哦，可以重现了，Firefox 版本问题。
