### ISSUE TITLE
固定工具栏模式下点击全屏打开后导航栏位置异常

### ISSUE THREAD

**Issue by m-rouin** [Vanessa219/vditor#849]
可解决办法,给全屏模式加个焦点到内容区就不会了.....

**Comment by Vanessa219** [comment]
正常的，如还能重现，请给出截图和说明。

![image](https://user-images.githubusercontent.com/970828/102563715-de520280-4114-11eb-8df0-f301dda80d08.png)

**Comment by m-rouin** [comment]
> 正常的，如还能重现，请给出截图和说明。
> 
> ![图片](https://user-images.githubusercontent.com/970828/102563715-de520280-4114-11eb-8df0-f301dda80d08.png)


![QQ截图20201218035851](https://user-images.githubusercontent.com/56850839/102565054-599bc000-40e5-11eb-9795-e8ea3bb9cab1.png)

**Comment by Vanessa219** [comment]
麻烦把这个页面发我看一下，我本地环境是好的。

**Comment by m-rouin** [comment]
> 麻烦把这个页面发我看一下，我本地环境是好的。

http://blog.rouin.com/

**Comment by m-rouin** [comment]
![QQ截图20201218040909](https://user-images.githubusercontent.com/56850839/102565763-c8c5e400-40e6-11eb-8869-752d5156abe0.png)
代码这边,是这些

> 麻烦把这个页面发我看一下，我本地环境是好的。

**Comment by m-rouin** [comment]
> 麻烦把这个页面发我看一下，我本地环境是好的。

刚又测试了下发现 , 点了全屏再点内容区,再滚动也出问题了,还是不能固定....
![QQ截图20201218041252](https://user-images.githubusercontent.com/56850839/102566033-4e499400-40e7-11eb-86a6-623e7fdcab73.png)

**Comment by Vanessa219** [comment]
报错了
![image](https://user-images.githubusercontent.com/970828/102566170-e95b6180-4119-11eb-8e25-2ee9a9280cd9.png)

**Comment by m-rouin** [comment]
> 报错了
> ![图片](https://user-images.githubusercontent.com/970828/102566170-e95b6180-4119-11eb-8e25-2ee9a9280cd9.png)

什么情况,我手机都打得开?? ,  我试试关闭调试模式

**Comment by Vanessa219** [comment]
你看一下 https://b3log.org/vditor/demo/advanced-toolbar.html 这个页面是否能重现

**Comment by m-rouin** [comment]
![QQ截图20201218042305](https://user-images.githubusercontent.com/56850839/102566712-bba9f480-40e8-11eb-849e-aad47200a14b.png)


> 你看一下https://b3log.org/vditor/demo/advanced-toolbar.html这个页面是否能重现

是的一样的

**Comment by m-rouin** [comment]
然后又发现一个问题,工具的层级数不够,会被其他东西覆盖了,文档编辑器可千万不能被覆盖...
![QQ截图20201218042423](https://user-images.githubusercontent.com/56850839/102566812-eac06600-40e8-11eb-9da4-6ef8b4ac084b.png)

**Comment by Vanessa219** [comment]
层级 https://github.com/Vanessa219/vditor/issues/855

工具栏那个问题，你用的是什么浏览器

**Comment by m-rouin** [comment]
> 层级[＃855](https://github.com/Vanessa219/vditor/issues/855)
> 
> 工具栏那个问题，你用的是什么浏览器

![QQ截图20201218043114](https://user-images.githubusercontent.com/56850839/102567296-e47eb980-40e9-11eb-8056-cb2d7f19e90e.png)

用的是谷歌浏览器

**Comment by m-rouin** [comment]
又发现一个问题: 当没内容可以滚动的时候 应该禁用滑动条 , 否则就会变成关闭全屏后,页面跑到了页面底部........

此次测试用的是QQ浏览器

![QQ截图20201218043504](https://user-images.githubusercontent.com/56850839/102567548-67a00f80-40ea-11eb-80cf-474f5aa3658e.png)
![QQ截图20201218043701](https://user-images.githubusercontent.com/56850839/102567676-ad5cd800-40ea-11eb-8cba-63823dec8517.png)
![QQ截图20201218043747](https://user-images.githubusercontent.com/56850839/102567723-c82f4c80-40ea-11eb-834c-ddaa0df41b15.png)
![QQ截图20201218043840](https://user-images.githubusercontent.com/56850839/102567777-e7c67500-40ea-11eb-93ab-d7117c74960b.png)

**Comment by Vanessa219** [comment]
收到
