### ISSUE TITLE
ctrl-z & 重写缩进

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#85]
enter at any place , after ctrl-z,
![1](https://user-images.githubusercontent.com/15811943/72949866-2aeb5d00-3d4f-11ea-8f3f-c12f1e73baa9.PNG)

**Comment by jakekwak** [comment]
Still problem at ordered.
and ⌘+z key is not working well at mac. 
![20](https://user-images.githubusercontent.com/15811943/73130321-a8b3a080-3fbb-11ea-9872-7cec85069963.PNG)

**Comment by jakekwak** [comment]
click, enter, ctrl+shift+e(tab was worked but not now), ctrl+shift+s, ctrl+z, ctrl+z... 
![unordered](https://user-images.githubusercontent.com/15811943/73130405-5d01f680-3fbd-11ea-8c3f-a6bbe7a70ef9.gif)

**Comment by jakekwak** [comment]
still not working ctrl-z at new version 2.1.6.  any testing guy before release?

**Comment by 88250** [comment]
🤦‍♂️ Sorry for that, we will check again.

**Comment by Vanessa219** [comment]
https://github.com/88250/lute/issues/15

**Comment by jakekwak** [comment]
@88250 I can test this. but when same problem occurred, I can not trust the fixed code.

**Comment by jakekwak** [comment]
ctrl-z is not working at windows 10(I think Mac is ok)

**Comment by Vanessa219** [comment]
@jakekwak Sorry，forget fix order list. Mac has also problem.
