### ISSUE TITLE
求更多官方html方面教程

### ISSUE THREAD

**Issue by m-rouin** [Vanessa219/vditor#852]
对于html教程官方中的手册案例代码
如下:
=========================================================
HTML script
在 HTML 中插入 CSS 和 JavaScript，可参考 demo

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vditor/dist/index.css" />
<script src="https://cdn.jsdelivr.net/npm/vditor/dist/index.min.js" defer></script>
=========================================================

其中引用脚本的这个实在太不友好了.......
这是 defer 延迟加载.... 对于新手来说 没有任何提示直接这样给人代码他们就直接复制了 , 导致在写js脚本的时候 经常出问题找不到问题在哪
........
建议再加一条 立即加载.....
如:
=========================================================
HTML script
在 HTML 中插入 CSS 和 JavaScript，可参考 demo

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vditor/dist/index.css" />
//<script src="https://cdn.jsdelivr.net/npm/vditor/dist/index.min.js" defer></script>//延迟加载模式 , 可能导致script无法立即响应部分操作
<script src="https://cdn.jsdelivr.net/npm/vditor/dist/index.min.js"></script>//立即模式
=========================================================

**Comment by Vanessa219** [comment]
已修正。

**Comment by m-rouin** [comment]
> 已修正。

![Uploading QQ截图20201218045726.png…]()
