### ISSUE TITLE
html模式下无法重设vditor.options.xxx , 而非完全初始化

### ISSUE THREAD

**Issue by m-rouin** [Vanessa219/vditor#853]
求重设......试过一大堆办法了,完全无法重设部分功能

**Comment by Vanessa219** [comment]
某些属性有 set 方法，如果还需要其他设置，请将使用场景和需要的方法进行逐一说明。

**Comment by m-rouin** [comment]
![QQ截图20201218045118](https://user-images.githubusercontent.com/56850839/102568702-acc54100-40ec-11eb-85d2-86fd8ca85d1d.png)


> 某些属性有 set 方法，如果还需要其他设置，请将使用场景和需要的方法进行逐一说明。

**Comment by m-rouin** [comment]
![QQ截图20201218045301](https://user-images.githubusercontent.com/56850839/102568798-ea29ce80-40ec-11eb-9d8b-a5e6511b748e.png)


> 某些属性有 set 方法，如果还需要其他设置，请将使用场景和需要的方法进行逐一说明。

**Comment by Vanessa219** [comment]
工具栏需要在初始化的时候进行设定

**Comment by m-rouin** [comment]
> 工具栏需要在初始化的时候进行设定

不太理解 , 能否添加相关说明在: https://ld246.com/article/1549638745630#HTML-script

**Comment by Vanessa219** [comment]
可参见 https://b3log.org/vditor/demo/advanced-toolbar.html
