### ISSUE TITLE
禁止编辑模式下全屏后透明度异常

### ISSUE THREAD

**Issue by m-rouin** [Vanessa219/vditor#857]
![QQ截图20201218053233](https://user-images.githubusercontent.com/56850839/102571578-7a1e4700-40f2-11eb-865a-8d8ac82bfa49.png)
![QQ截图20201218053346](https://user-images.githubusercontent.com/56850839/102571622-9a4e0600-40f2-11eb-9830-30e0b3eb8d8d.png)

**Comment by Vanessa219** [comment]
可能和 https://github.com/Vanessa219/vditor/issues/855 有关，等发布后麻烦再观察一下
