### ISSUE TITLE
添加必要教程-初始化时应注意重置工具栏时必须在初始化的最前面-否则导致功能异常

### ISSUE THREAD

**Issue by m-rouin** [Vanessa219/vditor#859]
![QQ截图20201218060941](https://user-images.githubusercontent.com/56850839/102573685-a092b100-40f7-11eb-9491-c00bfbba959f.png)

**Comment by Vanessa219** [comment]
不会有这种问题。这个对象传给我是一起解析的。

**Comment by m-rouin** [comment]
好吧,那可能是我搞错了,哪里搞错了还一直以为是这里的问题

> 不会有这种问题。这个对象传给我是一起解析的。
