### ISSUE TITLE
[suggestion]When change heading

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#86]
When change heading4 to heading3.
Current:
1. select heading
2. Click H for removing heading
3. Click H again for selecting another heading

suggestion
1. Select heading
2. showing toolbar menu when Click H (below picture)

![5](https://user-images.githubusercontent.com/15811943/72954017-98ea5100-3d5c-11ea-8be8-585a08d737b7.png)

**Comment by Vanessa219** [comment]
use `ctrl+` or `ctrl-`
