### ISSUE TITLE
自动检测文本为代码时应重设为```bash 或 直接不以代码块显示

### ISSUE THREAD

**Issue by m-rouin** [Vanessa219/vditor#860]
![QQ截图20201218061840](https://user-images.githubusercontent.com/56850839/102574200-e308bd80-40f8-11eb-9ee8-550d5742144b.png)

**Comment by m-rouin** [comment]
![Uploading QQ截图20201218062056.png…]()

**Comment by Vanessa219** [comment]
@88250 lute 解析问题，请查看

**Comment by Vanessa219** [comment]
https://github.com/88250/lute/issues/109
