### ISSUE TITLE
ir模式代码块异常

### ISSUE THREAD

**Issue by m-rouin** [Vanessa219/vditor#861]
![QQ截图20201218062933](https://user-images.githubusercontent.com/56850839/102574826-65de4800-40fa-11eb-95ca-7a6beebc586d.png)
![QQ截图20201218063020](https://user-images.githubusercontent.com/56850839/102574875-81e1e980-40fa-11eb-9a70-ce782e524130.png)

**Comment by Vanessa219** [comment]
应该是正常的，请查看一下 md 内容
![image](https://user-images.githubusercontent.com/970828/102581428-84186800-413b-11eb-890e-059c0ae9dd75.png)
