### ISSUE TITLE
请求提供解锁定预览模式方法 , 可用于直接帖子等网站无法编辑别人的文章

### ISSUE THREAD

**Issue by m-rouin** [Vanessa219/vditor#862]
![QQ截图20201218154523](https://user-images.githubusercontent.com/56850839/102621309-0b6bd880-4148-11eb-907c-08a2b89705f1.png)

**Comment by m-rouin** [comment]
![Uploading QQ截图20201218155214.png…]()

**Comment by Vanessa219** [comment]
数据库里面存 MD ，然后界面用 https://ld246.com/article/1549638745630#static-methods

**Comment by m-rouin** [comment]
> 数据库里面存 MD ，然后界面用 https://ld246.com/article/1549638745630#static-methods

知道这个,就是希望能完全用工具来体现编辑模式下的预览渲染效果 , 因为这样看 有大纲 起来太舒服了,并且还能更改工具的高度啥的

已找到你们官方示例 , 真的不够好
https://b3log.org/vditor/demo/preview-config.html

,希望支持直接用工具的预览效果设计

**Comment by Vanessa219** [comment]
是否提供一个 setToolbarConfig 就可以满足了？

可以使用这个：
![image](https://user-images.githubusercontent.com/970828/102684296-3c184480-4212-11eb-88bd-9a7db21d3f39.png)

**Comment by m-rouin** [comment]
> 是否提供一个 setToolbarConfig 就可以满足了？
> 
> 可以使用这个：
> ![image](https://user-images.githubusercontent.com/970828/102684296-3c184480-4212-11eb-88bd-9a7db21d3f39.png)

具体怎么说好呢 , 第1: 虽然工具确实是有预览模式可用,但过于复杂不是么 , 因为编辑模式已经非常强大了 , 没必要弄多余的 , 按代码来说 , 只要在编辑器模式下加个方法显示效果是最好的 , 但既然是新的预览模式 , 人们肯定就是不希望被编辑了 , 所以会使用禁止编辑的功能 , 此功能就 = 预览模式 , 那么如果这样 , 工具栏上的预览模式就没用了 , 那么method.min.js 也等于没用了

所以这样其实更好 , 可以专心开发 , 让编辑器模式变得完美
例如: gitee的预览就超级好

vditor完全可以直接弄一个函数 , 随时切换模式 , 而不是通过工具栏什么的

再有,这样切换回编辑模式也非常方便 , 无法就是把消失的工具栏弄回来 , 然后内容区允许编辑了...

![QQ截图20201219222436](https://user-images.githubusercontent.com/56850839/102698829-fc208400-4248-11eb-8061-712adaf32816.png)

**Comment by m-rouin** [comment]
还有 , 希望废弃掉ir模式  wysiwyg 模式算是vditor做的最完美的把 , ir模式越来越偏向于 wysiwyg 那么此功能就是个噱头 
几乎没用 , 与其复杂化代码架构 不如简介实用来的实在 , 再有与其在ir上搞噱头 , 实际不如简单来个youtube视频做个简易 使用教程
来的实在 .

**Comment by m-rouin** [comment]
再有 实际上大家喜欢这个vditor无法就是看上了 wysiwyg 模式 , 要不然像这个教程这么不齐全的真的难用 ,  我是一个c#过来的
在unity上做游戏 , 我能独立做游戏代码框架的 , 可能我学习能力是差了 , 但说时候 , vditor是打包成min.js 加上教程不齐全 , 去网上怎么搜都搜不到几个......整整花了一周时间 , 今天才没办法彻底去学webpack看到了源码.....实在是多余的东西太多了.....

**Comment by m-rouin** [comment]
> 是否提供一个setToolbarConfig就可以满足了？
> 
> 可以使用这个：
> ![图片](https://user-images.githubusercontent.com/970828/102684296-3c184480-4212-11eb-88bd-9a7db21d3f39.png)

再有就是还是上一张图那样 , 预览就是预览 没那些奇怪的东西 , 如果未来有人开发差不多同样的工具 , 支持拖拽md到网上直接编辑 , 或者谷歌浏览器谁做了个插件 直接拖拽md到浏览器上直接预览 , 再或者 提供下载md的附加需要提供预览方式 , 是不是编辑模式和预览模式用的工具ui几乎差不多 , 肯定是了 ,
 那么区别在哪 ? 允许编辑和不允许编辑呗 ... 
那么允许编辑需要啥? 当然需要工具栏了...
不允许编辑需要啥? 只需要大纲和全屏模式....那么工具栏是否要废弃掉 , 当然要废弃掉了 ,

**Comment by m-rouin** [comment]
所以最终结论是:
1: 废弃ir 模式 , 专心开发 wysiwyg 模式 , 把各种兼容性问题 , 响应式布局搞清楚
2: 扩展性自由性加强 , 尽可能提供所有一切感觉20%概率以上会被人需求手动调整的方法
3: 废弃原有工具栏上的预览模式 , 整合并更加合理化 wysiwyg 模式
4: 为工具初始化添加一个非工具栏按钮的方法 , 
vditor.setMode(mode:string){
if(mode === "editor" ){}
else if(mode === "browse" ){}
else{throw new Error("模式错误");}

**Comment by m-rouin** [comment]
以上個人建議。。。
若有冒犯請多多包涵，畢竟開源不易，抱歉了哈

**Comment by Vanessa219** [comment]
感谢建议
