### ISSUE TITLE
昨天我才发现这个宝藏项目，罪过罪过，有一些小小的新功能请求

### ISSUE THREAD

**Issue by gztrljh** [Vanessa219/vditor#863]
### 你在什么场景下需要该功能？

请问，鼠标移动到编辑区的时候，可以把ctrl+S 就是那个弹出保存网页那个禁用掉么？写文章的时候写着写着，我就习惯性的给自己来个ctrl+s

### 描述最优的解决方案 

csdn 的那个md编辑器禁用了ctrl+s

### 你在什么场景下需要该功能？

还有就是那个自适应，大屏幕下正常的
![image](https://user-images.githubusercontent.com/68222167/102682093-af658a80-4201-11eb-87fe-f4ab009f7a34.png)

然后我浏览器开启仿真，好像就不行了，就会变成这样
![image](https://user-images.githubusercontent.com/68222167/102682104-cf954980-4201-11eb-87bc-c5d538bb47f7.png)

然后解决办法就是，在小屏幕下刷新一下就会变成自适应的菜单
![image](https://user-images.githubusercontent.com/68222167/102682113-edfb4500-4201-11eb-8e30-8fea99e96c58.png)

也不知道是不是bug，是否可以改成和bootstrap一样的那种响应式呢？

支持，强烈支持。

**Comment by Vanessa219** [comment]
绑定 `options.save` 方法后可组织浏览器默认事件
