### ISSUE TITLE
ir模式下有序列表，无需列表，回车光标上移问题

### ISSUE THREAD

**Issue by jiakangning** [Vanessa219/vditor#867]
**ir模式下，列表渲染时候，连着两次按enter键，光标问题**

![image](https://user-images.githubusercontent.com/34635641/102900449-3e470100-44a7-11eb-87ee-00b34fab3568.png)

**Comment by jiakangning** [comment]
![vditor02](https://user-images.githubusercontent.com/34635641/102905482-2cb52780-44ae-11eb-97f0-d41f51370ad8.gif)

在光标处点击回车无效

**Comment by jiakangning** [comment]
推测可能是由于 现有样式覆盖vditor的ul，li的样式（list-style: none;）导致的

**Comment by Vanessa219** [comment]
是的，请不要对其进行样式的修改。

第一个问题无法重现，是在dasda 后面按2次 enter么？

**Comment by Vanessa219** [comment]
我先关闭了， 可以重现的话再打开。
附件为无法重现的录屏。
[QQ20201223-114422-HD.mp4.zip](https://github.com/Vanessa219/vditor/files/5733143/QQ20201223-114422-HD.mp4.zip)

**Comment by jiakangning** [comment]
@Vanessa219 ，这个问题在我的vue项目中还是会重现，你可以把你的 ul li 的样式置为（list-style:none;）就会出现这个问题
![image](https://user-images.githubusercontent.com/34635641/102962444-d8e42600-4521-11eb-9679-f77db40e6aa6.png)
这种情况下，列表块内enter键触发的时候，光标就会出现这个问题
目前发现有三种，
  一种就是光标上移，如上描述
  一种就是光标不动，如上描述
 一种就是光标光标跳不出去列表块
![image](https://user-images.githubusercontent.com/34635641/102963262-99b6d480-4523-11eb-9def-dc1946b2c03d.png)


目前项目内使用的 样式权重高覆盖了编辑器的ul,li的样式，手动恢复编辑器样式，但是问题还是没有解决，希望能够得到解决

**Comment by Vanessa219** [comment]
你怎么恢复的？

**Comment by jiakangning** [comment]
现在只是在编辑器页面内复写样式 @Vanessa219

![image](https://user-images.githubusercontent.com/34635641/102981907-a0a20f00-4544-11eb-8190-2be41869566c.png)

**Comment by jiakangning** [comment]
> 是的，请不要对其进行样式的修改。
> 
> 第一个问题无法重现，是在dasda 后面按2次 enter么？

是的，连着两次摁enter键，光标上移到第一个li上

**Comment by Vanessa219** [comment]
你把你的 reset.css 发我，我在本地看看

**Comment by jiakangning** [comment]
// reset.css


.el-pager li, .el-pagination__editor {
    -webkit-box-sizing: border-box;
    text-align: center
}

.el-pagination .el-pager li.disabled {
    color: #c0c4cc;
    cursor: not-allowed
}

.el-pager li, .el-pager li.btn-quicknext:hover, .el-pager li.btn-quickprev:hover {
    cursor: pointer
}

.el-pagination--small .btn-next, .el-pagination--small .btn-prev, .el-pagination--small .el-pager li, .el-pagination--small .el-pager li.btn-quicknext, .el-pagination--small .el-pager li.btn-quickprev, .el-pagination--small .el-pager li:last-child {
    border-color: transparent;
    font-size: 12px;
    line-height: 22px;
    height: 22px;
    min-width: 22px
}

.el-pagination--small .more:before, .el-pagination--small li.more:before {
    line-height: 24px
}

.el-pagination.is-background .btn-next, .el-pagination.is-background .btn-prev, .el-pagination.is-background .el-pager li {
    margin: 0 5px;
    background-color: #f4f4f5;
    color: #606266;
    min-width: 30px;
    border-radius: 2px
}

.el-pagination.is-background .btn-next.disabled, .el-pagination.is-background .btn-next:disabled, .el-pagination.is-background .btn-prev.disabled, .el-pagination.is-background .btn-prev:disabled, .el-pagination.is-background .el-pager li.disabled {
    color: #c0c4cc
}

.el-pagination.is-background.el-pagination--small .btn-next, .el-pagination.is-background.el-pagination--small .btn-prev, .el-pagination.is-background.el-pagination--small .el-pager li {
    margin: 0 3px;
    min-width: 22px
}

.el-pager, .el-pager li {
    vertical-align: top;
    display: inline-block;
    margin: 0
}

.el-pager li {
    padding: 0 4px;
    background: #fff;
    font-size: 13px;
    min-width: 35.5px;
    height: 28px;
    line-height: 28px;
    box-sizing: border-box
}

.el-pager li.btn-quicknext, .el-pager li.btn-quickprev {
    line-height: 28px;
    color: #303133
}

.el-pager li.btn-quicknext.disabled, .el-pager li.btn-quickprev.disabled {
    color: #c0c4cc
}

.el-pager li.active + li {
    border-left: 0
}

.el-pager li:hover {
    color: #409eff
}

.el-pager li.active {
    color: #409eff;
    cursor: default
}

.caf-file-manager .ace-code-editor .caf-menu-popper ul {
    max-height: 500px;
    overflow-y: auto;
    min-width: 50px
}

.caf-file-manager .card-file .right-menu .menu-box > ul {
    margin: auto
}

.caf-file-manager .card-file .right-menu .menu-box ul li {
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    padding: 0 10px;
    height: 30px;
    line-height: 30px;
    cursor: pointer
}

.caf-file-manager .card-file .right-menu .menu-box ul li:hover {
    background: hsla(0, 0%, 100%, .2)
}

.caf-file-manager .card-file .right-menu .menu-box ul li span {
    display: inline-block
}

.caf-file-manager .card-file .right-menu .menu-box ul li span:first-child {
    margin-right: 5px
}

.caf-file-manager .card-file .right-menu .menu-box ul li + li {
    border-top: 1px solid #e9e9e9
}
a, div, i, input, li, p, span, ul {
    margin: 0;
    padding: 0;
    border: 0
}

i, li, ul {
    font-style: normal;
     list-style:none
}
