### ISSUE TITLE
使用工具栏中的有序和无序列表功能，选中多行只能生效一行

### ISSUE THREAD

**Issue by yuhuan101** [Vanessa219/vditor#870]
### 描述问题

在使用有序和无序列表功能时，鼠标选中多行只有第一行会生效。

### 期待的结果

希望在鼠标选中多行都可以生效，变成无序或者有序列表，不仅仅是第一行生效。

1. a
2. b
3. c

**Comment by Vanessa219** [comment]
和 https://github.com/Vanessa219/vditor/issues/798 重复了
