### ISSUE TITLE
vditor.options.upload.file 支持 await

### ISSUE THREAD

**Issue by jeefyang** [Vanessa219/vditor#872]

**Comment by Vanessa219** [comment]
可以使用 `options.upload.file` 或 `options.upload.validate` 来进行处理

**Comment by jeefyang** [comment]
但是都不是异步,很多时候读取文件都是异步的方法,希望后面可以开放异步的功能,不然修改调整代码很头疼

**Comment by Vanessa219** [comment]
不太明白要怎么异步

**Comment by jeefyang** [comment]
![image](https://user-images.githubusercontent.com/13160414/103184011-c9cdf100-48f0-11eb-8937-af1826e18182.png)
就是这样,在上传的文件前,提供一个接口处理下数据,然后再执行上传代码

**Comment by Vanessa219** [comment]
你可以在外部

**Comment by jeefyang** [comment]
感谢大佬提供支持,不胜感激

**Comment by Vanessa219** [comment]
需要再等待几个 issue 后一起发版

**Comment by poolye** [comment]
现在支持了么~这个功能主要用在，上传文件前，通过Ajax请求服务器，获取上传签名。

**Comment by poolye** [comment]
包括extraData，每次上传可能数据都不一样，里面是一些签名数据，初始化的时候配置好，后面没办法修改。 @Vanessa219

**Comment by Vanessa219** [comment]
参见 https://ld246.com/article/1549638745630#options-upload setHeaders

**Comment by poolye** [comment]
已解决，非常感谢。这里简单说一下，通过web直传阿里云等场景，可以在options.upload.file里promise请求签名，然后用vditor.vditor.options.upload.extraData赋值到formdata，开始上传。 @Vanessa219 thanks again~
