### ISSUE TITLE
graphviz，mermaid 在为空时不应出现错误提示

### ISSUE THREAD

**Issue by jiakangning** [Vanessa219/vditor#873]
* `ir` 模式下
编辑mermaid，flowchart，mindmap，graphviz，math均出错

mermaid模式：

![image](https://user-images.githubusercontent.com/34635641/103254971-85ab2100-49c2-11eb-9737-4838e00d1a71.png)

graphviz
![image](https://user-images.githubusercontent.com/34635641/103255185-534df380-49c3-11eb-828f-9f9b418f1c25.png)

### 版本信息

3.6.6

**Comment by Vanessa219** [comment]
* flowchart，mindmap 无法重现
* math 无法重新，麻烦给一下配置
* graphviz，mermaid 在语法错误的时候会提示属于正常现象，为空的话会做一下优化

**Comment by jiakangning** [comment]
关于图表配置:

```js
new Vditor('vditor', {
  mode: 'wysiwyg',
  height: window.innerHeight + 100,
  outline: true,
  debugger: true,
  typewriterMode: true,
  placeholder: 'Hello, Vditor!',
  preview: {
    markdown: {
      toc: true,
      mark: true,
      footnotes: true,
    },
    math: {
      engine: 'KaTeX',
    },
  },
  toolbarConfig: {
    pin: true,
  },
  counter: {
    enable: true,
    type: 'text',
  }
})
```

**Comment by jiakangning** [comment]
mermaid模式下这个错误是 直接跑的demo报的错误，麻烦看下，是不是版本问题导致的 @Vanessa219

**Comment by Vanessa219** [comment]
你使用分支上的最新代码再看看
