### ISSUE TITLE
大纲支持固定

### ISSUE THREAD

**Issue by Hansanshi** [Vanessa219/vditor#874]
### 你在什么场景下需要该功能？

写长文时，需要查看大纲进行位置跳转。

目前是写到下边时，就看不到大纲了，需要在滑动上去

### 描述最优的解决方案 

像工具栏一样，大纲支持固定在页面的某个位置

**Comment by Vanessa219** [comment]
先把编辑器高度设置一下顶顶

**Comment by umi-soft** [comment]
# 版本3.7.5
> 目前我遇到的问题是

**Comment by Hansanshi** [comment]
@umi-soft 

我没有碰到你这个问题，我点击是有效的，可以跳转

固定大纲作者没有支持，我这边自己加了两行
```javascript
document.querySelector('.vditor-outline__content').classList.add("vditor-toolbar--pin")
document.querySelector('.vditor-outline').classList.add("vditor-toolbar--pin")
```

高亮显示是本来就没有功能，你应当先看下[官方文档](https://ld246.com/article/1549638745630#options-outline)

**Comment by umi-soft** [comment]
> 补充 
- 我尝试切换编辑模式，点击大纲，都是无效的，并没有触发锚点
- 全屏模式下，点击大纲，也是无效，但是全屏模式下，大纲是固定的，没有随着页面内容滚动

**Comment by umi-soft** [comment]
> 补充
我对比了一下，官网的文档中的大纲html结构，发现官网大纲使用的是a标签，而我本地是span标签包裹的，不知道是不是这个原因造成锚点无效的

**Comment by Vanessa219** [comment]
官网也是 span 的
![image](https://user-images.githubusercontent.com/970828/104460324-ebb1be00-55e8-11eb-8739-85ccde052ba3.png)

**Comment by HengCC** [comment]
要固定很简单. 给你个方案. 
编辑器初始化后 触发这个代码
```
const initOutLine = () => {
    const outlineElements = document.getElementsByClassName('vditor-outline');
    console.log('outlineElements:', outlineElements);
    const outlineElement = outlineElements[0];
    outlineElement.classList.add(styles.editOutline);
  };
```

然后给editOutline设置样式如下:
```css
.editOutline {
      position: fixed;
      top: 0;
      right: 0;
      bottom: 20px;
      z-index: 2;
      overflow: auto;
    }
```

其他看着改吧
