### ISSUE TITLE
增加大纲位置配置

### ISSUE THREAD

**Issue by akaylh** [Vanessa219/vditor#875]
### 你在什么场景下需要该功能？

目前我们在左侧放置了其它的树形结构内容，如果大纲也在左侧，会显示得乱，希望以放在右侧

### 描述最优的解决方案 

可配置大纲显示的位置，在左侧或者在右侧

**Comment by 88250** [comment]
你好，请手动拖到右侧即可，正常退出后会保存布局，下次启动会恢复布局，谢谢。

**Comment by 88250** [comment]
不好意思，看错项目了……
