### ISSUE TITLE
增强字数统计功能

### ISSUE THREAD

**Issue by jxjxjhjh** [Vanessa219/vditor#876]
### 你在什么场景下需要该功能？

小说写作需要查看某个章节的字数。

### 描述最优的解决方案 

大纲条目后面显示本条目的内容字数，这个方式最好，不过我觉得实现方式上来说可能难度非常大。

### 描述候选解决方案

也可以采取比较常见的【选中内容字数】，这样可以曲线救国，手动选中本章内容查看字数，但还是第一种更方便。

### 其他信息

最好不要放在右下角，容易被输入法挡住。
需要即时更新字数，如果难度大至少不要超过3秒更新一次。

**Comment by Vanessa219** [comment]
工具栏上有字数统计，可以把小说拆成多章，全部写在一个里面可能会卡
