### ISSUE TITLE
聚焦到编辑器特定位置

### ISSUE THREAD

**Issue by lsixi** [Vanessa219/vditor#880]
### 你在什么场景下需要该功能？

1.在自定义toolbar的click中，希望弹窗定义内容，然后将内容插入到编辑器 —— 也就是编辑器失去焦点时记住焦点位置，再次聚焦时能在上次焦点位置插入内容

### 描述最优的解决方案 

弹窗时可以通过getCursorPosition()取得焦点位置，插入内容时无法使用这个焦点位置；
希望可以通过这个取到的焦点位置先设置编辑器的焦点位置，再通过insertValue在焦点处插入内容

### 其他信息

类似于focus()功能，但是带参数，比如，focusPositon(left: number, top: number)

**Comment by Vanessa219** [comment]
和 https://github.com/Vanessa219/vditor/issues/720 重复了
