### ISSUE TITLE
只读模式还能操作

### ISSUE THREAD

**Issue by chenxiaobin** [Vanessa219/vditor#881]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式

### 描述问题

设置只读模式的时候，this.vditor.disabled()

1、ir模式的时候，链接，点击过去还是能转换为md的语法
2、插入的图片，点击上去还会删除的那个悬停快捷操作

### 期待的结果

只读，就是最后的展示，不能有其他操作性的东西！而且只读模式默认不要设置透明色和禁用手势把，正常预览，不能操作就好了
### 截屏或录像

![image](https://user-images.githubusercontent.com/2148077/103517808-b0f3ab80-4ead-11eb-8a76-376a7b603b22.png)
点击百度链接之后，就变了
![image](https://user-images.githubusercontent.com/2148077/103517838-bf41c780-4ead-11eb-931e-a6ad854b3463.png)

![image](https://user-images.githubusercontent.com/2148077/103517941-e5676780-4ead-11eb-8292-47e4689c6a05.png)

**Comment by Vanessa219** [comment]
1. 这个是特性
2. 最后一个截图应该是可写模式下吧？disabled 后我这里无法点出情景菜单

只读需要有样式的区别要告知用户，如果想保持原样的话可以用更高优先级的 css 来进行样式的重置

**Comment by chenxiaobin** [comment]
最后一张截图是设置为  disabled 后的情况

**Comment by Vanessa219** [comment]
调用 disabled 的时候会隐藏红框里面的东西，我这里没法重现，麻烦给一下详细的重现步骤
