### ISSUE TITLE
MathJax的\ref无法正确渲染

### ISSUE THREAD

**Issue by TobiasTao** [Vanessa219/vditor#883]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

MathJax无法正确渲染`\ref`
![image](https://user-images.githubusercontent.com/37654563/103643304-69dde700-4f8f-11eb-8a7b-66c7ac6a2381.png)

markdown原文
````````markdown
$$
x = y + z
\tag{1} \label{1}

\ref{1}
$$

$\ref{1}$
````````

### 版本信息

https://b3log.org/vditor/demo/advanced-math.html#

**Comment by Vanessa219** [comment]
不太清楚应该是什么样，看了其他软件也是这样的。
<img width="762" alt="截屏2021-01-05 下午11 36 38" src="https://user-images.githubusercontent.com/970828/103665896-ec29d380-4fae-11eb-905f-1be9cb6c99f7.png">

**Comment by Vanessa219** [comment]
官网上也是 ？？？
![image](https://user-images.githubusercontent.com/970828/103720203-cc71ca00-5005-11eb-8d95-cf15948ebaef.png)
