### ISSUE TITLE
新增plantuml支持

### ISSUE THREAD

**Issue by qintang** [Vanessa219/vditor#885]
https://plantuml.com/zh/

```plantuml
@startuml component
actor client
node app
database db

db -> app
app -> client
@enduml
```

**Comment by qintang** [comment]
可参考：
https://github.com/markushedvall/plantuml-encoder 类库渲染

**Comment by qintang** [comment]
http://www.plantuml.com/plantuml 为开源国外服务器，没有被墙，速度还可以

**Comment by qintang** [comment]
https://github.com/cweijan/vscode-office 也推动跟新一下版本，在vs-code里面用着还不错

**Comment by Vanessa219** [comment]
不太会弄，欢迎 PR
https://github.com/Vanessa219/vditor/issues/116
