### ISSUE TITLE
vditor可否扩展支持简单的对齐功能呢？
如靠左对齐，居中对齐，靠右对齐

### ISSUE THREAD

**Issue by vicnoah** [Vanessa219/vditor#887]
### 你在什么场景下需要该功能？

vditor在功能上已经足够强大了，但缺少一些基本的传统富文本编辑器才有的功能。对于技术人员来说vditor功能已经足够了，但是对于普通人来说的话使用上还有部分问题。我的想法是扩展一些简单的排版语法，就可以直接用vditor替换传统的富文本编辑器了。目前富文本编辑器很多，但多少使用者有各方面的问题。

**Comment by Vanessa219** [comment]
虽然思源笔记引入了，但 Vditor 在没有标准或常用的语法之前，可能不会考虑引入。
