### ISSUE TITLE
toolbar区域，增加tooltip显示位置配置项

### ISSUE THREAD

**Issue by umi-soft** [Vanessa219/vditor#889]
### 使用场景

在弹出层组件中使用，toolbar已经置顶了，导致toolbar区域hover之后，tooltip无法显示

### 描述最优的解决方案 

简直增加配置支持，显示在下方，默认只有全屏状态，才会显示在下方

**Comment by Vanessa219** [comment]
可参见 https://ld246.com/article/1549638745630#options-toolbar 将  `tipPosition ` 设置为 `s`

**Comment by yzuxqz** [comment]
![image](https://github.com/Vanessa219/vditor/assets/64350892/ffe0adc9-f228-4321-980f-e37a1f817e7e)
全屏取消后 设置的位置失效
