### ISSUE TITLE
数学公式支持 MathJax

### ISSUE THREAD

**Issue by mlsjla** [Vanessa219/vditor#89]
因为mathjax公式用的比较多。

比如下面的就用不了了。
```
$$\begin {align*}
 &800(1+0.04t)=1000\\
  &\Rightarrow n=6.25years
 \end{align*}$$
```

**Comment by AGJackie** [comment]
同需要mathjax！想知道具体在哪个文档代码处能把katex配置改成mathjax配置

**Comment by Vanessa219** [comment]
mathjax 从包大小，渲染速度、效果都不如 katex，这个需求会在 bug 修复的差不多后再支持。

**Comment by mlsjla** [comment]
@Vanessa219   可以考虑以扩展方式增加，即可以选择性引入或开启。

因为首先考虑能用，兼容性， 其次是渲染速度和包大小。 毕竟现在算力和流量不算贵。

**Comment by 88250** [comment]
建议加入配置项，让用户能够选择所需的数学公式渲染引擎。

**Comment by AGJackie** [comment]
另外建议对mathjax的配置增加自定义宏（Macros）的支持。比如给一个输入框，可以输入mathjax的自定义macros，这样可以定义新命令。原因：mathjax可以满足大部分公式需求。但用到latex宏包的地方会无法使用，这种不满足的情形可以用macro的形式把latex宏包在mathjax上模拟出来。

以下为mathjax的配置项，Macros的部分是我对LaTeX精算宏包actuarialsymbol在mathjax中的模拟：

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  showProcessingMessages: false,
  messageStyle: "none",
  jax: ["input/TeX", "output/HTML-CSS"], 
    tex2jax: {
      preview: 'none',
      inlineMath: [ ['$','$'], ["\\(","\\)"] ],
      displayMath: [ ['$$','$$'], ["\\[","\\]"] ]
    },
  TeX: {
    TagSide: "left",
    Macros: {
      actuarialangle: ['{\\mkern1mu\\overline\{#1\\,\}\\kern-3mu\\lower-1mu\\small|}',1],
      angl: ['{\\actuarialangle\{#1\\mkern1mu\}}',1],
      angln: '{\\angl n}',
      anglk: '{\\angl k}',
      anglr: '{\\angl r}',
      term: ['{\\overset\{1\}\{#1\}:\\angl\{#2\}}',2],
      termxn: '{\\term\{x\}\{n\}}',
      pureendow: ['{#1:\\overset\{1\}\{\\angl\{#2\}\}}',2],
      pureendowxn: '{\\pureendow\{x\}\{n\}}',
      endow: ['{#1:\\angl\{#2\}}',2],
      endowxn: '{\\endow\{x\}\{n\}}',
      joint: ['{\\overline\{#1\}}',1],
      actsymb: ['{\\sideset\{_\{#1\\mkern3mu\}^\{#2\\mkern3mu\}\}\{^\{#4\}_\{#5\}}\{#3\}}',5],
      Ax: ['{\\actsymb\{#1\}\{#2\}\{A\}\{#3\}\{#4\}}',4],
      Axz: ['{\\actsymb\{#1\}\{#2\}\{\\bar\{A\}\}\{#3\}\{#4\}}',4],
      Axzz: ['{\\actsymb\{#1\}\{#2\}\{\\ddot\{A\}\}\{#3\}\{#4\}}',4],
      ax: ['{\\actsymb\{#1\}\{#2\}\{a\}\{#3\}\{#4\}}',4],
      axz: ['{\\actsymb\{#1\}\{#2\}\{\\bar\{a\}\}\{#3\}\{#4\}}',4],
      axzz: ['{\\actsymb\{#1\}\{#2\}\{\\ddot\{a\}\}\{#3\}\{#4\}}',4],
      Ex: ['{\\actsymb\{#1\}\{\}\{E\}\{\}\{#2\}}',2],
      px: ['{\\actsymb\{#1\}\{\}\{p\}\{\}\{#2\}}',2],
      qx: ['{\\actsymb\{#1\}\{\}\{q\}\{\}\{#2\}}',2],
      sx: ['{\\actsymb\{\}\{\}\{s\}\{\}\{#1\}}',1],
      sxz: ['{\\actsymb\{\}\{\}\{\\bar\{s\}\}\{\}\{#1\}}',1],
      sxzz: ['{\\actsymb\{\}\{\}\{\\ddot\{s\}\}\{\}\{#1\}}',1],
      Vx: ['{\\actsymb\{#1\}\{\}\{V\}\{\}\{#2\}}',2],
    }
  },

"HTML-CSS": {
    availableFonts: ["MathJax TeX"],
    preferredFonts: "MathJax TeX" }
});
</script>

<script type="text/javascript"
  src="https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>

加载上述mathjax自定义宏后，输入精算符号时需要使用的代码及其效果可以看这个帖子：
[寿险精算符号的mathjax代码](https://actuarygarden.cn/forum.php?mod=viewthread&tid=22)

**Comment by 88250** [comment]
@AGJackie 谢谢反馈，等后续会研究一下。

**Comment by AGJackie** [comment]
@88250 谢谢！
