### ISSUE TITLE
大纲渲染是否可以提供自定义点击事件

### ISSUE THREAD

**Issue by chenxiaobin** [Vanessa219/vditor#891]
### 你在什么场景下需要该功能？

使用 Vditor.preview + Vditor.outlineRender 渲染页面，滚动条出现在某个外围div容器上，大纲定位window.scrollTo无效，大纲项点击的时候可以提供自定义的事件，或者回调自行处理

**Comment by Hansanshi** [comment]
岔一下话题  Vditor.outlineRender是怎么用的   不知道参数contentElement 该获取哪个

**Comment by Vanessa219** [comment]
> 岔一下话题 Vditor.outlineRender是怎么用的 不知道参数contentElement 该获取哪个

就是你需要提取标题的内容所在的 dom 元素

**Comment by Vanessa219** [comment]
```js
after () {
          if (window.innerWidth <= 768) {
            return
          }
          Vditor.outlineRender(previewElement, outlineElement)
          if (outlineElement.innerText.trim() !== '') {
            outlineElement.style.display = 'block'
          }

          outlineElement.firstElementChild.addEventListener('click', (event) => {
            let target = event.target
            while (target && !target.isEqualNode(outlineElement)) {
              if (target.getAttribute("data-target-id")) {
                event.preventDefault();
                event.stopPropagation();
                window.scrollTo(window.scrollX, 10);
                break;
              }
              target = target.parentElement;
            }
          })
        }
```

**Comment by Hansanshi** [comment]
> > 岔一下话题 Vditor.outlineRender是怎么用的 不知道参数contentElement 该获取哪个
> 
> 就是你需要提取标题的内容所在的 dom 元素，具体可参见 https://b3log.org/vditor/demo

首先编辑模式是ir

我参考了下[demo](https://b3log.org/vditor/demo/preview-render.html) 获取previewElement 是
`const previewElement = document.getElementById('preview')`
我实际调用发现获取到的是`null`，这样获取不到。

我去浏览器上找了下  应该是这个元素  `document.querySelector('.vditor-ir').childNodes[0]`，
但是加载出来的标题都带有`#`号

**Comment by Vanessa219** [comment]
你可以查看 https://b3log.org/vditor/demo/preview.html
