### ISSUE TITLE
wysiwyg模式下，insertValue方法插入，没有进行预处理

### ISSUE THREAD

**Issue by umi-soft** [Vanessa219/vditor#892]
### 版本
- 3.7.5
### 编辑模式
- `wysiwyg` 所见即所得模式

### 描述问题

上传文件，通过insertValue方法，插入链接，链接无法自动编译，现状如下：
![image](https://user-images.githubusercontent.com/13619406/104298585-1c1d2d80-54ff-11eb-9342-9e088b1a83f0.png)

### 期待的结果
目前需要手动处理，上传成功之后，在感叹号之前（不论当前有没有空格），再增加一个空格，触发，才能直接获得图片预览效果

### 版本信息

* 版本：3.7.5
* 操作系统：mac os 10.14.5 (18F203)
* 浏览器：Chrome  87.0.4280.141

**Comment by Vanessa219** [comment]
不太清除你的用法，这样是好的。
![image](https://user-images.githubusercontent.com/970828/104463902-4baa6380-55ed-11eb-9843-3ea65d2014db.png)
