### ISSUE TITLE
大纲锚点无效

### ISSUE THREAD

**Issue by umi-soft** [Vanessa219/vditor#893]
### 编辑模式
- wysiwyg
### 描述问题
大纲锚点功能无效，我对比了官网文档中的大纲结构，官网文档大纲接口均为a标签，我本地的却是span标签

```
        <ul>
            <li>
                <span data-target-id="wysiwyg-微服务开发规范_34"><span>微服务开发规范</span></span>
            </li>
        </ul>
        <ul>
            <li>
                <span data-target-id="wysiwyg-编码规范_35"><span>编码规范</span></span>
            </li>
            <li>
                <span data-target-id="wysiwyg-后端代码规范_36"><span>后端代码规范</span></span>
                <ul>
                    <li>
                        <span data-target-id="wysiwyg-Java编码规范_37"><span>Java编码规范</span></span>
                    </li>
                </ul>
            </li>
            <li>
                <span data-target-id="wysiwyg-数据库设计规范_38"><span>数据库设计规范</span></span>
            </li>
            <li>
                <span data-target-id="wysiwyg-API设计规范_39"><span>API设计规范</span></span>
            </li>
        </ul>
```

### 期待的结果
目前不清楚为啥我的大纲是无效的，想了解一下是否具有特殊的配置？

### 版本信息

* 版本：3.7.5
* 操作系统：mac os
* 浏览器：谷歌 87

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/874#issuecomment-759458774

**Comment by umi-soft** [comment]
> 原因如下：
外层html和body元素，设置了height: 100%

**Comment by Vanessa219** [comment]
设置一下 options.height 为固定值试试

**Comment by umi-soft** [comment]
> 设置一下 options.height 为固定值试试

试了，无效，外层html和body元素这是为height: 100%, options.height 固定值，菜单点击无效

**Comment by Vanessa219** [comment]
无法重现 

https://user-images.githubusercontent.com/970828/105009872-fef3dc00-5a75-11eb-8f82-5d40613c229e.mp4

**Comment by umi-soft** [comment]
> 我的复现如下：

[我在gitee上提交了一个小demo](https://gitee.com/just-newbie/vditor-bug-repreduce)

[演示视频，网太慢，只能用百度云了](https://pan.baidu.com/s/1oM_mvYIcoyPrZwXiZ-EFxQ)
密码: awkt
------------
我尝试了，移除html和body元素下的，`height: 100%;` 或者  `overflow-x: hidden;` 都可以触发锚点

**Comment by Vanessa219** [comment]
你把编辑器的高度设置为 window.innerHeight 再试试

**Comment by umi-soft** [comment]
> 你把编辑器的高度设置为 window.innerHeight 再试试

演示demo里面，我试了下，无效

**Comment by Vanessa219** [comment]
是在 vditor 中设置

**Comment by umi-soft** [comment]
> 是在 vditor 中设置

有效
就算html和body元素存在，height: 100%;  overflow-x: hidden; 设置编辑器高度为window.innerHeight，也是有效的

**Comment by Vanessa219** [comment]
有效就好😊
