### ISSUE TITLE
BUG：复制表格粘贴到Excel格式错误

### ISSUE THREAD

**Issue by nshusr** [Vanessa219/vditor#896]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式

### 描述问题

原文
````````markdown
| col1 | col2 | col3 |
| ---- | ---- | ---- |
| 1    | 2    | 3    |
| 7    | 5    | 6    |
````````

以下是粘贴WPS表格后的内容

* `wysiwyg` 所见即所得模式
```markdown
\| col1 \| col2 \| col3 \|
--
\| ---- \| ---- \| ---- \|
\| 1    \| 2    \| 3    \|
\| 7    \| 5    \| 6    \|
```

* `ir` 即时渲染模式
```markdown
\| col1 \| col2 \| col3 \|
--
\| ------ \| ------ \| ------ \|
\| 1    \| 2    \| 3    \|
\| 7    \| 5    \| 6    \|
```

### 期待的结果

这两种模式下拷贝都有错误，分屏是正常的，希望这种情况下拷贝也能正确粘贴到表格里

### 截屏或录像

*上为 `wysiwyg` 所见即所得模式 下为 `ir` 即时渲染模式
![image](https://user-images.githubusercontent.com/45023042/104539536-b80e7c80-5658-11eb-9315-55fde0663ba3.png)

### 版本信息

* 版本：Vditor v3.7.5 / Lute v1.7.0
* 操作系统：Mac  WPS表格
* 浏览器：Chrome 版本 87.0.4280.141（正式版本） (x86_64)

**Comment by Vanessa219** [comment]
右键用这个试试
![image](https://user-images.githubusercontent.com/970828/104540409-5ea74d00-565a-11eb-8f5b-6216241b8cc0.png)

**Comment by nshusr** [comment]
@Vanessa219 
WPS表格：没有这项
![image](https://user-images.githubusercontent.com/45023042/104541866-64eaf880-565d-11eb-80eb-a610f8420200.png)
