### ISSUE TITLE
夜间模式

### ISSUE THREAD

**Issue by rfhits** [Vanessa219/vditor#897]
# 希望添加夜间模式

我不知道添加了这个特性没有啊，反正我是找不到，导致眼睛一直不舒服，vscode本身就是夜间模式，而这个白色背景和vscode配色有点冲突啊。。

希望在上面的toolbar加上一个可以用于选择夜间模式的按钮吧，我真滴找不到在哪里开启夜间模式。

**Comment by Vanessa219** [comment]
设置主题即可。具体可参见文档 https://ld246.com/article/1549638745630

**Comment by rfhits** [comment]
V大你好，谢谢你的链接，我看到了可以通过options更改主题，不过，我还有个问题，就是请问下，到哪里去改这个theme？
我找了好久也没找到，QAQ

**Comment by Vanessa219** [comment]
https://ld246.com/article/1549638745630#%E4%B8%BB%E9%A2%98
