### ISSUE TITLE
增加导出自定义配置能力

### ISSUE THREAD

**Issue by umi-soft** [Vanessa219/vditor#898]
### 你在什么场景下需要该功能？

> PDF文件导出

### 描述最优的解决方案 

> 1. 支持默认的页眉页脚信息配置
> 2. 如果有可能的话，点击工具栏PDF导出时，增加事件能力，导出时候设置页眉和页脚

**Comment by Vanessa219** [comment]
这个调用的是浏览器自带的，弹出后可自行选择
