### ISSUE TITLE
toubar版本的mac chrome环境下输入字符卡顿，并且会阻塞其他操作

### ISSUE THREAD

**Issue by PainterPuppets** [Vanessa219/vditor#899]
### 编辑模式

所有模式都有相似的问题
* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

toubar版本的mac chrome环境下输入字符卡顿，并且会阻塞其他操作
测试在safari环境下并不会有问题
可以注意到在输入的时候touchbar一直在切换状态，猜测卡顿可能和这个有关。

### 期待的结果

在chrome环境下输入不卡顿

### 截屏或录像

https://user-images.githubusercontent.com/22258327/104767002-6c69e900-57a6-11eb-8f03-0cf7bf4efd09.MP4

录像是在4秒时停止输入之后摁了command+a全选，在8秒的时候停止输入才全选到了所有字符
可以注意到在输入的时候touchbar一直在切换输入和chrome的状态，猜测卡顿可能和这个有关。

### 版本信息

* 版本：demo在线版本：https://b3log.org/vditor/demo/option-mode.html
* 操作系统：macOS Big Sur 11.1
* 浏览器：chrome 87

**Comment by Vanessa219** [comment]
看不到图片

**Comment by PainterPuppets** [comment]
https://user-images.githubusercontent.com/22258327/104807943-a1655280-581d-11eb-9b87-16f555a2685a.mp4

**Comment by PainterPuppets** [comment]
@Vanessa219 
不知道为什么无法在线播放，不过这里点下载的话貌似能正常看到
![image](https://user-images.githubusercontent.com/22258327/104807966-c78af280-581d-11eb-982b-e46b24bf1387.png)

**Comment by Vanessa219** [comment]
我这里没有 touch bar，看上去像输入法监听的问题。可以帮忙看看具体的问题么？

**Comment by Vanessa219** [comment]
如果有定位到问题，请继续留言
