### ISSUE TITLE
img标签图片无法显示

### ISSUE THREAD

**Issue by Hansanshi** [Vanessa219/vditor#900]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

所见即所得模式和即时渲染模式下，img标签的图片不会显示，分屏预览可以

````````markdown
<img src="https://pic2.zhimg.com/v2-362200716cdb1df41e2862dda6f4a35e_qhd.jpg?source=57bbeac9"/>
````````

### 版本信息

* 版本：3.7.5
* 操作系统：macOS
* 浏览器：FireFox & Chrome

**Comment by Vanessa219** [comment]
请用标准的 md 进行书写
`![](https://pic2.zhimg.com/v2-362200716cdb1df41e2862dda6f4a35e_qhd.jpg?source=57bbeac9)`

**Comment by Hansanshi** [comment]
@Vanessa219 

不算大问题，主要是直接复制网页内容进编辑器时发现，正常情况下也是按标准md语法写的。

但markdown语法标准也是要支持html标签的

这里更正一下issue  我发现其实vditor也是支持`<img>`标签在即时渲染模式下，

即时渲染模式下是不支持路径后面带参数的url，如下边这种
```
<img src="https://pic2.zhimg.com/v2-362200716cdb1df41e2862dda6f4a35e_qhd.jpg?source=57bbeac9"/>
```

而不带参数的，显示是没有问题的，如下

```
<img src="https://pic2.zhimg.com/v2-362200716cdb1df41e2862dda6f4a35e_qhd.jpg"/>
```

而对于分屏预览模式，这两种写法都是ok的

请问这是为什么  单纯好奇

**Comment by 88250** [comment]
@Hansanshi 感谢你细致的补充，这是一个解析器的缺陷导致，下个版本修复。
