### ISSUE TITLE
wysiwyg 和 ir 模式表格增加向上插入行和向左插入列

### ISSUE THREAD

**Issue by chenxiaobin** [Vanessa219/vditor#904]
### 你在什么场景下需要该功能？

编辑表格，写和很多，但是没办法在第一列前添加一列

### 描述候选解决方案

添加行列是否可以选择，向上添加，向下添加，向左添加，向右添加

**Comment by 88250** [comment]
你好，最新版这里应该没有问题：

![image](https://user-images.githubusercontent.com/873584/105463290-ce58b000-5cca-11eb-9001-f55a3d76ad4a.png)

**Comment by Vanessa219** [comment]
@88250 又搞错了吧，@chenxiaobin 说的应该是 vditor


@chenxiaobin 你说的是那一个模式？

**Comment by chenxiaobin** [comment]
@Vanessa219 wysiwyg模式下
