### ISSUE TITLE
编辑列表内容时出现的问题

### ISSUE THREAD

**Issue by jiakangning** [Vanessa219/vditor#910]
### 编辑模式

IR模式下编辑有序列表、无序列表时

一。序号问题
**Vditor**
![image](https://user-images.githubusercontent.com/34635641/106105940-c04dd800-617f-11eb-9c34-3fea56fa198f.png)

**TYPORA**
![image](https://user-images.githubusercontent.com/34635641/106105860-a0b6af80-617f-11eb-9482-ea178059a4fa.png)

**语雀编辑器**
![image](https://user-images.githubusercontent.com/34635641/106105811-8d0b4900-617f-11eb-9999-a5f423fe7476.png)

### 描述问题

在编写有序列表的时候，有时候每个标记下项新增其他内容的时候，序号标记无法删除，无法在编写类似于问题这样的列表内容的时候增加答案这样类似的选项

### 期待的结果

期待修复于 typora或者语雀类似的效果，通过【Backspace】键直接去除掉序号，并且内容自动添加为改列表项的子内容

### 截屏或录像

暂时无法提供录屏

### 版本信息

* 版本：v3.6.6
* 操作系统：win10
* 浏览器：chrome  88.0.4324.104（正式版本） （64 位）

二。光标问题

### 描述问题

在编写列表内容的时候，若新增子列表项，编写内容的时候光标会上移，导致内容追加到该列表项的末尾

### 期待的结果

修复光标上移问题

### 截屏或录像

按tab键添加子列表项的时候
![image](https://user-images.githubusercontent.com/34635641/106107336-c644b880-6181-11eb-8d70-d7f455010cc8.png)
输入内容的时候 （光标上移导致内容上移）
![image](https://user-images.githubusercontent.com/34635641/106107429-e2e0f080-6181-11eb-9d06-4c50174bd98c.png)

暂时无法提供录屏

### 版本信息

* 版本：v3.6.6
* 操作系统：win10
* 浏览器：chrome  88.0.4324.104（正式版本） （64 位）

**Comment by Vanessa219** [comment]
第二个问题没看明白，还是在哪里按 tab 键第二行会被拼接到第一行末尾？
