### ISSUE TITLE
大纲渲染问题

### ISSUE THREAD

**Issue by Hansanshi** [Vanessa219/vditor#912]
### 编辑模式

与编辑模式无关

### 描述问题

我将vditor的版本从3.7.5升级至3.7.6(3.7.7一样)，发现大纲渲染有问题。

这里指的是我自己的渲染，编辑器本身渲染自己的大纲没问题

代码如下
```js
<template>
  <div id="app">
        <div id="preview"></div>
        <div id="outline" ></div>
  </div>
</template>
<script>
import VditorPreview from 'vditor/dist/method.min'  
import 'vditor/dist/index.css'

export default {
   mounted() {
      const previewElement = document.getElementById('preview')
      const outlineElement = document.getElementById('outline')

      VditorPreview.preview(previewElement, `# 教程
## 普通内容
这段内容展示了在内容里面一些排版格式
`, {
  after: () => {
    VditorPreview.outlineRender(previewElement, outlineElement)
  }
})

  }
}
</script>
<style >
ul{
  list-style: none;
}
</style>

```

### 期待的结果

升级前的效果

### 截屏或录像

升级前效果(3.7.5)示例
![3.7.5](https://gitee.com/hansanshi/image/raw/master/20210130113003.png)

升级后效果(3.7.6)示例
![3.7.6](https://gitee.com/hansanshi/image/raw/master/20210130112801.png)

### 版本信息

* 版本：3.7.5 -> 3.7.6
* 操作系统：macOS
* 浏览器：FireFox&Chrome

请问是我代码问题还是bug

**Comment by Vanessa219** [comment]
这个需要引入 css 或者自己照着 demo 中写一下 https://b3log.org/vditor/demo/preview.html

**Comment by Hansanshi** [comment]
我已经引入了，否则之前就错了。

**Comment by Hansanshi** [comment]
前几个版本都是这样写 也是照着api写的，没有自己加什么东西

**Comment by Vanessa219** [comment]
加了css 的话会有这样的样式，你检查一下看看
![image](https://user-images.githubusercontent.com/970828/106354883-c2ef2f80-632f-11eb-885c-b2f0fc3c3df9.png)
