### ISSUE TITLE
子目录引用根目录图片无法显示

### ISSUE THREAD

**Issue by rfhits** [Vanessa219/vditor#914]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

根目录下新建个img文件夹，再在其他文件夹中引用这个img文件夹中的图片，格式如[/img/...]会出现无法显示图片的情况

### 期待的结果

希望能够显示图片
![wrong](https://user-images.githubusercontent.com/70683664/106347062-77298100-6270-11eb-8410-09ba8f2af7a3.jpg)

### 版本信息

* 版本：Markdown All in One 3.4.0
* 操作系统：Win10

### 其他信息

VS Code原生的编辑器可以显示图片。

**Comment by Vanessa219** [comment]
F12 看一下实际请求的路径

**Comment by rfhits** [comment]
按了F12没反应。
V大你那边可以显示照片吗？

V <notifications@github.com>于2021年1月30日 周六16:25写道：

**Comment by Vanessa219** [comment]
我没有用  vs 哟
