### ISSUE TITLE
视频：无法输入文字，在输入文字时里面的内容都会被错误的删除。版本号是3.6.6。官方发布的。

### ISSUE THREAD

**Issue by thinkido** [Vanessa219/vditor#915]
### 编辑模式

* `ir` 即时渲染模式

### 描述问题

无法输入文字，在输入文字时里面的内容都会被错误的删除。版本号是3.6.6。官方发布的。

### 截屏或录像
[视频：vditor编辑器0124号左右开始出现问题](https://reccloud.cn/u/cr1m2ig?action=client-auto-login)

### 版本信息

* 版本：3.6.6

**Comment by Vanessa219** [comment]
我重现不了。你到 https://b3log.org/vditor/demo 这个上面试试，排查下问题

**Comment by thinkido** [comment]
前面2个月正常，最近2周才出现的，也是概率性问题。哎，测试不出来就没办法了。网页中也只有编辑器，无其他代码干扰。如果有其他代码，那只有捕获键盘快捷键。

**Comment by Vanessa219** [comment]
嗯，可以逐一排查下
