### ISSUE TITLE
单页面多主题渲染缺陷

### ISSUE THREAD

**Issue by HerbertHe** [Vanessa219/vditor#916]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

在同一个页面中，如果同时需要渲染文章和评论的话，使用两套主题`preview`和`comment`来提升视觉体验。使用React封装为组件，以用时加载为原则进行渲染，只修改配置的`theme`配置项，vditor的样式插入是使用link标签的。

查看了源码的内容，感觉是跟下面的插入link的id属性有关系emmm

https://github.com/Vanessa219/vditor/blob/4559ebeff953ddb8901ab89f1a88c0b117c9fa40/src/ts/ui/setContentTheme.ts#L7

整个页面插入的主题。最后其实加载的只有最后一次请求的主题，如果为了避免样式冲突而在自定义主题中加入className，会导致之前的样式渲染失败，并不能支持多样式分离的需求

我感觉好像是为了减少网络请求而性能优化而这样做的

### 期待的结果

正常加载文件分离的不同样式

### 修改意见

id的话我感觉可以动态构建，例如`vditorContentTheme-${contentTheme}`，这样既可以减少网络请求，又可以支持不同的样式插入（不知道是否在其它DOM操作中用到了这个id，不太敢直接改这个PR）

### 版本信息

* 版本：v3.7.7
* 操作系统：Win10
* 浏览器：Edge(Chromium)

**Comment by Vanessa219** [comment]
目前机制不支持，可以在外层加一个 theme__xxx，然后用 css 重置来实现。
