### ISSUE TITLE
删除标题文件时，保留标题格式

### ISSUE THREAD

**Issue by akaylh** [Vanessa219/vditor#924]
### 你在什么场景下需要该功能？

目前在使用#号，输入标题时，如果此时因为某些原因要删除或者修改文字，删除到第一个文字时，会把#也删除，希望只删除文字，标题形式保留。

### 描述最优的解决方案 

如：### 这个一个标题

删除到“这”的时候，保留### ，重新输入文字，而不用再输入###，这样体验会更好。

### 其他信息

建议参考bear笔记的方式。

**Comment by Vanessa219** [comment]
`### ` 是可以保留的
https://user-images.githubusercontent.com/970828/107144188-77aecf80-6974-11eb-9f07-456d7468e7e6.mp4

**Comment by akaylh** [comment]
不好意思，我没描述清楚，在所见即所得模式下有这个问题，在即时渲染模式下是正常的。

**Comment by Vanessa219** [comment]
wysiwyg 下是不保留标记符的，因此没有办法显示出 `###`，还请见谅
