### ISSUE TITLE
老哥，vditor吞换行符，这个有没有解决办法呀？

### ISSUE THREAD

**Issue by shuangt** [Vanessa219/vditor#925]
这个在这两个issue中有提到：#464 ，#690 
但是都没有彻底解决的方法。使用场景还挺多的：在编辑的时候先把标题的版拍好，或者创建一个模板下次加载的时候继续编辑...

**Comment by 88250** [comment]
你好，目前暂时没有解决方案……我关闭了，有实现思路请随时交流，谢谢。
