### ISSUE TITLE
Mathjax 资源缺失及添加 license

### ISSUE THREAD

**Issue by leoleoasd** [Vanessa219/vditor#928]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

https://cdn.jsdelivr.net/npm/vditor@3.8.1/dist/js/mathjax/sre/sre_browser.js 404, 导致无法使用MathJax渲染公式。

### 截屏或录像
![image](https://user-images.githubusercontent.com/37735580/107885907-d0173b80-6f37-11eb-8830-b0608ce95584.png)

### 版本信息

* 版本：3.8.1
* 操作系统：MacOS
* 浏览器：最新Chrome

### 其他信息

之前好像还可以

**Comment by leoleoasd** [comment]
![image](https://user-images.githubusercontent.com/37735580/107887616-4620a000-6f42-11eb-9956-b0ced3c3feb6.png)
src/js/mathjax/tex-svg.js 中依赖了这个文件，但是并不存在

为什么不能使用npm依赖mathjax，而直接把源代码提交到仓库中呢？这么做违反了[MathJax的协议](https://github.com/mathjax/MathJax/blob/master/LICENSE)。

**Comment by leoleoasd** [comment]
Mathjax的Apache协议中要求，有Mathjax代码的地方要附一份Apache License与版权声明。大致在本仓库中搜索了一下，没有找到。

**Comment by leoleoasd** [comment]
我下载了一份mathjax,替换掉cdn中的dist/js/mathjax就好了。
如果简单的修复，只需要编译一份最新的mathjax（或者从[jsdelivr](https://www.jsdelivr.com/package/npm/mathjax)下载），提交到src/js/mathjax即可。

**Comment by Vanessa219** [comment]
以前是依赖 npm ，但是打包出来的懒加载不够优雅。可参考以前代码提交记录。
放在本地是为了让用户方便的统一切换 cdn。

**Comment by Vanessa219** [comment]
你的输入是什么会导致 404？这里无法重现

**Comment by leoleoasd** [comment]
> 你的输入是什么会导致 404？这里无法重现

mathjax模式输入任意内容

**Comment by Vanessa219** [comment]
没有这个请求，我先把 license 加了吧。多谢。
![image](https://user-images.githubusercontent.com/970828/107902942-d8e12f00-6f82-11eb-9bd0-0b9f660c575c.png)

**Comment by leoleoasd** [comment]
重新测试了一下
![image](https://user-images.githubusercontent.com/37735580/107903845-3c6c5c00-6f85-11eb-922e-b6b0626a4823.png)

右键渲染出来的mathjax公式，选择开启accessbility模式，mathjax就会加载一下4个js：
![image](https://user-images.githubusercontent.com/37735580/107903888-57d76700-6f85-11eb-952d-9f86ba8eb5f6.png)

en.js的路径是 https://cdn.jsdelivr.net/npm/speech-rule-engine@3.1.1/lib/mathmaps/en.js， 其他三个分别位于sre和a11y目录下。

**Comment by Vanessa219** [comment]
原来要这样操作，已经可以重现，稍后修复
