### ISSUE TITLE
增加“编辑器加载完成”回调

### ISSUE THREAD

**Issue by leoleoasd** [Vanessa219/vditor#929]
### 你在什么场景下需要该功能？

我在Vue中使用Vditor。编辑器中文字内容是异步加载的，文字加载完成时编辑器还未加载完成（lute.min.js还没加载完），此时调用setValue方法就会报错（`this.vditor.lute`是undefined）。

![image](https://user-images.githubusercontent.com/37735580/108120521-5a000980-70dc-11eb-8382-649643696613.png)
![image](https://user-images.githubusercontent.com/37735580/108120546-64ba9e80-70dc-11eb-8cfc-f7db1cab6752.png)

### 描述最优的解决方案 

如果可以提供编辑器加载完成回调，就可以在编辑器加载完成时调用setValue。类似loaded

### 描述候选解决方案

可以在异步加载完编辑器中文字内容后再加载编辑器本身，但是这样就相当于是让整个过程串行，效率低。

**Comment by Vanessa219** [comment]
放在 options.after 中再调用
