### ISSUE TITLE
从v3.7.3升级v3.8.1后点击大纲，控制台报错

### ISSUE THREAD

**Issue by TobiasTao** [Vanessa219/vditor#931]
### 描述问题
从v3.7.3升级v3.8.1后点击大纲报错：

![image](https://user-images.githubusercontent.com/37654563/108521854-1f2de980-7307-11eb-9b8a-89314e3987bb.png)

![image](https://user-images.githubusercontent.com/37654563/108522273-9ebbb880-7307-11eb-906b-d36a567012ee.png)

对应的vditor的源码位置是：
https://github.com/Vanessa219/vditor/blob/35cb610a3752afb6e9be1a0d32856b70a9e253c3/src/ts/toolbar/Outline.ts#L17

**Comment by Vanessa219** [comment]
我本地是正常的，麻烦贴一下配置项。

**Comment by TobiasTao** [comment]
我的问题😓，少看了Release note
