### ISSUE TITLE
请问在即时渲染模式下可以设置像typora那样按特定快捷键才会显示markdown源码吗？

### ISSUE THREAD

**Issue by luhggit** [Vanessa219/vditor#933]
首先感谢作者大大创造了这么优秀的作品，非常好用，感谢感谢！

然后，我想问一下，能不能实现这样一个功能：

在即时渲染的模式下，当光标移动有markdown标签的地方，不会马上显示markdown源码，而是像typora一样只有按快捷键才会显示

或者，把光标移上去显示源码做成一个开关，按特定快捷键可以进行开闭

当然，如果作者大大不方便修改的话，可以指示一下对应的源码位置吗，我可以自己研究一下改一下

**Comment by Vanessa219** [comment]
感觉 typora 应该是移动到粗体就会显示 mark 标记，并不需要按任何快捷键

**Comment by luhggit** [comment]
> 感觉 typora 应该是移动到粗体就会显示 mark 标记，并不需要按任何快捷键

@Vanessa219 我的typora是按"cmd+/"才会进入"Source Mode"，才会显示mark标记，再次按"cmd+/"就会退出"Source Mode"

注：Typora版本是`0.9.9.32.1 (4191)`

**Comment by Vanessa219** [comment]
源码模式可以使用 `ctrl+alt+9`
