### ISSUE TITLE
复制的文本中包含本地图片自动回调图片上传接口

### ISSUE THREAD

**Issue by ihewro** [Vanessa219/vditor#934]
### 你在什么场景下需要该功能？

我在typora上面写了一篇文章，文章中包含文字和插入的本地图片。

我希望复制整篇文章到vditor中，本地的图片会自动调用图片上传的接口并且替换成服务器的地址。

这个功能目前是支持的吗，之前看到的是如果文本中有外链的图片会自动调用。

**Comment by Vanessa219** [comment]
typora 里面的图片可以被使用 vditor 的服务器读取到就可以

**Comment by ihewro** [comment]
可以读取到 是 什么意思呢

我现在使用官方的vditor 也不能复制粘贴过去

![image](https://user-images.githubusercontent.com/20165605/109304130-c5816e00-7876-11eb-8794-f3f2a67aaec1.png)

**Comment by Vanessa219** [comment]
你这个要开启 typora 的图床功能就可以了

我愿人长久 <notifications@github.com> 于2021年2月26日周五 下午9:08写道：

**Comment by ihewro** [comment]
好的，搜索了一下，本地图片和文字混合粘贴上传本地图片目前还没有可实现的方案

**Comment by Vanessa219** [comment]
可以的，思源同步后点击复制到知乎/语雀/公众号都可以自动拉取图片的

我愿人长久 <notifications@github.com> 于2021年2月26日周五 下午11:47写道：
