### ISSUE TITLE
导出的HTML文件离线渲染

### ISSUE THREAD

**Issue by TobiasTao** [Vanessa219/vditor#935]
### 你在什么场景下需要该功能？

导出的HTML文件离线查看时渲染有问题

### 描述最优的解决方案 

希望像 typora 那样，导出的HTML  没有 `<link>` 和 `<script>`

**Comment by Vanessa219** [comment]
要点击工具栏上的导出按钮

tyc1998 <notifications@github.com> 于2021年2月26日周五 下午11:41写道：
