### ISSUE TITLE
导出的HTML文件应该是离线可用的

### ISSUE THREAD

**Issue by TobiasTao** [Vanessa219/vditor#937]
### 描述最优的解决方案 

希望可以是像 typora 那样，导出后的就是一个单纯的html文件，已经不关联其它js与css文件

**Comment by Vanessa219** [comment]
不关联的话是需要把js和css内联到html里面么？

**Comment by TobiasTao** [comment]
对，希望可以把css内联，js没有（html时js执行后导出的）

**Comment by Vanessa219** [comment]
这个要依赖的 js 比较多，内联不太合适
