### ISSUE TITLE
关于markdown文档导出与图片问题

### ISSUE THREAD

**Issue by qianzai** [Vanessa219/vditor#940]
### 你在什么场景下需要该功能？

由于我并没有发现，markdown文档导入功能，当我将一个markdown文档复制过来时候，图片是电脑的全局路径，我想能否有放到文档的相对路径

![image.png](https://gitee.com/BuZM/images/raw/master/PicGo/20210303103705-mrntpoy-image.png)

> 当我想把这个markdown文档发给别人时，图片的引用地址是一个麻烦问题

### 描述最优的解决方案

希望可以在文档的相对路径创建一个文件夹，然后再根据文档名，在这个文件夹的相对路径创建对应的文件夹来存放图片

![image.png](https://gitee.com/BuZM/images/raw/master/PicGo/20210303102038-ckwjdoj-image.png)

![image.png](https://gitee.com/BuZM/images/raw/master/PicGo/20210303102652-akptq11-image.png)

**Comment by 88250** [comment]
你好，请使用 TextBundle 导出，批量 md 导出的话需要手动拷贝 assets 目录，谢谢。

**Comment by qianzai** [comment]
不是批量，我只想导出一个文档，而要复制整个assets文件夹？？

**Comment by 88250** [comment]
一个文档的话推荐用 TextBundle 导出。
