### ISSUE TITLE
插入图片后执行insertValue("xxx")不起作用

### ISSUE THREAD

**Issue by luhggit** [Vanessa219/vditor#941]
### 编辑模式
`ir` 即时渲染模式

### 描述问题
粘贴图片触发upload.handler，上传图片到服务器（返回图片url）后，调用vditor.insertValue插入图片标签，再调用vditor.insertValue("\n\nxxx")后，图片能正常显示，但"\n\nxxx"插入到了图片前面

### 期待的结果
"\n\nxxx"能插入到图片后面，即换行后再显示"xxx"

### 版本信息

* 版本：vditor v3.8.1
* 操作系统：MacOS
* 浏览器：Edge v87.0.664.66

### 其他信息

upload代码如下：
```javascript
upload: {
      url: 'abc',
      handler(files) {
          files.forEach(file => {
              if (!file.type.match(/^image\/(gif|jpe?g|a?png|bmp)/i)) {
                  return;
              }
              // 上传图片
              me.uploadToServer(file, (res) => {
                  let imgMdStr = `![](${res})`
                  // 插入图片
                  me.vditor.insertValue(imgMdStr)
                  // 进行换行 ————> 注：不起作用
                  me.vditor.insertValue("\n\nxxx")
                  // 保存数据
                  me.save()
              });
          })
      }
  },
```
截图如下：
![image](https://user-images.githubusercontent.com/15810028/109827273-8ab47700-7c76-11eb-82e7-dee1f6cf190f.png)

**Comment by Vanessa219** [comment]
图片处理较为复杂，不好弄的话可以使用默认的方法，数据可使用 format 方法进行格式化。
