### ISSUE TITLE
即时渲染模式行内代码粘贴文本报错

### ISSUE THREAD

**Issue by luhggit** [Vanessa219/vditor#943]
### 编辑模式
* `ir` 即时渲染模式

### 描述问题
即时渲染模式下，在行内代码（如`1245`）中粘贴文本会报错，如把"3"插入到行内代码`1234`的中间

### 期待的结果
处理报错

### 截屏或录像
报错如图：
![image](https://user-images.githubusercontent.com/15810028/110201810-fe859800-7e9f-11eb-97a2-a772511d6cb7.png)
![image](https://user-images.githubusercontent.com/15810028/110201834-1bba6680-7ea0-11eb-81a5-b58f79a5922a.png)

### 版本信息

* 版本：v3.8.1
* 操作系统：MacOS
* 浏览器：Edge

**Comment by Vanessa219** [comment]
目前不支持 Edge，谢谢。
