### ISSUE TITLE
【Suggestion】支持单纯的渲染模式（文章类型展示用）？

### ISSUE THREAD

**Issue by Jairwin-L** [Vanessa219/vditor#945]
1. 支持单纯的渲染模式（文章类型展示用）？
2. 支持less引入？

**Comment by Vanessa219** [comment]
感谢建议

1. js 包不大，所以就不分开了
2. 目前使用的 sass

**Comment by Vanessa219** [comment]
感谢建议

1. js 包不大，所以就不分开了
2. 目前使用的 sass
