### ISSUE TITLE
Improve the delete behavior in the list item after the code block

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#946]
![vditor1](https://user-images.githubusercontent.com/15811943/110242454-df2c5080-7f1b-11eb-92db-2ada35d0158f.gif)

**Comment by Vanessa219** [comment]
After enter, cursor move to code block?

**Comment by jakekwak** [comment]
This is the case when I want to add to the first list, but I want to cancel it using the backspace
