### ISSUE TITLE
How to close vditor in vscode edit！！！

### ISSUE THREAD

**Issue by Dreamupers** [Vanessa219/vditor#947]
![image](https://user-images.githubusercontent.com/49057488/110262689-67c7f100-7fef-11eb-851e-b524f178c3d5.png)

**Comment by Vanessa219** [comment]
`destroy`

**Comment by Dreamupers** [comment]
![image](https://user-images.githubusercontent.com/49057488/110570917-b1504180-8191-11eb-9e8b-03a987bd7c13.png)
I found that， thanks.
