### ISSUE TITLE
在代码中有注释的情况下,文件解析会报错

### ISSUE THREAD

**Issue by Muromi-Rikka** [Vanessa219/vditor#948]
### 编辑模式

所有

### 描述问题

在代码中有注释的情况下,文件解析会报错

````````markdown
<!-- # 1611817863629 -->
````````

### 期待的结果

编辑器不报错

### 截屏或录像

<img width="577" alt="error" src="https://user-images.githubusercontent.com/22149502/110274855-ca7ab600-800a-11eb-8b6b-65802f317140.png">

### 版本信息

* 版本：latest
* 操作系统：macOS & Windows
* 浏览器：Chrome & Safari

### 其他信息

因为查看不到解析器源码,无法定位错误原因

**Comment by Vanessa219** [comment]
这个错误可能是其他问题导致的，解析错误的话，界面就不会显示了。

![image](https://user-images.githubusercontent.com/970828/110330139-6252c100-8058-11eb-95ad-ce72e51db082.png)

**Comment by Muromi-Rikka** [comment]
这里你复制的是code包含下的注释,直接使用注释我在官网demo上依旧得到报错,鼠标不点击的情况下是不显示的
<img width="964" alt="error-1" src="https://user-images.githubusercontent.com/22149502/110440713-eefe8d00-80f3-11eb-994a-34b58b3f5b5b.png">
但也有可能此种写法不符合markdown规范,感觉无需考虑了

**Comment by Vanessa219** [comment]
不太清楚你是怎么粘贴的，还是没有办法重现。

![image](https://user-images.githubusercontent.com/970828/110730715-e7f28e80-825b-11eb-8ee7-08ff3f9845f6.png)
