### ISSUE TITLE
3.8.* 大纲渲染方法outlineRender()生成的大纲无法点击

### ISSUE THREAD

**Issue by zmister2016** [Vanessa219/vditor#952]
使用方式：https://www.jsdelivr.com/package/npm/vditor 下载的包通过`<script>`标签引入。

3.7.1 下调用`Vditor.outlineRender()`渲染的文档大纲元素中`span`标签的`data-target-id`属性有值，如下图所示：

![](http://mrdoc.zmister.com/media/202103/2021-03-13_221930.png)

但是在 3.8.1 、3.8.2 下测试，`data-target-id`属性没有值，如下图所示：

![](http://mrdoc.zmister.com/media/202103/2021-03-13_222230.png)

这导致在 3.8.3 下渲染的大纲无法点击跳转。

不知道是我使用方式不对还是Bug？

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/949 已修复，等发布
