### ISSUE TITLE
增加对代码块选中代码整体缩进的快捷键tab/shift tab

### ISSUE THREAD

**Issue by lihaixing** [Vanessa219/vditor#954]
### 你在什么场景下需要该功能？

复制代码到编辑器中，代码样式从第二行开始会缩进有问题，这时候就需要shift tab对整个代码减小缩进，可是不支持

### 描述最优的解决方案 

针对代码块，对选中得代码可进行 tab/shift+tab增加、较小缩进的快捷键，

### 描述候选解决方案

无

### 其他信息

![image](https://user-images.githubusercontent.com/6269419/112247930-0dd25700-8c90-11eb-99c7-8a4f97ba6b08.png)

**Comment by Vanessa219** [comment]
目前只能在 IDE 里面缩进好了再粘贴

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/110
