### ISSUE TITLE
所见即所得模式下的任务列表Bug

### ISSUE THREAD

**Issue by ydq** [Vanessa219/vditor#96]
V大D大新年快乐，我又来报告Bug了，直接上图：

![vditor-bug](https://user-images.githubusercontent.com/8097340/73535962-cc656380-445f-11ea-812d-620968e26d6e.gif)

如图所示，在所见即所得模式下，任意空行连续点击任务列表出现与**有序** / **无序**列表行为不一致的现象，会出现许多堆叠的checkbox框

**vditor** 版本：`2.1.5`

- 预期效果：同**有序** / **无序**列表一样，多次点击出现toggle效果

---

<details>
<summary>另外1: 貌似 vditor 版本2.1.5  在markdown 编辑 / 预览 模式下，无法正确渲染 任务列表【点我看详情】</summary>

![image](https://user-images.githubusercontent.com/8097340/73537578-c6718180-4463-11ea-8668-b04262f81e82.png)

</details>

<details>
<summary>另外2: 所见即所得模式下的 有序 / 无序 按钮 在所见即所得模式下使用上有点混乱【点我看详情】</summary>

- 当光标在**有序 / 无序**所在行且后面没有内容时，点击**有序 / 无序**按钮 可以互相切换列表类型或者toggle
- 当光标在**有序 / 无序**所在行且后面有内容时，点击**有序 / 无序**按钮 后第一次是切换列表类型，后面则是先新增一行，然后同时在新的一行切换了列表类型，不看markdown源码单纯从所见即的操作上来看比较令人费解，希望能整体统一一下操作逻辑。
- 而且**任务列表**在功能分类上隶属于列表的一种的话，三种类型的操作按钮应该统一体验~~

</details>

**Comment by 88250** [comment]
1. 任务列表重复添加的问题稍后修复
2. 任务列表内容为空时不渲染为 input checkbox，渲染为 ul 
   ![image](https://user-images.githubusercontent.com/873584/73538865-0ab25100-4467-11ea-85da-3115b9b2982a.png)
   不过样式不对
3. 这个问题有点复杂，但应该有解

感谢反馈，新年快乐！

**Comment by ydq** [comment]
@Vanessa219  V大 

堆叠checkbox的问题 貌似没有完全解决哦~ 

当无聊手贱疯狂点击的时候还是会出现checkbox堆叠的情况

![vditor-bug](https://user-images.githubusercontent.com/8097340/73607991-39136600-45f8-11ea-8eee-31878454d153.gif)

**Comment by 88250** [comment]
她说又改了一下，应该好了。社区线上还没发布。
