### ISSUE TITLE
是否可以改变 字体颜色、段落间距、背景颜色

### ISSUE THREAD

**Issue by zxf5115** [Vanessa219/vditor#960]
### 是否可以改变 字体颜色、段落间距、背景颜色

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

````````markdown

我现在客户是一些老师，他们电脑知识比较差，是否可以在工具区加入：字体颜色、段落间距、背景颜色，修改按钮？
或者是否有第三方插件推荐下
````````

### 期待的结果

工具栏加入：字体颜色、段落间距、背景颜色按钮

### 版本信息

* 版本：3.6.0
* 操作系统：win10
* 浏览器：firefox

**Comment by Vanessa219** [comment]
标准 md 没有这些语法，目前不会支持。

**Comment by koibi2** [comment]
建议用富文本编辑器
