### ISSUE TITLE
代码编写不友好，不支持Tab等基本操作

### ISSUE THREAD

**Issue by lu-tianyu** [Vanessa219/vditor#962]
首先，感谢开源优秀的markdown编辑器。满足了我大部分的需求，有1、2个小点如果能改进或者修正就更好了。谢谢

1. 最终要的是，tab的支持啊，包括shift+tab的回退。这两个功能在代码编辑时尤其的重要，是广大开发同学的习惯了。如果能支持，就很棒！（其他类似的比如ctrl + x剪切当前一行，这类习惯已经）
2. 在即可渲染模式下，没有找到任何能修改table的方式，比如新增一行一类的。（还有我看已经有人开的issue，无法复制多个单元格，然后粘贴自动匹配对应个数）

比较影响使用的就是这两个，麻烦看下，是否可以支持下，谢谢，祝越来越火

**Comment by Vanessa219** [comment]
table 可以使用快捷键，目前主要精力在思源笔记上，tab 可能需要后续才能完善。感谢建议。

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/110
