### ISSUE TITLE
支持Prism

### ISSUE THREAD

**Issue by Teeoo** [Vanessa219/vditor#964]
### 你在什么场景下需要该功能？

代码高亮

### 描述最优的解决方案 

希望同时支持Prism和Highlight

### 描述候选解决方案

Highlight.js

### 其他信息

Prism 是一个轻量级，可扩展的语法着色工具，符合 Web 标准。

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/issues/776
