### ISSUE TITLE
Whether theme customization or editing styles are supported

### ISSUE THREAD

**Issue by jahnli** [Vanessa219/vditor#965]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

Whether theme customization or editing styles are supported
I did not find this configuration
````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
````````

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

**Comment by Vanessa219** [comment]
https://ld246.com/article/1549638745630#%E4%B8%BB%E9%A2%98
