### ISSUE TITLE
增加切换不同编辑模式的快捷键

### ISSUE THREAD

**Issue by champagneo** [Vanessa219/vditor#966]
希望能像Typora一样，可以通过组合键（如Ctrl + /）切换编辑模式，并且加入源码模式。

实现方法我想可以通过识别组合键动作，修改编辑模式相关参数的方式来实现该功能。

**Comment by Vanessa219** [comment]
目前已经有快捷键了，只是暂不支持配置
源码模式可以使用较为接近的 sv 模式
