### ISSUE TITLE
如何动态修改options

### ISSUE THREAD

**Issue by jahnli** [Vanessa219/vditor#967]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题
![image](https://user-images.githubusercontent.com/20943608/113662373-8991c200-96da-11eb-8736-965149c652a7.png)
extraData的key是需要上传文件之后才能拿到，请问如何动态配置options

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
````````

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

**Comment by Vanessa219** [comment]
```
vditor.vditor.options.upload.extraData
```

**Comment by Innei** [comment]
> ```
> vditor.vditor.options.upload.extraData
> ```

这种方式直接改，并没有作用到现有实例上

**Comment by Vanessa219** [comment]
setHeaders

**Comment by snowchenlei** [comment]
> setHeaders

这个怎么使用，有例子吗
