### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated

### ISSUE THREAD

**Issue by jahnli** [Vanessa219/vditor#968]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

我使用的是vite2 + typescript + vue3
我运行时会提示
Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
````````

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

**Comment by Vanessa219** [comment]
在首次加载 lute 时，使用了同步来保证多实例下的一次加载。这个警告可以忽略。
