### ISSUE TITLE
vscode里可以和vim keymaps 一起用吗.....

### ISSUE THREAD

**Issue by WillDawnlll** [Vanessa219/vditor#969]
### 你在什么场景下需要该功能？

vscode里的office viewer 插件中的 vditor.........因为v开头的名字....以为有vim的键映射

**Comment by Vanessa219** [comment]
没有这个功能哟

**Comment by sisrfeng** [comment]
以后会有嘛?
刚需啊
https://github.com/typora/typora-issues/issues/187

**Comment by 88250** [comment]
@sisrfeng 不会有。
