### ISSUE TITLE
上传图片时的光标问题

### ISSUE THREAD

**Issue by jahnli** [Vanessa219/vditor#973]
### 编辑模式

wysiwyg
* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

目前我使用的自定义上传，当我尝试将上传成功的图片insertValue时，光标始终在图片的前方，是否可以配置或者调整光标始终在图片后方
````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
````````

### 截屏或录像
![5856e66b-13c0-450c-af7d-c06a85903bba](https://user-images.githubusercontent.com/20943608/114052428-a25bcc80-98c0-11eb-813c-69f2d38dd978.gif)

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

**Comment by Vanessa219** [comment]
insertValue 之前需要先设置 range 的位置，上传建议使用 upload 及其相关的方法。
