### ISSUE TITLE
所见即所得模式列表里的行级元素间的空格会被删除

### ISSUE THREAD

**Issue by zaaack** [Vanessa219/vditor#974]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式

### 描述问题

列表 + 文本 + 空格 + 链接(或代码) 会导致文本和链接之间的空格丢失

````````markdown
* Using [Custom Text Editor](https://code.visualstudio.com/api/extension-guides/custom-editors#custom-text-editor)
````````

编辑之后普通文本和链接之间的空格会丢失

### 期待的结果

getValue() 时获取到的依然是 
```md
* Using [Custom Text Editor](https://code.visualstudio.com/api/extension-guides/custom-editors#custom-text-editor)
```

### 截屏或录像

![Untitled5](https://user-images.githubusercontent.com/5233940/114144062-7df70300-9947-11eb-91e2-442ae873125f.gif)

### 版本信息

* 版本：Vditor v3.8.4
* 操作系统：macOS 
* 浏览器：chrome

**Comment by 88250** [comment]
在 https://github.com/88250/lute/issues/149 中排查解决，谢谢。

**Comment by 88250** [comment]
目前我在 IR 模式下重现不了，WG 模式已经确认是缺陷。

**Comment by zaaack** [comment]
@88250 ir 我刚才也没复现，可能是写错了
