### ISSUE TITLE
mermaid 编辑时带语法高亮和检测

### ISSUE THREAD

**Issue by zaaack** [Vanessa219/vditor#975]
### 你在什么场景下需要该功能？

mermaid 编写没有高亮和语法检测，不太友好

### 描述最优的解决方案 

参考 mermaid-live-editor https://github.com/mermaid-js/mermaid-live-editor

**Comment by Vanessa219** [comment]
![image](https://user-images.githubusercontent.com/970828/114312652-eef41180-9b25-11eb-877f-d3a178b9aae6.png)
这个高亮的有点不太好，而且要嵌入另外一个编辑器。
