### ISSUE TITLE
uninstall Markdown extension on VScode.

### ISSUE THREAD

**Issue by Hurley-Ng** [Vanessa219/vditor#977]
hi,

I had have issued after I install this Markdown extension on my VScode editor. I have to uninstall this extension because it has affected another extension I have, after I uninstall this one still get stuck on my VScode. Can you help me out with how to totally uninstall this extension, I have attached a screenshot of this for more instructions from you guy. thanks

Hurley
<img width="1006" alt="Screen Shot 2021-04-13 at 11 28 46" src="https://user-images.githubusercontent.com/77094397/114483276-6b344500-9c4b-11eb-8944-00c7b6584ce1.png">

### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
````````

### 版本信息

* 版本：
* 操作系统：
* 浏览器：

**Comment by 88250** [comment]
Hello, please try to contact the author of the VSCode plugin, thanks.

**Comment by EazycTee** [comment]
FYI...
https://github.com/Vanessa219/vditor/issues/1072
