### ISSUE TITLE
块引用格式化算法优化

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#98]
Is this the garbage?
`>>>`
`>>`

![Screen Shot 2020-02-02 at 11 34 36 PM](https://user-images.githubusercontent.com/15811943/73628192-2d826800-4615-11ea-946a-ac651005de79.png)

Thanks for improving the UI at Desktop

**Comment by 88250** [comment]
These `>` produced by Lute's markdown format handling. Maybe we can find a better algorithm to resolve it, maybe can not 😂

**Comment by 88250** [comment]
Transfered this issue to Lute https://github.com/88250/lute/issues/18
