### ISSUE TITLE
图片上传后如何插入到正文

### ISSUE THREAD

**Issue by linxiaotao1987** [Vanessa219/vditor#983]
![image](https://user-images.githubusercontent.com/16025998/115215672-51f13400-a136-11eb-9507-c87f07adb418.png)

**Comment by XGiton** [comment]
发现可以用下面这个方式操作：
let insertValue = `![${$file.name}](${imgUrl})`;
this.contentEditor.insertValue(insertValue);

**Comment by u19900101** [comment]
> 发现可以用下面这个方式操作： let insertValue = `![${$file.name}](${imgUrl})`; this.contentEditor.insertValue(insertValue);

请问一下当插入为img标签时，为啥不能自己结束块 #1120

**Comment by Vanessa219** [comment]
没问题的话我就关闭 issue 了

**Comment by u19900101** [comment]
> 没问题的话我就关闭 issue 了

没问题了，在末尾加了两个\n就好了但是不知道原理~~~~
