### ISSUE TITLE
有序列表无法正常显示

### ISSUE THREAD

**Issue by Macesuted** [Vanessa219/vditor#989]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

````````markdown
1. 123
2. 234
3. 435
````````

### 期待的结果

显示正常的有序列表。

### 截屏或录像

![image](https://user-images.githubusercontent.com/57275149/116236415-a0837b80-a791-11eb-9094-b360dd0274d4.png)

### 版本信息

* 版本： Vditor 3.8.4
* 操作系统： Windows 10
* 浏览器： Chrome
*

**Comment by Vanessa219** [comment]
https://ld246.com/guide/markdown 这个上面是好的，你看一下是不是样式被重置了
